### ISSUE TITLE
MuJoCo render incompatible with newer versions of MuJoCo Py

### ISSUE THREAD

**Issue by AdamGleave** [openai/gym#1000]
MujucoEnv's render method assumes the viewer has a 500x500 display. If it is larger than this, it will select pixels from the bottom-left corner when called with `mode='rgb_array'`. There's a comment which suggests this size used to be the default for mujoco-py, but with the latest mujoco-py it defaults to the screen resolution: see opengl_context.pyx:89 in _create_window.

This issue can be fixed by adding the line `self.viewer.opengl_context.set_buffer_size(W, H)` in `_get_viewer` to manually specify the desired frame size. (Oddly, I need to set both dimensions to twice the desired size, I think due to an overzealous workaround for Mac's on opengl_context.pyx:113.) But this is pretty hacky. 

I'm a little confused why we're rendering anything on the screen for `render(mode='rgb_array')`, which is typically used for video capture in a batch setting. In particular, MjViewer has the annoyance of showing an overlay menu by default, rarely desired for video capture. It might be better to use `mujoco_py.MjRenderContextOffscreen` instead for this purpose. If we allow render to be called with different modes, however, this would require making a breaking change to the interface for `viewer_setup` (or some hacking to make `self.viewer` point to different objects depending on the last call).

I'd be happy to work on a pull request to address these issues if we can agree on a good way forward for this.

**Comment by AdamGleave** [comment]
A more serious issue is that close() calls the method finish() on the viewer which no longer exists in the latest mujoco_py version. To reproduce:

1. Install latest version of mujoco-py (1.50.1.56 from PyPi, same as Git master)
2. Run:
`
import gym                                                                                                                                                                                            

env = gym.make('Reacher-v2')
ob = env.reset()
env.step([0.0, 0.0])
env.render()
env.close()
`
3. Output:
`
Creating window glfw                                                                                                                                                                                  
Traceback (most recent call last):                                                                                                                                                                    
  File "test_mjc.py", line 8, in <module>
    env.close()
  File "/home/adam/dev/gym/gym/core.py", line 288, in close
    return self.env.close()
  File "/home/adam/dev/gym/gym/envs/mujoco/mujoco_env.py", line 115, in close
    self.viewer.finish()
AttributeError: 'MjViewer' object has no attribute 'finish
`

I assume there's some version of mujoco-py where this all worked -- we could perhaps pin the Gym requirements to that version as a workaround, while a more permanent fix is developed?

**Comment by AdamGleave** [comment]
Could @matthiasplappert or another Gym committer working on MuJoCo take a look at this? I've had several people e-mail me as a result of this issue, so this seems to be a common problem for people. My PR provides a workaround, but a proper fix will require a coordinated change between gym and mujoco_py.

**Comment by AdamGleave** [comment]
Hi Matthias,

1. Apologies about the messy PR -- this was a rebase gone wrong when I incorporated some recent changes in Gym master. This is fixed now (in PR #1013).
2. This is also my impression -- I was hesitant to make this modification as it would be a breaking API change for any end-users that subclass MujocoEnv. Although it is easy enough for people to fix.
3. You're right, there seems to be a lot of code duplication between RobotEnv and MujocoEnv. I'm not sure how to fix this (without resorting to multiple inheritance) given RobotEnv inherits from GoalEnv.

Encapsulating the logic to switch between viewers in a meta viewer could be more elegant, but I think is fundamentally the same approach as my workaround, and so does still feel less clean to me than your proposal (2).

**Comment by kirk86** [comment]
Hi folks, I still face the issue of `env.close()` not properly working with `mujoco`. I have the latest gym and latest mujoco installed `mujoco 1.5.0`.

**Comment by tianheyu927** [comment]
Is there any progress on fixing `env.close()`?

**Comment by LonelyCloud97** [comment]
MjViewer is implemented by GLFW, so maybe you can write env.close() by yourself.  
```python
import glfw
import gym
from types import MethodType


# override env.close()
def env_wrapper(env):
    def close(self):
        if self.viewer is not None:
            glfw.terminate()
            self.viewer = None

    env.unwrapped.close = MethodType(close, env.unwrapped)
    return env


def test():
    env = env_wrapper(gym.make("Reacher-v2"))
    env.reset()
    for _ in range(50):
        env.render()
        env.step([0, 0])
    env.close()
    
    
if __name__ == '__main__':
    test()

```
It works well with no error, but I am not sure if there are some side effects.
```
"C:\Program Files\Python36\python.exe" D:/File/LAB/project/fix_problem.py
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
Creating window glfw

Process finished with exit code 0
```

**Comment by AdamGleave** [comment]
@JiangengDong will this close all GLFW windows from the application? (One can have multiple environments in the same process.)

**Comment by JiangengDong** [comment]
@AdamGleave Just as you say, `glfw.terminate()` will close all windows.  A better method is to use `glfw.destroy_window()` instead.

New version:
```python
def close(self):
    if self.viewer is not None:
        glfw.destroy_window(self.viewer.window)
        self.viewer = None
```

Thanks for your advice.
