### ISSUE TITLE
Monitor does not close the wrapped env

### ISSUE THREAD

**Issue by gutfeeling** [openai/gym#1002]
### Gym version
0.10.5

### Description
Monitor's `close()` method does not close the wrapped env. 

### Code to reproduce the issue

```python
import gym
from gym.wrappers import Monitor

env = gym.make("CartPole-v0")
env = Monitor(env, "/tmp/cartpole_experiment_1")

observation = env.reset()
while True:
    action = env.action_space.sample()
    observation, reward, done, info = env.step(action)
    if done:
        break
env.close()
```
The rendering window does not close when the code exits. Is this intended behavior?

### Solution 

I solved this issue by calling `close()` on the wrapped env at the end of the script.

```python
env.env.close()
```

This is a hacky solution. Perhaps a better way is to call `self.env.close()` within the `close()` method of the Monitor, defined in gym/gym/wrappers/monitor.py.

**Comment by christopherhesse** [comment]
Looks like this was fixed in https://github.com/openai/gym/pull/1023
