### ISSUE TITLE
Done turn into true in Half Cheetah-v1 envs

### ISSUE THREAD

**Issue by Lukeeeeee** [openai/gym#1003]
The source code of Half Cheetah-v1 step function is as follow:
```
    def _step(self, action):
        xposbefore = self.model.data.qpos[0, 0]
        self.do_simulation(action, self.frame_skip)
        xposafter = self.model.data.qpos[0, 0]
        ob = self._get_obs()
        reward_ctrl = - 0.1 * np.square(action).sum()
        reward_run = (xposafter - xposbefore)/self.dt
        reward = reward_ctrl + reward_run
        done = False
        return ob, reward, done, dict(reward_run=reward_run, reward_ctrl=reward_ctrl)
```

Which means the done should be always false, but during the test, some times the it will return True.
The print of the code: https://gist.github.com/Lukeeeeee/1996360023af13b2e4256382b49c03c3

Test code I used:

```
import gym

a = gym.make('HalfCheetah-v1')
state = a.reset()

for i in range(10000):
    action = a.action_space.sample()
    state, reward, done, _ = a.step(action)
    print(i, reward, done)

```

Can someone give any explanation of it? Thanks!

**Comment by gutfeeling** [comment]
Gym envs are wrapped by the TimeLimit wrapper defined in gym/gym/wrappers/time_limit.py. This wrapper overrides the `step()` function of the wrapped env. It seems like HalfCheetah has a time limit of 1000. That's most likely why the env is returning `done = True` at that point.

**Comment by Lukeeeeee** [comment]
@gutfeeling yes, found out the this . So close the issue now. Thanks,
