### ISSUE TITLE
New robotics environments error

### ISSUE THREAD

**Issue by lpsantao** [openai/gym#1005]
I've tried running this code:
`import gym`
`env = gym.make('HandManipulateBlock-v0')`
`env.reset()`
`env.render()`

and the following error is generated:
```
File "wrappers.pxi", line 2528, in mujoco_py.cymj.PyMjData.get_joint_qpos
TypeError: 'numpy.int32' object is not iterable
```
this happens only with every new robotics environment. Any suggestions?
I'm using python 3.6.5 and Windows 10

**Comment by matthiasplappert** [comment]
This is  an issue with `mujoco-py`, which apparently doesn't correctly work on Windows 10. Could you please open an issue there? http://github.com/openai/mujoco-py
