### ISSUE TITLE
doc: Gopher-v0 state shape is wrong

### ISSUE THREAD

**Issue by makdoudN** [openai/gym#1006]
Hi,

I do not know if it is worth opening an issue but the size of Gopher-v0 is mentioned in the documentation to be (210, 160, 3) but the shape is (250, 160, 3)

gym version: ***0.10.5***

Thanks for your work in this awesome library :)

**Comment by christopherhesse** [comment]
Thanks for the bug report!  It looks like this environment has been removed though.
