### ISSUE TITLE
"ImportError: No module named atari_py" but I already have atari_py installed?

### ISSUE THREAD

**Issue by JuliaNakhleh** [openai/gym#1008]
Hi,
Successfully managed to get a Deep Q-network running with the CartPole game. Now I'm trying to get it working with MsPacman but I'm having trouble installing the atari dependency. I tried:

`pip install gym[atari]`

And I see that it successfully installs atari_py in the same directory as gym, but when I run the program I get the following error:

```
raise error.DependencyNotInstalled("{}. (HINT: you can install Atari dependencies by running 'pip install gym[atari]'.)".format(e))
gym.error.DependencyNotInstalled: No module named atari_py. (HINT: you can install Atari dependencies by running 'pip install gym[atari]'.)
```

I tried adding `import atari_py` to my code and then I get the following error:

`ImportError: No module named atari_py`

As per the documentation, I also tried:

`pip install -e '.[atari]`

And got:

`Directory '.' is not installable. File 'setup.py' not found`

Any thoughts? Thanks very much!

**Comment by DavidXie2018** [comment]
Same problem here. It doesn't work in Jupyter notebook. I need to run python in the anaconda prompt in order for it to work

**Comment by bassamalghram** [comment]
> Same problem here. It doesn't work in Jupyter notebook. I need to run python in the anaconda prompt in order for it to work

**Comment by stephane-archer** [comment]
same problem

**Comment by christopherhesse** [comment]
What's the output of `python -c 'import atari_py'`?

**Comment by zook111** [comment]
**sudo** pip install absl-py atari-py gin-config gym opencv-python tensorflow-gpu

**Comment by christopherhesse** [comment]
This is likely an issue with having multiple copies of python installed.  Please make sure you are using the same python installation to install the package and run it.  I suggest using https://docs.conda.io/en/latest/miniconda.html to make this easier.
