### ISSUE TITLE
How to draw text ? 

### ISSUE THREAD

**Issue by Gasp34** [openai/gym#1016]
Here is my function render, do you have any idea of how i can draw text on the same window ? 

def render(self):

        screen_width = 1000
        screen_height = 1000
        cell_width = screen_width / self.num_states[1]
        cell_height = screen_height / self.num_states[0]

        if self.viewer is None:
            from gym.envs.classic_control import rendering
            self.viewer = rendering.Viewer(screen_width,screen_height)

            l,r,t,b = 0, cell_width, cell_height, 0
            cell = rendering.FilledPolygon([(l,b), (l,t), (r,t), (r,b)])
            cell.set_color(0,0,1) # blue for current state

            x=self.terminal_state[1]*cell_width
            y=self.terminal_state[0]*cell_height
            end = rendering.FilledPolygon([(x+l,y+b), (x+l,y+t), (x+r,y+t), (x+r,y+b)])
            end.set_color(1,0,0) # red for end state (note : end state is 0)

            for i in range(self.num_states[0]):
                for j in range(self.num_states[1]):
                    if self.mur_inv[i][j]==1:
                        x=j*cell_width
                        y=i*cell_height
                        mur = rendering.FilledPolygon([(x+l,y+b), (x+l,y+t), (x+r,y+t), (x+r,y+b)])
                        mur.set_color(0,0,0)
                        self.viewer.add_geom(mur)

            self.viewer.add_geom(end)
            self.celltrans = rendering.Transform()
            cell.add_attr(self.celltrans)
            self.viewer.add_geom(cell)

        if self.current_state is None: return None

        statex = self.current_state[1]
        statey = self.current_state[0]
        cellx = statex*cell_width
        celly = statey*cell_height
        self.celltrans.set_translation(cellx,celly)

        time.sleep(0)

        return self.viewer.render()

**Comment by christopherhesse** [comment]
Looks like you should use a pyglet label like the score text here: https://github.com/openai/gym/blob/master/gym/envs/box2d/car_racing.py#L332

**Comment by abelokon955** [comment]
Hi could you please elaborate, how to implement it into the upper example?
We added the following code but there is no text being displayed:
```

            self.score_label = pyglet.text.Label('0000', font_size=36,
                x=20, y=WINDOW_H*2.5/40.00, anchor_x='left', anchor_y='center',
                color=(255,255,255,255))

        self.score_label.text = "Hello World"
        self.score_label.draw()

```

**Comment by dickreuter** [comment]
I'm having issues with getting this to work as well.
In my case the Label simply doesn't appear. I'm wondering if this is because it's jsed in conjunction of the viewer method of the gym:

`
        if self.viewer is None:
            self.viewer = rendering.Viewer(screen_width, screen_height + 20)
            table = rendering.make_circle(radius=table_radius, filled=False)
            table_trans = rendering.Transform()
            table.add_attr(table_trans)
            table_trans.set_translation(screen_width / 2, screen_height / 2)

            self.viewer.add_geom(table)
            label = pyglet.text.Label(text, font_size=36,
                                      x=x, y=y, anchor_x='left', anchor_y='bottom',
                                      color=(255, 123, 255, 255))
            label.draw()

        self.viewer.render(return_rgb_array=mode == 'rgb_array')`

Any suggestions why the label is not drawn? If we can get it to work this is something that should be added to the gym pyglet wrapper.

**Comment by nilabha** [comment]
> I'm having issues with getting this to work as well.
> In my case the Label simply doesn't appear. I'm wondering if this is because it's jsed in conjunction of the viewer method of the gym:
> 
> ```
> if self.viewer is None:
> 	self.viewer = rendering.Viewer(screen_width, screen_height + 20)
> 	table = rendering.make_circle(radius=table_radius, filled=False)
> 	table_trans = rendering.Transform()
> 	table.add_attr(table_trans)
> 	table_trans.set_translation(screen_width / 2, screen_height / 2)
> 	self.viewer.add_geom(table)
> label = pyglet.text.Label(text, font_size=36,
> 			x=x, y=y, anchor_x='left', anchor_y='bottom',
> 			color=(255, 123, 255, 255))
> 
> label.draw()
> self.viewer.render(return_rgb_array=mode == 'rgb_array')`
> ```
> 
> Any suggestions why the label is not drawn? If we can get it to work this is something that should be added to the gym pyglet wrapper.

The label does not appear as self.viewer.render(return_rgb_array=mode == 'rgb_array') clears the window. You need pass the text and draw after it calls window.clear()
