### ISSUE TITLE
Wrong ordering of x and theta calculations

### ISSUE THREAD

**Issue by Rampagy** [openai/gym#1018]
`theta _dot` and `x_dot` should be calculated before `x` and `theta` otherwise `x` and `theta` will always be one timestep behind `theta_dot` and `x_dot`.  Below is the order that they should be calculated in.

    x_dot = x_dot + self.tau * xacc
    x  = x + self.tau * x_dot
    theta_dot = theta_dot + self.tau * thetaacc
    theta = theta + self.tau * theta_dot

https://github.com/openai/gym/blob/293eea787a662f501b0e4aab512d3769e830ece2/gym/envs/classic_control/cartpole.py#L63#L66

**Comment by pzhokhov** [comment]
New version is valid, but so is the old one. I have added suggestions to your PR, added a label, and assigned the issue back to you, @Rampagy :)

**Comment by christopherhesse** [comment]
Looks like this was fixed in #1019
