### ISSUE TITLE
Any pretrained agents for the MuJoCo envs for either OpenAI/baselines or Tensorforce?

### ISSUE THREAD

**Issue by benelot** [openai/gym#1022]
Hello,

I think I would be very helpful to have agents that are pre-trained on different gym environments. I am working on some transfer learning examples and it could be very helpful to have some baselines. Does anyone have pre-trained agents to experiment with?

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
