### ISSUE TITLE
Implementing parallel CPU execution of environments (from baselines)

### ISSUE THREAD

**Issue by prolearner** [openai/gym#1027]
I found parallel wrappers for gym environments in the [openai baseline](https://github.com/openai/baselines/) repo ([here](https://github.com/openai/baselines/tree/master/baselines/common/vec_env)). Why don't include them directly in gym too? They are very useful to speed up training.

**Comment by christopherhesse** [comment]
It's a good suggestion, we may do this at some point in the future, but we don't currently have plans to do so.
