### ISSUE TITLE
Python 3.5 incompatibility: print without parentheses in code examples

### ISSUE THREAD

**Issue by bartkamphorst** [openai/gym#103]
I'm working through the example scripts [from the docs](https://gym.openai.com/docs) using python 3.5. Most example code snippets break, however, because the print statements are not yet functions with parentheses. It would be great if someone could make the `print 'string' ` statements into `print('string')` statements in the docs. Thanks!

**Comment by gdb** [comment]
Fix committed and will be deployed soon. cc/ @jietang
