### ISSUE TITLE
Lunar Lander stops at 501 steps each episodes

### ISSUE THREAD

**Issue by leftluoyi** [openai/gym#1034]
Have designed a Q-network and I think it works in most parts. It start to train and after some episodes, here comes two problems:

1)  It converges to staying on the air. And finally, after **501** steps at each episode, the `env.step()` function will set `done=True`. 

2) During training, even through the lander arrived at the landing pad, it will drive away. After **501** steps at each episode, the average total rewards achieved is about 240. Then how can the agent know that resting on the landing pad will score 100 points.  

Thanks.

**Comment by TheBrokenRail** [comment]
How did you fix it? If you didn't fix it can you please reopen the issue, thanks!
