### ISSUE TITLE
Defining space for bounded length text observation

### ISSUE THREAD

**Issue by rahul-iisc** [openai/gym#1036]
For my environment, the observations are textual and are not of fixed length. How do I define observation space for this environment? 

For a use case see this paper: 
_Language Understanding for Text-based Games using Deep Reinforcement Learning_
http://www.emnlp2015.org/proceedings/EMNLP/pdf/EMNLP001.pdf

**Comment by christopherhesse** [comment]
You can just use a `gym.Space` instead or make your own subclass of `gym.Space`.  I don't know of any official way to do this yet.

**Comment by JerrickLiu** [comment]
Are there any updates on how to do this? I'm currently doing a RL NLP project and was wondering how to get text as observations in my custom environment.
