### ISSUE TITLE
Wrapping with same-name class from different modules fails

### ISSUE THREAD

**Issue by AdamGleave** [openai/gym#1037]
In gym/core.py:257, Wrapper forbids double wrapping with the same class, as this is usually a mistake. However, it compares only based on the class name, and not the module. If one has two classes with the same name defined in different modules, this raises an error.

I came across this when using baselines bench.Monitor and gym's built-in Monitor. Although this is admittedly somewhat redundant, I think it's a reasonable use case: I want to use the lightweight bench.Monitor all of the time for logging, and gym's built-in Monitor at one point in my pipeline for video generation.

Failing example:
```python
import gym                                                                                                                                                                                            
from baselines import bench

env = gym.make('CartPole-v1')
env = gym.wrappers.Monitor(env, '/tmp/gym-monitor', force=True)
env = bench.Monitor(env, '/tmp/bench-monitor')  # error on this line
```

Produces on my system:
```  
File "double_wrap_fail.py", line 6, in <module>
    env = bench.Monitor(env, '/tmp/bench-monitor')  # error on this line
  File "/home/adam/dev/baselines/baselines/bench/monitor.py", line 17, in __init__
    Wrapper.__init__(self, env=env)
  File "/home/adam/dev/gym/gym/core.py", line 247, in __init__
    self._warn_double_wrap()
  File "/home/adam/dev/gym/gym/core.py", line 258, in _warn_double_wrap
    raise error.DoubleWrapperError("Attempted to double wrap with Wrapper: {}".format(self.__class__.__name__))                                                                                       
gym.error.DoubleWrapperError: Attempted to double wrap with Wrapper: Monitor
```

**Comment by christopherhesse** [comment]
It doesn't look like `DoubleWrapperError` isn't used anywhere so I guess this issue isn't relevant anymore.  Thanks for reporting the bug!
