### ISSUE TITLE
The video window suddenly closes

### ISSUE THREAD

**Issue by linrl3** [openai/gym#1040]
My code is here: 
import gym
import gym.spaces
env = gym.make('LunarLander-v2')
env.reset()
env.render()
-------------
after I run this, the render window appear and then closes quickly.
Can somebody tell me how to fix this?

**Comment by hy76** [comment]
Try adding `env.close()` at the end.

**Comment by AQiLin** [comment]
Running software system ClaplR

**Comment by christopherhesse** [comment]
You probably want to run a loop like in the example code here: https://gym.openai.com/
