### ISSUE TITLE
[Bug?] Possible bug in logger.py regarding log levels

### ISSUE THREAD

**Issue by Cronixx** [openai/gym#1049]
Hey everyone, im quite new to open source, so i dont know if this belongs here, but i just noticed something in the logger.py which seemed like a mistake for me:

```
def debug(msg, *args):
    if MIN_LEVEL <= INFO:       <~~~~~~~~~~~~~~~~~~~~~~~~
        print('%s: %s'%('DEBUG', msg % args))

def info(msg, *args):
    if MIN_LEVEL <= INFO:
print('%s: %s'%('INFO', msg % args))
```

Shouldn't the MIN_LEVEL be smaller or equal to DEBUG in the Debug Method?

**Comment by christopherhesse** [comment]
This was fixed in https://github.com/openai/gym/pull/898, thanks for the bug report!
