### ISSUE TITLE
Official inclusion of new environment

### ISSUE THREAD

**Issue by RyanHope** [openai/gym#1063]
I am a post-doc at Carnegie Mellon University in the Psychology department. There is a video game relatively unknown outside of the cognitive science community has been heavily studied over the past few decades in the context of human learning and training. The game is a perfect platform for deepRL research. I have created a gym wrapper for this game and I would like to try and get it officially included in openai gym. I am not sure what the proper avenue for this is. Should I just create a PR?

**Comment by christopherhesse** [comment]
I'm afraid we are not accepting new environments currently but I made a wiki page to collect these: https://github.com/openai/gym/wiki/Third-Party-Environments  please update it with your environment. Note that we also just added a way to have `gym.make` work with third party python packages: https://github.com/openai/gym/pull/1344
