### ISSUE TITLE
2 x # TODO: depreciation warning in registration.py

### ISSUE THREAD

**Issue by jetojedno** [openai/gym#1066]
`# TODO: Add the following deprecation warning after 2017/02/18`
and
`# TODO: Add the following deprecation warning after 2017/03/01`
(both unactioned) appear in gym/gym/envs/registration.py

**Comment by christopherhesse** [comment]
@pzhokhov want to add those?

**Comment by pzhokhov** [comment]
https://github.com/openai/gym/pull/1379

**Comment by pzhokhov** [comment]
although frankly I'd rather just throw an error there. Do we actually support universe still?
