### ISSUE TITLE
allow keyword arguments on gym.make() which get passed to the environment's __init__

### ISSUE THREAD

**Issue by jetojedno** [openai/gym#1067]
It would be useful to be able to pass keywords to the chosen env's __init__ function.  The most obvious method is by passing them to gym.make() and passing them on if not consumed by gym.

**Comment by christopherhesse** [comment]
I believe this was fixed in https://github.com/openai/gym/pull/1301

**Comment by christopherhesse** [comment]
You can also avoid `gym.make` and instantiate environments directly.  The is currently done for `gym-retro`.
