### ISSUE TITLE
Different default friction coefficient

### ISSUE THREAD

**Issue by andrewliao11** [openai/gym#1068]
Is there any obvious motivation of making the friction coefficient different between two feet of the walker2d?

Left_foot: https://github.com/openai/gym/blob/master/gym/envs/mujoco/assets/walker2d.xml#L38
Right_foot: https://github.com/openai/gym/blob/master/gym/envs/mujoco/assets/walker2d.xml#L25

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
