### ISSUE TITLE
Board games have been removed

### ISSUE THREAD

**Issue by chairik** [openai/gym#1070]
Hi everyone,

As i noticed in the last version of GYM board games have been removed. Can you please inform me where i to find the last board games of GYM?, such the Go etc. Or is there any library that has several board games ready for GYM?
I need board games such as chess, connect-4, tic-tac-toe, go etc.

Thank you in advance

**Comment by vochicong** [comment]
There is a simple chess environment for openai/gym at
https://github.com/genyrosk/gym-chess

**Comment by christopherhesse** [comment]
Thanks for the answer @vochicong!  There may be other board game environments, but you will have to search around for them.  Feel free to update this issue if you find any.  You can also use the old version of gym if you just need the environments, or refactor them into a standalone python package.

**Comment by karhohs** [comment]
Will someone please share an explanation on _why_ board game environments were removed from GYM? Is there another toolkit better suited to applying reinforcement learning to a board game?

**Comment by vochicong** [comment]
From https://github.com/openai/gym/blob/master/README.rst

> 2018-01-25: ...
Removed the board_game, debugging, safety, parameter_tuning environments since they're not being maintained by us at OpenAI. We encourage authors and users to create new repositories for these environments.
