### ISSUE TITLE
Reacher-v2: typo leading to dead code

### ISSUE THREAD

**Issue by AdamGleave** [openai/gym#1074]
In ```gym/reacher.py``` in reset_model we have:
```
        while True:
            self.goal = self.np_random.uniform(low=-.2, high=.2, size=2)
            if np.linalg.norm(self.goal) < 2:
                break
```
This appears to be intended to ensure the goal is in a circle of radius ```0.2```, allowing the Reacher arm (consisting of two segments of 0.1 long with a 0.01 fingertip) to directly touch the goal. However, since the comparison is with 2 rather than 0.2, it is _always_ satisfied.

I suggest we either remove the while loop entirely (simplifying the code), or change ```2``` to ```0.2``` (changing the semantics of the Reacher environment).

Happy to make a PR for either of these approaches, requesting comment from @joschu or @matthiasplappert who most recently touched this file.

**Comment by christopherhesse** [comment]
This appears to be fixed now: https://github.com/openai/gym/blob/master/gym/envs/mujoco/reacher.py#L27

Thanks for the bug report!
