### ISSUE TITLE
Half cheetah state space

### ISSUE THREAD

**Issue by rohansaphal97** [openai/gym#1076]
I have some questions regarding the roboschool Half-Cheetah.

1.) I see that the observation space for Half-Cheetah is 26. Can anyone tell me what is each value for?- I only counted 18. (also, some of the values seem to remain 0 for all timesteps)

2.) In the half_cheetah.xml under roboschool/mujoco_assets, there is the following comment:

Cheetah Model

![image](https://user-images.githubusercontent.com/32096848/41475955-b21ab018-70dd-11e8-83e2-feab0d83ca53.png)

Could you please confirm to me if the order presented here is the same with the order they appear in the observation matrix?
Also the last 8 values of the 26 values are not always zero. They are either 0 and one. 

Please help.

Thank you

**Comment by christopherhesse** [comment]
Looks like HalfCheetah uses most of qpos and qvel here: https://github.com/openai/gym/blob/master/gym/envs/mujoco/half_cheetah.py#L22

You can find the index using something like `env.unwrapped.sim.model.get_joint_qpos_addr('bshin') ` but for each individual body.  See https://github.com/openai/gym/blob/master/gym/envs/mujoco/assets/half_cheetah.xml for a list of bodies and the Mujoco API for more info about `get_joint_qpos_addr`
