### ISSUE TITLE
I can't find any other reference to `benchmark_spec`? Did this function get renamed?

### ISSUE THREAD

**Issue by mimoralea** [openai/gym#1080]
https://github.com/openai/gym/blob/77568accd7f698ae67937da0099fa58a037a96fd/examples/scripts/benchmark_runner#L42

**Comment by mimoralea** [comment]
https://github.com/openai/gym/blame/6af4a5b9b2755606c4e0becfe1fc876d33130526/gym/benchmarks/registration.py#L108-L112

**Comment by mimoralea** [comment]
I guess it got removed here: https://github.com/openai/gym/commit/4c460ba

I understand this was all experimental. Is there a recommended way for running an Atari benchmark such as: https://github.com/openai/gym/commit/c6215f190d9242985c4e7184c36aab8dd99883f9#diff-170d6bbf20fa02890840c39b9fbb66a0R68

@joschu, I would appreciate any guidance you may have.

**Comment by christopherhesse** [comment]
Yeah looks like the benchmark specs were removed.  You can use something like a Monitor wrapper (such as the baselines one here https://github.com/openai/baselines/blob/master/baselines/bench/monitor.py#L12) and then take the CSV output files to get a score (for instance median human normalized performance) by loading it in pandas and processing the data.  Having easier to use standard evaluation procedures would be nice, but it seems this is currently outside the scope of gym.
