### ISSUE TITLE
Bug in multi-dimensional continuous action space envs: single dimension action gets accepted by environment and circumvent Halfcheetah movement penalty

### ISSUE THREAD

**Issue by watchernyu** [openai/gym#1083]
Hi! Would like to report a possible bug, when testing with the HalfCheetah-v2 environment, we find that if you just do env.step() with one single action (instead of a 6-dim action vector specified by the env.action_space), things actually work and the underlying code is extending this one action to a list of the same actions, and you also circumvent HalfCheetah-v2's penalty calculation for 5 out of 6 actions, the result is that you are getting much higher rewards from the environment although your model is not learning as much. Not sure if this is a problem that people are aware of?

I have written the following simple test code to show this bug. If you just put in a scalar action (e.g. 1) to env.step(), it works without giving an error, and also your reward is much higher compared to if you input a vector (1,1,1,1,1,1), if you give an action of 0, the reward is same compared to (0,0,0,0,0,0). If you give a vector of dimension 2-5, there actually will be error message, but a single action works just fine.

The major problem is that for HalfCheetah-v2, a well-trained agent achieves performance approximately the same as an agent that trained on giving only 1 action while getting much higher reward from the environment through this bug, this information can be very misleading for researchers using this environment. 

This might also be a problem for other mujoco environments, I'm not sure. Would be great if this can be fixed in future versions! Thanks! 

`
import numpy as np
import gym

envname = 'HalfCheetah-v2'
print("testing for ",envname)
env = gym.make(envname)
discrete = isinstance(env.action_space, gym.spaces.Discrete)
print("discrete env: ", discrete)
if discrete:
    n_action = env.action_space.n
else:
    n_action = env.action_space.shape[0]
test_action = 1 ## if test action is 0, then there is no difference in penalty

#######################################
env.seed(100)
np.random.seed(100)

for i_episode in range(5):
    total_reward = 0
    observation = env.reset()
    for t in range(100):
        # env.render()
        action =test_action ## use one single action actually works without error
        observation, reward, done, info = env.step(action)
        total_reward += reward
        if done or t==100-1:
            print("Episode finished, r:",total_reward)
            break

print('#################################')
env.seed(100)
np.random.seed(100)

for i_episode in range(5):
    total_reward = 0
    observation = env.reset()
    for t in range(100):
        # env.render()
        ## this should be the same as using one single action
        ## but gives much higher penalty
        action = [test_action for _ in range(n_action)]
        observation, reward, done, info = env.step(action)
        total_reward += reward
        if done or t==100-1:
            print("Episode finished, r:",total_reward)
            break

print('#################################')
## trace the error and can see that
"""
  File "/home/watcher/Desktop/gym/gym/envs/mujoco/half_cheetah.py", line 12, in step
    self.do_simulation(action, self.frame_skip)
    ## in here we can see this line
    reward_ctrl = - 0.1 * np.square(action).sum()
    ## which calculates the penalty for big actions, and this part will be circumvented 
    ## if your input action is 1-dim instead of 6-dim
    ## then you get less penalty and no error or warning    
File "/home/watcher/Desktop/gym/gym/envs/mujoco/mujoco_env.py", line 104, in do_simulation
    self.sim.data.ctrl[:] = ctrl
    ## this part seems to extend a single action to a list of actions
"""
env.seed(100)
np.random.seed(100)

for i_episode in range(5):
    total_reward = 0
    observation = env.reset()
    for t in range(100):
        # env.render()
        action = env.action_space.sample()
        action = [test_action for _ in range(2)]
        observation, reward, done, info = env.step(action)
        total_reward += reward
        if done or t==100-1:
            print("Episode finished, r:",total_reward)
            break
`

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
