### ISSUE TITLE
Installing an older version with only some environments

### ISSUE THREAD

**Issue by shenkev** [openai/gym#1088]
Hi,

I'm running an older piece of code written in gym 0.8.2 with the Atari environments.

I can install gym 0.8.2 easily using `pip install gym==0.8.2`.

However, the command to install all the environments doesn't work on my system so I'm only trying to install the Atari envs.

The problem is cloning this repo and running `pip install -e '.[atari]'` will uninstall gym 0.8.2 and install the newest version 0.10.5

How do I get around this?

**Comment by Chris-Lamb** [comment]
You don't need to clone the repo just get the version you want from pypi:
`pip install gym[atari]==0.8.2`

**Comment by danielnbarbosa** [comment]
@shenkev This should work: `pip install gym==0.8.2 -e '.[atari]'`

**Comment by christopherhesse** [comment]
You could also use the source code for that version of gym, something like https://github.com/openai/gym/releases/tag/v0.7.4 (unfortunately it looks like we did not tag version 0.8.2).
