### ISSUE TITLE
A way to return the number of elements in tuple space

### ISSUE THREAD

**Issue by NishanthVAnand** [openai/gym#1089]
There's no way to get the length of the tuple space right now. Can you please add a method to get the length of the tuple space?
For example, 
if we are in a discrete space, 
`env.observation_space.n` returns the dimension.
Similarly, if we are in box space,
`env.observation_space.shape` will return the dimension of the observation space.

Right now for tuple space, the only way to find the length is to sample and find the length of the sample.
`sample = env.observation_space.sample()`
`dim = len(sample)`
A direct method would be really appreciated.

**Comment by Ricocotam** [comment]
You can use `len(env.observation_space.spaces)`
Btw, you'd probably want to know what are the different spaces you have and thus iterate over the `spaces` attribute

**Comment by christopherhesse** [comment]
Thanks for answering this @Ricocotam!

**Comment by Yuchen0604** [comment]
Hi, I was just wondering, how can I get the dimension of a Tuple space?
My space is as follows:
`self.observation_space = spaces.Tuple(spaces=(spaces.Box(low=0, high=20, shape=(3,), dtype=np.float16),
                                                      spaces.Box(low=-high, high=high, shape=(2, 24), dtype=np.float16),
                                                      spaces.Discrete(24)))`
I want to use the dqn agent, which requires the space.shape to build the neural network, and according to my understanding, in this case I will need 3+2*24+1 = 52 input neuron.
How can I get the number of 52?
Thanks in advance!
