### ISSUE TITLE
Environment freeze with no reason

### ISSUE THREAD

**Issue by carpedm20** [openai/gym#109]
I think there is a bug in breakout environment that a game freeze (no new ball is generated) after a life is discounted (ex. from 4->3)

[freeze example 1](https://drive.google.com/file/d/0ByTS2HBKYvZxQkFDSnBxbjhPOG8/view?usp=sharing), [freeze example 2](https://drive.google.com/open?id=0ByTS2HBKYvZxTHo5R0Q5UTd5b2M), [normal exaple](https://drive.google.com/open?id=0ByTS2HBKYvZxc1ZaQ05QakRRU0E)

I don't know this happen to other environment because I'm only using breakout to train my model. I don't think this frequently occurs but while I testing my trained model, I found 2 freezing cases among 100 test cases. I only use `env.step(action)` when there is no `terminal` signal.

Do a freeze possibly occur when a specific key is entered in a specific state such as state right after dead of ball?

**Comment by gdb** [comment]
That doesn't look good! @joschu any ideas?

**Comment by carpedm20** [comment]
@gdb I think this happened because I set epsilon (e-greedy) almost 0 so that my model doesn't act any actions which include "fire" action. Close this issue.
