### ISSUE TITLE
Rendering slowly in server

### ISSUE THREAD

**Issue by Cuiyirui** [openai/gym#1091]
My system environment is CentOS, and I can run the demo successfully. The speed of rendering, however, is very very slow, approximate 1 frame per second.
My code is:

> import gym
import time
env = gym.make('CartPole-v0')   # create enviroment
env.mode = 'fast'
observation = env.reset()  # start the process
print(env.action_space)    #action space
print(env.observation_space) # observation space
for i in range(1000):
    env.render()
    print(i)
    env.step(env.action_space.sample()) # take a random action

When I comment "env.render()", the program can run normally.

**Comment by vishma** [comment]
I faced the same issue. I think it has to do something with your pyglet versions installed in python environment. As a workaround you can create a virtual environment using conda/pipenv and install gym and other required dependencies. A fresh install worked for me. 

conda : https://conda.io/docs/user-guide/tasks/manage-environments.html
pipenv : https://pipenv.readthedocs.io/en/latest/install/#installing-packages-for-your-project

**Comment by christopherhesse** [comment]
Thanks for answering this @vishma!  There could also be some issue with your linux setup that causes slow rendering.
