### ISSUE TITLE
Box2D dependency fails on Linux

### ISSUE THREAD

**Issue by christopherhesse** [openai/gym#1096]
The Box2D library used by setup.py doesn't seem to work, and also the tests do not seem to catch this.

Steps to reproduce:

`apt-get update`
`apt-get install swig`
`pip install gym[box2d]`
`python -c "import Box2D"`
```Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/opt/conda/lib/python3.6/site-packages/Box2D/__init__.py", line 20, in <module>
    from .Box2D import *
  File "/opt/conda/lib/python3.6/site-packages/Box2D/Box2D.py", line 434, in <module>
    RAND_LIMIT = _Box2D.RAND_LIMIT
AttributeError: module 'Box2D._Box2D' has no attribute 'RAND_LIMIT'
```

@pzhokhov has suggested that `box2d-py` is in fact the correct dependency to put in setup.py and not `box2d-kengz` but that may require testing on mac and linux.

**Comment by DuaneNielsen** [comment]
I could only get it working on mac with box2d-kengz box2d didn't work for me...

**Comment by christopherhesse** [comment]
@pzhokhov I tried `box2d-py` on my mac and it failed, it seems like `box2d-kengz` is required on mac while `box2d-py` is required on linux.  Is there some way to make this work correctly on both platforms?

**Comment by christopherhesse** [comment]
This also implies we have no mac based tests for these environments, is that the case?

**Comment by christopherhesse** [comment]
Since there is no valid configuration of box2d packages, could we get a note in the readme or something as a workaround until we have a box2d package that works? @pzhokhov

**Comment by BStudent** [comment]
box2d doesn't seem to work currently for [Pop!_OS](https://system76.com/pop) (System76' GPU-friendly unbuntu derivative), however **_box2d-kengz does_**.

**Comment by pzhokhov** [comment]
added a note to README: 
https://github.com/openai/gym/pull/1120
