### ISSUE TITLE
RAM

### ISSUE THREAD

**Issue by ling-pan** [openai/gym#1098]
Hi,
I am wondering what is the meaning of each byte in the RAM?
For example, in Pacman-ram-v0, an observation is [0, 112, 114, 115, 51, 1, 91, 91, 91, 85, 87, 0, 80, 80, 80, 50, 98, 0, 0, 3, 0, 0, 1, 0, 0, 1, 6, 6, 214, 4, 75, 0, 45, 1, 0, 150, 246, 0, 0, 255, 0, 0, 52, 0, 0, 120, 0, 100, 130, 0, 0, 24, 1, 222, 0, 2, 1, 0, 6, 80, 255, 255, 0, 255, 255, 80, 255, 255, 80, 255, 255, 80, 255, 255, 80, 191, 191, 80, 191, 191, 80, 191, 191, 80, 255, 255, 80, 255, 255, 80, 255, 255, 80, 255, 255, 0, 255, 255, 80, 255, 255, 20, 223, 43, 217, 123, 217, 123, 217, 123, 217, 123, 217, 123, 217, 221, 0, 63, 0, 0, 0, 0, 0, 2, 98, 250, 146, 215].

What does this mean? I have checked related material but did not find any explanation.

Thanks a lot!

**Comment by DuaneNielsen** [comment]
Just a wild guess.. but as I understand it,  there are 2 ways you can "observe" a simulation.  1.  Look at the video on the screen.  2.  Look at the video on the screen and the contents of the RAM while the game is running.

After all.. the video is just a special case of RAM.  It just so happens that each memory cell represents a pixel on the screen.

So, assuming my wild guess is correct.  I don't think anyone but the original programmer of the pacman code could tell you what the values in ram represent.  Certainly no modern programmer would have much idea what is going on in the RAM of their program.

However, if you spent a lot of time playing the game and looking at the ram, you would eventually figure out things like.. the score is represented by some of the memory, the ghost is a alive or dead depending upon these other values, etc..

So the idea is, given access to this information, an agent might be able to figure out some "special knowlege" that helps it improve its game.

**Comment by christopherhesse** [comment]
@DuaneNielsen is correct here, figuring out the meaning of the ram bytes is possible, especially if you have the original source code to the game (unlikely) or a hand-disassembled version (hard to find).
