### ISSUE TITLE
[Feature Request] An environment for Magnetic Levitation

### ISSUE THREAD

**Issue by SoutrikBandyopadhyay** [openai/gym#1099]
Magnetic Levitation is a classic control system problem which is non linear in nature and can be solved with Reinforcement learning. An environment for Magnetic Levitation can be helpful to people to enter the realm of Control Systems.

**Comment by christopherhesse** [comment]
Is there a standard version of this used in existing RL papers?

**Comment by christopherhesse** [comment]
I don't think we are adding new environments at this time, but let me know if there's a standard RL version of this task.
