### ISSUE TITLE
Any tutorial/documentation for custom rendering?

### ISSUE THREAD

**Issue by zHaytam** [openai/gym#1100]
Hello,
First of all, thank you for everything you've done, it's amazing.

I am currently creating a custom environment for my game engine and I was wondering if there was any tutorial or documentation about the 2D rendering you use in your control games?

I want to be able to render a frame of my game just like we can do using your envs.
Thank you

**Comment by tadeoos** [comment]
Is there any documentation on creating custom environment at all?

**Comment by zHaytam** [comment]
Well... If anyone has another suggestion for rendering a frame I'll take it!

**Comment by cjm715** [comment]
@tadeoos there is information here on creating a custom environment: https://github.com/openai/gym/blob/master/gym/envs/README.md .

**Comment by christopherhesse** [comment]
The control games render using pyglet + OpenGL and reads back the rendered pixels: https://github.com/openai/gym/blob/master/gym/envs/box2d/car_racing.py#L374

How you do that will depend on your specific game, but something along those lines should work.
