### ISSUE TITLE
Is the transition of the environment in Mujoco stochastic?

### ISSUE THREAD

**Issue by wmyw96** [openai/gym#1102]
Hi, ~
I wrote some code like this, `state` and `action` are numpy matrix representing a sample trajectory of learned policy. 
```
def set_state(env, state):
    qpos = np.concatenate([np.ones(1), state[:8]])
    qv = state[8:]
    env.env.set_state(qpos, qv)

env = gym.make("HalfCheetah-v1")
k = 0
for kk in range(100):
    k = (k * 27 + 34) % (1000-100+1)
    env.reset()
    set_state(env, state[k, :])
    for j in range(1000 - k):
        s, _, __, ___ = env.step(action[k + j, :])
    err = 0
    for i in range(100):
        env.reset()
        set_state(env, state[k, :])
        for j in range(1000 - k):
            o, _, __, ___ = env.step(action[k + j, :])
        err += np.sum((o - s) * (o - s))
    print(err)
```
If the Mujoco environment is deterministic, the printed `err` will be 0, but it prints like this, which is confusing. (I use mujoco-py==0.5.7 and gym==0.9.1)
```
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2995.20792008
0.0
0.0
0.0
0.0
0.0
0.0
```
I think if the transition is stochasitc, then all the error will siginificantly larger than 0, while all the error will be around 0 if the transition is deterministic. And such result makes me confused. So do anyone know whether the Mujoco env is stochastic?

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
