### ISSUE TITLE
Community Made Versions of Atari to Allow State Access

### ISSUE THREAD

**Issue by nflu** [openai/gym#1103]
I would like to access the lower-dimensional state of some Atari Environments but it [seems as though](https://github.com/openai/gym/issues/970) that is not possible using the current implementation from Open AI as it just accesses the ALE. 

Are there other environments made to emulate any of the Atari games that allow direct access to the lower-dimensional state of the game at each time-step, not just the frames? Is there any solution to access the lower-dimensional state of Atari games while training? I'm most interested in Pong, Space Invaders and Breakout but I'll take whatever I can find.

**Comment by christopherhesse** [comment]
Does the lower-dimensional state mean RAM observations?  We have ram versions of the environments: https://gym.openai.com/envs/AirRaid-ram-v0/

**Comment by nflu** [comment]
I meant the state elements that are necessary to perform the calculations of what the next state will be given the action. i.e. if the environment is a POMDP instead of observations I would like to know the underlying states. For example get the position of the paddle in pong #1110 

Ideally I would like to use them to calculate a different reward function while still giving the agent pixels.

It is probably possible to find them from the RAM but it may be difficult if variables are not at consistent positions in the RAM and instead are dynamically allocated. Also I would still have to calculate the pixels as well to give to the agent.

This project ended up getting pushed off so I don't have the time to look into all of the details right now, but I will respond here and if I do end up building something to read from RAM.

**Comment by christopherhesse** [comment]
There are likely to be reimplementations of atari games such as Breakout in https://github.com/vicariousinc/schema-games.  I don't believe we are interested in adding more environments to the gym library itself, but some of those could be cool to link to from the wiki.

The RAM data should be mostly sufficient for turning this into an MDP, although if you really want an MDP you'd have to use `env.unwrapped.clone_full_state()`, and you could make a wrapper or subclass of `AtariEnv` for this purpose.

As for which RAM values correspond to what in the game, this has to be figured out on a per-game basis.  If you have mappings for individual games, that might be nice to have in the wiki as well.  The RAM for atari games is very non-dynamic.
