### ISSUE TITLE
classic_control environments don't allow rendering a new window

### ISSUE THREAD

**Issue by cfperez** [openai/gym#1107]
This fails to display a window:
```
env = gym.make('CartPole-v0')
env.reset()
# Show the window
env.render()
# Close it
env.close()
# Show the window again
env.render()
```

The code seems to intend merely to close the window
https://github.com/openai/gym/blob/5c116fb3c91e872505300031d2bd60672b3a6e03/gym/envs/classic_control/cartpole.py#L140

but because of the None check, the environment will not re-render
https://github.com/openai/gym/blob/5c116fb3c91e872505300031d2bd60672b3a6e03/gym/envs/classic_control/cartpole.py#L105

Fix is simply to add `self.viewer=None` to `close()`.

**Comment by pzhokhov** [comment]
in fact, close() is already implemented that way in atari_env and box2d environment... sounds good, but please file a PR

**Comment by cfperez** [comment]
@pzhokhov See #1155 referenced above
