### ISSUE TITLE
Error when numpy version isn't of the standard x.x.x format

### ISSUE THREAD

**Issue by MarCnu** [openai/gym#111]
When I try to import gym, I get this Traceback

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "dqn/environment.py", line 2, in <module>
    import gym
  File "/usr/local/lib/python2.7/dist-packages/gym/__init__.py", line 32, in <module>
    sanity_check_dependencies()
  File "/usr/local/lib/python2.7/dist-packages/gym/__init__.py", line 18, in sanity_check_dependencies
    if distutils.version.StrictVersion(numpy.__version__) < distutils.version.StrictVersion('1.10.4'):
  File "/usr/lib/python2.7/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/usr/lib/python2.7/distutils/version.py", line 107, in parse
    raise ValueError, "invalid version number '%s'" % vstring
ValueError: invalid version number '1.12.0.dev0+8ccfede'
```

https://github.com/openai/gym/blob/1d414864802bf1e7e4b8beae85cbd5a196e3cdaa/gym/__init__.py#L13-23

```
def sanity_check_dependencies():
    import numpy
    import requests
    import six

    if distutils.version.StrictVersion(numpy.__version__) < distutils.version.StrictVersion('1.10.4'):
        logger.warn("You have 'numpy' version %s installed, but 'gym' requires at least 1.10.4. HINT: upgrade via 'pip install -U numpy'.", numpy.__version__)

    if distutils.version.StrictVersion(requests.__version__) < distutils.version.StrictVersion('2.0'):
        logger.warn("You have 'requests' version %s installed, but 'gym' requires at least 2.0. HINT: upgrade via 'pip install -U requests'.", requests.__version__)
```

In my self-compiled numpy, my version is '1.12.0.dev0+8ccfede', it isn't a recognised format by distutils.version.StrictVersion and it leads to an error.

It would be nice to be less strict in the format of versions.

**Comment by gdb** [comment]
Ah yes we should just skip the check if the version doesn't parse. Up for
writing a patch?

On Friday, May 20, 2016, MarCnu <notifications@github.com> wrote:

> When I try to import gym, I get this Traceback
>
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "dqn/environment.py", line 2, in <module>
>     import gym
>   File "/usr/local/lib/python2.7/dist-packages/gym/__init__.py", line 32, in <module>
>     sanity_check_dependencies()
>   File "/usr/local/lib/python2.7/dist-packages/gym/__init__.py", line 18, in sanity_check_dependencies
>     if distutils.version.StrictVersion(numpy.__version__) < distutils.version.StrictVersion('1.10.4'):
>   File "/usr/lib/python2.7/distutils/version.py", line 40, in __init__
>     self.parse(vstring)
>   File "/usr/lib/python2.7/distutils/version.py", line 107, in parse
>     raise ValueError, "invalid version number '%s'" % vstring
> ValueError: invalid version number '1.12.0.dev0+8ccfede'
>
>
> https://github.com/openai/gym/blob/1d414864802bf1e7e4b8beae85cbd5a196e3cdaa/gym/__init__.py#L13-23
>
> def sanity_check_dependencies():
>     import numpy
>     import requests
>     import six
>
>     if distutils.version.StrictVersion(numpy.__version__) < distutils.version.StrictVersion('1.10.4'):
>         logger.warn("You have 'numpy' version %s installed, but 'gym' requires at least 1.10.4. HINT: upgrade via 'pip install -U numpy'.", numpy.__version__)
>
>     if distutils.version.StrictVersion(requests.__version__) < distutils.version.StrictVersion('2.0'):
>         logger.warn("You have 'requests' version %s installed, but 'gym' requires at least 2.0. HINT: upgrade via 'pip install -U requests'.", requests.__version__)
>
> In my self-compiled numpy, my version is '1.12.0.dev0+8ccfede', it isn't a
> recognised format by distutils.version.StrictVersion and it leads to an
> error.
>
> It would be nice to be less strict in the format of versions.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/openai/gym/issues/111>
>


-- 
Sent from mobile

**Comment by MarCnu** [comment]
What would you like me to use ?

Replacing StrictVersion "For software idealists" http://epydoc.sourceforge.net/stdlib/distutils.version.StrictVersion-class.html
by LooseVersion "For software anarchists" ? http://epydoc.sourceforge.net/stdlib/distutils.version.LooseVersion-class.html

Or adding a 
```
try:
    xxx
except:
    logger.warn("You have 'lib' version %s installed, which is a non-standard version. 'gym' requires at least x.x.x", lib.__version__)
```

**Comment by gdb** [comment]
I would just catch the exception and not bother warning -- it's just a
best-effort check to make sure your numpy isn't too old, and you probably
know what you're doing if you have a custom version.

On Friday, May 20, 2016, MarCnu <notifications@github.com> wrote:

> What would you like me to use ?
>
> Replacing StrictVersion "For software idealists"
> http://epydoc.sourceforge.net/stdlib/distutils.version.StrictVersion-class.html
> by LooseVersion "For software anarchists" ?
> http://epydoc.sourceforge.net/stdlib/distutils.version.LooseVersion-class.html
>
> Or adding a
>
> try:
>     xxx
> except:
>     logger.warn("You have 'lib' version %s installed, which is a non-standard version. 'gym' requires at least x.x.x", lib.__version__)
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/openai/gym/issues/111#issuecomment-220642277>
>


-- 
Sent from mobile

**Comment by jietang** [comment]
Fix merged into master

**Comment by hashzulu** [comment]
So how do I go about solving this?
Dont really have much of a background in programming, but still want to "train my dragon" if you know what i mean :)

**Comment by tlbtlbtlb** [comment]
@hashzulu This particular issue was fixed a long time ago. If you're having a problem, can you provide as much information as possible about it?
