### ISSUE TITLE
Please consider disentangling this repo from Mujoco proprietary stuff, move that to another repo. Alternatively disentangle the Environment class of gym and its critical dependencies from the Mujoco proprietary stuff by moving that class to another repo.

### ISSUE THREAD

**Issue by brancoliticus** [openai/gym#1113]
Also I believe the project is not open source as stated in the github README. I do not think the Mujoco license for the models grants someone that doesn't have the Mujoco physics engine license but only wants to use the truly open source part of gym the right to download the Mujoco models to their hard drives even if they don't intend to use them. And it may be fine for OpenAI if research shops and RL enthusiasts break the law because OpenAI in it's infinite wisdom decided to entangle proprietary stuff with stuff that they own copyright to and release it and call it open source, but that is not good enough for me.

I cannot take anything from this repo and package it in my proprietary application because of this issue. If this issues is not resolved I will have to build up the stuff that might be useful for me in this repo from scratch, so as to use the RL algos in the baseline repo in my app. In particular I cannot use the Env python class from the gym repo, which is highly embedded in the baselines repo, and I guess I will have to also delete all imports of gym from the baselines repo to use the baselines repo.

Please consider fixing this issue in a way that is actually open source friendly, considering that you claim this project to be open source.

**Comment by pzhokhov** [comment]
Hi @brancoliticus! Could you be more specific about why is gym.Env (or anything in the gym) violates being open-source? We do not ship any mujoco models with gym, nor mujoco code or license keys. All the  mujoco-related code is written by OpenAI and contributors; and is licensed as a part of gym, not part of mujoco. 
OpenAI is not endorsing or "fine with" people breaking the law; so if there is something we missed - please let us know and we will fix it. 
While support for mujoco is not going away any time soon, if you need an open-source alternative, consider using bullet (https://github.com/bulletphysics/bullet3/tree/master/examples/pybullet)

**Comment by brancoliticus** [comment]
I can assure you that the license at https://github.com/openai/gym/blob/master/LICENSE.md is not open source according to OSI or free software according to FSF. It also has no mention of files that were derived from what is headlined in the license file as 'Mujoco models', so as to clearly separate what is derived from proprietary stuff so as to remove that and not be legally liable down the road of a project created by using gym.

My understanding is that the files that are mentioned as 'Mujoco models' in the license file are the ones at https://github.com/openai/gym/tree/master/gym/envs/mujoco/assets. But I am not a lawyer, I am not OpenAI and I am not Roboti LLC, therefore I am not going to guess blindly that by downloading gym and removing the mujoco/assets folder and modifying myself the license statement I am legally in the clear to use gym in a proprietary way without having to pay Roboti LLC a license fee for every single one of the users of my software down the road.

My acceptable solution is outlined in my post above: rebuild the entire history of the repo with what constitutes 'Mujoco models' out, possibly that being only the envs/mujoco/assets folder, and then modify the license file to match what is actually intended by the original MIT license.

In the meantime I am off to https://github.com/Unity-Technologies/ml-agents which has a decent PPO implementation that is currently not entangled with proprietary stuff I don't want to deal with.

**Comment by byjott** [comment]
We are in a similar position: While we'd like to use `gym` to test some reinforcement learning models, the unclear licensing is an issue. Would the maintainers accept a PR that makes bundling these files into the wheel optional?
(I'm thinking of an env variable that needs to be set when building wheels that would prevent bundling these files).
