### ISSUE TITLE
code question about Fetch experience 

### ISSUE THREAD

**Issue by huangjiancong1** [openai/gym#1119]
in /gym/gym/envs/robotics/fetch
```
import numpy as np

from gym import utils
from gym.envs.robotics import fetch_env


class FetchSlideEnv(fetch_env.FetchEnv, utils.EzPickle):
    def __init__(self, reward_type='sparse'):
        initial_qpos = {
            'robot0:slide0': 0.0,
            'robot0:slide1': 0.0,
            'robot0:slide2': 0.0,
            'object0:joint': [1.7, 1.1, 0.64, 1., 0., 0., 0.],
        }
        fetch_env.FetchEnv.__init__(
            self, 'baxter/slide.xml', has_object=True, block_gripper=True, n_substeps=20,
            gripper_extra_height=-0.02, target_in_the_air=False, target_offset=np.array([0.4, 0.0, 0.0]),
            obj_range=0.1, target_range=0.3, distance_threshold=0.05,
            initial_qpos=initial_qpos, reward_type=reward_type)
        utils.EzPickle.__init__(self)
```

I want to know what 'object0:joint': [1.7, 1.1, 0.64, 1., 0., 0., 0.], it means here. What are the seven variables referring to and why are they seven?

**Comment by huangjiancong1** [comment]
code link
[https://github.com/openai/gym/blob/master/gym/envs/robotics/fetch/slide.py](url)

**Comment by iSaran** [comment]
@huangjiancong1 Take a look at the model [here](https://github.com/openai/gym/blob/d1146303b070a463e9e81086a0aeff7a2c909311/gym/envs/robotics/assets/fetch/slide.xml#L23). As you can see the `object0:joint` is the name of the joint of the object, which is a free joint. As a free joint you can set its position in the Cartesian space and hence the 7 numbers: three numbers for position and four for orientation in the form of a quaternion. For more info on  how Mujoco modelling works, see [Mujoco's documentation](http://www.mujoco.org/book/modeling.html).

**Comment by christopherhesse** [comment]
Thanks for answering this @iSaran!
