### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Client'

### ISSUE THREAD

**Issue by sachinprabhu007** [openai/gym#1121]
Hello 

I am new to OpenAI gym and universe. I can't seem to run the program. It results in following error

> [2018-08-07 12:54:19,915] Making new env: flashgames.CoasterRacer-v0
> [2018-08-07 12:54:19,919] Called reset on <Timer<Render<ThrottleVNCEnv<flashgames.CoasterRacer-v0>>>> before configuring. Configuring automatically with default arguments
> [2018-08-07 12:54:19,919] Writing logs to file: /tmp/universe-25212.log
> Traceback (most recent call last):
>   File "demo.py", line 92, in <module>
>     main()	
>   File "demo.py", line 38, in main
>     observation_n = env.reset()
>   File "/home/sachin/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/gym/core.py", line 122, in reset
>     self.configure()
>   File "/home/sachin/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/gym/core.py", line 224, in configure
>     self._configure(*args, **kwargs)
>   File "/home/sachin/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/universe/vectorized/core.py", line 39, in _configure
>     super(Wrapper, self)._configure(**kwargs)
>   File "/home/sachin/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/gym/core.py", line 349, in _configure
>     return self.env.configure(*args, **kwargs)
>   File "/home/sachin/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/gym/core.py", line 224, in configure
>     self._configure(*args, **kwargs)
>   File "/home/sachin/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/universe/wrappers/render.py", line 18, in _configure
>     super(Render, self)._configure(**kwargs)
>   File "/home/sachin/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/universe/vectorized/core.py", line 39, in _configure
>     super(Wrapper, self)._configure(**kwargs)
>   File "/home/sachin/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/gym/core.py", line 349, in _configure
>     return self.env.configure(*args, **kwargs)
>   File "/home/sachin/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/gym/core.py", line 224, in configure
>     self._configure(*args, **kwargs)
>   File "/home/sachin/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/universe/wrappers/throttle.py", line 27, in _configure
>     super(Throttle, self)._configure(**kwargs)
>   File "/home/sachin/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/universe/vectorized/core.py", line 39, in _configure
>     super(Wrapper, self)._configure(**kwargs)
>   File "/home/sachin/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/gym/core.py", line 349, in _configure
>     return self.env.configure(*args, **kwargs)
>   File "/home/sachin/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/gym/core.py", line 224, in configure
>     self._configure(*args, **kwargs)
>   File "/home/sachin/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/universe/envs/vnc_env.py", line 199, in _configure
>     use_recorder_ports=record,
>   File "/home/sachin/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/universe/remotes/build.py", line 19, in build
>     n=n,
>   File "/home/sachin/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/universe/remotes/docker_remote.py", line 44, in __init__
>     self._assigner = PortAssigner(reuse=reuse)
>   File "/home/sachin/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/universe/remotes/docker_remote.py", line 162, in __init__
>     self.client, self.info = get_client()
>   File "/home/sachin/.virtualenvs/keras_tf/local/lib/python2.7/site-packages/universe/remotes/docker_remote.py", line 156, in get_client
>     return docker.Client(base_url=host, version=client_api_version), info
> AttributeError: 'module' object has no attribute 'Client'
> 

Thanks

**Comment by christopherhesse** [comment]
It looks like this uses Universe, which is no longer supported: https://github.com/openai/universe

There are other gym environments available, including [gym-retro](https://github.com/openai/retro) which has old video games and [μniverse](https://github.com/unixpickle/muniverse) which has a selection of javascript games to train on, and you can add your own.
