### ISSUE TITLE
ImportError:  Symbol not found: __ZdlPvm

### ISSUE THREAD

**Issue by tshrjn** [openai/gym#1122]
Hi, I've been trying to use the box2d envs. However, during `pip install -e '.[all]'` from the master, I kept getting the symbol not found. It seems to be linked with gcc/g++ versions. 

I tried different versions(5,6,7,8) of both gcc/g++ by first installing via homebrew and then symlinking them like `ln -s  gcc-8  gcc` in the `/usr/local/bin/`. Still kept getting the same error on trying to install the Box2D env.

So instead, I installed `pip install 'gym[all]'` which was successful.

However, now whenever I import Box2D env, I am faced with the following issue:

```
mportError: dlopen(/Users/tshrjn/anaconda3/lib/python3.6/site-packages/Box2D/_Box2D.cpython-36m-darwin.so, 2): Symbol not found: __ZdlPvm
  Referenced from: /Users/tshrjn/anaconda3/lib/python3.6/site-packages/Box2D/_Box2D.cpython-36m-darwin.so
  Expected in: /usr/lib/libstdc++.6.dylib
 in /Users/tshrjn/anaconda3/lib/python3.6/site-packages/Box2D/_Box2D.cpython-36m-darwin.so

```

Also, gym works fine with Atari, Classic Control, Robotics and even MuJoCo.

Versions:
Python 3.6.5
Gym 0.10.5

**Comment by danielnbarbosa** [comment]
@tshrjn If you just want Box2D, try `pip install gym Box2D box2d-py`.  Don't forget to install `swig` as well via either anaconda or brew.
