### ISSUE TITLE
Stella links needs updated!

### ISSUE THREAD

**Issue by yuezhilanyi** [openai/gym#1128]
stella links on [Pong-ram-v0](https://gym.openai.com/envs/Pong-ram-v0/) needs to be updated!
i cannot find any contact info on site above, so put it here.
can anyone solve this?

[Stella has left the building!](http://stella.sourceforge.net/)
> Stella has left the building!
> 
> As of January 1, 2017, the Stella project has moved to Github at https://stella-emu.github.io. As well, the codebase now uses Git instead of Subversion, so any developers must checkout from Git from this point forward. The new webpage includes instructions on how to set up Stella and Git. Developers can go directly to the Github devel page at https://github.com/stella-emu/stella.
> 
> If you reached this page from another website, please consider telling that website to update their links accordingly. This page (and all Stella-related items on Sourceforge) will be removed in approx. 3 months.
> 
> Thanks for the support,
> Steve A. and the Stella Team

**Comment by christopherhesse** [comment]
This is updated internally so it should appear next time we update the site.
