### ISSUE TITLE
gym/envs/robotics/hand/reach.py, see: Issue #1130 : use "choice" function with caution.

### ISSUE THREAD

**Issue by BStudent** [openai/gym#1131]
_This function does not seem to get nearly the coverage as those in #1130, however the presence of `choice()` might lead to people copying the code and using it in some more frequently-accessed module._

```Python
    def _sample_goal(self):
        thumb_name = 'robot0:S_thtip'
        finger_names = [name for name in FINGERTIP_SITE_NAMES if name != thumb_name]
        finger_name = self.np_random.choice(finger_names)

        thumb_idx = FINGERTIP_SITE_NAMES.index(thumb_name)
        finger_idx = FINGERTIP_SITE_NAMES.index(finger_name)
        assert thumb_idx != finger_idx
```
Note the use of `np_random.choice(....)` on the fourth line of code.

**Comment by christopherhesse** [comment]
np.random.choice is surprisingly slow but it's only called on reset and it's probably much faster than the mujoco stuff going on here.  I think fixing the blackjack one might be worth it since that could be called a lot, but I doubt this one is.
