### ISSUE TITLE
Reacher-v2 documentation

### ISSUE THREAD

**Issue by rajcscw** [openai/gym#1132]
Is there any place where Reacher-v2 is documented? I'm trying to understand the following:

- Description of actions. Are they controller angles ie. angles made by the arm segments?
- Also, how to get the position of the segments at any given point of time?

Any inputs would be helpful.

**Comment by christopherhesse** [comment]
We don't have documentation for observations/actions for individual environments, but in this case it looks like the actions are these actuators: https://github.com/openai/gym/blob/master/gym/envs/mujoco/assets/reacher.xml#L35

The observations will contain some information about positions: https://github.com/openai/gym/blob/master/gym/envs/mujoco/reacher.py#L37

If you want more than that, you can get individual object states through the mujoco-py api (should be env.unwrapped.data): https://openai.github.io/mujoco-py/build/html/reference.html#get_body_xpos
