### ISSUE TITLE
When making a new gym

### ISSUE THREAD

**Issue by jandevries123** [openai/gym#1133]
hey,

when making a new gym, what should the gym have for functions/returns?

i know for example of course render, step and reset but what is all you need?

also whiles on the subject how do i feed images to my algo in openaigym/how to return an image from a function in openaigym

thanks for helping

**Comment by pzhokhov** [comment]
Hi @jandevries123 ! 
The best starting point would be class gym.Env (https://github.com/openai/gym/blob/6332d4f113afbda7bb103412a16d9a3405be24b8/gym/core.py#L11)
It has methods that you need to implement along with the description of arguments and return parameters, and attributes that need to be set. 

Feeding images to the algorithm - usually, you can represent images as numpy arrays of shape (width, height, channels) (or (height, width, channels)), where channels is 1 for black and white, 3 for color; and values of the arrays are integers in range 0...255 (uint8). For an example of rendering such image, see, for instance, https://github.com/openai/gym/blob/6332d4f113afbda7bb103412a16d9a3405be24b8/gym/envs/atari/atari_env.py#L102. TensorFlow, Keras and pytorch all accept numpy arrays as inputs to the neural nets. 
Closing this, please reopen if some unclarity remains.
