### ISSUE TITLE
Playing against trained AI

### ISSUE THREAD

**Issue by raymondchua** [openai/gym#1134]
Hi,
Is there a way to play against the AI that we have trained?
For example in Pong and Boxing, this might be doable as it is a 2 players game.

**Comment by shuruiz** [comment]
There is. You can design your own environment pattern and use gym.make() to customize your settings.

**Comment by computerquest** [comment]
@shuruiz could you please elaborate on how this could be accomplished? I am new to gym, and this is not clear in the documentation.

**Comment by christopherhesse** [comment]
I don't know of a way to do this with the ALE atari games, but [gym-retro](https://github.com/openai/retro) includes poorly documented support for multiple players (see https://github.com/openai/retro/blob/master/retro/retro_env.py#L47 `players`) parameter.

You could train your agent on the normal mode, then use a script like https://github.com/openai/retro-movies/blob/master/human-recorder.py to play against your trained agent as long as it runs fast enough.

**Comment by CyanWatts** [comment]
> Hi,
> Is there a way to play against the AI that we have trained?
> For example in Pong and Boxing, this might be doable as it is a 2 players game.

Hey bro, I've got the same question as you said. But I do not quite understand Mr.Hesse's answer and still don know how to do so. So I'm wondering whether you please could give me some advice if possible. Many thanks！
