### ISSUE TITLE
Mujoco agent not fully tracked

### ISSUE THREAD

**Issue by rajcscw** [openai/gym#1135]
When I render the Half cheetah environment (also for other mujoco envs), I observe that camera is not moved automatically when the agent moves off the screen. Is this an issue or some manipulations to the camera to be done?

**Comment by R1ckF** [comment]
Hi,
I have exactly the same issue. Any new information available?

**Comment by pzhokhov** [comment]
Hi @rajcscw and @R1ckF! In mujoco env render, when you use mode 'human', Tab key allows you to move between viewpoints. One of the viewpoints is locked to the agent. Now if you are using rendering mode 'rgb_array' there is no good way to configure the viewpoint. Due to a recent bug  https://github.com/openai/baselines/issues/549 this also applies to replaying models in baselines.

**Comment by pzhokhov** [comment]
should be fixed now

**Comment by pzhokhov** [comment]
Tracking the agent in the `rgb_array` mode is not actually fixed (what was fixed is correct usage of mode='human' downstream). As such, let me reopen this issue

**Comment by pzhokhov** [comment]
also, as a temporary patch, you can add `camera_id=0` to the `render` argument here: https://github.com/openai/gym/blob/4ceff7dc096fa1c4fb56e68a1d6e34f4bff2870e/gym/envs/mujoco/mujoco_env.py#L105
(this will switch rendering `rgb_mode` rendering of mujoco envs to the tracking camera)

**Comment by rajcscw** [comment]
@pzhokhov  When I add that argument, it throws `Fixed camera id is outside valid range`

**Comment by pzhokhov** [comment]
@rajcscw which environment are you using?

**Comment by rajcscw** [comment]
@pzhokhov swimmer

**Comment by rajcscw** [comment]
Any updates on this @pzhokhov? This will be really helpful!

**Comment by pzhokhov** [comment]
@rajcscw sorry for the delay. Looks like specifically for swimmer the mujoco xml file does not include tracking camera. Here's a branch in which I have added a tracking camera: 
https://github.com/openai/gym/tree/issue1135
(specifically, here https://github.com/openai/gym/commit/82cae71acf11eaa0b994e397e8d476c7e8852f35)
It should also be used with `camera_id=0` fix from the discussion above. Changing the rgb_mode rendering behaviour merits releasing new version of the environments (or at least adding a gym.make kwarg now that we support them that defaults to old behaviour). PR on that is coming.

**Comment by pzhokhov** [comment]
oops closed accidentally, sorry and reopened

**Comment by rajcscw** [comment]
@pzhokhov Sorry for the delay, that worked perfectly! I assume the rest of the mujoco envs works fine already, have not tried it though.

**Comment by pzhokhov** [comment]
here's a PR that adds an optional kwarg that enables tracking in the rgb mode: https://github.com/openai/gym/pull/1405

**Comment by pzhokhov** [comment]
should be fixed now; I actually changed the default behavior to tracking rgb camera. The old behaviour can be restored by passing rgb_rendering_tracking=False kwarg. Also, a new version of pypi package is released.

**Comment by u6766669** [comment]
Is the keyword camera_id deleted?
 I got an error says "TypeError: render() got an unexpected keyword argument 'camera_id'" for Mujoco "Hopper-v2" environment

**Comment by rodrigodelazcano** [comment]
How are you using the `render()` method? There is a new render API that you can read more about in this [blog post](https://younis.dev/blog/render-api/). The `camera_id` argument is now passed when the environment is initialized:
```
env = gym.make('Hopper-v2', camera_id=0)
```

**Comment by u6766669** [comment]
@rodrigodelazcano Thanks for your reply, I tried to add this argument in gym.make(), but still not working. Maybe  my gym is too old (0.10.8). is it possible to have a tracking camera under the old version of gym?

**Comment by pseudo-rnd-thoughts** [comment]
Yes, 0.10.8 is too old
I suspect it won't have the camera tracking parameter

Quick question, why are you using 0.10.8

**Comment by u6766669** [comment]
Because I try to use openai baselines and the new version of gym would cast an import error. 
As I only need to render when evaluating, I bypass the problem by install gym 0.19.0 for evaluation and install gym 0.10.8 for training.
