### ISSUE TITLE
Problem adding own environment

### ISSUE THREAD

**Issue by hellandhansen** [openai/gym#1139]
Hi!

Tried adding my own environment. Followed the instructions exactly.

in envs folder, __init__.py: 

register(
    id='X-v0',
    entry_point='gym.envs.x:XEnv',
    max_episode_steps=200,
    reward_threshold=195.0,
)

in x folder,  __init__.py:

from gym.envs.x.x import XEnv

in x.py, I have:

class XEnv(gym.Env):

Still:

(open00) BAHHs-MBP:gym kodiak$ python -m baselines.run --alg=deepq --env=X-v0 --num_timesteps=1e6
Logging to /var/folders/sy/3rr0vmz10vg9gczm2p2rcw640000gn/T/openai-2018-08-24-11-19-01-089139
Traceback (most recent call last):
  File "/Users/kodiak/anaconda3/envs/open00/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/kodiak/anaconda3/envs/open00/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/kodiak/baselines/baselines/run.py", line 234, in <module>
    main()
  File "/Users/kodiak/baselines/baselines/run.py", line 213, in main
    model, _ = train(args, extra_args)
  File "/Users/kodiak/baselines/baselines/run.py", line 56, in train
    env = build_env(args)
  File "/Users/kodiak/baselines/baselines/run.py", line 136, in build_env
    raise ValueError('Unknown env_type {}'.format(env_type))
ValueError: Unknown env_type x

Any ideas? Much appreciated! :-)

**Comment by pzhokhov** [comment]
Hi @hellandhansen ! This is actually not an issue with gym, rather, with baselines (right now it is assumed that environment is either mujoco or atari). Will be lifted soon, for now, feel free to hack around by replacing https://github.com/openai/baselines/blob/0961f5dd94fbf2a97688c17870fa3714773d180e/baselines/run.py#L126 with "else:" (if you are not specifying network type explicitly, you may also need to modify https://github.com/openai/baselines/blob/0961f5dd94fbf2a97688c17870fa3714773d180e/baselines/run.py#L155)

**Comment by hellandhansen** [comment]
Hey Pzhokhov, that worked like a charm!

I’m now able to do what I want, have made a custom python game that I’ve run thru the algorithms. Will go on to more advanced stuff.

Thank you ever so much.

Kind regards

Bjørn A. Helland-Hansen


On 29 August 2018 at 05:41:21, pzhokhov (notifications@github.com) wrote:

Hi @hellandhansen ! This is actually not an issue with gym, rather, with baselines (right now it is assumed that environment is either mujoco or atari). Will be lifted soon, for now, feel free to hack around by replacing https://github.com/openai/baselines/blob/0961f5dd94fbf2a97688c17870fa3714773d180e/baselines/run.py#L126 with "else:" (if you are not specifying network type explicitly, you may also need to modify https://github.com/openai/baselines/blob/0961f5dd94fbf2a97688c17870fa3714773d180e/baselines/run.py#L155)

**Comment by pzhokhov** [comment]
Glad to hear :) Closing this
