### ISSUE TITLE
"error: pyglet.gl.lib.GLException: invalid enumerant "in pyglet

### ISSUE THREAD

**Issue by subercui** [openai/gym#115]
When doing the example: `python examples/agents/random_agent.py`

receive error:

> Traceback (most recent call last):
>   File "examples/agents/random_agent.py", line 36, in <module>
>     ob = env.reset()
>   File "/home/suber/Git/gym/gym/core.py", line 113, in reset
>     self.monitor._after_reset(observation)
>   File "/home/suber/Git/gym/gym/monitoring/monitor.py", line 233, in _after_reset
>     self.video_recorder.capture_frame()
>   File "/home/suber/Git/gym/gym/monitoring/video_recorder.py", line 105, in capture_frame
>     frame = self.env.render(mode=render_mode)
>   File "/home/suber/Git/gym/gym/core.py", line 164, in render
>     return self._render(mode=mode, close=close)
>   File "/home/suber/Git/gym/gym/envs/classic_control/cartpole.py", line 134, in _render
>     return self.viewer.get_array()
>   File "/home/suber/Git/gym/gym/envs/classic_control/rendering.py", line 104, in get_array
>     image_data = pyglet.image.get_buffer_manager().get_color_buffer().get_image_data()
>   File "/usr/local/lib/python2.7/dist-packages/pyglet/image/__init__.py", line 2090, in get_image_data
>     self.gl_format, GL_UNSIGNED_BYTE, buffer)
>   File "/usr/local/lib/python2.7/dist-packages/pyglet/gl/lib.py", line 104, in errcheck
>     raise GLException(msg)
> pyglet.gl.lib.GLException: invalid enumerant

**Comment by subercui** [comment]
Actually I found when doing `env.reset()` after `env.monitor.start()`, always receive this error. But `env.reset()` or `env.render()` alone works fine

**Comment by tlbtlbtlb** [comment]
This is likely a problem with compatibility of OpenGL libraries. What OS and graphical environment are you running in? Can you include the output of "pip list"?

**Comment by subercui** [comment]
OS：Ubuntu 14.04.4 LTS
NVIDIA-SMI 352.93     Driver Version: 352.93   
OpenGL version string: 1.4 (2.1 Mesa 10.5.4)

pip list:
> adium-theme-ubuntu (0.3.4)
> ale-python-interface (0.0.1)
> appdirs (1.4.0)
> apt-xapian-index (0.45)
> atari-py (0.0.18)
> backports-abc (0.4)
> backports.ssl-match-hostname (3.5.0.1)
> box2d-py (2.3.1)
> certifi (2015.11.20.1)
> chardet (2.0.1)
> colorama (0.2.5)
> command-not-found (0.3)
> cycler (0.9.0)
> Cython (0.23.4)
> debtagshw (0.1)
> decorator (4.0.6)
> defer (1.0.6)
> dirspec (13.10)
> doom-py (0.0.9)
> duplicity (0.6.23)
> easydict (1.6)
> et-xmlfile (1.0.1)
> FilenameSort (0.2.0)
> functools32 (3.2.3.post2)
> GifTiffLoader (0.2.1)
> graphviz (0.4.8)
> gym (0.1.1, /home/suber/Git/gym)
> h5py (2.5.0)
> html5lib (0.999)
> httplib2 (0.8)
> imageio (1.5)
> ipykernel (4.2.2)
> ipython (4.0.1)
> ipython-genutils (0.1.0)
> jdcal (1.2)
> Jinja2 (2.8)
> jsonschema (2.5.1)
> jupyter-client (4.1.1)
> jupyter-core (4.0.6)
> Lasagne (0.2.dev1, /home/suber/.local/lib/python2.7/site-packages)
> leveldb (0.193)
> lmdb (0.87)
> lockfile (0.8)
> lxml (3.3.3)
> Magic-file-extensions (0.2)
> Mako (1.0.3)
> MarkupSafe (0.23)
> matplotlib (1.5.1)
> mistune (0.7.1)
> mujoco-py (0.4.3)
> nbconvert (4.1.0)
> nbformat (4.0.1)
> networkx (1.10)
> nose (1.3.7)
> notebook (4.1.0)
> numexpr (2.5.2)
> numpy (1.11.0)
> oauthlib (0.6.1)
> oneconf (0.3.7.14.4.1)
> openpyxl (2.3.3)
> pachi-py (0.0.19)
> PAM (0.4.2)
> pandas (0.17.1)
> path.py (8.1.2)
> pexpect (4.0.1)
> pickleshare (0.5)
> Pillow (2.3.0)
> pillowfight (0.2)
> pip (8.1.1)
> piston-mini-client (0.7.5)
> protobuf (2.6.1)
> ptyprocess (0.5)
> py (1.4.31)
> pyasn1 (0.1.9)
> pycrypto (2.6.1)
> pycuda (2015.1.3)
> pycups (1.9.66)
> pycurl (7.19.3)
> pydicom (0.9.9)
> pydot (1.0.2)
> pyglet (1.2.4)
> Pygments (2.0.2)
> pygobject (3.12.0)
> pylearn2 (0.1.dev0, /home/suber/Git/pylearn2)
> PyOpenGL (3.1.0)
> pyOpenSSL (0.13)
> pyparsing (1.5.7)
> pyserial (2.6)
> pysmbc (1.0.14.1)
> pytest (2.8.5)
> python-apt (0.9.3.5ubuntu2)
> python-dateutil (1.5)
> python-debian (0.1.21-nmu2ubuntu2)
> python-gflags (2.0)
> python-xlib (0.14)
> pytools (2015.1.6)
> pytz (2012rc0)
> pyxdg (0.25)
> PyYAML (3.11)
> pyzmq (15.1.0)
> reportlab (3.0)
> requests (2.2.1)
> scikit-cuda (0.5.1)
> scikit-image (0.11.3)
> scikit-learn (0.17)
> scipy (0.17.0)
> sessioninstaller (0.0.0)
> setuptools (18.8)
> simplegeneric (0.8.1)
> singledispatch (3.4.0.3)
> six (1.10.0)
> sklearn (0.0)
> software-center-aptd-plugins (0.0.0)
> spyder (2.3.8)
> ssh-import-id (3.21)
> system-service (0.1.6)
> tables (3.2.2)
> terminado (0.6)
> Theano (0.8.0)
> tifffile (0.7.0)
> tornado (4.3)
> traitlets (4.0.0)
> Twisted-Core (13.2.0)
> Twisted-Web (13.2.0)
> unity-lens-photos (1.0)
> UNKNOWN (0.0.0)
> urllib3 (1.7.1)
> virtualenv (15.0.1)
> wheel (0.26.0)
> wxPython (2.8.12.1)
> wxPython-common (2.8.12.1)
> xdiagnose (3.6.3build2)
> zope.interface (4.0.5)

It shows PyOpenGL version is (3.1.0).

**Comment by tlbtlbtlb** [comment]
That should be well-supported. I have the same versions of the GL-related packages.

Would you mind running under a debugger, with
```
   $ python -m pdb examples/agents/random_agent.py
   (Pdb) c 
```

**Comment by subercui** [comment]
Sorry, which object `self `do you mean in  `self.gl_format`,` self.width`, `self.height` and `buffer` ?

**Comment by jietang** [comment]
@subercui @tlbtlbtlb any updates here?

**Comment by jietang** [comment]
Closing this as stale - happy to reopen if someone is still experiencing this.

**Comment by MultiPath** [comment]
HI, I experienced the same problem running this. I cannot run any scripts that needs recording.
Do you have any ideas?
pyglet.gl.lib.GLException: b'invalid enumerant'

**Comment by jaekyeom** [comment]
I'm having this issue too.

**Comment by tlbtlbtlb** [comment]
Do you have an X server capable of rendering OpenGL? You can test by running `glxinfo` (which will report detailed information on OpenGL modes) and `glxgears` (which will show a little visual demo). If these don't work, pyglet won't work either.

Please mention what sort of operating system and X server you're running in further reports.

**Comment by jaekyeom** [comment]
Actually, I've found a workaround. I'm not sure if it will fix other people's problems though.

I modified pyglet's source code. There is a method named `get_image_data` in `BufferImage` class.

In that method, I replaced `GLubyte` and `GL_UNSIGNED_BYTE` with `GLushort` and `GL_UNSIGNED_SHORT`, respectively.

Because `GL_UNSIGNED_BYTE` works with `GL_RGB` but doesn't seem to work with `GL_RGBA`.

I think there is something wrong the above as the resulting recording looks somewhat different from what it was supposed to be. But I didn't try more since I did not have enough time.

**Comment by jaekyeom** [comment]
I've just tried another thing, and it turned out to be the solution.

In `get_image_data` function inside `pyglet/image/__init__.py` file, I replaced
`        buffer = (GLubyte * (len(self.format) * self.width * self.height))()`
with
`        buffer = (GLubyte * (len(self.format) * self.width * self.height))(0)`

Now, videos are being recorded perfectly.

**Comment by ahoereth** [comment]
Any news here? Still running into this problem using nvidia-docker -- proposed workarounds did not fix it for me. When using normal docker everything works fine.

**Comment by jiameij** [comment]
hi i have the same problem
`File "demo.py", line 11, in <module>
    env.render()
  File "/home/jmj/anaconda3/lib/python3.5/site-packages/gym/core.py", line 150, in render
    return self._render(mode=mode, close=close)
  File "/home/jmj/anaconda3/lib/python3.5/site-packages/gym_dmcontrol/__init__.py", line 56, in _render
    self.viewer.update(pixels)
  File "/home/jmj/anaconda3/lib/python3.5/site-packages/gym_dmcontrol/viewer.py", line 12, in update
    self.window.clear()
  File "/home/jmj/anaconda3/lib/python3.5/site-packages/pyglet/window/__init__.py", line 1216, in clear
    gl.glClear(gl.GL_COLOR_BUFFER_BIT | gl.GL_DEPTH_BUFFER_BIT)
  File "/home/jmj/anaconda3/lib/python3.5/site-packages/pyglet/gl/lib.py", line 105, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: b'invalid operation'
` 
i try the mentioned methods above, however they does not work for me, oh, i can run "glxgears"
i use anaconda, python 3.5.4, cuda 8.0
NVRM version: NVIDIA UNIX x86_64 Kernel Module  384.111  Tue Dec 19 23:51:45 PST 2017
GCC version:  gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)
 and pip list:

absl-py (0.1.9)
alabaster (0.7.10)
anaconda-client (1.6.8)
anaconda-navigator (1.6.12)
anaconda-project (0.8.2)
asn1crypto (0.24.0)
astroid (1.6.0)
astropy (2.0.3)
attrs (17.4.0)
Babel (2.5.3)
backports.shutil-get-terminal-size (1.0.0)
beautifulsoup4 (4.6.0)
bitarray (0.8.1)
bkcharts (0.2)
blaze (0.11.3)
bleach (2.1.2)
bokeh (0.12.13)
boto (2.48.0)
Bottleneck (1.2.1)
certifi (2018.1.18)
cffi (1.11.4)
chardet (3.0.4)
click (6.7)
cloudpickle (0.5.2)
clyent (1.2.2)
colorama (0.3.9)
conda (4.4.8)
conda-build (3.3.0)
conda-verify (2.0.0)
contextlib2 (0.5.5)
cryptography (2.1.4)
cycler (0.10.0)
Cython (0.27.3)
cytoolz (0.9.0)
dask (0.16.1)
datashape (0.5.4)
decorator (4.2.1)
distributed (1.20.2)
dm-control (0.0.0)
docutils (0.14)
entrypoints (0.2.3)
enum34 (1.1.6)
et-xmlfile (1.0.1)
fastcache (1.0.2)
filelock (2.0.13)
Flask (0.12.2)
Flask-Cors (3.0.3)
future (0.16.0)
gevent (1.2.2)
glfw (1.5.1)
glob2 (0.6)
gmpy2 (2.0.8)
greenlet (0.4.12)
gym (0.9.5)
gym-dmcontrol (0.0.2)
h5py (2.7.1)
heapdict (1.0.0)
html5lib (1.0.1)
idna (2.6)
imageio (2.2.0)
imagesize (0.7.1)
ipykernel (4.8.0)
ipython (6.2.1)
ipython-genutils (0.2.0)
ipywidgets (7.1.0)
isort (4.2.15)
itsdangerous (0.24)
jdcal (1.3)
jedi (0.11.1)
Jinja2 (2.10)
jsonschema (2.6.0)
jupyter-client (5.2.2)
jupyter-console (5.2.0)
jupyter-core (4.4.0)
jupyterlab (0.31.1)
jupyterlab-launcher (0.10.2)
lazy-object-proxy (1.3.1)
llvmlite (0.21.0)
locket (0.2.0)
lxml (4.1.1)
MarkupSafe (1.0)
matplotlib (2.1.2)
mccabe (0.6.1)
mistune (0.8.3)
mpmath (1.0.0)
msgpack-python (0.5.1)
multipledispatch (0.4.9)
navigator-updater (0.1.0)
nbconvert (5.3.1)
nbformat (4.4.0)
networkx (2.1)
nltk (3.2.5)
nose (1.3.7)
notebook (5.3.1)
numba (0.36.2)
numexpr (2.6.2)
numpy (1.13.3)
numpydoc (0.7.0)
odo (0.5.1)
olefile (0.44)
openpyxl (2.4.10)
packaging (16.8)
pandas (0.22.0)
pandocfilters (1.4.2)
parso (0.1.1)
partd (0.3.8)
path.py (10.5)
pathlib2 (2.3.0)
patsy (0.5.0)
pep8 (1.7.1)
pexpect (4.3.1)
pickleshare (0.7.4)
Pillow (4.2.1)
pip (9.0.1)
pkginfo (1.4.1)
pluggy (0.6.0)
ply (3.10)
prompt-toolkit (1.0.15)
psutil (5.4.3)
ptyprocess (0.5.2)
py (1.5.2)
pycodestyle (2.3.1)
pycosat (0.6.3)
pycparser (2.18)
pycrypto (2.6.1)
pycurl (7.43.0.1)
pyflakes (1.6.0)
pyglet (1.3.0)
Pygments (2.2.0)
pylint (1.8.1)
pyodbc (4.0.22)
pyOpenSSL (17.5.0)
pyparsing (2.2.0)
PySocks (1.6.7)
pytest (3.3.2)
python-dateutil (2.6.1)
pytz (2017.3)
PyWavelets (0.5.2)
PyYAML (3.12)
pyzmq (16.0.3)
QtAwesome (0.4.4)
qtconsole (4.3.1)
QtPy (1.3.1)
requests (2.18.4)
rope (0.10.7)
ruamel-yaml (0.15.35)
scikit-image (0.13.1)
scikit-learn (0.19.1)
scipy (1.0.0)
seaborn (0.8.1)
Send2Trash (1.4.2)
setuptools (38.4.0)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.11.0)
snowballstemmer (1.2.1)
sortedcollections (0.5.3)
sortedcontainers (1.5.9)
Sphinx (1.6.6)
sphinxcontrib-websupport (1.0.1)
spyder (3.2.6)
SQLAlchemy (1.2.1)
statsmodels (0.8.0)
sympy (1.1.1)
tables (3.4.2)
tblib (1.3.2)
terminado (0.8.1)
testpath (0.3.1)
toolz (0.9.0)
tornado (4.5.3)
traitlets (4.3.2)
typing (3.6.2)
unicodecsv (0.14.1)
urllib3 (1.22)
wcwidth (0.1.7)
webencodings (0.5.1)
Werkzeug (0.14.1)
wheel (0.30.0)
widgetsnbextension (3.1.0)
wrapt (1.10.11)
xlrd (1.1.0)
XlsxWriter (1.0.2)
xlwt (1.3.0)
zict (0.1.3)

thanks~

**Comment by Pguhan** [comment]
Hello, 
I am facing the same error.
`[2018-03-26 20:20:47,648] Starting new video recorder writing to /home/pooja/deep-rl/ddpg/results/gym_ddpg/openaigym.video.0.13677.video000000.mp4
Traceback (most recent call last):
  File "ddpg.py", line 410, in <module>
    main(args)
  File "ddpg.py", line 377, in main
    train(sess, env, args, actor, critic, actor_noise)
  File "ddpg.py", line 276, in train
    s = env.reset()
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 104, in reset
    return self._reset()
  File "/usr/local/lib/python2.7/dist-packages/gym/wrappers/monitoring.py", line 41, in _reset
    self._after_reset(observation)
  File "/usr/local/lib/python2.7/dist-packages/gym/wrappers/monitoring.py", line 198, in _after_reset
    self._reset_video_recorder()
  File "/usr/local/lib/python2.7/dist-packages/gym/wrappers/monitoring.py", line 219, in _reset_video_recorder
    self.video_recorder.capture_frame()
  File "/usr/local/lib/python2.7/dist-packages/gym/monitoring/video_recorder.py", line 106, in capture_frame
    frame = self.env.render(mode=render_mode)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 150, in render
    return self._render(mode=mode, close=close)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 286, in _render
    return self.env.render(mode, close)
  File "/usr/local/lib/python2.7/dist-packages/gym/core.py", line 150, in render
    return self._render(mode=mode, close=close)
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/classic_control/pendulum.py", line 93, in _render
    return self.viewer.render(return_rgb_array = mode=='rgb_array')
  File "/usr/local/lib/python2.7/dist-packages/gym/envs/classic_control/rendering.py", line 94, in render
    image_data = buffer.get_image_data()
  File "/usr/local/lib/python2.7/dist-packages/pyglet/image/__init__.py", line 2090, in get_image_data
    self.gl_format, GL_UNSIGNED_BYTE, buffer)
  File "/usr/local/lib/python2.7/dist-packages/pyglet/gl/lib.py", line 104, in errcheck
    raise GLException(msg)

pyglet.gl.lib.GLException: invalid enumerant
[2018-03-26 20:20:48,394] Finished writing results. You can upload them to the scoreboard via `gym.upload('/home/pooja/deep-rl/ddpg/results/gym_ddpg')`

pip list gives me the following :

adium-theme-ubuntu (0.3.4)
atari-py (0.1.1)
azure (1.0.3)
azure-common (1.1.8)
azure-mgmt (0.20.2)
azure-mgmt-common (0.20.0)
azure-mgmt-compute (0.20.1)
azure-mgmt-network (0.20.1)
azure-mgmt-nspkg (2.0.0)
azure-mgmt-resource (0.20.1)
azure-mgmt-storage (0.20.0)
azure-nspkg (2.0.0)
azure-servicebus (0.20.1)
azure-servicemanagement-legacy (0.20.2)
azure-storage (0.20.3)
backports.functools-lru-cache (1.4)
backports.weakref (1.0rc1)
bleach (1.5.0)
certifi (2017.7.27.1)
chardet (3.0.4)
cycler (0.10.0)
decorator (4.0.6)
dill (0.2.7.1)
funcsigs (1.0.2)
functools32 (3.2.3.post2)
futures (3.1.1)
gevent (1.2.2)
greenlet (0.4.12)
gym (0.9.2)
h5py (2.7.1)
html5lib (0.9999999)
idna (2.6)
imageio (2.2.0)
joblib (0.11)
Keras (2.0.8)
keras-rl (0.3.1)
Markdown (2.6.9)
matlabengineforpython (R2017b)
matplotlib (2.0.2)
mock (2.0.0)
mujoco-py (0.5.7)
nose (1.3.7)
numpy (1.13.3)
olefile (0.44)
pbr (3.1.1)
Pillow (4.2.1)
pip (9.0.1)
pprintpp (0.3.0)
progressbar2 (3.34.2)
protobuf (3.4.0)
pybullet (1.6.3)
pyglet (1.2.4)
pygobject (3.20.0)
PyOpenGL (3.1.0)
pyparsing (2.2.0)
Pyrex (0.9.8.5)
Pyste (0.9.10)
python-dateutil (2.6.1)
python-utils (2.2.0)
pytz (2017.2)
PyYAML (3.12)
pyzmq (16.0.2)
requests (2.18.4)
scikit-learn (0.19.0)
scipy (0.19.1)
scour (0.32)
setuptools (36.3.0)
simplejson (3.8.1)
six (1.11.0)
subprocess32 (3.2.7)
tensorflow (1.3.0)
tensorflow-gpu (1.3.0)
tensorflow-tensorboard (0.1.5)
tflearn (0.3.2)
Theano (0.9.0)
tqdm (4.15.0)
unity-lens-photos (1.0)
urllib3 (1.22)
Werkzeug (0.12.2)
wheel (0.29.0)
zmq (0.0.0)

On running glxinfo , the following output is obtained :
name of display: localhost:10.0
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  24 (X_GLXCreateNewContext)
  Value in failed request:  0x0
  Serial number of failed request:  35
  Current serial number in output stream:  36
 
On running glxgears, the following output is obtained :
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  154 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  23
  Current serial number in output stream:  24

Any help would be appreciated.
Thanks!

**Comment by christopherhesse** [comment]
Does this issue exist with the current version of gym?

**Comment by sargamjain13** [comment]
Yes. I am facing the same issue with the current version of the gym. Any help is much appreciated.

**Comment by mahmoodn** [comment]
Using "ssh -Y" to enable X11 forwarding I hit the same error:

```
$ python -m pdb main.py
> /mnt/local/mahmood/pt/reinforcement_learning/main.py(1)<module>()
-> import gym
(Pdb) c
Traceback (most recent call last):
  File "/usr/lib/python2.7/pdb.py", line 1314, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib/python2.7/pdb.py", line 1233, in _runscript
    self.run(statement)
  File "/usr/lib/python2.7/bdb.py", line 400, in run
    exec cmd in globals, locals
  File "<string>", line 1, in <module>
  File "main.py", line 1, in <module>
    import gym
  File "main.py", line 99, in get_screen
    screen = env.render(mode='rgb_array').transpose((2, 0, 1))
  File "/home/mahmood/.local/lib/python2.7/site-packages/gym/envs/classic_control/cartpole.py", line 188, in render
    return self.viewer.render(return_rgb_array = mode=='rgb_array')
  File "/home/mahmood/.local/lib/python2.7/site-packages/gym/envs/classic_control/rendering.py", line 104, in render
    image_data = buffer.get_image_data()
  File "/home/mahmood/.local/lib/python2.7/site-packages/pyglet/image/__init__.py", line 2155, in get_image_data
    self.gl_format, GL_UNSIGNED_BYTE, buffer)
  File "/home/mahmood/.local/lib/python2.7/site-packages/pyglet/gl/lib.py", line 105, in errcheck
    raise GLException(msg)
GLException: invalid enumerant
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /home/mahmood/.local/lib/python2.7/site-packages/pyglet/gl/lib.py(105)errcheck()
-> raise GLException(msg)
```

the following packages are installed on ubuntu 18.04

```
$ dpkg -l | grep glx
ii  libglx0:amd64                                   1.0.0-2ubuntu2                       amd64        Vendor neutral GL dispatch library -- GLX support
ii  libxcb-glx0:amd64                               1.13-1                               amd64        X C Binding, glx extension
ii  libxcb-glx0-dev:amd64                           1.13-1                               amd64        X C Binding, glx extension, development files


$ dpkg -l | grep mesa
ii  libgl1-mesa-dev:amd64                           18.0.0~rc5-1ubuntu1                  amd64        free implementation of the OpenGL API -- GLX development files
ii  libgl1-mesa-dri:amd64                           18.0.0~rc5-1ubuntu1                  amd64        free implementation of the OpenGL API -- DRI modules
ii  libglapi-mesa:amd64                             18.0.0~rc5-1ubuntu1                  amd64        free implementation of the GL API -- shared library
ii  libglu1-mesa:amd64                              9.0.0-2.1build1                      amd64        Mesa OpenGL utility library (GLU)
ii  libglu1-mesa-dev:amd64                          9.0.0-2.1build1                      amd64        Mesa OpenGL utility library -- development files
ii  libwayland-egl1-mesa:amd64                      18.0.0~rc5-1ubuntu1                  amd64        implementation of the Wayland EGL platform -- runtime
ii  mesa-common-dev:amd64                           18.0.0~rc5-1ubuntu1                  amd64        Developer documentation for Mesa
ii  mesa-va-drivers:amd64                           18.0.0~rc5-1ubuntu1                  amd64        Mesa VA-API video acceleration drivers
ii  mesa-vdpau-drivers:amd64                        18.0.0~rc5-1ubuntu1                  amd64        Mesa VDPAU video acceleration drivers
```

**Comment by zzu0654** [comment]
I am facing the same error.

**Comment by zzu0654** [comment]
Traceback (most recent call last):
  File "DQN.py", line 320, in <module>
    pred, num_files)
  File "/data/zhcy/Projects/2D/v1/MARL-for-Anatomical-Landmark-Detection-master/common.py", line 106, in play_n_episodes
    render=render,agents=agents)
  File "/data/zhcy/Projects/2D/v1/MARL-for-Anatomical-Landmark-Detection-master/common.py", line 58, in play_one_episode
    obs,r, isOver, info = env.step(acts, q_values,isOver)      # 此处调用step（一步一步走）---num_success会加1------02
  File "/data/zhcy/Projects/2D/v1/MARL-for-Anatomical-Landmark-Detection-master/medical.py", line 1025, in step
    current_st, reward, terminal, info = self.env.step(act, q_values, isOver)           # step
  File "/data/zhcy/Projects/2D/v1/MARL-for-Anatomical-Landmark-Detection-master/medical.py", line 491, in step
    self.display()
  File "/data/zhcy/Projects/2D/v1/MARL-for-Anatomical-Landmark-Detection-master/medical.py", line 956, in display
    image_data = pyglet.image.get_buffer_manager().get_color_buffer().get_image_data()
  File "/data/zhcy/anaconda3/envs/tensorTest/lib/python3.6/site-packages/pyglet/image/__init__.py", line 2155, in get_imag
    self.gl_format, GL_UNSIGNED_BYTE, buffer)
  File "/data/zhcy/anaconda3/envs/tensorTest/lib/python3.6/site-packages/pyglet/gl/lib.py", line 105, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: b'invalid enumerant'

**Comment by zzu0654** [comment]
Traceback (most recent call last):
  File "DQN.py", line 320, in <module>
    pred, num_files)
  File "/data/zhcy/Projects/2D/v1/MARL-for-Anatomical-Landmark-Detection-master/common.py", line 106, in play_n_episodes
    render=render,agents=agents)
  File "/data/zhcy/Projects/2D/v1/MARL-for-Anatomical-Landmark-Detection-master/common.py", line 58, in play_one_episode
    obs,r, isOver, info = env.step(acts, q_values,isOver)      
  File "/data/zhcy/Projects/2D/v1/MARL-for-Anatomical-Landmark-Detection-master/medical.py", line 1025, in step
    current_st, reward, terminal, info = self.env.step(act, q_values, isOver)           # step
  File "/data/zhcy/Projects/2D/v1/MARL-for-Anatomical-Landmark-Detection-master/medical.py", line 491, in step
    self.display()
  File "/data/zhcy/Projects/2D/v1/MARL-for-Anatomical-Landmark-Detection-master/medical.py", line 956, in display
    image_data = pyglet.image.get_buffer_manager().get_color_buffer().get_image_data()
  File "/data/zhcy/anaconda3/envs/tensorTest/lib/python3.6/site-packages/pyglet/image/__init__.py", line 2155, in get_imag
    self.gl_format, GL_UNSIGNED_BYTE, buffer)
  File "/data/zhcy/anaconda3/envs/tensorTest/lib/python3.6/site-packages/pyglet/gl/lib.py", line 105, in errcheck
    raise GLException(msg)
pyglet.gl.lib.GLException: b'invalid enumerant'

**Comment by w00420198** [comment]
face the same problem with the latest pyglet version 1.5 and cuda10

**Comment by songya** [comment]
Face the same problem with the latest pyglet version 1.5 and cuda11
Using "ssh" to enable X11 forwarding I hit the same error.
