### ISSUE TITLE
Gym Step returned Observation

### ISSUE THREAD

**Issue by lhorus** [openai/gym#1159]
The documentation and examples aren't very clear on the subject of what exactly is returned by the Step function, for the observation argument.
The question being: is it supposed to link directly to a member of the observation_space (e.g., pointer style, or simply the returned object being an index of the observation_space), or simply any object which describes our new state? A tuple, an image, anything really.

**Comment by pzhokhov** [comment]
The assumption is that env.step() returns something that resembles an object from observation space (roughly speaking, something that has a non-zero probability of being returned from observation_space.sample()). For spaces.Box that would be a tensor of the same shape and dtype as observation_space.shape and observation_space.dtype respectively, for spaces.Discrete - an integer in the range 0..observation_space.n. For Dict and Tuple spaces same thing applies on a per-component basis.
