### ISSUE TITLE
Optimal Policy

### ISSUE THREAD

**Issue by lhorus** [openai/gym#1160]
Is there a method for obtaining the current optimal policy on the fly? Meaning, for optimal or convergence testing, considering with know the optimal policy obtained by other methods, is it possible to tell the environment that done = True, based on the RMSE between the current policy and that of the optimal?

**Comment by pzhokhov** [comment]
To my knowledge, there is no function call that would deliver the policy optimial for the environment; in fact, for many of the environments optimal policy is unknown. That being said, you can train a policy that is good enough, and then consider a progress of another policy being trained as some sort of distance between the two. Doing that is outside the scope of the gym, however.
