### ISSUE TITLE
not showing the cartpole

### ISSUE THREAD

**Issue by Shivam9034** [openai/gym#1161]
![image](https://user-images.githubusercontent.com/29898426/45415174-a8eb1e80-b69a-11e8-9e8f-0324c4103b92.png)

**Comment by pzhokhov** [comment]
you are trying to call env.step after the end of the episode (i.e. when environment has signaled 'done') without resetting. Let's modify your snippet a little bit: 
```
import gym
env = gym.make('CartPole-v0')
env.reset()
for _ in range(1000):
    env.render()
    observation, reward, done, info = env.step(env.action_space.sample())
    if done: 
        env.reset()
env.close()
```
that should work and show the cart (whenever it does a "jump" to the center, the environment is being reset)

**Comment by Pibastte** [comment]
I have added a sleep(0.03) in the for loop and it now works, I think every frame was being displayed to quickly so nothing was really shown on display. Here is my final code:

`import gym
from time import sleep

env = gym.make('CartPole-v0')
env.reset()
for _ in range(100):
    env.step(env.action_space.sample()) # take a random action
    env.render()
    sleep(0.03)
env.close()`
