### ISSUE TITLE
Missing __eq__ method in MultiDiscrete

### ISSUE THREAD

**Issue by araffin** [openai/gym#1171]
Hello,
it seems that the `__eq__` method that allows to compare two MultiDiscrete objects was removed in 4c460ba6c8959dd8e0a03b13a1ca817da6d4074f.

Is there any reason of that change? Should I submit a PR to fix that?

Related to https://github.com/hill-a/stable-baselines/issues/25

**Comment by pzhokhov** [comment]
@joschu could you comment? Otherwise, looks like we can __eq__ and __repr__ methods back.

**Comment by araffin** [comment]
@pzhokhov I don't think the previous function will work, according to the changelog:
"Changed `MultiDiscrete` action space to range from `[0, ..., n-1]` rather than `[a, ..., b-1]`."

Note that the same issue exist for MultiBinary space.

**Comment by pzhokhov** [comment]
fair; so it should be a comparison of self.nvec and other.nvec in MultiDiscrete case. Looks like for MultiBinary it was not removed in the same commit (maybe never existed in the first place), and __eq__ should be comparing self.n and other.n, I think. Sound like a reasonable thing to have; please feel free to submit a PR
