### ISSUE TITLE
Breakout-v4 does not step

### ISSUE THREAD

**Issue by nevakanezzar** [openai/gym#1175]
Environment for Breakout-v4 does not step in case it is provided only 0, 2, or 3 as actions.

Minimum Working Example:

```
import gym

GAME = "Breakout-v4"
#GAME = "MsPacman-v4"

env = gym.make(GAME)
env.reset()

while 1:
    aa = 0 #env.action_space.sample()
    _,_,e_done,_ = env.step(aa)
    print(aa)
    env.render()
    if e_done:
        break

env.close()
```

This currently hangs. aa = 2 and aa = 3 do not work either.

Replacing the game with MsPacman-v4 works as expected. Replacing aa = 0 with actions sampled from env.action_space works as expected.

**Comment by pzhokhov** [comment]
This is not a bug, but a property of Breakout. In the starting state, the game waits for player(actor) to hit fire (action 1). Game starts with 5 lives; and every time player (actor) fails to return the ball, number of lives goes down and the game waits for fire again. Hence, if you pass constant actions that are not 1, the actual game never starts. 

You should try playing the game yourself with the keyboard, it is fun :) You can use the following script (may need a couple of extra dependencies though):
```
import gym 
from gym.utils.play import play

GAME = "Breakout-v4"
# GAME = "MsPacman-v4"

env = gym.make(GAME)
play(env)
```
A key is left, D is right, space is fire.
