### ISSUE TITLE
FrozenLake env - trying to get image from the env.render(mode='rgb_array') but fails

### ISSUE THREAD

**Issue by Rajshreed** [openai/gym#1179]
Plt.imshow(env.render(mode='rgb_array'))
this fails and gives Type Error 

TypeError: Image data can not convert to float on plt.imshow()

Does the OpenAI gym have the rgb_array and if yes, how do i extract the image to display it on screen?

**Comment by christopherhesse** [comment]
@nautilusPrime is correct, sorry about that!
