### ISSUE TITLE
MountainCarContinuous-v0 NaN reward

### ISSUE THREAD

**Issue by TM6501** [openai/gym#1184]
The MountainCarContinuous-v0 environment occasionally returns 'NaN' as the return reward from the environment.step(action) function call.  

I've been unable to reproduce it consistently, though it is frequent and generally after it happens once, all subsequent calls to environment.step() will return a 'NaN' reward until the environment is reset.

**Comment by ishan00** [comment]
Hello, I tried to reproduce this but was unable to do so. Could you please post the observation of the environment (ie `[position, velocity]`) when the reward turns NaN.

Also I looked at the code of `step` for MountainCarContinuous which I am copying below. I couldn't find any line where NaN might appear. It may be the case that the action you are providing to the environment is itself NaN in which case the `math.pow` will return NaN.

https://docs.python.org/2/library/math.html#math.pow

```python
def step(self, action):

        position = self.state[0]
        velocity = self.state[1]
        force = min(max(action[0], -1.0), 1.0)

        velocity += force*self.power -0.0025 * math.cos(3*position)
        if (velocity > self.max_speed): velocity = self.max_speed
        if (velocity < -self.max_speed): velocity = -self.max_speed
        position += velocity
        if (position > self.max_position): position = self.max_position
        if (position < self.min_position): position = self.min_position
        if (position==self.min_position and velocity<0): velocity = 0

        done = bool(position >= self.goal_position)

        reward = 0
        if done:
            reward = 100.0
        reward-= math.pow(action[0],2)*0.1

        self.state = np.array([position, velocity])
        return self.state, reward, done, {}
```

**Comment by TM6501** [comment]
When attempting to collect observations to post here, I found that what you suspected is true: NaN is only returned when NaN is passed in.  So, the bug is in my agent, not in the environment.   If you're still interested, I get observations of [nan nan] when the reward is nan.

Sorry to have wasted your time; I wasn't aware of this bug in my code as it seems to only crop up with this particular environment.
