### ISSUE TITLE
Define enviroment

### ISSUE THREAD

**Issue by asiscrus** [openai/gym#1194]
Hi,

I try to define enviroment at gym --pyhton, monte carlo method. My state is 7 rows and my actions is 7 cloumns. There is a extra information about the actions as follows;

              action 1    action 2   action 3   action 4   action 5   action6   action 7
State 1       3r              2r             r             3r             2r             r             0
State 2       3r              2r             r             3r             2r             r             0
State 3       3r              2r             r             3r             2r             r             0
State 4       3r              2r             r             3r             2r             r             0
State 5       3r              2r             r             3r             2r             r             0
State 6       3r              2r             r             3r             2r             r             0
State 7       3r              2r             r             3r             2r             r             0

Some extions' rewars are 3 times or 2 times of others.

How can create an enviroment. Can you help me, please?

**Comment by ishan00** [comment]
Creating new environment for gym
https://github.com/openai/gym/tree/master/gym/envs#how-to-create-new-environments-for-gym

All you need to do is define the following functions for this environment
```python
def __init__(self):
    ...
def step(self, action):
    ...
def reset(self):
    ...
```

It isn't clear what these actions achieve. Does taking action `i` in state `j` takes you to state `i`?

**Comment by ishan00** [comment]
For the reward table you mentioned, the reward only depends on the action taken and not the state in which the agent is. Also since you mentioned the states are random (irrespective of the action taken)

```python
import numpy as np

def __init__(self):
	self.state = ... # Start State 
	self.reward_table = [3, 2, 1, 3, 2, 1, 0]

def step(self, action):
	reward = self.reward_table[action]
	self.state = np.random.randint(0,7)
	return self.state, reward
```
If you want a reward table which depends on `(state, action)` to decide the reward. You can create the reward table as matrix and then find reward using 
```python
reward = self.reward_table[self.state][action]
```

I hope this was helpful.

**Comment by asiscrus** [comment]
Thank you so much for information and your help, ishan00. Best.

I know all states on my envirement. However, I don't know when they accour. And they are not related to actions. Also, I don't know the reward excatly.

Forexample: 
If state1 occured, then if the agent choose action 1, the reward will be 3 or -3. Imagine, the agent has success then the reward will be 3, has not success then the reward will be -3.

I don't know how I create this envirement exactly. I read montecarlo methos is suitable when envirement is uncertain. But how can I create this envirement.

Thank you again your knowledge.
Best, Murat Y.

**Comment by christopherhesse** [comment]
Thanks for helping @ishan00.  This sounds like more of a general programming question than a gym question.  You probably want to do `random.random()` when the agent chooses action 1 and then decide based on that what the reward and next state should be.
