### ISSUE TITLE
Import Error when trying to use custom environment 

### ISSUE THREAD

**Issue by atrox1227** [openai/gym#1197]
I have created a custom environment to the exact specifications that are listed here:

https://github.com/openai/gym/tree/master/gym/envs

I have the exact file structure and init components listed. I have inserted the folder with all my files in the envs folder of the gym package (created a new folder for my environment, I didn't add it into any of the existing folders). I have added the registration of my environment into the main gym registration init, and it does work because the custom environment shows up when I give the command: print(envs.registry.all()) 

When I try the command:

gym.make('myEnv-v0')

I get the error:

ImportError: cannot import name 'myEnv'

Trace-back shows the error occurring in the init that is similar to:

"from gym_foo.envs.foo_env import FooEnv"

as is recommended in the link I gave above. I have spent hours trying the figure out how to fix this and would appreciate any help.

**Comment by atrox1227** [comment]
I went into my code for the environment and noticed that instead of defining "render", I was instead defining "_render". Changed this and problem went away.

**Comment by HarshayuGirase** [comment]
im getting the same error, but inside the render method im doing nothing
