### ISSUE TITLE
Need to add UTF-8 encoding 

### ISSUE THREAD

**Issue by mateoguaman** [openai/gym#1201]
When I ran the CarPole-v0 example from the documentation, it gave me an error until I included UTF-8 encoding to that file

**Comment by pzhokhov** [comment]
@mateoguaman could you provide more details please, specifically, code snippet that you ran, and error stacktrace? Thanks!

**Comment by christopherhesse** [comment]
Should be fixed in https://github.com/openai/gym/pull/1314
