### ISSUE TITLE
Custom Key Bindings with Mujoco

### ISSUE THREAD

**Issue by tanmaybinaykiya** [openai/gym#1202]
I am using the FetchPickandPlace environment and I wish to provide some initial configuration through keyboard inputs, but it seems like the key handler callback function is registered by mujoco in mujoco_py/MjViewer::key_callback. 
Is there a way to add a custom callback function in addition to this ?

**Comment by christopherhesse** [comment]
This sounds like an issue with mujoco_py, could you file the issue on that repo?
