### ISSUE TITLE
why MultiDiscrete  dtype=int8 

### ISSUE THREAD

**Issue by ftao** [openai/gym#1204]
MultiDiscrete  dtype is hardcoded as int8. 
Is this a bug ? What happens when  we need more than 256 category  
```
space = MultiDiscrete([7, 1024])
space.sample()
```

https://github.com/openai/gym/blob/e944885e3b31a10fb6973093b39ff7682ef3aa3d/gym/spaces/multi_discrete.py#L10

**Comment by christopherhesse** [comment]
That is a little surprising, since normal discrete is int64, @pzhokhov should this be set to an int64?
