### ISSUE TITLE
How can I configure negative rewards in FetchReach environments?

### ISSUE THREAD

**Issue by WuXinyang2012** [openai/gym#1205]
Hi guys, I am now having a project, which is about how to control the robotic arm to fetch something while avoiding hurting the surrounding workers. 

That means, just like in the FetchReach environment, there is not only a target point, which is in red color,  but also a black point, which shall be avoided collisions when the robotic arm moves. 

In the gym environment, there are only 0 reward for not reaching the target, and 1 reward for reaching the target. But now I want to add a -1 negative reward as the penalty for reaching the collision point.

Can you please tell me how to congifure the rewards in the gym environment? How to add the negative rewards for reaching some unwanted areas? Thanks.

**Comment by tkelestemur** [comment]
You can change the reward function defined in [fetch_env](https://github.com/openai/gym/blob/master/gym/envs/robotics/fetch_env.py#L53). You need to check the collision information and I'm not sure if you can get that from mujoco-py but you can probably implement a collision checker using primitive shapes.

**Comment by WuXinyang2012** [comment]
@tkelestemur Very thanks for your reply. I understand how to change the reward now but about the collision, it seems that the mujoco-py does not support this collision information. 
I will try to refer to the mujoco documentation to see what are the primitive shapes.
btw, do u know about the dm_control suite from Google? It seems they implement also a mujoco python binding but with newer version and more interfaces.

**Comment by christopherhesse** [comment]
I believe @tkelestemur is correct, thanks!  You would also need to probably update code in https://github.com/openai/gym/blob/master/gym/envs/robotics/robot_env.py
