### ISSUE TITLE
Missing path to your environment variable. 

### ISSUE THREAD

**Issue by ssghost** [openai/gym#1208]
I encountered this exception when try to use Mujoco-150 on Google Colab:
```

Exception: 
Missing path to your environment variable. 
Current values LD_LIBRARY_PATH=/usr/lib64-nvidia
Please add following line to .bashrc:
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/root/.mujoco/mjpro150/bin
```
I added this path to .bashrc but it returns that , "No such file or directory"

What's wrong with it?

**Comment by christopherhesse** [comment]
This seems to be an issue with `mujoco-py`, could you file the issue over at https://github.com/openai/mujoco-py?  Thanks!
