### ISSUE TITLE
Inconsistency in when to calc reward (MuJoCo)

### ISSUE THREAD

**Issue by fgolemo** [openai/gym#1210]
Hey, I just noticed that some MJC environments have the reward calculation **before** executing the step in simulation (like Reacher, Pusher, Striker) and some have it **after** simulating the action (like Ant, Swimmer, HalfCheetah). 

What's the reasoning behind this?

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
