### ISSUE TITLE
gym with windows and javascript

### ISSUE THREAD

**Issue by javismiles** [openai/gym#1211]
good day,
I installed the gym on windows with Ubuntu and python + Xming server, and all works well.
But then I tried to use it with javascript by following these instructions:

https://xaviergeerinck.com/running-openai-gym-on-windows-and-js

but it fails with the following issues:

a) all goes well until this command:
"sudo pip install -e '.[all]'
which returns "Directory '.' is not installable. File 'setup.py' not found."

b) the other issue I found is that I can install nodejs no probs, but not npm,
installing npm on ubuntu-windows with :  sudo apt-get install npm, after having installed nodejs (which doesnt install npm alongside it, curious), returns:

Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 npm : Depends: nodejs but it is not going to be installed
       Depends: node-abbrev (>= 1.0.4) but it is not going to be installed
       Depends: node-ansi (>= 0.3.0-2) but it is not going to be installed
       Depends: node-ansi-color-table but it is not going to be installed
       Depends: node-archy but it is not going to be installed
       Depends: node-block-stream but it is not going to be installed
       Depends: node-fstream (>= 0.1.22) but it is not going to be installed
       Depends: node-fstream-ignore but it is not going to be installed
       Depends: node-github-url-from-git but it is not going to be installed
       Depends: node-glob (>= 3.1.21) but it is not going to be installed
       Depends: node-graceful-fs (>= 2.0.0) but it is not going to be installed
       Depends: node-inherits but it is not going to be installed
       Depends: node-ini (>= 1.1.0) but it is not going to be installed
       Depends: node-lockfile but it is not going to be installed
       Depends: node-lru-cache (>= 2.3.0) but it is not going to be installed       Depends: node-minimatch (>= 0.2.11) but it is not going to be installed
       Depends: node-mkdirp (>= 0.3.3) but it is not going to be installed
       Depends: node-gyp (>= 0.10.9) but it is not going to be installed
       Depends: node-nopt (>= 3.0.1) but it is not going to be installed
       Depends: node-npmlog but it is not going to be installed
       Depends: node-once but it is not going to be installed
       Depends: node-osenv but it is not going to be installed
       Depends: node-read but it is not going to be installed
       Depends: node-read-package-json (>= 1.1.0) but it is not going to be installed
       Depends: node-request (>= 2.25.0) but it is not going to be installed
       Depends: node-retry but it is not going to be installed
       Depends: node-rimraf (>= 2.2.2) but it is not going to be installed
       Depends: node-semver (>= 2.1.0) but it is not going to be installed
       Depends: node-sha but it is not going to be installed
       Depends: node-slide but it is not going to be installed
       Depends: node-tar (>= 0.1.18) but it is not going to be installed
       Depends: node-underscore but it is not going to be installed
       Depends: node-which but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

and this  point I tried many things without success,
any advice much appreciated, as I say it all works well with python-ubuntu-windows, but it would be interesting to make it work with javascript

**Comment by christopherhesse** [comment]
I'm afraid we don't officially support windows at this time, nor is `gym-http-api` supported.  I believe gym does work on windows, but you should probably try getting it working with python first before trying to get node.js to work with it.  Sorry about that!
