### ISSUE TITLE
mujoco-py environments accept NaNs

### ISSUE THREAD

**Issue by machinaut** [openai/gym#1212]
I'm not sure if we want to incur this cost overhead per-step, but right now you can pass actions to mujoco environments which contain NaNs.

These end up generating the super-unhelpful message `Unknown warning type`

I think my recommendation would be to assert that input doesn't contain NaNs every step.  @pzhokhov let me know if that works for you and I can send a PR.

**Comment by pzhokhov** [comment]
I think that works, please send a PR!

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
