### ISSUE TITLE
[feature-request] General classes for multi-agent problems and/or turn and phase based games

### ISSUE THREAD

**Issue by gvgramazio** [openai/gym#1213]
One of the good point of gym is that it's easily expandable and reusable. However it's still stuck to basic problem, that are single player mode with only one phase of the game.

It would be good to have at least a general class that expand this in order to create new environments to experiment with a larger class of games. Of course, one could easily implement the class itself but then there would be compatibility issues between each implementation. Right now gym is the standard in the evaluation of machine learning algorithms and I think that a good idea could be implement multi-agent environments and turn and phase based environment.

- An example of two-agent environment could be pong where both agent act at the same time.
- Examples of two-agent, turn-based environment could be battleship, chess and checkers where agents alternate in acting (also it's time discrete and not time continuous).
- An example of multi-agent, turn and phase based could be poker (actually almost any variant of it) where at each turn a different agent took action and has also different phases because the length of the observations changes and also the type of actions. Plus, at each different turn-phase pair we could have a different amount of agent currently active (that haven't folded yet).

What do you think should be the requirements of such type of gym environment implementations? Do you think that they could be implemented anytime soon? If someone implements them, would you accept a pull request?

Note that I'm more interested in the general implementation of the parent class than of the actual environment.

**Comment by gvgramazio** [comment]
I just found out that a similar problem was already discussed in #934.

**Comment by christopherhesse** [comment]
Closing in favor of https://github.com/openai/gym/issues/934
