### ISSUE TITLE
MultiDiscrete - Poorly documented source code 

### ISSUE THREAD

**Issue by LUKELIEM** [openai/gym#1214]
In the original multi_discrete.py (version 0.9.2), the author took care to document what input is acceptable:

class MultiDiscrete(gym.Space):
    """
    - The multi-discrete action space consists of a series of discrete action spaces with different parameters
    - It can be adapted to both a Discrete action space or a continuous (Box) action space
    - It is useful to represent game controllers or keyboards where each key can be represented as a discrete action space
    - It is parametrized by passing an array of arrays containing [min, max] for each discrete action space
       where the discrete action space can take any integers from `min` to `max` (both inclusive)

    Note: A value of 0 always need to represent the NOOP action.

    e.g. Nintendo Game Controller
    - Can be conceptualized as 3 discrete action spaces:

        1) Arrow Keys: Discrete 5  - NOOP[0], UP[1], RIGHT[2], DOWN[3], LEFT[4]  - params: min: 0, max: 4
        2) Button A:   Discrete 2  - NOOP[0], Pressed[1] - params: min: 0, max: 1
        3) Button B:   Discrete 2  - NOOP[0], Pressed[1] - params: min: 0, max: 1

    - Can be initialized as

        MultiDiscrete([ [0,4], [0,1], [0,1] ])

    """

Some smart guy decides to change the data structure, but does not even document an example for the changes he had made. This is really unacceptable coding!!!

**Comment by christopherhesse** [comment]
Sorry about that, @pzhokhov is the description easy to add back in?

**Comment by pzhokhov** [comment]
https://github.com/openai/gym/pull/1373

**Comment by pzhokhov** [comment]
merged, closing this
