### ISSUE TITLE
Taxi-v2 results render fails

### ISSUE THREAD

**Issue by chaule97** [openai/gym#1215]
When i run this code
```
env = gym.make('Taxi-v2').env
env.render()
```
Command line show
```
+---------+
|[34;1mR[0m: | : :[35mG[0m|
| : : : :[43m [0m|
| : : : : |
| | : | : |
|Y| : |B: |
+---------+
```
I thinks pyglet and gym are wrong.
Please help me. Thankyou

**Comment by bmwant** [comment]
@chaule97 give your OS (type, version), python version and terminal you are using
It's probably the issue with your terminal because you are seeing escape sequences for colored/bolded text

**Comment by SunLightFor6** [comment]
[Python: How can I make the ANSI escape codes to work also in Windows?](https://stackoverflow.com/a/12493201)

It's really about the escape sequences in windows.

**Comment by christopherhesse** [comment]
As others have pointed out, this looks like an issue with escape sequences, possibly due to running on windows :/

**Comment by shashwat-vik** [comment]
Found [this answer](https://stackoverflow.com/questions/36760127/how-to-use-the-new-support-for-ansi-escape-sequences-in-the-windows-10-console/36760881#36760881) that resolved the ANSI escape sequence issue on Windows console environments.
