### ISSUE TITLE
Why are there hidden objects in the robotics environments?

### ISSUE THREAD

**Issue by llach** [openai/gym#1216]
While working with the robotics environments, I noticed, that both [block](https://github.com/openai/gym/blob/master/gym/envs/robotics/assets/hand/manipulate_block.xml#L29) and [egg](https://github.com/openai/gym/blob/master/gym/envs/robotics/assets/hand/manipulate_egg.xml#L28) environments define hidden objects for the scene.  For the pen environment, this hidden object is missing.
In the code the only time the hidden object is explicitly use is [here](https://github.com/openai/gym/blob/master/gym/envs/robotics/hand/manipulate.py#L250).

It is not obvious to me, what these hidden objects are good for. Can anyone explain to me the purpose of these hidden objects and why pen environment has none?

**Comment by christopherhesse** [comment]
@aray-openai any ideas why those hidden objects are there?
