### ISSUE TITLE
render image corrupt

### ISSUE THREAD

**Issue by rnunziata** [openai/gym#1217]
I've been having this issue when I set env.render the screen that is displayed is bad....not sure how to fix.
I have tried many setting mode grab_rgb.

![screenshot from 2018-11-07 17-31-18](https://user-images.githubusercontent.com/5377074/48221038-ef898c00-e35e-11e8-904f-c05592c341e9.png)

**Comment by christopherhesse** [comment]
Do you have a simple script that reproduces this issue?

**Comment by rnunziata** [comment]
no...unfortunately I no longer have this project installed.  I used a different  system for my work.
