### ISSUE TITLE
Box2d installation error blocking gym installation

### ISSUE THREAD

**Issue by ahuhn** [openai/gym#1221]
Box2d won't install with Python3.7 from Anaconda on Mac. This blocked me from installing the gym environment for a bit. 

It threw this error when I ran pip install -e '.[all]'
> warning: include path for stdlibc++ headers not found; pass '-std=libc++' on the command line to use the libc++ standard library instead [-Wstdlibcxx-not-found]
> Box2D/Box2D_wrap.cpp:3033:10: fatal error: 'string' file not found

This is the same issue as https://github.com/erincatto/Box2D/issues/524?fbclid=IwAR3E0WbMkFPkiHC1WM-u35VhXuf-Iq9-XQ7QDS1_DWuixAMn6WLbm-yKsGY

I was able to install box2d using the same solution as the link above:
- I installed a new copy of python through brew
- I used that python's pip to install box2d
- I used my usual anaconda python's pip to do pip install -e '.[all]'

My particular situation is solved, but I'm adding a note here to let you know in case it blocks other people and you want to fix it.

Thanks!

**Comment by yimingmao** [comment]
I have the exact same problem, seems xcode 10 removed some things

**Comment by chubakur** [comment]
Try to install box2d-py at the first.

**Comment by christopherhesse** [comment]
The current version of gym requires `box2d-py` https://github.com/openai/gym/blob/master/setup.py#L11 which should fix this issue, let me know if that's not the case.

**Comment by TheCoderMan2000** [comment]
@christopherhesse This did not work for me. I tried to install the module 'version' but it game me the error
`Command "python setup.py egg_info" failed with error code 1 in C:\Users\user\AppData\Local\Temp\pip-install-alq8ppcv\version\`
