### ISSUE TITLE
Statefull bug with reward -- Blackjack-v0

### ISSUE THREAD

**Issue by act65** [openai/gym#1223]
Ok, I am getting a weird statefull bug that I cant seem to figure out.
Every loop, the reward is being reset to zero. I even tried `deepcopy`ing the reward but it still didnt work.
Here is some code to reproduce.

```python
import gym

def run_episode(env):
    obs = env.reset()
    done = False
    R = 0
    reward = 0

    while not done:
        print(reward)
        print('\n')
        obs, reward, done, info = env.step(env.action_space.sample())
        print(reward)
        R += reward
    return R
        

if __name__=='__main__':
    env = gym.make('Blackjack-v0')
    print(sum([run_episode(env)for _ in range(100)])/100)
```

You should see that the two printed rewards are different.
(note this code works fine for other envs)

**Comment by 0Zeta** [comment]
This is because the while loop is only executed once for every call of `run_episode()`. As a result reward is set to 0 at the beginning of each run.

**Comment by christopherhesse** [comment]
Thanks for answering the question @0Zeta!
