### ISSUE TITLE
MountainCar-v0 with Deep-Q example doesn't converge

### ISSUE THREAD

**Issue by thomelane** [openai/gym#1225]
`baselines/deepq/experiments/train_mountaincar.py` doesn't converge and remains at -200 mean episode reward. I'm assuming these experiments have been added because they are working (rather than just used as a starting point), so would be good to fix.

My training log can be found here: https://gist.github.com/thomelane/06ea3fe1868e1bbdf377980569996f93

**Comment by christopherhesse** [comment]
Thanks, but could you file this issue on baselines instead?  This should be specifically bugs in gym.
