### ISSUE TITLE
Mujoco environments in the DDPG paper

### ISSUE THREAD

**Issue by ascane** [openai/gym#1226]
I am trying to find the Mujoco environments described in the DDPG paper in section 9.2: https://arxiv.org/pdf/1509.02971.pdf

I did find some in gym/envs/mujoco/, but not all of them. I wonder if they are open-sourced. I am particularly interested in using the blockworld3da.

Any pointers would be much appreciated.

**Comment by Sohojoe** [comment]
These are from another deepmind paper but I don't see blockworld3da

 https://github.com/deepmind/dm_control/tree/c24ec9f5f3cb3c25c6571c89c9f60bf3350f5711/dm_control/suite

**Comment by christopherhesse** [comment]
As @Sohojoe pointed out, that is a deepmind paper and it looks like they used their own custom environments that I didn't see available anywhere.  https://github.com/stevenpjg/ddpg-aigym looks to be an implementation of ddpg using gym environments.  In addition, @Sohojoe has some cool unity environments that you may want to look at: https://github.com/Unity-Technologies/marathon-envs
