### ISSUE TITLE
Is noise added to controls?

### ISSUE THREAD

**Issue by Ploppz** [openai/gym#1235]
I made an agent for `Acrobot-v1` that keeps doing action 0 (torque = -1). The result looks very noisy and not as I expected. When it does action 1 (torque = 0), I would expect the acrobot to be still, but it seems to be perturbed by some noise. In the source code of Acrobot-v1, I have disabled the torque noise (however, the noise is set to 0 by default). So I think there must be something in the Gym framework.

**Comment by christopherhesse** [comment]
So if you initialize it to zero state, it will be stationary.  However it's initialized to a random state and has no friction component.  If you say `ns[3] *= 0.9` and `ns[4] *= 0.9` in `acrobot.py` you can add some damping which causes it to stop moving after some time.
