### ISSUE TITLE
window opens but not rendering

### ISSUE THREAD

**Issue by jaxwagner** [openai/gym#1236]
After following the install instructions for mac, I seem to have gotten everything installed correctly and am not getting any errors, but I don't get anything rendering no matter what environment I use, I just get a blank window appearing   (running 10.14.1) any advice? I have tried reinstalling pybox2d and gym, that didn't seem to work.
![image](https://user-images.githubusercontent.com/28873065/49042258-99597d00-f195-11e8-8df4-aea7d42d85e4.png)

**Comment by vsaraph** [comment]
Also having this issues.

**Comment by fragyuan** [comment]
I had this issue before, solved after upgrading to macOS 10.14.2

**Comment by vsaraph** [comment]
Upgrading just resolved the issue for me as well. Thanks!

**Comment by abhinavraj23** [comment]
Also had the same problem, upgrading to macOS 10.14.2 solved it. Thanks for the comments 👍

**Comment by AL-JShen** [comment]
Save problem, upgrading also solved it for me!

**Comment by christopherhesse** [comment]
Thanks for the helpful comments everyone!  I guess upgrading macos fixes this particular issue.
