### ISSUE TITLE
How to import new gym environment into spyder

### ISSUE THREAD

**Issue by stewegg** [openai/gym#1237]
I am very new to the gym environment and python; however, I have years of experience in programming.
I have been trying to set up a new environment for myself by following https://github.com/openai/gym/tree/master/gym/envs#how-to-create-new-environments-for-gym

The environment that I created is currently blank.
But I thought I would test it anyway by using gym-pull to pull it into my Spyder in Anaconda.

After installing gym-pull using pip and import gym-pull as shown below, I got an error message.

```
import os
import numpy as np
import gym
from gym import wrappers
import gym_pull
gym_pull.pull('github.com/stewegg/gym-foo')
```

Error:

```
Traceback (most recent call last):

  File "<ipython-input-20-2337cf17fd1e>", line 5, in <module>
    import gym_pull

  File "C:\ProgramData\Anaconda3\lib\site-packages\gym_pull\__init__.py", line 6, in <module>
    from gym.configuration import logger_setup, undo_logger_setup

ModuleNotFoundError: No module named 'gym.configuration'
```

**Comment by christopherhesse** [comment]
This appears to be a bug in https://github.com/ppaquette/gym-pull, could you file the issue there?  Thanks!
