### ISSUE TITLE
fetch_env.py (pick and place v1) incorrect achieved goal

### ISSUE THREAD

**Issue by richardrl** [openai/gym#1239]
if not self.has_object:
            achieved_goal = grip_pos.copy()
        else:
            achieved_goal = np.squeeze(object_pos.copy())

This section starting on line 114 definitely cannot be correct, right?

It is saying the achieved goal is the object position regardless of what action is taken. That means you are always 'achieving' a correct servo to the target. Keeping in mind that the reward is achieved goal - goal, that means the movement of the end effector is not accounted for anywhere.

**Comment by christopherhesse** [comment]
Sorry, I'm afraid I don't understand.  Why does the end effector position matter if the reward is about getting the object to the goal?

**Comment by christopherhesse** [comment]
Closing for now due to inactivity.
