### ISSUE TITLE
Implement `__enter__` & `__exit__` for automatically closing an `env` at the end of `with` statement

### ISSUE THREAD

**Issue by tsuberim** [openai/gym#1243]
Implementing:
```python3
class Env:
  def __enter__(self):
    return self
  def __exit__(self, exc_type, exc_val, exc_tb):
    self.close()
``` 

Gives us a nice sytactic sugar for automatically doing `close` at the end of a `with` block:
```python3
with gym.make(..) as game:
  # do stuff
```

**Comment by christopherhesse** [comment]
An interesting idea, currently we rely on the `__del__` method being called, what do you think @pzhokhov?

**Comment by pzhokhov** [comment]
This is implemented already, closing
