### ISSUE TITLE
Custom env - action_space & observation_space

### ISSUE THREAD

**Issue by bbartling** [openai/gym#1253]
Hi I am attempting to create a custom RL env with the step function and I was interested to learn a little more about what is needed for the action_space & observation_space.

There is not a lot of wisdom here on my end but in my Python class for the step function env I am just attempting:
```
    #possible actions from more_heat less heat functions
    self.action_space = np.array([ 0,  1,  2])

    #possible deviation values from temp - setpoint
    self.observation_space = np.arange(50,150,1)
```

The application that I am using it for is to drive an electronic control valve on a piping system where I am hoping to train an RL agent to maintain a temperature setpoint. So there are 3 available actions (not shown) that are functions for more_heat, less_heat, and do_nothing. And the possible ranges of temperatures that are possible for the sensor are values from 50 to 150 degrees. Is this what could be utilized in calculating a Q Table? Something like:

```
action_size = action_space
state_size = observation_space

qtable = np.zeros((state_size, action_size))
print(qtable)
```

But the problem is I get an error for `TypeError: only integer scalar arrays can be converted to a scalar index`

Thank you for any help, tips, wisdom here that I can apply on my quest!

**Comment by bbartling** [comment]
I actually used this to print a Q table... But it maybe not best practice. I think this GitHub issue could deleted unless someone could post a best practice answer... Like how I could incorporate 15 buckets with a width of 5 instead of a 150.

```
action_size = action_space.shape[0]
state_size = observation_space.shape[0]
```

**Comment by christopherhesse** [comment]
You should just use a `gym.spaces.Discrete` and then have the environment convert to the correct range.

So something like:

```
observation_space = gym.spaces.Discrete(100)
```

And when you have some output, you can convert it to an observation:
```
observation = output - 50
```
