### ISSUE TITLE
FAQ should explain how to export to video

### ISSUE THREAD

**Issue by mlda065** [openai/gym#1254]
I've read through the whole readme and the docs and the FAQ and I can't actually find an explanation of how to export the render to a video file.

I don't even know *where* to look for help on this. Is this a gym thing? If I'm running a [keras-rl example](https://github.com/keras-rl/keras-rl) then is this a Keras thing? Or is this something for the particular algorithm I'm choosing from keras? Or is this something for each environment (e.g. cartpole)? The FAQ or README should explain the interaction between these libraries better. I'm quite lost.

A lot of issues for gym seem to be about exporting video, but none of them contain MWEs.

[This part of the README](https://github.com/openai/gym#rendering-on-a-server) is too brief. (e.g. how do I specify a filename?)

**Comment by mlda065** [comment]
Ah, I kind of figured it out. A bit. (It only exports some runs, and I don't know how to export as a GIF)

I just updated the FAQ with what I know.

Can someone check [what I wrote](https://github.com/openai/gym/wiki/FAQ#how-do-i-export-the-run-to-a-video-file), or add to it?

**Comment by sprakasdash** [comment]
@mlda065 It's kinda lengthy but I found a way to export as video. To your training code add:
(I've done this for CartPole-v0)
`env_to_wrap = gym.make('CartPole-v0')`
`env = wrappers.Monitor(env_to_wrap, 'your directory here', force = True)`
`observation = env.reset()`

`env.close()`
`env_to_wrap.close()`

Writing `force = True` replaces your existing recording with current recording in the present directory.

Hope that clears :)

**Comment by christopherhesse** [comment]
Thanks for updating the wiki @mlda065!
