### ISSUE TITLE
How to list successor states for each state?

### ISSUE THREAD

**Issue by laheraestefania** [openai/gym#1255]
Is the transition function (the mapping of state and action to all successor states and the probability of the action leading to that successor state) saved somewhere and accessible?

One option would be to iterate through the states and perform all possible actions and look at the "info" field returned, since that might contain the transition probabilities but is there a way to force the environment to be at a certain state?

For background, I'm trying to implement topological order value iteration. Thanks!

**Comment by GenjitsuGame** [comment]
I think you can find it in `env.env.P` but I am not sure I fully understand how it works. Hopefully someone more knowledgeable will reply, I'd like to see a proper answer too

**Comment by christopherhesse** [comment]
Thanks for answering @GenjitsuGame, it's not officially part of the gym API, but frozen lake does expose the transition data that you could use with value iteration.

The format looks to be something like:

```
for prob, newstate, rew, done in env.unwrapped.P[state][action]: 
    print(prob, newstate, rew, done) 
```

Since it's an MDP, you have a probability of ending up in any of a number of newstates.
