### ISSUE TITLE
sample doesn't work for np.uint8 Box types

### ISSUE THREAD

**Issue by afrozenator** [openai/gym#1256]
It always returns 0 because we add 1 to the high and this makes both low and high = 0 and when we sample we get a box of all 0s

The fix would actually involve going to a higher type, sampling in that and then casting it back to uint8

**Comment by christopherhesse** [comment]
Fixed with https://github.com/openai/gym/pull/1307, thanks for the bug report!

**Comment by afrozenator** [comment]
Thanks @christopherhesse and @pzhokhov !
