### ISSUE TITLE
how to update environment after installing it

### ISSUE THREAD

**Issue by yceny** [openai/gym#1258]
I successfully installed my customized environment, but how can I update it? Shall I just run `pip install -e .` again?  It seems that it's unable to uninstall the old one

`Found existing installation: gym-pricing 0.1
    Not uninstalling gym-pricing at /Users/ycenycute/gym-pricing, outside environment /Users/ycenycute/venv/bin/..
    Can't uninstall 'gym-pricing'. No files were found to uninstall.`

Do that mean that the new one is not installed?

**Comment by christopherhesse** [comment]
Installing with `-e` should create a symlink, so just restarting your python program should be sufficient to load any changes.
