### ISSUE TITLE
Cannot change many parameters of MuJoCo model

### ISSUE THREAD

**Issue by gautams3** [openai/gym#1262]
This is a follow-up to #234
I tried changing model parameters like size, pos, and mass in a [swimmer environment](https://gym.openai.com/envs/Swimmer-v2/). But it didn't change the swimmer model on the fly. Changing values in the model xml and loading it did change the swimmer, as expected.

The model.opt parameters are the only ones that seems to be the only ones which is read-write. Is there a way to make the model parameters (such as body_mass and so on) read-write with the latest version of mujoco-py?

_Originally observed by @vigneshramk in https://github.com/openai/gym/issues/234#issuecomment-378847012_

**Comment by richardrl** [comment]
@gautams3 Also, when you changed the model XML, how did you make it work for the viewer?

if you set self.sim = <new sim> in the def reset(), it freezes the viewer

**Comment by gautams3** [comment]
I changed the model xml and created a new mujoco model
```
new_model = load_model_from_xml(xml_buffer)
```
Yes, it freezes the viewer. So if I create n different models and visualize them, it gives me n viewers
> if you set self.sim = in the def reset(), it freezes the viewer

Set self.sim = what?

**Comment by richardrl** [comment]
"Yes, it freezes the viewer. So if I create n different models and visualize them, it gives me n viewers"

I need arbitrary number of models though so this doesn't work for me...

However, if the gym monitor still outputs the right videos, then I dont really care about the viewer. Did you test if the gym monitor works continuing to output videos despite frozen viewer?

**Comment by gautams3** [comment]
I didn't test that.

On Sun, Jan 13, 2019 at 10:42 AM richardrl <notifications@github.com<mailto:notifications@github.com>> wrote:

"Yes, it freezes the viewer. So if I create n different models and visualize them, it gives me n viewers"

I need arbitrary number of models though so this doesn't work for me...

However, if the gym monitor still outputs the right videos, then I dont really care about the viewer. Did you test if the gym monitor works continuing to output videos despite frozen viewer?

**Comment by eugval** [comment]
Any updates on this? Do we need to change the xml and reload every time?

Also is this a mujoco-py or a mujoco restriction?

**Comment by christopherhesse** [comment]
This is sounding like an issue on mujoco-py, could you refile the issue there? https://github.com/openai/mujoco-py
