### ISSUE TITLE
dynamically change (i.e., restrict) action space

### ISSUE THREAD

**Issue by jheffez** [openai/gym#1264]
(This is a question, not issue)
Hey all, how can we dynamically change (i.e., restrict) the action space available to agent (keras-rl/tensorforce) ? 
Let's say that at the beginning there are 4 possible actions  (up/down/left/right). Then, at some stage in the simulation (game), there are only two (left/right). 
What's the best way to let the agent know that? A link/example is appreciated.

**Comment by bionicles** [comment]
Hi,

I'm also interested in this issue. 

Try setting Env.action_space = spaces.Discrete(2) and please let us know if this solves the problem. If not please post the error messages!

**Comment by christopherhesse** [comment]
You could always allow all actions and rely on the agent to figure out that 2 of the actions do nothing in the later stage.  You could also signal to the agent in the observations that it is in one setting or the other.  It's likely that there are other ways to do this, but this may be the simplest one.
