### ISSUE TITLE
Feature Request: MetaEnv / MetaSpace

### ISSUE THREAD

**Issue by bionicles** [openai/gym#1270]
My last act of 2018 - 

It's not straightforward to do Meta RL, but the results are potentially impressive.

How do you add a Computation Graph / Meta Space?

If we do this then we could "sample" architectures...

Meta.sample() could get observation and action spaces for various other Envs, and then build an adjacency list to connect the observation spaces to the action spaces. 

MetaEnv.reset() could sample a graph and test it on various envs and return the rewards as an observation

Then the graph system could optimize itself and return a new graph

MetaEnv.step() could then take the new graph and test it on the envs again.

Done = All envs solved with reward > threshold over N episodes for all envs

Have code but it's still a WIP for 2019... 

Happy New Year
Bion

**Comment by christopherhesse** [comment]
This sounds interesting, but I don't think this is really an issue with gym.
