### ISSUE TITLE
Create and Install own OpenAI Gym Environment

### ISSUE THREAD

**Issue by stewegg** [openai/gym#1273]
I currently runs Spyder Python editor under Anaconda 3. I have followed the instruction from the link below to create my test dummy gym environment. https://github.com/openai/gym/tree/master/gym/envs#how-to-create-new-environments-for-gym

However, when I try to install it using the codes below in the Anaconda Prompt as administrator:

```
pip install gym
pip install -e .
```
All I got was an error message of 

> Directory '.' is not installable. File 'setup.py' not found. Even know I have setup.py in the root folder.

Here's the link to my dummy gym: https://github.com/stewegg/DanL-gym

Can someone assist me with this issue? Thank you.

**Comment by shuruiz** [comment]
Are you working on linux? 

try:
`pip3 install gym'
'pip3 install -e .`

**Comment by stewegg** [comment]
thank you shuruiz  & mayou36 

problem solved.
I am using Windows 10 ruing Aanconda 3.
The problem was that the prompt was not pointing to the correct dir.

the way to solve this for me was was.....
`
pip install gym
git clone https://github.com/stewegg/DanL-gym
cd DanL-gym
pip install -e .
`

**Comment by christopherhesse** [comment]
Thanks @shuruiz and @mayou36!

**Comment by SolowomanYudachi** [comment]
> thank you shuruiz & mayou36
> 
> problem solved.
> I am using Windows 10 ruing Aanconda 3.
> The problem was that the prompt was not pointing to the correct dir.
> 
> the way to solve this for me was was.....
> `pip install gym`
> `git clone https://github.com/stewegg/DanL-gym`
> `cd DanL-gym`
> `pip install -e .`

Thank you so much! I was totally clueless about how to deploy my environment, and I was thinking of ways to place it locally.
