### ISSUE TITLE
Observation and Action Spaces Violated

### ISSUE THREAD

**Issue by jar577** [openai/gym#1278]
Hello, I setup a custom environment with my observation and action spaces as such:
high = np.array([1.5, 1.5, 1.5,1.5])
action_space = spaces.Box(low=np.array([0,0]), high=np.array([0.05,2*np.pi]), dtype=np.float32)
observation_space = spaces.Box(low=-high, high=high, dtype=np.float32)

However, when using my environment with PPO2, it seems to be willingly violating these. I tried debugging the script and stopped it within model.py and policies.py but the values remain unchanged. At line 52 of policies,py, though, the sampled action violates the provided space. 

Can anyone assist me in figuring out what's going on? Just let me know if you need anything else. Thanks!

**Comment by jar577** [comment]
I just now found this discussion: https://github.com/openai/baselines/issues/121

Is the solution posed by joellutz the best way to go, or should I simply clip the action that is fed into my environment?

**Comment by christopherhesse** [comment]
joellutz's solution looks like it is for ddpg, so it might not work with ppo2.  If it doesn't, a clipping wrapper on the environment as proposed by olegklimov may be a good solution.
