### ISSUE TITLE
Issues with setting up environment

### ISSUE THREAD

**Issue by Rishabh-Samra** [openai/gym#1281]
Can someone help fixing this error
![screenshot from 2019-01-09 09-48-09](https://user-images.githubusercontent.com/36258085/50876576-d7cc9380-13f3-11e9-9b7f-68fe522b3172.png)

**Comment by JobJob** [comment]
`gym.make("Taxi-v2")`
lower case v

**Comment by shuruiz** [comment]
"Taxi-v2"

**Comment by christopherhesse** [comment]
Thanks @shuruiz and @JobJob !
