### ISSUE TITLE
Observation space invalid

### ISSUE THREAD

**Issue by JobSmith** [openai/gym#1286]
My observation space is as follows:
![image](https://user-images.githubusercontent.com/15700681/51095189-e6e58400-17ed-11e9-8e42-313683e00ac0.png)

And my low and high is just as this:
self.low_dbl = np.array([
            0, 0, -90, -np.Inf
            ...])

Then it raises thiss error:
![image](https://user-images.githubusercontent.com/15700681/51095171-b3a2f500-17ed-11e9-8329-c3524c298f6b.png)

What is the probleam?

**Comment by shuruiz** [comment]
your bound is a numpy array (low=low_dbl, high=...), not a scalar.

**Comment by christopherhesse** [comment]
Thanks for answering that @shuruiz!
