### ISSUE TITLE
Frozen Lake not possible to get the action actually executed in slippery mode

### ISSUE THREAD

**Issue by bojeanson** [openai/gym#1295]
As it actually run, the environment does not return the action actually executed when it is in slippery "mode", we know the action chosen by the agent but the one actually executed by the environment is not available since the *lastaction* attribute is set to the chosen one.

Therefore when learning a policy or a function value, the agent try to catch the slippering "function" and not the more safe path or shortest one.

Is this normal ?

**Comment by kaiszybiak** [comment]
please unsubscribe me. Thanks

Am Mi., 23. Jan. 2019 um 14:27 Uhr schrieb bojeanson <
notifications@github.com>:

**Comment by shuruiz** [comment]
The agent learns to catch the "slippery" and the learned policy is actually the shortest path (under uncertainty, close to optimal after you algorithm converges). 

In Frozen lake environment, the movement direction of the agent is uncertain and only partially depends on the chosen direction.  The agent has no previous knowledge about the uncertainty. Therefore, the learned policy is actually the optimal/near-optimal policy (shortest path to the goal) conditioned on the uncertainty.

**Comment by christopherhesse** [comment]
You should be able to tell based on the observation which action got executed, but you're right that there's no direct way to tell this.
