### ISSUE TITLE
How to modify the environment

### ISSUE THREAD

**Issue by v2-dev** [openai/gym#1296]
Hi, I'm new using OpenAI Gym! 
I need to modify the environment of MsPacman-v0. I would like to resize the state space (making it e.g. 10x10) and adapt the number of walls and ghosts accordingly. Also, I would like to make the ghosts static, only the agent can move. 
How can I do that? 
Thank you!

**Comment by christopherhesse** [comment]
I'm afraid that is an atari environment, so it's likely too hard to modify the game code.  You may wish to clone the game in unity using ml-agents https://github.com/Unity-Technologies/ml-agents.
