### ISSUE TITLE
ModuleNotFoundError after git clone and installed

### ISSUE THREAD

**Issue by stewegg** [openai/gym#1297]
I currently runs Spyder Python editor under Anaconda 3. 
I have created a custom gym in the link below and used the git clone and pip install to install it using the Anaconda cmd.
https://github.com/stewegg/gym4Locations

`pip install gym`
`git clone https://github.com/stewegg/gym4Locations`
`cd gym4Locations`
`pip install -e .`

However, when I tried to import my custom gym with the code below, the error just came up.

`import gym`
`import gym_4Locations`

>import gym
>import gym_4Locations
>Traceback (most recent call last):

>File "<ipython-input-3-c03fcbe54d85>", line 2, in <module>
>  import gym_4Locations

>ModuleNotFoundError: No module named 'gym_4Locations'

Help!

Thank you very much

**Comment by christopherhesse** [comment]
This looks like a python packaging issue with `gym4Locations`.  Please check out https://packaging.python.org/tutorials/packaging-projects/ for more info on that.  Also it looks like you named the module `gym4Loc` but imported `gym4Locations`.
