### ISSUE TITLE
Warning from deathmatch.cfg

### ISSUE THREAD

**Issue by gdb** [openai/gym#130]
@ppaquette or @jietang mind taking a look? I get this while running `nose2`:

```WARNING! Loading config from: "/Users/gdb/openai/gym/gym/envs/doom/assets/deathmatch.cfg". Unsupported value in lines 21-72: altattack. Lines ignored.```

**Comment by ppaquette** [comment]
ALTATTACK is in the official documentation, but does not appear to be properly supported.

Line 28 from deathmatch.cfg (ALTATTACK)  needs to be removed, so the commands in deatchmatch.cfg properly mirror the commands in controls.md.
