### ISSUE TITLE
Undesired control-c behavior with vizdoom on OSX

### ISSUE THREAD

**Issue by gdb** [openai/gym#131]
Here's one example, where my Python interpreter session exits after pressing ctrl-C twice:

```
>>> import gym; gym.make('DoomBasic-v0')
[2016-05-28 12:20:04,335] Making new env: DoomBasic-v0
<gym.envs.doom.doom_basic.DoomBasicEnv object at 0x10a6e6810>
>>>
(press ctrl-c twice)
gdb@fountain:~/openai/gym$
```

I've also observed a consistent segfault while pressing ctrl-c while the tests are running and a vizdoom process is active. (Easiest way to repro is removing any intermediate `env.close()` calls.)

**Comment by jietang** [comment]
Checked this out - this seems to be an issue with VizDoom (filed an issue upstream https://github.com/Marqt/ViZDoom/issues/73). I played around with registering a signal handler at the Python level but I think we need the C++ bindings to cooperate (e.g. by calling PyErr_CheckSignals)

**Comment by jietang** [comment]
@ppaquette, it looks like we can prevent interpreter exits by removing a call to exit() in our forked VizDoomController (see the VizDoom issue). Want to take a look? If you don't want to I'll get to it in a week or so.

**Comment by christopherhesse** [comment]
As far as I know we don't have vizdoom environments anymore, closing.
