### ISSUE TITLE
vizdoom steals the focus upon boot

### ISSUE THREAD

**Issue by gdb** [openai/gym#132]
I'm not sure if there's a good way around this, but when I run

```
import gym; gym.make('DoomBasic-v0')
```

in iterm2 on OSX, the vizdoom process steals the focus.

**Comment by jietang** [comment]
Did some digging and couldn't find anything obvious. @ppaquette any ideas

**Comment by ppaquette** [comment]
I had a quick look, and I don't see anything obvious either.

On Ubuntu, the terminal still has focus on gym.make, but loses it on env.render (when pyglet.window.Window is called)

**Comment by christopherhesse** [comment]
As far as I know, we don't have vizdoom environments anymore, closing.
