### ISSUE TITLE
pull request: pandas dataframe space

### ISSUE THREAD

**Issue by chanansh** [openai/gym#1322]
For creating environment to model logged data I need a pandas dataframe space.
Would this be accepted?

**Comment by christopherhesse** [comment]
Hmm, what would that look like?  I'm a little doubtful that we want a space specifically for pandas dataframes.  You may want to create a custom space for your own usage, or else use `None` for the `observation_space` property and assume a pandas dataframe in that case.

**Comment by chanansh** [comment]
The benefit is interaction with a system which logs event. See for example
https://www.microsoft.com/en-us/research/project/multi-world-testing-mwt/.
Most log data comes in a format of a table with mixed type of numerical and
categorical data across time.

**Comment by christopherhesse** [comment]
I think it would make sense to have your own subclass of `gym.Spaces` for this, thanks though!  Feel free to link your space here though, for others to reference.
