### ISSUE TITLE
MujocoEnv  render(mode  = 'rgb_array') throws GLEW initialisation error,  but render(mode='human') works.

### ISSUE THREAD

**Issue by eugval** [openai/gym#1324]
With Reacher-v2, and exporting LD_PRELOAD as described [here](https://github.com/openai/mujoco-py/issues/268) ,  the issue `ERROR: GLEW initalization error: Missing GL version`  gets fixed for rendering in "human" mode but not in "rgb_array" mode.

A workaround I am using is to call render("human") once, then call render("rgb_array") normally.

Is there something I am missing, or a more elegant way to fix this?

**Comment by christopherhesse** [comment]
This looks like a mujoco-py issue, could you file this on the mujoco-py repo?  Thanks!

**Comment by thachdo** [comment]
This is not a mujoco-py issue. This is a gym issue.
```
import gym
env = gym.make('Ant-v2')
while(True):
        env.render(mode='rgb_array')
```
gym: 0.15.4
ubuntu: 16.04
