### ISSUE TITLE
Done status based on action in OpenAI Atari

### ISSUE THREAD

**Issue by niallmandal** [openai/gym#1325]
I am attempting to create a neural network to play the emulated atari game "BreakoutDeterministic". The action space for the game is [0,1,2,3].

When inputting
```
frame, reward, is_done, _ = env.step(env.action_space.sample())
```

The game will play out and and the "is_done" variable will eventually be set to ```True``` (when the game ends)

When inputting
```
frame, reward, is_done, _ = env.step(3)
```
The game will end but done will not be set to True. Instead I have to manually end the process.

<b>Any explanation to why this happens and how I can fix it?</b>

Full code:
```
import gym

env = gym.make('BreakoutDeterministic-v4')
frame = env.reset()
env.render()

is_done = False
while not is_done:
  frame, reward, is_done, _ = env.step(env.action_space.sample())
  #frame, reward, is_done, _ = env.step(3)
  env.render()
```

**Comment by ishan00** [comment]
Hey !

I was able to reproduce this with the code above, it appears to me that the game starts (the ball appears) only when you do action 1 atleast once. Note that this has to be done every time you lose a life.

There has been some discussions here which you may want to read https://github.com/openai/gym/issues/588

**Comment by niallmandal** [comment]
so then how should i change the code to reflect this

**Comment by ishan00** [comment]
If you train a neural network to play this, I suppose it will learn to perform action 1 on it's own. Incase you want to manually provide the actions then add `env.step(1)` as the first step.

**Comment by christopherhesse** [comment]
Thanks for looking into this @ishan00!
