### ISSUE TITLE
Best method to structure two-representation environment with changing actions

### ISSUE THREAD

**Issue by Eriz11** [openai/gym#1329]
I have an environment with the following properties:

- You start interacting with the environment in "way1", in which you have 3 possible actions. We could say that we are playing level1 of an specific game. The rewards cannot be specified until level2 has concluded. 

- After some steps, you may enter in level2 and you start interacting with it in "way2", which has 2 possible actions. Once in level2 and depending on the actions the agent takes, you will get a certain reward. After that some steps, you may get to a terminal/done state and you get again to level1, from where this loop starts again UNTIL you have no more observations (you finish an episode). 

My concern is about how to structure this kind of environments within openAI Gym in which you change the representation (i.e. you have different levels) and hence you change the action space. I have to remark that the observations are the same in level1 and in level2; which this I mean that, I will get the same observation if I'm in level1 at time t or if I'm in level2 at the same time step t. 

The idea is that the agent (¿maybe I need two agents?) must learn two different "performance types" (as the problems are different in level1 and level2, two representations may be needed). 

My thoughts are on:

1) Create two environments and two agents with the same data. Start with agent1 in env1. When I enter the level2 I change to env2 and agent2 all in the same training loop. 

2) Create one environment and set a flag to change the `env.action_space.n` if I enter level2.

As per my experience, I haven't seen these kind of problems tackled anywhere; so I would greatly appreciate any input from experienced practitioners.

Many thanks in advance,

**Comment by christopherhesse** [comment]
Option 1 sounds pretty reasonable.  You can also create an action space that encompasses both environments, but each environment only uses the actions relevant for the current level.
