### ISSUE TITLE
Box with `inf` bounds yields `nan` samples

### ISSUE THREAD

**Issue by gdb** [openai/gym#133]
This isn't the most useful sample. @joschu any suggestions for improvement?

```
>>> import gym; h = gym.make('BipedalWalker-v2')
[2016-05-28 13:55:08,724] Making new env: BipedalWalker-v2
>>> h.observation_space.low
array([-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,
       -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,
       -inf, -inf])
>>> h.observation_space.high
array([ inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,
        inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,
        inf,  inf])
>>> h.observation_space.sample()
array([ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,
        nan,  nan])
```

**Comment by joschu** [comment]
I don't think nan is necessarily a bad result. It'll alert people that you need to think carefully before sampling from this space. In other cases, we sample from a uniform distribution, so it would be inconsistent to pick some other distribution arbitrarily.

**Comment by joschu** [comment]
So I vote to stick with nan.

**Comment by gdb** [comment]
I can buy that. BTW, what do you think people are using `.sample()` for?

**Comment by joschu** [comment]
For the action spaces, it's useful to implement random policies. For the observation space, I don't know of a common use case.

**Comment by gdb** [comment]
Ok. Let's leave it for now.
