### ISSUE TITLE
Getting Error when runing a program to load super mario game

### ISSUE THREAD

**Issue by dileepmatha** [openai/gym#1337]
Error: ModuleNotFoundError: No module named 'gym.envs.ppaquette_gym_super_mario'

I have done the registration for the game register
(
    id='SuperMarioBros-1-1-v0',
    entry_point='gym.envs.ppaquette_gym_super_mario:MetaSuperMarioBrosEnv'
) 
For the score board i diidnt found folder in envs, so i have created a folder scoreboard and add the following code 

add_group(
    id='ppaquette_gym_super_mario',
    name='ppaquette_gym_super_mario',
    description='super_mario'
)

 # mario bros
add_task(
    id='ppaquette/SuperMarioBros-1-1-v0',
    group='ppaquette_gym_super_mario',
    summary="SuperMarioBros-1-1-v0"
)

When runing the proogram 
 
import gym
env = gym.make('SuperMarioBros-1-1-v0')
env.reset()

I am getting the error
ModuleNotFoundError: No module named 'gym.envs.ppaquette_gym_super_mario'

Note: I have followed the article(link: [https://becominghuman.ai/getting-mario-back-into-the-gym-setting-up-super-mario-bros-in-openais-gym-8e39a96c1e41]) to install the packages.

I am facing this issue for three days and don't know what to do.

**Comment by christopherhesse** [comment]
I'm afraid this looks like a problem with https://github.com/ppaquette/gym-super-mario you should file the issue on that repo.
