### ISSUE TITLE
Improvement: GPU-Accelerated Headless Rendering with OpenGL

### ISSUE THREAD

**Issue by mmatl** [openai/gym#1338]
Hi,

This isn't a bug so much as a plug and an ask for feedback. I've written a [pure-python renderer](https://github.com/mmatl/pyrender) that supports physically-based rendering, shadowmaps, and a host of other useful features. Most importantly, however, it also supports offscreen rendering with hardware acceleration via EGL. Check out an example in a Google CoLab Notebook [here](https://colab.research.google.com/drive/1rTLHk0qxh4dn8KNe-mCnN8HAWdd2_BEh).

Could this be helpful for anyone? I know that offscreen rendering on servers has been a pain point in the past, and this seems to work pretty reliably on newer Ubuntu versions.

**Comment by christopherhesse** [comment]
That does look pretty sweet.  For the purposes of gym, I am hoping that pyglet adds EGL support: https://bitbucket.org/pyglet/pyglet/issues/219/egl-support-headless-rendering

Other use cases may benefit from your renderer though.

**Comment by mmatl** [comment]
I'm hoping so too! I don't think it'll be hard, as PyOpenGL already implements it well and the folks maintaining Pyglet should be able to work off of that.

**Comment by rainbow979** [comment]
Hi, how do we use it in gym? Shall I edit gym source code?
