### ISSUE TITLE
Unclear documentation in the Pitfall-v0 environment

### ISSUE THREAD

**Issue by adalvigi** [openai/gym#1348]
As already stated in #106 , the documentation on the environments would really need some improvements. As of now, I need to run experiments on the Pitfall-v0 environment and I'm stuck because I can't figure out how the reward is computed exactly. Is it the points in the game? And are they returned to the program via some simplified API or are they computed from the pixels on the screen? Thanks in advance to whoever will give us some clarification on this one.

**Comment by christopherhesse** [comment]
ALE environments such as Pitfall generally use score in the game, for pitfall you can find the code in the Arcade Learning Environment repo: https://github.com/mgbellemare/Arcade-Learning-Environment/blob/master/src/games/supported/Pitfall.cpp#L51

I agree that more documentation of the environments would be useful, for now we have issue #106 as well as https://github.com/openai/gym/wiki/Table-of-environments
