### ISSUE TITLE
Cannot use gym.utils.play.PlayPlot

### ISSUE THREAD

**Issue by Remosy** [openai/gym#1350]
```
from gym.utils.play import play, PlayPlot
def callback(obs_t, obs_tp1, action, rew, done, info):
    return [rew,]
env_plotter = PlayPlot(callback, 30 * 5, ["reward"])
env = gym.make("IceHockey-v0")
```
I got : self.fig, self.ax = plt.subplots(num_plots) NameError: name 'plt' is not defined

**Comment by christopherhesse** [comment]
It's likely that this line is failing: https://github.com/openai/gym/blob/master/gym/utils/play.py#L8

I submitted a PR for a better one: https://github.com/openai/gym/pull/1376 and changed the default rendering backend for matplotlib.  Even with this though, it looks like matplotlib steals keyboard focus so this may not work as well as you want.
