### ISSUE TITLE
CartPole Gravity 

### ISSUE THREAD

**Issue by dshahid380** [openai/gym#1352]
Hello! I am new to Reinforcement Learning. When i went through OpenAI gym documentation, i found that there is already a CartPole self balancing example with constant gravity(9.8 units). My question is how can i implement a CartPole environment where gravity is variable because in real world scenario gravity is variable right. Please suggest me an idea.

**Comment by ishan00** [comment]
It's not difficult to create a new environment by modifying the original cartpole environment. 

Here is the environment -
https://github.com/openai/gym/blob/master/gym/envs/classic_control/cartpole.py

Creating new environments -
https://github.com/openai/gym/tree/master/gym/envs#how-to-create-new-environments-for-gym

But what exactly will the gravity depend on in your case?

**Comment by dshahid380** [comment]
Hey @ishan00, I have seen this codes.  We all know that gravity is not same everywhere on the Earth right and OpenAI gym gravity is taken as 9.8 units. When we will apply this in real world, then gravity will not be same right. So my question is, how can we use gym with variable gravity?

**Comment by ishan00** [comment]
What exactly is the gravity a function of here? Do you want to model it as a function of elevation or depth, latitude angle and speed of rotation of earth? But you'll have to initialise it at the start of environment. Or if you just want small perturbation around mean then you can add a small random value before every call to `env.step(action)`

**Comment by christopherhesse** [comment]
If you want random gravity you can set https://github.com/openai/gym/blob/master/gym/envs/classic_control/cartpole.py#L57 to be something like `9.8 + random.random()`
