### ISSUE TITLE
ConnectionResetError: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by Akella17** [openai/gym#1360]
The same piece of code that successfully runs on my local environment fails when run on Google Colabs. I am providing the Colabs notebook so that you can take a closer look at the error.

https://colab.research.google.com/drive/1dS0aACflSE9Sn5ssixBGN_sP48ZlvUEK

On a side note, I am seeing a broken pipe exception (ignored during execution) when I forcefully terminate the program on my local environment. This exception does not surface when I allow the program to naturally terminate. However, in either case, the ```log_dir``` folder that stores the ```*.monitor.csv``` files (* is replaced by the process id) always contains fewer than 16 (num_processes = 16) monitor files.
I find it strange and am hoping for an explanation for the absence of all the 16 monitor.csv files.

**Comment by cmal** [comment]
@Akella17 Hi, I've encountered the same problem. How did you solve it?

**Comment by LARS12llt** [comment]
Hi all,  is there any solution to this problem?
