### ISSUE TITLE
Why Cartpole equations of motion slightly different from those mentioned on Wikipedia page?

### ISSUE THREAD

**Issue by isaeed3** [openai/gym#1361]
Hi,

So I was comparing the equations of motion for Cartpole on wikipedia with what's been implemented in gym and found slight difference. 
According to equations on [https://en.wikipedia.org/wiki/Inverted_pendulum](url), 
`temp = (force + self.polemass_length * theta_dot * theta_dot * sintheta) / self.total_mass` should be `temp = (force - self.polemass_length * theta_dot * theta_dot * sintheta) / self.total_mass` with minus after force
Moreover in the thetaacc equation `thetaacc = (self.gravity * sintheta - costheta* temp) / (self.length * (4.0/3.0 - self.masspole * costheta * costheta / self.total_mass))`, there should be a + before costheta instead of a - and no 4.0/3.0 term should be there. 
Please correct me if I am suggesting something wrong.
Thanks

**Comment by christopherhesse** [comment]
As https://gym.openai.com/envs/CartPole-v1/ states, this is an implementation cartpole from  AG Barto, RS Sutton and CW Anderson, "Neuronlike Adaptive Elements That Can Solve Difficult Learning Control Problem", IEEE Transactions on Systems, Man, and Cybernetics, 1983.  Which does have a + before `costheta`, except the sign is flipped on `temp` in our implementation, so `costheta` should have a + sign I believe.  Let me know if this does not look correct.

**Comment by isaeed3** [comment]
According to the paper, the equations seemed correct. Only the friction part has been taken out then. Wiki page has slightly different equations as mentioned in my original post which shows that there can be different ways of describing the system
