### ISSUE TITLE
How to initialize a target point with a fixed parameter in the FetchReach environment

### ISSUE THREAD

**Issue by sxwgit** [openai/gym#1363]
Hello, guys. I want to test with some algorithms in the FeachReach-v1 environment, but the current position of the target is random. The random target is hard for some algorithms like ppo or trpo to get a good reward.

How to modify it so that when you call `env.reset(),` the target is in a fixed position.

Thanks for your help.

**Comment by sxwgit** [comment]
Hello, maybe I found a function that can fix the target, just like
```
def _sample_goal(self):
        .......
        ......
        # the values is the postion where you want the target to be
        goal=np.array(values)
        return goal.copy()
```
in` fetch_env.py`



But now I have another problem, I don't know why resetting the value of the goal will affect the coordinates of the target in the environment. I thought the coordinates of the target should be randomly initialized by FetchReach environment. Does anyone know the reason?

Best regards.

**Comment by christopherhesse** [comment]
I don't see a difference in the code between the goal and the target, although there is a `gripper_target` variable as well.  So you've fixed the goal, but you want the target to be random?  What is the difference between those two?
