### ISSUE TITLE
Car racing pops up window upon reset()

### ISSUE THREAD

**Issue by gdb** [openai/gym#137]
The following results in a large window popping up:

```import gym; gym.make('CarRacing-v0').reset()```

Is there any way to suppress the window until the user calls `render()`?

**Comment by gdb** [comment]
cc/ @olegklimov

**Comment by ashishm-io** [comment]
This issue still persists. Any solutions to this? 
It prevents me from training using CarRacing env on a remote server.

**Comment by olegklimov** [comment]
Sorry this env requires window for rendering, because of the libraries it is using. People have succeeded in running CarRacing in the cloud though, I don't know the details.

**Comment by ashishm-io** [comment]
Thank you for your reply. I'll post my solution here if I succeed.

**Comment by ioneliabuzatu** [comment]
any success @AshishMehtaIO ?
