### ISSUE TITLE
Missing definition in Class Line

### ISSUE THREAD

**Issue by ravimohan1991** [openai/gym#1377]
Howdy!

There is a missing definition set_linewidth in the Class Line of file rendering.py and it is called by _add_attrs(geom, attrs) method of Class Viewer in the same file.

**Comment by christopherhesse** [comment]
It looks like that is supposed to be only called on a polyline, is there a case where it is not?

**Comment by ravimohan1991** [comment]
Right, there is one definition 

def draw_line(self, start, end, **attrs):
        geom = Line(start, end)
        _add_attrs(geom, attrs)
        self.add_onetime(geom)
return geom

which needs the above implementation of set_linewidth in that class for appropriate functioning.

**Comment by christopherhesse** [comment]
It looks like multiple geoms are missing `set_linewidth` though, and that `draw_line` is only called in a single place and with no attributes.  Where in the code base is this used incorrectly?

**Comment by ravimohan1991** [comment]
Default codebase seems fine. I wrote a custom environment (https://github.com/ravimohan1991/gym-tictactoe) which needs the rendering of line with additional attributes (e.g. line 225 of https://github.com/ravimohan1991/gym-tictactoe/blob/master/gym_tictactoe/envs/tictactoe_env.py).

**Comment by christopherhesse** [comment]
Ah, then it's a good point but I don't think that the rendering code is meant to be part of the public gym API so it should be fine if it only works with the few gym environments in this repo.  If this was packaged as some reusable library for rendering, I think it would make more sense to have it well documented and have better feature coverage.
