### ISSUE TITLE
my gym package can't generate json file.

### ISSUE THREAD

**Issue by ibrahimqazi** [openai/gym#1378]
hello all, i  want to record my my simulation environment for plotting it. But it didnt genereate the json file. after completing all episodes the training_results folder is still empty. what could be the possible reason. I am using VERSION = '0.12.0'.  
the code I wrote is:
    rospack = rospkg.RosPack()
    pkg_path = rospack.get_path('drone_training')
    outdir = pkg_path + '/training_results'
    env = wrappers.Monitor(env, outdir, force=True) 
    rospy.loginfo ( "Monitor Wrapper started")
Can someone help me. thanks

**Comment by christopherhesse** [comment]
Do you have a simple script that reproduces this error and does not rely on rospkg?

**Comment by ibrahimqazi** [comment]
yes I tried with **CartPole-v0** environment and it works fine, but doesn't work with ROS Gazebo simulator. And it also doesn't generate any error but after completing episodes the folder is empty.

**Comment by christopherhesse** [comment]
This makes it sound like an issue with ROS Gazebo, could you file the issue over there?  Thanks!

**Comment by ibrahimqazi** [comment]
> This makes it sound like an issue with ROS Gazebo, could you file the issue over there? Thanks!

there is cloud server which uses this gym package not sure which one, but on cloud it works fine. I didnt file this issue on Gazebo.
