### ISSUE TITLE
Standard pattern for delayed feedback in `Environment`s?

### ISSUE THREAD

**Issue by macks22** [openai/gym#1394]
**I'm wondering if there is a standard pattern to adapt the `Environment` interface for delayed feedback?**

**Delayed feedback** is common in realistic bandit problems and has been studied by many (though a minority of) papers in the academic literature. Basically, you take an action and the reward doesn't arrive immediately. It may eventually arrive after the next N steps, after some amount of time elapses, or after some stochastic period of time or number of steps. For a realistic example, consider display advertising in which the goal is to optimize for product purchases rather than click-throughs.

**Options Considered**
I can imagine a few options that involves bundling the delayed rewards into the `observation`. Basically, on each call to `step`, the `observation` object contains a `delayed_feedback` property. It could be a:

1.  mapping from time steps to rewards that are now arriving for that time step. This would necessitate the agent tracking which observations correspond to which time step, or alternatively, that the environment provide a mapping from time steps to historical observations (via nonstandard methods).
2.  mapping from time steps to tuples of `(observation, action, reward)`. This would mean the environment ends up returning every observation twice and track the actions the agent takes.

Both of these seem to be workable solutions -- even if the rewards arrive after a time delay rather than after some number of `step` calls, the agent will still be able to observe the rewards before taking the next action. I'm inclined to go with the first; it seems to lead to a simpler `Environment`, and agents that deal with delayed feedback will probably be tracking historical observations anyway. **Before choosing one of these, I'd love to know if either is standard or if there is another standard pattern I should use for compatibility with other environments/algorithms?**

Thanks!

**Comment by christopherhesse** [comment]
I'm not aware of a standard pattern here, but you should be able to easily do this with a wrapper: https://github.com/openai/gym/blob/master/gym/core.py#L209 and you could just delay the reward stream, though you'd probably have to insert extra observations at the end of an episode for any delayed rewards.

**Comment by wiesbadener** [comment]
@macks22  How did you end up implementing it?

> 1. mapping from time steps to rewards that are now arriving for that time step. This would necessitate the agent tracking which observations correspond to which time step, or alternatively, that the environment provide a mapping from time steps to historical observations (via nonstandard methods).

I guess this often represents real use-cases, as the environment model is likely to cause the delays. 

E.g. one step in a gym environment represents a certain time increment (dt) of the simulation model. Within this dt the agent didn't observe the response associated with the last action.

An other example would be stock keeping (I think it's mentioned in [Bertsekas' Book "Dynamic Programming and Optimal Control](http://www.athenasc.com/dpbook.html)". The agent orders products to fill up inventory (action). They are delivered with _some time delay_. There is some demand per time step. Stock amount is the state. Reward could be (sales income - stock keeping and purchase costs ). 

I think from a mathematical point of view the time delay makes it non-Markovian. But a non-MDP can be transformed into a Markovian one by a redefinition of the state considering history.

**Comment by daffarg** [comment]
@macks22 @wiesbadener @christopherhesse Do you have any practical sample code in custom env to handle the delayed feedback problem, especially in `step()` function? I have this problem with my project as the observation can only be obtained 10 seconds later after I applied an action. My current naive approach is using `time.Sleep()` in the `step()` function after I applied an action.
