### ISSUE TITLE
What do the numbers in env.observations_space really stand for?

### ISSUE THREAD

**Issue by Xunzhaocunzi** [openai/gym#1397]
![Screenshot from 2019-03-20 14-38-28](https://user-images.githubusercontent.com/32579634/54713956-dc14db80-4b1d-11e9-8f6b-5ca8424e260f.png)

Take CartPole-v0 for instance, what do 2.4 and 0.20943951 in the array stand for? I guess those numbers are used to describe the status of the cart and pole, such as speed, forces, angles, etc. But I cannot find the details in the documentations about how openai used those observation arrays/numbers to describe the status or state of the environment. Could anyone help? 
Thank you

**Comment by Tom2718** [comment]
The observation space contains the observations in the environment. For Cartpole, this is the cart position, cart velocity, pole angle and pole velocity. The 2.4 is the boundary of the screen while the 0.2 is 12 degrees in radians from the vertical axis. See the [docstring](https://github.com/openai/gym/blob/57187307f146adb4eec7c29a8483119f80ae6a67/gym/envs/classic_control/cartpole.py#L23) for more.

**Comment by christopherhesse** [comment]
Thanks for answering @Tom2718!  This is correct, the meanings are environment-specific and should be documented in the docstring there, though this is not guaranteed.
