### ISSUE TITLE
Add Hex

### ISSUE THREAD

**Issue by Botev** [openai/gym#14]
Since this as also a connection game, but a simpler than Go, yet hard enough on bigger boards (hard enough so no efficient algorithm exists (up to my knowledge) for boards on 11+ size.

**Comment by wojzaremba** [comment]
This sounds great.
Feel free to create a new environment. We are happy to merge it.

**Comment by Botev** [comment]
could you provide a bit more documentation of what is the required interface for the environment API? I've checked the Go version, but it heavily relies on Pachi, which does not make it a good example of a standalone environment.

**Comment by wojzaremba** [comment]
Environment has to implement three functions: 
def _step(action)
def _reset()
def _render()

You can have a look on Cartpole implemention, which is self contained: 
https://github.com/openai/gym/blob/master/gym/envs/classic_control/cartpole.py

**Comment by Botev** [comment]
Could someone take a look, as I'm working on weird environment, and have some restrictions, which is why I don't have the Gym yet installed, but the general implementation should be ok:
https://github.com/Botev/gym

**Comment by joschu** [comment]
Feel free to make a PR when you have something working, but the Issues list isn't for works in progress, so I'm closing this.

**Comment by gdb** [comment]
(If you re-open this instead as a pull request, it'll be much easier for us to review!)
