### ISSUE TITLE
A question about the step function

### ISSUE THREAD

**Issue by chaobiubiu** [openai/gym#1408]
Assuming that the current state is s0, what should I do when I only want to get the latter states s1 s2 and don't push the agent to these states in fact? I think that this operation is simlilar to the Monte Carlo Tree Search in AlphaGo. However, I can't solve this problem myself. I sincerely ask for your help.

**Comment by sritee** [comment]
One way would be to modify the 'step' method of the environment, and make it return the next states without changing the state of the environment. You can create a duplicate method step_nochange which does this and add it the environment file in gym/envs

**Comment by chaobiubiu** [comment]
> One way would be to modify the 'step' method of the environment, and make it return the next states without changing the state of the environment. You can create a duplicate method step_nochange which does this and add it the environment file in gym/envs

Ok, thank you!

**Comment by christopherhesse** [comment]
Thanks for the answer @sritee!
