### ISSUE TITLE
CartPole.render()  always creates a new window even when 'mode=rgb_array'

### ISSUE THREAD

**Issue by ZyUestc** [openai/gym#1409]
I want to find a method that don't have to create windows so that it runs over server.

**Comment by christopherhesse** [comment]
What error do you get when running this on the server?

**Comment by ZyUestc** [comment]
Sorry for insufficient description!
This is total: I run jupyter notebook over a ubuntu server,  then I want to test some function. Here is my code first:
import gym
env = gym.make('CartPole-v0')
env.reset()
for _ in range(1000):
    env.render(mode='rgb_array'))
    env.step(env.action_space.sample()) # take a random action
env.close()
then I got error with
---------------------------------------------------------------------------
NoSuchDisplayException                    Traceback (most recent call last)
<ipython-input-4-9942aa34e878> in <module>()
      3 env.reset()
      4 for _ in range(1000):
----> 5     print(env.render(mode='rgb_array'))
      6     env.step(env.action_space.sample()) # take a random action
      7 env.close()

~/gym/gym/core.py in render(self, mode, **kwargs)
    247 
    248     def render(self, mode='human', **kwargs):
--> 249         return self.env.render(mode, **kwargs)
    250 
    251     def close(self):

~/gym/gym/envs/classic_control/cartpole.py in render(self, mode)
    148 
    149         if self.viewer is None:
--> 150             from gym.envs.classic_control import rendering
    151             self.viewer = rendering.Viewer(screen_width, screen_height)
    152             l,r,t,b = -cartwidth/2, cartwidth/2, cartheight/2, -cartheight/2

~/gym/gym/envs/classic_control/rendering.py in <module>()
     25 
     26 try:
---> 27     from pyglet.gl import *
     28 except ImportError as e:
     29     raise ImportError('''

/anaconda3/lib/python3.6/site-packages/pyglet/gl/__init__.py in <module>()
    237     # trickery is for circular import
    238     _pyglet.gl = _sys.modules[__name__]
--> 239     import pyglet.window

anaconda3/lib/python3.6/site-packages/pyglet/window/__init__.py in <module>()
   1894 if not _is_pyglet_docgen:
   1895     pyglet.window = sys.modules[__name__]
-> 1896     gl._create_shadow_window()
   1897 

/anaconda3/lib/python3.6/site-packages/pyglet/gl/__init__.py in _create_shadow_window()
    206 
    207     from pyglet.window import Window
--> 208     _shadow_window = Window(width=1, height=1, visible=False)
    209     _shadow_window.switch_to()
    210 

/anaconda3/lib/python3.6/site-packages/pyglet/window/xlib/__init__.py in __init__(self, *args, **kwargs)
    164                     self._event_handlers[message] = func
    165 
--> 166         super(XlibWindow, self).__init__(*args, **kwargs)
    167 
    168         global _can_detect_autorepeat

/anaconda3/lib/python3.6/site-packages/pyglet/window/__init__.py in __init__(self, width, height, caption, resizable, style, fullscreen, visible, vsync, display, screen, config, context, mode)
    499 
    500         if not display:
--> 501             display = get_platform().get_default_display()
    502 
    503         if not screen:

/anaconda3/lib/python3.6/site-packages/pyglet/window/__init__.py in get_default_display(self)
   1843         :rtype: `Display`
   1844         """
-> 1845         return pyglet.canvas.get_display()
   1846 
   1847 if _is_pyglet_docgen:

/anaconda3/lib/python3.6/site-packages/pyglet/canvas/__init__.py in get_display()
     80 
     81     # Otherwise, create a new display and return it.
---> 82     return Display()
     83 
     84 if _is_pyglet_docgen:

/anaconda3/lib/python3.6/site-packages/pyglet/canvas/xlib.py in __init__(self, name, x_screen)
     84         self._display = xlib.XOpenDisplay(name)
     85         if not self._display:
---> 86             raise NoSuchDisplayException('Cannot connect to "%s"' % name)
     87 
     88         screen_count = xlib.XScreenCount(self._display)

NoSuchDisplayException: Cannot connect to "None"
So I turn to look source code of 'CartPole' then  I **found it always renders image first**,  the parameter 'rgb_array' has influence only on return.  It seems to we should check mode is 'human' or not then renders image).
After I try with 'Breakout-v0' and other environments in 'atari',  I got a np.array instance and not renders image anymore.

**Comment by christopherhesse** [comment]
Are you running an X11 server?  If not you should run everything using Xvfb to create a fake one so that rendering will work.  An X11 server is required until pyglet adds EGL support: https://bitbucket.org/pyglet/pyglet/issues/219/egl-support-headless-rendering

**Comment by christopherhesse** [comment]
Also see https://github.com/openai/gym#rendering-on-a-server
