### ISSUE TITLE
label:question BlackJack 32 possible values for sum of player's hand?

### ISSUE THREAD

**Issue by Christopheraburns** [openai/gym#1410]
I know I will feel silly when someone answers, but I am trying to understand why, in the observable space of the BlackJack environment, the player's hand value is 1 of 32 possible values?

How is 32 calculated?

If the player has one card, there are 12 possible values 2-10 and 1 or 11 from an Ace
If the player has two cards there should be 144 possible permutations.  

What am I missing?

TIA

**Comment by ZyUestc** [comment]
I guess u missing  "The observation of a 3-tuple of: the players current sum,
the dealer's one showing card (1-10 where 1 is ace),
and whether or not the player holds a usable ace (0 or 1)." in annotate.
The players current sum is least one, while the max sum is obtained when players draw a 'ace' when current sum is '21'.

32 is definitely calculated by  11 + 21. Even I thought the max sum should be 30 by 10 + 20 )

**Comment by Christopheraburns** [comment]
thank you @ZyUestc

**Comment by Sachinkumar04428** [comment]
The game of Blackjack starts with the player having 2 cards and the dealer with two cards with one faced down, while other faced up. Now the player can have the sum of those cards from 2 to 22. Minimum in the case where they receive two aces and keep there values as 1 each or maximum when the keep there values to be 11 each. 
Note: aces can have a value of either 1 or 11.

Now when the sum is 22, and the player chooses to hit he may get a card with value 10, resulting in a sum of 32, and thus loosing the game.
Also the dealer can have only cards with value 1-10 (where 1 is ace), which accounts to 10 possible values. 

But it seems the programmers also kept the not possible states of 0 sum or 0 value card with dealer.
Thus the observation space being a tuple (Discrete(32), Discrete(11), Discrete(2))..

**Comment by rhalbersma** [comment]
The state space enumeration includes unreachable states, but facilitates easy indexing for table-based algorithms:

- player's sum ranges from 0...31 (0...3 are unreachable)
- dealer's card ranges from 0...10 (0 is unreachable)
- player's action ranges from 0...1 (all reachable)

Note that the player's sum is at most 31 (hitting a 10 on 21) and not 32 since hitting an A on 21 gives 22 as the player's sum.

**Comment by A-Pai** [comment]
> The state space enumeration includes unreachable states, but facilitates easy indexing for table-based algorithms:
> 
> * player's sum ranges from 0...31 (0...3 are unreachable)
> * dealer's card ranges from 0...10 (0 is unreachable)
> * player's usable ace ranges over 0...1 (all reachable)
> 
> This allows the observed state tuple to be directly used in a NumPy 3D-array (0-based indexing). Note that the player's sum is at most 31 (hitting a 10 on 21) and not 32 since hitting an A on 21 gives 22 as the player's sum.
> 
> It's of course possible to compress state tables by subtracting 4 from the player's sum and 1 from the dealer's sum, and also by collapsing all bust states (player's sum 22...31) to a single state. That would give a state space of `tuple(Discrete(19), Discrete(10), Discrete(2))`, but at the cost of more complicated indexing.

“player's sum ranges from 0...31 (0...3 are unreachable)”---it should be “(0...31 are unreachable)”？
what is the meaning of “facilitates easy indexing for table-based algorithms”？
