### ISSUE TITLE
Clarify how the Gym handles a "Step" command

### ISSUE THREAD

**Issue by Christopheraburns** [openai/gym#1411]
I am writing a customized BlackJack environment for the Gym. 

In the existing BlackJack-v0 [code](https://github.com/openai/gym/blob/master/gym/envs/toy_text/blackjack.py)  we can see the "Step" function at line 91.

In the Taxi [code](https://github.com/openai/gym/blob/master/gym/envs/toy_text/taxi.py) we can see how the location of the passenger is randomized and the environment built.  (Anyone know why "P" was chosen as the name of the matrix that holds the environment?)  

I don't see a "Step" function in the Taxi code.  Yet, we would simply call `env.step(action)` in both environments to increment one time step.

What is the Gym doing to reconcile one class that has a Step function and one class that does not?

TIA

**Comment by christopherhesse** [comment]
Looks like that step function is defined on the parent class: https://github.com/openai/gym/blob/master/gym/envs/toy_text/discrete.py#L54
