### ISSUE TITLE
is there a method to get the type of environment

### ISSUE THREAD

**Issue by smilesun** [openai/gym#1412]
is there a method to get the type of environment? for example, given an environment name, or environment object, how can i know if it is belonging to atari or some other category?

**Comment by christopherhesse** [comment]
For now you have to keep a list of what environments are in what categories, it might be nice to have this sort of information available on the environment though: https://github.com/openai/baselines/blob/1b092434fc51efcb25d6650e287f07634ada1e08/baselines/run.py#L120

You could also look at the `env.unwrapped` class and guess from that.
