### ISSUE TITLE
what if we add goal_velocity to continuous_mountain_car.py 

### ISSUE THREAD

**Issue by abhinavsagar** [openai/gym#1414]
I think there should also be a `goal_velocity` constraint just like `goal_position` in a separate continuous_mountain_carV2.py for making the environment a bit more challenging. This could lead to many more further work to be explored in this field.

**Comment by christopherhesse** [comment]
Sounds good, we have a guide https://github.com/openai/gym/blob/master/docs/creating-environments.md on how to create new environments.
