### ISSUE TITLE
action space definition of HandManipulateBlock-v0

### ISSUE THREAD

**Issue by TristaZhang** [openai/gym#1418]
I can get the observation sapce and action space attributes for some of the envs here:https://github.com/openai/gym/wiki/Table-of-environments. 
such as the action space for CartPole-v0:

Num | Action
-- | --
0 | Push cart to the left
1 | Push cart to the right

However, there is no description for "HandManipulateBlock-v0".  Anyone knows? Thanks a lot!

**Comment by christopherhesse** [comment]
The actuators for those environments should be specified in https://github.com/openai/gym/blob/master/gym/envs/robotics/assets/hand/shared.xml#L232

I think there are more mujoco_py methods for verifying which index corresponds to which (though they should be in order), but that would be in the mujoco or mujoco py documentation.
