### ISSUE TITLE
Python 3 mountain car hill doesn't render

### ISSUE THREAD

**Issue by benjamin-vanniekerk** [openai/gym#142]
The hill renders for the first frame but disappears thereafter.

The issue seems to be on line 83 of MoutainCarEnv. Replacing `zip(...)` with `list(zip(...))` seems to resolve the problem.

**Comment by gdb** [comment]
Good find! Mind submitting a pull request?

On Monday, May 30, 2016, benjamin-vanniekerk <notifications@github.com>
wrote:

> The hill renders for the first frame but disappears thereafter.
>
> The issue seems to be on line 83 of MoutainCarEnv. Replacing zip(...)
> with list(zip(...)) seems to resolve the problem.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/openai/gym/issues/142>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAM7kQRuiViTSY2VfxTp-_9vR3SS-ZJiks5qGsrqgaJpZM4IpuKc>
> .
>


-- 
Sent from mobile

**Comment by jietang** [comment]
thanks @benjamin-vanniekerk

**Comment by benjamin-vanniekerk** [comment]
No problem.
