### ISSUE TITLE
env.render(mode='rgb_array') is returning None

### ISSUE THREAD

**Issue by akanksha95** [openai/gym#1420]
I am using version 0.10.5. If I run env.render(), it is correctly showing me a window with the Atari game (Breakout) running. However, if I attempt to get image pixels using env.render(mode='rgb_array'), it is returning None. Has anyone else faced this issue? Is this a bug?

**Comment by zhangj150** [comment]
yeah, what is the resolution?

**Comment by akanksha95** [comment]
I was using baselines with another library and that library was overriding `env.render`. So it wasn't an issue with openai!
