### ISSUE TITLE
Reset in GoalEnv never called

### ISSUE THREAD

**Issue by drozzy** [openai/gym#1425]
What is the purpose of the reset in GoalEnv base class?

https://github.com/openai/gym/blob/7006c7a182a991b9409c206c56abc121eaffafb5/gym/core.py#L169

If I derive my own env from `GoalEnv`, the base reset is never called - so it never checks observation_space.

Is there an example of when this is actually called?

**Comment by drozzy** [comment]
I suppose one must call:

    super(MyEnv, self).reset()

**Comment by drozzy** [comment]
Nope, this doesn't work as I get `NotImplementedError`

**Comment by christopherhesse** [comment]
Can you post a code example of this not working?  This sounds like just a normal python inheritance issue.

**Comment by drozzy** [comment]
Yeah, I mean when you derive from this class, you have to override reset function. So that the GoalEnv reset function is never called.

**Comment by christopherhesse** [comment]
Oh you're saying that since `GoalEnv.reset()` calls `Env.reset()` this can't possibly work https://github.com/openai/gym/blob/7006c7a182a991b9409c206c56abc121eaffafb5/gym/core.py#L173

I think the easiest fix would be to only have the `isinstance` check in `GoalEnv.reset()` and remove the other code.

**Comment by christopherhesse** [comment]
We could also merge `GoalEnv` into https://github.com/openai/gym/blob/e0f916a7d5e4b6afaee05a73ca3da508423d8cf2/gym/envs/robotics/robot_env.py#L16 since this appears to be the only use.

**Comment by christopherhesse** [comment]
Thoughts @pzhokhov ?

**Comment by pzhokhov** [comment]
I agree we should not call `result = super(GoalEnv, self).reset()` in GoalEnv... as for merging GoalEnv into RobotEnv - I'd rather not, I think RobotEnv is very mujoco-specific, whereas GoalEnv seems to generally define an interface for environments where a some goal is to be achieved.

**Comment by pzhokhov** [comment]
https://github.com/openai/gym/pull/1459/files
