### ISSUE TITLE
Random Sampling of rotations.

### ISSUE THREAD

**Issue by gsp-27** [openai/gym#1426]
https://github.com/openai/gym/blob/7006c7a182a991b9409c206c56abc121eaffafb5/gym/envs/robotics/rotations.py#L101

Hi,
Here, does the random sampling of rotation, mean sampling a point on the 3d sphere in 4d?

If that is the case I am happy to submit a pull request making it work. Also, if it means something else and/or more things are required, I would be more than happy to do it.

**Comment by christopherhesse** [comment]
@matthiasplappert would this be interesting to add?

**Comment by matthiasplappert** [comment]
Mh I don't think we really need this right now but thanks for offering!

**Comment by christopherhesse** [comment]
Well, thanks for the offer @gsp-27!
