### ISSUE TITLE
Question on how to display entire track in car racing env 

### ISSUE THREAD

**Issue by vijpandaturtle** [openai/gym#1427]
Hi, I want to create a version of this game with multiple tracks. But for that i need to see the whole environment (the whole track) displayed. Can you please tell me how i can achieve that ?
Thanks

**Comment by christopherhesse** [comment]
You can set the `ZOOM` value to `0.1` at https://github.com/openai/gym/blob/master/gym/envs/box2d/car_racing.py#L53
