### ISSUE TITLE
Hand Gestures Using ShadowHand?!

### ISSUE THREAD

**Issue by RamiSketcher** [openai/gym#1433]
Hello!

I want to make some poses and gestures by robotic hand model (e.g. ShadowHand), and train a network to learn how to relate that to some inputs (e.g. EMG signals) without using any hardware (just in simulation). Is this possible? and How?

Is it possible to make that with the ready gym environments such like _HandReach-v0_ ?! How?

Best regards.

**Comment by christopherhesse** [comment]
I think you can do something like that using the mujoco simulator and model data from https://github.com/openai/gym/blob/master/gym/envs/robotics/assets/hand/robot.xml

This is sort of out of the scope of gym though.
