### ISSUE TITLE
KellyCoinflipGeneralized-v0 outputs the wrong reward

### ISSUE THREAD

**Issue by bbbbbbbbba** [openai/gym#1434]
https://github.com/openai/gym/blob/8826379709617d08f7038c2806b726ac93e911ec/gym/envs/toy_text/kellycoinflip.py#L180

The reward when done is the wealth cap, instead of the current wealth. This means that an agent could get the maximum reward by betting nothing.

**Comment by christopherhesse** [comment]
It looks like this was broken in https://github.com/openai/gym/pull/1269 and that the logic in that environment was potentially altered in other ways as well.  @pzhokhov any thoughts?

**Comment by pzhokhov** [comment]
Re-read the step logic in KellyCoinFlip - other than this problem (fixed in https://github.com/openai/gym/pull/1456), it seems solid.

**Comment by christopherhesse** [comment]
Thanks for fixing this @pzhokhov!
