### ISSUE TITLE
Question about custom gym environment

### ISSUE THREAD

**Issue by kwk2696** [openai/gym#1441]
Hello, I'm currently making my custom gym env and I had some question about it.

1. In `step()` function, should I return the next observation state or current observation state?
for example, state0 -> action -> state1, then should I return state0 for observation state or should I return state1?

2. Whatever the observation space is (the size of the type) the model.learn will automatically fit to the network?

**Comment by abhinavsagar** [comment]
Sorry for the late reply. Regarding your first question you should return state0. model.learn will automatically fit to the network provided it dosen't run out of memory as you are mentioning large observation space could be a possibility.

**Comment by christopherhesse** [comment]
1. I suspect it is state1 you want to return.  state0 should have been returned by `env.reset()`
2. I don't know of any model.learn in gym, but whatever model you use needs to support whatever observations are produced by the environments you are using.
