### ISSUE TITLE
How can we get sensor which we want to continue our project

### ISSUE THREAD

**Issue by boonam02** [openai/gym#1444]
We continue the project "auto walking with real robot after simulating ant -v2.
In detail, we are making AI- ant with DQN.

However, we have some problems that we can't get some observation values after making 
ant- v2 robot.

To get observation values, we need sensors to carry out these values.

I WANT TO KNOW IF THERE IS A SENSOR THAT CAN GET OBSERVATION VALUES.

**Comment by abhinavsagar** [comment]
Sorry, can you please elaborate what kind of sensor are you talking about?

**Comment by pzhokhov** [comment]
In mujoco, the observation is the state of the physics simulator, so it is somewhat hard to replicate that in real life with sensors. If you are planning to transfer a trained policy on mujoco, I would recommend some environment that uses positions and velocities of joints - that you can get from sensors relatively easily. Look, for instance, into RoboschoolAnt (http://gym.openai.com/envs/RoboschoolAnt-v1/), requires `roboschool` package. 
Hope that helps and closing this issue.
