### ISSUE TITLE
What's the difference between environments such as 'Pong-v0' and 'PongDeterministic-v0'

### ISSUE THREAD

**Issue by HuiSiqi** [openai/gym#1446]
I'm sorry to ask a simple question.
In the environment list I just found there are lots of environment has a similar environment which just insert the text 'Deterministic' in the environment's name. That bothered me a lot.
And you guys are doing a great job, thanks for what you have contributed!

**Comment by christopherhesse** [comment]
`Deterministic` here refers to the frameskip, https://github.com/openai/gym/blob/7006c7a182a991b9409c206c56abc121eaffafb5/gym/envs/__init__.py#L626

You can have a random number of frames being skipped each time in some range, or you can always skip 4 frames, or you can have no frameskip.

Arguably there should be just a single canonical version of each atari game and the variants would be accessed by instantiating `AtariEnv` directly.  You can also create the `NoFrameskip-v4` version and get something that's basically `AtariEnv`.
