### ISSUE TITLE
Add get_observation() function to allow arbitrary repeated access to current observation

### ISSUE THREAD

**Issue by alexandervandekleut** [openai/gym#1464]
Hello all,

I think that it would be beneficial to be able to arbitrarily ask an env for the current observation many times. The purpose of this is that it would be nice to be able to wrap the same environment twice with two different wrappers, so that you can modify observations from the same environment in different ways.

Consider needing to wrap the same environment so that you can get
1) Normalized rewards for single frames
2) Greyscaled, resized, and frame-stacked observations for the last N frames.

Say I want to have something like
env = gym.make(...)
env1 = wrapper1(env)
env2 = wrapper2(env)

Then I can call env.step(...), and when needed, call env1.observation() and env2.observation() to get those modified observations as needed.

Currently, observation in the ObservationWrapper accepts an observation, makes modifications, then returns it. I would like to be able to be able to just call observation() to get the current observation.

**Comment by christopherhesse** [comment]
Why not make a wrapper that adds a `get_observation()` function that returns the last observation from `step()`?

**Comment by alexandervandekleut** [comment]
@christopherhesse I think my brain turned to mush thinking about this issue. Great idea.
