### ISSUE TITLE
How do I access environment registration data (for e.g. max_episode_steps)  from within my custom environment?

### ISSUE THREAD

**Issue by sibyjackgrove** [openai/gym#1465]
I want to have access to the `max_episode_steps` and `reward_threshold `that  are specified in __init__.py
For eg: 
```
from gym.envs.registration import registry, register, make, spec
register(
    id='myenv-v0',
    entry_point='gym.envs.algorithmic:myenv',
    max_episode_steps=500,
    reward_threshold=25.0,
)
```
But how do I access this from` gym_myenv.py`?
If I first create the environment and use env._max_episode_steps, I have access. However, I don't have access to _max_episode_steps from within ` gym_myenv.py`.

**Comment by christopherhesse** [comment]
This seems to work fine for me:

```
import gym
env = gym.make("CartPole-v0")
print(env._max_episode_steps)
```

Do you have an example that doesn't work?

**Comment by sibyjackgrove** [comment]
It seems the only way to do this currently is to access them outside the __init__ method that is after the gym environment object has been created i.e in any other method like reset() or render() or others.

It can be accessed either using `self.spec.max_episode_steps` or `self._max_episode_steps`

I am not sure whether it was intended to be like this or could it be a bug.

**Comment by sibyjackgrove** [comment]
> This seems to work fine for me:
> 
> ```
> import gym
> env = gym.make("CartPole-v0")
> print(env._max_episode_steps)
> ```
> 
> Do you have an example that doesn't work?

Yes, `env._max_episode_steps` also works for me.  But I want access to `max_episode_steps` in the `__init__() `method.  If I use `self._max_episode_steps` or `self.spec.max_episode_steps` within the `__init__() `method and do `gym.make('myenv-v0') `it will throw the following error. 
> object has no attribute '_max_episode_steps'

However, it will work in any method outside` __init__()`.

**Comment by christopherhesse** [comment]
The `__init__()` method of your environment?  I don't think environments have access to their wrappers in general.  Could you make the step limit part of your environment instead of relying on `gym.make` to add it?

**Comment by rickstaa** [comment]
For future reference, as discussed in https://github.com/Farama-Foundation/Gymnasium/issues/615#issuecomment-1639969801, below is a simple Gymnasium wrapper that can be used to inject the `max_episode_steps` attribute found in a potentially nested [TimeLimit](https://github.com/Farama-Foundation/Gymnasium/blob/8a75f5a5cab9cca68ddfd7156bcf8639152e7625/gymnasium/wrappers/time_limit.py) wrapper into the base environment:

```python
"""This file contains a small gymnasium wrapper that injects the `max_episode_steps`
argument of a potentially nested `TimeLimit` wrapper into the base environment under the
`_time_limit_max_episode_steps` attribute.
"""
import gymnasium as gym


def get_time_limit_wrapper_max_episode_steps(env):
    """Returns the ``max_episode_steps`` attribute of a potentially nested
    ``TimeLimit`` wrapper.

    Args:
        env (gym.Env): The gymnasium environment.

    Returns:
        int: The value of the ``max_episode_steps`` attribute of a potentially nested
            ``TimeLimit`` wrapper. If the environment is not wrapped in a ``TimeLimit``
            wrapper, then this function returns ``None``.
    """
    if hasattr(env, "env"):
        if isinstance(env, gym.wrappers.TimeLimit):
            return env._max_episode_steps
        get_time_limit_wrapper_max_episode_steps(env.env)
    return None


def inject_attribute_into_base_env(env, attribute_name, attribute_value):
    """Injects the ``max_episode_steps`` argument into the base environment under the
    `_time_limit_max_episode_steps` attribute.

    Args:
        env (gym.Env): The gymnasium environment.
        attribute_name (str): The attribute's name to inject into the base
            environment.
        attribute_value (object): The attribute's value to inject into the base
            environment.
    """
    if hasattr(env, "env"):
        return inject_attribute_into_base_env(env.env, attribute_name, attribute_value)
    setattr(env, attribute_name, attribute_value)


class MaxEpisodeStepsInjectionWrapper(gym.Wrapper):
    """A gymnasium wrapper that injects the ``max_episode_steps`` attribute of the
    ``TimeLimit`` wrapper into the base environment as the
    ``_time_limit_max_episode_steps`` attribute. If the environment is not wrapped in
    a ``TimeLimit`` wrapper, then the ``_time_limit_max_episode_steps`` attribute is
    set to ``None``.
    """
    def __init__(self, env):
        """Wrap a gymnasium environment.
        Args:
            env (gym.Env): The gymnasium environment.
        """
        super().__init__(env)

        # Retrieve max_episode_steps from potentially nested TimeLimit wrappers.
        max_episode_steps = get_time_limit_wrapper_max_episode_steps(self.env)

        # Inject the max_episode_steps attribute into the base environment.
        inject_attribute_into_base_env(
            self.env, "_time_limit_max_episode_steps", max_episode_steps
        )
```

This wrapper can be specified through the [additional_wrappers parameter of the gym.register method](https://gymnasium.farama.org/api/registry/#gymnasium.register):

```python
import gymnasium as gym
from MY_PACKAGE.max_episode_steps_injection_wrapper import MaxEpisodeStepsInjectionWrapper

gym.register(
        id="ENV_ID",
        entry_point="ENV_ENTRY_POINT",
        max_episode_steps="MAX_EPISODE_STEPS",
        additional_wrappers=(MaxEpisodeStepsInjectionWrapper.wrapper_spec(),)
)
```
