### ISSUE TITLE
How to modify the reward function for mountaincar-v0?

### ISSUE THREAD

**Issue by FassyGit** [openai/gym#1468]
Hi, 
I want to modify the MountainCar-v0 env, and change the reward for every time step to 0.
Is there any way to do this?
Thanks!

**Comment by christopherhesse** [comment]
Yep, just change this line to have reward 0: https://github.com/openai/gym/blob/master/gym/envs/classic_control/mountain_car.py#L54

You'll want to clone the gym repo, do `pip install -e gym` and then make your changes locally.
