### ISSUE TITLE
How should one represent a union space?

### ISSUE THREAD

**Issue by j2kun** [openai/gym#1469]
Suppose I want to represent an action space which is a union of a Box space and a Discrete space. How should I express that as a space?

**Comment by christopherhesse** [comment]
Does a Dict space work for you?

**Comment by DanielTakeshi** [comment]
@j2kun (fan of your blog :-) )There is a tuple space here: https://github.com/openai/gym/blob/master/gym/spaces/tuple.py

**Comment by j2kun** [comment]
Sorry, I meant a space that represents an "exclusive or" of two possible options. I want the action to be, for example, "either select a point in a Box, or choose from the set {A, B, C}, but not both"

**Comment by j2kun** [comment]
I'm particularly confused by how such spaces might encode such an "exclusive or" in the policies that would be built from them. I could probably hack something that works, but I worry that an unsuitable representation would hinder agents from learning.

**Comment by christopherhesse** [comment]
I think the general hope is that agents should be able to figure out these sorts of things out.  If you provide a Box and a Discrete space, and then another Discrete space to choose which one the agent means to use, the agent would ideally figure out when to activate which one.

**Comment by j2kun** [comment]
Sounds like an answer to me! Thanks!
