### ISSUE TITLE
video_recorder imageio

### ISSUE THREAD

**Issue by christopherhesse** [openai/gym#1470]
`video_recorder.py` should likely use `imageio` and `imageio-ffmpeg` to avoid depending on the system `ffmpeg` install.

This dependency is already required for some of the environments, so it's not adding too much.

**Comment by vis7** [comment]
i am facing #948 that issue redirected me hear I still don't found any solution

**Comment by RaihanKhan1970** [comment]
What is the solution, folks?  I don't see one here.  Looking for help with the video encoder error when trying to record videos from open AI gym
