### ISSUE TITLE
First example crashes with segmentation fault

### ISSUE THREAD

**Issue by i3games** [openai/gym#1472]
After installing gym into an Anaconda environment with pip (Mac OSX 10.14.4), 

> Successfully installed future-0.17.1 gym-0.12.1 pyglet-1.3.2 scipy-1.2.1

I am trying to run the first code example on 

https://gym.openai.com/docs/

```
import gym
env = gym.make('CartPole-v0')
env.reset()
for _ in range(1000):
    env.render()
    env.step(env.action_space.sample()) # take a random action
env.close()
```

Result (animation runs): 

> /miniconda3/envs/ml/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: WARN: You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behaviour.
>   warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))

After closing the window, python crashes with a segfault:

> Traceback (most recent call last):
>   File "_ctypes/callbacks.c", line 234, in 'calling callback function'
>   File "/miniconda3/envs/ml/lib/python3.6/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 1121, in objc_method
>     result = f(py_self, *args)
>   File "/miniconda3/envs/ml/lib/python3.6/site-packages/pyglet/window/cocoa/pyglet_window.py", line 25, in nextEventMatchingMask_untilDate_inMode_dequeue_
>     if self.inLiveResize():
>   File "/miniconda3/envs/ml/lib/python3.6/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 785, in __call__
>     return self.method(self.objc_id, *args)
>   File "/miniconda3/envs/ml/lib/python3.6/site-packages/pyglet/libs/darwin/cocoapy/runtime.py", line 753, in __call__
>     f = self.get_callable()
> RecursionError: maximum recursion depth exceeded
> Segmentation fault: 11

**Comment by christopherhesse** [comment]
I guess the docs should be updated again, what happens if you do:

```
import gym
env = gym.make('CartPole-v0')
env.reset()
for _ in range(1000):
    if not env.render():
        break
    obs, rew, done, info = env.step(env.action_space.sample()) # take a random action
    if done:
        obs = env.reset()
env.close()
```

**Comment by i3games** [comment]
1. The warning doesn't appear and the simulation runs until the end.

2. When try I close the window however, python still crashes with the segfault. This is a known bug in Pyglet - possibly related to Retina displays: https://bitbucket.org/pyglet/pyglet/issues/229/closing-window-causes-a-crash-on-mac-os

**Comment by christopherhesse** [comment]
Okay, we should update the site docs

**Comment by christopherhesse** [comment]
It looks like the warning is expected, the docs address this in the following section.  I added some clarification to the first section which should be deployed next time we update the site.

Thanks for finding the pyglet bug!  I will close this issue in favor of that bug though.
