### ISSUE TITLE
Best 100-episode performance meaning?

### ISSUE THREAD

**Issue by bhansconnect** [openai/gym#1477]
Hi,

So I have seen best 100-episode performance calculated in a few different ways and I was wondering if there is some page/article that correctly defines this.

Here are some of what I have seen:
- Best average of 100 episodes given infinite amounts of training
- Single best result given 100 episodes to train on
- Best average of 100 test episodes given 100 episodes of training

Any clarification or help would be greatly appreciated.

**Comment by christopherhesse** [comment]
This sounds like something where this is no "correct" way and it's up to the individual page/article that defines it :/

**Comment by bhansconnect** [comment]
What is the point of a leaderboard if there is no standard for how to measure performance? Best 100-performance is recorded on the leaderboard on the wiki.
