### ISSUE TITLE
how can i mix continuous and discrete action_space ?

### ISSUE THREAD

**Issue by greg2paris** [openai/gym#1482]
Hello, 
I would like to make an environement with continuous and discrete actions space but I dont realy know how to do it.

For exemple, one discrete action will be :
buy stock

And the continous action will be : 
How many stocks

I saw that i could create continous action space with : 
action_space = spaces.Box(np.array([-10, -10, -10, -10]),
                    np.array([10, 10, 10, 10]), 
                    dtype=np.float32)

I could mabe get away with this as for every action will represent one different stock.
So for exemple, -10 would sell 10 stocks, and 8 will buy 8 stocks.

But I would realy make the diferenciation between "buy stock" and "how many stock to trade".
So I would like to have two differents actions.
One discrete and one continous.

Do you know how I could do that?

**Comment by christopherhesse** [comment]
You should put them in a Dict space, `{"buy": Discrete(<number of different stocks), "amount": Box()}`

**Comment by greg2paris** [comment]
ok thanks for the answer, i never understand how the dict are working
