### ISSUE TITLE
observation_space or action space sample error when ranges are infinity

### ISSUE THREAD

**Issue by sritee** [openai/gym#1494]
There are situations where sampling from observation or action space can be useful, for example while doing random shooting in model-based RL. When we do this for environments which have an infinite range, it throws an error. Overflow error: Range exceeds valid bounds.

I propose to sample from a normal distribution in such cases, or use (sys.maxsize) to sample uniformly. What do you think? I can make a PR if that's reasonable.

**Comment by christopherhesse** [comment]
Do the environments actually have infinite range?  It might be better to put limits on the environment's spaces.

**Comment by sritee** [comment]
Well technically, I think mujoco is fine accepting in the infinite range, which is why perhaps this is the case. I feel sampling should, however, be valid. Perhaps we can have a clip argument to the sampler if necessary. That would be an easy fix.

**Comment by sritee** [comment]
Fixed by #1567, #1579
