### ISSUE TITLE
Remove support for Python 2.7

### ISSUE THREAD

**Issue by zuoxingdong** [openai/gym#1501]
At some point, it might be reasonable to consider removing official support for Python 2.7 as it'll be discontinued for maintenance in a few months, and many standard libraries also start to drop Python 2 support. This would further make some code cleaner.

**Comment by christopherhesse** [comment]
I think sometime next year we should drop support for Python 2.7, but I'm not sure how much cleaner it will make the code, do you have some examples?

**Comment by Jonahss** [comment]
Removing support for python 2 would allow you to drop python-future as a dependency. Which is where the rest of the deprecation warnings which appear during tests stem from.
