### ISSUE TITLE
Website probably relies on Chrome bug.

### ISSUE THREAD

**Issue by emilio** [openai/gym#1504]
Hey, the website of this project renders wrong in Firefox, and turns out that it'll start rendering wrong in Chrome too, since you're relying on a Chrome bug that's fixed with their new layout engine (you can try it in Chrome Dev / Chrome Canary with "Enable LayoutNG").

See https://bugzilla.mozilla.org/show_bug.cgi?id=1545063 for the details and a reduced test-case.

// cc @bfgeek

**Comment by christopherhesse** [comment]
Hmm, is there an easy fix to the CSS?

**Comment by emilio** [comment]
Adding `display: flow-root` / `overflow: hidden` to `.GlobalNav` should fix it.

**Comment by christopherhesse** [comment]
Fixed on the internal version, thanks for the bug report!
