### ISSUE TITLE
python neat parallel learning when doing env.render the windows do not close  

### ISSUE THREAD

**Issue by jimhoggey** [openai/gym#1507]
Python neat parallel learning with 3 workers learning at once when in the code env.render is renders the environment but after its done the window does not close witch means there are a heap of inactive windows all over the desktop.
is there a way to fix this or use open cv to display the environment?

thanks

**Comment by AkshayS96** [comment]
did you use env.close() after learning

**Comment by christopherhesse** [comment]
Thanks for answering this @AkshayS96!

**Comment by jimhoggey** [comment]
sorry this question is not yet answered.genome.fitness = job.get(timeout=self.timeout)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 670, in get
    raise self._value
NameError: name 'env' is not defined

I put env.close in the done = true function.
but it still seems to spit out a bunch of windows

**Comment by paulcarouge** [comment]
have you found a solution for this?
