### ISSUE TITLE
How to render

### ISSUE THREAD

**Issue by abhinavsagar** [openai/gym#1508]
Documentation lacking how to render.

**Comment by christopherhesse** [comment]
I think the example on https://gym.openai.com/ shows how to render, am I missing something?

**Comment by abhinavsagar** [comment]
I need to render [this](https://github.com/openai/gym/blob/master/gym/envs/atari/atari_env.py). On running `python atari_env.py`, I am not getting anything. How should I proceed?

**Comment by AkshayS96** [comment]
This is the environment file which will make the environment for you. Running this file won't give you any output. For rendering the environment you have to make the environment using gym.make() then on that environment you can call env.render() after that you will be able to see the rendered environment.

**Comment by DollarAkshay** [comment]
`env.render()`

**Comment by christopherhesse** [comment]
Thanks for answering @AkshayS96 !
