### ISSUE TITLE
NotImplementedError

### ISSUE THREAD

**Issue by IsaacPatole** [openai/gym#1510]
I'm getting an error as following
----------------------------------------------------------------------------------------------------------
state = env.reset()
  File "C:\Users\hp\AppData\Local\Programs\Python\Python36\lib\site-packages\gym\core.py", line 69, in reset
    raise NotImplementedError
----------------------------------------------------------------------------------------------------------
I also tried env._reset() instead of env.reset(), my gym package is up to date, but nothing is working, I am using the code from the following link : https://github.com/llSourcell/Q-Learning-for-Trading 

Please let me know what changes I should make in order to solve this.

**Comment by IsaacPatole** [comment]
Closing the issue as I found the answer, I had to change methods from envs.py file as _reset() to reset()  and so on..

**Comment by azyslzp** [comment]
Hi, I have met the same problem, have you solved this problem? Thanks a lot
