### ISSUE TITLE
Can not import self defined environment correctly

### ISSUE THREAD

**Issue by Maximilian92** [openai/gym#1514]
Hello,  I am a beginner using openai gym and now I have a problem with it.
I defined an environment myself and try to register it into the gym package.
Following steps are what I did:

1. Put my environment document into the directory ~/Anaconda3/Lib/site-packages/gym/envs/user

2. Append the following code in __init__ file in gym directory:

register(
	id='Env_arbeitsraum' # Name of my environment
	entry_point='gym.envs.user:Env_arbeitsraum',
	max_episode_steps=200
	reward_threshold=0,9
	)

3. Try to run the following code:

import gym
env = gym.make('Env_arbeitsraum')

4. Then I saw the following information:

[autoreload of gym.envs failed: Traceback (most recent call last):
  File "D:\Applications.Pro\Anaconda3\lib\site-packages\IPython\extensions\autoreload.py", line 244, in check
    superreload(m, reload, self.old_objects)
  File "D:\Applications.Pro\Anaconda3\lib\site-packages\IPython\extensions\autoreload.py", line 378, in superreload
    module = reload(module)
  File "D:\Applications.Pro\Anaconda3\lib\imp.py", line 314, in reload
    return importlib.reload(module)
  File "D:\Applications.Pro\Anaconda3\lib\importlib\__init__.py", line 169, in reload
    _bootstrap._exec(spec, module)
  File "<frozen importlib._bootstrap>", line 630, in _exec
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\Applications.Pro\Anaconda3\lib\site-packages\gym\envs\__init__.py", line 598
    entry_point='gym.envs.user:Env_arbeitsraum',
              ^
SyntaxError: invalid syntax
]
Traceback (most recent call last):

  File "<ipython-input-3-a6de884fa40f>", line 1, in <module>
    runfile('C:/Users/lenovo/Desktop/cnc/test.py', wdir='C:/Users/lenovo/Desktop/cnc')

  File "D:\Applications.Pro\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 786, in runfile
    execfile(filename, namespace)

  File "D:\Applications.Pro\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 110, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/lenovo/Desktop/cnc/test.py", line 10, in <module>
    env = gym.make('Env_arbeitsraum')

  File "D:\Applications.Pro\Anaconda3\lib\site-packages\gym\envs\registration.py", line 183, in make
    return registry.make(id, **kwargs)

  File "D:\Applications.Pro\Anaconda3\lib\site-packages\gym\envs\registration.py", line 124, in make
    spec = self.spec(path)

  File "D:\Applications.Pro\Anaconda3\lib\site-packages\gym\envs\registration.py", line 156, in spec
    raise error.Error('Attempted to look up malformed environment ID: {}. (Currently all IDs must be of the form {}.)'.format(id.encode('utf-8'), env_id_re.pattern))

Error: Attempted to look up malformed environment ID: b'Env_arbeitsraum'. (Currently all IDs must be of the form ^(?:[\w:-]+\/)?([\w:.-]+)-v(\d+)$.)

So what should I do to solve the problem and import my environment correctly and successfully? Thank you so much for your help!

**Comment by christopherhesse** [comment]
It looks like your code is not valid python:

```
register(
id='Env_arbeitsraum' # Name of my environment <- missing comma on this line
entry_point='gym.envs.user:Env_arbeitsraum',
max_episode_steps=200
reward_threshold=0,9 <- not sure if comma is supported here
)
```

You may want to read up some more on python before making a gym environment.

**Comment by Maximilian92** [comment]
> It looks like your code is not valid python:
> 
> ```
> register(
> id='Env_arbeitsraum' # Name of my environment <- missing comma on this line
> entry_point='gym.envs.user:Env_arbeitsraum',
> max_episode_steps=200
> reward_threshold=0,9 <- not sure if comma is supported here
> )
> ```
> 
> You may want to read up some more on python before making a gym environment.

Thank you for checking the code! It's my fault not to check it carefully before asking. But the problem seems not about the comma, because I typed in the code correctly and still, I could not import my env. But when I try to add '-v0' after the name of my env like this:
`register(
    id='WorkingSpace-v0',
    entry_point='gym.envs.user:working_space',
    reward_threshold=0.9,
    )`
Then it works. The same error doesn't show any more.
But there is another problem here. I imported a module (not built in module), then there is a new error:
ModuleNotFoundError: No module named 'binvox_rw'
I tried to copy the binvow_rw.py file into the directory but it doesn't work. Any solutions?
Thanks a lot! :)

**Comment by SolowomanYudachi** [comment]
> > It looks like your code is not valid python:
> > ```
> > register(
> > id='Env_arbeitsraum' # Name of my environment <- missing comma on this line
> > entry_point='gym.envs.user:Env_arbeitsraum',
> > max_episode_steps=200
> > reward_threshold=0,9 <- not sure if comma is supported here
> > )
> > ```
> > 
> > 
> > You may want to read up some more on python before making a gym environment.
> 
> Thank you for checking the code! It's my fault not to check it carefully before asking. But the problem seems not about the comma, because I typed in the code correctly and still, I could not import my env. But when I try to add '-v0' after the name of my env like this:
> 
> ```
> register(
>     id='WorkingSpace-v0',
>     entry_point='gym.envs.user:working_space',
>     reward_threshold=0.9,
>     )
> ```
> 
> Then it works. The same error doesn't show any more.
> But there is another problem here. I imported a module (not built in module) in my self defined environment, then there is a new error:
> ModuleNotFoundError: No module named 'binvox_rw'
> I tried to copy the binvow_rw.py file into the directory but it doesn't work. Any solutions?
> Thanks a lot! :)

Hello there, just wanna ask if there was any further development after that? I encountered a similar issue with the registry and it omits an ID format error.

**Comment by yepw** [comment]
@Maximilian92 @SolowomanYudachi To import a local file in a custom environment, you can take a look how they import utils.py https://github.com/Farama-Foundation/Gymnasium/tree/main/gymnasium/envs/classic_control
