### ISSUE TITLE
Attribute Error: ... object had no attribute 'make'

### ISSUE THREAD

**Issue by LRLinnell** [openai/gym#1517]
Trying to run OpenAI Universe on Raspberry Pi. My first three lines are:
import universe
import gym
env = gym.make('flashgames.NeonRace-v0')

I get an error from Python 3.4.2 Shell "Attribute Error: 'module' object had no attribute 'make'"
the gym folder is located: $HOME/gym/gym

I have been reading all the posts I can find for the last 4 hours and no luck. Any ideas?

Thanks, Lloyd

**Comment by christopherhesse** [comment]
I'm afraid we don't support universe anymore :(
