### ISSUE TITLE
Action space, state space docs for fetch

### ISSUE THREAD

**Issue by migom6** [openai/gym#1518]
Is there any documentation for the description of models of the robotics fetch models?
https://gym.openai.com/envs/#robotics
Thanks.

**Comment by asdint** [comment]
HELP!!!

**Comment by sritee** [comment]
What do you guys want to know particularly?

**Comment by Amritpal-001** [comment]
@asdint , @migom6 - I wrote a recent article about Fetch environments in OpenAI [https://link.medium.com/CV6la7YfV7](https://link.medium.com/CV6la7YfV7). It talks about the environment's observations, action variables and their components. I hope it's helpful.

**Comment by jkterry1** [comment]
see gymlibrary.ml
