### ISSUE TITLE
Can I run Open-AI in cloud9?(ipython notebook

### ISSUE THREAD

**Issue by darren1231** [openai/gym#152]
![image](https://cloud.githubusercontent.com/assets/17348113/15734107/8cad50ec-28be-11e6-9525-b136019afb80.png)

I tried to used ipython notebook to run Open-AI in cloud9.
But it seems that render returned nothing.
Is that normal?

**Comment by jietang** [comment]
close=True will close the viewer. Can you try running env.render(mode='rgb_array')?

**Comment by darren1231** [comment]
No, it created a a lot of words and said error.
![image](https://cloud.githubusercontent.com/assets/17348113/15741650/3106affc-28ed-11e6-9222-cf6aa0cae721.png)
![image](https://cloud.githubusercontent.com/assets/17348113/15741704/7453ad1e-28ed-11e6-96bf-4b75ea0e21d5.png)

**Comment by JKCooper2** [comment]
env.render() doesn't return anything to assign to a. You should just be able to call `env.render()` without assigning to anything. You don't need to set the mode for most environments unless you are overwriting the default, CartPole should work just fine with the default rendering mode

**Comment by jietang** [comment]
I suspect that the pyglet-based rendering we use cannot handle rendering inside the notebook (in the stack trace you can see it trying to open an xlib.XOpenDisplay and failing). We're unlikely to support this at present but could add it depending on demand.

As an experiment to verify that gym is working properly, you can try running on the FrozenLake-v0 environment - it should render to stdout (if you use the default 'human' mode) or a StringIO (if you use the 'ansi' mode)

**Comment by gdb** [comment]
(Also relevant: https://github.com/openai/gym/issues/56.)

**Comment by darren1231** [comment]
Thank you all guys.
I have found another method.
Because cloud9 is similiar to docker which is a virtual machine.
So I have to run next line.
Xvfb :12 -screen 0 800x600x24 +extension RANDR 2>/dev/null &
export DISPLAY=:12
Then run the code.   It worked, but it can only produce picture without showing the screen.
Now I just have to combine them into gif then I can watch the movie!!!~~

**Comment by jietang** [comment]
Glad you got to the bottom of it.

**Comment by Faur** [comment]
Can you elaborate on your solution? I am having a very similar problem.

I am using jupyter on a AWS server. I get the following error

`GLXInfoException: pyglet requires an X server with GLX`

**Comment by Faur** [comment]
It seems that this is solved in #247 now
