### ISSUE TITLE
Matching state variables to observations

### ISSUE THREAD

**Issue by kyr-pol** [openai/gym#1521]
Hi everyone,

I've been trying to figure out to what variable each observation in the Swimmer environment corresponds to, any ideas?

I saw in the swimmer.py that the first few correspond to positions and the rest to velocities `return np.concatenate([qpos.flat[2:], qvel.flat])`, but haven't managed to get which are the positions exactly (and which are the two that are skipped) from the swimmer.xml. In general is there a standard way of figuring this out (from the .xml file or elsewhere) ? Should I read something in the mujoco documentation?

**Comment by QuXinghuaNTU** [comment]
Same issue for me. Still cannot find such kind of document. Will come back here if there is any good news.

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
