### ISSUE TITLE
AssertionError: nvec (counts) have to be positive

### ISSUE THREAD

**Issue by AnuragGIITB** [openai/gym#1526]
spaces.MultiDiscrete throw AssertionError: nvec (counts) have to be positive for python 3.6 but works fine for python 2.7.

**Comment by christopherhesse** [comment]
Are you using different versions of gym in each python installation?  https://github.com/openai/gym/pull/1249

Also, are you sending negative counts to multidiscrete?

**Comment by AntoineMath** [comment]
Same question @AnuragGIITB
