### ISSUE TITLE
Mujoco halfcheetah - is there a useful range for the observation space?

### ISSUE THREAD

**Issue by richielo** [openai/gym#1530]
As titled, may I ask if there's a useful range for the observation space in Mujoco environments like half-cheetah?  I saw that in Lunar Lander, even though the observation space is unbounded, the comment in the source code indicated a useful range which is between -1 and 1. So I am wondering is there anything similar with Mujoco.

Thanks a lot

**Comment by QuXinghuaNTU** [comment]
I am also looking for such information. However, it seems mujoco does not provide such kind of document. Even for understanding the physical description of the state and action space, it is also quite hard. Reading the xml file is a difficult job for the person who is not from robotics engineering.

**Comment by sritee** [comment]
Try running a trained policy and observing.

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
