### ISSUE TITLE
Registered wrapped environments have no spec

### ISSUE THREAD

**Issue by tristandeleu** [openai/gym#1554]
When trying to register a custom environment (eg. an environment with a wrapper), the `spec` property doesn't seem to be properly set. Here is a minimal example
```python
# breakout.py
from gym.envs.registration import register
from gym.envs.atari import AtariEnv
from gym.wrappers import AtariPreprocessing

def breakout():
    env = AtariEnv('breakout')
    env = AtariPreprocessing(env)
    return env

register(
    'BreakoutProcessed-v0',
    entry_point='breakout:breakout',
    max_episode_steps=10000
)
```

```python
import gym
import breakout

env = gym.make('BreakoutProcessed-v0')

# ---------------------------------------------------------------------------
# AttributeError                            Traceback (most recent call last)
# test_env.py in <module>
#       2 import breakout
#       3
# ----> 4 env = gym.make('BreakoutProcessed-v0')
# 
# gym/gym/envs/registration.py in make(id, **kwargs)
#     154
#     155 def make(id, **kwargs):
# --> 156     return registry.make(id, **kwargs)
#     157
#     158 def spec(id):
# 
# gym/gym/envs/registration.py in make(self, path, **kwargs)
#     106         if hasattr(env, "_reset") and hasattr(env, "_step") and not getattr(env, "_gym_disable_underscore_compat", False):
#     107             patch_deprecated_methods(env)
# --> 108         if (env.spec.max_episode_steps is not None) and not spec.tags.get('vnc'):
#     109             from gym.wrappers.time_limit import TimeLimit
#     110             env = TimeLimit(env, max_episode_steps=env.spec.max_episode_steps)
# 
# AttributeError: 'NoneType' object has no attribute 'max_episode_steps'
```

**Comment by tristandeleu** [comment]
One solution may be to have `spec` as a `@property` in `Wrapper` [here](https://github.com/openai/gym/blob/220ae8487d9436fba0322b18bcb0402790c25335/gym/core.py#L212)
```python
@property
def spec(self):
    return self.env.spec
```

**Comment by lespeholt** [comment]
Running into the same issue. @tristandeleu 's fix works.

**Comment by christopherhesse** [comment]
Could be related to https://github.com/openai/gym/pull/1525

We should also try removing this line: https://github.com/openai/gym/blob/220ae8487d9436fba0322b18bcb0402790c25335/gym/core.py#L212 since it's shadowing the env's spec property.

**Comment by zuoxingdong** [comment]
> shadowing the env's spec property

@christopherhesse If I got it correctly, `spec` can already be reachable by [this line](https://github.com/openai/gym/blob/220ae8487d9436fba0322b18bcb0402790c25335/gym/core.py#L214) ?

**Comment by pzhokhov** [comment]
`__getattr__` does not work here because Wrapper subclasses from Env, and Env has class-level spec property set to None (so __getattr__ is not being called). I think the cleanest solution is what @tristandeleu proposed, combined with @christopherhesse proposition of removing https://github.com/openai/gym/blob/220ae8487d9436fba0322b18bcb0402790c25335/gym/core.py#L212 line

**Comment by pzhokhov** [comment]
https://github.com/openai/gym/pull/1574

**Comment by PierreExeter** [comment]
> #1574

It seems that after this fix, I can no longer have a private method in my custom environment and the spec `max_episode_step` at the same time.

**This works:**
My environment with my `_start_sim` private method and `max_episode_step` not specified.
```python
def _start_sim(self):
```
\+
```python
register(id='my_env-v0', entry_point='my_env.envs:MyEnv')
```
\+
```python
env = gym.make('my_env-v0')._start_sim()
```

**This works:**
My environment without my `_start_sim` private method and `max_episode_step` specified.
```python
register(id='my_env-v1', entry_point='my_env.envs:MyEnv', max_episode_step=100)
```
\+
```python
env = gym.make('my_env-v1')
```

**This doesn't work:**
My environment with my `_start_sim` private method and `max_episode_step` specified.
```python
def _start_sim(self):
```
\+
```python
register(id='my_env-v2', entry_point='my_env.envs:MyEnv', max_episode_step=100)
```
\+
```python
env = gym.make('my_env-v2')._start_sim()
```

This return the following error:
```
AttributeError: attempted to get missing private attribute '_start_sim'
```

Does anybody know how to use private methods in the environment and the max_episode_step spec at the same time?

Thanks

**Comment by PierreExeter** [comment]
I found the solution right after my previous post... I just had to delete the underscore in front of my private method (i.e. `start_sim` instead of `_start_sim`).
