### ISSUE TITLE
Using pyglet label to draw text when rendering

### ISSUE THREAD

**Issue by dickreuter** [openai/gym#1555]
I'm having issues in drawing a label in combination with the gym wrapper around pyglet. I tried ti implement it as show in the code snippet below, adding a label and then using label.draw().

In my case the Label simply doesn't appear. I'm wondering if this is because it's jsed in conjunction of the viewer method of the gym?

```
import pyglet
from gym.envs.classic_control import rendering

screen_width = 600
screen_height = 400
table_radius = 200

viewer = rendering.Viewer(screen_width, screen_height + 20)
table = rendering.make_circle(radius=table_radius, filled=False)
table_trans = rendering.Transform()
table.add_attr(table_trans)
table_trans.set_translation(screen_width / 2, screen_height / 2)

viewer.add_geom(table)

text = 'This is a test but it is not visible'
label = pyglet.text.Label(text, font_size=36,
                          x=10, y=10, anchor_x='left', anchor_y='bottom',
                          color=(255, 123, 255, 255))
label.draw()

viewer.render(return_rgb_array=False)
input()
```

Any suggestions why the label is not drawn? If we can get it to work this is something that should be added to the gym pyglet wrapper.

**Comment by christopherhesse** [comment]
The rendering stuff isn't meant to part of the public gym API, more of an internal detail.  So I'm afraid you're on your own here.  I think we'd consider PRs if there are bugs in the rendering code though.

**Comment by dickreuter** [comment]
ok, no worries. In the end I implemented my own pyglet wrapper: https://github.com/dickreuter/neuron_poker/blob/master/gym_env/rendering.py#L45
