### ISSUE TITLE
Error Installing  atari_py~=0.2.0 with python 3.5.5 on OSX 10.14.5

### ISSUE THREAD

**Issue by gstoica27** [openai/gym#1568]
Hi, 

I am unable to install the atari environment on OSX with the most recent gym. When installing using 
`pip install 'gym[atari]'`
or 
`pip install atary_py=0.2.0`
or 
`pip install -e .[all]`
or 
I have tried suggestions regarding updating brew and cmake to install it but none of them appear to solve the problem. 

I receive the following error: 

ERROR: Could not find a version that satisfies the requirement atari_py~=0.2.0 (from versions: 0.0.1, 0.0.2, 0.0.3, 0.0.4, 0.0.5, 0.0.7, 0.0.8, 0.0.9, 0.0.10, 0.0.11, 0.0.12, 0.0.13, 0.0.14, 0.0.15, 0.0.16, 0.0.17, 0.0.18, 0.0.19, 0.0.20, 0.0.21, 0.1.0, 0.1.1, 0.1.2, 0.1.4, 0.1.6, 0.1.7)
ERROR: No matching distribution found for atari_py~=0.2.0

Which appears to be suggesting that version 0.2.0 is not downloadable. However, it exists as a requirement in the gym source setup.py file: 
`'atari': ['atari_py~=0.2.0', 'Pillow', 'opencv-python'],` on line 10. 

Just running pip install atari_py installs version 0.1.7 which does not appear to be sufficient to run breakout-v0. The following code, 

`import gym
env = gym.make('Breakout-ram-v0')
env.reset()
for _ in range(1000):
    env.render()
    env.step(env.action_space.sample()) # take a random action
env.close()`

Returns the error: 
AttributeError: 'ALEInterface' object has no attribute 'getAvailableModes'

Which from online suggests that the atari_py install is outdated, despite it being the latest available version to download. 

Is there anything that stands out to try instead? 

Thanks very much for your help and time!

**Comment by christopherhesse** [comment]
@pzhokhov it looks like atari-py isn't uploading the source package: 0.1.7 has a .tar.gz here https://pypi.org/project/atari-py/0.1.7/#files but not https://pypi.org/project/atari-py/0.2.0/#files

**Comment by pzhokhov** [comment]
uh oh... while that's weird, I think the real problem is that the wheel for python 3.5 for osx is not being uploaded (even though it exists in the staging).  Will fix shortly.

**Comment by pzhokhov** [comment]
should be fixed now (and I have also manually pushed wheels for 0.2.0 and 0.2.2 versions). Closing this.
