### ISSUE TITLE
How to return a custom variable from DummyVecEnv

### ISSUE THREAD

**Issue by maxmatical** [openai/gym#1584]
I have a custom environment where I want to return some intermediate variables from states, such as raw input values before performing preprocessing. Is there a way to do this? I tried to create a function to return values such as `def _return_values(self)` but when I try to run `CustomEnv._return_values()` I get `AttributeError: 'DummyVecEnv' object has no attribute '_return_values'`

**Comment by christopherhesse** [comment]
`DummyVecEnv` is part of baselines, not gym.  What you're describing should work for gym environments.  If defining a method doesn't work, you can also put whatever you want in the `info` dictionary returned on each step.
