### ISSUE TITLE
addition of differential quaternion rather than multiplication

### ISSUE THREAD

**Issue by kifarid** [openai/gym#1586]
https://github.com/openai/gym/blob/ccd5ef756edc689c03563578b9b46e4fbc5caf72/gym/envs/robotics/utils.py#L56a

` sim.data.mocap_quat[:] = sim.data.mocap_quat + quat_delta`

**Comment by karim174** [comment]
https://github.com/openai/gym/blob/ccd5ef756edc689c03563578b9b46e4fbc5caf72/gym/envs/robotics/utils.py#L56a

shouldn't the differential change in the angle in terms of quaternions be multiplied not added

**Comment by sritee** [comment]
Mathematically multiplication makes sense. However, using addition ight have something to do with the fact that we commonly sample zero mean actions. This corresponds to making the overall rotating zero on average (zero*quat), whereas with this, on average, the arm stays unchanged in position, which is more intuitive.

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
