### ISSUE TITLE
gym.utils.play with grayscale environment

### ISSUE THREAD

**Issue by mphe** [openai/gym#1587]
Hi,

I have a custom environment with preprocessing that converts the image to grayscale and scales it to its half size.
The code looks like this:

```python
obs = self._image_data    # rgb image
w, h = obs.shape[1] // 2, obs.shape[0] // 2
grayimg = cv2.cvtColor(obs, cv2.COLOR_RGB2GRAY)
scaled = cv2.resize(grayimg, (w, h))
return scaled.reshape(h, w, 1)    #  required for some algorithms
```

I used `gym.utils.play` to get a visualization of the observations returned by `env.step()` to see how the agent would see the world.
This worked until f37830bbe2c85f613fded1721976dbe94f6bed0b changed the rendering code  to render the output of `env.render(mode="rgb_array")` instead.
However, since I have a grayscale image, I can't return it in `render()` without first converting it back to RGB format, which would be unnecessary overhead.

Maybe there should be an option in `gym.utils.play` to render either the observation or an RGB array.

**Comment by christopherhesse** [comment]
I don't think `gym.utils.play` or `env.render(mode="rgb_array")` needs to be super high performance.  It's likely true that there should be an option in `gym.utils.play` to choose to show observations or renders, but even in that case it would probably require that the observations be RGB arrays.

For now I'd recommend that `env.render(mode="rgb_array")` actually return an RGB array.  You can do this in a wrapper if you want, just to use it with `gym.utils.play`.

Longer term it might be nice to replace `gym.utils.play` with something similar to the interactive class from retro: https://github.com/openai/retro/blob/master/retro/examples/interactive.py
