### ISSUE TITLE
Sample function issue

### ISSUE THREAD

**Issue by ShibiHe** [openai/gym#159]
The actions in atari games are not continuously from 0 to n-1, so the sample function in https://github.com/openai/gym/blob/master/gym/spaces/discrete.py is probably not right.
breakout's legal actions: [ 0  1  3  4 11 12]
ms_pacman's legal actions: [0 2 3 4 5 6 7 8 9]

For the details, I described this problem in this script: https://github.com/ShibiHe/DQN_OpenAI_keras/blob/master/action_difference.py

**Comment by jietang** [comment]
@ShibiHe We map from the discrete space to valid actions in gym.envs.atari.atari_env. Take a look at the _step() function.

**Comment by jietang** [comment]
Closing for now, let me know if you still think there's an issue after looking through the referenced code
