### ISSUE TITLE
Problem in making atari game environment in window 7 (missing MSVCP140D.dll system error)

### ISSUE THREAD

**Issue by Ali-Ai** [openai/gym#1592]
When I run the command gym.envs.make() it works for other environments like control and algorithmic; however, I can not run it for atari game envs. I have already installed the dependencies!

Below is an example when I tried to run the env = gym.envs.make("Pitfall-v0").

OSError                                   Traceback (most recent call last)
<ipython-input-13-82f4e77742af> in <module>
----> 1 env = gym.envs.make("Pitfall-v0")

... \gym\gym\envs\registration.py in make(id, **kwargs)
    154 
    155 def make(id, **kwargs):
--> 156     return registry.make(id, **kwargs)
    157 
    158 def spec(id):

... \gym\gym\envs\registration.py in make(self, path, **kwargs)
     99             logger.info('Making new env: %s', path)
    100         spec = self.spec(path)
--> 101         env = spec.make(**kwargs)
    102         # We used to have people override _reset/_step rather than
    103         # reset/step. Set _gym_disable_underscore_compat = True on

... \gym\gym\envs\registration.py in make(self, **kwargs)
     70             env = self._entry_point(**_kwargs)
     71         else:
---> 72             cls = load(self._entry_point)
     73             env = cls(**_kwargs)
     74 

... \gym\gym\envs\registration.py in load(name)
     15 def load(name):
     16     mod_name, attr_name = name.split(":")
---> 17     mod = importlib.import_module(mod_name)
     18     fn = getattr(mod, attr_name)
     19     return fn

~\Anaconda3\lib\importlib\__init__.py in import_module(name, package)
    125                 break
    126             level += 1
--> 127     return _bootstrap._gcd_import(name[level:], package, level)

**Comment by christopherhesse** [comment]
I'm afraid we don't provide support for windows.  This looks like you're missing the VC redistributable package:

https://www.microsoft.com/en-US/download/details.aspx?id=48145

or using the chocolatey package manager: https://chocolatey.org/packages/vcredist140

You can file an issue on atari_py to document this for other users though: https://github.com/openai/atari-py/issues

We'd accept any PRs that fix this (maybe the DLLs can be included in the python wheel)

**Comment by Ali-Ai** [comment]
Thanks Christopher. I had already installed the VC redists from the
Microsoft site.
