### ISSUE TITLE
How do I get nested Tuple/Dict space shape? 

### ISSUE THREAD

**Issue by QiXuanWang** [openai/gym#1593]
It seems currently tuple/dict spaces return None for .shape() call. Is there a plan to support this? How about nested version , e.g Tuple(spaces.Discrete(3), spaces.Box(0,1,shape=(3,))) etc.

**Comment by christopherhesse** [comment]
What should shape return in this case?

**Comment by QiXuanWang** [comment]
My assumption would be return element space size for Tuple/Dict. Otherwise, why design such complicated Spaces? You may leave original Tuple/Dict works as it is. 
For me, it seems most Github implementation using Gym will assume .shape returns something meaningful and which mostly assume the space has actual meanings. I don't see the value of complex spaces then.

**Comment by christopherhesse** [comment]
Hmm, it's not clear to me what you mean, for your tuple space in your example, what should `.shape()` return?  Complex spaces may be handy if you have say, an RGB image and a set of lidar observations.
