### ISSUE TITLE
HandReach-v0 goal position not visible in video

### ISSUE THREAD

**Issue by chaitanyadwivedii** [openai/gym#1594]
After running the following 
python3 -m baselines.run --alg her --env HandReach-v0 --num_timesteps 0 --load_path model/t1 --play

I get the following output (attached)
![Screenshot 2019-07-09 at 1 00 24 PM](https://user-images.githubusercontent.com/46801223/60908380-bab13a00-a249-11e9-843d-143e6e0a4ee5.png)
As can be seen the goal positions are not visible in the image. Any reason this might be happening ? Or is this the expected behaviour?  I was expecting something like this:
![image](https://user-images.githubusercontent.com/46801223/60908606-4a56e880-a24a-11e9-9bae-59cb190c9ad6.png)

**Comment by alexlioralexli** [comment]
Downgrading to ``mujoco-py==1.50.1.68 `` solved the visualization problem for me. Note that Gym environments usually expect MuJoCo 150, as discussed here: https://github.com/openai/gym/issues/1541

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
