### ISSUE TITLE
Pendulum should set done = True after it is upright

### ISSUE THREAD

**Issue by gautams3** [openai/gym#1596]
As per the [official description](https://gym.openai.com/envs/Pendulum-v0/), The goal of the pendulum environment is to "to swing it up so it stays upright" (`theta = 0` i.e. vertical upwards, `theta_dot = 0` i.e. stationary)

However, the pendulum env always returns `False` (until `TimeLimit` kicks in, addressed in #1437). This should be changed so that `done = True` if the desired goal state is reached.

**Comment by christopherhesse** [comment]
Does the pendulum ever get to the state where `theta_dot = 0`?  What if the agent were to perform an action after getting it to that state?

**Comment by gautams3** [comment]
Yes it does. But the `step()` function always returns `done=False` by design, as per [this line](https://github.com/openai/gym/blob/master/gym/envs/classic_control/pendulum.py#L47)

I was expecting the episode to end when `theta=0` and `theta_dot=0`

**Comment by christopherhesse** [comment]
The description seems like it could mean the current behavior, staying upright until the timelimit has expired.  Presumably once you've got `theta=0` and `theta_dot=0`, it will be easy to keep it there.  It might be weird that there's no way to get to a done state without the timelimit, but the timelimit wrapper should always be applied when using `gym.make`.

Also if you can get to `theta=0` and `theta_dot=0` often, then it's likely the environment is solved anyway.

**Comment by christopherhesse** [comment]
Closing as we are unlikely to change the behavior of the pendulum environment, though we may want to update the docs if they are unclear.
