### ISSUE TITLE
env.render(mode='rgb_array') fails now

### ISSUE THREAD

**Issue by ZurMaD** [openai/gym#1598]
Hi Openai Team, I was using the env command without errors weeks ago but now I get this error

![imagen](https://user-images.githubusercontent.com/28235457/61154296-58f40880-a4b3-11e9-8eb2-4bf79b71f68f.png)

An stops in this file

https://github.com/openai/gym/blob/f33408c4fd85114baa7b1938b127c0254e8df536/gym/envs/classic_control/rendering.py#L90-L116

**Comment by christopherhesse** [comment]
This should be fixed in `gym==0.13.1` by https://github.com/openai/gym/pull/1591.  pyglet was updated and broke gym.

**Comment by ZurMaD** [comment]
Thanks.
