### ISSUE TITLE
[working deep RL demo][need help]Lasagne+Agentnet baselines

### ISSUE THREAD

**Issue by justheuristic** [openai/gym#16]
Greetings!
We happen to have just pushed into the open source one of the Lasagne-based library for reinforcement learning algorithm design.

* The repo's here: [AgentNet](https://github.com/yandexdataschool/AgentNet)
* [A step-by-step demo for Atari SpaceInvaders ](https://github.com/yandexdataschool/AgentNet/blob/master/examples/Playing%20Atari%20with%20Deep%20Reinforcement%20Learning%20%28OpenAI%20Gym%29.ipynb)
* [Neural Kung-Fu with GRU and actor-critic](https://github.com/yandexdataschool/AgentNet/blob/master/examples/Deep%20Kung-Fu%20with%20GRUs%20and%20A2c%20algorithm%20%28OpenAI%20Gym%29.ipynb)

On the bright side, 
- it is capable of sustaining virtually any custom RL (and even non-RL) architecture using minimalistic Lasagne network design 
- it has most of the generic reinforcement learning algorithms (Q-learning, K-step algos, SARSA, Advantage Actor-Critic)
- It is also capable of interacting with any external environment with a simple wrapper.

On the gloomy one,  it has been made public ~4 days ago and doesn't have a community yet. Prior to that, it's only been used by several Yandex researchers for tinkering.

I would very much like to provide a set of baseline training/testing stands for several problems (and i will do so shortly), for people to be able to experiment with NN architecture, but i'm a bit doubtful about
- whether the interface of the library doesn't have any flaws worth immediate fixing
- whether there is someone interested in tinkering with openai baselines, provided they're readable and performing reasonably.

The most basic Reinforcement Learning pipeline looks [like this](https://github.com/yandexdataschool/AgentNet/blob/master/examples/Basic%20tutorial%20on%20Boolearn%20Reasoning%20problem.ipynb)

The questions are, again, if there is anyone interested in having such baselines for gym problems, and if so, what are possible api improvements you would recommend?

**Comment by wojzaremba** [comment]
Having good, simple baselines is super important. This could tell which simple algorithms work. Feel free to submit your algs, and we will reproduce it, and review it.

**Comment by justheuristic** [comment]
It actually turned out that our interfaces are even closer - around 30 lines of code from my example to start plating atari with simple convolutional q-network.

 - [The demo for Atari AirRaid ](https://github.com/yandexdataschool/AgentNet/blob/master/examples/AirRaid%20-%20Simple%20ConvNet.ipynb) (current notebook output is training session that was interrupted earlier than should be)
- [Some tinkering with SpaceInvaders](https://github.com/yandexdataschool/AgentNet/tree/master/research/gym)

Could you please try to run them on your side to see if they are indeed reproducible?


The problem is, to simplify the code i avoided bot recurrent memory layers and DeepMind tricks from atari article - simply trained a NN that tries to act based on current image frame - and of course i forgot that the atari games have flickering effect and some frames are plain rubbish.
So the next step (after some sleep) is definitely adding memory, since that is why the library was built in the first place. 

Gym is indeed a super-unified interface, as switching through several atari games boiled down to simply switching their names in the notebook header.

Now the main question is, if these demos are at least somewhat readable, what would be the best course of actions to make them more interpretable?

**Comment by justheuristic** [comment]
[updated comment above: the demo became more readable and has better scores]

**Comment by wojzaremba** [comment]
Awesome. Looking forward for you submissions.

**Comment by justheuristic** [comment]
This one is clearly early-stopped (learning curve still goes up almost linearly), but it works ~somehow~ nevertheless.
https://gym.openai.com/evaluations/eval_yv5uO0fRiS7eNaZGFKacw#reproducibility

**Comment by justheuristic** [comment]
The question stands: how to make these more understandable?

**Comment by justheuristic** [comment]
Thanks. 
Added more detailed NN setup.

Again, please suggest any ways this thing can get easier to understand.

**Comment by gdb** [comment]
(I might recommend asking in chat — I think one helpful approach might be to ask a beginner to work through it.)

**Comment by justheuristic** [comment]
Well, i was stupid not to. Thanks!

Upd - trained NN to hurt humans using Kung-Fu, GRU and advantage actor-critic
https://github.com/yandexdataschool/AgentNet/blob/master/examples/Deep%20Kung-Fu%20with%20GRUs%20and%20A2c%20algorithm%20%28OpenAI%20Gym%29.ipynb

**Comment by gdb** [comment]
(Going to close this; please let me know if there's more to discuss!)
