### ISSUE TITLE
Box2D Imports

### ISSUE THREAD

**Issue by Bhaney44** [openai/gym#1608]
One problem I am having is manipulating environments to make new environments because a lot of the packages are unavailable. For example, the Lunar Lander environment uses Box2D.

```
#Import box
import Box2D
from Box2D.b2 import (edgeShape, circleShape, fixtureDef, polygonShape, revoluteJointDef, contactListener)
```
And, the shape of the lander itself is defined as a polygon.

`LANDER_POLY =[(-14,+17), (-17,10), (-17,-10),(+17,-10), (+17,10), (+14,+17)]`

The problem is if I want to make the lander a different shape, like a rectangle, I need to access to the Box2D library. Any suggestions on where I can find the code for Box2D?

With thanks,

Brian

**Comment by christopherhesse** [comment]
Gym uses https://github.com/openai/box2d-py which is a clone of https://github.com/pybox2d/pybox2d.  It looks like the Box2D source is embedded in there.

But since a rectangle is just a special case of a polygon, you should be able to use that to make a rectangle.
