### ISSUE TITLE
How to adjust camera angle when recording video using a Monitor?

### ISSUE THREAD

**Issue by ajlangley** [openai/gym#1609]
Specifically, I'm interested in recording a Mujoco agent. I'd like to be able to reproduce the videos here:

https://www.youtube.com/watch?time_continue=33&v=jeid0wIrSn4

I have been able to change the fixed camera angle by changing the `azimuth` and `elevation` attributes of the camera, but this did not change the angle when the camera followed the agent.

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
