### ISSUE TITLE
Fixed Gripper orientation to Free orientation

### ISSUE THREAD

**Issue by chaiban** [openai/gym#1610]
I trained FetchPickAndPlaceEnv with DDPG + Her. It works fine for cube shaped objects but it is not working for rectangular objects because the gripper rotation is fixed. Is there way to use Gripper without fixing the orientation ? 

################# code from fetch_env
# Move end effector into position.
        gripper_target = np.array([-0.498, 0.005, -0.431 + self.gripper_extra_height]) + self.sim.data.get_site_xpos('robot0:grip')
        gripper_rotation = np.array([1., 0., 1., 0.])  

Thank you!

**Comment by HatemHunish** [comment]
Hello, @chaiban , were you able to solve this issue ?

**Comment by chaiban** [comment]
Hello @HatemHunish ,
NO.
Sorry I drifted apart from this topic. I do not work any longer in this area.

**Comment by ollintzinlab** [comment]
Hello everyone,
I implemented a new environment for xArm6 based on FetchEnv with DDPG+HER. But I have the same problem to free the gripper orientation.
Thank you
