### ISSUE TITLE
Render working for CartPole but not Atari games with identical usage

### ISSUE THREAD

**Issue by justinkterry** [openai/gym#1611]
I've was following the basic PyTorch DQN tutorial using cartpole (https://pytorch.org/tutorials/intermediate/reinforcement_q_learning.html) , and got it to work just fine, and it rendered a live window of the training, a sample frame, and a live plot of the performance after every episode. I ported it to run on breakout (and later space invaders) and while according to the plot it's worked very well, no rendering of the gameplay happens. There's no changes in the code that could cause this. Everything else displays fine (though the sample frame is removed below it does work when included).

 Here's a diff of my code and the working tutorial code: https://www.diffchecker.com/ULceKr5l

I'm using Ubuntu 18.04. What's going on here? This genuinely looks like it may be a bug, and/or possibly related to issue #762 .

Edit:
I tried uninstalling atari_py and building it from source, and the problem persists.

**Comment by justinkterry** [comment]
@christopherhesse Any ideas here?

**Comment by christopherhesse** [comment]
The closest I've seen is https://github.com/openai/gym/issues/1524

Unclear if this is a gym bug, a linux bug, or an atari_py bug.  From your description, it sounds more likely to be an atari_py bug.  What does the output show?

**Comment by justinkterry** [comment]
What output are you referring to? The model appears to be learning just fine based on the reward over episode graph if that's what you're referring to

**Comment by justinkterry** [comment]
I just replicated it on a different Ubuntu 18.04 system. I'll try fedora in the morning to rule out Linux as a potential cause.

**Comment by justinkterry** [comment]
Hey I just ran your test code in the comment on the issue you mentioned, and that code worked for both pong and space invaders. That means the issue is either in my code (which seems unlikely given it's similarity to working code) or gym.

**Comment by justinkterry** [comment]
@christopherhesse have you been able to look into this further?

**Comment by christopherhesse** [comment]
If the test script here works: https://github.com/openai/gym/issues/1524#issuecomment-502300792 then it's likely to be a bug in your code, though there is still some possibility that there is a bug in gym.

Do you have a short self contained example script that demonstrates your issue?
