### ISSUE TITLE
Spaces.DIct implement methods from collections.abc.mapping

### ISSUE THREAD

**Issue by adolfogonzalez3** [openai/gym#1612]
Hello
It would be useful if spaces.Dict had the same non-mutating methods as a python dictionary. This would include implementing:
```python
__getitem__
__iter__
keys
values()
items()
```
directly for the space rather than having to access its spaces attribute. 

However I don't know if this behavior is acceptable for a space to have.

**Comment by christopherhesse** [comment]
In my code it's been fine to access `.spaces` instead of trying to overload the `spaces.Dict` object, is there some reason this is better?

**Comment by adolfogonzalez3** [comment]
I think it would make it more convenient to use the Dict space. It would be a more natural way to interact with the space.
