### ISSUE TITLE
Running Classic Environment in Google Colab gives Attribute error

### ISSUE THREAD

**Issue by qm123** [openai/gym#1613]
I am trying to run MountainCar-v0 on google colab, when i try video recording of gym environment and displaying it using
```
 def wrap_env(env):

  env = Monitor(env, './video', force=True)
  return env`
```

It gives error on env.reset()

![github](https://user-images.githubusercontent.com/24230860/61596180-e5be6500-ac1d-11e9-9575-bfde94225bb9.png)

**Comment by christopherhesse** [comment]
This should already be fixed by this change: https://github.com/openai/gym/commit/f4d3c075e8486b90cbc5f16a8d71f091be269939
