### ISSUE TITLE
Why this is not a object velocity that relative to gripper?

### ISSUE THREAD

**Issue by YijiongLin** [openai/gym#1619]
https://github.com/openai/gym/blob/9dea81b48a2e1d8f7e7a81211c0f09f627ee61a9/gym/envs/robotics/fetch_env.py#L102

object_velp -= grip_velp

why not object_rel_velp = object_velp -grip_velp? Are these typos or any deep design thought?

**Comment by sritee** [comment]
The velocity exposed to the client is relative, which is a design choice. It works fine even if it's not relative probably, but might suffer a bit in performance. They probably didn't want to create a copy for a new variable.

**Comment by YijiongLin** [comment]
@sritee Thanks
