### ISSUE TITLE
Request: Support GPU-accelerated ALE port

### ISSUE THREAD

**Issue by kengz** [openai/gym#1622]
NVIDIA recently released a CUDA port of ALE. This accelerates the Atari environments using GPU. It will be nice to have this as part of gym, or at least an option to install it over the original ALE.
paper: https://arxiv.org/pdf/1907.08467.pdf
code: https://github.com/NVLABs/cule

**Comment by christopherhesse** [comment]
Seems pretty neat, it looks like it already has some gym environments in there: https://github.com/NVlabs/cule/blob/master/examples/utils/openai/envs.py

They seem to use the baselines VecEnv stuff.  If someone wanted to make a repackaged version of CuLE as a python package that uses the new gym VectorEnv setup, we should add it to the list of gym environments here: https://github.com/openai/gym/blob/master/docs/environments.md
