### ISSUE TITLE
FOREX Trading Env

### ISSUE THREAD

**Issue by AminHP** [openai/gym#1623]
Hello!
I was looking for a FOREX trading env implemented in `gym` for a long time. I've found many codes in Github that were mostly about Stocks trading. Although there were some envs for FOREX trading, they all inspired their idea from Stocks trading envs; as far as I checked.
Besides, the envs were very complicated and confusing. Some of them couldn't be run easily and you get bothered when you want to install their dependencies to run.
And after all, they are not quite trusty by the public. Everyone spends so much time to understand and run those codes and then create his own env for himself. So different algorithms on these envs can't compete with each other.
Sorry for the long Introduction :). Now I'm gonna get to the point.

Here I decided to implement a simple and specific env for FOREX trading after reading many of those existed codes for Stocks and FOREX trading. I also tried to use my env in `keras-rl` to test it and make sure that it works and can qualify to be used in public competitions. 
So now, I can create a pull request and share my codes to get through this if you're interested :)

It seems all those mentioned problems can be solved in this way for the community's sake.

**Comment by mg64ve** [comment]
Are you keen to share your code?

**Comment by AminHP** [comment]
Sure. I'm still working on it and In a few days, I'll make a pull request.

**Comment by christopherhesse** [comment]
Thanks for making this!  We're not adding new environments to the gym package itself though, see this guide for how to create new gym environments: https://github.com/openai/gym/blob/master/docs/creating-environments.md

Users can still use `gym.make` if they have your package installed.

Please do make a PR to add your environment to the list of environments here: https://github.com/openai/gym/blob/master/docs/environments.md

**Comment by AminHP** [comment]
Finally, I decided to create some environments to support not only FOREX but also other trading markets such as Stocks. Please read the documentation.

**Comment by christopherhesse** [comment]
Closed by PR
