### ISSUE TITLE
AttributeError: 'MjViewer' object has no attribute 'finish'

### ISSUE THREAD

**Issue by Gloriabhsfer** [openai/gym#1637]
Hi all,

I am new to reinforcement learning and I am trying to figure out the simulation example of 

- mujoco in OpenAI.
- My system is Ubuntu18.04
- Mujoco is 200
- mujoco-py                          2.0.2.4  
- gym                                0.10.1 
- tensorflow                         1.13.1  

I tried to run the example in OpenAI Gym offical document

> import gym
> env = gym.make('CartPole-v0')
> env.reset()
> for _ in range(1000):
>     env.render()
>     env.step(env.action_space.sample()) # take a random action
> env.close()

And it gave feedback like this:

> Episode finished after 32 timesteps
> Traceback (most recent call last):
>   File "test.py", line 13, in <module>
>     env.close()
>   File "/home/gloria/anaconda3/envs/openai/lib/python3.6/site-packages/gym/core.py", line 288, in close
>     return self.env.close()
>   File "/home/gloria/anaconda3/envs/openai/lib/python3.6/site-packages/gym/envs/mujoco/mujoco_env.py", line 115, in close
>     self.viewer.finish()
> AttributeError: 'MjViewer' object has no attribute 'finish'

And the simulator will flash for second and close. 
I am looking forward to anyone reply.

Thanks,
Gloria

**Comment by christopherhesse** [comment]
It looks like this was fixed a year ago, could you update to the newest version of gym?  Thanks!

**Comment by Gloriabhsfer** [comment]
> It looks like this was fixed a year ago, could you update to the newest version of gym? Thanks!

Sorry for reply late. But if I update the gym version, mujoco-py example will not work. And I see other people solve that problem by return old version of gym.

**Comment by christopherhesse** [comment]
What mujoco-py example?  We do not really support old versions of gym, just the latest ones.
