### ISSUE TITLE
done = True when ale.lives != 0

### ISSUE THREAD

**Issue by vfleon** [openai/gym#1638]
When I called the clone_full_state() and restore_full_state() for many times, the game will be over even there are still many lives left in the breakout game.

**Comment by christopherhesse** [comment]
Are you using a timelimit wrapper?

**Comment by vfleon** [comment]
Thanks for your reply!

I used env = gym.envs.make("BreakoutDeterministic-v4").

I am not sure if there is a time or step limitation. But it is quite
weird, *done
*becomes *True* erratically. It will end at only a few steps sometimes. The
action planning time indeed takes a bit long time for each step in my test.
So, I guess there might be a time limitation for running one episode in the
environment?

**Comment by csicher** [comment]
613-8

**Comment by christopherhesse** [comment]
Yeah you are using a TimeLimit wrapper:

```In [1]: import gym                                                                                                                                                      

In [2]: env = gym.envs.make("BreakoutDeterministic-v4")                                                                                                                 

In [3]: env                                                                                                                                                             
Out[3]: <TimeLimit<AtariEnv<BreakoutDeterministic-v4>>>
```

You should create the `AtariEnv` object directly instead of using `gym.make`.  In general gym environments (and wrappers such as `TimeLimit`) do not support save/restore, see https://github.com/openai/gym/issues/402 for more info
