### ISSUE TITLE
Build error by running "pip install -e .[all]" on OSX 10.11.5

### ISSUE THREAD

**Issue by sumethy** [openai/gym#164]
Running pip install -e .[all] produces something like:

Failed building wheel for pachi-py
  Running setup.py clean for pachi-py
Failed to build pachi-py

make is version 3.5.2
pip is version 8.1.2

The attached file is the full output
[gym install error.txt](https://github.com/openai/gym/files/304371/gym.install.error.txt)

**Comment by tlbtlbtlb** [comment]
It seems like it's trying to build binaries for OSX 10.5, which is incompatible with some recent libraries. Are you on a recent version of OSX? Do you have some global XCode setting requesting an older binary compatibility?

**Comment by sumethy** [comment]
I am on the latest OSX version: 10.11.5. I don't even have Xcode installed, just the command line tools, version 7.3.

**Comment by jietang** [comment]
Can you run `env | grep OSX_` and `env | grep PATH` and report the results?

**Comment by sumethy** [comment]
`env | grep OSX_` produces nothing
`env | grep PATH` produces
```
PATH=/Users/sumethy/miniconda2/bin:/Users/sumethy/torch/install/bin:/Library/Frameworks/Python.framework/Versions/2.7/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Library/TeX/texbin
CLASSPATH=:/Users/sumethy/algs4/algs4.jar
```

**Comment by qubey** [comment]
I suspect the warnings aren't the real issue - it seems like this is the final error that causes the overall failure:
```
    ld: targeted OS version does not support use of thread local variables in _fast_srandom for architecture x86_64
    clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I'm getting the same issue here.  It seems like this might have something to do with it? http://stackoverflow.com/questions/28094794/why-does-apple-clang-disallow-c11-thread-local-when-official-clang-supports (not too sure though)

**Comment by act65** [comment]
same issue here

**Comment by tlbtlbtlb** [comment]
For some reason, your system is trying to build for OSX 10.5 compatibility which doesn't have some features (like thread-local variables) required by pachi. OSX 10.5 is quite old (10.6 came out in 2009).

Perhaps you have a very old Python installation. Try `brew upgrade python`. 

Or maybe your XCode is out of date, it probably requires XCode 7.

If that doesn't work, could you provide the output of `python -v` and `gcc -v`?

**Comment by mthrok** [comment]
I had the same issue (`clang` try to build 10.5) when installing pachi-py from `openai/pachi-py` repo.

In my case, the following command solved it.

`MACOSX_DEPLOYMENT_TARGET=10.11 python setup.py install`

After installing pachi-py, gym installation succeeded.

**Comment by sumethy** [comment]
I think the problem is with Anaconda Python. I simply removed Anaconda, built a new Python environment with homebrew. Then running `pip install -e '.[all]'` just worked without any problem.

**Comment by du-phan** [comment]
Hi I have the same problem as you. I see that you have solved it by removing Anaconda, but I want to keep it, do you have any other suggestions ? Thank you!

**Comment by sumethy** [comment]
@du-phan I am not sure about this, but try making a symbolic link to Anaconda's python into /usr/local/bin just like the way Homebrew does with its python.

**Comment by lebo1990** [comment]
@du-phan Did you solve this problem still under Anaconda environment?

**Comment by adam-erickson** [comment]
The solution of @mthrok solves this for Anaconda.

**Comment by sumethy** [comment]
Just an update. Now I am on MacOS 10.12 with miniconda3 python, inside a conda virtual environment (python 3.5.2) and
```
export MACOSX_DEPLOYMENT_TARGET=10.12
pip install -e '.[all]'
```
works.

**Comment by Greenwicher** [comment]
@mthrok  Thanks a lot, it solved similar issue when I tried to build the openai/universe

**Comment by JulianNorton** [comment]
Still having this issue, I uninstalled anaconda and changed Deployment Target. No luck.

**Comment by weiliu620** [comment]
@sumethy @mthrok thanks very much. I'm on OS X 10.12 and Anaconda python 3.5. You trick of exporting environment variable works.

**Comment by chtano** [comment]
Hi
The command MACOSX_DEPLOYMENT_TARGET=10.11 pip install -e '.[all]'
works for me which also can be seen in #811.
Now I have problem with ppaquette-gym...

**Comment by Vanban-Wu** [comment]
Hi,

I used the command MACOSX_DEPLOYMENT_TARGET=10.12 then pip install -e '.[all]'
It works for me. But I run into the same problem as 'chtano' user on the ppaquette-gym... Any suggestion to his problem. By the way, I am a MacOS user running on Sierra version. Thanks much.

**Comment by Vanban-Wu** [comment]
The solution to ppaquette-gym-doom is by downgrading boost to 1.64 version for MacOS users until they fix the compatibility in newer version:

1. Downgrade the boost version to 1.64 by executing  "brew edit boost"  to edit boost's formula and replace it with the content of this file https://raw.githubusercontent.com/Homebrew/homebrew-core/3df9cdfc25f796ec8d3ffd0a0a12476cf6d413d5/Formula/boost.rb

then  "brew edit boost-python" to edit boost-python's formula and replace it using the content of this file https://raw.githubusercontent.com/Homebrew/homebrew-core/d22f78c56a1c7d8e711a407c2dae5fc42f4ae6c2/Formula/boost-python.rb

 2. brew unlink boost

3. brew unlink boost-python

4. brew install boost boost-python

5. pip install ppaquette-gym-doom
