### ISSUE TITLE
[gym numpy ray] Error pickling numpy random state

### ISSUE THREAD

**Issue by giuse** [openai/gym#1641]
I got a pretty nasty-to-track error using gym with Ray about pickling numpy.random. My money is on a problem with numpy serializing the recently overhauled random state, but 1. I am not competent to make such call (new to Python), 2. could not pinpoint the problem (ay Ray...), 3. was told straight to include you folks in the conversation [ https://github.com/numpy/numpy/issues/14210#issuecomment-519050123 ].

I am copying the original issue below for your convenience, but would appreciate if you could have a look at the discussion so far at https://github.com/numpy/numpy/issues/14210 .  
Thanks!

------------------

Still unsure if this problem is on numpy's side, but I tried downgrading to 1.14 (minimum numpy version for my dependencies) and verified it all works, no errors.
Given the recent changes on `random` I thought of bringing it up with you guys, particularly @charris @mattip (from https://github.com/numpy/numpy/pull/14207 )

I am sorry I could not isolate a simple reproducible example yet, my setup is inconveniently convoluted ATM. 

I am using [Ray](https://github.com/ray-project/ray) to parallelize calls to the [OpenAI Gym](https://github.com/openai/gym), this in turn implying a numpy random state is pickled for storage on its Redis-based object store. The un-pickling after Redis does not find the function [`__randomstate_ctor()`](https://github.com/numpy/numpy/blob/master/numpy/random/_pickle.py#L62).
I tried adding it to the [__init()__](https://github.com/numpy/numpy/blob/master/numpy/random/__init__.py) on the same fashion as (the suspiciously similar) [__RandomState_ctor()](https://github.com/numpy/numpy/blob/master/numpy/random/__init__.py#L194), but to no avail.

My hope is that someone with a better knowledge of this code will find something useful in the error.

### Reproducing code example:

Sorry too complex yet, unable to isolate it.

### Error message:

(Getting one of each from each worker, hundreds of them running async)

```
2019-08-06 14:18:59,907	ERROR worker.py:1714 -- Failed to unpickle the remote function '__main__.<lambda>' with function ID 84d9aba7e5b48a67d1b84d50bbf3f47e94bd0f4b. Traceback:
Traceback (most recent call last):
  File "/home/giuse/.local/share/virtualenvs/des-htl_CtVS/lib/python3.6/site-packages/ray/function_manager.py", line 424, in fetch_and_register_remote_function
    function = pickle.loads(serialized_function)
AttributeError: Can't get attribute '__randomstate_ctor' on <module 'numpy.random._pickle' from '/home/giuse/.local/share/virtualenvs/des-htl_CtVS/lib/python3.6/site-packages/numpy/random/_pickle.py'>

2019-08-06 14:18:59,861	ERROR worker.py:1654 -- Possible unhandled error from worker: ray_BlockWorker:run() (pid=28613, host=diufrm148)
  File "/home/giuse/des/block_worker.py", line 61, in run
    fitnesses = self.parallel_eval(population)
  File "/home/giuse/des/block_worker.py", line 91, in parallel_eval
    return ray.get([ ev.evaluate.remote(ind) for ev, ind in zip(self.fitness_evaluators, population) ])
ray.exceptions.RayTaskError: ray_FitnessEvaluator:evaluate() (pid=29830, host=diufrm148)
  File "pyarrow/serialization.pxi", line 461, in pyarrow.lib.deserialize
  File "pyarrow/serialization.pxi", line 424, in pyarrow.lib.deserialize_from
  File "pyarrow/serialization.pxi", line 275, in pyarrow.lib.SerializedPyObject.deserialize
  File "pyarrow/serialization.pxi", line 174, in pyarrow.lib.SerializationContext._deserialize_callback
AttributeError: Can't get attribute '__randomstate_ctor' on <module 'numpy.random._pickle' from '/home/giuse/.local/share/virtualenvs/des-htl_CtVS/lib/python3.6/site-packages/numpy/random/_pickle.py'>
```

### Numpy/Python version information:

```
1.17.0 3.6.8 (default, Jan 14 2019, 11:02:34) 
[GCC 8.0.1 20180414 (experimental) [trunk revision 259383]]
```

**Comment by christopherhesse** [comment]
I tried to pickle a gym space and it seemed to work fine.  It sounds like it could be some ray arrow serialization issue, you should try filing this issue on the ray repo: https://github.com/ray-project/ray

If you're able to make a short reproduction script and it looks like gym is to blame, please create a new issue.

Also as a workaround, you can try to avoid pickling anything that causes this error, some gym envs are unpickleable, so I avoid issues by just never pickling them.
