### ISSUE TITLE
VectorEnv should allow heterogeneous environments

### ISSUE THREAD

**Issue by hartikainen** [openai/gym#1644]
It would be great if `VectorEnv` allowed the use of heterogenous child environments. This would be useful for example when running the same environment with different arguments. The api could look something like:
```python
env_ids = ('Humanoid-v3', 'Humanoid-v3')
env_kwargs = ({'forward_reward_weight': 1.0}, {'forward_reward_weight': 2.0})
envs = gym.vector.make(env_ids=env_ids, env_kwargs=env_kwargs)
```

I'd be happy to contribute this at some point if it sounds like something that could be added to gym.

**Comment by tristandeleu** [comment]
I think `gym.vector.make` should only handle very simple cases, where all the environments are the same, and leave more complex use cases to `VectorEnv`. `VectorEnv` already allows heterogenous environments, as long as the observation spaces are the same (for batching). For example
```python
import gym
from gym.vector import AsyncVectorEnv

def make_env(env_name, **kwargs):
    def _make_env():
        env = gym.make(env_name, **kwargs)
        return env
    return _make_env

env_fns = [
    make_env('Humanoid-v3', forward_reward_weight=1.0),
    make_env('Humanoid-v3', forward_reward_weight=2.0)
]

envs = AsyncVectorEnv(env_fns)
```

**Comment by hartikainen** [comment]
Okay, yeah, I think that sounds like a good way to go. Thanks @tristandeleu!
