### ISSUE TITLE
humanoid action bound is not really 1

### ISSUE THREAD

**Issue by ZhaomingXie** [openai/gym#1645]
I notice that while the action bound for the humanoid environment is [-1, 1], the actual action bound is defined in the xml file, i.e, it is actually 0.4. Is it intentionally done to make the environment harder?

**Comment by ZhaomingXie** [comment]
Upon further inspection, I find that the action bound is already represented correctly. Though I am not sure where in the code this is done.

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
