### ISSUE TITLE
different friction coefficients for walker2d

### ISSUE THREAD

**Issue by ZhaomingXie** [openai/gym#1646]
I notice that the friction coefficients for the left and right foot of walker2d are different. I know it shouldn't matter for learning, just wondering if it is intentional or a bug.

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
