### ISSUE TITLE
Taxi environment doesn't match paper

### ISSUE THREAD

**Issue by kobotics** [openai/gym#1651]
![image](https://user-images.githubusercontent.com/11912669/63098742-89f7ab00-bf41-11e9-8d95-d4936dbd189a.png)

The map implemented in Taxi-v2 differs slightly from the one in the original paper (shown above). Namely, the paper example has a wall that prevents transitioning from (1,1) to (1,2), but the gym environment implemented doesn't. Any reason for that?

**Comment by christopherhesse** [comment]
It looks like an oversight.  The original `Taxi-v0` was even more different from the example in the paper, but the current one is quite close except for that wall.  Want to make a PR to fix it and change the name to `Taxi-v3`?

**Comment by kobotics** [comment]
Done. Please let me know if I did the PR correctly.

Thanks,

*Kim Baraka, *PhD candidate
Robotics Institute, *Carnegie Mellon University* (Pittsburgh, USA)
Group on Artificial Intelligence for People and Society (GAIPS), *INESC-ID
/ Instituto Superior Té**cnico* (Lisboa, Portugal)
kimbaraka.com

**Comment by christopherhesse** [comment]
Thanks!
