### ISSUE TITLE
RuntimeError: expand(torch.FloatTensor{[1, 1]}, size=[1]): the number of sizes provided (1) must be greater or equal to the number of dimensions in the tensor (2)

### ISSUE THREAD

**Issue by ilyesmrad** [openai/gym#1655]
model = ActorCritic(num_inputs, num_outputs, hidden_size).to(device) optimizer = optim.Adam(model.parameters(), lr=lr)

    for _ in range(num_steps):
        state = torch.FloatTensor(state).to(device)
        dist, value = model(state)

RuntimeError                              Traceback (most recent call last)
<ipython-input-243-69657a139f61> in <module>
     19         state = torch.FloatTensor(state).to(device)
     20         print(state)
---> 21         dist, value = model(state)
     22 
     23         action = dist.sample()

~\.conda\envs\reinforcement\lib\site-packages\torch\nn\modules\module.py in __call__(self, *input, **kwargs)
    487             result = self._slow_forward(*input, **kwargs)
    488         else:
--> 489             result = self.forward(*input, **kwargs)
    490         for hook in self._forward_hooks.values():
    491             hook_result = hook(self, input, result)

<ipython-input-237-5ecef3e21935> in forward(self, x)
     27         value = self.critic(x)
     28         mu    = self.actor(x)
---> 29         std   = self.log_std.exp().expand_as(mu)
     30         dist  = Normal(mu, std)
     31         return dist, value

RuntimeError: expand(torch.FloatTensor{[1, 1]}, size=[1]): the number of sizes provided (1) must be greater or equal to the number of dimensions in the tensor (2)

**Comment by christopherhesse** [comment]
`ActorCritic` isn't anything from the gym library, it looks like this is an issue with another library that you should file on that library.
