### ISSUE TITLE
Private Methods don't copy from Wrapper to subclasses of Wrapper (e.g., ObservationWrapper)

### ISSUE THREAD

**Issue by rkruegs123** [openai/gym#1656]
This would be a VERY easy change. The problem is the following:

Wrapper (in core.py) has __getattr__. When you subclass Wrapper to make things like ObservationWrapper, this overload of __getattr__ does not get copied over. You just have to copy that function definition (and similar ones) into subclasses of Wrapper.

**Comment by christopherhesse** [comment]
I wasn't able to reproduce this issue, do you have a short script that illustrates the problem?
