### ISSUE TITLE
Site: Algorithms Page 'Evaluation' click opens blank page

### ISSUE THREAD

**Issue by JKCooper2** [openai/gym#166]
On the [algorithms page](https://gym.openai.com/algorithms/alg_xFvqxWu0TSShCouaVW63hg) when I click on the evaluation part of `CartPole-v0  100.00 ± 17.35 episodes to solve (7 evaluations)` it loads a blank page with the url `javascript:$('#CartPole-v0-evaluations').show()` and displaying '[object Object]'

Using Firefox

**Comment by jietang** [comment]
Thanks for the report; I'm going to be spending significant time on the algorithms page this week and will work this in.

**Comment by christopherhesse** [comment]
Thanks for the feedback but the scoreboard isn't active anymore, so I am closing this issue.
