### ISSUE TITLE
Why is the reward function of Hopper not a function of the state and action only?

### ISSUE THREAD

**Issue by JulianoLagana** [openai/gym#1662]
Why is the reward in `Hopper-v3` computed [using the average velocity between two time-steps](https://github.com/openai/gym/blob/c33cfd8b2cc8cac6c346bc2182cd568ef33b8821/gym/envs/mujoco/hopper_v3.py#L97)? I believe it's better to simply use the velocity already present in the state (i.e. `s[5]`), otherwise we end up with a reward function which is not a function of the state of the agent (as it currently is computed, the reward is a function of the position of the agent, which is non-observable for agents).

I believe this might be a problem with other Mujoco environments as well, resulting in POMDPs where we could have them as MDPs instead.

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
