### ISSUE TITLE
Stuck after 400 episodes with MMC

### ISSUE THREAD

**Issue by DihBastos** [openai/gym#1665]
Hello guys,

When I try to run MMC algorithm in Ms. Pac-man (graph_manager),after 400 episodes, the training stucks. 

Initially, I was thinking that maybe the problem was hardware bottleneck, here my configs:

Intel Core i5-8600k 3.60GHz
32 GB RAM DDDR5 2400 MHz
NVIDIA 1070TI ASUS CERBERUS
SSD 120GB (SO)
HD 1750GB
Ubuntu 16.04
Python 3.7

Anyone can help me? The same occurs with another algorithms

Thanks =)

**Comment by christopherhesse** [comment]
I'm afraid this is not an issue with the gym library, so I'm going to close it.  If you're using a library for the training, you can try filing an issue on that particular library.

**Comment by DihBastos** [comment]
Oh my
I'm so sorry

I thought I was in another project = (

 Can u delete the issue? Please
