### ISSUE TITLE
env.close() not working as intended?

### ISSUE THREAD

**Issue by pkoppol** [openai/gym#1666]
Hello,

I recently installed mujoco_py (2.0.2.5) on an Ubuntu 18.04 system, and was playing around with the FetchReach environment when I noticed that env.close() was not properly closing the render window. 

Instead, the window would freeze and become unresponsive, causing me to force-quit and terminate my program early. I believe that adding:

```
if self.viewer is not None:
               glfw.destroy_window(self.viewer.window)
               self.viewer = None
```
will resolve this issue. 

As I'm writing this, I found a related issue (#1000) where someone encountered a similar problem and surfaced the same solution about a year ago. I'm wondering if there's a reason that this hasn't been addressed, or if it makes sense to go ahead with a pull request.

Thanks!

**Comment by christopherhesse** [comment]
I don't know of any reason, please provide a pull request if this change doesn't break anything else.

**Comment by christopherhesse** [comment]
From looking more closely at the PR, I think this is a bug in `mujoco-py`, so you should file the issue/PR there, sorry for the confusion!
