### ISSUE TITLE
custom environment doesn't have `make`

### ISSUE THREAD

**Issue by ThisIsIsaac** [openai/gym#1675]
When I run `test.py` of my [custom env](https://github.com/ThisIsIsaac/gym_cityflow), I get error:

```
AttributeError: module 'gym_cityflow' has no attribute 'make'
```

Funny thing is, this used to work on my past commits, but reverting my code to the commit that used to work also gives me the same error.

**Comment by psusarla95** [comment]
Hi @ThisIsIsaac , add `import gym` as well in your test.py before gym_cityflow. I am not sure, if this is the right way, but it solved the similar problem I was facing with my custom environment

**Comment by psusarla95** [comment]
Also, `gym_cityflow.make()` is incorrect. You added your custom environment to gym with
 `pip install -e .`  . So, now the way you make your custom environment is by `gym.make(custom_env_name)`

**Comment by ThisIsIsaac** [comment]
I have registered my environment like this in `gym_cityflow/__init__.py`:

```python
from gym.envs.registration import register

register(
    id='CityFlow-1x1-LowTraffic-v0', # use id to pass to gym.make(id)
    entry_point='gym_cityflow.envs:CityFlow_1x1_LowTraffic'
    # max_episode_steps =
    # reward_threshold =
)
```

When I try to instantiate it with `gym.make()` as follows:

```python
>>> import gym
>>> import gym_cityflow
>>> gym.make("gym_cityflow:CityFlow-1x1-LowTraffic-v0")
```

I get error:

```
Traceback (most recent call last):
  File "/home/isaac/gym/gym/envs/registration.py", line 132, in spec
    return self.env_specs[id]
KeyError: 'CityFlow-1x1-LowTraffic-v0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/isaac/gym/gym/envs/registration.py", line 156, in make
    return registry.make(id, **kwargs)
  File "/home/isaac/gym/gym/envs/registration.py", line 100, in make
    spec = self.spec(path)
  File "/home/isaac/gym/gym/envs/registration.py", line 142, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: CityFlow-1x1-LowTraffic-v0
```

**Comment by psusarla95** [comment]
You need to instantiate `gym.make()` as follows:

`>>> gym.make("CityFlow-1x1-LowTraffic-v0")`

'CityFlow-1x1-LowTraffic-v0' is your environment name. gym_cityflow is your custom gym folder. `gym_register` helps you in registering your custom environment class (CityFlow-1x1-LowTraffic-v0 in your case) into `gym` directly. No need to mention `gym_cityflow` inside your path because of that

**Comment by ThisIsIsaac** [comment]
Thanks for the clarification.

Unfortunately, I get the same error when I run:

```python
import gym
import gym_cityflow

env = gym.make('CityFlow-1x1-LowTraffic-v0')
```

```
gym.error.UnregisteredEnv: No registered env with id: CityFlow-1x1-LowTraffic-v0
```

**Comment by psusarla95** [comment]
Also, make sure the name of .py file defined in envs is same as that of defined class 'CityFlow_1x1_LowTraffic' (Rename cityflow_1x1.py to CityFlow_1x1_LowTraffic.py).

Then, update the entrypoint of `__init__.py` under `gym_cityflow` folder accordingly. In your case, `entry_point='gym_cityflow.envs:CityFlow_1x1_LowTraffic'`

I tried these changes on your code and it has resolved the above problem you have mentioned. Let me know here again, if you are still facing problem.

**Comment by ThisIsIsaac** [comment]
Following your suggestions, I have:

1. renamed file to `CityFlow_1x1_LowTraffic.py`

2. changed import in `init.py` under `gym_cityflow/gym_cityflow/envs/` accordingly

I am not sure how I should change `__init__.py` under `gym_cityflow/gym_cityflow`. It used to be:

```python
from gym.envs.registration import register

# source: https://github.com/openai/gym/blob/master/gym/envs/__init__.py

register(
    id='CityFlow-1x1-LowTraffic-v0', # use id to pass to gym.make(id)
    entry_point='gym_cityflow.envs:CityFlow_1x1_LowTraffic'
)
```

and doesn't seem like it requires any further change. How did you change it in your version to get it working?

With the above 2 changes, I still get the same error.

**Comment by ThisIsIsaac** [comment]
the bug is fixed and `gym.make` works. I have made a push and the [master](https://github.com/ThisIsIsaac/gym_cityflow) now should work.

However, I am not sure what fixed it. I don't think changing the name of the file had any effect since the [example](https://github.com/openai/gym/blob/master/docs/creating-environments.md) used by OpenAI had the file named differently from the class. 

If you have any insight please share with me. Else, I will close the issue.

**Comment by psusarla95** [comment]
Yes, you are correct. changing the name of the file is not compulsory. I have looked into OpenAI gym environment implementation, while I was making a custom environment as well. I couldn't find the reason back then and this keep the same name helped.

Now, after looking at your reasons, I tried using different `filename` and `class name` and now it works. I think, the mistake we made or overlooked at yesterday's issue was that of `entry_point='gym_cityflow.envs:**CityFlow_1x1_LowTraffic**'` in `gym_cityflow/__init__.py` . As far as I remember, during yesterday's the entrypoint written was `entry_point='gy_cityflow.envs:**cityflow_1x1**` where `cityflow_1x1.py` was the filename. Probably, that was the issue. Can you recall anything on these lines?

I think as long as you define the entry point as `entry_point='gym_cityflow.envs:**class name**'` and import accordingly the defined class in `gym_cityflow/envs/__init__.py` from the `gym_cityflow/envs/file_name.py`, the custom environment will be properly defined and should work.

**Comment by psusarla95** [comment]
> Following your suggestions, I have:
> 
> 1. renamed file to `CityFlow_1x1_LowTraffic.py`
> 2. changed import in `init.py` under `gym_cityflow/gym_cityflow/envs/` accordingly
> 
> I am not sure how I should change `__init__.py` under `gym_cityflow/gym_cityflow`. It used to be:
> 
> ```python
> from gym.envs.registration import register
> 
> # source: https://github.com/openai/gym/blob/master/gym/envs/__init__.py
> 
> register(
>     id='CityFlow-1x1-LowTraffic-v0', # use id to pass to gym.make(id)
>     entry_point='gym_cityflow.envs:CityFlow_1x1_LowTraffic'
> )
> ```
> 
> and doesn't seem like it requires any further change. How did you change it in your version to get it working?
> 
> With the above 2 changes, I still get the same error:
> 
> ```python
> import gym
> import gym_cityflow
> 
> gym.make('gym_cityflow:CityFlow-1x1-LowTraffic-v0')
> ```

Even I made the same changes in my version and it worked. Did you run `pip install -e .` after making these changes?

**Comment by ThisIsIsaac** [comment]
> As far as I remember, during yesterday's the entrypoint written was entry_point='gy_cityflow.envs:**cityflow_1x1** where cityflow_1x1.py was the filename. 

I took a look at [yesterday's `__init__.py`](https://github.com/ThisIsIsaac/gym_cityflow/blob/a0e35fac1c63d9c03a41a5c33660b16629acdf47/gym_cityflow/__init__.py#L7) and it seemed to be fine:

```python
entry_point='gym_cityflow.envs:CityFlow_1x1_LowTraffic'
```

where `CityFlow_1x1_LowTraffic` is the name of the `class`.

> Even I made the same changes in my version and it worked. Did you run pip install -e . after making these changes?

I have always installed with `pip install -e .`. I am not sure how often I re-typed `pip install -e .`, but I don't think it should be of issue since `-e` automatically installs it again when source code is changed, right?

**Comment by psusarla95** [comment]
> > As far as I remember, during yesterday's the entrypoint written was entry_point='gy_cityflow.envs:**cityflow_1x1** where cityflow_1x1.py was the filename.
> 
> I took a look at [yesterday's `__init__.py`](https://github.com/ThisIsIsaac/gym_cityflow/blob/a0e35fac1c63d9c03a41a5c33660b16629acdf47/gym_cityflow/__init__.py#L7) and it seemed to be fine:
> 
> ```python
> entry_point='gym_cityflow.envs:CityFlow_1x1_LowTraffic'
> ```
> 
> where `CityFlow_1x1_LowTraffic` is the name of the `class`.
> 

I see. In that case, even I am not sure now what was the mistake we overlooked yesterday. Something we have resolved for sure and that made it work. Anyways, now its more clear to what changes to be made inside `gym_cityflow/__init__.py' and `gym_cityflow/envs/__init__.py` to build in a custom environment.


> > Even I made the same changes in my version and it worked. Did you run pip install -e . after making these changes?
> 
> I have always installed with `pip install -e .`. I am not sure how often I re-typed `pip install -e .`, but I don't think it should be of issue since `-e` automatically installs it again when source code is changed, right?

Yes, you are correct but sometimes in my PyCharm IDE with python interpreter from anaconda virtual environment, use to not show the changes I made in source code, unless I run `pip install -e .` . It happened once or twice and I ended up running the command `pip install -e .` every time I make the change in source code, just to be sure of it. 

Anyways, in that case, even I am not sure how it resolved the problem but now that it got resolved, you may close the issue. Thanks for the help in making me understand the problems as well.

**Comment by ThisIsIsaac** [comment]
@psusarla95 Thanks so much for your help. It was a pleasure :)

**Comment by Muhsinka** [comment]
Check your enviroment, which enviroment did you install gym and open python from that enviroment.
if you are using jupyter open jupyter from anaconda promt.

**Comment by pgsudheesh** [comment]
I am trying to make a custom env in gym.

i got following error

gym.make('Env-v4')
Traceback (most recent call last):
  File "C:\Python\Python38\lib\site-packages\gym\envs\registration.py", line 118, in spec
    return self.env_specs[id]
KeyError: 'Env-v4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python\Python38\lib\site-packages\gym\envs\registration.py", line 142, in make
    return registry.make(id, **kwargs)
  File "C:\Python\Python38\lib\site-packages\gym\envs\registration.py", line 86, in make
    spec = self.spec(path)
  File "C:\Python\Python38\lib\site-packages\gym\envs\registration.py", line 128, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: Env-v4

init.py is 
from gym.envs.registration import  register
register(id='Env-v4',
    entry_point='envs.custom_env_dir:CustomEnv',
    tags={'wrapper_config.TimeLimit.max_episode_steps': 200},
    reward_threshold=8, # optimum = 8.46
)

next init.py is 
from envs.custom_env_dir.custom_env import CustomEnv

the custom_env.py file is

import gym
class CustomEnv(gym.Env):
    def __init__(self):
        print('Environment initialized')
    def step(self):
        print('Step successful!')
    def reset(self):
        print('Environment reset')

**Comment by ZZWang21** [comment]
the same error here, anyone has any ideas? @pgsudheesh  @ThisIsIsaac

**Comment by pseudo-rnd-thoughts** [comment]
You can output gyms registry which contains all of the registered environments, `gym.envs.registry.keys()`
If your environments name is not within the list. It means that you have not registered your environment correctly
