### ISSUE TITLE
OpenAI GYM Implementation in OMNeT++

### ISSUE THREAD

**Issue by shahrukhkasi** [openai/gym#1676]
I intend to use Q-learning (or any other reinforcement learning variant) to control the congestion window size of TCP in OMNeT++. I know of OpenAI GYM library for NS-3 that provides an interface between NS-3 and GYM library to implement reinforcement learning algorithms.

Is there anything similar to that NS3GYM library in OMNeT++ as well? If there is none, what is the best way to use GYM library in OMNeT++?

**Comment by christopherhesse** [comment]
Not that I'm aware of.  As you mentioned, sounds like someone would need to do what the authors of https://arxiv.org/abs/1810.03943 did but for OMNeT++.
