### ISSUE TITLE
Frame Normalization in AtariPreProcessing

### ISSUE THREAD

**Issue by koulanurag** [openai/gym#1679]
Hi,
I guess, it would be useful to include [frame normalization](https://github.com/openai/baselines/blob/master/baselines/common/atari_wrappers.py#L219) as well in the [AtariPreProcessing](https://github.com/openai/gym/blob/master/gym/wrappers/atari_preprocessing.py).

This is also included optionally in [wrap_deepmind](https://github.com/openai/baselines/blob/master/baselines/common/atari_wrappers.py#L275) method

**Comment by koulanurag** [comment]
@zuoxingdong @pzhokhov. This might be relevant to you.

**Comment by christopherhesse** [comment]
Looks like this was merged https://github.com/openai/gym/pull/1680
