### ISSUE TITLE
How to get the optimal policy of the gym env?

### ISSUE THREAD

**Issue by WenyuHuang** [openai/gym#1681]
I want to do some experiments on gym and i want to know the rewards of the optimal policy. However, how can i get the optimal policy? Maybe i should use ppo to train but ppo doesn't guanrantee returns a optimal policy.

**Comment by christopherhesse** [comment]
I'm afraid this is more of an algorithmic question and not really covered by the gym library :/

**Comment by christopherhesse** [comment]
If you have a simple environment, especially one where you know the transition probabilities, like maybe `Taxi-v3`.
