### ISSUE TITLE
cartpole system: reward is always 1

### ISSUE THREAD

**Issue by yerzhik** [openai/gym#1682]
I have a question, shouldn't the reward depend on how good the action was?
correct me if I'm wrong. What I see in the code is that always it gives for any action reward equal to 1.0.

**Comment by JNC96** [comment]
I believe it rewards 1.0 for every step that the environment doesn't end, and accumulates reward depending on how long it doesn't fail the current episode.

As per the [wiki](https://github.com/openai/gym/wiki/CartPole-v0):

### Episode Termination
- Pole Angle is more than ±12°
- Cart Position is more than ±2.4 (center of the cart reaches the edge of the display)
- Episode length is greater than 200

### Solved Requirements
- Considered solved when the average reward is greater than or equal to 195.0 over 100 consecutive trials.

So the reward here is basically amount of steps that the episode runs for, and rewarding that fact.

**Comment by yerzhik** [comment]
Thank you! Now I get it. Should have read the wiki in the first place
