### ISSUE TITLE
Can I randomise the scenario played in the OpenAI Gym Atari environments?

### ISSUE THREAD

**Issue by dimitar-hristov** [openai/gym#1685]
I am looking at the Seaquest Atari game in OpenAI Gym and I have the following code snippet:
```
import gym
import time
import random

env = gym.make('Seaquest-v4')

for i_episode in range(10):
    seed = (int)(time.time())    
    random.seed(seed)
    env.seed(seed)
    observation = env.reset()
    for t in range(800):
        env.render()
        time.sleep(0.01)
        action = 0
        observation, reward, done, info = env.step(action)
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
env.close()
```
The code above renders 10 games, however, even though I reset the seed every time to be unique, I still get the same scenario of the game. As a result the agent is trained on the same scenario. Could someone suggest a way to fix this? I am just trying to find a way to make the Atari emulator to produce different scenarios of the game.

**Comment by christopherhesse** [comment]
In general no, atari games are entirely deterministic.

ALE supports different difficulty modes which are like a small number of unique scenarios.  Your other options are: add action noise (like sticky frame skip from this paper: https://arxiv.org/pdf/1804.03720.pdf), or collect a set of starting states and restore to a random state on each reset (this isn't supported by all gym environments, but ALE happens to have this feature).  Collecting a set of starting state can be done by playing the game a bunch or having the agent play the game a bunch, though in the second case your game states might not be very diverse.
