### ISSUE TITLE
bug with gym 

### ISSUE THREAD

**Issue by WenyuHuang** [openai/gym#1686]
In the first case, i rollout some trajectories directly.
In the the second case, i reset some initial states which are the same as those in the first case, then i rollout trajectories from those states  and i get other trajectories. But it's strange the trajs in these two cases are not the same. The policy to generate the trajs are the same and i use deterministic policy. The only difference is that in the second case, i first generate the initial states but i make sure the initial states are the same as those in the first case. Why does this happen?

**Comment by briantimar** [comment]
Do have a code example? (in particular, for the policy, and the state reset)

**Comment by WenyuHuang** [comment]
> Do have a code example? (in particular, for the policy, and the state reset)

Thanks for replying. I have found the reason of the bug. Because in the second case, i didn't reset the state of the mujocoEnv

**Comment by christopherhesse** [comment]
Glad you figured it out!
