### ISSUE TITLE
pyglet >=1.4 support 

### ISSUE THREAD

**Issue by pzhokhov** [openai/gym#1689]
rendering of classic_control environments depends on pyglet, and pyglet image data api has changed a bit between versions 1.3 and 1.4.

**Comment by MaKaNu** [comment]
Does this relate to Images? If I use rendering.Image the Image is loaded correctly but not the colors. The image stays black.

**Comment by pzhokhov** [comment]
No, I think pyglet either works correctly or throws an exception at the call time

**Comment by pzhokhov** [comment]
https://github.com/openai/gym/pull/1771

**Comment by floringogianu** [comment]
@MaKaNu I am experiencing this exact issue, Image is loaded, but black (alpha channel is fine). Is this related to pyglet >=1.4?
