### ISSUE TITLE
AttributeError: module 'gym' has no attribute 'make'

### ISSUE THREAD

**Issue by gatij10** [openai/gym#1693]
i installed the gym module but i still get this error

**Comment by christopherhesse** [comment]
I think this is often due to installing to a different copy of python than the one you are doing the import from.  Make sure your `pip` and `python` packages match up and that `gym` appears in `site-packages` for the `python` that you are using.

**Comment by christopherhesse** [comment]
Did this fix the issue for you?

**Comment by gatij10** [comment]
@christopherhesse  i m still getting the same error.

**Comment by christopherhesse** [comment]
Could you reinstall python and then reinstall gym using the new python?  If you still get this error please paste the error here.

**Comment by bronxbear** [comment]
Fixed it! Well kind of, I ran directly through the terminal window (not the imbedded one in my IDE) and it ran. I was never able to get it to run straight through the IDE (PyCharm). ¯\_(ツ)_/¯
