### ISSUE TITLE
Defender-ram-v0 doesn't initialize

### ISSUE THREAD

**Issue by jacekplocharczyk** [openai/gym#1698]
Hi,
could you check why `Defender-ram-v0` cannot initialize the environment?

I've tested it in the jupyter online https://jupyter.org/try - jupyter lab.
```Python
!pip install gym[atari]

import gym
env = gym.make('DemonAttack-ram-v0') # works
print(env)
env = gym.make('Defender-ram-v0') # doesn't work (it hangs)
print(env)
```

Edit.  
I've tested all environments in my docker container and all versions of the `Defender-*` doesn't work.

**Comment by christopherhesse** [comment]
I was able to reproduce this on colaboratory, but not on a normal linux machine.  This could be a bug in https://github.com/mgbellemare/Arcade-Learning-Environment or else a bug in how colab/jupyter handles something.

Can you try running this directly on a linux machine without docker?

**Comment by jacekplocharczyk** [comment]
Unfortunately I can't recreate the whole docker setup (there are a lot of CUDA related stuff and I don't want to mess with the NVIDIA drivers).

If that helps here is the [Dockerfile](https://github.com/jacekplocharczyk/jupyter-lab-server/blob/master/Dockerfile).

**Comment by christopherhesse** [comment]
This looks to be an issue with the defender rom, the following Dockerfile seems to work for me:

```
FROM continuumio/miniconda:4.7.12
RUN conda install python==3.7.3
RUN pip install gym[atari]
RUN apt-get update && apt-get install -y procps
RUN pip install py-spy
RUN python -c "import gym; env = gym.make('DemonAttack-ram-v0'); print(env.reset().shape)"
RUN md5sum /opt/conda/lib/python3.7/site-packages/atari_py/atari_roms/defender.bin
ADD defender.bin /opt/conda/lib/python3.7/site-packages/atari_py/atari_roms/defender.bin
RUN md5sum /opt/conda/lib/python3.7/site-packages/atari_py/atari_roms/defender.bin
RUN python -c "import gym; env = gym.make('Defender-ram-v0'); print(env.reset().shape)"
```

The newest version of atari-py doesn't have this issue because it doesn't include the bad rom (https://github.com/openai/atari-py#roms).  Your ROM md5 should match the one in this file: https://github.com/mgbellemare/Arcade-Learning-Environment/blob/master/md5.txt

We should upgrade atari-py to the new ale-py when that is available and it should fix this issue in general: https://github.com/mgbellemare/Arcade-Learning-Environment/pull/272

**Comment by gitanshu** [comment]
Bump! 
I still see the same issue, can reliably reproduce on ubuntu 18.04 on local, and in docker on CI, even with latest release of gym.
It works fine though if I downgrade `atari-py` to latest `0.1.x`.

**Comment by christopherhesse** [comment]
I think the new version of ale-py is almost ready, and @JesseFarebro was considering upgrading the version gym uses, but I haven't heard about the status of that recently.

**Comment by JesseFarebro** [comment]
I am blocked on a couple of things right now but I'll push to have this completed in the next couple of weeks.
