### ISSUE TITLE
Docker is available?

### ISSUE THREAD

**Issue by andrewssobral** [openai/gym#17]

**Comment by gdb** [comment]
There's a Dockerfile in the repo, which you can use to build your own image! We may publish an official image at some point, once we've decided what it should be exactly.

**Comment by andrewssobral** [comment]
Thank you @gdb

**Comment by sych74** [comment]
@gdb, it will be great to have an official OpenAI Docker image. Is there any blocker for that? Please let me know if I can help.

**Comment by gdb** [comment]
No particular blocker except for just doing it and making sure we're happy maintaining the setup going forward. We're working on a larger overhaul of a few things, and probably in early December will have an official story here!

**Comment by breandan** [comment]
Looks like there was [some images](https://hub.docker.com/u/openai/) published, but they haven't been updated in over two years...
