### ISSUE TITLE
I can't build mujoco-py

### ISSUE THREAD

**Issue by hyc6668378** [openai/gym#1701]
I try to install mujoco-py in pip-environment.

```
(PY3_6) baxter@baxter:~$ python --version
Python 3.6.8
```

I used to have no problem with `mujoco-py`, but it suddenly doesn't work today.
The error is bellow:
```
(PY3_6) baxter@baxter:/usr/lib/x86_64-linux-gnu$ pip3 install -U 'mujoco-py<2.1,>=2.0' --no-cache
Collecting mujoco-py<2.1,>=2.0
  Downloading https://files.pythonhosted.org/packages/31/85/57a2a6ed8356100f2eff1678976187dff9ebc1d059af4664ada06f4bb424/mujoco-py-2.0.2.5.tar.gz (769kB)
     |████████████████████████████████| 778kB 6.8MB/s 
Requirement already satisfied, skipping upgrade: glfw>=1.4.0 in /home/baxter/.virtualenvs/PY3_6/lib/python3.6/site-packages (from mujoco-py<2.1,>=2.0) (1.8.3)
Requirement already satisfied, skipping upgrade: numpy>=1.11 in /home/baxter/.virtualenvs/PY3_6/lib/python3.6/site-packages (from mujoco-py<2.1,>=2.0) (1.17.2)
Requirement already satisfied, skipping upgrade: Cython>=0.27.2 in /home/baxter/.virtualenvs/PY3_6/lib/python3.6/site-packages (from mujoco-py<2.1,>=2.0) (0.29.13)
Requirement already satisfied, skipping upgrade: imageio>=2.1.2 in /home/baxter/.virtualenvs/PY3_6/lib/python3.6/site-packages (from mujoco-py<2.1,>=2.0) (2.6.0)
Requirement already satisfied, skipping upgrade: cffi>=1.10 in /home/baxter/.virtualenvs/PY3_6/lib/python3.6/site-packages (from mujoco-py<2.1,>=2.0) (1.12.3)
Requirement already satisfied, skipping upgrade: lockfile>=0.12.2 in /home/baxter/.virtualenvs/PY3_6/lib/python3.6/site-packages (from mujoco-py<2.1,>=2.0) (0.12.2)
Requirement already satisfied, skipping upgrade: pillow in /home/baxter/.virtualenvs/PY3_6/lib/python3.6/site-packages (from imageio>=2.1.2->mujoco-py<2.1,>=2.0) (6.2.0)
Requirement already satisfied, skipping upgrade: pycparser in /home/baxter/.virtualenvs/PY3_6/lib/python3.6/site-packages (from cffi>=1.10->mujoco-py<2.1,>=2.0) (2.19)
Building wheels for collected packages: mujoco-py
  Building wheel for mujoco-py (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/baxter/.virtualenvs/PY3_6/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qfl5mw2t/mujoco-py/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qfl5mw2t/mujoco-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-bvbppxt1 --python-tag cp36
       cwd: /tmp/pip-install-qfl5mw2t/mujoco-py/
  Complete output (22 lines):
  running bdist_wheel
  running build
  Removing old mujoco_py cext /tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/generated/cymj_2.0.2.5_36_linuxcpuextensionbuilder_36.so
  Compiling /tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/cymj.pyx because it changed.
  [1/1] Cythonizing /tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/cymj.pyx
  running build_ext
  building 'mujoco_py.cymj' extension
  creating /tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder
  creating /tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6
  creating /tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/tmp
  creating /tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/tmp/pip-install-qfl5mw2t
  creating /tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/tmp/pip-install-qfl5mw2t/mujoco-py
  creating /tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py
  creating /tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/gl
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Imujoco_py -I/tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py -I/home/baxter/.mujoco/mujoco200/include -I/home/baxter/.virtualenvs/PY3_6/lib/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -I/home/baxter/.virtualenvs/PY3_6/include/python3.6m -c /tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/cymj.c -o /tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/cymj.o -fopenmp -w
  x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Imujoco_py -I/tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py -I/home/baxter/.mujoco/mujoco200/include -I/home/baxter/.virtualenvs/PY3_6/lib/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -I/home/baxter/.virtualenvs/PY3_6/include/python3.6m -c /tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/gl/osmesashim.c -o /tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/gl/osmesashim.o -fopenmp -w
  creating /tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/lib.linux-x86_64-3.6
  creating /tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/lib.linux-x86_64-3.6/mujoco_py
  x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 /tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/cymj.o /tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/gl/osmesashim.o -L/home/baxter/.mujoco/mujoco200/bin -Wl,--enable-new-dtags,-R/home/baxter/.mujoco/mujoco200/bin -lmujoco200 -lglewosmesa -lOSMesa -lGL -o /tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/lib.linux-x86_64-3.6/mujoco_py/cymj.cpython-36m-x86_64-linux-gnu.so -fopenmp
  /usr/bin/ld: cannot find -lGL
  collect2: error: ld returned 1 exit status
  error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for mujoco-py
  Running setup.py clean for mujoco-py
Failed to build mujoco-py
Installing collected packages: mujoco-py
  Running setup.py install for mujoco-py ... error
    ERROR: Command errored out with exit status 1:
     command: /home/baxter/.virtualenvs/PY3_6/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qfl5mw2t/mujoco-py/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qfl5mw2t/mujoco-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-wqflp_sy/install-record.txt --single-version-externally-managed --compile --install-headers /home/baxter/.virtualenvs/PY3_6/include/site/python3.6/mujoco-py
         cwd: /tmp/pip-install-qfl5mw2t/mujoco-py/
    Complete output (11 lines):
    running install
    running build
    Removing old mujoco_py cext /tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/generated/cymj_2.0.2.5_36_linuxcpuextensionbuilder_36.so
    running build_ext
    building 'mujoco_py.cymj' extension
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Imujoco_py -I/tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py -I/home/baxter/.mujoco/mujoco200/include -I/home/baxter/.virtualenvs/PY3_6/lib/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -I/home/baxter/.virtualenvs/PY3_6/include/python3.6m -c /tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/cymj.c -o /tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/cymj.o -fopenmp -w
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Imujoco_py -I/tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py -I/home/baxter/.mujoco/mujoco200/include -I/home/baxter/.virtualenvs/PY3_6/lib/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -I/home/baxter/.virtualenvs/PY3_6/include/python3.6m -c /tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/gl/osmesashim.c -o /tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/gl/osmesashim.o -fopenmp -w
    x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 /tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/cymj.o /tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/gl/osmesashim.o -L/home/baxter/.mujoco/mujoco200/bin -Wl,--enable-new-dtags,-R/home/baxter/.mujoco/mujoco200/bin -lmujoco200 -lglewosmesa -lOSMesa -lGL -o /tmp/pip-install-qfl5mw2t/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/lib.linux-x86_64-3.6/mujoco_py/cymj.cpython-36m-x86_64-linux-gnu.so -fopenmp
    /usr/bin/ld: cannot find -lGL
    collect2: error: ld returned 1 exit status
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/baxter/.virtualenvs/PY3_6/bin/python3.6 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-qfl5mw2t/mujoco-py/setup.py'"'"'; __file__='"'"'/tmp/pip-install-qfl5mw2t/mujoco-py/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-wqflp_sy/install-record.txt --single-version-externally-managed --compile --install-headers /home/baxter/.virtualenvs/PY3_6/include/site/python3.6/mujoco-py Check the logs for full command output.
```

**Comment by hyc6668378** [comment]
I can install from source. `python setup.py install`
but when I import mujoco_py.
The error is bellow:
`(PY3_6) baxter@baxter:~/Documents/mujoco-py$ python 
Python 3.6.8 (default, May  7 2019, 14:58:50) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mujoco_py
running build_ext
building 'mujoco_py.cymj' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Imujoco_py -I/home/baxter/Documents/mujoco-py/mujoco_py -I/home/baxter/.mujoco/mujoco200/include -I/home/baxter/.virtualenvs/PY3_6/lib/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -I/home/baxter/.virtualenvs/PY3_6/include/python3.6m -c /home/baxter/Documents/mujoco-py/mujoco_py/cymj.c -o /home/baxter/Documents/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/home/baxter/Documents/mujoco-py/mujoco_py/cymj.o -fopenmp -w
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Imujoco_py -I/home/baxter/Documents/mujoco-py/mujoco_py -I/home/baxter/.mujoco/mujoco200/include -I/home/baxter/.virtualenvs/PY3_6/lib/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -I/home/baxter/.virtualenvs/PY3_6/include/python3.6m -c /home/baxter/Documents/mujoco-py/mujoco_py/gl/osmesashim.c -o /home/baxter/Documents/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/home/baxter/Documents/mujoco-py/mujoco_py/gl/osmesashim.o -fopenmp -w
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 /home/baxter/Documents/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/home/baxter/Documents/mujoco-py/mujoco_py/cymj.o /home/baxter/Documents/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/home/baxter/Documents/mujoco-py/mujoco_py/gl/osmesashim.o -L/home/baxter/.mujoco/mujoco200/bin -Wl,--enable-new-dtags,-R/home/baxter/.mujoco/mujoco200/bin -lmujoco200 -lglewosmesa -lOSMesa -lGL -o /home/baxter/Documents/mujoco-py/mujoco_py/generated/_pyxbld_2.0.2.5_36_linuxcpuextensionbuilder/lib.linux-x86_64-3.6/mujoco_py/cymj.cpython-36m-x86_64-linux-gnu.so -fopenmp
/usr/bin/ld: cannot find -lGL
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "/usr/lib/python3.6/distutils/unixccompiler.py", line 207, in link
    self.spawn(linker + ld_args)
  File "/usr/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/baxter/Documents/mujoco-py/mujoco_py/__init__.py", line 3, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/home/baxter/Documents/mujoco-py/mujoco_py/builder.py", line 507, in <module>
    cymj = load_cython_ext(mujoco_path)
  File "/home/baxter/Documents/mujoco-py/mujoco_py/builder.py", line 105, in load_cython_ext
    cext_so_path = builder.build()
  File "/home/baxter/Documents/mujoco-py/mujoco_py/builder.py", line 220, in build
    built_so_file_path = self._build_impl()
  File "/home/baxter/Documents/mujoco-py/mujoco_py/builder.py", line 272, in _build_impl
    so_file_path = super()._build_impl()
  File "/home/baxter/Documents/mujoco-py/mujoco_py/builder.py", line 243, in _build_impl
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/baxter/.virtualenvs/PY3_6/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/home/baxter/Documents/mujoco-py/mujoco_py/builder.py", line 143, in build_extensions
    build_ext.build_extensions(self)
  File "/home/baxter/.virtualenvs/PY3_6/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 194, in build_extensions
    self.build_extension(ext)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 558, in build_extension
    target_lang=language)
  File "/usr/lib/python3.6/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/usr/lib/python3.6/distutils/unixccompiler.py", line 209, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
`

**Comment by christopherhesse** [comment]
I'm afraid this looks like an error with mujoco, could you file the bug on the mujoco repo at https://github.com/openai/mujoco-py?  Thanks!

**Comment by shiyujin0** [comment]
@christopherhesse @hyc6668378 I have the exactly same issue. Did you solve it? I'm trying to install mujocopy, when I import mujoco_py, I got this

>>> import mujoco_py
running build_ext
building 'mujoco_py.cymj' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I.local/lib/python3.6/site-packages/mujoco_py -I/homes/sjin/.local/lib/python3.6/site-packages/mujoco_py -I/homes/sjin/.mujoco/mujoco200/include -I/homes/sjin/.local/lib/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -c /homes/sjin/.local/lib/python3.6/site-packages/mujoco_py/cymj.c -o /homes/sjin/.local/lib/python3.6/site-packages/mujoco_py/generated/_pyxbld_2.0.2.10_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/homes/sjin/.local/lib/python3.6/site-packages/mujoco_py/cymj.o -fopenmp -w
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I.local/lib/python3.6/site-packages/mujoco_py -I/homes/sjin/.local/lib/python3.6/site-packages/mujoco_py -I/homes/sjin/.mujoco/mujoco200/include -I/homes/sjin/.local/lib/python3.6/site-packages/numpy/core/include -I/usr/include/python3.6m -c /homes/sjin/.local/lib/python3.6/site-packages/mujoco_py/gl/osmesashim.c -o /homes/sjin/.local/lib/python3.6/site-packages/mujoco_py/generated/_pyxbld_2.0.2.10_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/homes/sjin/.local/lib/python3.6/site-packages/mujoco_py/gl/osmesashim.o -fopenmp -w
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 /homes/sjin/.local/lib/python3.6/site-packages/mujoco_py/generated/_pyxbld_2.0.2.10_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/homes/sjin/.local/lib/python3.6/site-packages/mujoco_py/cymj.o /homes/sjin/.local/lib/python3.6/site-packages/mujoco_py/generated/_pyxbld_2.0.2.10_36_linuxcpuextensionbuilder/temp.linux-x86_64-3.6/homes/sjin/.local/lib/python3.6/site-packages/mujoco_py/gl/osmesashim.o -L/homes/sjin/.mujoco/mujoco200/bin -Wl,--enable-new-dtags,-R/homes/sjin/.mujoco/mujoco200/bin -lmujoco200 -lglewosmesa -lOSMesa -lGL -o /homes/sjin/.local/lib/python3.6/site-packages/mujoco_py/generated/_pyxbld_2.0.2.10_36_linuxcpuextensionbuilder/lib.linux-x86_64-3.6/mujoco_py/cymj.cpython-36m-x86_64-linux-gnu.so -fopenmp
/usr/bin/ld: cannot find -lGL
collect2: error: ld returned 1 exit status
Traceback (most recent call last):
  File "/usr/lib/python3.6/distutils/unixccompiler.py", line 207, in link
    self.spawn(linker + ld_args)
  File "/usr/lib/python3.6/distutils/ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "/usr/lib/python3.6/distutils/spawn.py", line 36, in spawn
    _spawn_posix(cmd, search_path, dry_run=dry_run)
  File "/usr/lib/python3.6/distutils/spawn.py", line 159, in _spawn_posix
    % (cmd, exit_status))
distutils.errors.DistutilsExecError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/homes/sjin/.local/lib/python3.6/site-packages/mujoco_py/__init__.py", line 3, in <module>
    from mujoco_py.builder import cymj, ignore_mujoco_warnings, functions, MujocoException
  File "/homes/sjin/.local/lib/python3.6/site-packages/mujoco_py/builder.py", line 510, in <module>
    cymj = load_cython_ext(mujoco_path)
  File "/homes/sjin/.local/lib/python3.6/site-packages/mujoco_py/builder.py", line 105, in load_cython_ext
    cext_so_path = builder.build()
  File "/homes/sjin/.local/lib/python3.6/site-packages/mujoco_py/builder.py", line 221, in build
    built_so_file_path = self._build_impl()
  File "/homes/sjin/.local/lib/python3.6/site-packages/mujoco_py/builder.py", line 273, in _build_impl
    so_file_path = super()._build_impl()
  File "/homes/sjin/.local/lib/python3.6/site-packages/mujoco_py/builder.py", line 244, in _build_impl
    dist.run_commands()
  File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/homes/sjin/.local/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/homes/sjin/.local/lib/python3.6/site-packages/mujoco_py/builder.py", line 144, in build_extensions
    build_ext.build_extensions(self)
  File "/homes/sjin/.local/lib/python3.6/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "/usr/lib/python3.6/distutils/command/build_ext.py", line 558, in build_extension
    target_lang=language)
  File "/usr/lib/python3.6/distutils/ccompiler.py", line 717, in link_shared_object
    extra_preargs, extra_postargs, build_temp, target_lang)
  File "/usr/lib/python3.6/distutils/unixccompiler.py", line 209, in link
    raise LinkError(msg)
distutils.errors.LinkError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by shiyujin0** [comment]
I solved it by sudo apt install libgl1-mesa-dev
https://github.com/openai/mujoco-py/issues/341
