### ISSUE TITLE
[Feature request] viewer camera z-coord (rendering scale)

### ISSUE THREAD

**Issue by dizcza** [openai/gym#1702]
I'd like to have the ability to zoom out `rendering.Viewer`.
For example, I'm creating a new env with the aim to simulate real robot size and surrounding obstacles in mm (1 pixel == 1 mm). In this scenario, I need to create 2000 x 2000 window size which is, of course, memory and time consuming to render. An alternative would be manually scaling all obstacles, positions and robot sizes with some predefined constant - this is inconvenient.
**Could you please add `z`- coordinate to `rendering.Viewer` camera to be rendered later on with pyglet (or any other option to scale the rendering frame)?**

**Comment by christopherhesse** [comment]
Is this about the gym renderer or the mujoco py renderer?

**Comment by dizcza** [comment]
This is about the gym render only. I don't use mujoco.

**Comment by christopherhesse** [comment]
I don't think it's meant to be a fully featured renderer, could you create your own based on the gym renderer that supports this?

**Comment by dizcza** [comment]
> could you create your own based on the gym renderer that supports this?

I don't know how to do this - it's not one-hour-task for sure.
