### ISSUE TITLE
Random seed for scipy.stats

### ISSUE THREAD

**Issue by lr91-089** [openai/gym#1703]
Dear all,

the standard seeding function is:
```
    def seed(self, seed=None):
        self.np_random, seed = seeding.np_random(seed)
        return [seed]
```

with calling random numbers with `self.np_random`.
I created a custom environment and needed a truncated normal distribution. Is there any option to call the random seed easily with `self.np_random` on this truncated normal distribution?

**Comment by christopherhesse** [comment]
`np_random` is a `np.random.RandomState`, can you use that to create or seed your distribution?
