### ISSUE TITLE
Consistency in env.state / env.s / env.observation

### ISSUE THREAD

**Issue by sgraaf** [openai/gym#1707]
Looking at the implementations of the various envs available in gym, I find it surprising that there is no consistency in terms of keeping track of the current state of the environment. Some states in `toy_text` use `self.state`, some use `self.s` and others `self.observation`, for example.

When faced with a situation where one has to manipulate the state of the environment directly (bypassing `env.reset()`), some consistency on this front would help a great deal!

**Comment by christopherhesse** [comment]
I'm afraid that environment state is only covered by the gym api when it is returned as the observation from `step()`.  For partially-observed environments, the gym api doesn't specify how the state should be exposed, so it's up to the individual environment :/

The existing gym env API is already fairly large, so I think we're unlikely to add a way to access underlying env state, sorry!
