### ISSUE TITLE
Rewards in BreakoutDeterministic-v4

### ISSUE THREAD

**Issue by devloper13** [openai/gym#1709]
Can I know what are the rewards in BreakoutDeterministic-v4? I don't get a reward of -1 when the game is over or when I lose life.

**Comment by christopherhesse** [comment]
Those are determined by https://github.com/mgbellemare/Arcade-Learning-Environment

It looks like the reward is the change in score: https://github.com/mgbellemare/Arcade-Learning-Environment/blob/master/src/games/supported/Breakout.cpp#L54

So no penalty for losing a life.
