### ISSUE TITLE
[Probable bug] Contact forces in MuJoCo 2.0 are absent.

### ISSUE THREAD

**Issue by brickerino** [openai/gym#1711]
Hello.
It looks like several environments (at least Ant and Humanoid) lack contact forces. The corresponding state part filled with zeroes, and corresponding reward part is absent too.

A environment (v2 and v3) uses the cfrc_ext field of PyMjData which is a proxy to the cfrc_ext field of MuJoCo C structure _mjData . But the changelog to MuJoCo 2.0 contains the following line:

>The function mj_rnePostConstraint is no longer called by default. Instead, it is called only when the model contains force-related sensors which need the results of this function. The user can still call it directly in order to compute the mjData fields cacc, cfrc_ext, cfrc_int if desired.

Please look into it, is it a bug or was this omission intentional?

**Comment by christopherhesse** [comment]
Closing in favor of https://github.com/openai/gym/issues/1541
