### ISSUE TITLE
FetchReach-v1 changes target position from step 200 to step 220? Why?

### ISSUE THREAD

**Issue by RyanRizzo96** [openai/gym#1712]
**Describe the bug**
FetchReach-v1 seems to be changes target position from step 200 to step 220. I present two images below.

Shouldn't the goal be the same throughout the episode?

<img width="1676" alt="image" src="https://user-images.githubusercontent.com/31866965/67073754-0f891880-f188-11e9-86d7-595d5f8e4aba.png">

<img width="1676" alt="image" src="https://user-images.githubusercontent.com/31866965/67073808-262f6f80-f188-11e9-8752-eb745fb03699.png">

**To Reproduce**
Run` python3 -m baselines.run --alg=her --env=FetchReach-v1 --num_timesteps=10000 --save_path=.models/FetchReach_10k_her --play`

**Expected behavior**
I would expect the goal/target to be the same from step 200 all the way to step 1200.

 - Mujoco Version 2.00
 - mujoco-py version 2.0.2.7

**Comment by christopherhesse** [comment]
Did the environment reset?

**Comment by RyanRizzo96** [comment]
No, I don't think so. The next steps are 240, 260, 280... 1200. At step 1200 the environment resets.

**Comment by RyanRizzo96** [comment]
Let me know if I can provide further information regarding this scenario. I tested again and had the same issue where during training, the goal position changed on the second step (220). So to recap:

```
Step 200: Goal A
Step 220: Goal B
Step 240: Goal B
.
.
.
Step 1200: Goal B
Environment Restes
Step 200: Goal C
Step 220: Goal D
.
.
.
Step 1200: Goal D
Environment Resets
```

**Comment by RyanRizzo96** [comment]
Any suggestions anyone?

**Comment by RyanRizzo96** [comment]
I can confirm that this happens on all Fetch environments including FetchPush-v1, FetchSlide-v1 and FetchPicakAndPlace-v1.

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
