### ISSUE TITLE
Atari env: states are not exactly equal

### ISSUE THREAD

**Issue by Coac** [openai/gym#1720]
The states using `env.clone_full_state()` are not exactly equal for the same action taken from the same state.
However, there is no problem on the observations.

The following script reproduces the problem:
```python
import sys

import gym
import numpy as np

if __name__ == '__main__':

    env = gym.make("Breakout-v0")
    env.reset()

    initial_state = env.clone_full_state()

    env.restore_full_state(initial_state)
    obs_after1, _, _, _ = env.step(0)
    state_after1 = env.clone_full_state()

    env.restore_full_state(initial_state)
    obs_after2, _, _, _ = env.step(0)
    state_after2 = env.clone_full_state()

    if not np.array_equal(state_after1, state_after2):
        print("the states are not equal")

        np.set_printoptions(threshold=sys.maxsize)
        print("state_after1:", state_after1)
        print("state_after2:", state_after2)

    if not np.array_equal(obs_after1, obs_after2):
        print("the obs are not equal")
```
The diff of `state_after1` vs `state_after2` https://www.diffchecker.com/QLagLXQk

**Comment by christopherhesse** [comment]
I don't think those are required to be the same.  What if the state has like a timestamp in it?

If RAM values (and observations) are the same, that may be sufficient for determinism.  If you're looking to compare states to see if they are the same, RAM may be good enough.
