### ISSUE TITLE
What do the observation values of Robotics env really represent?

### ISSUE THREAD

**Issue by RyanRizzo96** [openai/gym#1721]
FetchReach-v1 has the following characteristics:

```
Action Space: Box(4,)
Observation Space: Dict(achieved_goal:Box(3,), desired_goal:Box(3,), observation:Box(10,))
```

I'm printing out the observaions during a couple of runs and I get the following:
```

{'observation': array([ 1.34183265e+00,  7.49100387e-01,  5.34722720e-01,  1.97805133e-04,
        7.15193042e-05,  7.73933014e-06,  5.51992816e-08, -2.42927453e-06,
        4.73325650e-06, -2.28455228e-06]), 'achieved_goal': array([1.34183265, 0.74910039, 0.53472272]), 'desired_goal': array([1.20070508, 0.77258851, 0.41541062])}

{'observation': array([ 1.33991276e+00,  7.32872698e-01,  5.46933152e-01,  0.00000000e+00,
        0.00000000e+00, -1.80062459e-03, -1.37797288e-02,  1.05229019e-02,
        3.34696314e-04,  2.43512426e-04]), 'achieved_goal': array([1.33991276, 0.7328727 , 0.54693315]), 'desired_goal': array([1.20070508, 0.77258851, 0.41541062])}

```

What do the above values represent? Is there any way to know, for example, value 1,2,3:position of gripper, value 4: linear velocity of gripper, and so on?

Reading the [technical paper](https://arxiv.org/abs/1802.09464) it's not quite clear to me which parameters these values represent.

As I understand, from the paper, these are the observations for the robotics environments:

1. Cartesian position of gripper   (3 values)
2. Linear velocity of griper
3. Position of robot gripper         (3 values What is the difference between point 1? )
4. Linear velocity of robot’s gripper
5. Object’s Rotation using Euler angles of object
6. Object’s Cartesian position
7. Object’s linear velocity
8. Object’s angular velocity
9. Object’s position relative to gripper
10. Object’s linear velocity relative to gripper

I digged into the  gym/gym/envs/robotics/fetch_env.py  code and foudn that the observations are extracted using the following code:

```
def _get_obs(self):
        # positions
        grip_pos = self.sim.data.get_site_xpos('robot0:grip')
        dt = self.sim.nsubsteps * self.sim.model.opt.timestep
        grip_velp = self.sim.data.get_site_xvelp('robot0:grip') * dt
        robot_qpos, robot_qvel = utils.robot_get_obs(self.sim)
        if self.has_object:
            object_pos = self.sim.data.get_site_xpos('object0')
            # rotations
            object_rot = rotations.mat2euler(self.sim.data.get_site_xmat('object0'))
            # velocities
            object_velp = self.sim.data.get_site_xvelp('object0') * dt
            object_velr = self.sim.data.get_site_xvelr('object0') * dt
            # gripper state
            object_rel_pos = object_pos - grip_pos
            object_velp -= grip_velp
        else:
            object_pos = object_rot = object_velp = object_velr = object_rel_pos = np.zeros(0)
        gripper_state = robot_qpos[-2:]
        gripper_vel = robot_qvel[-2:] * dt  # change to a scalar if the gripper is made symmetric
```

Now when I run `FetchPickAndPlace-v1` I get 25 observations! **Where are these 15 added observations coming from and what do they represent?**

Any help would be appreciated.

**Comment by liuyichenliu** [comment]
Hello,I have the same problem about FetchReach 10 observations means for.Especially the last 7.Could you help me about this?
Any help would be appreciated.
