### ISSUE TITLE
Viewer set_color alpha channel

### ISSUE THREAD

**Issue by dizcza** [openai/gym#1722]
This is a feature request with a bug description.

1. Feature request.
I'd like to have an option for setting the alpha channel in
```python
    def set_color(self, r, g, b, a=1):
        self._color.vec4 = (r, g, b, a)
```

2. Bug/Unexpected behavior.
Currently, I cannot easily modify object transparency.

```python
obj = FilledPolygon(...)
obj.add_attr(Color(1, 0, 0, 0.5))
...
viewer.render()
```

Expected:
Transparent red color. Or, at least, warning that Color attr are ignored.

Got:
Black non-transparent (alpha=1) color.

For now, I'm doing 
`obj._color.vec4 = (1, 0, 0, 0.5)`

but `_color` is a protected field and I should not rely on this. Hence, this is a hack.

**Comment by christopherhesse** [comment]
Thanks for the feature request, but `classic_control.rendering` isn't really meant to be supported for external uses (just for the few included gym environments).  If you'd like to customize it, you can fork that code and make your own rendering setup.
