### ISSUE TITLE
What is the difference between success rate and reward when dealing with binary and sparse rewards?

### ISSUE THREAD

**Issue by RyanRizzo96** [openai/gym#1727]
In OpenAI Gym `reward` is defined as: 

> reward (float): amount of reward achieved by the previous action. The
> scale varies between environments, but the goal is always to increase
> your total reward.

I am training Hindsight Experience Replay on Fetch robotics environments, where rewards are sparse and binary indicating whether or not the task is completed. The [original paper][1] implementing HER uses **success rate** as a metric in it's plots like so:

[![enter image description here][2]][2]

On page 5 on the original paper it is stated that the reward is binary and sparse.

When I print the rewards obtained during a simulation of `FetchReach-v1` trained with HER I get the following values. First column shows the reward and the second column shows the episode length. As can be seen at every time step I am getting a reward, sometimes I get a -1 reward at every time step throughout the episode for a total of -50.

The maximum reward I can achieve throughout the episode is 0.

[![enter image description here][3]][3]

Therefore my question is: What is the reward obtained at each time-step? What does it represent and how is this different from the success rate?

  [1]: https://arxiv.org/pdf/1707.01495.pdf
  [2]: https://i.stack.imgur.com/ryiyZ.png
  [3]: https://i.stack.imgur.com/t5cCj.png

**Comment by pzhokhov** [comment]
the reward computing logic is very simple in Fetch environments:
https://github.com/openai/gym/blob/8e5a7ca3e6b4c88100a9550910dfb1a6ed8c5277/gym/envs/robotics/fetch_env.py#L53

essentially, if the reward type is 'sparse' (default), then reward is -1 for each step the achieved position (position of the gripper in case of FetchReach) is further than threshold from the goal, and 0 if the achieved position is within the vicinity of the goal. 
The episode length is always 50 in FetchReach environment (as your experiments seem to indicate too). Thus, if the goal is reached in 7 steps, the reward would be -7, and the gripper would just stay in place for 43 steps).
