### ISSUE TITLE
Sampling Bug

### ISSUE THREAD

**Issue by gowtham1997** [openai/gym#1729]
Gym Version: 0.15.3
issue: Box samples numbers above the `high` parameter.

```
from gym.spaces import Box
observation_space = Box(low=-3, high=-1, shape=(9,), dtype='int')
print(observation_space.sample())
>> [ 0 -2  0 -2  0 -1  0 -2  0]
```
The current implementation samples float numbers from uniform distribution of [`low`, `high`] and then converts the resulting samples to desired `dtype`. This runs into the problem of sampling `low` parameter very rarely(and not uniformly) when `dtype` is `int`(as we are converting the floats back to int which results in ceil operation in case of negative numbers) i.e in the above example -3 is almost never sampled as most of the low sampled floats like -2.85, -2.9 get converted to -2.
https://github.com/openai/gym/blob/0cd9266d986d470ed9c0dd87a41cd680b65cfe1c/gym/spaces/box.py#L93-L97

**Comment by pzhokhov** [comment]
moved the discussion into the PR
