### ISSUE TITLE
Getting permission denied error if I want to edit the wiki page

### ISSUE THREAD

**Issue by kishanpb** [openai/gym#1732]
![Screen Shot 2019-11-01 at 10 36 39 PM](https://user-images.githubusercontent.com/9605238/68065503-2b4bfd00-fcf8-11e9-841a-9d7634a29f3c.png)
![Screen Shot 2019-11-01 at 10 37 00 PM](https://user-images.githubusercontent.com/9605238/68065504-2b4bfd00-fcf8-11e9-8bf1-d85f5403313a.png)
Getting the same permission error by both methods (Github Desktop app, and terminal). The wiki-page mentions that anyone can edit, but not to do so!

**Comment by kishanpb** [comment]
So, this(https://stackoverflow.com/questions/10642928/how-to-pull-request-a-wiki-page-on-github/56810747#56810747) says we cannot directly edit the wiki page (makes sense if people go on randomly editing!) but can create a wiki page in our local repository and create an issue here suggesting changes.

I have updated the Leaderboard - https://github.com/kishanpb/gym/wiki/Leaderboard - for cartpole-v0, adding my name in a row. Please review and update the same in your wiki page.

**Comment by christopherhesse** [comment]
Can you try from a different account?  It looks like other people have been editing the wiki lately so this sounds like a github bug.
