### ISSUE TITLE
Can I change the length of some parts of a Mujoco model while running with Python?

### ISSUE THREAD

**Issue by KitanoFumiya** [openai/gym#1736]
I want to change the length of an agent part in mujoco using Python. (I am challenging the co-evolution of structure and control)
However, I didn't know how to change the length.
If I looked at a similar article, I can saw that the mass can be changed like env.model.body_mass [2] = 3.2. 
However, the length could not be changed.
In addition, we designed with Fusion 360, and saved as stl file, and simulated with model called in xml file. Can I change the length of the part saved in the stl file?

**Comment by TristanTrim** [comment]
I don't know for sure, but you might try looking at the variables defined in mjmodel.pxd:

https://github.com/openai/mujoco-py/blob/master/mujoco_py/pxd/mjmodel.pxd#L524

Maybe fiddle with jnt_pos or body_pos and see if that does anything like what you want.

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
