### ISSUE TITLE
Source Code of the Gym Webiste

### ISSUE THREAD

**Issue by vwxyzjn** [openai/gym#1737]
Hi,

I was wondering if the OpenAI team would consider releasing the source code of https://gym.openai.com. Recently I have been struggling to record a video of the agent's performances in `Taxi-v3` because the video recording wrapper produces this JSON file (https://gym.openai.com/videos/2019-10-21--mqt8Qj1mwo/Taxi-v3/original.json) that is not directly playable. Upon further inspection, it appears that OpenAI actually customized a version of asciinema to do so. 

If for various reasons it is not desirable for the team to open the source of the gym website, could you maybe consider releasing the source code of the customized version of asciinema? Or perhaps someone could write some instructions about how to play the JSON file as a video?

Thanks a lot.

**Comment by christopherhesse** [comment]
It looks like it's over here: https://github.com/jonasschneider/asciinema-player
