### ISSUE TITLE
cannot import name 'TransformObservation' from 'gym.wrappers'

### ISSUE THREAD

**Issue by lweitkamp** [openai/gym#1739]
On gym version 0.15.3,
```
>>> gym.__version__
'0.15.3'
```
When I write 
```
>>> from gym.wrappers import TransformObservation
```
I get the following error:
```
ImportError: cannot import name 'TransformObservation' from 'gym.wrappers'
```

**Comment by christopherhesse** [comment]
A new version of gym hasn't been released yet, you'll have to install from source for now or wait until the new version is released.
