### ISSUE TITLE
Deactivate rendering of desired goal in MuJoCo Envs

### ISSUE THREAD

**Issue by weidler** [openai/gym#1742]
I need the rendered frames from the HandEnv, but without the slightly transparent desired goal. Camera, colors, etc. were easily adjustable using viewer and sim, but I cannot find a way to completely deactivate the desired goal. Is it possible to add this as a parameter to the Environment class?

And until then, what would be a reasonable workaround? I could make the desired goal's texture completely transparent, but I assume it then is still "rendered", which adds computation time.

**Comment by pzhokhov** [comment]
@MillionIntegrals @ntezak do you know if that's possible / easy to implement?

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
