### ISSUE TITLE
** ARCHIVE FAILED ** Exit status: 65 at the very last step of the archive process

### ISSUE THREAD

**Issue by AshrafTawfeeq** [openai/gym#1743]
I am running gym using fastlane and I have my lane gym method as follows:

```
gym(
	scheme: "App Name", #Contains a space 
	configuration: "Beta",
	clean: true,
	include_bitcode: false,
	export_method: "enterprise",
	export_options: {
	provisioningProfiles: { 
	        <APP_BUNDLE_ID> => "match InHouse bundle id",
	        <RICH_PUSH_BUNDLE_ID> => "match InHouse rich push bundle ID"
	      	}
    	},
	output_directory: $OUTPUT_PATH,
	skip_profile_detection: true
)
```

I get hit by a failure while trying to ```touch app name.app```. When I try to locate this folder `InstallationBuildProductsLocation` I can't seem to find it. 
I tried to archive with Xcode and it works 100% of the time. Tried to delete my provisioning profiles and redownloading them, and still nothing.

**Comment by christopherhesse** [comment]
This issue is with a different library called gym, please file this issue here: https://github.com/fastlane/fastlane
