### ISSUE TITLE
observation space filled with white pixels

### ISSUE THREAD

**Issue by chtsao8** [openai/gym#1755]
Hi,

I'm currently using retro gym to train an RL agent using Q-learning to play SNES Mario Kart, but the observation space seems to be continuously incorrect at each timestep of the game, giving me a 224x256x3 array of 0's.

env.render(mode='rgb_array') also gives me the same thing at each timestep. Any suggestions on how to fix this?

**Comment by christopherhesse** [comment]
This sounds like either a gym-retro bug or a bug with the mario kart integration.  Please test the game `Airstriker-Genesis` and make sure that works.  If not, please file an issue on https://github.com/openai/retro.  If it does work, please check your mario kart integration.
