### ISSUE TITLE
wiki page ’gym/wiki/Leaderboard’  shows nothing. may destroyed by someone.

### ISSUE THREAD

**Issue by Taoerwang** [openai/gym#1759]
wiki page ’https://github.com/openai/gym/wiki/Leaderboard’ was destroyed by someone....

i don't know what and how to do .

**Comment by christopherhesse** [comment]
@aaronhma any idea why this was done?

![image](https://user-images.githubusercontent.com/440336/70364341-02f87680-1841-11ea-8596-4dde06e716ef.png)

**Comment by christopherhesse** [comment]
I reverted the deletion, thanks for filing the issue!

**Comment by aaronhma** [comment]
@christopherhesse Sorry, I wanted to edit it but pressed the wrong buttons and couldn’t undo. Thanks for undoing it.
