### ISSUE TITLE
Is SubprocVecEnv well-suited for large-CPU architecture ?

### ISSUE THREAD

**Issue by Hadjubuntu** [openai/gym#1760]
Hi everyone,

I'm trying to speed up the training phase of your PPO2 algorithm with a 96-CPU architecture by increasing the number of environnments for experience collection (30 envs in SubprocVecEnv), I don't see much improvement in FPS compared to a traditionnal 8-CPU architecture, do you have some clues about it ?

Thanks a lot
Adrien

**Comment by christopherhesse** [comment]
Is this a question about baselines?

**Comment by Hadjubuntu** [comment]
You are right, I'm gonna close this topic and move it to baselines repository
