### ISSUE TITLE
gym and Jetson Nano ???

### ISSUE THREAD

**Issue by alpersarikaya** [openai/gym#1762]
When I try for installing gym in Jetson Nano "pip3 install gym" or "pip install gym", I am receiving below error:

"Could not find a version that satisfies the requirement opencv-python (from gym) (from versions: )
No matching distribution found for opencv-python (from gym)"

Opencv is installed on Jetson Nano with opencv4.1.0:

Can anyone help me??

Both version of Python are working with below command successfully:

Python 2.7.15+ (default, Oct 7 2019, 17:39:04)
[GCC 7.4.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.__version__
'4.1.0'

Python 3.6.9 (default, Nov 7 2019, 10:44:02)
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
>>> cv2.__version__
'4.1.0'

**Comment by pzhokhov** [comment]
I have zero experience with Jetson Nano; however, this seems like pip issue (maybe the opencv pip package is named differently on Jetson Nano?).
Could you run `pip freeze | grep opencv-python` and post here the output? 
Also, as an alternative option (if you are not planning to use atari), I would suggest cloning latest gym and removing opencv-python from line 33 of setup.py, here https://github.com/openai/gym/blob/bd68ec33f333d9aa276922ef5155b6b575d0cf6c/setup.py#L32
opencv is really only used in gym for atari image processing (in fact, I think we should move it out of core dependencies); so if you are not relying on atari environments, it should not be necessary

**Comment by pzhokhov** [comment]
actually, it has been added recently, so yet another option is to use older version of gym, for instance, 0.15.3 (`pip install gym==0.15.3`)

**Comment by pzhokhov** [comment]
https://github.com/openai/gym/pull/1764

**Comment by alpersarikaya** [comment]
> actually, it has been added recently (#1713), so yet another option is to use older version of gym, for instance, 0.15.3 (`pip install gym==0.15.3`)

This commands work for pip installation. Thanks your big helps.

**Comment by alpersarikaya** [comment]
> actually, it has been added recently (#1713), so yet another option is to use older version of gym, for instance, 0.15.3 (`pip install gym==0.15.3`)

Commands work Jetson Nano gym installation. Big thanks. Thank you.

**Comment by EHB-1989** [comment]
I work also with a Jetson Nano and I had the same issue when trying to install gym (pip3 install gym).
The solution (pip3 install gym==0.15.3) from @pzhokhov worked perfectly. Thanks
