### ISSUE TITLE
Observation Space Help Needed

### ISSUE THREAD

**Issue by Ashwin-Ramesh2607** [openai/gym#1766]
Hey,
I am trying to create a custom gym environment for a Rubik's cube solver. I am using a list of numpy array (6 np.arrays having a 3*3 matrix each for each side of the cube). I am using action space as spaces.Discrete(12) to indicate the 12 different kinds of face turns we can make on the cube. I am having trouble initialize the observation space. It has to represent the list of numpy arrays having discrete values from 1 to 6 (colors on the cube). Please help as to how to approach the observation space for this problem.

**Comment by pzhokhov** [comment]
What's the upside of having a list of matrices vs 6x3x3 tensor? In other words, would `Box(low=0, high=5, shape=(6,3,3), dtype=np.uint8)` work?

**Comment by Ashwin-Ramesh2607** [comment]
Alright, I shall try that.
The thing was I had an existing code with a list of matrices, and I can just transfer the functions from that code. I shall try using Box with the parameters you had specified. Thanks!
