### ISSUE TITLE
Help message to install atari-py fails with zsh

### ISSUE THREAD

**Issue by koreymacdougall** [openai/gym#1767]
Operating environment - Running Debian 10 and zsh:

Upon initial installation, when attempting to launch an Atari environment that hasn't been installed, (e.g., MsPacman-v0), the following error message is presented: 

> (HINT: you can install Atari dependencies by running 'pip install gym[atari]'.)

This is defined in file [envs/atari/atari_env.py](https://github.com/openai/gym/blob/567c620b723cd7455d4e590b9698b85dc93dc612/gym/envs/atari/atari_env.py), on lines 12-13.

The specified install command throws an error:

>  zsh: no matches found: gym[atari]

The command works fine in Bash.  On zsh, it is necessary to use the following:
`pip3 install atari-py` or `pip install atari-py`

The help note could be modified to capture the two different options.  Or does pip installing atari-py accomplish the same thing in both shells?  I don't know if this issue affects other shells.

**Comment by biggzlar** [comment]
This is a behavior on zsh's side. It doesn't escape square brackets by default, so you'd have to add this to your .zshrc:

```
alias rake='noglob rake'
```

Alternatively, you can use either:

```
pip install gym\[atari\]
pip install 'gym[atari]'
```

**Comment by pzhokhov** [comment]
`pip` does recognize `pip install 'gym[atari]'` correctly. That's the preferred method, because `atari` extra has some other dependencies (like `Pillow` and `opencv-python`).

**Comment by amjadmajid** [comment]
The commands the I used to install gym with atari environments in _zsh_ environment is `pip install 'gym [atari,accept-rom-license]==0.21.0'`
