### ISSUE TITLE
Openai Gym about creating one's own environment

### ISSUE THREAD

**Issue by zhaoworking** [openai/gym#1768]
Traceback (most recent call last): 
 File "mytest.py", line 40, in <module>
    env.reset()
  File "/home/zhao/gym/gym/wrappers/time_limit.py", line 25, in reset
    return self.env.reset(**kwargs)
  File "/home/zhao/gym/gym/core.py", line 66, in reset
    raise NotImplementedError
NotImplementedError

When I make my own environment in gym ,there is something worng with creating.And I have registered the envs .But it told me the error as above.So,what can i do solve it ? Please help me.

**Comment by zhaoworking** [comment]
I have found the cause,it is becasue that unstandard use of Tab and space leads to the wrong Code indentation .

**Comment by Maltimore** [comment]
Could the issue be closed then?

**Comment by pzhokhov** [comment]
@zhaoworking the error you specified suggests that you have not implemented `reset` method in your environment. gym Env API requires `step`, `reset` and `render` methods to be explicitly defined.
