### ISSUE TITLE
Is reward_threshold ever used?

### ISSUE THREAD

**Issue by Maltimore** [openai/gym#1769]
I'm trying to find out where in the code the ```reward_threshold``` is being used to determine whether a task is solved? I'm most likely missing something, but doing a full-text search revealed nothing that looks like reward_threshold is ever really used.

**Comment by pzhokhov** [comment]
Correct, there is no code in gym that relies on `reward_threshold`. It is essentially metadata that external users of the environment could use. To my understanding, in the past we used to filter the results for the env leaderboards; but those are not active anymore. Still, it can be useful for reward normalization across difference environments, or for computing aggregate statistics of sort "out of all the environments, how many did my new algorithm manage to solve"
