### ISSUE TITLE
CartPole-v0 documentation issue

### ISSUE THREAD

**Issue by ty-w** [openai/gym#1772]
Based on my naive trials, the max reward (at any given step)  is 1, but the "Solved Requirements" say "Considered solved when the average reward is greater than or equal to 195.0 over 100 consecutive trials". I think there may be some typos or unclearness here.

**Comment by christopherhesse** [comment]
I think that means the average reward per episode, not per step.

**Comment by christopherhesse** [comment]
That should be referring to 200 step episodes: https://github.com/openai/gym/blob/57187307f146adb4eec7c29a8483119f80ae6a67/gym/envs/__init__.py#L56 so the max reward per episode is 200.

**Comment by qw245roar** [comment]
Does this mean you can only fail at most 5 times within one episode if you want to have this episode marked as a successful one? Many thanks! @christopherhesse
