### ISSUE TITLE
Mujoco tasks highest score or when one task is sovled?

### ISSUE THREAD

**Issue by zhan0903** [openai/gym#1776]
Hi, I am wondering for Mujoco tasks such as Hopper-v2, HalfCheetah-v2, and Swimmer, what are these the highest score of these tasks we can gain?  Or how to judge when a task is solved? Thanks.

**Comment by jacekplocharczyk** [comment]
Hi, if you are creating environments using `gym.make(ENV_NAME)` you can check done threshold in this file: https://github.com/openai/gym/blob/master/gym/envs/__init__.py

**Comment by zhan0903** [comment]
> Hi, if you are creating environments using `gym.make(ENV_NAME)` you can check done threshold in this file: https://github.com/openai/gym/blob/master/gym/envs/__init__.py

Thanks for your response! 
From the file, the reward threshold of the environment "HalfCheetah-v2" is 4800, but based on some baselines, e.g., SAC or TD3 ( they create environments using `gym.make(ENV_NAME)`), they can achieve a final score around 10000.  I am confused about it. Thanks.

**Comment by jacekplocharczyk** [comment]
Yeah I know that pain 😝 

They probably used `*-v1` versions and there could be a different reward.
But I don't know much about those versions.

**Comment by zhan0903** [comment]
> Yeah I know that pain 😝
> 
> They probably used `*-v1` versions, and there could be a different reward.
> But I don't know much about those versions.

Thanks. 
I have trained SAC on "HalfCheetah-v2" for 1 million steps, the final score is also over 10000. BTW, if there is no  "reward_threshold" (e.g.," Walker2d-v2" and "Humanoid-v2") in that file, does it means there is no limitation on its maximum score?

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
