### ISSUE TITLE
Is there an environment in which we can train a car to avoid the obstacle in Gym ?

### ISSUE THREAD

**Issue by zhaoworking** [openai/gym#1782]
I wanna find an environment in which i can train a car to avoid the obstacle with RL in the Gym
simulation. If so,can u tell me what the envs'  name is ? Due to the envs hard to code ,I wanna find a written envs that i can use it immediately.

**Comment by MouseAndKeyboard** [comment]
https://gym.openai.com/envs/Enduro-v0/
https://gym.openai.com/envs/CarRacing-v0/

**Comment by zhaoworking** [comment]
> https://gym.openai.com/envs/Enduro-v0/
> https://gym.openai.com/envs/CarRacing-v0/
> 
> (might not be exactly what you want)
> I'm guessing what you really want is some sort of simulator for creating a self-driving car or something.

yes,u are right.but both of two are not fit for avoiding obscale.Can u server a tip for the self-driving car envs?

**Comment by MouseAndKeyboard** [comment]
A quick search brought me this:
https://github.com/duckietown/gym-duckietown

Maybe this might be along the lines of what you're looking for.

**Comment by christopherhesse** [comment]
Please try https://github.com/duckietown/gym-duckietown
