### ISSUE TITLE
Dict space documentation, improvements

### ISSUE THREAD

**Issue by nickagliano** [openai/gym#1784]
The dict space seems like a potentially powerful tool to describe more complex environments, but I'm struggling to find any documentation on it. It would be really cool if there was some built in gym function to describe the shape of these space dicts, similar how you can do box.shape or discrete.n to get the size/shape. I guess right now I'm just struggling to see the advantage of the gym spaces.dict vs a regular python dict.

**Comment by christopherhesse** [comment]
A regular python dict would be an instance of a dict space.  A dict space is an object describing the structure of a python dict (used as an observation or action). 

There's some documentation on the dict space object itself: https://github.com/openai/gym/blob/master/gym/spaces/dict.py#L7

You can access the subspaces of a dict space with `.spaces` I think.
