### ISSUE TITLE
Is it possible to modify an env's "done" condition?

### ISSUE THREAD

**Issue by Zju-George** [openai/gym#1788]
![test](https://user-images.githubusercontent.com/33959089/72504381-b14bfe80-3878-11ea-88b6-7dfd650f36dd.gif)

For example, in "CartPole-v0" env, I guess a game would be terminated as soon as the rotation angle of the pole is greater than a certain critical angle. If that is the case, the critical angle is actually pretty small and I wish I can increase that angle.

Generally, is it possible to modify an env's "done" condition by any chance?

**Comment by christopherhesse** [comment]
Yes, but you'd have to make your own copy of the cartpole environment as a new gym environment: https://github.com/openai/gym/blob/master/gym/envs/classic_control/cartpole.py#L13

Also see https://github.com/openai/gym/blob/master/docs/creating-environments.md

**Comment by Zju-George** [comment]
@christopherhesse 
Thank you very much! Below is what I got!

Here are sceenshots of I playing my own version of CarPole in which I double the termination angle so I can play a little bit longer.
https://github.com/openai/gym/blob/8e5a7ca3e6b4c88100a9550910dfb1a6ed8c5277/gym/envs/classic_control/cartpole.py#L68
`self.theta_threshold_radians = 24 * 2 * math.pi / 360          # George's Modification : 12->24.`
![play_myself](https://user-images.githubusercontent.com/33959089/72666965-e790a600-3a51-11ea-94a6-dbd1268cdb42.gif)
