### ISSUE TITLE
Ant Density

### ISSUE THREAD

**Issue by half-potato** [openai/gym#1797]
Why is the ant density 5.0 g/m^3? That's insanely light. The ant seems to fly with the slightest touch. I watched a random policy and it would constantly be in the air because every time it touched the ground it flew.

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
