### ISSUE TITLE
Why is done always false in robotics environment?

### ISSUE THREAD

**Issue by macsmitty** [openai/gym#1803]
Hi!
In the step function of the robotics environment 'done' is always set to False and only the info dict contains information about the success of an episode. 
```
    def step(self, action): 
        ...
        done = False
        info = {
            'is_success': self._is_success(obs['achieved_goal'], self.goal),
        }
        ...
        return obs, reward, done, info 
```

Why is it handled like this? Can someone point me to the mechanism catching if an episode is successful?
In the robotics environment I'm working in (Ur10 in Mujoco) it seems like this mechanism is not working (success rate is always 0 but goal is reached within tolerance sometimes). However, everything is working perfectly when training FetchReach for example. Thanks for your help!

**Comment by Aaatresh** [comment]
I have a similar doubt, except that I am dealing with another environment. Where does mujoco toggle the done flag to True?

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
