### ISSUE TITLE
Does anyone know what is in the ram of atrai games? 

### ISSUE THREAD

**Issue by dxu23nc** [openai/gym#1805]

**Comment by christopherhesse** [comment]
I'm afraid this is game-specific.  A few of the ram locations are documented in the ALE source code (things used to calculate done or reward).  In general, I don't know of any documentation for these games, though you could ask on the Arcade Learning Environment repo.

**Comment by dman82499** [comment]
For those that still have this question, there is a Atari Annotated RAM Interface wrapper for gym available here https://github.com/mila-iqia/atari-representation-learning
