### ISSUE TITLE
Should clipping be applied before stepping?

### ISSUE THREAD

**Issue by fywu85** [openai/gym#1806]
https://github.com/openai/gym/blob/4d24886f20a04a6c57c580d57c4402e59941b7bb/gym/envs/classic_control/pendulum.py#L46

Why clipping angular speed after stepping angular position? Should it be before the forward Euler step so that its effect is fully applied?

**Comment by christopherhesse** [comment]
I don't see any paper reference for this environment, so I don't know why this particular clipping method was chosen. I doubt it's worth changing at this point because we would need to make a new pendulum-v1 environment with this different clipping.
