### ISSUE TITLE
Threading issues

### ISSUE THREAD

**Issue by tobq** [openai/gym#1810]
I tried to multi thread my usage of gym using a `ThreadPoolExecutor` but I get 2 issues:

1. `gym.make()` fails
* throws empty error
2. Trying to render also fails
* throws error

**Comment by christopherhesse** [comment]
Do you have a script that does this?  You probably can't use multiple threads with render (or any opengl calls) because those will fail if they're not on the main thread.  You have to make a subprocess in that case.
