### ISSUE TITLE
a minor documentation issue in blackjack.py?

### ISSUE THREAD

**Issue by sorryformyself** [openai/gym#1812]
In the 51 line of **gym/envs/toy_text/blackjack.py** , the documentation said that "The game starts with each (player and dealer) having one face up and one face down card." 

But from my knowledge, the game "blackjack" should starts with **dealer** having one face up and one face down card while **player** having two face up card. Maybe its' just different rules?

**Comment by christopherhesse** [comment]
According to https://bicyclecards.com/how-to-play/blackjack/:

```
When all the players have placed their bets, the dealer gives one card face up to each player in rotation clockwise, and then one card face up to themselves. Another round of cards is then dealt face up to each player, but the dealer takes the second card face down. Thus, each player except the dealer receives two cards face up, and the dealer receives one card face up and one card face down. (In some games, played with only one deck, the players' cards are dealt face down and they get to hold them. Today, however, virtually all Blackjack games feature the players' cards dealt face up on the condition that no player may touch any cards.)
```

So it sounds like you're right and that's the way blackjack is mostly played currently.  This environment is an implementation from "Example 5.1 in Reinforcement Learning: An Introduction by Sutton and Barto", so really it just needs to implement those rules.

However, it's not clear to me that there is any difference between the player having one face up card or two face up cards, does the dealer's behavior change for the purposes of this environment?  The player is able to perceive both of their cards regardless of their face status.

If you agree that it doesn't matter, you can file a PR to remove the mention that the player has one face up and one face down card (which isn't mentioned in the original example from the book at all).

**Comment by sorryformyself** [comment]
@christopherhesse Thanks for your investigation! If 

> The player is able to perceive both of their cards regardless of their face status.

Then everything will be alright. I infered from that documentation, which I thought the player doesn't even know their own face down card. Maybe the documentation need to be more clear. Thanks for helping!

**Comment by christopherhesse** [comment]
The documentation has this part:

> The observation of a 3-tuple of: the players current sum,
    the dealer's one showing card (1-10 where 1 is ace),
    and whether or not the player holds a usable ace (0 or 1).

Looking at the observations of the environment, it seems that you do observe your own sum (the first number):

```
In [16]: env.reset()
Out[16]: (13, 9, False)

In [17]: env.step(env.action_space.sample())
Out[17]: ((14, 9, False), 0, False, {})

In [18]: env.step(env.action_space.sample())
Out[18]: ((20, 9, False), 0, False, {})

In [19]: env.step(env.action_space.sample())
Out[19]: ((20, 9, False), 0.0, True, {})
```

So I will close this issue since it looks okay.  Please file a PR for the docstring if you think it can be made more clear.
