### ISSUE TITLE
How to create a demonstration for Inverse Reinforcement Learning on mountain car

### ISSUE THREAD

**Issue by Ishira1601** [openai/gym#1813]
I'm testing Inverse Reinforcement Algorithms. I want to recover the reward function for the mountain car. For IRL you need demonstrations. How would I go about creating them.

**Comment by christopherhesse** [comment]
You can train an agent and then record demonstrations, or else setup the environment in an interactive fashion like procgen's interactive.py: https://github.com/openai/procgen/blob/master/procgen/interactive.py and then record the observations/actions of you solving the environment yourself.

Recording demonstrations should be a matter of recording the observations and actions at each step, perhaps into a python pickle file for training on later.
