### ISSUE TITLE
How does gym store experience?

### ISSUE THREAD

**Issue by Jaccccc** [openai/gym#1820]
I have been using a gym environment called gym tetris and i am a bit confused about it all. I understand that this probably isn't the best approach to making a tetris ai but even when my ai gets a line or an increase in score, it still appears to be quite bad at the game. Is the ai actually learning and storing what it learns? And if not, how do i do that? I am on raspbian and this is the code:

from nes_py.wrappers import JoypadSpace
import gym_tetris
from gym_tetris.actions import MOVEMENT

env = gym_tetris.make('Tetris-v2')
env = JoypadSpace(env, MOVEMENT)

done = True
for step in range(5000):
    if done:
        state = env.reset()
    state, reward, done, info = env.step(env.action_space.sample())
    env.render()

env.close()

**Comment by jacekplocharczyk** [comment]
`state, reward, done, info = env.step(env.action_space.sample())` this line means you are sampling random action (`env.action_space.sample()`). You don't have any ML/DL model here.
