### ISSUE TITLE
`KellyCoinflipGeneralizedEnv` can overflow `numpy.random.RandomState.randint`

### ISSUE THREAD

**Issue by ymd-h** [openai/gym#1821]
`KellyCoinflipGeneralizedEnv` sometimes raises `ValueError: high is out of bounds for int64` when calling `KellyCoinflipGeneralizedEnv.action_space.sample`.

There is a overflow bug.

I tested following on the docker image `python:3.7`

```
docker run -it --rm python:3.7 bash
pip install scipy gym
```

---

`action_space` is initialized as follows:

https://github.com/openai/gym/blob/5f73c5dff519083f6e3dac1ca91e6505c8db1e20/gym/envs/toy_text/kellycoinflip.py#L100

`maxWealth` is calculated at here using `scipy.stats.genpareto` ([link](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.genpareto.html)) with `c=maxWealthAlpha (=5.0)` and `loc=maxWealthM (=200.0)`

https://github.com/openai/gym/blob/5f73c5dff519083f6e3dac1ca91e6505c8db1e20/gym/envs/toy_text/kellycoinflip.py#L87

Survival function shows the probability of sampling `2^63+1` and up is around `1e-4` (not zero and actually I encountered).

```
>>> from scipy.stats import genpareto
>>> genpareto.sf(2**63+1,c=5.0,loc=200)
0.0001167422485095261
```

---

`numpy.random.RandomState.randint`, which is used at `Discrete.sample`, can accept only int64 range integer. (Precisely speaking which is platform dependent `np.int` ([link](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.random.RandomState.randint.html#numpy.random.RandomState.randint)))

```
>>> import numpy as np
>>> r = np.random.RandomState()
>>> r.randint(2**63)
7744376569175500554
>>> r.randint(2**63+1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "mtrand.pyx", line 747, in numpy.random.mtrand.RandomState.randint
  File "_bounded_integers.pyx", line 1267, in numpy.random._bounded_integers._rand_int64
ValueError: high is out of bounds for int64
```

---

I don't know how much important the shape of probability distribution (at > 2^63) for this game, but from engineering point of view, we need to put a upper ceil at certain level.

**Comment by christopherhesse** [comment]
Thanks for the bug report!  @pzhokhov should there be a `min(val, 2**63)` in kellycoinflip?

**Comment by jkterry1** [comment]
Kelly coinflip has been moved

**Comment by ymd-h** [comment]
@jkterry1 Thank you for your comment.

Could you give me more information?
Will the environment be deleted?

**Comment by jkterry1** [comment]
It and a host of other largely unused toytext environments are being moved to https://github.com/Rohan138/gym-legacy-toytext

**Comment by ymd-h** [comment]
@jkterry1 
Thank you.

I understand the situation.
