### ISSUE TITLE
CartPole doesn't work 

### ISSUE THREAD

**Issue by ddevsantos** [openai/gym#1824]
import gym
env = gym.make('CartPole-v0')
env.reset()
for _ in range(1000):
    env.render()
    env.step(env.action_space.sample()) # take a random action
env.close()

![cart_pole](https://user-images.githubusercontent.com/61477111/75286150-bcd70180-57f6-11ea-893e-72d737d642d8.JPG)

I've used the same code provided by gym's oficial site, by the way:

![gym_](https://user-images.githubusercontent.com/61477111/75286333-20612f00-57f7-11ea-9b3c-015fc8316fed.JPG)

lol

**Comment by jacekplocharczyk** [comment]
You are running headless (on a remote server, in this case - Colab).
Gym requires virtual display to render episodes in remote displays.

Take a look at this colab https://colab.research.google.com/drive/18LdlDDT87eb8cCTHZsXyS9ksQPzL3i6H#scrollTo=7wY4qZhPXotR

Hope it helps!

**Comment by christopherhesse** [comment]
Thanks for answering @jacekplocharczyk!  That's correct, you can remove the `env.render()` line or you can start an X server.  Since you won't be able to see the output anyway, removing the `env.render()` line seems like a good idea here: https://github.com/openai/gym#rendering-on-a-server
