### ISSUE TITLE
Game difficulty in atari_env.py, no assertion of limit

### ISSUE THREAD

**Issue by wgeul** [openai/gym#1825]
```
import gym
env = gym.make('Pong-v0')
env.reset()
env.env.game_difficulty = 10**9
for _ in range(1000):
    env.step(5)
    env.render()
env.close()
```

When I run this code I don't get a notification that the difficulty exceeds the maximum. But the code in atari_env.py at lines 101 -  107 indicates:

```
        if self.game_difficulty is not None:
             difficulties = self.ale.getAvailableDifficulties()

            assert self.game_difficulty in difficulties, (
                 "Invalid game difficulty \"{}\" for game {}.\nAvailable difficulties are: {}"
             ).format(self.game_difficulty, self.game, difficulties)
            self.ale.setDifficulty(self.game_difficulty)
```
 I also can't find the maximum game_difficulty in any way, nor can I really confirm the actual game difficulty. Is this suppose to happen? How do I change the game difficulty?

**Gym version:** '0.16.0'

**Comment by christopherhesse** [comment]
You can call `env.unwrapped.ale.getAvailableDifficulties()` to get a list (actually numpy array) of difficulties.  You are setting it correctly, but after you set it, you want to do `env.seed()` and then probably `env.reset()`.  The code you referenced is actually run during `env.seed()`, sorry for the confusion!

**Comment by wgeul** [comment]
> You can call `env.unwrapped.ale.getAvailableDifficulties()` to get a list (actually numpy array) of difficulties. You are setting it correctly, but after you set it, you want to do `env.seed()` and then probably `env.reset()`. The code you referenced is actually run during `env.seed()`, sorry for the confusion!

Thank you!
