### ISSUE TITLE
Should achieved_goal and desired_goal also be part of the observation?

### ISSUE THREAD

**Issue by siferati** [openai/gym#1826]
When using HER, the `observation_space` should consist of `observation`, `achieved_goal` and `desired_goal`.

My question is, should `achieved_goal` and `desired_goal` also be part of the `observation`?

I was taking a look at OpenAI's Fetch environment, and it looks to me like the `achieved_goal` is indeed part of the `observation`, but the ` desired_goal` is not. Why is that?

https://github.com/openai/gym/blob/639264c545329638a513d3c241e52ef792f56379/gym/envs/robotics/fetch_env.py#L108-L121

**Comment by xloem** [comment]
This question appears fully answered at https://github.com/hill-a/stable-baselines/issues/708#issuecomment-591483216 unless I am missing something.

The `achieved_goal` is not part of the `observation` subobject, it is just calculated from part of it.  Both goals are part of the observation space.

It is true there is no clear link between the achieved goal state and the observation state provided, to inform a learning algorithm of their relationship.

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
