### ISSUE TITLE
Atari Pong uses left/right keys instead of up/down keys

### ISSUE THREAD

**Issue by elliotwaite** [openai/gym#1832]
Running this code:
```
env = gym.make('Pong-v0')
print(env.get_keys_to_action())
```
... prints:
```
{(): 0, (32,): 1, (100,): 2, (97,): 3, (32, 100): 4, (32, 97): 5}
```
97 is the key code for the "a" key and 100 is the key code for the "d" key. So pressing left ("a") moves the paddle down, and pressing right ("s") moves the paddle up. Is this the expected behavior, or is Pong supposed to be using the "w" key to move the paddle up and the "s" key to move the paddle down?

**Comment by christopherhesse** [comment]
Does it look correct for other atari games?  This could just be what the original atari pong did.

**Comment by elliotwaite** [comment]
I think I figured it out. I tried inspecting the ROMs using [Stella](**url**), and the specified controller type for most games was `JOYSTICK`, but for Pong, it was `PADDLES_IAXDR`, which I assume refers to these:

![512px-Atari_Paddle](https://user-images.githubusercontent.com/1767836/76146927-5b136480-604c-11ea-8017-8f40392c39b0.jpeg)

Which makes sense since these would allow the user to move the Pong paddle up and down at a variable speed, probably making the game easier to play.

So mapping counter-clockwise to left and clockwise to right is probably the right thing to do for most games. A special case could be made for Pong to remap them to up and down, but this probably isn't important enough to warrant the effort. I'll let you decide.

**Comment by christopherhesse** [comment]
Good find!

While `keys_to_actions` appears to only be used for human keyboard interaction with the environment and only for mountain car and atari, I think it's probably not worth changing this currently.  The risk is low, but the benefit is also pretty low.  Sorry for the confusion though, and thanks for filing the issue!
