### ISSUE TITLE
cannot import univserse: No module named 'gym.benchmarks'

### ISSUE THREAD

**Issue by TaeheeJeong** [openai/gym#1834]
I successfully installed gym-0.17.0 with universe-0.21.3
but when I tried to 'import universe', the following error comes out.

ModuleNotFoundError: No module named 'gym.benchmarks'

I already tried to 'pip uninstall gym, pip install gym==0.9.5'. 
but my gym version does not change at all.

**Comment by christopherhesse** [comment]
I'm afraid universe is deprecated and no longer supported
