### ISSUE TITLE
Robot dynamics in FetchReach-v1

### ISSUE THREAD

**Issue by nik31096** [openai/gym#1837]
What are the equation of motion for robot from FetchReach-v1 and other Fetch* environments? I want to apply iLQR to this environment. Can anyone help in that? Thanks

**Comment by Amritpal-001** [comment]
You can check out my article on Fetch environments by OpenAI [https://link.medium.com/CV6la7YfV7](https://link.medium.com/CV6la7YfV7) , I hope it's helpful.

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
