### ISSUE TITLE
PlayPlot 'missing 1 required positional argument' error

### ISSUE THREAD

**Issue by Berk035** [openai/gym#1838]
Hello dear contributors,

I deal with a problem while real time plotting in gym environment. An error occurred that is given below:

`points = self.data_callback(obs_t, obs_tp1, action, rew, done, info)`
`TypeError: callback() missing 1 required positional argument: 'info'`

I tried lots of way to solve this problem. I've read lots of problem about missing argument on websites about initialization. I put the line below but still problem is exist. 

`p = PlayPlot(PlayPlot.callback, horizon_timesteps=300, plot_names=["reward"])`
` play(env, zoom=4, fps=60, callback=p.callback)`

Thank you for your attention. Have a nice day.

**Comment by christopherhesse** [comment]
You should provide your callback function to the `PlayPlot` constructor like `p = PlayPlot(YOUR_CALLBACK_HERE, horizon_timesteps=300, plot_names=["reward"])`

An example callback would be:

```py
def callback(obs_t, obs_tp1, action, rew, done, info):
            return [rew,]
```

**Comment by Berk035** [comment]
Hello again @christopherhesse ,

   I got it that point, but I guess I couldn't explain myself exactly. Your callback function in code: [https://github.com/openai/gym/blob/f37830bbe2c85f613fded1721976dbe94f6bed0b/gym/utils/play.py](url) consist 'self' argument.
   If you mean that function [self.data_callback(obs_t, obs_tp1, action, rew, done, info)](https://github.com/openai/gym/blob/f37830bbe2c85f613fded1721976dbe94f6bed0b/gym/utils/play.py#L159), it would response missing argument as 'info'. How can I fix this? 
Thank you for your attention.
