### ISSUE TITLE
Question regarding best way to provide metadata about the actions for a Custom Environment

### ISSUE THREAD

**Issue by fernandocamargoti** [openai/gym#1842]
I'm creating a custom environment for Recommendation Systems. My action is discrete, being the item to recommend. My Observation is a dict containing the current user and some information about the day of the week and other kinds of stuff like that. The Agent should take the observation into account to select the item the user will most likely purchase, being rewarded with 1.0 if the user purchased and 0.0 otherwise.

The thing is, I have a lot of metadata about each item that I'd like to make available for the Agent. Should I put it inside the "metadata" property? Should I return an "available_items" in my Observation dict containing the items and their metadata? Is there a better option?

Thanks in advance.

**Comment by christopherhesse** [comment]
If you want that data to be directly observable to all agents using the environment in a generic way, encoding it in some array format inside the observation makes sense to me.

If you don't want to encode it in some array format, you could include it in the observation dict and just not describe it with a `gym` observation space.  I don't think putting it in the `metadata` property makes sense though, the information that the agent is supposed to receive should be contained entirely in the observation.
