### ISSUE TITLE
Does anyone know the training results of *-ram-v0 and *-v0? Here, * represents one game in atari 2600.

### ISSUE THREAD

**Issue by dxu23nc** [openai/gym#1843]
Gym is a great interface. I notice that it provides two kinds of training input for RL. The first one is RAM-based and the second one is image-based. 

Does anyone know which one is better for training an RL agent?

Thanks in advance.

**Comment by christopherhesse** [comment]
I've heard RAM is easier, but I don't recall seeing any graphs that showed one way or the other, sorry!
