### ISSUE TITLE
Box bound precision warning

### ISSUE THREAD

**Issue by rusu24edward** [openai/gym#1844]
I get this warning a lot when using Box environments:

```
.../gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
```
This is particularly annoying, especially because the [default dtype for Box is](https://github.com/openai/gym/blob/master/gym/spaces/box.py#L24) `np.float(32)`

**Comment by cpnota** [comment]
I get this message when loading `Pendulum-v0`. A workaround is changing the logger level:  `gym.logger.set_level(40)`. Not great though, because you could miss more important warnings as a result.

**Comment by christopherhesse** [comment]
@pzhokhov do you know why this is happening now?

**Comment by ezanchi** [comment]
This is also happening to me using CarRacing-v0

**Comment by P3RI9** [comment]
> This is also happening to me using CarRacing-v0

Same issue faced to me. I've tried with `gym = 0.18.3 `and `gym = 0.17.3`

**Comment by amirmmi** [comment]
As the error says, you have to make Box boundaries using np.float32 data type, like the following example:
`
action_space = spaces.Box(low=np.array([-1, -1, -1], dtype=np.float32), high=np.array([1, 1, 1], dtype=np.float32), dtype=np.float32)
`
Not only set action_space into float32 data type but also set the boundary types to float32.

**Comment by xujinming01** [comment]
> 

@amirmmi That's helpful.

**Comment by xujinming01** [comment]
> As the error says, you have to make Box boundaries using np.float32 data type, like the following example: `action_space = spaces.Box(low=np.array([-1, -1, -1], dtype=np.float32), high=np.array([1, 1, 1], dtype=np.float32), dtype=np.float32)` Not only set action_space into float32 data type but also set the boundary types to float32.

@amirmmi That's helpful!
