### ISSUE TITLE
FetchReach - Why is action space 4-D?

### ISSUE THREAD

**Issue by RyanRizzo96** [openai/gym#1845]
The action space for `FetchReach-v1` is  `Box(4,)`. When I print the actions I get:

`[ 0.11746755 -0.56623757 -0.05967733  0.36495462]`

According to the HER paper, the first 3 dimensions specify the desired relative gripepr position at the next time step while the fourth dimension specifies the distance between the two fingers.

In FetchReach-v1, the two fingers are not used, so what does the fourth dimension represent?

**Comment by YeeCY** [comment]
I think it is meanless since the environment block the gripper and set the finger positions to 0.

https://github.com/openai/gym/blob/c0860592f51b53c00ce57e00cb3a9195943847d9/gym/envs/robotics/fetch_env.py#L80

**Comment by christopherhesse** [comment]
Thanks for answering this @YeeCY!
