### ISSUE TITLE
It's a question about the functionality of seed.

### ISSUE THREAD

**Issue by dxu23nc** [openai/gym#1846]
I noticed that in the gym/envs/atari/atari_env.py, it has a funtion called seed():`    
def seed(self, seed=None):
        self.np_random, seed1 = seeding.np_random(seed)
       ...... (Condider the length, I delete those lines of code.)
        return [seed1, seed2]
`
What is the functionality of the seed()? I saw it being called in the init().

Thanks in advance.

**Comment by albertcthomas** [comment]
the role of the `seed` method is to fix the seed of the random number generator used by the environment so that you can get reproducible results.

**Comment by christopherhesse** [comment]
Thanks for answering this @albertcthomas !
