### ISSUE TITLE
Segfaulting Unrelated Threads?

### ISSUE THREAD

**Issue by mharradon** [openai/gym#1847]
I've found what I believe to be quite the mysterious (and painful) bug.

A minimal reproducing example:

```
from threading import Thread
import faulthandler

import gym

faulthandler.enable()

def make_t2():
    print(1)

def make_t1():
    t = Thread(target=make_t2)
    t.start()

env = gym.make('MsPacman-v4')
#env = gym.make('CartPole-v0')

t = Thread(target=make_t1)
t.start()
```

I believe it's related to this issue: https://github.com/openai/atari-py/issues/52

Essentially, it appears that nesting of threads segfault if and only if `gym.make` has occurred. If you comment out that line the error goes away.

This issue appeared sometime since gym release 0.15.3 . The older versions don't seem to have this problem.

If I use faulthandler I can get:

```
 $ python error_demo.py
1
Fatal Python error: Segmentation fault

Thread 0x00007f6b01327700 (most recent call first):
  File "/root/anaconda3/lib/python3.7/threading.py", line 989 in _stop
  File "/root/anaconda3/lib/python3.7/threading.py", line 1282 in _shutdown
[1]    83051 segmentation fault (core dumped)  python error_demo.py
```

So, at least as I understand, it is not even gym code that is segfaulting - rather it is somehow indirectly causing other code to segfault.

I'm using Python3.7

**Comment by christopherhesse** [comment]
Does this happen with CartPole-v0 or just MsPacman-v4?  If it's just MsPacman, this may be an Arcade Learning Environment issue and you should file the issue here: https://github.com/mgbellemare/Arcade-Learning-Environment. (technically the error would be in atari-py, but atari-py is a clone of ALE)

**Comment by mharradon** [comment]
It's just on the Atari environments - I wasn't sure where would be best. Thanks!

**Comment by jkterry1** [comment]
@JesseFarebro

**Comment by JesseFarebro** [comment]
You can close this issue as this is being tracked upstream @ https://github.com/mgbellemare/Arcade-Learning-Environment/issues/341. I do need help reproducing this as I've failed to reproduce this issue so far.
