### ISSUE TITLE
Batch mode / human mode

### ISSUE THREAD

**Issue by olegklimov** [openai/gym#185]
We should agree on a common way for agent to say "I want fast batch mode" or "I want slow human mode".

In #168 (Remove sleep statement from DoomEnv render) @ppaquette proposed:

``` python
env = gym.make('DoomBasic-v0')
env.mode = 'human'
env.reset()
```

('fast' 70 fps, 'normal' 35 fps, 'human' human can play)

In #119 @jietang proposed:

``` python
env = gym.make('CartPole-v0')
env.configure(batch_mode=True)
```

And agree on the default, too. My thoughts is for simple programs and tutorial we should have human mode as default. But the paper says batch mode is the default. 

After we agree, I can fix all classic control and box2d.

**Comment by gdb** [comment]
Cool. Let's use the configure method, and pass in a "mode='human'" in
appropriate environments so we leave our options open for future modes, and
have it feel similar to render modes.

On Monday, June 13, 2016, Oleg Klimov <notifications@github.com> wrote:

> We should agree on a common way for agent to say "I want fast batch mode"
> or "I want slow human mode".
>
> In #168 <https://github.com/openai/gym/issues/168> (Remove sleep
> statement from DoomEnv render) @ppaquette <https://github.com/ppaquette>
> proposed:
>
> env = gym.make('DoomBasic-v0')
> env.mode = 'human'
> env.reset()
>
> ('fast' 70 fps, 'normal' 35 fps, 'human' human can play)
>
> In #119 <https://github.com/openai/gym/pull/119> @jietang
> <https://github.com/jietang> proposed:
>
> env = gym.make('CartPole-v0')
> env.configure(batch_mode=True)
>
> And agree on the default, too. My thoughts is for simple programs and
> tutorial we should have human mode as default. But the paper says batch
> mode is the default.
>
> After we agree, I can fix all classic control and box2d.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/openai/gym/issues/185>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAM7kSiWudX4pbv3QPZiOz0rCDNtFQOQks5qLWfmgaJpZM4I0YRJ>
> .
>


-- 
Sent from mobile

**Comment by ppaquette** [comment]
Agree that we need to standardize terminology.

My modes are 'fast', 'normal', 'human'

batch_mode == True  ==> 'fast' mode
batch_mode == False ==> 'normal' mode

The 'human' mode is a way for the researcher to actually play the environment to have a better idea of what it looks like and what variables are returned. Without that mode, the 43 commands in the action space and the 22 variables returned in the info dict. might be confusing.

**Comment by gdb** [comment]
What's the difference between normal and human, exactly? When would you
want to use normal but not human?

On Monday, June 13, 2016, Philip Paquette <notifications@github.com> wrote:

> Agree that we need to standardize terminology.
>
> My modes are 'fast', 'normal', 'human'
>
> batch_mode == True ==> 'fast' mode
> batch_mode == False ==> 'normal' mode
>
> The 'human' mode is a way for the researcher to actually play the
> environment to have a better idea of what it looks like and what variables
> are returned. Without that mode, the 43 commands in the action space and
> the 22 variables returned in the info dict. might be confusing.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/openai/gym/issues/185#issuecomment-225606951>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAM7kYR5djq5RbYIkRSFSNH8umn4vzPZks5qLXAngaJpZM4I0YRJ>
> .
>


-- 
Sent from mobile

**Comment by ppaquette** [comment]
normal = AI plays, renders at 35 fps (i.e. would be used to watch AI play)
human = Human plays the level to get better acquainted with level, commands, and variables

VizDoom calls the human mode 'spectator' mode, because the AI is supposed to learn from human, but I haven't implemented it that far. Human mode only prints the action, variables, and reward in the console for the researcher to have a better idea of the level dynamics.

**Comment by olegklimov** [comment]
Sorry if it's too invasive... I've created `_display_options` in environment, all parameters that belong to display_options are intercepted in common `configure()`, so all environments don't have to reimplement `_configure()`, and in fact match all the parameters of original call.

`_configure()` is still there, but now accept dict as only argument, so all environments don't have to share the same set of parameters.

@gdb do you like this?

**Comment by jietang** [comment]
@olegklimov, any updates here?

**Comment by olegklimov** [comment]
Now I'm attending Machine Intelligence Summit, Berlin, I'll reappear a few days later, attempt to solve this another way (create structure for display options, include it in environments that should have display options).

**Comment by jues** [comment]
I'm expecting the same feature, any updates here?

**Comment by olegklimov** [comment]
Let's kill this bug. 

Resolution is: don't call render("human") is training. That's all you need.
