### ISSUE TITLE
blackjack.py dealer busting not checked ?

### ISSUE THREAD

**Issue by fusiller** [openai/gym#1856]
Hi there,
from a newbie carefully reading the code to learn how to use your great environment.
It seems to me that the dealer can go bust without the player getting his reward for winning.
line 105
There is no is_bust() test and the cmp() function will return player loosing to a busted dealer.
In the comment though : " If the dealer goes bust the player wins."
Regards
Alexandre

**Comment by rhalbersma** [comment]
There is an `is_bust` check inside `score()` on line 35, which returns 0 for a busted hand. So a player who didn’t bust himself, will always win against a busted dealer.

**Comment by christopherhesse** [comment]
Are you sure there's no `is_bust` test?  `cmp` compares the output of `score` which seems to have that test: https://github.com/openai/gym/blob/master/gym/envs/toy_text/blackjack.py#L35

**Comment by christopherhesse** [comment]
Whoops should have hit refresh, thanks for answering @rhalbersma!
