### ISSUE TITLE
How to create Environment from already trained agent

### ISSUE THREAD

**Issue by mtsokol** [openai/gym#1860]
Hi! 

I have a question regarding `gym` usage. Sorry for asking here in issues section but `gym`s Gitter channel is not present anymore (or I couldn't find it). 

How can I create Environment from an already trained Environment?

For example I've performed many steps and I'm satisfied with the result.

Now I would like to create another agent based on this trained model, so the new agent will already have the knowledge from the previous one.

Is it possible to do something like this?:

```python
env = gym.make(trained_env)
```

Or to export this model/transition table that resides inside environment and create a new agent which will start with that knowledge?

[EDIT] Would `copy.deepcopy(env)` work?

**Comment by christopherhesse** [comment]
I think what you want is to save/load your trained agent.  Gym only handles the environment side though, which is not trained.  From the gym side you can create the same environment used for training and that should be fine.

For your agent, loading the trained agent depends on how you trained the agent which I am afraid is not covered by the `gym` library.  You should check the documentation for whatever training setup you are using.

**Comment by mtsokol** [comment]
@christopherhesse It's clear for me now, thank you for explanation! 

In my example I'm using `hill-a/stable-baselines` and found https://stable-baselines.readthedocs.io/en/master/guide/save_format.html which I will look into.
