### ISSUE TITLE
CUDA conflict when installing gym

### ISSUE THREAD

**Issue by pavlexander** [openai/gym#1865]
I am willing to install the `gym` using the conda, like so:
```
conda install -c powerai gym
```

Following error is shown:

> Collecting package metadata (current_repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: |
> Found conflicts! Looking for incompatible packages.
> This can take several minutes.  Press CTRL-C to abort./
> Examining @/win-64::__cuda==10.2=0:  33%|█████████████████████████████████████████████████████████████████████████████████▋                                                                                                                                                                   | 1/3 [00:00<00:00, 15.57it/s]-failed
> 
> UnsatisfiableError: The following specifications were found to be incompatible with each other:
> 
> Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your CUDA driver:
> 
>   - feature:/win-64::__cuda==10.2=0
>   - feature:|@/win-64::__cuda==10.2=0
> 
> Your installed CUDA driver is: 10.2

So it seems like gym is dependant on some particular CUDA version? Or it is conflicting with CUDA that is currently installed on my PC. **Unfortunately I was not able to find information anywhere, whether gym actually requires CUDA and what version exactly. So any advises on solving this issue are welcomed.**

`conda list anaconda$`

> packages in environment at C:\Users\xxxx\AppData\Local\Continuum\anaconda3:
> 
> Name                    Version                   Build  Channel
> anaconda                  custom                   py37_1

`conda info`

>      active environment : base
>     active env location : C:\Users\xxxx\AppData\Local\Continuum\anaconda3
>             shell level : 1
>        user config file : C:\Users\xxxx\.condarc
>  populated config files : C:\Users\xxxx\.condarc
>           conda version : 4.8.3
>     conda-build version : 3.18.11
>          python version : 3.7.7.final.0
>        virtual packages : __cuda=10.2
>        base environment : C:\Users\xxxx\AppData\Local\Continuum\anaconda3  (writable)
>            channel URLs : https://repo.anaconda.com/pkgs/main/win-64
>                           https://repo.anaconda.com/pkgs/main/noarch
>                           https://repo.anaconda.com/pkgs/r/win-64
>                           https://repo.anaconda.com/pkgs/r/noarch
>                           https://repo.anaconda.com/pkgs/msys2/win-64
>                           https://repo.anaconda.com/pkgs/msys2/noarch
>           package cache : C:\Users\xxxx\AppData\Local\Continuum\anaconda3\pkgs
>                           C:\Users\xxxx\.conda\pkgs
>                           C:\Users\xxxx\AppData\Local\conda\conda\pkgs
>        envs directories : C:\Users\xxxx\AppData\Local\Continuum\anaconda3\envs
>                           C:\Users\xxxx\.conda\envs
>                           C:\Users\xxxx\AppData\Local\conda\conda\envs
>                platform : win-64
>              user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.7 Windows/10 Windows/10.0.16299
>           administrator : True
>              netrc file : None
>            offline mode : False

**Comment by christopherhesse** [comment]
You should use `pip install gym` instead of `conda install` I believe, but make sure you did `conda install pip` first.

**Comment by mizkulg** [comment]
Thanks @christopherhesse this worked for me
