### ISSUE TITLE
Custom MuJoCo environment

### ISSUE THREAD

**Issue by CharlesAverill** [openai/gym#1870]
I'm trying to create a custom 3D environment using humanoid models. It doesn't seem like that's possible with mujoco being the only available 3D environments for gym, and there's no documentation on customizing them. Is there any way to customize the mujoco environments?

**Comment by christopherhesse** [comment]
I think you can customize mujoco enviroments, but you may also want to check out pybullet: https://github.com/openai/gym/blob/master/docs/environments.md#pybullet-robotics-environments

**Comment by OlalekanIsola** [comment]
i am trying to create a 3D environment for NAO robot. I tried creating a new environment but i get this errors:

Traceback (most recent call last):
  File "/home/ola/.local/lib/python3.5/site-packages/gym/envs/registration.py", line 121, in spec
    return self.env_specs[id]
KeyError: 'Nao-v1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 2, in <module>
    env = gym.make('Nao-v1')
  File "/home/ola/.local/lib/python3.5/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/home/ola/.local/lib/python3.5/site-packages/gym/envs/registration.py", line 89, in make
    spec = self.spec(path)
  File "/home/ola/.local/lib/python3.5/site-packages/gym/envs/registration.py", line 131, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: Nao-v1


I also tried replacing the NAO xml file with humanoid.xml in Humanoid.py, it only displays the humanoid.xml.

Can anyone help with a solution?

**Comment by RaghuSpaceRajan** [comment]
You can customise Mujoco environments by modifying/creating XMLs based on the Mujoco website [here](http://mujoco.org/book/XMLreference.html). There are further related pages there.

If you want to do it programmatically, then you would need to look up the internals of mujoco-py and how they correspond to the Mujoco internal data structures.

**Comment by ChrisSim01** [comment]
https://ashbabu.github.io/blog/2019/Custom-MuJoCo-Environment/ might help?

**Comment by denisgriaznov** [comment]
I encountered the same problem, and not finding a direct tutorial, I made a simple example of creating a Gymnasium environment from my own MuJoCo model. 

https://github.com/denisgriaznov/CustomMuJoCoEnviromentForRL 

If you have any questions, write!

**Comment by ChrisSim01** [comment]
Many thanks Denis
