### ISSUE TITLE
Resetting environment on Done

### ISSUE THREAD

**Issue by avandekleut** [openai/gym#1871]
This is a significant proposal, but should environments automatically reset themselves when done? The environments return the done-ness upon a call to `step`. Is there a significant reason to require the user to manually reset the environment? 

Is this something that is better handled by making use of `Wrapper`s?

**Comment by christopherhesse** [comment]
The value of manual resetting seems low, since people mostly just have bugs where they forgot to reset it.  So I think this is a reasonable idea, but also that we are unlikely to change the gym interface at this point.  Thanks for the suggestion!
