### ISSUE TITLE
"pip install gym" fails on freebsd

### ISSUE THREAD

**Issue by mwm** [openai/gym#188]
Trying to install gym on freebsd fails to find a large number of libraries, even though some (many? all?) are actually installed. It even appears to be looking in the right place (/usr/local/lib).

For some reason, it's removing and installing numpy from sources, which may be why things are breaking. In particular, I note the error "    non-existing path in 'numpy/distutils': 'site.cfg'". Could that be the issue?

Also, it's trying to reference things in a gcc48 library. Possibly it's getting confused because "cc" is 3.4.1, but  gcc is installed and available?

Or maybe I've just got the wrong set of dependencies installed? I couldn't find a list for them.

[gyminstall.txt](https://github.com/openai/gym/files/312937/gyminstall.txt)

**Comment by tlbtlbtlb** [comment]
Gym requires numpy >= 1.10.4, and you had 1.8.1 installed Building numpy from source is nontrivial because it requires gfortran. So probably better to upgrade using `cd /usr/ports/math/py-numpy && make install`

**Comment by mwm** [comment]
Um, I didn't try to install numpy from source; it looked like the pip install of gym was doing that. Possibly I misinterpeted what it was doing.

I had numpy 1.11 installed from pkg. If I ran python and just imported numpy, it found that version. For some reason, gym was finding a the 1.8 egg, uninstalling that (according to the log) then reinstalling it. Which is just odd.

Using pip to uninstall 1.8.1 solved the problem gym installs fine. Though it really needs either a "sudo" or "--user".

**Comment by jietang** [comment]
Yes pip was attempting to upgrade numpy (by installing from source).

Not sure why it was picking up on the wrong version of numpy. In the log the version of pip was also outdated (7.0.3 vs. 8.1.2) which may result in a different set of build steps (I believe the latest version uses the wheel format)
