### ISSUE TITLE
gym.spaces.Box allows arbitrary shape assignment, but the true value of shape does not change.

### ISSUE THREAD

**Issue by AnanthHari** [openai/gym#1880]
**Description:** After creation of a Box space, the shape variable _can_ be assigned a new value. For instance,
```python
>>> from gym.spaces import Box
>>> a = Box(low=0, high=1, shape=(2,3))
>>> a; a.low
Box(2, 3)
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)
>>> a.shape = (4,5)
>>> a; a.low
Box(4, 5)
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)
```

We can see that the representation of the Box object acknowledges the change in shape, but `box.low` is unchanged. The actual behavior is that the shape of the Box object remains unchanged even after simply assigning new value to `shape` attribute. (Also, it is now in an awkward state as both `a.contains(np.zeros((2,3)))` and `a.contains(np.zeros((4,5)))` do not return `True`).

This creates confusion to new users who might think that the change in `shape` attribute changes the shape of the underlying `Box` object. The misleading notion that changing the `shape` attribute changes the `Box`'s shape also comes from the fact that `low` and `high` input parameters might be scalars, and they could potentially be arranged in different shapes by assigning different `box.shape` values.

**Solution:** I propose the following solution. Store the shape of Box in an internal variable named `__shape__`, and use `shape` as a method, instead of an attribute. Use `@property ` decorator to use `box.shape` instead of `box.shape()` like this:
```python
@property
def shape(self):
    return self.__shape__
```
This ensure backward compatibility. Now, trying to assign a new shape value to `shape` attribute of Box fails, because `shape` is not a variable.
```python
>>> a = Box(low=0, high=1, shape=(2,3))
>>> a.shape = (5,1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: can't set attribute
```

We also need to patch up the base class in `space.py`. Change 
```python
self.shape = None if shape is None else tuple(shape)
```
as 
```python
if not hasattr(self, "shape") or self.shape is None:
    self.shape = None if shape is None else tuple(shape)
```
I can make a pull request if the bug/feature description warrants changing the current structure of `Box` space.

**Comment by jkterry1** [comment]
@AnanthHari I'm the maintainer of Gym now; mind making that PR?

**Comment by RedTachyon** [comment]
I made a PR for this, in the spirit of what OP suggested, but I think slightly simpler - the property is handled at the `Space` level.

The biggest complication I see is that custom spaces would have to be updated so that they define their own `self._shape` rather than `self.shape`. Is this a problem? And how often are custom spaces used in the first place?
