### ISSUE TITLE
Sampling numbers that sum to a constant from spaces.box

### ISSUE THREAD

**Issue by ckrk** [openai/gym#1881]
Description:
##########
I am developing a custom environment for gym. 
In my action space, I want to study strategic consequences when arbitrary dividing a fixed quantity Q into a (possibly fixed) number of parts. Hence, the action space is continuous and uses spaces.box.

I want to be able to draw several numbers a1, ..., aN and have the guarantee that they sum up to 
Q =  a1 + .... +aN.

I believe since spaces.box allows only for independent sampling, this is currently not possible.  

Example:
##########
Assume I want 3 samples from spaces.box that sum up to 5.
Assume I draw sample_1 from [0,5] and get 2.
Then sample_2 needs to be drawn from [0,5-sample_1]=[0,3], not from [0,5]!
Assume I draw sample_2=0.5
Finally sample_3 needs to be drawn from [0,5-sample_1-sample_2]=[0,2.5]

In contrast, box spaces has fixed limits. 
If using it 3 times in limits [0,5], we could get the sequence (3,3,5). 3+3+5 would exceed the limit 5 though, since the 2nd and 3rd sample do not know about the earlier results and hence can not respect the limit of 5. I believe that all othe spaces have similar problems.

Possible Use-Cases:
##########
- Dividing profits or flows
- Action spaces restricted by a capacity (storage, transport, etc...)
- Probability normalization (i.e. pick weights p1+p2+p3=1)

Suggestions and Questions:
##########
- Is there any known best practice to include this?

- If not I would ask for the inclusion of such a sampling mechanism

- I think the use-cases above are pretty general and should not be restricted to my problem

- I would like to avoid post-processing since this is really a property of the action space.
I am not sure how this interact with learning algorithms and whether it would "secretly" change the underlying probabilities. In the spirit of gym, these environment properties should be resolved within the environment and not touch on the algorithmic side for inter-comparability.

-I have already asked a [stack exchange question](https://ai.stackexchange.com/questions/20003/how-to-formulate-normalization-probability-conditions-on-state-action-spaces-in), that was not unanswered but up-voted. 
Therefore I believe, that my issue is not trivial.

**Comment by instance01** [comment]
Is drawing integers a requirement?

**Comment by ckrk** [comment]
@instance01 Thank you for your reply! Drawing integers is not required. I am working in a continuous setting, hence the drawn numbers can be arbitrary real numbers.

**Comment by instance01** [comment]
How about the following:

```
>>> box = spaces.Box(0, 1, shape=(1,10))
>>> sample = box.sample()
>>> sample
array([[0.56555617, 0.5769829 , 0.07108209, 0.10859283, 0.47241163,
        0.56022567, 0.4106281 , 0.9875782 , 0.13131236, 0.40297922]],
      dtype=float32)
>>> Q = 5
>>> sample = sample * Q / sample.sum()
>>> sample
array([[0.6595639 , 0.67289007, 0.08289748, 0.12664333, 0.55093676,
        0.6533474 , 0.47888348, 1.1517352 , 0.15313934, 0.46996316]],
      dtype=float32)
>>> sample.sum()
5.0
>>> sample.sum() == Q
True
```

The main interesting line is this one: `sample = sample * Q / sample.sum()`

**Comment by instance01** [comment]
Ah wait, I just saw that you want to avoid post-processing..

**Comment by instance01** [comment]
Also, you are right. The distribution may change (i.e. become non-uniform) if you're not careful (like my answer above).
More about that: https://stackoverflow.com/questions/8064629/random-numbers-that-add-to-100-matlab/8068956#8068956

**Comment by ckrk** [comment]
@instance01 Thank you for your input!  Surely, one could go for a similar solution as you propose, however it seems a bit like a work around. Your stackexchange perfectly shows what i am concerned about. Maybe the effect isnt even strong, but it is not easy for me to asess this apriori.
