### ISSUE TITLE
Possible memory leak LunarLander-v2

### ISSUE THREAD

**Issue by MatheusZickuhr** [openai/gym#1882]
After running this code:

```
import gym

env = gym.make('LunarLander-v2')
env.reset()
for i in range(3_000_000):
    # env.render()
    _, _, done, _ = env.step(env.action_space.sample())
    if done:
        env.reset()
env.close()
```

this is the memory-profiler result:

![image](https://user-images.githubusercontent.com/37124939/79352776-a739aa80-7f10-11ea-84d3-269a30fdae48.png)

I managed to reduce the memory leak by setting some fixtureDef as global variables, but did not fix the problem completly:

![image](https://user-images.githubusercontent.com/37124939/79354363-b1f53f00-7f12-11ea-9888-6d77dedd939b.png)

**Comment by christopherhesse** [comment]
Good find, could you try doing `self.world = Box2D.b2World()` in `_destroy()`?  It would be nice to verify that the environment is just not cleaning up box2d objects and that this is not some underlying memory leak in box2d.

**Comment by MatheusZickuhr** [comment]
> Good find, could you try doing `self.world = Box2D.b2World()` in `_destroy()`? It would be nice to verify that the environment is just not cleaning up box2d objects and that this is not some underlying memory leak in box2d.

 `self.world = Box2D.b2World()` did not fix it

**Comment by christopherhesse** [comment]
Hmm, this makes me think it's a box2d issue.

Does the following script reproduce the issue for you?

```
import gym
import resource

def main():
    env = gym.make('LunarLander-v2')
    for i in range(3_000_000):
        env.reset()
        ram_peak_python_mb=resource.getrusage(resource.RUSAGE_SELF).ru_maxrss // int(1e6)
        if i % 1000 == 0:
            print(ram_peak_python_mb)

if __name__ == "__main__":
    main()
```

If so, you could try producing the simplest lunar lander environment that still leaks.  It seems like if you have only the lander but don't add a fixture it does not leak.

**Comment by Zhehui-Huang** [comment]
I guess it should be the following code that caused the issue.
`            self.moon.CreateEdgeFixture(
                vertices=[p1,p2],
                density=0,
                friction=0.1)`
Cuz, if I disable these lines and running it. I got the following result.
![Screenshot from 2020-07-23 04-35-38](https://user-images.githubusercontent.com/30305127/88286675-f593dd80-cca5-11ea-9238-b8dc1a000dcb.png)

**Comment by jkterry1** [comment]
It's my understanding that this is fixed on master, but if people are still having problems let me know and I'll reopen.
