### ISSUE TITLE
Error importing OpenAI Gym env : gym.error.UnregisteredEnv: No registered env with id: vrp-v0 

### ISSUE THREAD

**Issue by niranj555** [openai/gym#1888]
Hi Github community,

I'm attempting to create a new Open AI environment with name 'vrp' . Following this link : https://medium.com/@apoddar573/making-your-own-custom-environment-in-gym-c3b65ff8cdaa

**My folder structure is:**
```
gym-vrp/
               gym_vrp/
                              envs/
                                       __init__
                                      vrp_env
               setup.py 
```             

My setup.py is:
```
from setuptools import setup

setup(name='gym_vrp',
      version='0.0.1',
      install_requires=['gym']  # And any other dependencies foo needs
)
```

My gym-vrp/gym_vrp/envs/ __init__ 
```
from gym.envs.registration import register
register(
    id='vrp-v0',
    entry_point='gym_vrp.envs:VrpEnv',
)
```
**Issue:**
After a sucessfull installation of the environment.
Im unable to make() my gym envirnment

**I try to do**
import gym
import gym_vrp
env = gym.make('vrp-v0')

**And it throws me an error:**
File "C:\Users\niran\Anaconda3\envs\vrp\lib\site-packages\gym\envs\registration.py", line 128, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: vrp-v0

I have followed numerous github solutions but none of it was able to solve this.

Can you guys help me with this error.

**Comment by christopherhesse** [comment]
It looks like you've messed up the `__init__.py` stuff, there should be two of those, one under `gym_vrp` and another under `envs`.  Please consult the article you linked.  You can add some print statements in each file to see if/when it is running.
