### ISSUE TITLE
Can I get access to the in-game audio in Atari games?

### ISSUE THREAD

**Issue by Cospui** [openai/gym#1890]

**Comment by Cospui** [comment]
I know that in `openai/retro` repo I can do this by call the function `env.em.get_audio()`. I'm wondering that if there's somethign like this in gym

**Comment by christopherhesse** [comment]
gym-retro does expose a gym interface, did you want to know if ALE, which provide the atari envs in this package does audio, or did you want to know if the audio can be used as an observation for your agent?

If it's the first, it seems like ALE does not support that: https://github.com/mgbellemare/Arcade-Learning-Environment/issues/183

If it's the second, then it should be possible by modifying the RetroEnv class in gym-retro, but it's not supported currently.

**Comment by Cospui** [comment]
I see, thanks a lot
