### ISSUE TITLE
Rendering Issues for grid world environments

### ISSUE THREAD

**Issue by THINK989** [openai/gym#1891]
Hello Everyone,
I am having trouble getting expected output from **env.render()** for grid world environments.

For example:-
```
>>> gym.make('FrozenLake-v0').render()

[41mS[0mFFF
FHFH
FFFH
HFFG
>>> gym.make('Taxi-v3').render()
+---------+
|[35mR[0m: | : :G|
| : | : : |
| :[43m [0m: : : |
| | : | : |
|Y| : |[34;1mB[0m: |
+---------+
```
I am using Windows 10, I am using anaconda prompt for running any of my codes,
**Python Version 3.7.7
Gym Version 0.17.1**

Now I do know these are referring to a color highlighting the location of the agent, terminal state, or other important states, but it is not rendering on my terminal.

For a reference, it should look like this:-
![image](https://user-images.githubusercontent.com/48655557/80216771-330fad00-865c-11ea-9aa9-cb0d1d05f733.png)

I don't know if it has anything to do with my terminal settings or a problem with the environment or some other problems. 

Thank You

**Comment by christopherhesse** [comment]
Unfortunately it looks like it that method doesn't work well with the windows terminal.  If you use a different terminal such as cmder, does it work?

**Comment by THINK989** [comment]
Cmder worked 
Thank You 
Although I am trying other shells
I will close the issue until then

**Comment by THINK989** [comment]
Although this comment is not that important now in case someone is looking into it which would be rare
I will still say it has nothing to do with the shell I use but rather an emulator I use which is kind of obvious. Though it didn't work on default cmd terminal or PowerShell or bash,
It worked on
1) cmder emulator and
2) new [Windows Terminal](https://www.microsoft.com/en-in/p/windows-terminal-preview/9n0dx20hk701)
3) Jupyter Notebook
4) Spyder
It is not that big of a problem so I didn't dive much deep into it :smile:
