### ISSUE TITLE
NameError: name 'base' is not defined

### ISSUE THREAD

**Issue by deinega** [openai/gym#1898]
Hello.

I am trying to run:

```
import gym
env = gym.make("CartPole-v1")
obs = env.reset()
env.render(mode="rgb_array")
```

As a result, I am getting:

NameError                                 Traceback (most recent call last)
<ipython-input-20-595a5fbc2c5c> in <module>
----> 1 img = env.render(mode="rgb_array")

/usr/local/lib/python3.6/dist-packages/gym/core.py in render(self, mode, **kwargs)
    233 
    234     def render(self, mode='human', **kwargs):
--> 235         return self.env.render(mode, **kwargs)
    236 
    237     def close(self):

/usr/local/lib/python3.6/dist-packages/gym/envs/classic_control/cartpole.py in render(self, mode)
    148 
    149         if self.viewer is None:
--> 150             from gym.envs.classic_control import rendering
    151             self.viewer = rendering.Viewer(screen_width, screen_height)
    152             l,r,t,b = -cartwidth/2, cartwidth/2, cartheight/2, -cartheight/2

/usr/local/lib/python3.6/dist-packages/gym/envs/classic_control/rendering.py in <module>
     25 
     26 try:
---> 27     from pyglet.gl import *
     28 except ImportError as e:
     29     raise ImportError('''

/usr/local/lib/python3.6/dist-packages/pyglet/gl/__init__.py in <module>
    233 elif compat_platform == 'darwin':
    234     from .cocoa import CocoaConfig as Config
--> 235 del base  # noqa: F821
    236 
    237 

NameError: name 'base' is not defined

How this issue can be resolved?
Thank you!

**Comment by christopherhesse** [comment]
What version of pyglet do you have?  `pip show pyglet`

**Comment by deinega** [comment]
`pip show pyglet
`

```
Name: pyglet
Version: 1.5.0
Summary: Cross-platform windowing and multimedia library
Home-page: http://pyglet.readthedocs.org/en/latest/
Author: Alex Holkner
Author-email: Alex.Holkner@gmail.com
License: BSD
Location: /usr/local/lib/python3.6/dist-packages
Requires: future
Required-by: gym
```

**Comment by ItsAlex42** [comment]
Don't forget to use python3

**Comment by deinega** [comment]
I am using python3. Please see this line in my previous reply:  `Location: /usr/local/lib/**python3.6**/dist-packages`

**Comment by ItsAlex42** [comment]
why are you using pip and not pip3?

**Comment by deinega** [comment]
I was following request from @christopherhesse :
https://github.com/openai/gym/issues/1898#issuecomment-622565974

**Comment by ItsAlex42** [comment]
It's working for me. I am using pyglet 1.5.5

**Comment by ItsAlex42** [comment]
use ```pip3 install pyglet --upgrade```

**Comment by deinega** [comment]
`ERROR: gym 0.17.1 has requirement pyglet<=1.5.0,>=1.4.0, but you'll have pyglet 1.5.5 which is incompatible.`

**Comment by deinega** [comment]
pip3 shows that 0.17.1 is the latest version of gym
`pip3 install gym  --upgrade
Requirement already up-to-date: gym in /usr/local/lib/python3.6/dist-packages (0.17.1)
`

**Comment by ItsAlex42** [comment]
Idk how to help, I mean it's working with pyglet 1.5.5

**Comment by deinega** [comment]
what is your version of gym?

**Comment by ItsAlex42** [comment]
Oh you have to upgrade gym

**Comment by ItsAlex42** [comment]
0.17.1

> what is your version of gym?

**Comment by deinega** [comment]
pip3 says that I already have latest gym

**Comment by ItsAlex42** [comment]
weird

**Comment by deinega** [comment]
I updated pyglet to 1.5.5. Still the same error `NameError: name 'base' is not defined`

**Comment by pierluigi-failla** [comment]
Try to make a clean python 3 environment (using pyenv or conda as you prefer) and install gym with `pip install 'gym[all]'`.

**Comment by christopherhesse** [comment]
I think @pierluigi-failla has a good idea here, and just make a clean environment to try it out in.  I'm not able to reproduce this issue, and I don't see how that pyglet code is supposed to ever work, so not clear why it works for me.

**Comment by sophronesis** [comment]
Same issue here. Tried to follow this manual
https://nbviewer.jupyter.org/github/patrickmineault/xcorr-notebooks/blob/master/Render%20OpenAI%20gym%20as%20GIF.ipynb

pip3 freeze result here
https://gist.github.com/sophronesis/c7b351cb5baf0e096e6454abec46a695

**Comment by christopherhesse** [comment]
I tried that notebook but I was unable to reproduce the error in google colab: https://colab.research.google.com/drive/17kpHsCZWd3DS8pHbT0r5icosRMU_459h?usp=sharing

Am I missing something important from this reproduction?

**Comment by ayjabri** [comment]
> I tried that notebook but I was unable to reproduce the error in google colab: https://colab.research.google.com/drive/17kpHsCZWd3DS8pHbT0r5icosRMU_459h?usp=sharing
> 
> Am I missing something important from this reproduction?

I have the same problem, so I tried your google colab. It returns the same error
<img width="915" alt="Error" src="https://user-images.githubusercontent.com/58453150/83396658-513e9a80-a3ca-11ea-90a5-8acdce557f00.png">

**Comment by vincent-163** [comment]
I executed the following code directly in a Jupyter Lab environment:
```python
import pyglet.gl
```
And it gives `NoSuchDisplayException: Cannot connect to "None"`. It makes sense since my Jupyter Lab does not have any X server at all.
Then I imported it again:
```python
import pyglet.gl
```
This time it shows the error `NameError: name 'base' is not defined`.
I suppose `pyglet` requires an X display to work at all. Does `pyglet` work without an X display, like using egl?

**Comment by shanmukha-MaiL** [comment]
> EDIT2: I've worked around the problem by launching Xvfb and setting DISPLAY to :0 while launching Jupyter Lab. Now everything just works.
Hey can you please explain what do you mean by this ? Do you mean setting visible = 0 inside Display() ?

**Comment by Addi-11** [comment]
I had the same issue working in google colab, locally it seems to be working just fine. Can anyone explain the cause behind it and ways to fix it? <br>I think it might have to do with colab unable connect to x server.

**Comment by shanmukha-MaiL** [comment]
Hey, @Addi-11 I have figured out a way to do it on kaggle. Not sure on colab though. If you want the steps to make it work on kaggle then you can go through my kernel [here](https://www.kaggle.com/shanmukhamail/rl-tutorial). Hope this helps !!!

**Comment by Addi-11** [comment]
> Hey, @Addi-11 I have figured out a way to do it on kaggle. Not sure on colab though. If you want the steps to make it work on kaggle then you can go through my kernel [here](https://www.kaggle.com/shanmukhamail/rl-tutorial). Hope this helps !!!

Thanks, @shanmukha-MaiL, I will surely check it out.

**Comment by srsani** [comment]
I've managed to get an image in a jupyter notebook by adding the following to my imports: 

from pyvirtualdisplay import Display
_display = Display(visible=False, size=(1400, 900))
_ = _display.start() 

[here](https://stackoverflow.com/questions/53472940/nameerror-name-base-is-not-defined-openai-gym)

**Comment by surak** [comment]
> from pyvirtualdisplay import Display
> _display = Display(visible=False, size=(1400, 900))
> _ = _display.start()

> [here](https://stackoverflow.com/questions/53472940/nameerror-name-base-is-not-defined-openai-gym)

This works, just have in mind that you need XVFB for that.

**Comment by nawinaswin** [comment]
> > EDIT2: I've worked around the problem by launching Xvfb and setting DISPLAY to :0 while launching Jupyter Lab. Now everything just works.
> 
> Hey can you please explain what do you mean by this ? Do you mean setting visible = 0 inside Display() ?
like this

_display = pyvirtualdisplay.Display(visible=0, size=(1400, 900))
_ = _display.start()

**Comment by rauf-source** [comment]
``# Here is an alternative
## This works for kaggle notebooks
https://www.kaggle.com/toshikazuwatanabe/how-to-show-cartpole 
I found this notebook VERY helpful. After soooo much headache with pygl this kinda works. Thanks to the person who did it.. quoting that person's code. 
```
!apt-get install python-opengl -y
!pip install pyvirtualdisplay 
```

```
import gym
import os
import matplotlib.pyplot as plt
from pyvirtualdisplay import Display

display = Display(visible=0, size=(1400, 900))
display.start()
#os.environ["DISPLAY"] = ":" + str(display.display) + "." + str(display.screen)

```

```
env = gym.make("CartPole-v1")

env.reset()
plt.imshow(env.render('rgb_array'))
plt.grid(False)
```

# If you want to show animations in the notebook you can make a class using matplotlib animtaions, add frames to it then animate.
I wrote this class myself after seeing how it works from the given kaggle notebook.. not perfect so check for yourself

```
class RenderAnim:
    from pyvirtualdisplay import Display
    import matplotlib.pyplot as plt
    from matplotlib import animation, rc

    def __init__(self, env):
        #         initialize frame with empty list
        self.frame = []
        self.fig = self.plt.figure()

#     initializing display
        self.display = self.Display(visible=0, size=(1400, 900))
#         display.start()
#         self.plt.imshow(env.render('rgb_array'))
        self.plt.grid(False)
#    adding frame to compose animation

    def add_frame(self, frame):
        self.frame.append(frame)
#  animating

    def animate(self):
        self.display.start()
        an = self.animation.ArtistAnimation(
            self.fig, self.frame, interval=100, repeat_delay=1000, blit=True)
        self.rc('animation', html='jshtml')
        return an
```
