### ISSUE TITLE
I have tensorflow2 installed and cuda driver updated

### ISSUE THREAD

**Issue by quantwin** [openai/gym#1900]
UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versionsThe following specifications were found to be incompatible with your CUDA driver:

  - feature:/win-64::__cuda==11.0=0
  - feature:|@/win-64::__cuda==11.0=0

Your installed CUDA driver is: 11.0

**Comment by christopherhesse** [comment]
gym shouldn't depend on cuda or tensorflow, are you sure this is a gym error?

**Comment by quantwin** [comment]
Maybe it's my conda source problem.

Use 
`conda install -c conda-forge gym`

It worked
