### ISSUE TITLE
How to check the actual meaning for action space?

### ISSUE THREAD

**Issue by Donny-Boy** [openai/gym#1901]
Hello! Could you please tell me how can I check what does the action space of a particular environment actually mean? I am now trying to implement pacman and I know there are 9 actions available for pacman but what do those 9 moves actually stand for?

**Comment by christopherhesse** [comment]
I'm afraid those are environment specific.  For ALE envs, I believe there is a `get_action_meanings()` method on the underlying environment that you can call.
