### ISSUE TITLE
I have a code for simulating a robot dog using pybullet. Which environment can be used to create a robotdog in gym?

### ISSUE THREAD

**Issue by addy1997** [openai/gym#1902]
Link to my repo - https://github.com/addy1997/Reinforcement-Learning-with-gym/blob/master/robotdog.py

**Comment by pierluigi-failla** [comment]
You may want to take a look to this: https://github.com/openai/gym/blob/master/docs/creating-environments.md to have an hint about creating your own envs.

**Comment by addy1997** [comment]
@pierluigi-failla yes I went through the link but I wanted to know Has robot dog been created by anybody in the environment?

**Comment by pierluigi-failla** [comment]
@addy1997 not sure about it, but I do not think so. Try to take a look to all classes defined in `gym.envs`
