### ISSUE TITLE
Unable to change model parameter in the classic_control environments

### ISSUE THREAD

**Issue by andretag** [openai/gym#1907]
I am working with the CartPole-v1 environment and I am trying to change some of the model parameters (such as `force_mag`) in order to test the robustness of my algorithms w.r.t model variations. I am trying to do so with the following code: 
```
env = gym.make('myCartPole-v1)
env.force_mag = -10.0 # nominal is +10.0
```
but I do not see any change in the model behavior, while testing it with my learnt policy (which should fail/worsen, but it does not). Nothing happens when changing other parameters (e.g. 
 `masscart`, `length`...). Am I missing something? What is the best way to produce local changes to the models?

**Comment by christopherhesse** [comment]
You're probably not setting the property on the actual environment, but a wrapper, what happens if you set it on `env.unwrapped` instead of `env`?

**Comment by andretag** [comment]
Thank you @christopherhesse, adding the `env.unwrapped` (for example 'env = gym.make('myCartPole-v1).unwrapped' solved the problem.
