### ISSUE TITLE
The observation of fetchreah_env

### ISSUE THREAD

**Issue by 13350068164** [openai/gym#1911]
1. For example ,the obs in fetchreah_env. Why the observation include the grriper_velp ,gripper_vel,gripper_state  instead of the angle of each joint?
2. And in fetchreah_env,i don't konw the gripper_vel and gripper_state really mean,because the gripper doesn't need to open or close.

Thank you for your help.

**Comment by 13350068164** [comment]
And I try change obs in fetchreach_env.
Like this :obs = grip_pos.
Just the xyz of the grip,and use HER to train a model ,the success rate after 10 epochs is 1.
Could anybody help me and tell me why.

**Comment by spitis** [comment]
Your first post: (1) Why not? That's just how it's defined. (2) They are extraneous. 
Your second post: FetchReach is easy. You don't need velocity info to solve it.

**Comment by Amritpal-001** [comment]
@13350068164  gripper needs to open or close, depending on the environment you use.  For Fetch reacher, slider, pusher - the gripper is blocked. But in PickAndPlace - the gripper is needed.
If you look into source code you can find valuable info there. Or you can check out my article on Fetch environments by OpenAI [https://link.medium.com/CV6la7YfV7](url) , I hope it's helpfull.

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
