### ISSUE TITLE
`flatdim` for `MultiDiscrete` is inconsistent

### ISSUE THREAD

**Issue by araffin** [openai/gym#1915]
Related: https://github.com/DLR-RM/stable-baselines3/pull/13#issuecomment-628078922

The implementation in https://github.com/openai/gym/pull/1319 does not treat `Discrete` and `MultiDiscrete` spaces the same way.
- for `Discrete`, one hot encoding is assumed:
https://github.com/openai/gym/blob/b2727d6fd396f7fe2b19a541ef3a6ea47559cdb3/gym/spaces/utils.py#L21-L22
- for `MultiDiscrete`, the shape (here number of sub-spaces) is used:
https://github.com/openai/gym/blob/b2727d6fd396f7fe2b19a541ef3a6ea47559cdb3/gym/spaces/utils.py#L29-L30

**Comment by christopherhesse** [comment]
Seems like that should be `np.sum` and also do one-hot encoding to be consistent.  Thoughts @pzhokhov?

**Comment by jkterry1** [comment]
@araffin interested in doing a PR to fix this?

**Comment by araffin** [comment]
>@araffin interested in doing a PR to fix this?

I won't have time before some weeks to submit a proper PR (including tests).
For the record, SB3 has currently a monkey patch: https://github.com/DLR-RM/stable-baselines3/blob/master/stable_baselines3/common/preprocessing.py#L171

**Comment by jkterry1** [comment]
I'm closing this in favor of the open PR so I can keep track of what all is going on
