### ISSUE TITLE
Significance of obs in BipedalWalker-v3 as opposed to BipedalWalker-v2? [question]

### ISSUE THREAD

**Issue by philippwulff** [openai/gym#1920]
So I found an explanation of what the obs and actions represent in the BipedalWalker-v2 env here: [doc](https://github.com/openai/gym/wiki/BipedalWalker-v2).

However the min and max values of the obs (as mentioned in the doc) values are exceeded in BipedalWalker-v3, so I am unsure if the obs from the doc (which are for v2) still refer to the same obs in v3. Also v2 cannot be loaded anymore using
`env = gym.make('BipedalWalker-v2')`.

Do you know if the explanation from the link also corresponds to the obs in v3 correctly? In that case why are the min and max values exceeded in v3? 

Also, do you know a good way of finding out, which value in the obs array corresponds to what in the env?

**Comment by philippwulff** [comment]
This google colab shows the issue:

https://colab.research.google.com/gist/philippwulff/852587ce6c6bc2a7251fb1b98012f8d2/bipedalwalker-v3-obs-values-do-not-match-v2-doc.ipynb

**Comment by christopherhesse** [comment]
You'll have to use an old version of gym if you want the v2 version of the environment.  Could you make the same chart for the v2 version?  I'm suspicious that the v2 version also does not match the doc.

The v3 version is going to have different observations, but it looks like it's only supposed to affect lidar obs (supposedly 14-23): https://github.com/openai/gym/commit/2d247dc93a8c98360ebeb6a3807a9b3d945424ee

**Comment by philippwulff** [comment]
[This](https://colab.research.google.com/gist/philippwulff/895f36147d9814bed4a2ecd57bf68ae4/bipedalwalker-v2-obs-values-matching-the-doc.ipynb) is the new colab for the v2.

It seems only the hull_angle (obs_0) value does not match the doc, because it also has negative values.

I wonder whether the angles are measured in radians or degrees. Do you know which one it is? From the magnitude of the values I would assume it must be Radians. 

I am currently writing a script which record the data from a pretrained rl-baselines-zoo model, which shows totally different values. But maybe I made a mistake there.
