### ISSUE TITLE
pyglet.gl.lib.GLException: b'invalid enumerant'

### ISSUE THREAD

**Issue by zzu0654** [openai/gym#1921]
Hi!
when i run the code : image_data = pyglet.image.get_buffer_manager().get_color_buffer().get_image_data()
the error pyglet.gl.lib.GLException: b'invalid enumerant'  always appear.
I have kept trying other methods and searching for several days, however, none of them work for me.
Do you have any ideas?
Thanks!

**Comment by christopherhesse** [comment]
What version of pyglet do you have?  Also does `glxgears` work?

**Comment by jkterry1** [comment]
Closed due to inactivity
