### ISSUE TITLE
Usage of Group 4 in Hand - MuJoCo XML

### ISSUE THREAD

**Issue by aswinkumar1999** [openai/gym#1927]
I am learning MuJoCo modeling  , I was going through the MJCF files of the Hand robot and noticed that in [robotics/assets/hand/robot.xml](https://github.com/openai/gym/blob/master/gym/envs/robotics/assets/hand/robot.xml/) lots of geoms used the class `DC_HAND` which is declared as group 4 in [shared.xml](https://github.com/openai/gym/blob/master/gym/envs/robotics/assets/hand/shared.xml). 

I understand I can enable them in the MuJoCo simulator by toggling the group settings , but I don't understand the reasoning behind them. What is the purpose of group 4 ? Why we do need `robot0:C_xyz` when we have `robot0:V_xyz`.

I found a [similar question](http://www.mujoco.org/forum/index.php?threads/visualization-group.3935/) in the MuJoCo forum , but it did not seem to answer my question.

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
