### ISSUE TITLE
How can I install gym for spinningup with mujoco-py installed?

### ISSUE THREAD

**Issue by hexi519** [openai/gym#1931]
gym's latest version has dropped support for mujoco-py 2.0, so I have to install mujoco-py 1.5.0 which requires python 3.5 , while spinningup needs python 3.6 or greater ,which I found out when I tried to install spinningup with python 3.5 and got report as below:
```
Obtaining file:///home/hesy/pro/spinningup
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/hesy/pro/spinningup/setup.py", line 7, in <module>
        + "Please install it before proceeding."
    AssertionError: The Spinning Up repo is designed to work with Python 3.6 and greater.Please install it before proceeding.
```

Any idea to help?

**Comment by christopherhesse** [comment]
You could install mujoco-py 2.0 anyway, but be warned that the results you get may not be comparable with mujoco-py 1.50.  Does that work if you try it?

I don't see any requirement that mujoco-py 1.50 requires python 3.5, and I think the tests install mujoco-py 1.50 in python 3.7.  Are you certain that mujoco-py 1.50 requires python 3.5?

**Comment by hexi519** [comment]
Do you mean install mujoco-py 2.0 with mujoco150 by "You could install mujoco-py 2.0 anyway"？

The Readme on [mujoco-py 1.50.1.1](https://github.com/openai/mujoco-py/tree/1.50.1.1) tells that it requires python 3.5.2.

**Comment by christopherhesse** [comment]
I'm not certain if mujoco-py 2.0 supports mujoco150, I just meant that you could install mujoco-py 2.0 despite the warning and it should mostly work.  It used to work, but there were apparently minor differences in the environments so gym requires the old mujoco-py.

You linked to mujoco-py 1.50.1.1, not 1.50.1.68, which seems to be the most recent released version.

**Comment by hexi519** [comment]
Thanks for your remind of installing mujoco-py1.50.1.68 which can support python3.6 instead of 1.50.1.1. I referred to [openai/mujoco-py](https://github.com/openai/mujoco-py) and just saw new's tag of 1.50.1.x as 1.50.1.1, but with your help I successes. Thanks a lot! For anyone need help, you can get more detailed info on [my blog](https://blog.csdn.net/Hesy_H/article/details/106352895) :p
