### ISSUE TITLE
XIO:  fatal IO error 0 (Success) on X server ":99"

### ISSUE THREAD

**Issue by leocus** [openai/gym#1933]
Hi,
I'm trying to evolve a controller for the "CarRacing-v0" environment on a headless server.

I use xvfb-run to simulate a display.
It seems to work, but after some iterations, i get the following error:

~~~~
XIO:  fatal IO error 0 (Success) on X server ":99"
      after 11393 requests (11393 known processed) with 3 events remaining.
~~~~

Can someone explain me how to run this in an headless server (If possible, without having to install programs such as xvfb-run)?

**Comment by christopherhesse** [comment]
xvfb-run is sort of the main way to do this.  The other way is to run a full X server, which is more of a pain than xvfb-run.

It's possible to make 2D/3D environments that do not require an X server at all (for instance https://github.com/christopher-hesse/computer-tennis) but that requires potentially significant changes to the code and also I've only tested it on a small number of linux machines.
