### ISSUE TITLE
Comment mistake in classic_control/cartpole.py

### ISSUE THREAD

**Issue by dskart** [openai/gym#1934]
In "gym/gym/envs/classic_control/cartpole.py" I think there is a little comment mistake.

at the end of the class docstring you have this paragraph: 
```
Episode Termination:
        Pole Angle is more than 12 degrees.
        Cart Position is more than 2.4 (center of the cart reaches the edge of
        the display).
        Episode length is greater than 200.
        Solved Requirements:
        Considered solved when the average reward is greater than or equal to
        195.0 over 100 consecutive trials.
```

I think what is meant on the second to last line is "average return" instead of "average reward".

this is how it should be:
```
Episode Termination:
        Pole Angle is more than 12 degrees.
        Cart Position is more than 2.4 (center of the cart reaches the edge of
        the display).
        Episode length is greater than 200.
        Solved Requirements:
        Considered solved when the average return is greater than or equal to
        195.0 over 100 consecutive trials.
```

Very possible I could also be wrong, but this did make me confused for a few minutes.

:)

**Comment by BSVogler** [comment]
The returned value is the reward, as every cycle returns the reward. I am not sure if the usage of "return" as a noun in this context is correct English.

**Comment by dskart** [comment]
Correct me if I am wrong, but from my understanding, the reward only depends on the current state, the action taken, and the next step. So here for the cart pole, the reward is either always 1 or 0 at each step.

the cumulative reward for a trajectory is normally called either the undiscounted return or the discounted return and just return for short.

Here each trial corresponds to a trajectory and therefore we are looking at the cumulative reward (that is sometimes named just return).

the spinningup page from open AI as a section about reward and return that explains what I am trying to say better than I do.
https://spinningup.openai.com/en/latest/spinningup/rl_intro.html#reward-and-return

Maybe instead of the word "return" using "cumulative reward" would be more meaningful.

**Comment by BSVogler** [comment]
Ah, I have not noticed this terminology before. Regarding the linked openAI documentation your proposed change is correct. It is also the terminology in Sutton and Barto. However, it is only loosely defined as "some specific function of the reward function". As this concrete function implementation is not specified per experiment, I think "cumulative reward" is more self-explanatory.

**Comment by christopherhesse** [comment]
I think `return` may be the correct term here, want to make a PR?
