### ISSUE TITLE
Frozen lake

### ISSUE THREAD

**Issue by randhawp** [openai/gym#1935]
There is a bug / issue in the Frozen lake, action probability ( when is_slippery == True).
`li.append((1.0/3.0, newstate, rew, done))`
The sum of the probabilities for all the 4 actions should be 1
The code returns 0.333 *4 most of the time.

When the following is called in a loop (for for actions)
print(env.P[0][0][0][0])
print(env.P[0][1][0][0])
print(env.P[0][2][0][0])
print(env.P[0][3][0][0])

It returns
(0.3333333333333333, 0, 0.0, False)
(0.3333333333333333, 0, 0.0, False)
(0.3333333333333333, 4, 0.0, False)
(0.3333333333333333, 1, 0.0, False)

Is this is a valid call ?

Also why does for e.g print(env.P[6])  return 12 possible combinations (when is_slippery==True)
{0: [(0.3333333333333333, 2, 0.0, False), (0.3333333333333333, 5, 0.0, True), (0.3333333333333333, 10, 0.0, False)], 1: [(0.3333333333333333, 5, 0.0, True), (0.3333333333333333, 10, 0.0, False), (0.3333333333333333, 7, 0.0, True)], 2: [(0.3333333333333333, 10, 0.0, False), (0.3333333333333333, 7, 0.0, True), (0.3333333333333333, 2, 0.0, False)], 3: [(0.3333333333333333, 7, 0.0, True), (0.3333333333333333, 2, 0.0, False), (0.3333333333333333, 5, 0.0, True)]}

**Comment by Fgrueter** [comment]
Every action in one direction has a probability to go in an adjacent direction, e.g. when you go left, it could also go up or down, but not right. So 0.333 doesent say where it could go. It says how likely it was to end in the new state after your action. Thats why you get an 1 as probability, while you are in a whole. 
And P[6] has not 12 combinations, it has just 4. They all have there one index 0,1,2,3 and return the possible outcomes. The first "0:" means action left, so you can end in the state 5 (what is actually left) and the states 2 and 10, which are above and under 6. 
Its this first part:  "0: [(0.3333333333333333, 2, 0.0, False), (0.3333333333333333, 5, 0.0, True), (0.3333333333333333, 10, 0.0, False)],"
I hope I could clear some things up. :) I was also really confused about this probabilitys at the beginning.

**Comment by randhawp** [comment]
Thank you. That clear up.
