### ISSUE TITLE
pyglet requires an X server with GLX

### ISSUE THREAD

**Issue by ayjabri** [openai/gym#1937]
I'm trying to run CartPol on Google cloud server with GPU, but every time I render the environment to get a tensor of the state it returns this error
`pyglet requires an X server with GLX`

can you please help

**Comment by christopherhesse** [comment]
I don't think you need to render the environment to get a tensor of the state, are you rendering it to get a screenshot?  And if so, what X server are you running to make that work?

**Comment by jkterry1** [comment]
Closed due to inactivity
