### ISSUE TITLE
custom class or a string as env.observation_space in custom gym environment

### ISSUE THREAD

**Issue by saikrishna-1996** [openai/gym#1945]
can I have a custom class or a string as env.observation_space in my custom environment? right now, it throws an error at env.reset(). 

If I can use a string, how do I define the env.observation_space?

even better, if I can use my custom class, how do I define env.observation_space? 

I think there is no way around without defining it because env.reset() and gym.vector.make() are throwing errors ?

**Comment by christopherhesse** [comment]
What error do you get?  Do you have an example script that produces the error?

**Comment by bionicles** [comment]
```
import numpy as np
import string
import random
import gym


class String(gym.Space):
    def __init__(
                self,
                length=None,
                min_length=1,
                max_length=180,
                min=0,
                max=127
            ):
        self.length = length
        self.min_length = min_length
        self.max_length = max_length
        self.letters = string.ascii_letters + " .,!-"

    def sample(self):
        length = random.randint(self.min_length, self.max_length)
        string = ""
        for i in range(length):
            letter = random.choice(self.letters)
            string += letter
        return string

    def contains(self, x):
        return type(x) is "str" and len(x) > self.min and len(x) < self.max
```

**Comment by bionicles** [comment]
^^^ we could upgrade the "contains" to check if the letters in the x match the allowed letters

this would be good for base imo, for NLP + RL tasks (text adventure games!)

**Comment by bionicles** [comment]
```
    def contains(self, x):
        is_a_string = type(x) == "str"
        correct_length = self.min_length < len(x) < self.max_length
        correct_letters = all([l in self.letters for l in x])
        return is_a_string and correct_length and correct_letters
```

**Comment by saikrishna-1996** [comment]
Thanks @bionicles !

I added it to gym.spaces.smiles.py (I have used class name `Smiles` instead of `String`) 

In my environment, I added `from gym.spaces.smiles import Smiles` because directly using `self.observation_space = spaces.Smiles()`  (in the spirit of `self.action_space = spaces.Box`) is throwing an error that `AttributeError: module 'gym.spaces' has no attribute 'Smiles'.

Anyways `from gym.spaces.smiles import Smiles`.and `self.observation_space = Smiles()` resolved that issue. But how do I handle vector environments (to be able to use AsyncVectorEnv() for simultaneously spawning multiple environments) ? It is currently throwing the following error:
```
gym-apollo/gym/vector/utils/spaces.py", line 43, in batch_space
    raise NotImplementedError()
```
when I do gym.vector.make('myenv-v0', num_envs=5)

The error is because we do not have any batch_space_smiles() function here: https://github.com/openai/gym/blob/master/gym/vector/utils/spaces.py#L9

What would this function look like ? Because I cannot think of a way to decompose into something like `return Box(low=0, high=1, shape=(n,) + space.shape, dtype=space.dtype)` for my Smiles (string)
