### ISSUE TITLE
InterpretabilityCartpoleObservations-v0 environment runtime warning

### ISSUE THREAD

**Issue by arushir** [openai/gym#195]
Taking a single step with a random action in the InterpretabilityCartpoleObservations-v0 environment, generates the following error:

_RuntimeWarning: invalid value encountered in greater_equal
return x.shape == self.shape and (x >= self.low).all() and (x <= self.high).all()
[2016-06-14 23:08:07,331] Action '(0, array([ 0.89130833,         nan,  0.29987182,         nan]), array([ 1.18621149,         nan, -0.16961701,         nan]), array([-2.18249957,         nan,  0.26152186,         nan]), array([-1.02926596,         nan, -0.13622267,         nan]), array([-1.26488122,         nan, -0.30129903,         nan]))' is not contained within action space 'Tuple(Discrete(2), Box(4,), Box(4,), Box(4,), Box(4,), Box(4,))'._

Repro: 
import gym
env = gym.make('InterpretabilityCartpoleObservations-v0')

observation = env.reset()
action = env.action_space.sample()
observation, reward, done, _ = env.step(action)

**Comment by arushir** [comment]
This is no longer an issue with the latest pull. The environment was also renamed to 'PredictActionsCartpole-v0.'

**Comment by arushir** [comment]
Sorry, looking again I believe it was renamed to 'PredictObsCartpole-v0' instead of 'PredictActionsCartpole-v0,' and the issue still exists with the observation environment.

**Comment by jietang** [comment]
@RafaelCosman can you take a look?

**Comment by RafaelCosman** [comment]
Looking at this now...

**Comment by RafaelCosman** [comment]
Yep, @arushir, I reproduced the problem. Thanks for pointing this out.

**Comment by RafaelCosman** [comment]
@jietang @arushir, thanks for bringing this to my attention. Just submitted a PR which fixes this: https://github.com/openai/gym/pull/210
