### ISSUE TITLE
Pong paddles have momentum

### ISSUE THREAD

**Issue by david-donofrio** [openai/gym#1954]
I am running the pong-v0 environment. It seems that each action (up-2/down-5) gives the paddle momentum instead of just simply moving the paddle. Is this inevitable, or is there a fix to this? I tried pong-v4 because it said it wouldn't have a 'repeat_action_probability': 0.25}, which I assume is what causes a momentum for the paddle, but this did not fix the problem. It is also stated "Each action is repeatedly performed for a duration of k frames, where k is uniformly sampled from {2,3,4}." Is this what causes the appearance of momentum, and if so, can I stop it so each action is only preformed for 1 frame?

**Comment by christopherhesse** [comment]
I tried this out with a gym-retro interactive script, and I believe that this is just part of the pong game.  Stepping frame by frame and hitting a button causes the paddle to move for multiple frames (sometimes delayed by a frame).

You can try using the Arcade Learning Environment directly with a script to verify that this is the case.
