### ISSUE TITLE
Questions with observation space for custom environment

### ISSUE THREAD

**Issue by fshih1** [openai/gym#1955]
Questions: **How to determine the size/type of our observation space for our custom environment ?**

I am currently working on creating an environment for a Hide-and-Seek game, wish to utilize the tools of OpenAi Gym. The game has map size 16x16 to 24x24, with building in the map blocking certain path and vision. Two opposing agents have limited vision in the map, blocking the rest of map with fog of war, and information of distance to its closest opponent. Details: [https://github.com/acmucsd/hide-and-seek-ai](url)

I found  [https://github.com/openai/gym/issues/1752 ](url)
useful. Should I use space.dict for observation space? 

Any resources like books or post is really appreciated.

**Comment by fshih1** [comment]
I found this and hopefully this could be useful to anyone see this. 
https://www.toptal.com/deep-learning/pytorch-reinforcement-learning-tutorial

**Comment by christopherhesse** [comment]
A dict observation space seems fine if you have multiple observation shapes you want to expose.   There's a small amount of documentation on spaces here: http://gym.openai.com/docs/

You can make the map observation the size of the maximum map.  If you want to have different layers, it could be 24 x 24 x num_layers.  You could have 1 layer for if the square has fog of war or not, maybe another layer for the type of tile on each square, perhaps another for visible players.

Does that answer your question?

**Comment by fshih1** [comment]
it does! thank you so much!
