### ISSUE TITLE
Question about gym/gym/envs/robotics/assets/fetch/ 

### ISSUE THREAD

**Issue by ishaanchandratreya** [openai/gym#1956]
Hello, 

I had some questions about the choice of dimensions and sites for the assets here: gym/gym/envs/robotics/assets/fetch/ 

More specifically, in pick_and_place.xml, push.xml and slide.xml, the site for the chosen objects
is a sphere of dimensions '0.02 0.02 0.02' which is inside a geom box of size '0.025 0.025 0.025'. Since geom determines most of the physics, this seems irrelevant, but now I am trying to attach a few sensors to this object. Since the site is smaller than the corresponding geom box and of a different shape, I am unable to attach any touch or force sensors on the site and get accurate results as the site is always inside the object. I was wondering why this design choice was made, and whether there are any inherent risks in MuJoCo to having geoms and sites of the same size so that such sensors can be used. These are the specific files I am referring to:

github.com/openai/gym/blob/master/gym/envs/robotics/assets/fetch/pick_and_place.xml
github.com/openai/gym/blob/master/gym/envs/robotics/assets/fetch/push.xml
github.com/openai/gym/blob/master/gym/envs/robotics/assets/fetch/slide.xml

Within these files, I am referring to the 'object0' inside worldbody and the associated geom and site inside it.

Many thanks,
Ishaan

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
