### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by BSVogler** [openai/gym#1957]
I recently [added a PR](https://github.com/openai/gym/pull/1914) but the PR is just ignored so far. A [similar PR was approved](https://github.com/openai/gym/pull/1946) after discussing the issue in a ticket. If the expected way is to open a ticket for each PR, this should be noted somewhere. For me, it is unclear, which types of changes are welcome here and which are not. Now I suspect that my PR will have the same fate as many of the other open PRs on this repo. New environments are currently not added, but this is not noted somewhere. The standard on GitHub is to add a CONTRIBUTING.md to document all these things. therefore, I suggest adding such a file.

**Comment by christopherhesse** [comment]
Sorry, we must have missed your PR.  There is no requirement to make an issue first, though it's often a good idea for non-documentation related changes.  Can you rebase your PR?

It looks like we do not explicitly say that we are not adding new environments.  I've made a PR for adding a CONTRIBUTING file: https://github.com/openai/gym/pull/1969

**Comment by BSVogler** [comment]
Thank you! I appreciate it.
