### ISSUE TITLE
Segmentation fault when rendering both human and rgb_array

### ISSUE THREAD

**Issue by DiddiZ** [openai/gym#1958]
Rendering in both `human`  and `rgb_array` alternatingly results in a segfault.

MWE:
```python
import gym

env = gym.make("FetchReach-v1")

env.render("human") # Renders properly
env.render("rgb_array")  # Returns correct image
env.render("human")  # Segmentation fault
```

Couriously, the other way round also does not work as intended:
```python
import gym

env = gym.make("FetchReach-v1")

env.render("rgb_array") # Returns correct image
env.render("human")  # Renders properly
env.render("rgb_array")  # Only returns zeros, returned image is black
```

I'm using mujoco-py 2.0.2.10.

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
