### ISSUE TITLE
Can't register GoalEnv and specify max_episode_steps

### ISSUE THREAD

**Issue by PierreExeter** [openai/gym#1959]
Hello,

It seems that it not possible to register a `GoalEnv` and to specify `max_episode_steps` at the same time.

For example, I have this minimal environment:

```python
from gym import GoalEnv

class MyGoalEnv(GoalEnv):

    def __init__(self):
        pass
```

**This works:**
```python
from my_goal_env.envs.my_goal_env import MyGoalEnv

env = MyGoalEnv()
print(isinstance(env, gym.GoalEnv))
```
True

**This doesn't work:**

```python
from gym.envs.registration import register

register(id='test_goal_env-v0',
         entry_point='my_goal_env.envs.my_goal_env:MyGoalEnv',
         max_episode_steps=100)
```

```python
import my_goal_env

env = gym.make('test_goal_env-v0')  
print(isinstance(env, gym.GoalEnv))
```
False

I'm using gym 0.17.2.

I attached a minimal working example (run test_env.py)
[goalEnv_question.zip](https://github.com/openai/gym/files/4785322/goalEnv_question.zip)

Any idea why it is not possible to specify `max_episode_steps` for GoalEnv?

Thanks

**Comment by PierreExeter** [comment]
OK so I found out that registering a GoalEnv with `max_episode_steps` is working.
The only minor issue is that isinstance(env, gym.GoalEnv) returns False but this is not a problem in my case.

**Comment by christopherhesse** [comment]
Good to know, sorry that `GoalEnv` is confusing, I wouldn't recommend using it if you can avoid it.
