### ISSUE TITLE
If I want develop a gym-style environment, is there any standard or documentation I should follow?

### ISSUE THREAD

**Issue by songyuc** [openai/gym#1963]
Hi guys,
I am a student who is working on robot soccer games, and we have a simulator for robot soccer games.
I want to make it as a gym-style environment which others could use to do some research about Reinforcement Learning.
So I want to know if there is any standard or documentation I should follow?

Your answer or idea will be appreciated!

**Comment by christopherhesse** [comment]
There's documentation here: https://github.com/openai/gym/blob/master/docs/creating-environments.md

You can look at some of the existing environments to see how they work, but mostly it's a matter of making your environment have the gym.Env interface.  Once your environment works you can add it to this list here: https://github.com/openai/gym/blob/master/docs/environments.md if you want.
