### ISSUE TITLE
issue with assertion in the classic control cartpole domain

### ISSUE THREAD

**Issue by korymath** [openai/gym#197]
File "/gym/envs/classic_control/cartpole.py", line 58, in _step
    assert action==0 or action==1, "%r (%s) invalid"%(action, type(action))
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

**Comment by jietang** [comment]
Seems like you're passing in a numpy array when step() requires an integer action.

The error message could be improved though.
