### ISSUE TITLE
Env Kwargs (gym.make) for ExperimentGrid

### ISSUE THREAD

**Issue by tsunhenry** [openai/gym#1973]
This is a follow-up from issue  #644. I don't think you can pass env kwargs using eg.add in ExperimentGrid? It'd be great if we can merge  #644 to ExperimentGrid too!

Thanks.

**Comment by christopherhesse** [comment]
I'm not sure what ExperimentGrid is, could you explain?

**Comment by christopherhesse** [comment]
Oh it looks to be a feature of SpinningUp, I think you need to file this issue on https://github.com/openai/spinningup
