### ISSUE TITLE
Is there any tutorial manual to teach us how to use this code

### ISSUE THREAD

**Issue by elonhu001** [openai/gym#1976]
hello, OpenAI friends，I am study how to use RL  to realize the motion control of balance robot, so it's very happy to see your work ,  but unfortunately，I can't understand this code, so I am here to ask, Is there any tutorial manual to teach us how to use this code? Thank you very much!

**Comment by christopherhesse** [comment]
I think you might be looking for something like this book: https://www.amazon.com/Deep-Reinforcement-Learning-Hands-optimization/dp/1838826998/ref=pd_sbs_14_1/138-0714365-9013634

**Comment by elonhu001** [comment]
Thank you so much, actually, I want a manual liake ROS Tutorials ( http://wiki.ros.org/ROS/Tutorials ), which can tell me how to use Gym, and how to use Gym to implement my one work, like doing the balance control of self balance robot. But I do think I really need to learn more about RL first.
(By the way, could you write more comment in the code of Gym, thank you!)

**Comment by ricardosalazarcab** [comment]
A good tutorial:
https://www.learndatasci.com/tutorials/reinforcement-q-learning-scratch-python-openai-gym/
