### ISSUE TITLE
close the env when finished

### ISSUE THREAD

**Issue by miluChen** [openai/gym#1978]
https://github.com/openai/gym/blob/345c65973fc7160d8be374745a60c36869d8accc/gym/envs/box2d/lunar_lander.py#L449

Shall we add `env.close()` before returning here?
I've seen error below if it's not closed.
`ImportError: sys.meta_path is None, Python is likely shutting down`.

**Comment by christopherhesse** [comment]
Technically yes, I would entertain a PR to add that.
