### ISSUE TITLE
Mathematical model of Lunar Lander and Bipedal Walker

### ISSUE THREAD

**Issue by NishanthARao** [openai/gym#1979]
Can I get the mathematical model (linear / non-linear state space model) of the Lunar Lander, and the Bipedal Walker?

I could get the non-linear model of the CartPole environment from sutton-barto's paper (as linked in the repository). But I am unable to find the model of the Lunar Lander and Bipedal Walker.

Thanks!

**Comment by christopherhesse** [comment]
Those use the box2d physics engine, wouldn't that make it hard to get the mathematical model since you'd need to re-implement box2d?

**Comment by NishanthARao** [comment]
Oh, right. So box2d physics engine calculates everything implicitly?

Thank you.
