### ISSUE TITLE
I was writing the given code in colab. But the following error prompted:- NameError: name 'base' is not defined. My Pyglet version is 1.5.0

### ISSUE THREAD

**Issue by Samar-080301** [openai/gym#1981]
`import gym

env = gym.make("MountainCar-v0")
env.reset()

done = False
while not done:
    action = 2  # always go right!
    new_state, reward, done, _ = env.step(action)
    env.render()
env.close()        `

**Comment by kethan1** [comment]
Gym is incompatible with pyglet==1.5.0
Do this:  `pip install pyglet==1.3.2`
