### ISSUE TITLE
Saving environment variable that is not included in the observations space

### ISSUE THREAD

**Issue by junwoony** [openai/gym#1983]
Hi, I'm new to gym.
I'm using a gym-based custom environment and Monitor wrappers. If my environment is built like,

```
class MyEnv(gym.Env):
    ....
    self.variable (but not included in the observations)
    ....
```
Is there a way to automatically save or look up the variable after each episode?

**Comment by gallorob** [comment]
I don't know if you are still unsure about how to do this, but you could do something like this:
```
import gym
env = gym.make('MyEnv-v0')
env = gym.wrappers.Monitor(env, 'custom-name')
variables = []  #  <-- where to "save" your variable
env.reset()
for _ in range(1000):
    env.render()
    observation, reward, done, info = env.step(env.action_space.sample()) # take a random action
    variables.append(env.env.variable)  # <-- access the original env via the wrapper
env.close()
```
Obviously this is just a short example, you can save the variable for each episode checking the `done` variable.
