### ISSUE TITLE
Unused (Dead) code in respository

### ISSUE THREAD

**Issue by tusharsrivastava** [openai/gym#1985]
https://github.com/openai/gym/blob/345c65973fc7160d8be374745a60c36869d8accc/gym/core.py#L5

Hi Maintainer,

I'm creating this issue to list issues like unused (dead) code as I'll find it. We can have a discourse over the reasoning of why it is still present and can be helpful to someone else reading the code.

**Comment by tusharsrivastava** [comment]
https://github.com/openai/gym/blob/master/gym/spaces/box.py#L4

Found another one

**Comment by tusharsrivastava** [comment]
I must add, it felt like privilege to read through the code. It is written so elegantly. Just beautiful

**Comment by pzhokhov** [comment]
Hi @tusharsrivastava! There is definitely some dead code, feel free to convert your findings into PRs :) This will also trigger CI to do the first-pass check on whether the code is actually used.

**Comment by jkterry1** [comment]
Close by:

https://github.com/openai/gym/pull/2306 (code was not dead)
https://github.com/openai/gym/pull/2305
