### ISSUE TITLE
Incorrect Labeling For Ant.xml file

### ISSUE THREAD

**Issue by ryanmaxwell96** [openai/gym#1988]
Hello,

I think the legs for Ant.xml are labeled incorrectly. I verified that the x direction points right from the video recording of it running so y is into the screen and z is up. It says the leg in the (x,y) = (+,+) direction is the front left leg. This I agree with. But the (x,y) = (-,+) leg is called the front_right_leg but this should be the back_left_leg. Similarly, I think the (x,y) = (-,-) leg should be the back_right_leg (not just a generic "back_leg") and I think the (x,y) = (+,-) leg should be the front_right_leg, not the right_back_leg.

This is assuming forward is in the +x direction which I think makes sense.

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
