### ISSUE TITLE
gym.utils seed function doesn't replicate pseudorandom results

### ISSUE THREAD

**Issue by QasimWani** [openai/gym#1990]
Using Blackjack demo. tried setting environment seed to 1 using env.seed(seed=1). however, when running random sample in action_space, i was unable to replicate the same value of the discrete output, i.e. should've been 1 all the time (see code below). Moreover, i even set the seed of action_space as `env.action_space.seed(1)` but that still didn't replicate the results.

`for i in range(100):`
    &ensp; `val = env.action_space.sample()`
    &ensp; `if(val != 1):`
      &ensp;&ensp;`print(i) #prints the iteration number when random sample ≠ 1.
`
<br>
Output: `5
7
9
10
13
14
15
...`
<br>
Moreover, the index values were random on multiple runs.
How do I replicate pseudorandom results by selecting a value of seed in this case?
Thanks.

**Comment by sritee** [comment]
Firstly, seeding by the generator doesn't mean you will always sample the same action. The sequence of actions will be same across multiple runs. Secondly, action_space.sample() currently does not support seeding, as the random sampler part of the action space is not used by algorithms in general. (tend to have our own function approximators)

**Comment by QasimWani** [comment]
Got it, thanks for the clarification!
