### ISSUE TITLE
Environment with only terminal reward

### ISSUE THREAD

**Issue by surajp92** [openai/gym#1991]
Is there any environment in OpenAI gym where only a terminal reward is assigned? For example, an agent plays a game and takes number of actions at each time step. But, the agent receives some positive reward if it wins the game and some negative reward if it loses the game? What RL algorithm is suitable for such environments?

Thank you.

**Comment by sritee** [comment]
Checkout out the fetch environments like https://github.com/openai/gym/blob/master/gym/envs/robotics/fetch/push.py, which are initialized with sparse rewards. There is also option to make the rewards dense.
