### ISSUE TITLE
Any `rendering.Image` is rendered as black by default

### ISSUE THREAD

**Issue by gallorob** [openai/gym#1994]
Loading any image file as `rendering.Image` is rendered as black by default.
Code snippet:
```
img = rendering.Image(fname, width, height)
```
I found that setting the `rendering.Geom` color afterwards to white (`img.set_color(1., 1., 1.)`) solves this issue. It looks like the image's color is multiplied by the `rendering.Geom._color` when rendering.

It'd be nice if this was done by default in `rendering.Image.__init__()` method, it's just one additional line:

```
    def __init__(self, fname, width, height):
        Geom.__init__(self)
        self.width = width
        self.height = height
        img = pyglet.image.load(fname)
        self.img = img
        self.flip = False
  ->    self._color = (1., 1., 1., 1.)
```

**Comment by KarlXing** [comment]
Thanks @gallorob ! I'm trying to load customized backgrounds and this issue really saved my time. 
BTW, to update the init of Image class, I think there should an extra line to add self._color to self.attrs. 

```
    def __init__(self, fname, width, height):
        Geom.__init__(self)
        self.width = width
        self.height = height
        img = pyglet.image.load(fname)
        self.img = img
        self.flip = False
        self._color=Color((1, 1, 1, 1.0))
        self.attrs = [self._color]
```

**Comment by gallorob** [comment]
Glad it helped!
I don't think the additional line is necessary though: if you look at the `Geom.__init()` you have that
```
class Geom(object):
    def __init__(self):
        self._color=Color((0, 0, 0, 1.0))
        self.attrs = [self._color]
        ...
```
So once you update the `self._color` in the `Image`, it's already updated for the `self.attrs`.

**Comment by KarlXing** [comment]
I think the problem is that updating self._color will not update self.attrs as well. The element in self.attrs still points to the old Color object. I made a simple test like below 

```
def __init__(self, fname, width, height):
    Geom.__init__(self)
    self.width = width
    self.height = height
    img = pyglet.image.load(fname)
    self.img = img
    self.flip = False
    self._color=Color((1, 1, 1, 1.0))
    print(self.attrs[0].vec4)
```
The printed result is still (0, 0, 0, 1.0)

**Comment by gallorob** [comment]
Weird, I thought it would've worked, thanks for testing it.
Is it then possible to call `self.set_color(1., 1., 1.)` in the `__init__()` instead of redeclaring variables?

**Comment by KarlXing** [comment]
You're welcome. Calling self.set_color() cannot work since it only changes self._color and never touches self.attrs.

**Comment by gallorob** [comment]
Nevermind, this issue seems to have already been fixed in the repo: https://github.com/openai/gym/pull/1928 , I guess I'll update my version of gym.
Calling `self.set_color()` does indeed work though.
