### ISSUE TITLE
Inconsistent observation shapes returned depending on action shape, Pendulum-v0

### ISSUE THREAD

**Issue by sritee** [openai/gym#1999]
```
import gym

#small shape checking experiment of returned observation

env = gym.make('Pendulum-v0')
env.reset()

single_dim_arr = np.array([0.0])
o, _, _, _= env.step(single_dim_arr))
print(o.shape) # (3, )

double_dim_arr = np.array([[0.0]]) #note extra dimension
o, _, _, _ = env.step(double_dim_arr)) #still works
print(o.shape) #(3, 1) 
```
A simple fix would just be doing dimension checking at the start using env.action_space.contains. This is happening because of using the input actions in creating the output state using some broadcasting. https://github.com/openai/gym/blob/6df1b994bae791667a556e193d2a215b8a1e397a/gym/envs/classic_control/pendulum.py#L53

**Comment by sritee** [comment]
It might break old client code, and depending on appropriate assert statement I can make a PR if you wish.

**Comment by DomNomNom** [comment]
I just got bitten by this too :(
the `action_space` says it wants the torque in an array of shape (1,) but the code only works when the torque `u` is a straight float.

**Comment by denishot** [comment]
push it

**Comment by denishot** [comment]
i love this one watson, keep going $IBMusk.

**Comment by denishot** [comment]
You’re breaking trade rules with global ipo.i¢င issues. I am a lobbyist. 

နSEC
