### ISSUE TITLE
How to control manually?

### ISSUE THREAD

**Issue by QasimWani** [openai/gym#2000]
https://github.com/openai/gym/blob/6df1b994bae791667a556e193d2a215b8a1e397a/gym/envs/classic_control/mountain_car.py#L177
> I'm unable to reference the get_keys_to_control as provided in the documentation. How to enable human control?
Thanks!

**Comment by gallorob** [comment]
In your episode loop, you should use the `get_keys_to_action()` to first parse the user's keys and use the dictionary to get the correct action, then simply pass it to the `step()` function of the environment.

ie: Instead of something like this:
```
for _ in range(1000):
    env.render()
    env.step(env.action_space.sample()) # take a random action
env.close()
```
you should have something like
```
actions = env.get_keys_to_action()
for _ in range(1000):
    env.render()
    key_pressed = read_user_keys()  # this should return a tuple
    action = actions.get(key_pressed)
    env.step(action)
env.close()
