### ISSUE TITLE
How to get the number of valid actions for a descrete action space of gym environment?

### ISSUE THREAD

**Issue by Kimonili** [openai/gym#2005]
I saw this [issue](https://github.com/openai/gym/issues/676#issuecomment-399622347) and performed the following line of code
`env.action_space.n`  but it did not work and I got this error instead.

> AttributeError: 'list' object has no attribute 'n'

**Comment by gallorob** [comment]
Depends on the environment; in your case I think it doesn't have a `Discrete` action space but a `list` instead, so you could get the number of valid actions by simply
```
len(env.action_space)
```
You can also make sure the action space is indeed a list before by
```
type(env.action_space) == list
```

**Comment by Kimonili** [comment]
Yes, the `env.action_space` is indeed a list but when when I print it I get this output `[Discrete(5)]`. In addition, `len(env.action_space)` outputs 1 which is not what I want as `[Discrete(5)]` implies that the environment has 5 discrete valid actions. 

My goal is that given an environment I could feed to my neural network the action dimensions of that environment.

In case it helps, I use the [multiagent particle environments](https://github.com/openai/multiagent-particle-envs) from OpenAI.

**Comment by Kimonili** [comment]
Update to whoever might find helpful:
`for act in env.action_space:`
      `print(act.n)`
This block of code outputs `5`. In order for `env.action_space.n` to work correctly you first have to transform it from `list `to `Discrete `object.

**Comment by gallorob** [comment]
Yes, if you look at https://github.com/openai/multiagent-particle-envs/blob/master/multiagent/environment.py at line 39 you can see it creates a list of action spaces for each agent. Doing `len(env.action_space)` would return you the number of agents in your environment.

Also,
>In order for `env.action_space.n` to work correctly you first have to transform it from `list `to `Discrete `object.

I think this would be incorrect: you have to first fetch the right agent and then you can check the number of valid actions, ie
```
env.action_space[agent].n
```
, where `agent` is the index of your agent (in your case, `agent=0` since you only have one).

**Comment by Kimonili** [comment]
> I think this would be incorrect: you have to first fetch the right agent and then you can check the number of valid actions, ie

> env.action_space[agent].n
, where agent is the index of your agent (in your case, agent=0 since you only have one).

Okay, makes sense! I can affirm that it worked.
Thank you very much @gallorob, this information will be very helpfull for the rest of my project as well where I am gonna have multiple agents.

**Comment by gallorob** [comment]
Great, glad to help. Good luck with your project!
