### ISSUE TITLE
[Announcement] blendtorch - OpenAI environments using Blender

### ISSUE THREAD

**Issue by cheind** [openai/gym#2011]
_(Not sure if this tracker is the best way to announce things, let me know if not)_ We have recently been active on seamlessly integrating [Blender](http://www.blender.org) into OpenAI gym via a software package called blendtorch.

**blendtorch** is a Python framework to seamlessly integrate [Blender](http://blender.org) into [PyTorch](http://pytorch.org) datasets for deep learning from artificial visual data. We utilize Eevee, a new physically based real-time renderer, to synthesize images and annotations in real-time and thus avoid stalling model training in many cases.

Feature summary
 - ***Data Streaming***: Stream distributed Blender renderings directly into PyTorch data pipelines in real-time for supervised learning and domain randomization applications. Supports arbitrary pickle-able objects to be send alongside images/videos. Built-in recording capability to replay data without Blender.
 - ***OpenAI Gym Support***: Create and run remotely controlled Blender gyms to train reinforcement agents. Blender serves as simulation, visualization, and interactive live manipulation environment.

https://github.com/cheind/pytorch-blender/

![](https://github.com/cheind/pytorch-blender/raw/develop/examples/control/etc/capture.gif)

**Comment by jkterry1** [comment]
This is awesome. Please do a PR including this as a third party environment if you have not already

**Comment by pAra-d0x** [comment]
Is it possible to use blender environment and its physics with openAI gym to make reinforcement agents that can train a blender object for performing specific tasks?

**Comment by cheind** [comment]
@pAra-d0x  that should be possible from a technical perspective, but hasn't been done. Could you elaborate a bit on the use case?

**Comment by pAra-d0x** [comment]
Yes, I also want to the same. I want to apply forces at four different points on an object (suppose a cube). The agent will decide the  magnitude of each forces such that cube lifts up against gravity. I completely want to use blender's environment and its physics (if possible I will prefer to use UPBGE to access it's game engine capabilities) to simulate real world.

Do you have any resources which can help me to complete this task? By achieving this I can create more advance agent integrated with blender's physics.

**Comment by cheind** [comment]
no sorry, but as a start point you can have a look at the source for the above demo: 
https://github.com/cheind/pytorch-blender/tree/develop/examples/control
