### ISSUE TITLE
[Docs] Explicit link to API?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [openai/gym#2013]
For the website's docs: http://gym.openai.com/docs/

When I see docs for a website, I'd expect an explicit link to the API documentation too.
The API is explained in that section, but it'd be nice to get the full story without having to infer.

There's an implicit link to the API here:
> ![image](https://user-images.githubusercontent.com/26719449/89331783-533e0780-d660-11ea-8356-6f3b775d803e.png)

I think this would be 1000% better if it said "(click here for API)", or even a section that said "API Documentation", and then said "Here, go look at the `gym/core.py`."

I'd submit a PR, but with #2012, I dunno where to submit it...

**Comment by EricCousineau-TRI** [comment]
Just to throw in some more rando comment, one thing that got me to is that both unlinked and linked preformatted text are the same color, so it's hard to tell what's a link:
> ![image](https://user-images.githubusercontent.com/26719449/89332107-d3646d00-d660-11ea-9e30-08b1f1849b2c.png)

In this pic, `observation_space` is just text, whereas `Space` is not.

(That being said, thanks for the great work! It's super nice to leverage this library!)

**Comment by jkterry1** [comment]
closed in favor of issue #2276
