### ISSUE TITLE
ERROR: File "setup.py" not found. Directory cannot be installed in editable mode

### ISSUE THREAD

**Issue by mays95** [openai/gym#2014]
when i run `pip install -e .[dev]`
i have the error `ERROR: File "setup.py" not found. Directory cannot be installed in editable mode: /home/esraa/private-ethereum
`

**Comment by kjellvb** [comment]
I also have this error with wav2letter, have you managed to solve it?

**Comment by AlephNotation** [comment]
Maybe this will help? https://github.com/openai/gym/issues/974

**Comment by npandey3** [comment]
Same error saying 
`Directory '.' is not installable. File 'setup.py' not found.`

**Comment by Ashish0628** [comment]
I am also having the same issue, is there any solution?

**Comment by kjellvb** [comment]
Maybe try to remove the repo folder and clone again, check if setup.py file is there. Also check if all dependencies are installed, upgrade setuptools

**Comment by elasticdotventures** [comment]
Pythons module handling is atrocious.
The number of sharp edges seems to multiple with each horribly written tutorial and github issue.

**Comment by saadnajib** [comment]
you might be running this command in the wrong directory. verify if its the right directory you are in.

**Comment by jkterry1** [comment]
Closed as the issue looks to be solved, let me know if it isn't
