### ISSUE TITLE
[Announcement] We made PettingZoo, Gym for multi-agent RL

### ISSUE THREAD

**Issue by jkterry1** [openai/gym#2018]
Hey, we just released the 1.0 version of PettingZoo. It's a library that includes 62 different multi-agent environments, including multiplayer Atari games (we updated the arcade learning environment) and a fixed version of OpenAI's MPE environments, with an API that's very similar to Gym's. A decent number of people are already using it, and I thought this would be a good place to announce it. This is the repo: https://github.com/PettingZoo-Team/PettingZoo.

**Comment by Pavankunchala** [comment]
I would love to check it out , I will try to use different algorithms to see how they perform. I am excited to see the results though
