### ISSUE TITLE
Why don't you just use qval?

### ISSUE THREAD

**Issue by Triple-ROCK** [openai/gym#2025]
https://github.com/openai/gym/blob/6df1b994bae791667a556e193d2a215b8a1e397a/gym/envs/mujoco/half_cheetah.py#L16

**Comment by Triple-ROCK** [comment]
> https://github.com/openai/gym/blob/6df1b994bae791667a556e193d2a215b8a1e397a/gym/envs/mujoco/half_cheetah.py#L16

I see some tutorial where they register customized env and use 'xvel = observations[:, 9]' instead of 
 reward_run = (xposafter - xposbefore)/self.dt

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
