### ISSUE TITLE
Error  pip install -e .

### ISSUE THREAD

**Issue by 7hu5-5p0k3-6u5** [openai/gym#2031]
Here's what I typed in my terminal:  pip install -e .

Here's the error I got:

ERROR: Could not find a version that satisfies the requirement tensorflow<2.0,>=1.8.0 (from spinup==0.2.0) (from versions: 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0)
ERROR: No matching distribution found for tensorflow<2.0,>=1.8.0 (from spinup==0.2.0)

**Comment by pzhokhov** [comment]
that sounds like a spinning up error, not gym error, please consider filing an issue there. gym does not require tensorflow as a dependency.
