### ISSUE TITLE
Native Google colab

### ISSUE THREAD

**Issue by johnnync13** [openai/gym#2046]
Hello, everybody,
could you create a google colab to make openaigym work perfectly? Many people really don't have a good pc, and google colab is one solution, but I see that it can't be reproduced as well as it is natively.
Is there any reference?

**Comment by pecey** [comment]
I was able to run gym environments on colab. Can you specify what issue are you exactly facing? Someone would be able to help you out then.

**Comment by johnnync13** [comment]
Yes, me too, but to be able to reproduce the environments you have to do crazy things.
