### ISSUE TITLE
how to create a new Robotics env?

### ISSUE THREAD

**Issue by MartinaRuocco** [openai/gym#2051]
Hi, first of all, I'd like you for all the work you are doing :) 
(I am quite a newbie in the field of Reinforcement Learning and) I am trying to understand how the Robotic Envs are built, in particular, I would like to write a new task for the FetchEnv. 
I tried to have a look at the code but the difference between the Fetch envs is very hard to spot (i.e. FetchPushEnv vs FetchSlideEnv look pretty much the same).

Where is the task specified? Is it possible that all the tasks are stuffed in FetchEnv and that the only difference between them is only the value of certain variables?  
I've read in the "What's new" section that 

> FetchEnv sample goal range can be specified through kwargs - thanks @YangRui2015!

Would you mind clarifying how?
Can you write some comments in the code or at least a bit of documentation that explains how these tasks were built? 

Many thanks in advance

**Comment by YangRui2015** [comment]
In my point of view, the tasks are specified by the xml file (in the following picture) and the value of certain variables.

![image](https://user-images.githubusercontent.com/38036768/93463784-d23e8500-f91a-11ea-8b49-8d34f20e5c95.png)

More information about the line in the "What's new" section can be found in the pull requests https://github.com/openai/gym/pull/1799 .

**Comment by avandekleut** [comment]
The physical setup for the environment (table, robot, objects, etc) is defined in the .xml files for use in MuJoCo. The "task" is just the goal-conditioned reward function `compute_reward` defined for any GoalEnv, which for HER is just a sparse binary reward indicating whether the state vector is sufficiently close to the goal state vector.

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
