### ISSUE TITLE
env reset is NotImplementedError

### ISSUE THREAD

**Issue by CyberDreamer** [openai/gym#2056]
i have NotImplementedError in atary_wrapper in few github projects which use it. I just pull code and try to run. I think that work code but may be in another system env or something?

github projects which i try run: 

- https://github.com/AdrianHsu/breakout-Deep-Q-Network
- https://github.com/andi611/DQN-Deep-Q-Network-Atari-Breakout-Tensorflow

**Comment by lakshin** [comment]
In atari_wrapper.py you will have to remove the underscore of the methods which require to be overridden. The Not Implemented methods in the parent class should be implemented in the child classes. 

![image](https://user-images.githubusercontent.com/9911515/110202940-8fa14280-7e91-11eb-8a37-1f22ce04bbd5.png)
