### ISSUE TITLE
Targets not updated correctly in HandReach-v0

### ISSUE THREAD

**Issue by lorenz-h** [openai/gym#2061]
It seems that the HandReach-v0 environment is not updated correctly using the latest versions of gym (0.17.3), mujoco-py (2.0.2.13), Mujoco 2.0 and Python 3.8.6 running on Ubuntu 18.04. The hand is rendered and updated correctly (see screenshot below) but the finger tip marker and target marker positions are not updated correctly. 

![screenshot_default](https://user-images.githubusercontent.com/32291082/95059568-581f4600-06f9-11eb-92cc-4cfe217ecd90.png)
The environment should update the positions (self.sim.model.site_pos[site_id]) in the self._render_callback function - however these changes seem to be ignored by mujoco and reset at the next timestep. I have observed this issue both when rendering directly to display (mode="human") and when rendering to image files (mode="rgb_array"). 

As this environment was developed for an older version of Mujoco, I assume this may have something to do with how Mujoco 2.0 handles site positions nested inside bodies (as can be seen in the default [xml file](https://github.com/openai/gym/blob/master/gym/envs/robotics/assets/hand/reach.xml). I already fixed this issue by moving the markers outside of the <body name="floor0" ... > tag. If anyone is able to replicate this problem, I will create a pull request with my fix.

**Comment by ssilwal** [comment]
Hi Lorenz I'm seeing the same error,  could you share your PR?

**Comment by Epistoteles** [comment]
I am having the same problem, just moving the markers out of the surrounding body tag did not help. Would you mind publishing your solution and linking it here?

**Comment by lorenz-h** [comment]
Hi Everyone,
I don't have my original workaround anymore, since I ended up not using the model. If I remember correctly I ended up modifying the initial positions of the target sites (e.g. target0) to be (0.001 0 0) instead of (0 0 0).
Let me know how it goes!

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
