### ISSUE TITLE
car_racing.py memory leaking issue

### ISSUE THREAD

**Issue by Jaekyung-Cho** [openai/gym#2062]
https://github.com/openai/gym/blob/38a1f630dc9815a567aaf299ae5844c8f8b9a6fa/gym/envs/box2d/car_racing.py#L527

There is memory leaking in car_racing.py code.

pyglet.graphics.vertex_list() function makes the memory almost double,

And it can be fixed with `vl.delete()` under this line
https://github.com/openai/gym/blob/38a1f630dc9815a567aaf299ae5844c8f8b9a6fa/gym/envs/box2d/car_racing.py#L530

**Comment by praveenVnktsh** [comment]
Thanks a lot. This fixed the leak issue.

@Jaekyung-Cho I guess it would be great if you could submit a pull request for this.

**Comment by JunkyByte** [comment]
Hello, I've experienced the same memory leak and applied the solution given by @Jaekyung-Cho.
While it reduces the problem (greatly) it does not eliminate it, I'm running out of ram pretty quickly using multiple CarRacing environments in parallel (on a 64gb ram machine).

Could you share your results for the following code? I see constant increase in ram usage.
(For fair comparison I'm sharing a single environment test code to reproduce so that there's no doubt that it is related to gym / CarRacing env).

```python
import gym
import psutil
import os

def memory_used():
    return psutil.Process(os.getpid()).memory_info().rss * 1e-6  # To megabyte

e = gym.make('CarRacing-v0')
e.unwrapped.verbose = 0

for i in range(10000000):
    e.reset()

    if i % 1000 == 0:
        print('Ram Used: %f' % memory_used())
```

which outputs (numbers are megabyte)

```
Ram Used: 153.264128
Ram Used: 172.523520
Ram Used: 181.149696
Ram Used: 181.149696
Ram Used: 197.632000
Ram Used: 197.632000
Ram Used: 197.632000
Ram Used: 202.498048
Ram Used: 204.931072
Ram Used: 226.336768
Ram Used: 229.040128
Ram Used: 231.743488
Ram Used: 234.176512
Ram Used: 236.609536
Ram Used: 239.312896
Ram Used: 241.745920
Ram Used: 244.449280
Ram Used: 280.604672
Ram Used: 283.037696
(...)
```

looking for a solution, would you be so kind to tell me if you are able to reproduce the issue?

**Comment by Jaekyung-Cho** [comment]
> Hello, I've experienced the same memory leak and applied the solution given by @Jaekyung-Cho.
> While it reduces the problem (greatly) it does not eliminate it, I'm running out of ram ~pretty quickly~ using multiple CarRacing environments in parallel (on a 64gb ram machine).
> 
> Could you share your results for the following code? I see constant increase in ram usage.
> (For fair comparison I'm sharing a single environment test code to reproduce so that there's no doubt that it is related to gym / CarRacing env).
> 
> ```python
> import gym
> import psutil
> import os
> 
> def memory_used():
>     return psutil.Process(os.getpid()).memory_info().rss * 1e-6  # To megabyte
> 
> e = gym.make('CarRacing-v0')
> e.unwrapped.verbose = 0
> 
> for i in range(10000000):
>     e.reset()
> 
>     if i % 1000 == 0:
>         print('Ram Used: %f' % memory_used())
> ```
> 
> which outputs (numbers are megabyte)
> 
> ```
> Ram Used: 153.264128
> Ram Used: 172.523520
> Ram Used: 181.149696
> Ram Used: 181.149696
> Ram Used: 197.632000
> Ram Used: 197.632000
> Ram Used: 197.632000
> Ram Used: 202.498048
> Ram Used: 204.931072
> Ram Used: 226.336768
> Ram Used: 229.040128
> Ram Used: 231.743488
> Ram Used: 234.176512
> Ram Used: 236.609536
> Ram Used: 239.312896
> Ram Used: 241.745920
> Ram Used: 244.449280
> Ram Used: 280.604672
> Ram Used: 283.037696
> (...)
> ```
> 
> looking for a solution, would you be so kind to tell me if you are able to reproduce the issue?

`Ram Used: 164.515840
Ram Used: 173.060096
Ram Used: 181.374976
Ram Used: 181.428224
Ram Used: 196.329472
Ram Used: 194.228224
Ram Used: 196.370432
Ram Used: 198.959104
Ram Used: 201.515008
Ram Used: 218.734592
Ram Used: 221.319168
Ram Used: 223.891456
Ram Used: 226.594816
Ram Used: 229.027840
Ram Used: 231.723008
Ram Used: 234.295296
Ram Used: 236.916736
Ram Used: 268.730368
Ram Used: 271.433728
Ram Used: 273.866752
Ram Used: 276.467712
Ram Used: 279.158784
Ram Used: 281.751552
`

I also got same result.

In my case, I didn't run car_racing module more than 24 hours. And that's why I didn't care about this RAM memory leaking.

Anyway, thank you for notice me and I try to solve it!!!
