### ISSUE TITLE
How to submit scores to Leaderboard?

### ISSUE THREAD

**Issue by Yonv1943** [openai/gym#2066]
How to submit the scores directly to [gym.openai.com/envs](https://gym.openai.com/envs/)?

I solved _BipedalWalkerHardCore-v2_  after 3883 Episodes. It gets average reward of 313 over 128 consecutive trials. I want to submit this scores to [the following website (gym Leaderboard)](https://github.com/openai/gym/wiki/Leaderboard). But I don't know how to do. Can you help me?

* *BipedalWalkerHardcore-v2 defines "solving" as getting average reward of 300 over 100 consecutive trials.*

| User                                            | Episodes before solve | 100-Episode Average Score | Write-up                                                                                                                 | Video | 
|-------------------------------------------------|-----------------------|---------------------------|--------------------------------------------------------------------------------------------------------------------------|-------| 
| [liu](https://github.com/createamind/DRL) | N/A                   | 319 (average of 10000 trials)                   | [writeup](https://github.com/createamind/DRL/blob/master/spinup/envs/BipedalWalkerHardcore) |       | 
| [DollarAkshay](https://github.com/DollarAkshay) | N/A                   | N/A                   | [writeup](https://gist.github.com/DollarAkshay/0453d8ef144b2dd35056180229ec42f4#file-openai_bipedalwalkerhardcore_v2-py) |       | 
| [ryogrid](https://github.com/ryogrid)           | N/A                   | N/A                   | [writeup](https://gist.github.com/ryogrid/f344aa0909c5eda5ecbf95d3ccbd99f7#file-ai_gym_dqn-py)                           |       | 
| [dgriff777](https://github.com/dgriff777) | N/A | 300 | [writeup](https://github.com/dgriff777/a3c_continuous/blob/master/README.md) | [video](https://github.com/dgriff777/a3c_continuous/blob/master/README.md) |
| [lerrytang](https://github.com/lerrytang/) and [hardmaru](https://github.com/hardmaru) | N/A | 300 | [writeup](https://cloud.google.com/blog/products/ai-machine-learning/how-to-run-evolution-strategies-on-google-kubernetes-engine) | [video](http://blog.otoro.net/2017/11/12/evolving-stable-strategies/) |
| [hardmaru](https://github.com/hardmaru) | N/A | 313 ± 53 | [writeup](https://github.com/hardmaru/estool) | [video](https://github.com/hardmaru/estool) |

I want to add this line:
| User                                            | Episodes before solve | 100-Episode Average Score | Write-up                                                                                                                 | Video | 
|-------------------------------------------------|-----------------------|---------------------------|--------------------------------------------------------------------------------------------------------------------------|-------| 
| [Yonv1943](https://github.com/Yonv1943/ElegantRL) | 3883                  | 313 (average of 128 trials)                   | [writeup](https://github.com/Yonv1943/ElegantRL) |       [video](https://www.bilibili.com/video/BV1wi4y187tC) |

<p float="left">
    <img src="https://github.com/Yonv1943/ElegantRL/blob/master/Result/InterSAC_BipedalWalkerHardcore-v3_310/plot_Step_Time_2665512_102194.png" width = "400"  alt="InterSAC_BipedalWalkerHardcore_310"/>
    <img src="https://github.com/Yonv1943/ElegantRL/blob/master/Result/InterSAC_BipedalWalkerHardcore-v3_313/plot_step_time_maxR_3102410_90060_313.828.png" width = "400"  alt="InterSAC_BipedalWalkerHardcore_313"/>
</p>

---
By the way, I suggest to compare the "total training step before solve" instead of "total training episodes before solve".

**Comment by yashaslokesh** [comment]
Some info here: https://github.com/openai/gym/wiki/Leaderboard
It looks like this wiki is being used over the website now.

**Comment by Yonv1943** [comment]
I will close this issue. Your answer helped me. Thank you.
