### ISSUE TITLE
The game interface is blurry

### ISSUE THREAD

**Issue by golden-memory** [openai/gym#2075]
Hi, I am a beginner in Gym. I tried to run the game as follows, but the interface is blurry! 
![2](https://user-images.githubusercontent.com/50734162/97305539-2b91c080-1898-11eb-881a-4d73587320bb.png)
It is clearly on another game, Now how can I  do it?
![1](https://user-images.githubusercontent.com/50734162/97305797-8aefd080-1898-11eb-9e47-0f43fb250eeb.png)

**Comment by Suhas7** [comment]
I couldn't reproduce this on MacOS, maybe it has something to do with your OpenGL install?
