### ISSUE TITLE
Make scipy an optional dependency

### ISSUE THREAD

**Issue by davidrusu** [openai/gym#2079]
Hi, we are looking to simplify our dependencies as much as we can.

We found that gym was pulling in scipy, which is a non-trivial package to install. It has various system dependencies that need to be installed before the package will install successfully. A few of our users have encountered issues with installing our package due to scipy install issues.

By my count, scipy is only used by the following modules:
* `gym/envs/classic_control/acrobot.py`
* `gym/envs/toy_text/kellycoinflip.py`

Any objections to moving scipy to an optional dependency?

**Comment by ZhiqingXiao** [comment]
`acrobot.py` does not use `scipy`.

**Comment by jkterry1** [comment]
Ideally we could just remove scipy entirely

**Comment by jkterry1** [comment]
Closed by #2291
