### ISSUE TITLE
Travis ending free plan for open source projects

### ISSUE THREAD

**Issue by jkterry1** [openai/gym#2089]
If Gym is using the free open source plan for Travis (which it appears to be), then you guys have like a few days to switch to a paid plan: https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing. Might want to look into that. @pzhokhov

**Comment by pzhokhov** [comment]
from cursory reading of the blogpost, I got that these changes don't affect free plans on travis-ci.org? So I think we are good, but it is possible I missed something

**Comment by justinkterry** [comment]
@pzhokhov the .org is being permanently shut down at the end of 2020 https://mailchi.mp/3d439eeb1098/travis-ciorg-is-moving-to-travis-cicom

**Comment by pzhokhov** [comment]
Checked with our infra people - we do have a paid plan for travis-ci.com. Will migrate gym to it shortly.
