### ISSUE TITLE
HalfCheetah-v3 reward threshold is strange

### ISSUE THREAD

**Issue by ChenDRAG** [openai/gym#2090]
When I use gym 0.17.3. I find out that game 'HalfCheetah-v3' in mujoco has a reward_threshold of 4800.0.
```
gym.make('HalfCheetah-v3').spec.reward_threshold
4800.0

gym.make('Walker2d-v3').spec.reward_threshold
None
```
However, I typically reached 9000+ points in HalfCheetah-v3, clearly you can achieve much higher points than 4800. Is this number wrong? Can anyone explain.

Also, standard game like Walker2d-v3 doesn't have reward_threshold, which cause inconvenience. Could anyone sovle this?

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
