### ISSUE TITLE
Some ENVs in the wiki/Table-of-environments page get 404 response

### ISSUE THREAD

**Issue by Dynmi** [openai/gym#2095]
## Location
Wiki page

## Problem
When I cilck some env in the wiki page, it leads to 404 not found, as followed:
![1](https://user-images.githubusercontent.com/43609816/99207600-51581880-27f9-11eb-9b6e-db2a687d4906.png)

## List of envs which lead to 404 (tested)
- Adventure-ram-v4
- AirRaid-ramDeterministic-v4
- Asterix-ramDeterministic-v0

**Comment by jkterry1** [comment]
There will be a new website per #2276
