### ISSUE TITLE
Gym on Mac OS X Big Sur

### ISSUE THREAD

**Issue by marcelovidigal** [openai/gym#2101]
After updating OS all my scripts stopped working, most of the errors related to pyglet, and paths to some libraries, some errors that I came across:

```
Error occurred while running `from pyglet.gl import *`
HINT: make sure you have OpenGL install. On Ubuntu, you can run 'apt-get install python-opengl'.
If you're running on a server, you may need a virtual frame buffer; something like this should work:
'xvfb-run -s "-screen 0 1400x900x24" python <your_script.py>'
```

`ImportError: Can't find framework /System/Library/Frameworks/OpenGL.framework.`

I researched, and tried, various possible solutions on the internet, but nothing solved, does anyone have an idea of how to fix this problem, I appreciate any help, I'm using python 3.8, but I tried on 3.7 too, and I was unsuccessful.

**Comment by WayenVan** [comment]
I have the same problem,  is that means the OpenGl didn't be installed properly?

**Comment by WayenVan** [comment]
Well,[there](https://github.com/pyglet/pyglet/issues/274) are some solutions. I have not tried them yet, good luck!

**Comment by DarioBernardo** [comment]
I had the same problem, and installing `pyglet==1.5.11 `(as suggested in the discussion linked by @WayenVan) solved the issue.

**Comment by kochsebastian** [comment]
@DarioBernardo  How can you install `pyglet==1.5.11` when the newest version of gym (0.17.3) requires pyglet between 1.4  and 1.5 at least according to my error message:
```gym 0.17.3 requires pyglet<=1.5.0,>=1.4.0, but you'll have pyglet 1.5.11 which is incompatible```

**Comment by DarioBernardo** [comment]
I get the same error, however pyglet get installed (I get "Successfully installed pyglet-1.5.11" message after the error). In fact when i try to run my code again it actually works. Try, I think should work for you as well if the pyglet get actually installed as it happens for me.

**Comment by kochsebastian** [comment]
@DarioBernardo Yes you are 100% correct. It did get installed and now gym runs without an error

**Comment by lix4** [comment]
@DarioBernardo You are my lifesaver.

**Comment by emnabarred** [comment]
@DarioBernardo I did the same but when I run my code it still doesn't work 😅

**Comment by K-tang-mkv** [comment]
@DarioBernardo Thanks for your help. I got the same error from pyglet and I try the method **pip install pyglet==1.5.11** then the issue was addressed!

**Comment by takumijoel** [comment]
@emnabarred  Mine didn't work at first as well. But it worked after closing everything and reopening.

**Comment by antic11d** [comment]
I tried installing pyglet==1.5.11 and that fixed the ImportError, but know I get the following: AttributeError: dlsym(0x104f43d80, class_getMethodImplementation_stret): symbol not found. Does anyone know what's this about, and/or how to fix it?
Btw, I'm running the code on MacbookPro M1.

**Comment by emnabarred** [comment]
> @emnabarred Mine didn't work at first as well. But it worked after closing everything and reopening.

Unfortunately, it didn't work for me. I'm on the M1 chip if that has anything to do with this..

**Comment by antic11d** [comment]
@emnabarred This https://github.com/pyglet/pyglet/pull/335 should be the fix, at least it did the job for me :)

**Comment by emnabarred** [comment]
@antic11d Thank you very much, this fixed my issue !

**Comment by leon-richard** [comment]
> I had the same problem, and installing `pyglet==1.5.11 `(as suggested in the discussion linked by @WayenVan) solved the issue.

Thanks you for saving my life!

**Comment by holoodst** [comment]
> @DarioBernardo How can you install `pyglet==1.5.11` when the newest version of gym (0.17.3) requires pyglet between 1.4 and 1.5 at least according to my error message:
> `gym 0.17.3 requires pyglet<=1.5.0,>=1.4.0, but you'll have pyglet 1.5.11 which is incompatible`

sure ,but it is work amzing

**Comment by cmsax** [comment]
I just tried `pyglet==1.5.11`, not worked. but `pyglet==1.5.12` worked. with `gym==0.18.0`

**Comment by DerekGrant** [comment]
> I had the same problem, and installing `pyglet==1.5.11 `(as suggested in the discussion linked by @WayenVan) solved the issue.

Solved my problem,thx!

**Comment by PluteW** [comment]
Thanks! Installing pyglet==1.5.11 worked for me!

**Comment by OleksiyAnokhin** [comment]
pyglet==1.5.11 does not work on Windows for me

What did I also try?

- !pip install gym
- !pip install -f https://github.com/Kojoley/atari-py/releases atari_py
- !pip install gym[atari]
- !pip install git+https://github.com/Kojoley/atari-py.git
- 
ImportError: 
    Error occurred while running `from pyglet.gl import *`
    HINT: make sure you have OpenGL install. On Ubuntu, you can run 'apt-get install python-opengl'.
    If you're running on a server, you may need a virtual frame buffer; something like this should work:
    'xvfb-run -s "-screen 0 1400x900x24" python <your_script.py>'

**Comment by XiaoyanQian** [comment]
> I had the same problem, and installing `pyglet==1.5.11 `(as suggested in the discussion linked by @WayenVan) solved the issue.

Thank you so much. this helps to fix my issue

**Comment by JalexDooo** [comment]
Thx!!

**Comment by rajvijay68** [comment]
Installing `pyglet==1.5.11` did not work for me , 
This is with MacOS Big sure 11.3.1 and `gym=='0.18.0'`

**Comment by JanKaifer** [comment]
After installing `pyglet==15.11.1` I get:
```zsh
zsh: segmentation fault  python gym_demo.py
```

**Comment by jkterry1** [comment]
This should all be fixed, but if it is not please create new issues for individual porblems
