### ISSUE TITLE
Apple M1 chip rendering problems

### ISSUE THREAD

**Issue by JingkaiXie** [openai/gym#2114]
I just traded in my intel MacBook for the new m1 MacBook. and I get the following error message, I have tried `pip install PyOpenGL` , `pip install pyglet`  and `pip install PyOpenGL-accelerate`, and they don't seem to fix the problem. Could anyone advise how to fix this? 

```
ImportError: 
    Error occured while running `from pyglet.gl import *`
    HINT: make sure you have OpenGL install. On Ubuntu, you can run 'apt-get install python-opengl'.
    If you're running on a server, you may need a virtual frame buffer; something like this should work:
    'xvfb-run -s "-screen 0 1400x900x24" python <your_script.py>'
```

**Comment by wangyuan02605** [comment]
installing pyglet==1.5.11

**Comment by geyang** [comment]
@JingkaiXie are you able to run MuJoCo environments on the M1 mac?
