### ISSUE TITLE
Skiing game not random (same level repeated)

### ISSUE THREAD

**Issue by axtonisaly1013** [openai/gym#2117]
Hi,

I was a bit disappointed recently to find that the Skiing game only has one level. When I reset the environment, it is reconfigured with the exact same obstacle configuration. I was expecting the obstacles to be regenerated randomly upon each reset.

Am I missing something? Is this lack of randomness common in other games?

Thanks.

**Comment by jkterry1** [comment]
This will be fixed when ALE-Py is merged in to replace Atari-Py the coming weeks.
