### ISSUE TITLE
record humanoid env

### ISSUE THREAD

**Issue by azamkamranian** [openai/gym#2118]
Hi, I am using the mujoco humanoid environment on windows. The env.render() with 'Creating window glfw' works fine and I have a good visualization of my humanoid, but I can't record it.  I tried "gym.wrappers.monitor" but it doesn't work, just freeze and make a .json and empty .mp4 file for me. This creates a "MUJOCO_LOG.TXT" that contains 'ERROR: GLEW initalization error: Missing GL version'. I am using:
gym==0.17.3
mujoco==2.0.2.13
glfw==2.0.0

Is there a way to record env? Could you help me?
Thanks

**Comment by potatouncle** [comment]
I have the same problem, please let me know if you solve it.

**Comment by azamkamranian** [comment]
> I have the same problem, please let me know if you solve it.

Sure.. but I think it is because of windows os, it works in ubunu for me

**Comment by Coder-RG** [comment]
> Hi, I am using the mujoco humanoid environment on windows. The env.render() with 'Creating window glfw' works fine and I have a good visualization of my humanoid, but I can't record it. I tried "gym.wrappers.monitor" but it doesn't work, just freeze and make a .json and empty .mp4 file for me. This creates a "MUJOCO_LOG.TXT" that contains 'ERROR: GLEW initalization error: Missing GL version'. I am using:
> gym==0.17.3
> mujoco==2.0.2.13
> glfw==2.0.0
> 
> Is there a way to record env? Could you help me?
> Thanks

When I tried to make  "Humanoid-v2", I received **ValueError: numpy.ndarray size changed, may indicate binary incompatibility. Expected 88 from C header, got 80 from PyObject**. Did you also face this?

**Comment by azamkamranian** [comment]
@Coder-RG sorry, I don't remember.. I don't use mujoco anymore

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
