### ISSUE TITLE
Writing Frame in video_recorder.py ImageEncoder is unreachable

### ISSUE THREAD

**Issue by mattvlaw** [openai/gym#2124]
I was having trouble recording video files with the latest version of gym, using CarRacing.

After some exploration, I found that in the capture_frame function of ImageEncoder here:

https://github.com/openai/gym/blob/c4d0af393ef9fba641bd3ebbbf1f60d291c8475d/gym/wrappers/monitoring/video_recorder.py#L303

self.proc.stdin.write(frame.tobytes()) seems to be unreachable and is not getting called. When I unindent that line, I see videos written again.

I think this may have been a change in the following: https://github.com/openai/gym/pull/2084

I apologize if I'm violating norms as this is my first time opening an issue.

**Comment by mattvlaw** [comment]
Made a PR here: https://github.com/openai/gym/pull/2125

**Comment by jkterry1** [comment]
Closed with PR
