### ISSUE TITLE
Python 3.9 and apple silicon support?

### ISSUE THREAD

**Issue by slerman12** [openai/gym#2129]
Hi, I just got a new M1 MacBook and I have no idea how to get Gym running on it.

**Comment by JesseLT** [comment]
Have you got gym running on it ?

**Comment by anglyan** [comment]
Here is a suggestion: clone the repo and remove the pillow version dependency from setup.py. It will probably break if you need it, but as long as you don't do any rendering it should be fine.

**Comment by jkterry1** [comment]
Duplicate issue
