### ISSUE TITLE
pip install gym not working

### ISSUE THREAD

**Issue by Blueelectrum** [openai/gym#2138]
I tried installing gym and it comes up with this. Please help.
`Collecting gym
  Using cached gym-0.18.0.tar.gz (1.6 MB)
Requirement already satisfied: scipy in c:\users\gmfl2\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from gym) (1.5.4)
Requirement already satisfied: numpy>=1.10.4 in c:\users\gmfl2\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from gym) (1.19.4)
Requirement already satisfied: pyglet<=1.5.0,>=1.4.0 in c:\users\gmfl2\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from gym) (1.5.0)
Collecting cloudpickle<1.7.0,>=1.2.0
  Using cached cloudpickle-1.6.0-py3-none-any.whl (23 kB)
Collecting Pillow<=7.2.0
  Using cached Pillow-7.2.0.tar.gz (39.1 MB)
Requirement already satisfied: future in c:\users\gmfl2\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pyglet<=1.5.0,>=1.4.0->gym) (0.18.2)
Using legacy 'setup.py install' for gym, since package 'wheel' is not installed.
Using legacy 'setup.py install' for Pillow, since package 'wheel' is not installed.
Installing collected packages: Pillow, cloudpickle, gym
  Attempting uninstall: Pillow
    Found existing installation: pillow 8.0.1
    Uninstalling pillow-8.0.1:
      Successfully uninstalled pillow-8.0.1
    Running setup.py install for Pillow ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\Gmfl2\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Gmfl2\\AppData\\Local\\Temp\\pip-install-_rlxnry7\\pillow_930daf7600064945a31f6c5d91da11ce\\setup.py'"'"'; __file__='"'"'C:\\Users\\Gmfl2\\AppData\\Local\\Temp\\pip-install-_rlxnry7\\pillow_930daf7600064945a31f6c5d91da11ce\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Gmfl2\AppData\Local\Temp\pip-record-ci3cjexi\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\Gmfl2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Include\Pillow'
         cwd: C:\Users\Gmfl2\AppData\Local\Temp\pip-install-_rlxnry7\pillow_930daf7600064945a31f6c5d91da11ce\
    Complete output (174 lines):
    C:\Users\Gmfl2\AppData\Local\Temp\pip-install-_rlxnry7\pillow_930daf7600064945a31f6c5d91da11ce\setup.py:42: RuntimeWarning: Pillow 7.2.0 does not support Python 3.9 and does not provide prebuilt Windows binaries. We do not recommend building from source on Windows.
      warnings.warn(
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.9
    creating build\lib.win-amd64-3.9\PIL
    copying src\PIL\BdfFontFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\BlpImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\BmpImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\BufrStubImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ContainerIO.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\CurImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\DcxImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\DdsImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\EpsImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ExifTags.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\features.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\FitsStubImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\FliImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\FontFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\FpxImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\FtexImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\GbrImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\GdImageFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\GifImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\GimpGradientFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\GimpPaletteFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\GribStubImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\Hdf5StubImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\IcnsImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\IcoImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\Image.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageChops.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageCms.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageColor.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageDraw.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageDraw2.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageEnhance.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageFilter.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageFont.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageGrab.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageMath.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageMode.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageMorph.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageOps.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImagePalette.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImagePath.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageQt.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageSequence.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageShow.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageStat.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageTk.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageTransform.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImageWin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\ImtImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\IptcImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\Jpeg2KImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\JpegImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\JpegPresets.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\McIdasImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\MicImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\MpegImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\MpoImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\MspImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PaletteFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PalmImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PcdImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PcfFontFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PcxImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PdfImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PdfParser.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PixarImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PngImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PpmImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PsdImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PSDraw.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\PyAccess.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\SgiImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\SpiderImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\SunImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\TarIO.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\TgaImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\TiffImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\TiffTags.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\WalImageFile.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\WebPImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\WmfImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\XbmImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\XpmImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\XVThumbImagePlugin.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\_binary.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\_tkinter_finder.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\_util.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\_version.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\__init__.py -> build\lib.win-amd64-3.9\PIL
    copying src\PIL\__main__.py -> build\lib.win-amd64-3.9\PIL
    running egg_info
    writing src\Pillow.egg-info\PKG-INFO
    writing dependency_links to src\Pillow.egg-info\dependency_links.txt
    writing top-level names to src\Pillow.egg-info\top_level.txt
    reading manifest file 'src\Pillow.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.c'
    warning: no files found matching '*.h'
    warning: no files found matching '*.sh'
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.readthedocs.yml'
    warning: no previously-included files found matching 'codecov.yml'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    no previously-included directories found matching '.ci'
    writing manifest file 'src\Pillow.egg-info\SOURCES.txt'
    running build_ext

    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html

    Traceback (most recent call last):
      File "C:\Users\Gmfl2\AppData\Local\Temp\pip-install-_rlxnry7\pillow_930daf7600064945a31f6c5d91da11ce\setup.py", line 864, in <module>
        setup(
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\__init__.py", line 165, in setup
        return distutils.core.setup(**attrs)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\distutils\command\install.py", line 546, in run
        self.run_command('build')
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.496.0_x64__qbz5n2kfra8p0\lib\distutils\command\build_ext.py", line 340, in run
        self.build_extensions()
      File "C:\Users\Gmfl2\AppData\Local\Temp\pip-install-_rlxnry7\pillow_930daf7600064945a31f6c5d91da11ce\setup.py", line 694, in build_extensions
        raise RequiredDependencyException(f)
    __main__.RequiredDependencyException: zlib

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Gmfl2\AppData\Local\Temp\pip-install-_rlxnry7\pillow_930daf7600064945a31f6c5d91da11ce\setup.py", line 918, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:

    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html

    ----------------------------------------
  Rolling back uninstall of pillow
  Moving to c:\users\gmfl2\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages\pil\
   from C:\Users\Gmfl2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\~il
  Moving to c:\users\gmfl2\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages\pillow-8.0.1.dist-info\
   from C:\Users\Gmfl2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\~illow-8.0.1.dist-info
ERROR: Command errored out with exit status 1: 'C:\Users\Gmfl2\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Gmfl2\\AppData\\Local\\Temp\\pip-install-_rlxnry7\\pillow_930daf7600064945a31f6c5d91da11ce\\setup.py'"'"'; __file__='"'"'C:\\Users\\Gmfl2\\AppData\\Local\\Temp\\pip-install-_rlxnry7\\pillow_930daf7600064945a31f6c5d91da11ce\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Gmfl2\AppData\Local\Temp\pip-record-ci3cjexi\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\Gmfl2\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\Include\Pillow' Check the logs for full command output.`

**Comment by compilation-error** [comment]
try pip installing wheel first so you don'tt have to compile Pillow. Also, [pillow dependencies](https://pillow.readthedocs.io/en/stable/installation.html#external-libraries) should be installed - in this case zlib before installing pillow.

Try:
1. `pip install wheel`
2. install zlib for windows
3. rerun `pip install gym`

**Comment by JRitmeester** [comment]
@compilation-error That doesn't work for me sadly.

**Comment by Baekalfen** [comment]
This is covered in #2135

**Comment by erolrecep** [comment]
zlib is the dependency to build pillow from source even if you have cached pillow in your site-packages. 
What I have done is, 
 1. brew install zlib
 2. Add zlib libraries to the path, "brew info zlib" gives instructions for how to add zlib libraries as well as package-config file to the path.
 
For Mac
> export LDFLAGS="-L/usr/local/opt/zlib/lib"
> export CPPFLAGS="-I/usr/local/opt/zlib/include"
> export PKG_CONFIG_PATH="/usr/local/opt/zlib/lib/pkgconfig"

 3. pip install gym

This worked for me.

Python -> 3.9
Virtualenvironment -> Virtualenv (I haven't tested on conda)

I hope this works for you.

**Comment by chrismilleruk** [comment]
@erolrecep 
I had the same issue and that fixed it for me. Thanks!

**Comment by meetpandya27** [comment]
> zlib is the dependency to build pillow from source even if you have cached pillow in your site-packages.
> What I have done is,
> 
> 1. brew install zlib
> 2. Add zlib libraries to the path, "brew info zlib" gives instructions for how to add zlib libraries as well as package-config file to the path.
> 
> For Mac
> 
> > export LDFLAGS="-L/usr/local/opt/zlib/lib"
> > export CPPFLAGS="-I/usr/local/opt/zlib/include"
> > export PKG_CONFIG_PATH="/usr/local/opt/zlib/lib/pkgconfig"
> 
> 1. pip install gym
> 
> This worked for me.
> 
> Python -> 3.9
> Virtualenvironment -> Virtualenv (I haven't tested on conda)
> 
> I hope this works for you.

It works !

**Comment by Hrrsmjd** [comment]
@compilation-error I am having the exact error as @Blueelectrum. How do I install zlib on windows?

**Comment by Hrrsmjd** [comment]
@erolrecep Any idea how to install zlib for windows?

**Comment by erolrecep** [comment]
I am not a Windows user and haven't installed any software or library. I found this on DuckDuckGo -> https://github.com/horta/zlib.install . You can try this. Also, you may need to add zlib library files to the PATH.

**Comment by AK47dev** [comment]
> zlib is the dependency to build pillow from source even if you have cached pillow in your site-packages.
> What I have done is,
> 
> 1. brew install zlib
> 2. Add zlib libraries to the path, "brew info zlib" gives instructions for how to add zlib libraries as well as package-config file to the path.
> 
> For Mac
> 
> > export LDFLAGS="-L/usr/local/opt/zlib/lib"
> > export CPPFLAGS="-I/usr/local/opt/zlib/include"
> > export PKG_CONFIG_PATH="/usr/local/opt/zlib/lib/pkgconfig"
> 
> 1. pip install gym
> 
> This worked for me.
> 
> Python -> 3.9
> Virtualenvironment -> Virtualenv (I haven't tested on conda)
> 
> I hope this works for you.

Works like a charm :)

**Comment by solomon0303** [comment]
> zlib is the dependency to build pillow from source even if you have cached pillow in your site-packages.
> What I have done is,
> 
> 1. brew install zlib
> 2. Add zlib libraries to the path, "brew info zlib" gives instructions for how to add zlib libraries as well as package-config file to the path.
> 
> For Mac
> 
> > export LDFLAGS="-L/usr/local/opt/zlib/lib"
> > export CPPFLAGS="-I/usr/local/opt/zlib/include"
> > export PKG_CONFIG_PATH="/usr/local/opt/zlib/lib/pkgconfig"
> 
> 1. pip install gym
> 
> This worked for me.
> 
> Python -> 3.9
> Virtualenvironment -> Virtualenv (I haven't tested on conda)
> 
> I hope this works for you.

this is working! appreciate that!

**Comment by ZhangYizhe** [comment]
> zlib is the dependency to build pillow from source even if you have cached pillow in your site-packages.
> What I have done is,
> 
> 1. brew install zlib
> 2. Add zlib libraries to the path, "brew info zlib" gives instructions for how to add zlib libraries as well as package-config file to the path.
> 
> For Mac
> 
> > export LDFLAGS="-L/usr/local/opt/zlib/lib"
> > export CPPFLAGS="-I/usr/local/opt/zlib/include"
> > export PKG_CONFIG_PATH="/usr/local/opt/zlib/lib/pkgconfig"
> 
> 1. pip install gym
> 
> This worked for me.
> 
> Python -> 3.9
> Virtualenvironment -> Virtualenv (I haven't tested on conda)
> 
> I hope this works for you.

Thank you, you save my time!!!

**Comment by kangelo** [comment]
> zlib is the dependency to build pillow from source even if you have cached pillow in your site-packages.
> What I have done is,
> 
> 1. brew install zlib
> 2. Add zlib libraries to the path, "brew info zlib" gives instructions for how to add zlib libraries as well as package-config file to the path.
> 
> For Mac
> 
> > export LDFLAGS="-L/usr/local/opt/zlib/lib"
> > export CPPFLAGS="-I/usr/local/opt/zlib/include"
> > export PKG_CONFIG_PATH="/usr/local/opt/zlib/lib/pkgconfig"
> 
> 1. pip install gym
> 
> This worked for me.
> 
> Python -> 3.9
> Virtualenvironment -> Virtualenv (I haven't tested on conda)
> 
> I hope this works for you.

Thank you!, this help me so much :D

**Comment by mbutterfieldGO** [comment]
Windows: this solved the problem for me.
I typically use terminal/powershell.  Switching to a simple 'command prompt' and re-running the 'pip install gym' worked.  I do believe this is due to the Windows PATH environment variable and its use by the two tools.
