### ISSUE TITLE
Best 100-episode average reward calculated wrong

### ISSUE THREAD

**Issue by RafaelCosman** [openai/gym#214]
E.g. https://gym.openai.com/evaluations/eval_UFV16qbdTraYLs9HnKomQ

**Comment by RafaelCosman** [comment]
At least it seems inconsistent with the `learning performance` chart.

**Comment by JKCooper2** [comment]
It looks like the graph breaks the scores into 100 blocks so 20K episodes are grouped into 200 episodes per block. The [stats scoring](https://github.com/openai/gym/blob/master/gym/scoreboard/scoring.py) use the median value `scipy.stats.binned_statistic(x_timestep, episode_rewards, 'median', buckets)` which for something like roulette where it's either 0 or 1 results in a graph that isn't very expressive. 

Potentially using the mean could work better, or alternatively having additional options like zoom (assuming the uploaded data is kept and graph on the site can be calculated on the fly)

**Comment by JKCooper2** [comment]
That code may need to be changed server side rather as I don't think it's calculated locally
