### ISSUE TITLE
How to combine Tuple with dqn

### ISSUE THREAD

**Issue by Yuchen0604** [openai/gym#2143]
Hi, I was just wondering, how can I get the dimension of a Tuple space?
My space is as follows:
`self.observation_space = spaces.Tuple(spaces=(spaces.Box(low=0, high=20, shape=(3,), dtype=np.float16), spaces.Box(low=-high, high=high, shape=(2, 24), dtype=np.float16), spaces.Discrete(24)))`
I want to use the dqn agent, which requires the space.shape to build the neural network, and according to my understanding, in this case I will need 3+2*24+1 = 52 input neuron.
How can I get the number of 52?
Thanks in advance!

**Comment by jordan-schneider** [comment]
You can sample from the observation space, and then iterate over the resulting tuple, and count the dimensions
```python
def get_flat_dimension(space: gym.spaces.Tuple) -> int
  obs = space.sample()
  dims = 0
  for item in obs:
    dims += np.prod(item.shape)
  return dims
```
