### ISSUE TITLE
PyCharm jupyter notebook window renders incorrectly

### ISSUE THREAD

**Issue by Auhill** [openai/gym#2146]
![image](https://user-images.githubusercontent.com/20203629/103746154-98190080-503b-11eb-80ef-209ac5789346.png)

PyCharm version: 2020.2.4 (Professional  Edition)
Python version: python 3.6
gym version: 0.18.0
jupyter version: 1.0.0

**Comment by jkterry1** [comment]
I'd be open to PRs for this but this isn bot something I have the bandwidth to sort out and fix myself. This works fine in a regular terminal.
