### ISSUE TITLE
2D tuple space of different types: Assertion failure: "Elements of the tuple must be instances of gym.Space"

### ISSUE THREAD

**Issue by miladga** [openai/gym#2153]
Hi,

 I would like to have a 2D tuple space that consist of discrete and box elements, e.g.,

self.observation_space = spaces.Tuple(([spaces.Discrete(2),
                                       spaces.Discrete(2),
                                            spaces.Box(low=np.array([0, -18,]),
                                                       high=np.array([1, 34]),
                                                       dtype=np.float32,),
                                            ],)*self.num_users)

However, I get assertion failure in tuple.py due to "Elements of the tuple must be instances of gym.Space" because in this case. space is a 1D tuple with Discrete and box elements which is not of type gym.Space. Does anyone have an idea on how to do it in gym?

Thanks in advance.

**Comment by RedTachyon** [comment]
@miladga Syntax error, your first argument to `spaces.Tuple` is a tuple containing lists containing spaces, and it should be a tuple containing spaces.

What you probably wanted is something like:

```python
gym.spaces.Tuple((gym.spaces.Discrete(2),
    gym.spaces.Discrete(2),
    gym.spaces.Box(low=np.array([0, -18,]),
    high=np.array([1, 34]),
    dtype=np.float32,),
)*num_users)
```

@jkterry1 closable

**Comment by RedTachyon** [comment]
@miladga You can make a nested Tuple space by making sure that the elements are also Tuple spaces. Right now you're passing a tuple of lists of spaces, instead pass a tuple of (Tuple space)s of spaces, like this:

```python
gym.spaces.Tuple((
    gym.spaces.Tuple([
    gym.spaces.Discrete(2),
    gym.spaces.Discrete(2),
    gym.spaces.Box(low=np.array([0, -18,]),
    high=np.array([1, 34]),
    dtype=np.float32,),
    ]),)*num_agents)
```

@jkterry1 Closable
