### ISSUE TITLE
Atari observations are all 0

### ISSUE THREAD

**Issue by xlnwel** [openai/gym#2159]
I ran into a problem that all of Atari's observations are 0.

Here's a colab notebook that shows this issue: https://colab.research.google.com/drive/1N9g0XYMNb6X4CjxQWsuFJ0GOuvmWkbFW?usp=sharing

**Comment by 1nF0rmed** [comment]
Hey - I ran into a similar problem. Was this is a programming error or did you come up with a fix?

**Comment by xlnwel** [comment]
I don't think it should be fixed. Most parts of the observations are indeed zero

**Comment by 1nF0rmed** [comment]
> I don't think it should be fixed. Most parts(but not all of them) of the observations are indeed zero.

Then why close the issue?

**Comment by xlnwel** [comment]
Because it's not an issue! Most parts of the observations are black, i.e., zero.
