### ISSUE TITLE
np.inf in Box Spaces causing invalid samples

### ISSUE THREAD

**Issue by JKCooper2** [openai/gym#216]
When running action_space.sample() on [https://gym.openai.com/envs/PredictObsCartpole-v0](https://gym.openai.com/envs/PredictObsCartpole-v0) the np.inf in the observation space bounds for CartPole cause it to return nan for all samples which isn't accepted in the range.

Options I can see are either to only allow real numbers in space bounds, or to have .sample() function inside the box space to choose a random number that isn't nan if the bounds is np.inf (potentially selecting from a normal distribution)

I think the first is a better alternative because while there mighn't be a theoretical upper limit to the velocity of the cart if the sample return a number like 17239817329817329871298371932 then it's not very useful. It would be better to couple this with the hard limits on observation spaces and just force the environment to be contained to reasonable range.

**Comment by gdb** [comment]
I believe @joschu had thoughts on this, and was ok with `.sample()` returning `nan`s in this case — I don't recall the details though.

**Comment by JKCooper2** [comment]
It would mean that action_space.sample() wouldn't be valid for all environment though which would render a lot of agents that use exploration methods like epsilon greedy unable to solve the environment. I think it should be reasonable to expect space.contains(space.sample()) to always return true regardless of the environment

**Comment by JKCooper2** [comment]
Just realised PR already exists: https://github.com/openai/gym/pull/210
