### ISSUE TITLE
Environment not closing cleanly on macOS Big Sur

### ISSUE THREAD

**Issue by inwaves** [openai/gym#2160]
Hi folks,

I'm encountering an error closing any environment on gym 0.18.0 and macOS Big Sur 11.0.1. I can force quit the window and after a few seconds it'll quit, but this kills my notebook Python kernel, so I have to re-run all cells. 

Where would I start looking for an error traceback? I don't get anything in my notebook (probably because the kernel is closed).

<img width="608" alt="image" src="https://user-images.githubusercontent.com/8530685/104918579-a3eeb600-599d-11eb-8051-137188ffd5a5.png">

I'm running a really simple example:
```env = gym.make("CartPole-v0")
env.reset()

for _ in range(1000):
    env.render()
    env.step(env.action_space.sample()) # Take a random action
    
env.close()

**Comment by JordanCosio** [comment]
I am facing the same problem. I've run my code well on windows but on Big Sur, the window crashes and I can't close it. I need to force the closing and to restart the kernel. 
I didn't forget the "env.close()" and I tried with the example provided above and I'm having the exact same issue.
Please provide a fix

**Comment by Mukilan-Krishnakumar** [comment]
Hi, 
@jkterry1, you seemed to have closed the issue, but I still ran into the same problem. 

I am running a very simple CartPole experiment:
`environment_name = 'CartPole-v0'
env = gym.make(environment_name)
episodes = 5
for episode in range(1, episodes+1):
    state = env.reset()
    done = False
    score = 0
    while not done:
        env.render()
        action = env.action_space.sample()
        n_state, reward, done, info = env.step(action)
        score += reward
    print(f'Episode : {episode} Score : {score}')
    
env.close()`

I have to manually force quit the window, which kills the kernel.

**Comment by Mukilan-Krishnakumar** [comment]
Hi,
@jkterry1, you seemed to have closed the issue, but I still ran into the same problem.

I am running a very simple CartPole experiment:
```python
environment_name = 'CartPole-v0'
env = gym.make(environment_name)
episodes = 5
for episode in range(1, episodes+1):
state = env.reset()
done = False
score = 0
while not done:
env.render()
action = env.action_space.sample()
n_state, reward, done, info = env.step(action)
score += reward
print(f'Episode : {episode} Score : {score}')

env.close()
```

I have to manually force quit the window, which kills the kernel.

**Comment by alingavriliuc** [comment]
I'm facing the same problem

**Comment by Viddesh1** [comment]
This is what I did:-

Import pygame

pygame.quit() 

https://github.com/Viddesh1/RL/blob/main/Mini_Project.ipynb
