### ISSUE TITLE
How is the action relate to the joint velocity in Mujoco-Antv2 and how it calculate? (also other Mujoco env)

### ISSUE THREAD

**Issue by johnnylin110** [openai/gym#2161]
Hello,
I was working on mujoco env Ant-v2,  and I found there are many people talking about what state(111-dim),action(8-dim),reward is , like #585 .
However, I want to know the relation about the Joint velocity and action's relation(non-linear or linear relation)，that is , how the action infect the Joint velocity and how it calculate?
I know the Ant-v2 state has 111-dim and we can get the joint velocity from state[19 :19+8] (where each action relate to one joint velocity )
Because I need to set the constraint about the joint velocity when training , so i want to know the relation to train my action well , I want to know what will the joint velocity be calculate before the env.step() . 
Thanks for helping me , if there is any other detail I need  to provide , please tell me , thanks!

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
