### ISSUE TITLE
Clone/restore Atari state does not work as expected

### ISSUE THREAD

**Issue by wubdub** [openai/gym#2163]
In this [PR](https://github.com/openai/gym/pull/575/commits) @shelhamer added the ability to clone/restore the state of the Atari emulator. When I test this API, it appears the randomness is not captured as it doesn't work as I would expect. Minimum example:
```
from gym.envs import atari

TOTAL_TESTS = 10
equals = 0
for _ in range(TOTAL_TESTS):
    g = atari.AtariEnv(game='pong', obs_type='image')
    g.reset()

    # Clone the env state and take a step
    save0 = g.clone_full_state()
    g.step(0)
    # Save the state we landed in
    save1 = g.clone_full_state()

    # Restore to the same initial state & take the same step
    g.restore_full_state(save0)
    g.step(0)
    save2 = g.clone_full_state()

    # Save2 should equal Save1 as they were reached by taking the same action from Save0
    equals += int(np.array_equal(save1,save2))
    
print(f'{equals} of {TOTAL_TESTS} matched')
```

Prints ```2 of 10 matched``` the first time I run it instead of the expected 10 of 10. Am I misunderstanding the clone/restore API?

**Comment by wubdub** [comment]
Bump ;)

**Comment by jkterry1** [comment]
Assignee: @JesseFarebro

**Comment by JesseFarebro** [comment]
I can confirm this is now fixed via https://github.com/mgbellemare/Arcade-Learning-Environment/pull/401.
