### ISSUE TITLE
Why function _get_obs in blackjack-v0 return the first card of the dealer instead of the sum of his hand?

### ISSUE THREAD

**Issue by renatonankran** [openai/gym#2165]
[https://stackoverflow.com/questions/65889339/is-there-a-reason-for-returning-only-the-first-card-of-the-dealer-in-openai-blac](https://stackoverflow.com/questions/65889339/is-there-a-reason-for-returning-only-the-first-card-of-the-dealer-in-openai-blac)

**Comment by RedTachyon** [comment]
@renatonankran Because this is how the game of Blackjack works, you only see one card of the dealer's hand.

@jkterry1 Closable
