### ISSUE TITLE
car_racing has memory leak!

### ISSUE THREAD

**Issue by MGokcayK** [openai/gym#2168]
Hello everyone,

I work on the car_racing env. for my project. I want to add some different things on the env. Thus, I copied the codes from https://github.com/openai/gym/blob/master/gym/envs/box2d/car_racing.py and started to modify them for my purpose. I found that the env. has memory leak.  I got vertex buffer error which says the "__ length __" argument is too large. I search it and I got nothing. I undo the modifications and the leak still there. Memory usage increase upto 3GB. After that, I looked my local gym (which version is 0.10.5 at that time) files and saw the difference of file. I wrote old version of implementation and leak has gone which means that the usage of memory decrease to 76MB. So, the problem is usage of pyglet.graphics.vertex_list instead of usage of glBegin / glEnd methods. 

To make sure, I updated gym and rerun the env. and still the vertex_list usage has leak. I look at commits on the file and saw that the last commit https://github.com/openai/gym/commit/81508d348d543555bde95d8b4ed1711c810b008d#diff-8f9e342a50c65e66923c4b20efde695f0ce02e0a40873e82ce23f5eb7376b754 has changed the usage. 

I want to share my experience with you and let you reconsidering the last commit. Therefore, I open this issue. 
Have a nice day :)

----------
Specs of PC:
- OS : Windows 10
- CPU : i7-8700K
- GPU : Nvidia 1070Ti
- RAM :  16 GB

**Comment by jkterry1** [comment]
This should be closed by other PRs for this
