### ISSUE TITLE
error while trying to install

### ISSUE THREAD

**Issue by lars5038** [openai/gym#2169]
Ive tried to clone the git and to install it like described on the website but the i got this error:
`ERROR: Command errored out with exit status 1: 'c:\program files\python39\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\larsf\\AppData\\Local\\Temp\\pip-install-v14nl52b\\pillow_21fde82484b243ae83dcd30690b49315\\setup.py'"'"'; __file__='"'"'C:\\Users\\larsf\\AppData\\Local\\Temp\\pip-install-v14nl52b\\pillow_21fde82484b243ae83dcd30690b49315\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\larsf\AppData\Local\Temp\pip-record-yww75yv1\install-record.txt' --single-version-externally-managed --user --prefix= --compile --install-headers 'C:\Users\larsf\AppData\Roaming\Python\Python39\Include\Pillow' Check the logs for full command output.`

**Comment by derossm** [comment]
Pillow 7.2 is not compatible with Python 3.9 under windows, so you need to clone the repository and edit setup.py to change line 32
`          'scipy', 'numpy>=1.10.4', 'pyglet>=1.4.0,<=1.5.0', 'Pillow<=7.2.0', 'cloudpickle>=1.2.0,<1.7.0',` to
`          'scipy', 'numpy>=1.10.4', 'pyglet>=1.4.0', 'Pillow>=7.2.0', 'cloudpickle>=1.2.0',`
and then `pip install -e .` will work on windows.

This may or may not break other parts of gym, but is required to make it work at all. I don't know if the authors had a specific reason for restricting the versions, but that would need to be addressed either way to make it work now.

**Comment by ferreirajoaouerj** [comment]
One other solution that worked for me, using conda, was:
`pip uninstall pillow`  - remove all previous installations
`pip install pillow` - install newest version 8.x
`conda install -c conda-forge gym`
