### ISSUE TITLE
In mujoco Hopper-v2 Environment what are the observations' names and actions' names and what they represent

### ISSUE THREAD

**Issue by hellfireworld** [openai/gym#2173]
In mujoco such as Hopper-v2 what are the observations' names and actions' names . (If you can help I would like to read them sorted as you get them from the environment). For example If I want to train a neural network with the features when I save them with pandas in a csv file, I would like to know the real names of the features/observations' columns and actions because I assigned them like var1,var2...var11,  action1, action2, action3. So I can understand better the environment. If you have any documentation or wiki that I can find these it would be appreciated because the only thing I found was this issue https://github.com/openai/gym/issues/971 and it describes... how can I  see (only) the values when they pass them after concatenation. 

PS: Maybe they have something to do with q pos( x,y,z) and q vel

Thank you.

**Comment by lishanwu135** [comment]
Good question! I am also interested in this question. I would like to know the physical meaning of each variable. Hope someone will answer this question soon.

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
