### ISSUE TITLE
Strange behavior in Freeway

### ISSUE THREAD

**Issue by Nightaway** [openai/gym#2186]
The acts has no response when agent got a reward. 
![00107](https://user-images.githubusercontent.com/1297050/109777547-d1867a80-7c3e-11eb-92ca-369ec058af76.png)
![00108](https://user-images.githubusercontent.com/1297050/109777556-d2b7a780-7c3e-11eb-80ff-1172bb2b522a.png)
![00109](https://user-images.githubusercontent.com/1297050/109777558-d3503e00-7c3e-11eb-9d88-1d0c415735f4.png)
![00110](https://user-images.githubusercontent.com/1297050/109777562-d3503e00-7c3e-11eb-9939-ae244675ba4d.png)

**Comment by Nightaway** [comment]
the act log can be found in https://github.com/junhyukoh/nips2015-action-conditional-video-prediction

**Comment by Nightaway** [comment]
the act log can be found in https://github.com/junhyukoh/nips2015-action-conditional-video-prediction

**Comment by JesseFarebro** [comment]
I'm not sure what I'm looking at here? After the chicken reaches the top are you saying the actions don't have any effect? I'm not sure how these images were generated. It could be the case where sticky actions were enabled and a NOOP was stuck for multiple timesteps. There's not enough information to go off of here.

If you have additional information feel free to create an issue @ https://github.com/mgbellemare/Arcade-Learning-Environment
