### ISSUE TITLE
Update pinned dependencies

### ISSUE THREAD

**Issue by pikeas** [openai/gym#2193]
https://github.com/openai/gym/blob/8a721ace460cbaf8c3e6c03c12d06c616fd6e1e8/setup.py#L32

Dependencies on Pillow and pyglet are pinned to max versions. This makes gym installation and usage very finicky under Python 3.9 and/or macOS Big Sur. Please unpin these dependencies, or document why they're necessary.

**Comment by jkterry1** [comment]
These should all be fixed now
