### ISSUE TITLE
MountainCar environment: is the reward calculation incorrect?

### ISSUE THREAD

**Issue by zha** [openai/gym#2194]
According to the documentation, the reward should be 0 if the agent reaches the target position of beyond 0.5. However, the reward can never be 0 according to implementation in the `step()` method of the `MountainCarEnv` class. So I am wondering if this is a mistake or something that is intended?

**Comment by fearofcode** [comment]
Yeah, seems like a bug to me. There is an open PR to fix this: https://github.com/openai/gym/pull/2123

**Comment by zha** [comment]
Thank you for letting me know about the existing PR. 

TBH, as the matter of fact, this should have a very minimal impact on the results. But again, if we stick to the definition, then this is certainly a bug.
