### ISSUE TITLE
Error while checking 

### ISSUE THREAD

**Issue by parthagrawal02** [openai/gym#2198]
(spinningup) parthagrawal02@Parths-MacBook-Air spinningup % python -m spinup.run ppo --hid "[32,32]" --env LunarLander-v2 --exp_name installtest --gamma 0.999

zsh: illegal hardware instruction  python -m spinup.run ppo --hid "[32,32]" --env LunarLander-v2 --exp_name

**Comment by jkterry1** [comment]
This should be fixed with gym master and the newest version of macos on apple silicon, but if it is not let us now
