### ISSUE TITLE
Pillow pinned to <=7.2.0 but security hole found in that version

### ISSUE THREAD

**Issue by grecoe** [openai/gym#2199]
Build warning:

A security issue was found in python-pillow before version 8.1.1. The PDF parser has a catastrophic backtracking regex that could be used in a denial of service (DoS) attack.

But trying to push it fails to resolve dependencies due to pin.

**Comment by mg64ve** [comment]
I am getting the following error @grecoe:

```
ERROR: Cannot install Tensorforce and tensorforce==0.6.2 because these package versions have conflicting dependencies.

The conflict is caused by:
    tensorforce 0.6.2 depends on Pillow==8.1.1
    gym 0.18.0 depends on Pillow<=7.2.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
The command '/bin/sh -c pip3 install -e tensorforce' returned a non-zero code: 1
```

Any chance to get this solved?

**Comment by grecoe** [comment]
@mg64ve , I'd open up another ticket. I never even got to the build, was just trying to resolve dependencies so we could ditch any reliance on pillow <8.1.1 due to the security warning. But if multiple reports come in, maybe someone will have a look.

**Comment by mg64ve** [comment]
Thanks @Gordonjo . This project does not seem to be maintained. But indeed it is very useful and also many other projects rely on it.

**Comment by jkterry1** [comment]
Fixed in recently merged PRs
