### ISSUE TITLE
ERROR: VideoRecorder encoder exited with status 1

### ISSUE THREAD

**Issue by RaihanKhan1970** [openai/gym#2201]
New to Open AI and would appreciate help.  Everything is going smoothly but can't seem to record or play back the videos.  Getting "ERROR: VideoRecorder encoder exited with status 1".

I am using Ubuntu 20

**Comment by Khoa-NT** [comment]
I'm also having the same issue in my environment with python 3.8.
However, Python 3.7 on Google Colab is running normally. 
Still debugging.

**Comment by RaihanKhan1970** [comment]
I have a workaround.  I'm training my models on my Jupyter framework and then uploading my models and recording videos on Colab.

**Comment by Khoa-NT** [comment]
I don't know it's related to Jupyterlab 3 or not.
Previously, I'm using Jupyterlab 2 and it worked normally.

**Comment by Khoa-NT** [comment]
I fixed it. Follow this [post](https://github.com/openai/gym/issues/1925).

- Download gym from source (the master branch)  and install with `python setup.py install` 
- Or use `gym==0.17.3`

I didn't notice Colab using `gym==0.17.3`
