### ISSUE TITLE
Running setup.py install for mujoco-py ... error

### ISSUE THREAD

**Issue by jgp-github** [openai/gym#2207]
ERROR: Command errored out with exit status 1:
     command: 'D:\anaconda3\envs\py36\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jgp\\AppData\\Local\\Temp\\pip-install-3hovz2ry\\mujoco-py_77abc2bca99347949f8ff21e735ca545\\setup.py'"'"'; __file__='"'"'C:\\Users\\jgp\\AppData\\Local\\Temp\\pip-install-3hovz2ry\\mujoco-py_77abc2bca99347949f8ff21e735ca545\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\jgp\AppData\Local\Temp\pip-record-d71pqdhc\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\anaconda3\envs\py36\Include\mujoco-py'
         cwd: C:\Users\jgp\AppData\Local\Temp\pip-install-3hovz2ry\mujoco-py_77abc2bca99347949f8ff21e735ca545\
    Complete output (7 lines):
    running install
    running build
    Removing old mujoco_py cext C:\Users\jgp\AppData\Local\Temp\pip-install-3hovz2ry\mujoco-py_77abc2bca99347949f8ff21e735ca545\mujoco_py\generated\cymj_1.50.1.68_36_windowsextensionbuilder_36.so
    running build_ext
    building 'mujoco_py.cymj' extension
    creating C:\Users\jgp\AppData\Local\Temp\pip-install-3hovz2ry\mujoco-py_77abc2bca99347949f8ff21e735ca545\mujoco_py\generated\_pyxbld_1.50.1.68_36_windowsextensionbuilder\temp.win-amd64-3.6\Release\Users\jgp\AppData\Local\Temp\pip-install-3hovz2ry\mujoco-py_77abc2bca99347949f8ff21e735ca545
    error: could not create 'C:\Users\jgp\AppData\Local\Temp\pip-install-3hovz2ry\mujoco-py_77abc2bca99347949f8ff21e735ca545\mujoco_py\generated\_pyxbld_1.50.1.68_36_windowsextensionbuilder\temp.win-amd64-3.6\Release\Users\jgp\AppData\Local\Temp\pip-install-3hovz2ry\mujoco-py_77abc2bca99347949f8ff21e735ca545': 系统找不到指定的路径。
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'D:\anaconda3\envs\py36\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\jgp\\AppData\\Local\\Temp\\pip-install-3hovz2ry\\mujoco-py_77abc2bca99347949f8ff21e735ca545\\setup.py'"'"'; __file__='"'"'C:\\Users\\jgp\\AppData\\Local\\Temp\\pip-install-3hovz2ry\\mujoco-py_77abc2bca99347949f8ff21e735ca545\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\jgp\AppData\Local\Temp\pip-record-d71pqdhc\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\anaconda3\envs\py36\Include\mujoco-py' Check the logs for full command output.

**Comment by jkterry1** [comment]
Issue is not in gym itself, please file with mujuco-py
