### ISSUE TITLE
CartPole-v0 results in "undefined behavior"

### ISSUE THREAD

**Issue by dorajam** [openai/gym#221]
I tried running the basic CartPole environment and I got the following warnings. 
When running it, the cartpole just simply runs out of my window and it all freezes. 

Anyone had the same problem before?

```
INFO:gym.envs.registration:Making new env: CartPole-v0
[2016-06-20 11:40:58,912] Making new env: CartPole-v0
WARNING:gym.envs.classic_control.cartpole:You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.
[2016-06-20 11:40:59,334] You are calling 'step()' even though this environment has already returned done = True. You should always call 'reset()' once you receive 'done = True' -- any further steps are undefined behavior.
WARNING:gym.core:Observation '[ 0.12323865  0.05115398 -0.44006244 -1.57913373]' is not contained within observation space 'Box(4,)'.
[2016-06-20 11:40:59,485] Observation '[ 0.12323865  0.05115398 -0.44006244 -1.57913373]' is not contained within observation space 'Box(4,)'.
```

**Comment by gdb** [comment]
1. Once you see done=True, per the warning, you should call reset. i.e. you should have a line somewhere of the form `if done: env.reset()`
2. I think once the cartpole is out of the window, it's not actually frozen — just rendering off-screen!

**Comment by jietang** [comment]
@dorajam any updates here?

**Comment by dorajam** [comment]
Yes, I got it, thank you! The problem was exactly what Greg said, the window just kept rendering without ever resetting the environment.

**Comment by madvn** [comment]
Is it possible to suppress this warning? Thanks.
