### ISSUE TITLE
Seed Returned by gym.seeeding.np_random not usable with numpy Random Generators

### ISSUE THREAD

**Issue by maximilianreimer** [openai/gym#2210]
Hi everyone,
I just stumble upon a minor bug (?): The seed returned by `np_random, seed = gym.seeding.np_random(seed)` can not be used to seed another `numpy.random.RandomGenerator(seed)` or reseed and exiting one (e.g. `numpy.random.seed(seed)`) since those except numbers between between 0 and 2**32 - 1.  I think that should be possible, shouldn't it? 

The concrete failure case I have is: 
```python
import numpy as np
from gym.utils import seeding

user_given_seed = None
np_random, seed = seeding.np_random(user_given_seed)

# since in some places np.random.randn or similar is used we want to seed the global numpy random generator as well
np.random.seed(seed)
```
Results in: 
```
...
   np.random.seed(seed)
  File "mtrand.pyx", line 244, in numpy.random.mtrand.RandomState.seed
  File "_mt19937.pyx", line 166, in numpy.random._mt19937.MT19937._legacy_seeding
  File "_mt19937.pyx", line 180, in numpy.random._mt19937.MT19937._legacy_seeding
ValueError: Seed must be between 0 and 2**32 - 1
```

And I think the user might expect that a generator seeded by returned seed it the same as the one that has been returned by the methods. 

```
import numpy as np
from gym.utils import seeding

# setting this to 1 resulted in a seed in the valid range. 
user_given_seed = 1
np_random, seed = seeding.np_random(user_given_seed)

np_random_2 = np.randm.RandomState(seed)

asser np_random_2.random() == np_random() # fails
```
As far as I can see that's not the case currently. 

I am using:
* Python 3.9
* gym 0.15.3

**Comment by RedTachyon** [comment]
So to the best of my understanding, the issue here is that the gym seeding uses 8-bit bigint (uint64), whereas numpy only accepts 4-bit ints (uint32, as stated in the docs).

I think this can be fixed by setting create_seed (seeding.py#L49) to only use 4 bits. Or ditching the seeding tools entirely as per #1663

**Comment by jkterry1** [comment]
Closing in favor of the PR
