### ISSUE TITLE
Training terminates at EP40 every time 

### ISSUE THREAD

**Issue by sowbobo12000** [openai/gym#2211]
Hello, whenever I train the model, it always terminates when ep is 40. the below message is what I get : 
Ep 40   Last score: -18.08      Moving average score: 2.58
Track generation: 1056..1324 -> 268-tiles track
Track generation: 1092..1377 -> 285-tiles track
zsh: segmentation fault  python3 train.py --render
(motion) kyuyeon@gimgyuyeon-ui-MacBookPro pytorch_car_caring % /usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 6 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

I am assuming that this might an issue of gym, but I am not sure how to fix it. Could you please give me some idea? Thank you!

**Comment by sowbobo12000** [comment]
I fixed it!

**Comment by Bh4r4t** [comment]
Hi @sowbobo12000, why was the error coming and how did you fixed it?
