### ISSUE TITLE
Installation of gym on m1

### ISSUE THREAD

**Issue by bjrnfrdnnd** [openai/gym#2213]
Hello,

did anyone succeed to install gym on m1 without rosetta2?
I am using a fresh conda python3.8 environment with miniforge, using arm architecture.

**Comment by Anonymous7code** [comment]
This might help you :-
<p>
OpenAI Gym  on Apple Macbook arm M1, using miniconda3, Miniforge3-MacOSX-arm64.sh from <a href='https://github.com/conda-forge/miniforge/releases/tag/4.9.2-3'>here</a>

Also installed PyTorch cpu arm version from source (bit of a hassle, also compiling arm version of bazel), and PyBullet 3.07 (pip3 install pybullet). Running the OpenGL3 rendering is smooth, tested using
</p>
python3 -m pybullet_envs.examples.enjoy_TF_AntBulletEnv_v0_2017may
<br>
<br>
<p>
Gym is written in Python, so there should be a no problem with the Apple M1 chip. There's some sort of rendering problems with the newest version of MacOs . It looks like it might take awhile.</p>


</p>

**Comment by woohan** [comment]
Which command did you use? pip3 install gym? I also failed to install gym on my m1 Macbook. Environment is miniforge3

**Comment by jkterry1** [comment]
Changes in master should fix all of this now.
