### ISSUE TITLE
call step function with a list of same environments

### ISSUE THREAD

**Issue by weiguowilliam** [openai/gym#2214]
I need a list of the same environments to work step by step. Here's the test code. It seems that we can call each environment `list_of_envs[j]` and it still can work properly. I just wonder why? Because I think in this loop t = 0, `env` is updated, but `list_of_envs[j]` is not updated, right? So when t=1, `list_of_envs[j]` should still have the state as t = 0 and return the same observation as t = 0, but actually it doesn't. The returned observation changed which means `list_of_envs[j]` also updates. That confuses me. Could you help me explain that? Thank you in advance.
```
import gym

list_of_envs = []

for _ in range(2):
    env = gym.make('CartPole-v0')
    env.seed(0)
    env.reset()
    list_of_envs.append(env)

for t in range(3):
    for j in range(2):
        action = 0
        env = list_of_envs[j]
        observation, reward, done, info = env.step(action)
        print(observation)
```

Here's the output:

```
[-0.04363321 -0.14877061  0.01284913  0.2758415 ]
[-0.04363321 -0.14877061  0.01284913  0.2758415 ]
[-0.04660862 -0.3440735   0.01836596  0.5725492 ]
[-0.04660862 -0.3440735   0.01836596  0.5725492 ]
[-0.05349009 -0.5394481   0.02981694  0.87096095]
[-0.05349009 -0.5394481   0.02981694  0.87096095]
```

**Comment by RedTachyon** [comment]
@weiguowilliam This is just how Python works. First you create two separate instances of the env and store them in `list_of_envs`. Then for each timestep you grab the first instance, make an action, grab the second instance, make an action. And then repeat, so again you grab both instances in a row. You can try to "unroll" the loop, so write out every line as it happens, it might become clearer then.

@jkterry1 closable
