### ISSUE TITLE
OpenAI Gym environment CarRacing-v0

### ISSUE THREAD

**Issue by infinite789** [openai/gym#2216]
Upon running:

`import gym`

`env = gym.make('CarRacing-v0')`

.. the following warning occurs: 
`C:\Users\bddra\Anaconda3\lib\site-packages\gym\logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32`
  ` warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))`

This [issue](https://github.com/openai/roboschool/issues/169) from `openai/roboschool`  reports the same issue but for different environment and sounds like an easy fix?

**Comment by thedivyanshuyadav** [comment]
@infinite789  Set logger level to 40.
Try this code :
```
import gym
gym.logger.set_level(40)
env = gym.make('CarRacing-v0')
```

Hope that might solve this issue #2216.
