### ISSUE TITLE
Unfunctional data structure when rendering with VideoRecorder

### ISSUE THREAD

**Issue by Osrip** [openai/gym#2224]
I would like to render gym experiments into videos.
When running (shortened to essential lines):
```
dones = [False] * self.batch_size
video_env = self.envs[0]
video_recorder = VideoRecorder(video_env, video_path+video_name, enabled=record)
for i, (env, action, done) in enumerate(zip(self.envs, actions, dones)):
              if record and i == 0:

                    env.render()
                    video_recorder.capture_frame() # <--- THIS CAUSES ERROR
                if not done:
                    state, reward, done, _ = env.step(action)
                    fitnesses[i] += reward
                    if not done:
                        states[i] = state
                    dones[i] = done
```
(The code processes all environments in a batch simultaneously)
I get the following error message:
```
AttributeError: 'ImageData' object has no attribute 'data'
ImportError: sys.meta_path is None, Python is likely shutting down
```
which is caused by the following line in rendering.py, which is called by video_recorder.capture_frame() :

`arr = np.fromstring(image_data.data, dtype=np.uint8, sep='')
`
Does anyone have an idea what causes the image_data instance not to have a .data attribute?

**Comment by jkterry1** [comment]
@vwxyzjn does your #2300 PR close this?

**Comment by vwxyzjn** [comment]
@Osrip did you return an RGB numpy array when the environment does `env.render(‘rgb_array’)`?

**Comment by vwxyzjn** [comment]
@jkterry1 I think my #2300 will help with this.
