### ISSUE TITLE
Handling action spaces with np.complex64 type

### ISSUE THREAD

**Issue by mauro-belgiovine** [openai/gym#2234]
I am new to Gym, so I apologize in advance if I am asking something obvious. 

I am trying to define a continuous action space with gym.spaces.Box and I would like to use np.complex64 as dtype.

`action_space = gym.spaces.Box(low=-1.0, high=1.0, shape=(Nt, NRF), dtype=np.complex64)`

The problem is that I get the following error when sampling from the action space:

```
In[5]: x = action_space.sample()
/home/englab/mauro.belgiovine/venv/tf-latest/lib/python3.6/site-packages/gym/spaces/box.py:96: ComplexWarning: Casting complex values to real discards the imaginary part
  else self.high.astype('int64') + 1
Traceback (most recent call last):
  File "/home/englab/.local/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-0a744ac15331>", line 1, in <module>
    x = space.sample()
  File "/home/englab/mauro.belgiovine/venv/tf-latest/lib/python3.6/site-packages/gym/spaces/box.py", line 119, in sample
    size=bounded[bounded].shape)
  File "mtrand.pyx", line 1098, in numpy.random.mtrand.RandomState.uniform
TypeError: Cannot cast array data from dtype('complex64') to dtype('float64') according to the rule 'safe'
```

Am I missing something? How is the support for complex numbers within the gym framework?

**Comment by RedTachyon** [comment]
It does seem that numpy doesn't support sampling from distributions over complex numbers. An easy change would be repeating the process in https://github.com/openai/gym/blob/master/gym/spaces/box.py#L97 for the real and imaginary parts separately. 

On the upside, it seems to only be an issue when sampling. Other than that, in principle if you're developing a custom environment with complex actions, gym shouldn't have any problems with that.

**Comment by jkterry1** [comment]
I don't believe that this should be supported natively in Gym, but if I'm missing something here someone is free to explain why.
