### ISSUE TITLE
[CliffWalking-v0] Done != True when reward == -100

### ISSUE THREAD

**Issue by MLTrap** [openai/gym#2236]
For the 'CliffWalking-v0' env, is the `done` flag suppose to throw true when an agent reaches a cliff tile? Currently it does not.

<img width="110" alt="Screen Shot 2021-06-03 at 10 11 10 AM" src="https://user-images.githubusercontent.com/84875378/120684834-067bb680-c454-11eb-8e49-b41057e3e653.png">

[MazeCliffByHand.ipynb.zip](https://github.com/openai/gym/files/6593257/MazeCliffByHand.ipynb.zip)

**Comment by RedTachyon** [comment]
@MLTrap As per Sutton & Barto (http://incompleteideas.net/book/bookdraft2018jan1.pdf, page 106), this is intended behavior - cliff sends you to the start, and only the final cell is a "final" state, i.e. ending the episode

**Comment by RedTachyon** [comment]
@jkterry1 closable
