### ISSUE TITLE
Weird results on the evaluation page

### ISSUE THREAD

**Issue by SimonRamstedt** [openai/gym#224]
Hey, just made a [submission](https://gym.openai.com/evaluations/eval_jCJs99SpSjjoya6MTkg) for InvertedDoublePendulum but results are weird/wrong:

Only one video is displayed and it is falsely linked with episode 0. The problem might be that I'm alternating training and testing phases and I'm closing the monitor after each test phase and restart it before the next test with `resume=True`. I'm doing this because the algorithm is off-policy and therefore the training episodes are not representative (exploration noise is added to the policy during training).  The other issue is that the monitor counts the test episodes as normal learning episodes even though the algorithm isn't learning during test.

I uploaded my [monitor output folder](https://www.dropbox.com/sh/6np5w8eftdxvavo/AAByj4FfjmBpm9tvborsIFFca?dl=0) and this is my [train-test loop](https://github.com/SimonRamstedt/ddpg/blob/master/run.py).

**Comment by tlbtlbtlb** [comment]
The learning performance graph is based on how many episodes are needed to train the agent, so you have to include all the training runs to make a fair comparison with other algorithms. The monitor system intentionally makes it hard to exclude some.

Rather than alternating train and test, it's better to gradually reduce the exploration noise. Ideally your agent can figure out when to decrease noise itself as its performance increases, rather than rely on a pre-defined schedule.

**Comment by SimonRamstedt** [comment]
Hey Mr Blackwell,

Thanks for the answer! The algorithm concerned is not mine,  it's [DDPG](http://arxiv.org/abs/1509.02971) by Lillycrap et. al. Even though reducing the noise over time sounds reasonable it's not what the DDPG does. In the DDPG case alternating test and training phases are necessary for the designer to see how the performance of the actual policy is, since for the usual training/exploration a different (noisy) policy is used. I alleviated the problem a bit now by doing only few test evaluations until the agent has reached threshold performance. Another option would be to start a second environment only for the tests. So I guess the training/testing issue is secondary.

One little thing remains however: Only one video is displayed and it is falsely linked with episode 0
:P 

Cheers
- Simon

**Comment by tlbtlbtlb** [comment]
Every time you open the monitor it starts counting at episode 0 again. It's really supposed to stay open the entire lifetime of the training.

It's normal to see alternating low and high rewards for 2-phase algorithms like this. The Scoreboard looks at the best average across any 100 consecutive episodes, so it's optimal to make your test session 100 episodes

**Comment by tlbtlbtlb** [comment]
The convention of counting all episodes -- both test & train --  comes from a robotics perspective where both kinds of episodes wear out your robot hardware and seems more applicable to agents learning online in the real world.

**Comment by SimonRamstedt** [comment]
Yes I see, that sounds reasonable. Then I'll simply keep the monitor on. Thanks! The 100 episode test session is exactly what I did now. In some cases this can get pretty long however. 100 episodes x 10k steps = 1M steps for InvertedDoublePendulum. Thats as long as my maximum total training time :P
