### ISSUE TITLE
reset() calls from __init__ ?

### ISSUE THREAD

**Issue by srvanrell** [openai/gym#2242]
Some envs in classic_control call `reset()` in their `__init__.py` and others don't. 
Is there any rule about it? 

Do
---
https://github.com/openai/gym/blob/ee5ee3a4a5b9d09219ff4c932a45c4a661778cd7/gym/envs/classic_control/continuous_mountain_car.py#L64

Don't
-------
https://github.com/openai/gym/blob/ee5ee3a4a5b9d09219ff4c932a45c4a661778cd7/gym/envs/classic_control/mountain_car.py#L84
https://github.com/openai/gym/blob/ee5ee3a4a5b9d09219ff4c932a45c4a661778cd7/gym/envs/classic_control/cartpole.py#L94

**Comment by jkterry1** [comment]
It should not be called in init if done properly.

**Comment by jkterry1** [comment]
Closing in favor of PR
