### ISSUE TITLE
Possibly Erroneous Reward Signal of MountainCar Environment

### ISSUE THREAD

**Issue by Bick95** [openai/gym#2245]
Hello,

In the [description](https://github.com/openai/gym/blob/master/gym/envs/classic_control/mountain_car.py#L40-L43) of the [MountainCar](https://gym.openai.com/envs/MountainCar-v0/)-environment (featuring the discrete action space), concerning the reward signal, it is stated that:

```
Reward:
         Reward of 0 is awarded if the agent reached the flag (position = 0.5)
         on top of the mountain.
         Reward of -1 is awarded if the position of the agent is less than 0.5.
```
However, in the step-function associated with that environment, the [reward is simply defined](https://github.com/openai/gym/blob/ee5ee3a4a5b9d09219ff4c932a45c4a661778cd7/gym/envs/classic_control/mountain_car.py#L104) as `reward = -1.0`. 

Given this, I am wondering how the reward is supposed to become 0 if the car's destination is reached. Maybe I am just overlooking something, but to me it feels as if the reward signal wasn't implemented as described in the description and is thus not useful for training agents on this environment.

**Comment by valayDave** [comment]
@Bick95: I was reading the code and I felt the same when I initially saw your comment but there is a nuance here. 

The `step` function also passes a [done](https://github.com/openai/gym/blob/ee5ee3a4a5b9d09219ff4c932a45c4a661778cd7/gym/envs/classic_control/mountain_car.py#L101) object which makes the user of the `Environment` know the episode is complete.  

In context to mountain car, I have noticed that the reward is a measure of how _quickly_ the car reaches the top of the mountain; So minimizing the number of steps _seems to be_ the main objective.
