### ISSUE TITLE
The incorrect end of Atari games

### ISSUE THREAD

**Issue by dibbla** [openai/gym#2247]
Hi guys!

I'm now doing MCTS with Atari game Breakout-v4. To have a snap shot to memorize the  node's state, I'm using this wrapper:

```
from gym.core import Wrapper

class withSnapshot(Wrapper):
    
    def getSnapshot(self):
        return self.env.ale.cloneState()
    
    def loadSnapshot(self,snapshot):
        self.env.ale.restoreState(snapshot)
```

Once I test it separately, it seems to work fine (Cuz I'm running on Jupyter notebook, my render is a little delayed). However, when I rollout the game:

```
def rollout(node):
    
    env.loadSnapshot(node.snapshot)
    
    if node.is_done():
        print('done!!!')
        env.reset()
        env.seed(1995)
        env.loadSnapshot(node.snapshot)
        
    rollout_done=False
    endReward=0
    last=0
    
    while True:
        action = env.action_space.sample()
        _, immediate_reward, rollout_done, _ = env.step(action)
        endReward += immediate_reward
        last += 1
        if rollout_done:
            break

    node.propagate(endReward)
    return endReward
```
The game returns end even when my agent has 4 life. So I print every steps and replay the env with same seed to see what is wrong. One thing need to mention is that this case often happened when agent loses 1 life. But even after I force the incorrect dones to be 'not done', the whole game planned by MCTS may still end early.

BTW, the main program is like following:
```
env=withSnapshot(gym.make("Breakout-v4"))
test=Node(None,None)  #both parent and actions are None

done = False
acList=[]
for i in range(10000):
    
    new_root,action=MCTS(test)
    env.loadSnapshot(test.snapshot)
    _,reward,done,_=env.step(action)
    acList.append(action)
    test.snapshot=env.getSnapshot()
    test.n,test.t=0,0
    test.children=[]
    print("Is done?{}  one step with action:{} reward:{}".format(done,action,reward))
    if done:
        break
```

So it's the problem of my wrapper?

**Comment by jkterry1** [comment]
Assignee: @JesseFarebro

**Comment by JesseFarebro** [comment]
I'm not quite sure what the problem is here. The environment is terminating while you still have lives remaining? If this is the case I don't think you're handling the Gym `TimeLimit` wrapper properly. You should strip out the `TimeLimit` wrapper, a simple way to hack this is to just,

```py
env = gym.make('Breakout-v4')
env = env.env
```

The issue is that the `TimeLimit` wrapper doesn't reset the episode step count when you load a state to do a rollout. You should just remove it altogether, it doesn't make much sense here.
