### ISSUE TITLE
Bug frozen lake

### ISSUE THREAD

**Issue by GiorgioSgl** [openai/gym#2250]
Hi everyone, I meet a problem in the render of the frozen lake. Actually I was testing it and choose the move of the cursor by myself, not random and not even chose by an agent.  

The problem is that it's not following what I'm typing I have tried it on Anaconda and after on Google Colab but the problem persist. If I tell the agent to move down it moves random and I don't understand why.

Here is the code

```
import time
import gym

env = gym.make('FrozenLake-v0')

for i_episode in range(20):
    observation = env.reset()
    for t in range(100):
        env.render()
        #print(observation)
        #action = env.action_space.sample()
        #print(action)
        import re
        
        print("\n")
        print("Introduce where do you want to move:")
        entrada  = re.search(r"\d+", input())
        dia = int(entrada.group(0)) if entrada is not None else None
        observation, reward, done, info = env.step(dia)
        print("\n")
        
        print(type(observation))
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
env.close()
```

And here the output

```
[S]FFF
FHFH
FFFH
HFFG


Introduce where do you want to move:
1


<class 'int'>
  (Down)
[S]FFF
FHFH
FFFH
HFFG


Introduce where do you want to move:
1


<class 'int'>
  (Down)
SFFF
[F]HFH
FFFH
HFFG


Introduce where do you want to move:
1


<class 'int'>
  (Down)
SFFF
[F]HFH
FFFH
HFFG


```

_Note: I have added the symbol '>', because on github the highlight showed in the output it's not visible_

**Comment by GiorgioSgl** [comment]
I think there is some randomization in some where. This is the answer of the professor @philtabor 

> Some proportion of the time the agent will take a random action

**Comment by RedTachyon** [comment]
@GiorgioSgl This is intended behavior, reading from the environment description, "Additionally, the movement direction of the agent is uncertain and only partially depends on the chosen direction. " (https://gym.openai.com/envs/FrozenLake-v0/)

**Comment by RedTachyon** [comment]
@jkterry1 closable
