### ISSUE TITLE
env.render() induces different results in robotics and mujoco environments

### ISSUE THREAD

**Issue by SkittlePox** [openai/gym#2255]
It appears as though the results of running a robotics environment differ based on whether the simulation was rendered using `env.render()` or not. I'm running `FetchEnv` and the way the simulation plays out is consistently different. I'm also calling `env.seed(1)` before resetting each environment and my agent's behavior is completely deterministic.

```
Creating window glfw
achieved goal: [1.67919555 0.77144518 0.41404505]    # calls env.render() each step
achieved goal: [1.68385299 0.76366328 0.41406109]    # does not call env.render()
Creating window glfw
achieved goal: [1.67919555 0.77144518 0.41404505]    # calls env.render() each step
achieved goal: [1.68385299 0.76366328 0.41406109]    # does not call env.render()
```

Might this have something to do with the `_render_callback()` method? I have not overridden this method.

**Comment by MoritzTaylor** [comment]
Could you provide a minimal example as I cannot recreate your results?

And furthermore answer to the following questions would be also helpful:
Which exact environment do you use?
Do you restart the whole script in between changing from env.render() to the version where you do not call env.render() or do you just reset the environment? 
Do you use the same environment instance for this?

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
