### ISSUE TITLE
Protect master branch against direct commits

### ISSUE THREAD

**Issue by mzjp2** [openai/gym#2271]
I would urge to keep the [master branch](https://github.com/openai/gym/commits/master) clean and use the github settings for protected branches to enforce against direct commits to master (including administrators) so that the only way something can hit `master` is via a PR which is squash-merged into `master`. This also helps protect against failing builds/linting against `master` since those checks will block a PR merge if they fail on a PR.

**Comment by jkterry1** [comment]
I do not have permissions to do this. However, I'm the only one with permissions to push to master. Once a PR with complete CI tests is finalized and merged I will refrain from doing so further.

**Comment by jkterry1** [comment]
Master is also now fixed so tests pass, my apologies.
