### ISSUE TITLE
Inclusion of Changelog

### ISSUE THREAD

**Issue by jkterry1** [openai/gym#2275]
In #2259, @araffin suggested including release notes in a changelog instead of just in github releases like SB3. This has two ostensible benefits:

-It can make creating full GitHub release notes earlier since they release exist. On a personal level for other libraries I've maintained though, I've found dealing with this in PRs more annoying than just going through commits, and ultimately this matter only impacts me personally.
-It helps people based off master, which is a fair point. In libraries like SB3, there's a lot of people using master for good reason. I don't believe this is something that would ever be done under normal circumstances for Gym though? If people disagree with me on this I can go ahead and include a proper changelog.

**Comment by araffin** [comment]
>In #2259, @araffin suggested including release notes in a changelog instead of just in github releases like SB3. This has two ostensible benefits:

As an additional remark, just putting release notes in Github releases is fine as long as the releases don't take took long to be released (something we do in SB3, where each release may take some months before we consider it reliable enough) and that nothing is forgotten.
