### ISSUE TITLE
API Compliance Testing

### ISSUE THREAD

**Issue by jkterry1** [openai/gym#2278]
To help users with creating custom environments, we should have a user test for environments to ensure the Gym API is properly followed, similar to what PettingZoo has. The easiest solution is to upstream the checker in SB3.

Crosspost from https://github.com/DLR-RM/stable-baselines3/issues/525

**Comment by amtamasi** [comment]
I'd be interested in picking this up if nobody else has started work on it!

**Comment by jkterry1** [comment]
Add far as I know no one has yet :)

**Comment by amtamasi** [comment]
Great, I'll get working on it then!

**Comment by araffin** [comment]
quick remark: i don't mind SB3 env checker being copied but please don't forget to comply to the MIT license ;) (explicit mention of the original authors/license + link to the repo in the file)
