### ISSUE TITLE
Why contains function of gym.spaces.Box does not check dtype of the input?

### ISSUE THREAD

**Issue by ozgraslan** [openai/gym#2298]

**Comment by jkterry1** [comment]
box can take any input dtype...?

**Comment by tristandeleu** [comment]
This is what @ozgraslan probably means:
```python
import numpy as np
from gym import spaces

space = spaces.Box(low=0., high=1., shape=(2,), dtype=np.float32)
sample = np.array([0., 0.5], dtype=np.float64)

assert space.contains(sample)
assert sample in space  # Alternatively
```

I agree `contains` should check for the dtype as well. If I were to guess, this was probably not included to allow lists to be valid elements of the space: since lists are [implicitly converted to `np.ndarray`](https://github.com/openai/gym/blob/ddd650a3fe700dc0c9ebfd1b78027265fb909eac/gym/spaces/box.py#L141-L142), they would automatically be converted to a `np.float64` dtype if it is a list of floats, and the comparison would fail for the default `dtype=np.float32` of `Box`. If dtype is checked for `Box`, it should probably be also checked for `MultiDiscrete` and `MultiBinary`.

**Comment by ozgraslan** [comment]
Exactly! Thank you for the explanation @tristandeleu.

**Comment by RedTachyon** [comment]
Is it enough to simply make a condition in each `contains` of the datatypes being equal? Could be a simple fix. I don't think we'd ever want a different type to be "implicitly" accepted? 

Possibly also worth considering the distinction between `float`, `np.float`, `torch.float64` etc. Should a `np.float32` space accept a python float? Should a `np.float64` do it?

**Comment by tristandeleu** [comment]
> Take this example:
> 
> ```
> space = spaces.Box(low=0., high=10., dtype=np.float32)
> assert space.contains(np.asarray(np.pi, dtype=np.float64)
> ```
> 
> Why is pi no longer in the interval [0, 10], just because I add more digits of precision to it?

Maybe this example would be more convincing for why we need to check for dtype as well:
```python
space = Box(low=0, high=255, shape=(3,), dtype=np.uint8)
assert [8.13, 21.34, 55.89] in space
assert np.array([8.13, 21.34, 55.89], dtype=np.float64) in space
```
`Box` is often used for continuous values, but it is also widely used for images (`np.uint8`-valued arrays), for example in [`AtariEnv`](https://github.com/openai/gym/blob/150404104afc57ea618acca34d2d1f797d779869/gym/envs/atari/atari_env.py#L89-L91) and [`CarRacing`](https://github.com/openai/gym/blob/150404104afc57ea618acca34d2d1f797d779869/gym/envs/box2d/car_racing.py#L144-L146). In that case, you most likely don't want to have continuous values be detected as valid "images".

**Comment by FirefoxMetzger** [comment]
> Box is often used for continuous values, but it is also widely used for images (np.uint8-valued arrays)

I see, that's the piece I was missing; thanks for explaining. 

Do you think it would be worthwhile to update the docstring? Currently, it says: `A (possibly unbounded) box in R^n.` which leaves the impression that continuous-valued images would be okay if the action/observation space is defined as a Box. Though I do not have a good suggestion on how to best express the need to differentiate between float precision.

**Comment by jkterry1** [comment]
That docstring sounds sane to me at least

**Comment by jkterry1** [comment]
Yes, please update the docstrings to clarify that
