### ISSUE TITLE
Switch to imageio-ffmpeg

### ISSUE THREAD

**Issue by jkterry1** [openai/gym#2314]
Per discussion in PR #1893

**Comment by jkterry1** [comment]
@zlig does your PR I just merged close this?

**Comment by zlig** [comment]
I would actually defer to @christopherhesse as it was his original suggestion.

We need to confirm if the intention was to fully switch everything to **imageio-ffmpeg**, which means there is more work to do, or just add it as an alternative, which means we are done as we did in #1893

**Comment by jkterry1** [comment]
Christopher Hesse isn't really involved in the maintenance. I'm happy to close this given us supporting both, however a concern that's raised is that the "other" extra in setup.py doesn't include ffmpeg, meaning this alternative rendering method isn't tested. Would you be willing to add a PR that does this?
