### ISSUE TITLE
Go environment does not clean up after itself

### ISSUE THREAD

**Issue by gdb** [openai/gym#232]
We should implement a `_close` method on the Go environment, and close all open resources. @hojonathanho mind taking?

**Comment by dommueller** [comment]
Without the ```_close```, there seems to be a memory leak.

As a test case one can use this:
```
import gym

def eval():
	env = gym.make("Go9x9-v0")
	env.reset()
	# Evaluate on the env
	env.close()

pop = [eval() for _ in xrange(10000)]
```

While running it, the memory should not increase.
