### ISSUE TITLE
Fix the dtypes of observation spaces in Classic Control envs

### ISSUE THREAD

**Issue by RedTachyon** [openai/gym#2336]
**Problem**: On the example of `MountainCarContinuous-v0` because that's where I noticed the problem. The `env.observation_space` claims that observations are of type `float32`, but the actual observations are `float64`, which is a pain to deal with sometimes, but primarily it is simply internally inconsistent. Note that this issue is also present in other environments from this family.

**Replication**: 
```python
import gym
env = gym.make("MountainCarContinuous-v0")

print(f"Observation space: {env.observation_space.dtype}")  # Out: Observation space: float32
print(f"Real observation dtype: {env.reset().dtype}") # Out: Real observation dtype: float64
```

**Solution (proposed)**: I think the best way is to fix it is to actually use `float32` as that's the standard in DL libraries. The easiest way would be adding a `.astype(np.float32)` cast in `.reset()` and `.step()` methods of each environment. It might be possible to only explicitly add it to `.reset()` and then make sure no new float64's appear during a step, but that would require more changes in the code.

I can whip up a pull request with this fix.

**Comment by jkterry1** [comment]
Please create a PR :). Yes, just make it fp32.
