### ISSUE TITLE
[Proposal] Remove or Move Algorithmic Environments

### ISSUE THREAD

**Issue by jkterry1** [openai/gym#2342]
### Proposal

While many lesser used environments in Gym are still important in certain contexts (e.g. toy text), as far as I know the algorithmic ones are not. During the process of generating documentation, it's become clear that there's a not of maintenance for these that's just never really happened. My preference would be to remove this entirely or to move them into a different repo with a maintainer if anyone will volunteer as such. If anyone has strong objections to this, please let me know.

**Comment by jkterry1** [comment]
@tristandeleu

**Comment by jkterry1** [comment]
After thinking about this a bit more, my full proposal is to remove them from Gym and offer to link to anyone who wants to maintain these in a separate repo in the 3rd party envs.

**Comment by tristandeleu** [comment]
As I have previously said in #2259, removing features in general does not sound like a good idea, no matter how unlikely you think people use it. What kind of maintenance do these environments would need precisely? They look fairly well tested.
