### ISSUE TITLE
[Proposal] Switch from gym.make to import structure

### ISSUE THREAD

**Issue by jkterry1** [openai/gym#2343]
### Proposal

Right now, Gym uses the unusual structure of a gym.make to create environments. Generally, third party environments have not adopted this system because it creates issues with passing environment arguments in a user friendly manner. While in Gym this has historically not been a huge issue, it's become a huge one for the long-planned ALE-Py upgrade, and would allow for PRs adding environment arguments to different environments (e.g. reward or physics parameters), which is really valuable for beginners just learning who want to explore things. If there are no profound objections to this I believe the change is necessary in the long term.

**Comment by jkterry1** [comment]
To be clear, we would deprecate this functionality or something and not remove it entirely to prevent breaking 3rd party environments

**Comment by tristandeleu** [comment]
> Generally, third party environments have not adopted this system because it creates issues with passing environment arguments in a user friendly manner.

With the `gym.make` API, you can already pass environment arguments in a friendly manner.
```python
env = gym.make('Pendulum-v0', g=9.81)

# Equivalent to (modulo TimeLimit)
from gym.envs.classic_control import PendulumEnv
env = PendulumEnv(g=9.81)
```

Besides, how is exactly the ALE-Py upgrade going to be affected here? The environments in ALE-Py have been registered and you can also do this already
```python
env = gym.make("ale-py:Freeway-v4", render_mode="rgb_array")
```
