### ISSUE TITLE
[Proposal] Plugins for Third-Party Environment Registration

### ISSUE THREAD

**Issue by JesseFarebro** [openai/gym#2345]
### Proposal 

With the removal of some of the mainstay environments in Gym, e.g., Atari envs moving over to ale-py there is room for improvement in how third-parties can register environments. Currently Gym provides module imports in the ID of the environment, e.g., `gym.make('ale-py:Freeway-v4')` which will import `ale-py` and then attempt to make the environment with the ID `Freeway-v4`. This is a good start but there are a couple of issues this doesn't address.

1) Collisions. For example, there's an atari environment with the name `BlackJack` which conflicts with the classic env `BlackJack` found in Sutton & Barto.

2) No ability to pre-register legacy environment IDs. This is particularly relevant to me as I'd like to register the legacy Atari environments found in `gym/envs/__init__.py` in `ale-py`. There's no easy way to do this apart from importing ale_py directly in Gym.

### Pitch

Gym should leverage a type of plugin system found commonly in other Python packages. My suggestion is to leverage entry points to solve both of these issues and provide further functionality/flexibility to env registration. My proposal would look like this:

Let's say a third party wants to register a Gym environment. They specify an entry point of `gym.envs`. When doing this you provide a key and value, the key can be used as a namespace and the value is the module that should be loaded to register the environments found in that package. For example, in `ale-py` we'd have `setup.cfg` that looks like:

```
[options.entry_points]
console_scripts =
  ale-import-roms = ale_py.roms.import_roms:main
gym.envs =
    ALE = ale_py.gym
```

As you can see we have one entry point already which provides a console script to `ale-import-roms`. The other is the entry point which provides a plug-in for `gym.envs`. The key is `ALE` and the module of `ale_py.gym` will be loaded when Gym is first imported. In `ale-py` we'd register the environments as follows:

```py
register('Freeway-v5', ...)
```

and Gym would dynamically enforce the `ALE/` part of the environment ID. So after all the plugins are loaded a user could make the environment as follows:

```py
gym.make('ALE/Freeway-v5', ...)
```

Furthermore, there could be a whitelist, e.g., `ale-py`, `mujoco-py`, where they could register legacy IDs by using a blank key, i.e.,

```
[options.entry_points]
gym.envs =
    ALE = ale_py.gym
    = ale_py.gym.legacy
```

### Additional context

Having this type of functionality would also allow Gym to deal with issues like #1113 by moving the Mujoco envs into `mujoco-py` or another Python package with the ability to register into the root registry for backwards compatibility.

It's also worth noting the `prefix/ID` format is already accepted by Gym although not widely used.

Lastly, these changes would be completely backwards compatible and wouldn't introduce any breaking changes to Gym.

Thoughts?

### Implementation Details

The implementation on Gym's side would be minimal. It's as simple as

`gym/envs/registration.py`
```py
import sys

if sys.version_info < (3, 10):
    from importlib_metadata import entry_points
else:
    from importlib.metadata import entry_points


def load_from_plugins():
    plugins = entry_points(group='gym.envs')
    for plugin in plugins:
        plugin.load()
```
(would have to depend on importlib_metadata for Python < 3.10 but the dependency is minimal)

`gym/envs/__init__.py`
```py
from gym.envs.utils import load_from_plugins

load_from_plugins()
```

Obviously, this would have to be modified to allow for whitelisting and dynamic namespace prefixes but the complexity of the implementation is minimal.

**Comment by tristandeleu** [comment]
This sounds like a great idea! A plugins system would be very convenient for third-party environments, and the complexity seems very reasonable. This seems to be particularly helpful for plugins loaded by Gym directly (inside Gym's `entry_points`). What about for third-party libraries, you would still need to load the library first, right? For example let's say you have a `my_env` library with

`my-env/setup.cfg`
```
[options.entry_points]
gym.envs =
    MyEnv = my_env.envs
```

Then to load an environment, you'd have to do something like
```python
import my_env  # Needs to be loaded before gym still?
import gym

env = gym.make('MyEnv/MyFirstEnv-v0')
```

In that case (specifically for third-party libraries which are not meant to be included as part of Gym), what is the advantage of the plugin system over the old registration? For example

`my_env/__init__.py`
```python
from gym.envs.registration import register

register('MyEnv/MyFirstEnv-v0', entry_point='my_env.envs:MyFirstEnv')
```

And then load it the same way as above for `gym.make`.

**Comment by JesseFarebro** [comment]
@tristandeleu You don't need to import `my_env` at all. When you install the `my-env` wheel it has the appropriate hooks to register the entry point and then Gym will see it immediately.

I hope this addresses the rest of your comments.

**Comment by tristandeleu** [comment]
That's very cool! Thank you for the clarification.

**Comment by jkterry1** [comment]
@JesseFarebro had thoughts on colissions that he can share

As a note to others, I don't want to say we're doing this until Ben approves this, which will probably have to wait until the weekend after the upcoming one (@benblack769)

**Comment by JesseFarebro** [comment]
@Rohan138 the key in the entry point acts as a namespace for the environment IDs. As in my original post:

```
[options.entry_points]
gym.envs =
    ALE = ale_py.gym
```

would prefix all environments registered in `ale_py.gym` with `ALE`. So when creating an environment you would instantiate `ALE/BlackJack-v0` for example. The blackjack ALE environment is new so it isn't currently registered in the root namespace, i.e., `BlackJack-v0` (as you noted this is already registered to the Sutton & Barto blackjack).


@jkterry1 I already have this implemented with the forced namespace I discussed above.

**Comment by jkterry1** [comment]
@JesseFarebro can you please open a PR so people can take a look?

**Comment by benblack769** [comment]
Sorry, I'm not too familiar with this sort of plugin system. From what I see, the main differences from the current environment registration system are:

1. Gym enforces the gym.make("Package/Environment") format, rather than the 3rd party libraries
2. Users don't need to import 3rd party libraries, only install them

Does that sound right?

**Comment by benblack769** [comment]
Also, my understanding is that most 3rd party environments work like this: https://github.com/benelot/pybullet-gym#installing-pybullet-gym

I assume that the registration system will continue to work exactly as before in this setup?

**Comment by tristandeleu** [comment]
> Also, my understanding is that most 3rd party environments work like this: https://github.com/benelot/pybullet-gym#installing-pybullet-gym

The current registration of third-party environments requires you to explicitly import the library to register those environments in Gym (e.g. `import pybulletgym`). Here, as mentioned in https://github.com/openai/gym/issues/2345#issuecomment-903333652, you don't need to import the library at all.

**Comment by benblack769** [comment]
@tristandeleu Yes, I got that, it was my point 2. I meant to ask if that use pattern will continue to work without any code changes from the environment developer (i.e., after this change to gym, will the pybullet-gym script work as is, without any changes internally to pybullet-gym).

**Comment by tristandeleu** [comment]
Sorry my bad, I thought you said that the current registration system was already working like this. The current registration system will probably still work, just have to make sure that the environments don't get registered twice (once with `entry_points`, another with manually importing the library), but that should be easy enough (just check if the ID and entry-point are already in the registry).

**Comment by Rohan138** [comment]
Relevant question: Could someone explan in the reasoning behind not allowing environment IDs to be overwritten in the registry? [Link](https://github.com/openai/gym/blob/master/gym/envs/registration.py#L183)  
Asking this because it would help solve the issue with environments getting registered twice and new environments being able to override older ones.
