### ISSUE TITLE
Box.contains fails on tuple input

### ISSUE THREAD

**Issue by FirefoxMetzger** [openai/gym#2357]
```python
from gym.spaces import Box
import numpy as np

space = Box(low=np.array((-1, -1, -1)), high=np.array((1, 1, 1)))
space.contains((0,0,0))

```

Produces the following stack-trace

```
Traceback (most recent call last):
  File "box_bug.py", line 5, in <module>
    space.contains((0,0,0))
  File "/home/firefoxmetzger/.local/lib/python3.8/site-packages/gym/spaces/box.py", line 144, in contains
    x.shape == self.shape and np.all(x >= self.low) and np.all(x <= self.high)
AttributeError: 'tuple' object has no attribute 'shape'
```

A quick look at the code reveals that only lists are promoted to arrays.

https://github.com/openai/gym/blob/edc233288e4336825540ca2c0dc2e6b8a9291dfc/gym/spaces/box.py#L140-L145

I would lobby for using a more generic call to `np.asarray` to convert anything ArrayLike; perhaps combined with a type hint update `Any -> np.typing.ArrayLike`:

```python
def contains(self, x):
    x = np.asarray(x)

    if x.shape != self.shape:
        return False

    if np.any( (x<self.low) | (x>self.high) ):
        return False

    return True
```

**Comment by tristandeleu** [comment]
> @tristandeleu Oh? Am I missing something? What situation do you have in mind where this conversion would be detrimental?

Not detrimental, but less intuitive from a UX perspective because this conversion happens internally to Gym, and is not something that the user requested. But really at the end of the day, I am not strongly against the internal conversion to Numpy arrays.

**Comment by FirefoxMetzger** [comment]
> this conversion happens internally to Gym, and is not something that the user requested.

@tristandeleu I'm confused. `np.asarray` would create a copy of its input if it isn't already a ndarray (with correct type and order), which will then be handed to gc once the function returns, so the user would keep the original object that was passed into `space.contains` and (performance aside) wouldn't even notice that gym creates a temporary array internally in some cases. I can see how this can be troublesome if `x` was a tensor located on the GPU since this can have significant performance implications. Then again `space.contains` doesn't seem like a function one would expect to see in the critical loop of HPC code, so I'm not sure if my argument here counts.

Which part is unintuitive from your perspective?

**Comment by tristandeleu** [comment]
The issue would be if you ensure dtype as well, as I suggested in https://github.com/openai/gym/issues/2357#issuecomment-907128794 (to eventually also check for the input dtype). Any object that can't be casted in the space's dtype would then raise an error because of the conversion to Numpy array.

If the dtype is not being checked (as it is the case currently), then I agree this has minimal impact since `np.asarray` would just copy the input.

**Comment by FirefoxMetzger** [comment]
@tristandeleu Hm, I'm still not sure I 100% get what you're after; I think it might be related to https://github.com/openai/gym/issues/2298#issuecomment-907322981.

In either case, would something like this do what you have in mind?

```python
if isinstance(x, np.ndarray):
    assert x.dtype == self.dtype
else:
    x = np.asarray(x, dtype=self.dtype)
    warn("Casting input to numpy array of correct type)
```

**Comment by tristandeleu** [comment]
Sorry for the confusion, but this is indeed more or less what I had in mind. To be very concrete, here is what I would suggest
```diff
diff --git a/gym/spaces/box.py b/gym/spaces/box.py
index 32b5c93..f4c27aa 100644
--- a/gym/spaces/box.py
+++ b/gym/spaces/box.py
@@ -1,4 +1,5 @@
 import numpy as np
+import warnings

 from .space import Space
 from gym import logger
@@ -138,10 +139,11 @@ class Box(Space):
         return sample.astype(self.dtype)

     def contains(self, x):
-        if isinstance(x, list):
-            x = np.array(x)  # Promote list to array for contains check
+        if not isinstance(x, np.ndarray):
+            warnings.warn('Casting input to Numpy array.')
+            x = np.asarray(x, dtype=self.dtype)
         return (
-            x.shape == self.shape and np.all(x >= self.low) and np.all(x <= self.high)
+            np.can_cast(x.dtype, self.dtype) and x.shape == self.shape and np.all(x >= self.low) and np.all(x <= self.high)
         )

     def to_jsonable(self, sample_n):
```

**Comment by tristandeleu** [comment]
Also worth noting, there are other places in Gym where the inputs get implicitly casted to a Numpy array with a dtype given by the space. For example when [writing to shared memory in `gym.vector`](https://github.com/openai/gym/blob/150404104afc57ea618acca34d2d1f797d779869/gym/vector/utils/shared_memory.py#L176-L182). That's why I said I am not against the internal conversion into Numpy arrays.

**Comment by FirefoxMetzger** [comment]
@tristandeleu Sure thing. I created a PR with the respective changes.
