### ISSUE TITLE
Replace Pyglet with PyGame for Classic Control

### ISSUE THREAD

**Issue by jkterry1** [openai/gym#2359]
This is a recreation of the content in https://github.com/openai/gym/issues/2347 that wasn't moved to https://github.com/openai/gym/issues/2358- Classic Control environments use Pyglet for rendering instead of something that can render headless and is unobtrusive. Given that we more or less need to use PyGame for the Box2D replacements and PyGame is suitable here, that's my preference. This is a fairly low priority issue because of what the Classic Control environments are.

**Comment by pyweeker** [comment]
hello, did you try with Arcade instead of pyglet ?
https://api.arcade.academy/en/latest/examples/index.html
