### ISSUE TITLE
Specific Plans for Replacing MuJoCo Environments With PyBullet

### ISSUE THREAD

**Issue by jkterry1** [openai/gym#2366]
This is specifically for the MuJoCo class environments, not the robotic class environments that depend on MuJoCo (those will be replaced too, but that's a future problem).

The plan is to create a phys3d class for the pybullet replacement environments (since they aren't MuJoCo) with drop in replacements. Initially the environments will be unversioned and will have a warning message saying that they're beta. Once they've been thoroughly tested by the community to make sure that they're truly drop in replacements we'll add versioning to them and remove the MuJoCo class of environments.

For specific environments, the major source is is https://github.com/benelot/pybullet-gym. However, this repo has problems:
-It doesn't have the Humanoid Standup or Swimmer environments
-It says that the Walker2d and HalfCheetah environments are not similar to the reference implementations

This brings us to the lesser used source:
https://github.com/benelot/bullet-gym (which by the same guy, but is unmaintained and according to the environment description is the experimental version of the above repo). This is notable in that it has the missing Humanoid Standup and Swimmer environments. 

The plan accordingly is for @Rohan138 to add the pybullet environments that replace MuJoCo ones to a new phys3d class from the first repo (it has many more than are included in Gym and I don't want to include new environments) and swimmer and humanoid from the second repo. _Once these are in_, we would greatly appreciate PRs that make the environments closer to drop in replacements for those in Gym and contributors testing these thoroughly.

**Comment by jkterry1** [comment]
Two things from the exchanges with @benelot needs to be mentioned for those watching because I don't believe it's been publicly documented:

1) The environments from repo #1 that were upstreamed into pybullet have included a lot of pybullet maintenance, however the master repo #1 has included various observation fixes after the merge, and these features have never been resolved. This means that results between repos #1, #2 and the environments in pybullet should not be compared, and is a profound argument for upstreaming these and making these environments officially and highly reviewed. Also will have to figure out how to merge the code somehow, @Rohan138 I would prefer to move things from repo #1 and #2 in first before adding the upgrades in pybullet (amongst other upgrades) so that those can review

2) The observation spaces of these are likely profoundly troubling, to qoute: "The most work intensive thing will be to identify the observations of Mujoco (what they are conceptually) and replace them with pybullet provided observations. The observations in my code contains a lot of zeros to fill in the blanks such that the code runs, but this certainly leads to slower or impossible training"

**Comment by sgillen** [comment]
Hello I also wanted to chime in. This is something I was briefly interested in awhile ago but didn't really go anywhere with.

I'm not quite sure what exactly you mean by a "drop in replacement" I think it will probably be possible to make the observation space in bullet mimic what the current MuJoCo environments, but I think it will be much more difficult to get the performance of RL algorithms across similar environments in the two different sims to be roughly equivalent.

Like I mentioned on the discord the contact / constraint model between the two simulators is very different, although we can tweak the parameters in bullet to try to better match what MuJoCo does. I made a small example doing this here: https://gist.github.com/sgillen/7674fe6b8254aa512f5091367719fef2 which may be interesting if replicating the MuJoCo envs as close as possible is necessary. 

Another question I have is (and I mean this as a genuine question) why replicate the Mujoco environments exactly in the first place? Another option might be to try and upgrade / update the environments that @benelot developed / that live in pybullet_envs. I think those environments are also widely used at this point, but I have no numbers on that.

**Comment by sgillen** [comment]
Also, you may be aware of these already but I thought I'd bring them up just in case:

1. I think the bullet environments will be incompatible with the render() interface gym currently uses. Though maybe we can work around this ... 

2. For the robotic environments (excluding shadow hand) this: https://github.com/qgallouedec/panda-gym  repo  seems pretty good, I know rl-baselines3-zoo already includes benchmarks for it alongside the mj versions, but I have not looked into them closely yet.
