### ISSUE TITLE
[Bug] Environment registration fails in forked processes

### ISSUE THREAD

**Issue by harwiltz** [openai/gym#2370]
## Description

I made some custom environments that I'd like to use for some experiments. When I run experiments in parallel with `joblib`, they immediately crash with `gym` complaining that my environment is unregistered. When I run the exact same code sequentially, everything is fine.

### A package with a custom environment

Consider the following package `silly_envs`, consisting of the files `silly_envs/{__init__, silly}.py` shown below.

`silly_envs/__init__.py`:

```python
from gym.envs.registration import register

register(
    id="SillyEnv-v0",
    entry_point="silly_envs.silly:SillyEnv",
    max_episode_steps=150
)
```

`silly_envs/silly.py`:

```python
import gym
from gym.spaces import Discrete

class SillyEnv(gym.Env):
    def __init__(self):
        self.observation_space = Discrete(3)
        self.action_space = Discrete(2)
        self.state = 0

    def reset(self):
        self.state = 0
        return self.state

    def step(self, action):
        self.state = (self.state + action) % self.observation_space.n
        done = self.state == 1
        return self.state, 1, done, {}

    def render(self):
        print(self.state)
```

I used the following `setup.py` script to install the `silly_envs` package:

```python
from setuptools import setup

setup(name='silly-envs', packages=['silly_envs'])
```

### Script

```python
import gym
import silly_envs

from joblib import Parallel, delayed

@delayed
def fun(i):
    env = gym.make('SillyEnv-v0')
    return env.action_space.n

Parallel(n_jobs=1, prefer='processes')(fun(i) for i in range(1, 11)) # This works
Parallel(n_jobs=4, prefer='processes')(fun(i) for i in range(1, 11)) # This crashes 
```

The exception that is thrown is:

```
gym.error.UnregisteredEnv: No registered env with id: SillyEnv-v0
```

### Additional Context

I suppose I could technically make this work by replacing the `env = gym.make(...)` with `env = silly_envs.SillyEnv()`, however I would rather not as it would make the configuration of my experiments more cumbersome.

**System Info**
Describe the characteristic of your environment:
 * The issue occurs when Gym is installed via `pip` and via the packages provided by Linux distros that I use.
 * Reproduced on Gentoo and Arch Linux
 * Python 3.8.x and Python 3.9.6

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by Rohan138** [comment]
Could you try moving ```import gym``` into the function?

Explanation: The environments are registered by Gym when it is imported, so it's likely that your environments are only being registered on the parent process.

**Comment by harwiltz** [comment]
@Rohan138 Thanks! Works for me too. About why it doesn't happen with internal Gym environments, I was wondering the same thing. Never had this issue before running my exact same experiments the same way with standard Gym envs.

I'll leave this open in case people want to investigate the discrepancy with internal envs, otherwise feel free to close.

**Comment by Rohan138** [comment]
I think [this](https://stackoverflow.com/questions/50643983/joblib-importerror-tries-to-load-a-library-i-think-it-shouldnt-be-looking-for) explains why pickle isn't loading the imported library automatically. Anyway, voting to close.

**Comment by harwiltz** [comment]
Yeah that is fairly insightful. Thanks!
