### ISSUE TITLE
[Question] Improve Taxi example

### ISSUE THREAD

**Issue by pyweeker** [openai/gym#2372]
Hello, is it possible to show how to do this with Taxi example:
add more locations and destination (Hop-on x 21 , Hop-off x 7) , add more passengers (the taxi is a 10 places van) , a wider map 50*30 .
I am stuck with plenty silly bugs when trying to achieve this.

**Comment by jkterry1** [comment]
This is not an issue with Gym, please ask questions in the RL discord or r/reinforcementlearning (like the issue template said)
