### ISSUE TITLE
gym[atari] requires a yanked version of atari-py (aka. 0.2.6)

### ISSUE THREAD

**Issue by ymd-h** [openai/gym#2379]
**Describe the bug**

gym[atari] requires `atari-py==0.2.6`.
https://github.com/openai/gym/blob/150404104afc57ea618acca34d2d1f797d779869/setup.py#L12

The version of atari-py is [yanked on PyPI](https://pypi.org/project/atari-py/0.2.6/) and reported as "no good" at an [issue](https://github.com/google/dopamine/issues/24#issuecomment-594355868).

When installing ROM, `No module named atari_py.import_roms` happens.

**Code example**

```shell
pip install gym[atari]
wget http://www.atarimania.com/roms/Roms.rar
7z x Roms.rar && unzip ROMS.zip
python -m atari_py.import_roms ROMS
```

**System Info**

 * Install Gym with pip on GitHub Actions hosted runner
 * OS: Ubuntu / macOS / Windows
 * Python version: 3.7 & 3.8

**Additional context**
Full detail is [here](https://github.com/ymd-h/tf2rl/runs/3467150016?check_suite_focus=true)

As long as I checked, the version 0.2.9 can install ROM correctly.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by Rohan138** [comment]
atari-py is being removed in favor of ale-py [here](#2348 ).

**Comment by jkterry1** [comment]
atari-py still shouldn't have been yanked, I'm sending emails about this......

**Comment by jkterry1** [comment]
Apparently the plan is to just get ALE-Py out very quickly in 1-2 more days and get rid of the Atari-Py situation once and for all.
