### ISSUE TITLE
What's the meaning of the input of CartPole observation space?

### ISSUE THREAD

**Issue by tornadomeet** [openai/gym#238]
Hello, all, i'm newbie to gym.  
    I print out the env.observation_space.shape[0], and it equals 4(CartPole-v0 env), so What's the meaning of this 4 numbers,? i cannot found the doc which describe it.( i think it may include the position of cart, the angle of the pole, the speed of the cart and the speed of the pole.)   
Thanks!

**Comment by tlbtlbtlb** [comment]
Good general-purpose agents don't need to know the semantics of the observations: they can learn how to map observations to actions to maximize reward without any prior knowledge.

That said, it's:
 `[position of cart, velocity of cart, angle of pole, rotation rate of pole]`. Defined at https://github.com/openai/gym/blob/master/gym/envs/classic_control/cartpole.py#L75

**Comment by tornadomeet** [comment]
great!

**Comment by cyborgnoah** [comment]
Is there a documentation which explains what the gym observation is returning. Please Share a Link.

**Comment by oliverastrand** [comment]
Some of the environments are described in further detail in the [wiki](https://github.com/openai/gym/wiki/CartPole-v0). This includes explanations of what the observations contain.

**Comment by stefanbschneider** [comment]
> 
> 
> Good general-purpose agents don't need to know the semantics of the observations: they can learn how to map observations to actions to maximize reward without any prior knowledge.
> 
> That said, it's: `[position of cart, velocity of cart, angle of pole, rotation rate of pole]`. Defined at https://github.com/openai/gym/blob/master/gym/envs/classic_control/cartpole.py#L75

Thanks! The link points to the wrong line, though. Here's a correct permalink: https://github.com/openai/gym/blob/01cc8a3a1694c978a2310714faf52e41df1988b5/gym/envs/classic_control/cartpole.py#L26
