### ISSUE TITLE
[Bug Report] API compliance test needs to check for observations and actions emitted being in spaces

### ISSUE THREAD

**Issue by jkterry1** [openai/gym#2382]
Specifically, the API compliance test should've failed on the environments fixed here and did not https://github.com/openai/gym/pull/2340

**Comment by jkterry1** [comment]
@amtamasi would you be willing to add this?

**Comment by tristandeleu** [comment]
It already does. https://github.com/openai/gym/blob/e5c7f1e3a767a73f130a9956a99b6683f4bc7e4e/gym/utils/env_checker.py#L91-L93

**Comment by jkterry1** [comment]
I missd that ariel added that in the PR, thanks a ton
