### ISSUE TITLE
Matlab connection?

### ISSUE THREAD

**Issue by leonardoaraujosantos** [openai/gym#239]
Hi guys there is any chance that the gym become also available on matlab?

**Comment by catherio** [comment]
Not yet, but if you are interested in writing that functionality yourself, I can point you in the right direction!

At this point, accessing gym from other languages takes place over a local API, by running gym on a python process that acts as a "server", and sending actions and observations back and forth using HTTP: https://github.com/openai/gym-http-api

If you would like to write a MATLAB client, then you can make your client look just like the example clients already written, such as this python client:
https://github.com/openai/gym-http-api/blob/master/gym_http_client.py

There are likely good packages in MATLAB for creating and sending HTTP requests and receiving the responses. For example, http://www.mathworks.com/help/matlab/ref/webread.html looks alright, though I haven't used it myself.

**Comment by leonardoaraujosantos** [comment]
Hi catherio thanks for the directions, I will write one myself, do you know if there is any coding rules to add  later a pull request on openai gym?

About performance does this http interface impact training performance on other languages?

Again thanks

**Comment by catherio** [comment]
Glad to hear it! There aren't any formal rules, but I encourage you to write clean and maintanable code that will be easy for others to read and use. A MATLAB-specific style guide can be found here if that's useful to you: http://www.datatool.com/prod02.htm.

The HTTP interface definitely incurs a small delay. However, we have not yet heard from any users who find the slight slowdown to be prohibitively difficult for their uses. (Note that the server and client are both intended to be run locally on the same machine, so there are no network round-trips involved.) We do have some ideas for how we might use a faster messaging protocol, but we won't prioritize them unless there's a strong demand among users. So, if you find that the additional time incurred by the HTTP protocol is making a serious difference to your use of the package, we'd like to know about it.

**Comment by leonardoaraujosantos** [comment]
Ok catherio I will work on it today, and I will post the results as soon as I finish.

**Comment by leonardoaraujosantos** [comment]
Hi I've added a PR
https://github.com/openai/gym-http-api/pull/14

I'm having problems on how to configure properly the travis test system

**Comment by MangiapeloRiccardo** [comment]
Hi, 

Is OpenAi Gym working on Matlab yet?

**Comment by leonardoaraujosantos** [comment]
Hi MangiapeloRiccardo I've added a Pull request with a matlab http client you can try it out. But it's not yet on the main branch
