### ISSUE TITLE
[Question] Should seed() always return a list?

### ISSUE THREAD

**Issue by jkterry1** [openai/gym#2406]
The very long discussion in https://github.com/openai/gym/pull/1774 raises two questions:

1. Should the seed method always return a list for all spaces/datatypes? The answer seems like no to me, but I may be wrong
2. If we change this, how impactful will upstream breaking changes be and can we mitigate them in a reasonable way?

**Comment by XuehaiPan** [comment]
As documented in `Env.seed`:

https://github.com/openai/gym/blob/d35d211fee6d2eb46066d4e733d81fa238b6b081/gym/core.py#L124-L139

The `seed` method of all subclasses of `gym.Env`, including customized environments and wrapped ones, always returns a list of integers. And the first item is the main seed of the environment's RNG.

We'd better keep the behavior of `space.Space.seed` to be consistent with `Env.seed`, i.e., returns a list of integers and the first one is the main seed (especially for a compound space `space.Tuple` or `space.Dict`).
