### ISSUE TITLE
gym.error.Error: Unable to find game "Pong", did you import Pong with ale-import-roms?

### ISSUE THREAD

**Issue by jiangzheng77** [openai/gym#2414]
If you are submitting a bug report, please fill in the following details and use the tag [bug].

**Describe the bug**
Traceback (most recent call last):
  File "C:/Users/jz/Desktop/download/Deep-Reinforcement-Learning-Hands-On-master/Chapter06/02_dqn_pong.py", line 115, in <module>
    env = wrappers.make_env(args.env)
  File "C:\Users\jz\Desktop\download\Deep-Reinforcement-Learning-Hands-On-master\Chapter06\lib\wrappers.py", line 115, in make_env
    env = gym.make(env_name)
  File "c:\users\jz\gym\gym\envs\registration.py", line 235, in make
    return registry.make(id, **kwargs)
  File "c:\users\jz\gym\gym\envs\registration.py", line 129, in make
    env = spec.make(**kwargs)
  File "c:\users\jz\gym\gym\envs\registration.py", line 90, in make
    env = cls(**_kwargs)
  File "C:\Users\jz\Anaconda3\envs\pytorch\lib\site-packages\ale_py\gym\environment.py", line 123, in __init__
    self.seed()
  File "C:\Users\jz\Anaconda3\envs\pytorch\lib\site-packages\ale_py\gym\environment.py", line 172, in seed
    f'Unable to find game "{self._game}", did you import {self._game} with ale-import-roms?'
gym.error.Error: Unable to find game "Pong", did you import Pong with ale-import-roms?

**System Info**
 * window10 
** Python version
* python 3.6

**Comment by ezeid** [comment]
I am getting the exact same error when the code executes this line:
env    = gym.make("Pong-v0")

The code: env = gym.make('CartPole-v0') executes fine.

What is special about the Pong game?

My system:
windows 10; python 3.7.0

**Comment by JesseFarebro** [comment]
There's nothing special about Pong. Since Gym 0.20 we've switched over to using the official version of the [Arcade Learning Environment](https://github.com/mgbellemare/Arcade-Learning-Environment). As the error message says:

> UserWarning: atari_py.atari_roms contains unsupported ROMs: C:\Users\elioa\miniconda3\envs\tfcuda_env\Lib\site-packages\atari_py\atari_roms\\{adventure.bin, air_raid.bin, alien.bin, amidar.bin, assault.bin, asterix.bin, asteroids.bin, atlantis.bin, bank_heist.bin, battle_zone.bin, beam_rider.bin, berzerk.bin, bowling.bin, boxing.bin, breakout.bin, carnival.bin, centipede.bin, chopper_command.bin, crazy_climber.bin, defender.bin, demon_attack.bin, double_dunk.bin, elevator_action.bin, enduro.bin, fishing_derby.bin, freeway.bin, frostbite.bin, gopher.bin, gravitar.bin, hero.bin, ice_hockey.bin, jamesbond.bin, journey_escape.bin, kaboom.bin, kangaroo.bin, krull.bin, kung_fu_master.bin, montezuma_revenge.bin, ms_pacman.bin, name_this_game.bin, phoenix.bin, pitfall.bin, pong.bin, pooyan.bin, private_eye.bin, qbert.bin, riverraid.bin, road_runner.bin, robotank.bin, seaquest.bin, skiing.bin, solaris.bin, space_invaders.bin, star_gunner.bin, tennis.bin, time_pilot.bin, tutankham.bin, up_n_down.bin, venture.bin, video_pinball.bin, wizard_of_wor.bin, yars_revenge.bin, zaxxon.bin}

The version of Pong that is packaged with the old `atari-py` wrapper is unsupported. For more info see [this blog post](https://brosa.ca/blog/ale-release-v0.7). To solve this issue you have to import the proper version of Pong. A tool that can help you out is [AutoROM](https://github.com/PettingZoo-Team/AutoROM).

Sorry for the confusion, there will be a better error message informing users of the change.

**Comment by IlyaNefedov** [comment]
> There's nothing special about Pong. Since Gym 0.20 we've switched over to using the official version of the [Arcade Learning Environment](https://github.com/mgbellemare/Arcade-Learning-Environment). As the error message says:
> 
> > UserWarning: atari_py.atari_roms contains unsupported ROMs: C:\Users\elioa\miniconda3\envs\tfcuda_env\Lib\site-packages\atari_py\atari_roms\{adventure.bin, air_raid.bin, alien.bin, amidar.bin, assault.bin, asterix.bin, asteroids.bin, atlantis.bin, bank_heist.bin, battle_zone.bin, beam_rider.bin, berzerk.bin, bowling.bin, boxing.bin, breakout.bin, carnival.bin, centipede.bin, chopper_command.bin, crazy_climber.bin, defender.bin, demon_attack.bin, double_dunk.bin, elevator_action.bin, enduro.bin, fishing_derby.bin, freeway.bin, frostbite.bin, gopher.bin, gravitar.bin, hero.bin, ice_hockey.bin, jamesbond.bin, journey_escape.bin, kaboom.bin, kangaroo.bin, krull.bin, kung_fu_master.bin, montezuma_revenge.bin, ms_pacman.bin, name_this_game.bin, phoenix.bin, pitfall.bin, pong.bin, pooyan.bin, private_eye.bin, qbert.bin, riverraid.bin, road_runner.bin, robotank.bin, seaquest.bin, skiing.bin, solaris.bin, space_invaders.bin, star_gunner.bin, tennis.bin, time_pilot.bin, tutankham.bin, up_n_down.bin, venture.bin, video_pinball.bin, wizard_of_wor.bin, yars_revenge.bin, zaxxon.bin}
> 
> The version of Pong that is packaged with the old `atari-py` wrapper is unsupported. For more info see [this blog post](https://brosa.ca/blog/ale-release-v0.7). To solve this issue you have to import the proper version of Pong. A tool that can help you out is [AutoROM](https://github.com/PettingZoo-Team/AutoROM).
> 
> Sorry for the confusion, there will be a better error message informing users of the change.

Hi! What is proper version of Pong? I use this 60e0ea3cbe0913d39803477945e9e5ec pong.bin (as mentioned as supported in md5.txt), but still get same error.

**Comment by kangdongki** [comment]
I solved this issue by "pip install gym==0.19"

**Comment by frankgray** [comment]
the same issue:

INFO: Making new env: Breakout-v0
---------------------------------------------------------------------------
Error                                     Traceback (most recent call last)
<ipython-input-33-19ee29477b34> in <module>
      1 import gym
----> 2 env = gym.make('Breakout-v0')

D:\ProgramData\Anaconda3\envs\pytorch1.1_cuda9.0\lib\site-packages\gym\envs\registration.py in make(id, **kwargs)
    198     """
    199     global warn_once
--> 200     if warn_once:
    201         logger.warn(
    202             "Environment '%s' has deprecated methods '_step' and '_reset' rather than 'step' and 'reset'. Compatibility code invoked. Set _gym_disable_underscore_compat = True to disable this behavior."

D:\ProgramData\Anaconda3\envs\pytorch1.1_cuda9.0\lib\site-packages\gym\envs\registration.py in make(self, path, **kwargs)
    103         else:
    104             logger.info("Making new env: %s", path)
--> 105         spec = self.spec(path)
    106         env = spec.make(**kwargs)
    107         # We used to have people override _reset/_step rather than

D:\ProgramData\Anaconda3\envs\pytorch1.1_cuda9.0\lib\site-packages\gym\envs\registration.py in make(self, **kwargs)
     73             env = self.entry_point(**_kwargs)
     74         else:
---> 75             cls = load(self.entry_point)
     76             env = cls(**_kwargs)
     77 

D:\ProgramData\Anaconda3\envs\pytorch1.1_cuda9.0\lib\site-packages\ale_py\gym\environment.py in __init__(self, game, mode, difficulty, obs_type, frameskip, repeat_action_probability, full_action_space, render_mode)
    121 
    122         # Seed + Load
--> 123         self.seed()
    124 
    125         self._action_set = (

D:\ProgramData\Anaconda3\envs\pytorch1.1_cuda9.0\lib\site-packages\ale_py\gym\environment.py in seed(self, seed)
    170         if not hasattr(roms, self._game):
    171             raise error.Error(
--> 172                 f'Unable to find game "{self._game}", did you import {self._game} with ale-import-roms?'
    173             )
    174         self.ale.loadROM(getattr(roms, self._game))

Error: Unable to find game "Breakout", did you import Breakout with ale-import-roms?

**Comment by JesseFarebro** [comment]
See the [latest release notes](https://github.com/openai/gym/releases/tag/v0.21.0) for how to deal with ROMs in `gym>=0.21`.

**Comment by JesseFarebro** [comment]
This issue was actually a problem with how we were checking the ROM hash on Windows. Even if you had the supported ROM it wouldn't be detected as supported by the ALE. This will be resolved in the next release of the ALE which you can expect in the next couple of days. I'll update this thread when it's published.

**Comment by JesseFarebro** [comment]
As of `v0.7.2` of the ALE, this issue is now resolved on Windows.
