### ISSUE TITLE
[Bug Report] Striped rather than solid fill on all box2d environments

### ISSUE THREAD

**Issue by cversteeg** [openai/gym#2416]
I am trying to build a new environment that learns to move a cursor to a target, and have been using the lunar lander as a template. I recently ran the lunar lander and found strange behavior where the objects are approximately correctly displayed on the screen, the fills are incorrect and seem to be "striped" across the whole horizontal plane.

![image](https://user-images.githubusercontent.com/15896921/134066304-95a9aa8a-988f-45d7-aca0-a4acd8762ee4.png)

This works from the lunar_lander.py demo function. 

**System Info**
Windows 10

Gym was installed via pip install gym[all]
I also pip installed box2d
I am using python 3.8.11

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)
- There was one similar issue (closed with no comments...) https://github.com/openai/gym/issues/2237

**Comment by jkterry1** [comment]
Can you provide as much system detail as you can and include pip freeze? Me and others have rendered these plenty of times without issues, so it this is not a universal bug. The reason I closed the last issue is I assumed it was just someone with a corrupted graphic driver of something since this works for so many people. I'll note that the maintainers looking into this ourselves is going to be an incredibly low priority because we plan to rewrite the rendering of these with a different graphics library in the future.

**Comment by jkterry1** [comment]
Also we don't officially support Windows FWIW

**Comment by cversteeg** [comment]
Here's my pip freeze:

absl-py==0.13.0
alabaster @ file:///home/ktietz/src/ci/alabaster_1611921544520/work
appdirs==1.4.4
argh==0.26.2
arrow==0.13.1
astroid @ file:///C:/ci/astroid_1628063293445/work
async-generator @ file:///home/ktietz/src/ci/async_generator_1611927993394/work
atari-py==0.2.9
atomicwrites==1.4.0
attrs @ file:///tmp/build/80754af9/attrs_1620827162558/work
autopep8 @ file:///tmp/build/80754af9/autopep8_1615918855173/work
Babel @ file:///tmp/build/80754af9/babel_1620871417480/work
backcall @ file:///home/ktietz/src/ci/backcall_1611930011877/work
bcrypt @ file:///C:/ci/bcrypt_1597936263757/work
binaryornot @ file:///tmp/build/80754af9/binaryornot_1617751525010/work
black==19.10b0
bleach @ file:///tmp/build/80754af9/bleach_1628110601003/work
Bottleneck==1.3.2
Box2D==2.3.10
brotlipy==0.7.0
cachetools==4.2.2
certifi==2021.5.30
cffi @ file:///C:/ci/cffi_1625831749120/work
chardet @ file:///C:/ci/chardet_1607690654534/work
charset-normalizer @ file:///tmp/build/80754af9/charset-normalizer_1630003229654/work
click @ file:///tmp/build/80754af9/click_1621604852318/work
cloudpickle==2.0.0
colorama @ file:///tmp/build/80754af9/colorama_1607707115595/work
cookiecutter @ file:///tmp/build/80754af9/cookiecutter_1617748928239/work
cryptography @ file:///C:/ci/cryptography_1616769344312/work
cycler==0.10.0
Cython==0.29.24
debugpy @ file:///C:/ci/debugpy_1629222854708/work
decorator @ file:///tmp/build/80754af9/decorator_1621259047763/work
defusedxml @ file:///tmp/build/80754af9/defusedxml_1615228127516/work
diff-match-patch @ file:///Users/ktietz/demo/mc3/conda-bld/diff-match-patch_1630511840874/work
docutils @ file:///C:/ci/docutils_1620828260973/work
entrypoints==0.3
flake8 @ file:///tmp/build/80754af9/flake8_1615834841867/work
future==0.18.2
glfw==2.2.0
google-auth==1.35.0
google-auth-oauthlib==0.4.6
grpcio==1.40.0
gym==0.20.0
idna @ file:///tmp/build/80754af9/idna_1622654382723/work
imageio==2.9.0
imagesize @ file:///home/ktietz/src/ci/imagesize_1611921604382/work
importlib-metadata @ file:///C:/ci/importlib-metadata_1631916848487/work
importlib-resources==5.2.2
inflection==0.5.1
iniconfig @ file:///home/linux1/recipes/ci/iniconfig_1610983019677/work
intervaltree @ file:///Users/ktietz/demo/mc3/conda-bld/intervaltree_1630511889664/work
ipykernel @ file:///C:/ci/ipykernel_1629995240690/work/dist/ipykernel-6.2.0-py3-none-any.whl
ipython @ file:///C:/ci/ipython_1632141541768/work
ipython-genutils @ file:///tmp/build/80754af9/ipython_genutils_1606773439826/work
isort @ file:///tmp/build/80754af9/isort_1628603791788/work
jedi @ file:///C:/ci/jedi_1606914528444/work
Jinja2 @ file:///tmp/build/80754af9/jinja2_1612213139570/work
jinja2-time @ file:///tmp/build/80754af9/jinja2-time_1617751524098/work
jsonschema @ file:///Users/ktietz/demo/mc3/conda-bld/jsonschema_1630511932244/work
jupyter-client @ file:///tmp/build/80754af9/jupyter_client_1630690655192/work
jupyter-core @ file:///C:/ci/jupyter_core_1612213356021/work
jupyterlab-pygments @ file:///tmp/build/80754af9/jupyterlab_pygments_1601490720602/work
keyring @ file:///C:/ci/keyring_1629321676013/work
kiwisolver==1.3.2
lazy-object-proxy @ file:///C:/ci/lazy-object-proxy_1616529307648/work
lockfile==0.12.2
Markdown==3.3.4
MarkupSafe==1.1.1
matplotlib==3.4.3
matplotlib-inline @ file:///tmp/build/80754af9/matplotlib-inline_1628242447089/work
mccabe==0.6.1
mistune==0.8.4
mkl-fft==1.3.0
mkl-random @ file:///C:/ci/mkl_random_1626186184278/work
mkl-service==2.4.0
more-itertools @ file:///tmp/build/80754af9/more-itertools_1622818384463/work
mypy-extensions==0.4.3
nbclient @ file:///tmp/build/80754af9/nbclient_1614364831625/work
nbconvert @ file:///C:/ci/nbconvert_1624479163777/work
nbformat @ file:///tmp/build/80754af9/nbformat_1617383369282/work
nest-asyncio @ file:///tmp/build/80754af9/nest-asyncio_1613680548246/work
numexpr @ file:///C:/ci/numexpr_1618856738664/work
numpy @ file:///C:/ci/numpy_and_numpy_base_1626271903025/work
numpydoc @ file:///tmp/build/80754af9/numpydoc_1605117425582/work
oauthlib==3.1.1
opencv-python==4.5.3.56
packaging @ file:///tmp/build/80754af9/packaging_1625611678980/work
pandas @ file:///C:/ci/pandas_1629682609359/work
pandocfilters @ file:///C:/ci/pandocfilters_1605102497129/work
paramiko @ file:///tmp/build/80754af9/paramiko_1598886428689/work
parso==0.7.0
pathspec==0.7.0
pexpect @ file:///tmp/build/80754af9/pexpect_1605563209008/work
pickleshare @ file:///tmp/build/80754af9/pickleshare_1606932040724/work
Pillow==8.3.2
pluggy @ file:///C:/ci/pluggy_1615976358795/work
poyo @ file:///tmp/build/80754af9/poyo_1617751526755/work
prompt-toolkit @ file:///Users/ktietz/demo/mc3/conda-bld/prompt-toolkit_1629146841569/work
protobuf==3.18.0
psutil @ file:///C:/ci/psutil_1612298324802/work
ptyprocess @ file:///tmp/build/80754af9/ptyprocess_1609355006118/work/dist/ptyprocess-0.7.0-py2.py3-none-any.whl
py @ file:///tmp/build/80754af9/py_1607971587848/work
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycodestyle @ file:///home/ktietz/src/ci_mi/pycodestyle_1612807597675/work
pycparser @ file:///tmp/build/80754af9/pycparser_1594388511720/work
pydocstyle @ file:///tmp/build/80754af9/pydocstyle_1621600989141/work
pyflakes @ file:///home/ktietz/src/ci_ipy2/pyflakes_1612551159640/work
pyglet==1.5.21
Pygments @ file:///tmp/build/80754af9/pygments_1629234116488/work
pylint @ file:///C:/ci/pylint_1627536881874/work
pyls-black @ file:///tmp/build/80754af9/pyls-black_1607553132291/work
pyls-spyder @ file:///tmp/build/80754af9/pyls-spyder_1613849700860/work
pymunk==6.2.0
PyNaCl @ file:///C:/ci/pynacl_1595000047588/work
pyOpenSSL @ file:///tmp/build/80754af9/pyopenssl_1608057966937/work
pyparsing @ file:///home/linux1/recipes/ci/pyparsing_1610983426697/work
pyrsistent @ file:///C:/ci/pyrsistent_1600141795814/work
PySocks @ file:///C:/ci/pysocks_1605287845585/work
pytest==6.2.4
python-dateutil @ file:///tmp/build/80754af9/python-dateutil_1626374649649/work
python-jsonrpc-server @ file:///tmp/build/80754af9/python-jsonrpc-server_1600278539111/work
python-language-server @ file:///tmp/build/80754af9/python-language-server_1607972495879/work
python-slugify @ file:///tmp/build/80754af9/python-slugify_1620405669636/work
pytiled-parser==1.5.3
pytz @ file:///tmp/build/80754af9/pytz_1612215392582/work
pywin32==228
pywin32-ctypes==0.2.0
PyYAML==5.4.1
pyzmq @ file:///C:/ci/pyzmq_1628276144921/work
QDarkStyle @ file:///tmp/build/80754af9/qdarkstyle_1617386714626/work
qstylizer @ file:///tmp/build/80754af9/qstylizer_1617713584600/work/dist/qstylizer-0.1.10-py2.py3-none-any.whl
QtAwesome @ file:///tmp/build/80754af9/qtawesome_1615991616277/work
qtconsole @ file:///tmp/build/80754af9/qtconsole_1623278325812/work
QtPy @ file:///tmp/build/80754af9/qtpy_1629397026935/work
regex @ file:///C:/ci/regex_1629302316714/work
requests @ file:///tmp/build/80754af9/requests_1629994808627/work
requests-oauthlib==1.3.0
rope @ file:///tmp/build/80754af9/rope_1623703006312/work
rsa==4.7.2
Rtree @ file:///C:/ci/rtree_1618421009405/work
scipy==1.7.1
Shapely==1.7.1
sip==4.19.13
six @ file:///tmp/build/80754af9/six_1623709665295/work
snowballstemmer @ file:///tmp/build/80754af9/snowballstemmer_1611258885636/work
sortedcontainers @ file:///tmp/build/80754af9/sortedcontainers_1623949099177/work
Sphinx @ file:///tmp/build/80754af9/sphinx_1623884544367/work
sphinxcontrib-applehelp @ file:///home/ktietz/src/ci/sphinxcontrib-applehelp_1611920841464/work
sphinxcontrib-devhelp @ file:///home/ktietz/src/ci/sphinxcontrib-devhelp_1611920923094/work
sphinxcontrib-htmlhelp @ file:///tmp/build/80754af9/sphinxcontrib-htmlhelp_1623945626792/work
sphinxcontrib-jsmath @ file:///home/ktietz/src/ci/sphinxcontrib-jsmath_1611920942228/work
sphinxcontrib-qthelp @ file:///home/ktietz/src/ci/sphinxcontrib-qthelp_1611921055322/work
sphinxcontrib-serializinghtml @ file:///tmp/build/80754af9/sphinxcontrib-serializinghtml_1624451540180/work
spyder @ file:///C:/ci/spyder_1626182189433/work
spyder-kernels @ file:///C:/ci/spyder-kernels_1625671146339/work
stable-baselines3==1.2.0
tensorboard==2.6.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
testpath @ file:///tmp/build/80754af9/testpath_1624638946665/work
text-unidecode @ file:///Users/ktietz/demo/mc3/conda-bld/text-unidecode_1629401354553/work
textdistance @ file:///tmp/build/80754af9/textdistance_1612461398012/work
three-merge @ file:///tmp/build/80754af9/three-merge_1607553261110/work
tinycss @ file:///tmp/build/80754af9/tinycss_1617713798712/work
toml @ file:///tmp/build/80754af9/toml_1616166611790/work
torch==1.9.0
tornado @ file:///C:/ci/tornado_1606942392901/work
traitlets @ file:///home/ktietz/src/ci/traitlets_1611929699868/work
typed-ast @ file:///C:/ci/typed-ast_1624953785070/work
typing-extensions @ file:///tmp/build/80754af9/typing_extensions_1631814937681/work
ujson @ file:///C:/ci/ujson_1611241570789/work
Unidecode @ file:///tmp/build/80754af9/unidecode_1614712377438/work
urllib3 @ file:///tmp/build/80754af9/urllib3_1625084269274/work
watchdog @ file:///C:/ci/watchdog_1624955096624/work
wcwidth @ file:///Users/ktietz/demo/mc3/conda-bld/wcwidth_1629357192024/work
webencodings==0.5.1
Werkzeug==2.0.1
whichcraft @ file:///tmp/build/80754af9/whichcraft_1617751293875/work
win-inet-pton @ file:///C:/ci/win_inet_pton_1605306167264/work
wincertstore==0.2
wrapt==1.12.1
yapf @ file:///tmp/build/80754af9/yapf_1615749224965/work
zipp @ file:///tmp/build/80754af9/zipp_1625570634446/work

I am using Windows 10 Pro, version 20H2,
OS build 19042.1237

Please let me know if there is any other info you need. I am muddling through it for now (it works, but the blur is just annoying). I appreciate the help!

**Comment by araffin** [comment]
Apparently come from Intel driver: https://discourse.slicer.org/t/issue-on-slicer-ui-in-windows10-green-stripes/17232
You should upgrade/downgrade.

**Comment by jkterry1** [comment]
@cversteeg, I'm going to close the issue based on that. Let me know if the issue persists.
