### ISSUE TITLE
[Bug Report] v5 Environments unexpected keyword frame_skip

### ISSUE THREAD

**Issue by tnfru** [openai/gym#2418]
While following [the blog post on the new v5 environments](https://brosa.ca/blog/ale-release-v0.7) I tried to run the example code and recieved the unexpected keyword error for frame_skip. All other keywords work fine.

`TypeError: __init__() got an unexpected keyword argument 'frame_skip'`

**Code example**
```
import gym

env = gym.make('ALE/Breakout-v5',
    obs_type='rgb',                   # ram | rgb | grayscale
    frame_skip=5,                     # frame skip
    mode=0,                           # game mode, see Machado et al. 2018
    difficulty=0,                     # game difficulty, see Machado et al. 2018
    repeat_action_probability=0.25,   # Sticky action probability
    full_action_space=True,           # Use all actions
    render_mode=None                  # None | human | rgb_array
)
```

**System Info**
Installed gym with pip, on PopOS. Python 3.8.8

**Comment by JesseFarebro** [comment]
Hi! A couple things,

1. I was trying to demonstrate what the different arguments look like that you can now pass to the environment. By no means do you have to specify each one of them, the `v5` environments will specify the appropriate defaults for you. 

2. I seemed to have overlooked that the frame skip argument is `frameskip` and not `frame_skip` as described in the blog post. I will fix this.

3. If you get an error saying Gym can't find the environment try importing `ale_py` after Gym. In the next minor release this won't be necessary but as of 0.20 you'll need to import the ALE so we can register these environments.

**Comment by tnfru** [comment]
Thanks for resolving.

Third point has been an issue for me too, but I figured I might need to import ALE - works great now.
