### ISSUE TITLE
[Proposal] Relocate wrapper tests

### ISSUE THREAD

**Issue by RedTachyon** [openai/gym#2424]
### Proposal 

This is basically my inner pedant speaking. The tests for wrappers are all sitting in `gym/wrappers`, when there's a perfectly fine (and empty) `gym/wrappers/tests` directory sitting there, so they should be moved there.

### Motivation

Despaghettification of the file/directory structure

### Pitch

Put wrappers tests into `wrappers/tests`

### Alternatives

Live with it.

### Additional context

The one case where I see this being breaking in any way if someone imports the tests from gym with hardcoded paths and uses them in downstream code, which feels cursed and I really hope nobody does that.

Also in theory it's possible that one of the tests is written in a way that requires it to be in `gym/wrappers` (e.g. with relative imports), but from a quick glance I don't see anything like that, and if there were, it'd be worth fixing (and would trivially appear when running tests)

I can make a quick PR later today and pray that nothing breaks.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by jkterry1** [comment]
There's also a tests/gym/wrappers. My preference would to move _all_ tests into the format of tests/xxx, e.g. tests/wrappers, tests/envs, etc.

**Comment by jkterry1** [comment]
Closing in favor of PR
