### ISSUE TITLE
[Proposal] Remove the "Box bound precision lowered" warning

### ISSUE THREAD

**Issue by RedTachyon** [openai/gym#2431]
### Proposal 

Remove the warning from https://github.com/openai/gym/blob/master/gym/spaces/box.py#L73

### Motivation

The main motivation is annoyance - in PyBullet envs, specifically [here](https://github.com/bulletphysics/bullet3/blob/master/examples/pybullet/gym/pybullet_envs/robot_bases.py#L25), the bounds of the obs/action spaces are initialized using the default numpy float64, while the Box space is initialized to the default float32. This results in the fact that each time you create an environment, you have a warning

```
/path/lib/python3.9/site-packages/gym/logger.py:34: UserWarning: WARN: Box bound precision lowered by casting to float32 warnings.warn(colorize("%s: %s" % ("WARN", msg % args), "yellow"))
```

Or, if you're using multiple processes, something like:

![image](https://user-images.githubusercontent.com/19414946/135350978-bd58e3cb-c845-46f9-ab90-2646a26d631d.png)

I think the warning isn't that valuable, since it should be obvious that it's the `dtype` argument that defines the type of a `space`, and not the low/high values

### Pitch

Make terminal logs readable again.

### Alternatives

bulletphysics/bullet3#3982 being merged into bullet would be ideal, but I'm not very optimistic considering their backlog of PRs. Still, I'd wait a bit to see if that actually happens. If it doesn't, I want to open a discussion on whether changing it this way would be acceptable.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by jkterry1** [comment]
I disagree with removing this, I think that people need to update things over time for them to continue working as expected. The thing is that all of pybullet is basically deprecated in favor of Brax and Tiny Differentiable Simulator. Environments that are no longer maintained are inherently going to have issues. I also think that the community dependence on pybullet envs in particular going forward will be basically gone except for legacy comparissons once the Brax envs are merged into Gym (which considerable progress is being made twoards).
