### ISSUE TITLE
AttributeError: module 'ale_py.gym' has no attribute 'ALGymEnv'

### ISSUE THREAD

**Issue by mirzaabdulwahab1612** [openai/gym#2432]
### Question

I am trying to install Gym on Windows and MacOS (BigSur) as well. However, whenever I install `pip install gym[atari]` and then try to import any Atari environment, I get this error. Any ideas what could be causing this? I am using Python 3.8. Thanks.

**Comment by kyleabbott** [comment]
Had this issue as well with a fresh install today. `pip install gym` installs version 0.20.0 of gym for me which depends on ale-py for Atari envs, and `pip install gym[atari]` installs 0.7.1 of ale-py; but this dependency appears to be broken (the way `gym/envs/__init__.py` is registering Atari envs is broken w.r.t. the ale-py interface). This appears to be acknowledged in the [tag notes for gym 0.21.0](https://github.com/openai/gym/releases/tag/v0.21.0). Indeed, installing gym from the 0.21.0 tag seems to resolve this issue.

**Comment by JesseFarebro** [comment]
Yes, sorry all, there was a delay with the PyPI `0.21` release which was supposed to drop at the same time as `ale-py==0.7.1`. You can either do as @kyleabbott said and install Gym 0.21 from Github or downgrade ale-py to 0.7, i.e., `pip install --force-reinstall ale-py==0.7`.

**Comment by tfboyd** [comment]
Adding a +1, this was the source of a nightly test failure for us. We will wait until 0.21.0 is released as locking to 0.7 seems like tech debt.

**Comment by JesseFarebro** [comment]
@tfboyd it is fine to include [Tetris by Colin Hughes](https://atariage.com/software_page.php?SoftwareID=3290). It was self-published with no license, i.e., Colin wrote:

```
Hi,

This is my first 2600 program, a clone of Tetris. I wrote this using DASM
to assemble the code and PC Atari 1.5 to test it. Use the joystick to move
the block and the fire button to rotate it.	I don't know what the speed is
like on a real VCS as I'm using a 486DX25 to test the code.
There's currently no sound ( no soundcard ) and I've tried to keep it all
under 2k.

Feel free to do anything you like with this code, I only wrote it to pass
away a few days. If you have any comments feel free to Email me at:

Colin_Hughes@interactive.sony.com


Cheers,

CJH.

10th June 1997.
```

This is how we do basic [unit tests in the ALE](https://github.com/mgbellemare/Arcade-Learning-Environment/tree/master/tests/resources).

**Comment by tfboyd** [comment]
I cannot use that internally, but pulling down this .bin for unit testing could be an option.  It would be awesome if it was included in the .whl but without a license that is likely a big dangerous.  @JesseFarebro **thank you** for the suggestion, I got caught in a bit of tunnel vision. We have a complex internal/external testing setup.  I am still waiting on pins and needles for gym to release the version that is compatible with latest ale.

**Comment by JesseFarebro** [comment]
@tfboyd my email is on my profile, could you send me an email so we can better discuss your needs.

**Comment by jkterry1** [comment]
OpenAI finally cut 0.21.0, which should fix everything here. Please lmk if anything else goes wrong for people.
