### ISSUE TITLE
MacOS + Jupyter window hangs up

### ISSUE THREAD

**Issue by Mazorati** [openai/gym#2433]
Hi, I try to simulate basic example _CartPole-v1_ using Jupyter Notebook.
As I run the code a window with simulation appears, performs the simulation and hangs. The notebook is dead.

If I run the same script without Jupyter it works good.
On Ubuntu also no problems.

**Code example**
```
import gym
env = gym.make("CartPole-v1")
observation = env.reset()
for _ in range(10):
  env.render()
  action = env.action_space.sample() # your agent here (this takes random actions)
  observation, reward, done, info = env.step(action)

  if done:
    observation = env.reset()
env.close()
```

**System Info**
MacOS 11.5.2 (Intel)
Python 3.9.7
jupyter core : 4.7.1
jupyter-notebook : 6.4.3
gym 0.20.0

Similar issue from 2017 (without solution): https://github.com/openai/gym/issues/741

<img width="500" alt="Screenshot 2021-09-30 at 21 15 15" src="https://user-images.githubusercontent.com/3396425/135520120-c8fa303f-8c45-4957-8a4c-af33b05eb4c5.png">

**Comment by jkterry1** [comment]
So this is an issue in jupyter notebooks not us, specifically the render method would cause a pop up to your screen in a new window, and this behavior is not supported in jupyter notebooks AFIAK.

**Comment by francofusco** [comment]
Hello, I was reading #741 and ended up here. I have found a convenient workaround, or at least it seems so to me. My minimal (non-working) example is the "usual one":

```py
import gym

env = gym.make('Pendulum-v1')
env.reset()

while True:
    env.render()
    _,_,done,_ = env.step(env.action_space.sample())
    if done:
         break

env.close()
```

This does not work in the sense that as soon as I focus on the graphical window, it freezes. Same as in @axmav's original issue - my only difference being the OS, I am on Windows 11. I have tried the following:

```py
import gym
import pygame

env = gym.make('Pendulum-v1')
env.reset()

while True:
    env.render()

    for event in pygame.event.get():
        pass

    _,_,done,_ = env.step(env.action_space.sample())
    if done:
         break

env.close()
```

which apparently solves the problem. I do not know `pygame` but I guess that when you try to focus on the window, move it, etc this causes new events to be added to some queue and not handling these events just makes the window idle in a jupyter notebook. If someone has actual knowledge of `pygame` and wants to give a proper answer, please do!

In the meanwhile, I would suggest to simply define a wrapper class as follows:

```py
import gym
import pygame

# Wrapper class that calls the "event loop" for us when rendering.
class PyGameWrapper(gym.Wrapper):
    def render(self, mode="human", **kwargs):
        retval = self.env.render(mode, **kwargs)
        for event in pygame.event.get():
            pass
        return retval

# Wrap the environment
env = PyGameWrapper(gym.make('Pendulum-v1'))

# Now the "usual example" should work fine
env.reset()

while True:
    env.render()

    _,_,done,_ = env.step(env.action_space.sample())
    if done:
         break

env.close()
```

Note that this makes the window completely unresponsive (you can drag it around, but not close it). If you want to exit the loop, you must wait for the simulation to be over. Again, if there is someone who actually knows PyGame, we might be able to have a better solution 😉

@jkterry1 if the workaround works for others as well, it might be interesting to add a comment to #741 as well. I am unsure if you want an actual PR for such a feature, it seems maybe too specific? Maybe it could be useful to add a reference to this in the [standard methods wiki page](https://www.gymlibrary.ml/pages/api/#standard-methods) instead?
