### ISSUE TITLE
Bad rendering with two simultaneous Pyglet windows

### ISSUE THREAD

**Issue by gdb** [openai/gym#244]
Sometimes I'll see uninitialized data on the `e1` window, or a double cartpole rendering there, when running something like this:

`import gym; e1 = gym.make('CartPole-v0'); e2 = gym.make('CartPole-v0'); e1.reset(); e1.render(); e2.reset(); e2.render(); e1.render()`

It's a bit non-deterministic, so you may have to run multiple times. (Also fun to run the same block multiple times within a single Python interactive session — old windows start to display garbage data too, I think.) I assume we're not handling our OpenGL context properly.

**Comment by olegklimov** [comment]
I tried this.

On Ubuntu 14.04, Titan X: cannot reproduce anything, works perfect, even in a loop.

MacBook Pro 10.9.5 Intel GPU: black background for e1 every time, nothing non-deterministic. Only second `e1.render()` (as in your code) produces black background. Subsequent renders (and first of course) make normal image.
