### ISSUE TITLE
gym.error.UnregisteredEnv: No registered env with id: SpaceInvaders-v0[Question] Question title

### ISSUE THREAD

**Issue by TonFard** [openai/gym#2442]
import gym
from skimage import io
env = gym.make('SpaceInvaders-v0')
status = env.reset()

for step in range(1000):
    env.render()
    thisstep = 1
    status, reward, done, info = env.step(thisstep)
    jpgname = './pic-%d.jpg' % step
    io.imsave(jpgname, status)
    print(reward)
    if done:
        print('dead in %d steps' % step)
        break
env.close()
I run these codes on win10pycharm, but there is such an error, I don’t understand

**Comment by gsq88** [comment]
i have solved my problem, thank you for your suggestion
only add this two lines, it's ok
pip install ale-py
pip install gym[accept-rom-license]

**Comment by gsq88** [comment]
i have solved my problem, thank you for your suggestion
only add this two lines, it's ok
pip install ale-py
pip install gym[accept-rom-license]
