### ISSUE TITLE
Third party environments no longer available

### ISSUE THREAD

**Issue by DarthMalloc** [openai/gym#2453]
I'm not sure if this is the right place for my question, but I noticed that on the main gym environment list, when I click the link for third-party environments, it takes me to a blank Github page instead. I am therefore wondering where to find the third-party environments.

**Comment by RedTachyon** [comment]
You're probably looking for this? https://github.com/openai/gym/blob/master/docs/third_party_environments.md

Where exactly is the broken link?

**Comment by JoKoum** [comment]
@RedTachyon I believe that @DarthMalloc refers to the https://gym.openai.com/envs page, where the **Third party environments** link points to https://github.com/openai/gym/blob/master/docs/environments.md#third-party-environments

**Comment by jkterry1** [comment]
That website is no longer maintained and I have no ability to edit anything on it. We're working on a new documentation website that will have appropriate links and so on. The current plan was to finish in a few weeks but the developer has became very ill last week so there are (further) delays.
