### ISSUE TITLE
Better error messages for capitalization variance in Gym

### ISSUE THREAD

**Issue by jkterry1** [openai/gym#2455]
I just spent 15 minutes debugging, only to realize the issue was that I was typing `pendulum-v1` instead of `Pendulum-v1`. These names really ought to be capitalization invariant.

**Comment by jkterry1** [comment]
error messages that responsibly handle this is probably better, yes

**Comment by kir0ul** [comment]
https://github.com/openai/gym/pull/2535 should take care of this issue now.
