### ISSUE TITLE
[Question] Details regarding the terminal conditions for LunarLander-v2

### ISSUE THREAD

**Issue by hagerrady13** [openai/gym#2468]
### When does LunarLander terminate?

I have been carefully looking into LunarLander to model the environment dynamics but there seems to be little documentation on when it terminates; it is not clear in the source code too.

There are two cases:
- If it fails by hitting anywhere outside the landing pad, it receives -100 reward and terminates, but how do you decide on that? The leg contacts do not seem to be enough, can we use the lander coordinates to check for that if we know that the landing pad is at (0,0)?

- If it reaches the landing pad by checking if the lander is awake, is it the state when the lander no longer moves? so it basically provides rewards for landing and not moving anymore? Moreover, what makes a lander not awake?

If someone can provide more information behind the conditions of termination on LunarLander, that would be great!
@olegklimov

**Comment by kir0ul** [comment]
My understanding is the following, the `LunarLander` environment terminates if:
1) the lander crashes (the lander body gets in contact with the moon);
2) the lander gets outside of the viewport (`x` coordinate is greater than 1);
3) the lander is not awake. From the [Box2D docs](https://box2d.org/documentation/md__d_1__git_hub_box2d_docs_dynamics.html#autotoc_md61), a body which is not awake is a body which doesn't move and doesn't collide with any other body:
> When Box2D determines that a body (or group of bodies) has come to rest, the body enters a sleep state which has very little CPU overhead. If a body is awake and collides with a sleeping body, then the sleeping body wakes up. Bodies will also wake up if a joint or contact attached to them is destroyed.

I will add this to the docs in https://github.com/Farama-Foundation/gym-docs/pull/9.

Hope that helps!
