### ISSUE TITLE
Too large action spaces for most Doom environments

### ISSUE THREAD

**Issue by danijar** [openai/gym#248]
In some Doom environments, the action space is restricted using `available_buttons` in the Doom configuration file. However, `env.action_space` is the full actions space for all Doom environments. There is also a member called `allowed_actions` that removes actions not in the list before forwarding the remaining ones to the game.

I think we should dynamically create the action space based on the list of `allowed_actions` so that one bot can be efficiently used on all environments without modifications. I can help with a pull request if wanted, it would be a nice project to get started contributing to gym.

**Comment by ppaquette** [comment]
You should look at the comments on pull request #157 . 

The original PR had a "small" action space (i.e. only the commands used in the env), but it was decided to use the full action space on all environments, because that would only slow down the algos by a constant factor, and would permit transfer learning.

In all cases, if it is an issue, you can probably train an algo on a custom small action space, and map it back to the full action space on each step. 

As for your suggestion, the actions in allowed_actions are different in every doom env, which makes learning across envs hard to do (e.g. the second item in the array might be MOVE_RIGHT in one env, and TURN_RIGHT in another).

**Comment by jietang** [comment]
@danijar any updates?

**Comment by danijar** [comment]
I see the problem and it makes sense to have a common action space for all Doom environments. It's just that with current state-of-the-art, it's hard to learn anything in Doom because it's a comparably complex environment and the large action space doesn't make it easier. The authors of VizDoom also reduce the action space in their experiments.

For my own experiments, I wrapper the Doom envs with my own environment that reduces the action space and unfolds the actions from the agent before forwarding them to the Doom environment. Changing the action space is really part of the environment, not the agent. Otherwise, the agent would not be general purpose anymore. Maybe we want a `env.configure()` option for whether to use the available or full action space?

**Comment by ppwwyyxx** [comment]
The best part of the doom environment is that it is highly customizable. In my research I customize reward & buttons & render options & wad files a lot, and it would be very good to see some of these options available in gym.

**Comment by danijar** [comment]
@ppwwyyxx I agree, it would be nice to have an abstract doom environment class (There is already something similar). Of course, that shouldn't have a scoreboard on the webservice because people might configure it differently. The existing Doom tasks could make use of this class then.

**Comment by ppaquette** [comment]
Submitted PR #282 with action_filter parameter on configure(). You can set action_filter to be one of:

- 'doom-minimal' (Discrete action space with only the level's allowed_actions and noop)
- 'doom-constant-8' (Discrete action space with noop + 7 actions required to pass all levels)
- 'doom-constant-18' (Discrete action space with noop + 17 most common actions)
- 'reset' (Resets action space to HighLow with 43 commands)

Let me know what you think of it.

For the custom/abstract level, please open another issue with a better explanation of the features you want to be able to configure.

**Comment by danijar** [comment]
Thanks a lot. I like both that this allows to use the minimal action set and that is allows to use discrete action spaces. The tasks on the web service will keep using the full action space, I guess? Regarding the custom levels, I opened https://github.com/openai/gym/issues/283.

**Comment by ppaquette** [comment]
I converted doom to a custom env.

1) you need to install ``gym_pull`` with ``pip install gym_pull``
2) you need to pull the custom env with:

```
import gym
import gym_pull
gym.pull('ppaquette/gym-envs/DoomBasic')   # You can use gym.pull('ppaquette/gym-envs/*') to download all my custom envs, but there are 75+
env = gym.make('ppaquette/DoomBasic-v0')
```

If you go the my [gym-envs](https://github.com/ppaquette/gym-envs) repo, you can manually download wrappers to modify the env (including the action space).

If you want more customization, you can just fork the repo, modify a couple of lines directly, adjust the '.openai.yml' in the root folder, and then download the env with gym.pull('<your username>/<your repo>/<env name>'). The openai.yml documentation is [here](https://github.com/ppaquette/gym_pull)

**Comment by christopherhesse** [comment]
Thanks @ppaquette!  We don't have doom environments anymore, so any users with this issue should try `ppaquette/gym-envs/DoomBasic` or the `VizDoom` python bindings.
