### ISSUE TITLE
Can not download files from Virustotal

### ISSUE THREAD

**Issue by rhr407** [openai/gym#2485]
I can not download the malware samples from Virustotal using the download_samples.py script inside the repo folder[Kindly see the error in the image below]. I will highly appreciate your help on this.

My Python version is 3.8

- [x ] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

![image](https://user-images.githubusercontent.com/26026993/142003945-23a857e7-964a-4387-bebf-df60548fa3aa.png)

**Comment by ikamensh** [comment]
I don't see a file `download_samples.py` in the repo tree here, are you sure you are reporting bug to the right repository?

**Comment by rhr407** [comment]
My bad! I was out of mind. Sorry about that. I had to report on another github tab. This repo was open besides that. My apologies!!
