### ISSUE TITLE
How to use the monitor with multiple environment instances?

### ISSUE THREAD

**Issue by danijar** [openai/gym#249]
From the docs:

> This will log your algorithm's performance to the provided directory. The monitor is fairly sophisticated, and supports multiple instances of an environment writing to a single directory.

Should I create on monitor for each of the environment instances? This gives me an error `You should use a unique directory for each training run...`. If I should use only one monitor, which environment instance should I use to access it and how would it know about the other environments?

**Comment by jietang** [comment]
Can you describe your use case a bit more? Are you trying to log the results from running one algorithm on different environments to the same directory, many algorithms on the same environment, or multiple runs of the same algorithm on the same environment?

If it's the latter case, you can disable the error by passing resume=False to monitor.start(). Be warned that the results from multiple runs will get merged together when e.g. submitting to the scoreboard.

**Comment by danijar** [comment]
One agent and one environment, but multiple instances of that environment, as suggested in [arXiv:1602.01783[1]. I had to set `reuse=True` when starting the monitor and it works now. Is this option meant for parallel learning? If so, it might be mistaken by users because it sounds like reusing an old directory for a new experiment.

[1]: https://arxiv.org/abs/1602.01783

**Comment by gdb** [comment]
It should work fine to have multiple monitors pointed at the same directory without `resume=True` (as you say, `resume` is intended for continuing a previous training run). You just need to make sure to `start` all of them before `reset`ing.

**Comment by gdb** [comment]
(Let me know if you're still seeing trouble; otherwise closing for now.)

**Comment by danijar** [comment]
Sorry for the late reply. I can confirm that everything it working as expected now, without the `resume` flag set.
