### ISSUE TITLE
Move unittest envs to tests directory

### ISSUE THREAD

**Issue by jkterry1** [openai/gym#2492]

**Comment by WillieCubed** [comment]
Hey, I started looking into the repo's directory structure, and it was unclear how to properly run the tests. I see the `CONTRIBUTING.md` file nor the `docs/` directory have that information, so could @jkterry1 provide some more information on what unit/integration tests exist and how to run them?

**Comment by jkterry1** [comment]
See: 

 https://github.com/openai/gym/tree/master/.github/workflows, the /tests folder and github actions CI that's run on open PRs

**Comment by jkterry1** [comment]
like, there are unittest envs in the envs folder. These should be in the tests folder. It's a fairly simple thing?

**Comment by jkterry1** [comment]
Closed by #2553
