### ISSUE TITLE
[Question] Is the new `Pong-v0` environment equivalent to the old `Pong-NoFrameskip-v4` environment?

### ISSUE THREAD

**Issue by 00krishna** [openai/gym#2499]
### Question

I know that Pong is one of the most cited environments in reinforcement learning. With recent changes in the OpenAI API, it seems that the `Pong-NoFrameskip-v4` environment is no longer part of the environment, or needs to be loaded from the `atari_py` package. I was wondering whether the current `Pong-v0` that is currently part of OpenAI is a suitable replacement or equivalent to the original `Pong-NoFrameskip-v4`? Like will the benchmarks for training models be roughly the same, etc?

The challenge is that the Maxim Lapan book, and so many tutorials reference the original `Pong-NoFrameskip-v4` environment, and given the API changes this demo code no longer works. Hence it would be helpful to answer the question here, so that other users might get the answer to this important newbie question. Thanks.

**Comment by JesseFarebro** [comment]
The environment names haven't changed and are fully backwards compatible. I'm pretty sure the proper environment ID has always been: `PongNoFrameskip-v4` and if you try instantiating this environment ID with the `ale-py` package installed everything works as expected.
