### ISSUE TITLE
Random Seed Feature

### ISSUE THREAD

**Issue by RuofanKong** [openai/gym#250]
I am just wondering if the user can set a random seed so it could reproduce all game states for testing purpose. Is it possible to support it if there is no such feature? Thanks!

**Comment by jietang** [comment]
Yes, envs in gym expose a seed() function for exactly this purpose e.g.

```
>>> import gym
>>> env = gym.make('CartPole-v0')
>>> env.seed(0)
```

This could be documented better.

**Comment by RuofanKong** [comment]
@jietang Thanks! I also wonder if `env.reset()` will reset the seed that I previously set. For example, 
```
import gym
env = gym.make('CartPole-v0')
env.seed(0)

# reset the environment.
env.reset()
# Then the random seed is still 0 or not?
```
In this case, does `reset()` reset seed as well?

**Comment by danijar** [comment]
Hopefully not, otherwise the agent would always train on the same scenario.

**Comment by gdb** [comment]
(Correct, it does not.)


- gdb
