### ISSUE TITLE
RecordVideo Documentation - How to record without rendering a video?

### ISSUE THREAD

**Issue by MLTrap** [openai/gym#2500]
I am trying to use the new RecordVideo wrapper, however, a video always displays. Is there a way to disable rendering? Am I using RecordVideo correctly? I am running this on a linux server through ssh and the login node. I run it on jupyterlab. Below is the code that I am using:

`import gym
from gym.wrappers import record_video

    
env = record_video.RecordVideo(gym.make('MountainCarContinuous-v0'), video_folder="./Unfinished/recordings/mcc.mp4")

for i_episode in range(5):
    observation = env.reset()
    for t in range(100):
        # env.render()
        # print(observation)
        action = env.action_space.sample()
        observation, reward, done, info = env.step(action)
        if done:
            # print("Episode finished after {} timesteps".format(t+1))
            break
env.close()`

**Comment by vwxyzjn** [comment]
Hey sorry for the late reply. There is no way to disable the rendering in the current implementation. A common way to record on servers is to use `xvfb-run`. Example:

```
xvfb-run -a python my script.py
```
