### ISSUE TITLE
[Bug Report] environment close() does not close the viewer for mujoco task.

### ISSUE THREAD

**Issue by PuzeLiu** [openai/gym#2503]
Hi, 
When I call the env.close() function for mujoco environment, the viewer() still remains. And the next time I call the render() function, it will pop up a new viewer. Here is an example code: 

```
import gym
import numpy as np

env = gym.make('Hopper-v2')

for i in range(10):
    env.reset()
    for j in range(1000):
        action = np.random.randn(3)
        env.step(action)
        env.render()

    env.close()
```
Can you please fix this issue? Thanks!

**Comment by Markus28** [comment]
Concerning your code snippet: It is my understanding that you should not interact with the environment after having called `close`. Thus, `env.close()` should be *outside* the first loop. Nonetheless, one might still want `close` to actually close the glfw window.

There is a strange line in `close`: https://github.com/openai/gym/blob/941e5bfea3abbea4a85a2fdc1752cdea28b36229/gym/envs/mujoco/mujoco_env.py#L183 

Uncommenting it will throw an error when `close` is called. Idk what it is doing there.

Quick googling leads to this issue: https://github.com/openai/mujoco-py/issues/349 .
I would suggest adding the following to `close` in `MujocoEnv`:

```
if "human" in self._viewers:
    glfw.destroy_window(self._viewers["human"].window)
``` 
If this is an acceptable solution, I can create a PR for this.

**Comment by aniruddhkb** [comment]
Just chiming in -- @Markus28 's solution worked for me, although I did have to add 

`import glfw`
to the top of mujoco_env.py
