### ISSUE TITLE
Trying to get sample code run, terminal freezes after import

### ISSUE THREAD

**Issue by lbandy** [openai/gym#251]
Hey guys,

I've been trying to set up gym on two different platforms. I've done an installation on Windows using Cygwin and ImageMagick. I got to the point when running my test.py, which contains only the basic sample code from the site, and here the terminal seems to freeze and nothing happens. If I click anywhere or hit ctrl+c the following errors appear, and I'm returned to the command prompt:
./test.py: line 2: syntax error near unexpected token '('
./test.py: line 2: 'env = gym.make('CartPole-v0')'

I've tried setting up VirtualBox and installed Ubuntu Linux on it. After getting the gym installed I experience exactly the same behavior. It also worth noting that no windows getting opened. I've used "pip install gym" in both cases.

If anyone could provide any advice how to move forward with this I would greatly appreciate that!

**Comment by tlbtlbtlb** [comment]
That error appears to be due to executing test.py with a shell instead of Python.

Try running 
```sh
$ python test.py
```

**Comment by lbandy** [comment]
I can't imagine how dumb I'm looking right now... Thank you very much for your help!
