### ISSUE TITLE
[Question] Does gym provide type stubs?

### ISSUE THREAD

**Issue by syheliel** [openai/gym#2526]
### Question
It seems that `Pylance` can't find the type stubs and there are no package like `gym-types` to fix it.
![image](https://user-images.githubusercontent.com/45957390/145765731-2938b8c1-e53d-4696-bf7b-6354f08a24c6.png)

**Comment by ilyabosch** [comment]
This might be because the library doesn't have `py.typed` file. According to https://www.python.org/dev/peps/pep-0561/ a library should have this in it's file tree to signal that sources should be used for type checking.

**Comment by jkterry1** [comment]
So, Gym does not provide type stubs. However, we're working on adding type hints, which there are issues tracking. Is there any reason to deal with type hints as well given this?
