### ISSUE TITLE
what is the mapping between action and gripper posture of fetch robot in fetch_env.py?

### ISSUE THREAD

**Issue by whynpt** [openai/gym#2532]
I want to pick a bottle with fetch robot, but the gripper posture is specific as ` rot_ctrl=[1.0, 0.0, 1.0, 0.0]` in fetch_env.py `_set_action`. With such posture fetch robot cann't pick bottle sucessfully, so I wang to know the mapping of action and posture in `utils.mocap_set_action(self.sim, action)`.

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
