### ISSUE TITLE
[Question] CartPole observation space doubled in constructor

### ISSUE THREAD

**Issue by Jose-Verdu-Diaz** [openai/gym#2542]
The [CartPole](https://github.com/openai/gym/blob/master/gym/envs/classic_control/cartpole.py) implementation states states the [following](https://github.com/openai/gym/blob/2af816241e4d7f41a000f6144f22e12c8231a112/gym/envs/classic_control/cartpole.py#L31) for the observation space:

```
Observation:
        Type: Box(4)
        Num     Observation               Min                     Max
        0       Cart Position             -2.4                    2.4
        1       Cart Velocity             -Inf                    Inf
        2       Pole Angle                -0.209 rad (-12 deg)    0.209 rad (12 deg)
        3       Pole Angular Velocity     -Inf                    Inf
```

`x_threshold` is set to `2.4` ([view](https://github.com/openai/gym/blob/2af816241e4d7f41a000f6144f22e12c8231a112/gym/envs/classic_control/cartpole.py#L78)), but the value is doubled when defining the `high` array ([view](https://github.com/openai/gym/blob/2af816241e4d7f41a000f6144f22e12c8231a112/gym/envs/classic_control/cartpole.py#L84)). What is the reason behind this? Shouldn't the documentation reflect it?

The same happens with `theta_threshold_radians`. A comment states: `Angle limit set to 2 * theta_threshold_radians so failing observation is still within bounds`, but I don't fully understand it.

**Comment by jkterry1** [comment]
See this doc: https://github.com/Farama-Foundation/gym-docs/blob/main/docs/classic_control/cartpole.md (it will be used in the new documentation website)
