### ISSUE TITLE
[Bug Report] 404 on gym.openai.com/envs

### ISSUE THREAD

**Issue by kylefmohr** [openai/gym#2543]
**Describe the bug**
The link to "Third party environments" on this website 404s: https://gym.openai.com/envs/

**Code example**
N/A

**System Info**
Chrome, Windows 11

**Additional context**
Just noticed that the link to "Third party environments" results in a GitHub 404 error on this website: https://gym.openai.com/envs/

~~I think the link should be https://github.com/openai/gym/wiki/Table-of-environments however I'm not 100% sure about this.~~

**See @jkterry1's comment for the correct link**

I also did not see this page in the repository, so apologies if this is the wrong place to post this issue. 

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by jkterry1** [comment]
So, I can't fix that site, and the new one should be up very soon. The actual file is here though: https://github.com/Farama-Foundation/gym-docs/blob/main/docs/third_party_environments.md

**Comment by kylefmohr** [comment]
Thanks, updated my comment to reflect this (and fixed the title!)
