### ISSUE TITLE
How to get the list of all possible observation spaces?

### ISSUE THREAD

**Issue by biplavc** [openai/gym#2545]
Currently, the available methods are to sample a particular observation and to get the highest and lowest values. Is there a way to get a list of all possible observations?

Edit: the new method would be in the [Box class](https://github.com/openai/gym/blob/master/gym/spaces/box.py) -

**Comment by balisujohn** [comment]
If I'm understanding correctly, you want a list of all possible observations in the observation space of a Box env. This could be practical in the Discrete env, but in the context of a Box env(continuous observation space) the observation is generally a vector of floating point values. Given the massive number of possible floating point values, this might even be intractable for a 1-D observation space, and would certainly become intractable as the number of dimensions in the observation space increases. https://jameshoward.us/2015/09/09/how-many-floating-point-numbers-are-there/

Please let me know if I'm misunderstanding your question.
