### ISSUE TITLE
Where can I find third-party environments?

### ISSUE THREAD

**Issue by DarthMalloc** [openai/gym#2558]
I am unable to locate the repository for third-party environments.
The page on gym.openai.com that lists environments has a link that goes to third-party environments. However, when I click that link, I get a "page not found" message from github.

Please share the new location of that repository, if it still exists.

**Comment by jkterry1** [comment]
It's here: https://github.com/Farama-Foundation/gym-docs/blob/main/docs/pages/third_party_envs/index.md

there will be a new fancy website soon that uses them :)
