### ISSUE TITLE
Modifying mujoco xml file to modify environment

### ISSUE THREAD

**Issue by wj210** [openai/gym#2559]
I am trying to modify the inverteddoublependulum environment in mujoco and tried to changed the xml parameters in the gym envs folder, however when i load the environment in my script, it still loads back the same un-modified environment. 
I am creating a closed-loop kinematic chain by adding another cart with poles connecting to the original cart. 
Am i missing a step such as using some wrapper or having to register the environment?
Thanks, its first first time doing this.

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
