### ISSUE TITLE
How do i display the super mario environment on google colab?

### ISSUE THREAD

**Issue by flowerboy9** [openai/gym#2560]
```
done = True
for step in range(5000):
  if done:
    env.reset()
    state, reward, done, info = env.step(env.action_space.sample())
  env.render()

env.close()
```

when run this code i get this error

`AttributeError        Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/pyglet/__init__.py in __getattr__(self, name)
    328         try:
--> 329             return getattr(self._module, name)
    330         except AttributeError:

AttributeError: 'NoneType' object has no attribute 'key'

During handling of the above exception, another exception occurred:

NoSuchDisplayException                    Traceback (most recent call last)
11 frames
/usr/local/lib/python3.7/dist-packages/pyglet/canvas/xlib.py in __init__(self, name, x_screen)
    121         self._display = xlib.XOpenDisplay(name)
    122         if not self._display:
--> 123             raise NoSuchDisplayException('Cannot connect to "%s"' % name)
    124 
    125         screen_count = xlib.XScreenCount(self._display)

NoSuchDisplayException: Cannot connect to "None"`

how do i display the other screen that displays the game i have tried using matplotlib along with all the necc. imports but its very slow and take a long time to complete the above steps so i had to reduce it to 5000 but still it took a long time in this youtube video this person doesnt install and extra packages and the rendering screen appears how do i do that? if its not possible on colab then how do i do it on jupyter notebook. this is the video [https://www.youtube.com/watch?v=2eeYqJ0uBKE&t=941s](url)

**Comment by msaroufim** [comment]
Google collab doesn't have a monitor associated with it, so what you need to do is record the agent playing and then watch

# Record agent

```python
import gym
from gym import wrappers

env = gym.make('SpaceInvaders-v0')
env = wrappers.Monitor(env, "./gym-results", force=True)
env.reset()
for _ in range(1000):
    action = env.action_space.sample()
    observation, reward, done, info = env.step(action)
    if done: break
env.close()
```

# Watch agent

```python
import io
import base64
from IPython.display import HTML

video = io.open('./gym-results/openaigym.video.%s.video000000.mp4' % env.file_infix, 'r+b').read()
encoded = base64.b64encode(video)
HTML(data='''
    <video width="360" height="auto" alt="test" controls><source src="data:video/mp4;base64,{0}" type="video/mp4" /></video>'''
.format(encoded.decode('ascii')))
```

Probably worth someone building Google collab for RL - maybe @simoninithomas has put some more thought into this

**Comment by flowerboy9** [comment]
> Google collab doesn't have a monitor associated with it, so what you need to do is record the agent playing and then watch
> # Record agent
> 
> ```python
> import gym
> from gym import wrappers
> 
> env = gym.make('SpaceInvaders-v0')
> env = wrappers.Monitor(env, "./gym-results", force=True)
> env.reset()
> for _ in range(1000):
>     action = env.action_space.sample()
>     observation, reward, done, info = env.step(action)
>     if done: break
> env.close()
> ```
> 
> # Watch agent
> 
> ```python
> import io
> import base64
> from IPython.display import HTML
> 
> video = io.open('./gym-results/openaigym.video.%s.video000000.mp4' % env.file_infix, 'r+b').read()
> encoded = base64.b64encode(video)
> HTML(data='''
>     <video width="360" height="auto" alt="test" controls><source src="data:video/mp4;base64,{0}" type="video/mp4" /></video>'''
> .format(encoded.decode('ascii')))
> ```
> 
> Probably worth someone building Google collab for RL - maybe @simoninithomas has put some more thought into this

okay thank you sir i will try it right now also how what should i do on jupyter lab to make the rendering screen pop up cause when i run that above code(the one i pasted) on jupyter lab as well it throws an error

**Comment by jkterry1** [comment]
(closing since the question is answered, but obviously please feel free to have a discussion)

**Comment by engbJapan** [comment]
I have done real-time graphics of "Moon Landing, Xeyes, Xterm" in ColabNoteBook.
It provides an X desktop with a NOVNC viewer embedded inside ColabNotebook.

see below
NoteBook:
https://github.com/engbJapan/Programming/blob/main/VNCinCellJapan.ipynb
Youtube:
https://youtu.be/CihGimhrclQ
Qiita:
https://qiita.com/engbJapan/items/f39b2f927de290e6a65f
