### ISSUE TITLE
Error with Seed

### ISSUE THREAD

**Issue by harshraj22** [openai/gym#2562]
https://github.com/openai/gym/blob/44242789179d79fae1d5636fa6db23491a5c422e/gym/wrappers/normalize.py#L67

Below set of wrapper 
```python3
from future_gym_wrapper import NormalizeObservation, NormalizeReward

 env = SyncVectorEnv([
        lambda: RecordEpisodeStatistics(
            NormalizeReward(
                NormalizeObservation(
                    ClipAction(gym.make('Pendulum-v0'))
                )
            )
        )
    ])
```
with Pendulum-v0 gives Error

![image](https://user-images.githubusercontent.com/46635452/149627135-345bb310-7b98-4ae6-9725-f3223e61f2ae.png)

Gym Version Using: '0.19.0'
Since NormalizeReward & NormalizeObservation were not available in that version, I copied the file from latest repo, and imported.

**Comment by RedTachyon** [comment]
The API has changed a bit on current master, so you can't just copy paste code and mix it with old code. You can probably fix it by changing the calls to `env.reset` in the copied code.
