### ISSUE TITLE
[Bug Report] In cart pole v1 the window doesn't open and the program stops immediately

### ISSUE THREAD

**Issue by gbocs** [openai/gym#2563]
Hi everyone and thank you. Im sorry for the bad layout because i'm new in github.

I tried to copy and paste the entire code for the cart pole v1 with reinforcement learning in jupyter notebook. The window doesn't open and the program stops immediately without displaying any error message. I have installed all required libraries and tried many times in different conditions, but nothing changes. 

but if i run the test code suggested in the download (the short part) it goes ok and show up the window: 

import gym
env = gym.make('CartPole-v0')
env.reset()
for _ in range(1000):
    env.render()
    env.step(env.action_space.sample()) # take a random action
env.close()

this works , but the complete code not works.

**Comment by RedTachyon** [comment]
What exactly is the "complete code" that doesn't work?

**Comment by gbocs** [comment]
> What exactly is the "complete code" that doesn't work?

the complete code is the one in this page (the official code example for cart pole v1 directly linked from openai gym website)

https://github.com/openai/gym/blob/master/gym/envs/classic_control/cartpole.py

**Comment by jkterry1** [comment]
(feel free to continue discussing questions, but this does not appear to be a well defined open issue with gym)
