### ISSUE TITLE
Potential dead code in utils

### ISSUE THREAD

**Issue by jkterry1** [openai/gym#2572]
Without any further review on my end, the following files possibly are dead code, and/or should be removed for refactoring purposes:

https://github.com/openai/gym/blob/master/gym/utils/atomic_write.py
https://github.com/openai/gym/blob/master/gym/utils/closer.py
https://github.com/openai/gym/blob/master/gym/utils/json_utils.py

**Comment by gianlucadecola** [comment]
From what I'm seeing they are used in Monitor (which is deprecated)  and in StatsRecorder (which is not deprecated but only used by Monitor).
I could tackle  #2367, and then work on this

**Comment by jkterry1** [comment]
Closed in favor of PR
