### ISSUE TITLE
[Proposal] Add license to the license field in the setup.py file

### ISSUE THREAD

**Issue by jaredvann** [openai/gym#2573]
### Proposal 

Add license to the license field in the setup.py file.

### Motivation

The license field is defined but not completed in the setup.py file. 

Some package dependency scanners will block the usage of this package as the license is not specified.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by jkterry1** [comment]
We'd just need to specify the MIT license flag in setup.py right? if that's the case, could you please do a tiny PR for this?
