### ISSUE TITLE
uploaded frozen submissions

### ISSUE THREAD

**Issue by tsadigovAgmail** [openai/gym#2592]
### Question
I know once there was option to upload solutions and compare to other applications. But it got frozen. 
I would like to ask where I can get those now.

When I searched I got to this link which does not work
https://openai-kubernetes-prod-scoreboard.s3.amazonaws.com/v1/evaluations/eval_lx2AyNgERragVmNtY1t67A/training_episode_batch.json

**Comment by jkterry1** [comment]
Hey, I think you accidentally posted on the wrong repository?
