### ISSUE TITLE
[Proposal] Adding Constant variable for different Environments available within Gym

### ISSUE THREAD

**Issue by gauranshkumar** [openai/gym#2603]
### Proposal 
Create a simple constant file with storing already available environment. Something like this
```python3
from gym.environments import CurrentEnv
print(CurrentEnv.CARTPOLEV1)
```
Expected Output:
```
'CartPole-v1'
```
### Motivation
I am new to the Gym and the major Issue that frustrates me is to change the name of different environments by constantly looking at the [gym envs](https://gym.openai.com/envs) page. In general workflow we know the name of the environments but just to get the exact name of the env we need to switch to docs. So it would be really great to just put a constant in the API itself as described above.

### Pitch

We will be needing to add a file in the environment sub-module and store all the currently available environments in there.

### Alternatives

We can also add a simple class instead of the file in the environment.py and this too will work 

### Additional context

I will be happy to work on this and would create a PR if this issue gets validated.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by ikamensh** [comment]
So you suggest to have an Enum that would have autocompletion in IDE for available environments, right?

**Comment by gauranshkumar** [comment]
Yes exactly @ikamensh, It would be very Intuitive to create the environments with this feature

**Comment by RedTachyon** [comment]
So I'm not a huge fan of an enum/constants for that, it's another place where a name has to be maintained anyways. Maybe something that would help instead is an easily accessible list of registered environments? For example
```python
print(env.envs.ALL_ENVS)
# [ CartPole-v0, CartPole-v1, Pendulum-v1, ...]
```

Worth remembering that it is always possible to just import the specific env and instantiate it yourself with whatever parameters you need:
```python
from gym.envs.classic_control import CartPoleEnv
env = CartPoleEnv(...)
```
