### ISSUE TITLE
[Bug Report] Can't define start for Discrete Space 

### ISSUE THREAD

**Issue by ahmedo42** [openai/gym#2605]
**Describe the bug**
__init__() got an unexpected keyword argument 'start'

```python
import gym
from gym.spaces import Discrete 

observation_space = Discrete(5, start=-2)
```

**System Info**
* Ubuntu version
18.04.5 LTS
* Gym version
0.21.0
 * Python version
 3.7.12

**Additional context**
The problem persists on my local machine , kaggle kernels , collab
### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by gianlucadecola** [comment]
Tagged 0.21.0 version does not have the start argument in the init. You can use ```Discrete(5)``` .
If you instead need to set the start argument install gym from the repo to get the latest version on master branch with ```pip install git+https://github.com/openai/gym.git```.
You do this also on Colab ```!pip install git+https://github.com/openai/gym.git```

**Comment by ahmedo42** [comment]
@gianlucadecola Thanks! , it works now
