### ISSUE TITLE
[Bug Report] Bug title self.np_random, seed1 = seeding.np_random(seed) can't set attribute

### ISSUE THREAD

**Issue by yeyimilk** [openai/gym#2610]
If you are submitting a bug report, please fill in the following details and use the tag [bug].

**Describe the bug**
Python code error

**Code example**
in environment.py, line 165
`self.np_random, seed1 = seeding.np_random(seed)`

by looking to the code,  class `AtariEnv`(environment.py)'s parent class `Env`(core.py), it has a propery

```
@property
    def np_random(self) -> RandomNumberGenerator:
        """Initializes the np_random field if not done already."""
        if self._np_random is None:
            self._np_random, seed = seeding.np_random()
        return self._np_random
```

The most easiest way to fix bug maybe to change
`self.np_random, seed1 = seeding.np_random(seed)`
into 
`self._np_random, seed1 = seeding.np_random(seed)`

**System Info**
macOS 10.15.7 
pip 22.0.3 

 * Python version
3.8.6

**Comment by RedTachyon** [comment]
This just seems to be because ALE isn't yet updated to support the not-yet-released version of gym? Use the official releases that are compatible with one another, not `master`
