### ISSUE TITLE
[Proposal] fix linebreaks on gymlibrary.ml

### ISSUE THREAD

**Issue by Arcify** [openai/gym#2627]
After having changed the documentation in the frozen lake environment, I noticed that the linebreaks do not show up correctly at [https://www.gymlibrary.ml/pages/environments/toy_text/frozen_lake](url) because I did not know that the documentation was directly rendered onto the website

- at the bottom the version history is all on the same line.
- the explanation about the observation states can also need some linebreaks or periods.
- maybe also add an extra header for both the action space and the observation space

**Comment by trigaten** [comment]
- [x] version history fixed
- [x] periods added
- [x] headers added 
Fixed here: https://github.com/openai/gym/pull/2628
