### ISSUE TITLE
[Bug Report] NChain environment doesn't exist 

### ISSUE THREAD

**Issue by RomanGirin** [openai/gym#2631]
**Describe the bug**
Seems like NChain environment doesn't exist although according the docs (https://gym.openai.com/envs/NChain-v0/) it should be in the list.

**Code example**
import gym
env = gym.make('NChain-v0')

throws gym.error.NameNotFound: Environment `NChain` doesn't exist.

Also NChain doesn't show up in the list
from gym import envs
print(envs.registry.all())

**System Info**
OS Win 10 (I know that it's not supported but the issue doesn't seem to be Windows-specific)
Python 3.9
gym's ver 0.22.0 (the latest at the moment of reporting this issue)
gym was installed via pip

Note:
I know it's a simple toy env but it's illustrative for some purposes, that would be great to keep it in the package

### Checklist

- [ checked ] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo 

Update:
Even the link  ([View source on GitHub](https://github.com/openai/gym/tree/master/gym/envs/toy_text/nchain.py)) provided on page (https://gym.openai.com/envs/NChain-v0/) about the env itself is broken and leads to 404 page

**Comment by jkterry1** [comment]
Hey, these were removed from Gym two releases ago. This and all the other removed classic control environments are available here: https://github.com/Rohan138/gym-legacy-toytext

**Comment by jkterry1** [comment]
Also that's the old documentation website too by the way. The current one, and the one that's linked throughout the repo, is: https://www.gymlibrary.ml/
