### ISSUE TITLE
[Bug Report] Classic Control environments (and possibly others) have different FPS

### ISSUE THREAD

**Issue by trigaten** [openai/gym#2636]
Different classic control environments have different values for their `video.frames_per_second` metadata.

See:

https://github.com/openai/gym/blob/bdde1ede6c52ea5fa95f54404fa3e4f4420d7afc/gym/envs/classic_control/acrobot.py#L132

https://github.com/openai/gym/blob/bdde1ede6c52ea5fa95f54404fa3e4f4420d7afc/gym/envs/classic_control/cartpole.py#L75

**Comment by jkterry1** [comment]
All of the FPS values need to be sanity checked at this point tbh

**Comment by jkterry1** [comment]
(this is now fixed on masteR)
