### ISSUE TITLE
[Bug Report] Bug title

### ISSUE THREAD

**Issue by cwf1005** [openai/gym#2641]
If you are submitting a bug report, please fill in the following details and use the tag [bug].

**Describe the bug**
the pygame dependency is missing in setup.py

**Code example**
pip install gym==0.22.0
import gym
env = gym.make("CartPole-v1")

**System Info**
pygame not found

**Additional context**

### Checklist

- [ ] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by kir0ul** [comment]
See https://github.com/openai/gym/issues/2634.

**Comment by jkterry1** [comment]
Like kir0ul said, you have to use `pip install gym[classic_control]`
