### ISSUE TITLE
[Bug Report] Classic control environments not displaying after update to 0.22.0

### ISSUE THREAD

**Issue by mtreca** [openai/gym#2655]
If you are submitting a bug report, please fill in the following details and use the tag [bug].

**Describe the bug**

Hi. After updating to version 0.22.0, I noticed that the environment windows of both 'CartPole' and 'LunarLander' did not display anymore. I saw that #2552 and #2599 introduced the use of Pygame for environment rendering. I tripled checked that Pygame and its dependencies were properly installed; they were. The example aliens game from Pygame also displays properly on my machine. Downgrading gym to version 0.21.0 using the old environment fixes my issue, but I would like to know if version 0.22.0 introduced an issue or if only my machine is at fault.

**Code example**

The minimal updated example provided in #2643 does not throw any error message, but no window is displayed. A Pygame icon appears in my bar.

**System Info**

Macbook Air M1 on Monterey 12.2.1
Python 3.9.10 installed through homebrew
All packages are installed through pip

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by andrewtanJS** [comment]
Hey, since Pygame icon appears in your bar, it might be opening the display behind your other windows. Could you rerun the environment and minimize all other windows to see if the Pygame display is hidden underneath them?

**Comment by mtreca** [comment]
Thank you for your replies.
@andrewtanJS This one of the first things I tried, but to no avail.
@jkterry1 Thank you for the suggestion. I tried bringin the app to front using [rcmd](https://lowtechguys.com/rcmd/) to no avail (the window is focused, but invisible). I also tried to center the window using [moom](https://manytricks.com/moom/), but window controls are unavailable when the Pygame window is "in focus" (even though it is still invisible).

**Comment by andrewtanJS** [comment]
Could you `pip freeze` to show the package versions?

**Comment by mtreca** [comment]
Here is the complete output of `pip freeze`. Thanks!

```
ale-py==0.7.4
appnope==0.1.2
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arviz==0.11.4
astroid==2.9.3
asttokens==2.0.5
attrs==21.4.0
backcall==0.2.0
black==22.1.0
bleach==4.1.0
box2d-py==2.3.8
cachetools==5.0.0
certifi==2021.10.8
cffi==1.15.0
cftime==1.5.2
charset-normalizer==2.0.12
click==8.0.4
cloudpickle==2.0.0
cycler==0.11.0
Cython==0.29.28
debugpy==1.5.1
decorator==5.1.1
defusedxml==0.7.1
dill==0.3.4
docopt==0.6.2
entrypoints==0.4
executing==0.8.3
fastprogress==1.0.2
ffmpeg==1.4
filelock==3.6.0
fonttools==4.29.1
glfw==2.5.1
graphviz==0.19.1
gym==0.22.0
gym-notices==0.0.4
h5py==3.6.0
idna==3.3
imageio==2.16.1
importlib-metadata==4.11.2
importlib-resources==5.4.0
ipykernel==6.9.1
ipython==8.1.0
ipython-genutils==0.2.0
ipywidgets==7.6.5
isort==5.10.1
jedi==0.18.1
Jinja2==3.0.3
jsonschema==4.4.0
jupyter-client==7.1.2
jupyter-core==4.9.2
jupyterlab-pygments==0.1.2
jupyterlab-widgets==1.0.2
kiwisolver==1.3.2
lazy-object-proxy==1.7.1
lockfile==0.12.2
lz4==4.0.0
MarkupSafe==2.1.0
matplotlib==3.5.1
matplotlib-inline==0.1.3
mccabe==0.6.1
mistune==2.0.2
mypy-extensions==0.4.3
nbclient==0.5.11
nbconvert==5.5.0
nbformat==5.1.3
nest-asyncio==1.5.4
netCDF4==1.5.8
notebook==6.4.8
numpy==1.22.2
opencv-python==4.5.5.62
packaging==21.3
pandas==1.4.1
pandocfilters==1.5.0
parso==0.8.3
pathspec==0.9.0
patsy==0.5.2
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.0.1
platformdirs==2.5.1
prometheus-client==0.13.1
prompt-toolkit==3.0.28
ptyprocess==0.7.0
pure-eval==0.2.2
pycparser==2.21
pygame==2.1.0
pyglet==1.5.21
Pygments==2.11.2
pylint==2.12.2
pymc3==3.11.4
PyOpenGL==3.1.6
pyparsing==3.0.7
pyrsistent==0.18.1
python-dateutil==2.8.2
pytz==2021.3
pyzmq==22.3.0
requests==2.27.1
res==0.1.7
scipy==1.8.0
seaborn==0.11.2
semver==2.13.0
Send2Trash==1.8.0
setuptools-scm==6.4.2
six==1.16.0
stack-data==0.2.0
terminado==0.13.1
testpath==0.6.0
Theano-PyMC==1.1.2
toml==0.10.2
tomli==2.0.1
torch==1.10.2
torchvision==0.11.3
torchviz==0.0.2
tornado==6.1
tqdm==4.63.0
traitlets==5.1.1
typing-extensions==3.10.0.2
urllib3==1.26.8
wcwidth==0.2.5
webencodings==0.5.1
widgetsnbextension==3.5.2
wrapt==1.13.3
xarray==0.21.1
zipp==3.7.0
```

**Comment by jkterry1** [comment]
Hey does this issue still persist on the newest version of gym (0.23.1)?

**Comment by mtreca** [comment]
@jkterry1 The update fixed the issue indeed. Thanks!
