### ISSUE TITLE
gym version 0.22.0 issue with pygame lib

### ISSUE THREAD

**Issue by abhi1ranjan** [openai/gym#2661]
error                                     Traceback (most recent call last)
/tmp/ipykernel_28914/1839657951.py in <module>
     13     action = agent.get_action(state)
     14     state, reward, done, info = env.step(action)
---> 15     env.render()
     16 
     17 env.close()

~/anaconda3/lib/python3.9/site-packages/gym/core.py in render(self, mode, **kwargs)
    284 
    285     def render(self, mode="human", **kwargs):
--> 286         return self.env.render(mode, **kwargs)
    287 
    288     def close(self):

~/anaconda3/lib/python3.9/site-packages/gym/core.py in render(self, mode, **kwargs)
    284 
    285     def render(self, mode="human", **kwargs):
--> 286         return self.env.render(mode, **kwargs)
    287 
    288     def close(self):

~/anaconda3/lib/python3.9/site-packages/gym/envs/classic_control/cartpole.py in render(self, mode)
    249 
    250         self.surf = pygame.transform.flip(self.surf, False, True)
--> 251         self.screen.blit(self.surf, (0, 0))
    252         if mode == "human":
    253             pygame.display.flip()

**error: display Surface quit**

**Comment by andrewtanJS** [comment]
Hey, could you provide a reproducible example of your code which throws this error?

**Comment by jkterry1** [comment]
Hey, I'm going to close this for now, please let us know if you need any additional help
