### ISSUE TITLE
[Question] Support for MuJoCo 2.1+

### ISSUE THREAD

**Issue by Borzyszkowski** [openai/gym#2664]
Hello!

I would like to ask if there are plans to support MuJoCo v.2.1+ and when could we expect the release? 
The new versions are already covered by mujoco-py after the library has been acquired by DeepMind.

Thank you,
Bartek

**Comment by jkterry1** [comment]
https://github.com/openai/gym/pull/2595 should give you this right?

**Comment by jkterry1** [comment]
hey, I'm going to close this, lmk if I was wrong

**Comment by Borzyszkowski** [comment]
I'm not sure this answers the question. Does it mean that after merging this PR we will be able to run OpenAI Gym with MuJoCo v.2.1? For now it is required to downgrade to MuJoCo v.1.5

**Comment by jkterry1** [comment]
It's my understanding that that's the case, yes

**Comment by Borzyszkowski** [comment]
Thank you for the answer. I will be waiting for the merge
