### ISSUE TITLE
[sys.stderr.write(f"ERROR: {exc}")]  Problems installing Docker Image [bug]

### ISSUE THREAD

**Issue by KingDoood** [openai/gym#2667]
[bug]

Hello,
I am attempting to build Docker image into Open AI Universe, but I keep getting an error that says "SyntaxError: invalid syntax." After some time on the internet, I was able to surmise that there was something wrong with the pip and attempted to follow other suggestions on solving it like the "Index of /pip/", removing and reinstalling pip, updating the python version, and all has come to no avail. I would appreciate the help if possible. (Note: I understand this is technically for "Gym" and not "Universe," however, the Universe was closed and imo this was the closest repository to my issue.

**Code**
(universe) upshec@paters-lab01:~/universe$ docker build -t universe .
Sending build context to Docker daemon   4.38MB
Step 1/13 : FROM ubuntu:16.04
 ---> b6f507652425
Step 2/13 : RUN apt-get update     && apt-get install -y libav-tools     python3-numpy     python3-scipy     python3-setuptools     python3-pip     libpq-dev     libjpeg-dev     curl     cmake     swig     python3-opengl     libboost-all-dev     libsdl2-dev     wget     unzip     git     golang     net-tools     iptables     libvncserver-dev     software-properties-common     && apt-get clean     && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 08b3dea87f8f
Step 3/13 : RUN ln -sf /usr/bin/pip3 /usr/local/bin/pip     && ln -sf /usr/bin/python3 /usr/local/bin/python     && pip install -U pip
 ---> Using cache
 ---> 247a067c513b
Step 4/13 : RUN pip install gym[all]
 ---> Running in 092cbd9e0b22
Traceback (most recent call last):
  File "/usr/local/bin/pip", line 7, in <module>
    from pip._internal.cli.main import main
  File "/usr/local/lib/python3.5/dist-packages/pip/_internal/cli/main.py", line 57
    sys.stderr.write(f"ERROR: {exc}")
                                                     ^
SyntaxError: invalid syntax
The command '/bin/sh -c pip install gym[all]' returned a non-zero code: 1

I downloaded both the Gym and Universe through the github clone method.
cd ~                                                                                                  cd ~
git clone https://github.com/openai/universe.git                               git clone https://github.com/openai/gym.git
cd universe                                                                                       cd gym
pip install -e .                                                                                    pip install -e '.[all]'

 My Ubuntu version is Ubuntu 20.04.4 
My Python version is 3.7.0

**Comment by jkterry1** [comment]
Hi,

OpenAI's universe library id a different one from gym and hasn't been supported for years.
