### ISSUE TITLE
[Question] KeyError: 'ale.lives' when training on BreakoutDeterministic-v4 Environment 

### ISSUE THREAD

**Issue by ayush714** [openai/gym#2669]
### Question

When I am training a model which u can find the snippet of the code [here](https://gist.github.com/ayush714/5d6130581b0a46de4c84be3b50b31810). It gives me the below error.

```KeyError: 'ale.lives'``` 

![image](https://user-images.githubusercontent.com/81796368/156881459-a8b09cb9-f752-4026-91e4-fd2dbd933373.png)
This is coming at this line. 

So How to fix it?

**Comment by pseudo-rnd-thoughts** [comment]
Your gist is not self-complete as it is missing a lot of the code required to run 
I think the problem is in the game_wrapper however this variable is never defined in the code

In addition, the gym atari preprocessing wrapper includes a parameter for terminate on life lost so I recommend using that

**Comment by ayush714** [comment]
Hi @pseudo-rnd-thoughts The whole can be found [here](https://github.com/zenml-io/zenfiles/blob/main/Powerful%20DQN/train_dqn.py). 

Let me know your thoughts on this.

**Comment by pseudo-rnd-thoughts** [comment]
You need to change 'ale.lives' to 'lives' on lines 128 and 132

```
import gym

env = gym.make('Breakout-v4')
obs = env.reset()
obs, rewards, done, info = env.step(0)

print(info)  # {'lives': 5}
```

I also noticed that there are several issues with your Atari wrapper (frame stack, skipping, no-op starts and frame processing, all look different to the normal specification that I'm aware of) and recommend you look at the gym implementation of it 
https://github.com/openai/gym/blob/master/gym/wrappers/atari_preprocessing.py
