### ISSUE TITLE
[Question] Where is `gym.wrappers.Monitor` in `gym==0.23`?

### ISSUE THREAD

**Issue by unsignedrant** [openai/gym#2674]
### Question

So, it works perfectly fine in `0.22` but not in `0.23` and I don't see any deprecation warning in earlier versions, any suggestions/alternatives?

```
AttributeError: module 'gym.wrappers' has no attribute 'Monitor'
```

**Comment by balisujohn** [comment]
It was removed. I think the intended replacements are the RecordEpisodeStatistics wrapper and the RecordVideo wrapper.

**Comment by jkterry1** [comment]
Before being removed, importing it also raised a depreciation warning.

**Comment by unsignedrant** [comment]
@jkterry1

```
(gymenv) unsignedrant@MacBook-Pro Desktop % pip install gym==0.22
Collecting gym==0.22
  Using cached gym-0.22.0-py3-none-any.whl
Collecting numpy>=1.18.0
  Using cached numpy-1.22.3-cp310-cp310-macosx_10_14_x86_64.whl (17.6 MB)
Collecting gym-notices>=0.0.4
  Using cached gym_notices-0.0.5-py3-none-any.whl (2.7 kB)
Collecting cloudpickle>=1.2.0
  Using cached cloudpickle-2.0.0-py3-none-any.whl (25 kB)
Installing collected packages: gym-notices, numpy, cloudpickle, gym
Successfully installed cloudpickle-2.0.0 gym-0.22.0 gym-notices-0.0.5 numpy-1.22.3
(gymenv) unsignedrant@MacBook-Pro Desktop % python
Python 3.10.2 (main, Feb  2 2022, 06:19:27) [Clang 13.0.0 (clang-1300.0.29.3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from gym.wrappers import Monitor

>>> 
```
No deprecation warning is given or alternatives suggested. So, what should I use instead?

**Comment by vwxyzjn** [comment]
Hey, @unsignedrant we are deprecating `Monitor` in favor of `RecordEpisodeStatistics and `RecordVideo` wrappers. Could you give them a try? Note the `RecordVideo` wrapper is temporarily broken for third party envs (see #2678)

**Comment by vwxyzjn** [comment]
@unsignedrant thanks for giving it a try. Could you try `RecordVideo` with `CartPole-v1`? `RecordVideo` does not work with Pong at the moment because of #2678.

**Comment by jkterry1** [comment]
Hey, the fix is merged so I'm going to close this. We'll cut another release fairly soon.

**Comment by chinggg** [comment]
`RecordEpisodeStatistics` does not have `get_episode_lengths` method though it also has attribute `episode_lengths`, is it intended?
