### ISSUE TITLE
[Bug Report] `gym.wrappers.RecordVideo` no longer render videos for Atari environments.

### ISSUE THREAD

**Issue by vwxyzjn** [openai/gym#2675]
`gym.wrappers.RecordVideo` no longer render videos for Atari environments. Try running the following script with `gym==0.23.0` and  `gym==0.22.0`

```python
import gym

env = gym.make("BreakoutNoFrameskip-v4")
env = gym.wrappers.RecordEpisodeStatistics(env)
env = gym.wrappers.RecordVideo(env, f"videos/{gym.__version__}")

env.reset()
for _ in range(2000):
    _, _, done, _ = env.step(env.action_space.sample())
    if done:
        env.reset()
```

the `videos/0.22.0` contains videos but not the `videos/0.23.0`:
![image](https://user-images.githubusercontent.com/5555347/157367532-5bf29b22-8a2c-4b14-9230-35bacfb9db18.png)

**Comment by vwxyzjn** [comment]
I think it's related to https://github.com/openai/gym/commit/35b78ac0ab13a6f91f7ebadad510651f346a6922#diff-90696e71aa0337431a4337e5383a2e082bc301b183de550ae1c088d3aa22a8da: the `render.modes` in the atari envs also needed to be changed to `render_modes`.

**Comment by vwxyzjn** [comment]
I can confirm this works after https://github.com/mgbellemare/Arcade-Learning-Environment/pull/448

![image](https://user-images.githubusercontent.com/5555347/157369057-a0e35e14-c217-483b-a921-1f6662ded7ba.png)

This is also likely a breaking change to existing environments such as pybullet envs. @jkterry1 Maybe it's worth submitting a PR for `RecordVideo` wrapper to be backward-compatible (supporting both `render.modes` and `render_modes`) for the next 6 months?

**Comment by jkterry1** [comment]
Closing due to merged PR
