### ISSUE TITLE
[Bug Report] Can't close rendered window from Jupyter notebook

### ISSUE THREAD

**Issue by Takher** [openai/gym#2677]
When running CartPole-v1 using the starter code from https://gym.openai.com/ within a Jupyter notebook a window opens up and runs the CartPole game but then doesn't close. I have to manually "Force quit" the window, and this leads to the kernel crashing.

**Code example (taken from directly from  https://gym.openai.com/)**
```python
import gym
env = gym.make("CartPole-v1")
observation = env.reset()
for _ in range(1000):
  env.render()
  action = env.action_space.sample() # your agent here (this takes random actions)
  observation, reward, done, info = env.step(action)

  if done:
    observation = env.reset()
env.close()
```

**System Info**
 * Installed gym==0.21.0 using conda 4.11.0 using `conda install 'gym[all]'`
 * Running macOS Monterey 12.1 on an arm-based MacBook Pro
 * Python 3.9.10

**Comment by jkterry1** [comment]
#2684 should fix this

**Comment by modestasgrz** [comment]
Still freezes on Mac (M1 Pro) using Jupyter Notebook, and then Kernel dies

**Comment by pseudo-rnd-thoughts** [comment]
@modestasgrz  Are you using the same code as above? I suspect this might be a pygame issue rather than Gymnasium

**Comment by Faugermire** [comment]
I am running into this issue as well. The cartpole env will run through its episodes, but will then lock up when `env.close()` is called. I have to force quit the python app, which then causes the kernel to crash. 

I have a Macbook M2 Max, using Jupyter Notebook.

Here is the code:

```
episodes = 5

for episode in range(episodes):
    state = env.reset()
    done = False
    score = 0
    
    while not done:
        env.render()
        action = env.action_space.sample()
        n_state, reward, done, info = env.step(action)
        score += reward
    print(f'Episode: {episode}, Score: {score}')

env.close()
```

Here are my imports:

```
import os
import gym
from stable_baselines3 import PPO
```

Here are my installs:

```
%conda install -c conda-forge stable-baselines3
%conda install -c conda-forge gym
%conda install -c conda-forge gym-classic_control
```

I am using Anaconda, and am running jupyter from inside a conda env. I have tried using different envs, however, I get the same results.

Here is the output of `conda info`:

```
active environment : rein-conda-venv
active env location : /Users/bruh/opt/anaconda3/envs/rein-conda-venv
shell level : 1
user config file : /Users/bruh/.condarc
populated config files : /Users/bruh/.condarc
conda version : 23.1.0
conda-build version : 3.22.0
python version : 3.9.13.final.0
virtual packages : __archspec=1=x86_64
                              __osx=10.16=0
                              __unix=0=0
base environment : /Users/bruh/opt/anaconda3  (writable)
conda av data dir : /Users/bruh/opt/anaconda3/etc/conda
conda av metadata url : None
channel URLs : https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
package cache : /Users/bruh/opt/anaconda3/pkgs
                             /Users/bruh/.conda/pkgs
envs directories : /Users/bruh/opt/anaconda3/envs
                              /Users/bruh/.conda/envs
platform : osx-64
user-agent : conda/23.1.0 requests/2.28.1 CPython/3.9.13 Darwin/22.3.0 OSX/10.16
UID:GID : 501:20
netrc file : None
offline mode : False
```

Not sure if any of this helps. Let me know if you need more information.

**Comment by MesaJonathan** [comment]
Was this ever figured out because I am currently running into the same issue?
