### ISSUE TITLE
[Proposal] Add latest version of spaces/discrete.py to release

### ISSUE THREAD

**Issue by alfred100p** [openai/gym#2681]
### Proposal 

Add latest version of discrete.py to release. This will allow use of the start parameter during initialization.

### Motivation

This will allow use of the start parameter during initialization allowing actions to have a different start value than 0.

### Pitch

Add latest version of discrete.py to release. 

### Alternatives

No alternatives.

### Additional context

N.A.

### Checklist

- [ X] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by RedTachyon** [comment]
What?

**Comment by alfred100p** [comment]
> What?

The latest release doesn't have the start parameter present in the repo

**Comment by jkterry1** [comment]
I'm very confused. A new 0.23.1 release of Gym will go out in less than a week, will that fix this problem?

**Comment by alfred100p** [comment]
> I'm very confused. A new 0.23.1 release of Gym will go out in less than a week, will that fix this problem?

I don't think so. It has been present in the repo for a while but hasn't been in any of the releases.

**Comment by RedTachyon** [comment]
Can you elaborate anything more about this? Like why are you saying this is not present in the release, what do you think is necessary to fix it etc?

I just did a quick test with colab:
```python
!pip install gym==0.23
from gym.spaces import Discrete
space = Discrete(5, start=10)
space.sample()
```

and it works exactly how intended. Also, looking at the [code](https://github.com/openai/gym/blob/2dddaf722acccfd0412d745890c40dcd972586d5/gym/spaces/discrete.py#L20) of the last commit of 0.23, the `start` parameter is very much present there.

Are you sure you don't have some cached files after updating gym from an older version?

**Comment by alfred100p** [comment]
> Can you elaborate anything more about this? Like why are you saying this is not present in the release, what do you think is necessary to fix it etc?
> 
> 
> 
> I just did a quick test with colab:
> 
> ```python
> 
> !pip install gym==0.23
> 
> from gym.spaces import Discrete
> 
> space = Discrete(5, start=10)
> 
> space.sample()
> 
> ```
> 
> 
> 
> and it works exactly how intended. Also, looking at the [code](https://github.com/openai/gym/blob/2dddaf722acccfd0412d745890c40dcd972586d5/gym/spaces/discrete.py#L20) of the last commit of 0.23, the `start` parameter is very much present there.
> 
> 
> 
> Are you sure you don't have some cached files after updating gym from an older version?

It may be a cached file. Sorry for the trouble.
