### ISSUE TITLE
py.typed not bundled in release

### ISSUE THREAD

**Issue by micimize** [openai/gym#2682]
The latest pypi package [gym==0.23.0](https://pypi.org/project/gym/0.23.0/) does not include `py.typed`, resulting in failed `mypy` checks.

Reproduce by `pip install gym` and noting the missing file or downloading the zip from pypi (zip on GH contains the file).

**Comment by RedTachyon** [comment]
We use `pyright` for type checking. Can you elaborate on what `py.typed` should contain, and what benefits there would be to including it?

**Comment by micimize** [comment]
@RedTachyon you already have it in [gym](https://github.com/openai/gym/tree/master/gym), it just isn't bundled properly in the release. It is an empty file python uses to tell type checkers "yes this is type checked" – `pyright` uses it as well

opened #2683 which may be all that's necessary
