### ISSUE TITLE
Remove backwards compatibility with Gym 1.0

### ISSUE THREAD

**Issue by younik** [openai/gym#2699]
WIth the release of Gym 1.0, we should:

- [ ] Remove `.render()` method. Now it is not possible anymore to change render mode after initialization.
- [ ] Clean code. Unmutable render_mode allows to remove a lot of boilerplate (e.g. moving pygame attribute initialization in `__init__`, `_render` can append to `render_list` instead of return). See [this](https://github.com/younik/gym/tree/cffacd74100824885ed4308ade573e7aedf7d39d).

**Comment by jkterry1** [comment]
Wasn't there something else pertaining to how arguments are being passed around that we can remove?

**Comment by younik** [comment]
> Wasn't there something else pertaining to how arguments are being passed around that we can remove?

Are you referring to the workaround to make `.render()` still supported before Gym 1.0? I am working on it right now, so if there will be something special to do also on that I will add

**Comment by araffin** [comment]
`close()` method is not used for rendering only, it is also used to release resources (for instance close processes).

https://github.com/openai/gym/blob/64a0eb01935f4643388f8dc61bc2e9b4af023fdc/gym/core.py#L149-L150

**Comment by jkterry1** [comment]
Right, we can't remove close for this reason, we just need to remove functionally when it specifically pertains to render.

**Comment by RedTachyon** [comment]
Yea, `close()` definitely isn't going away. Do we even need to change its behavior around rendering either? I think it should just depend on the environment, and if an environment maintains some display like pygame, or whatever else in a separate process, then that should absolutely be also cleaned up in `close()`

**Comment by younik** [comment]
I close this since the last changes in #2671.
