### ISSUE TITLE
Support for SMDP

### ISSUE THREAD

**Issue by osm3000** [openai/gym#27]
Hi,
Does this toolkit support semi-MDP or MDP reinforcement learning only?
I am currently experimenting with the Options framework, and I am building everything from scratch. I am trying to find a quick and well tested solution for this.
Cheers,
Omar

**Comment by joschu** [comment]
Yes, semi-MDPs are only different than MDPs when you consider the discount factor, but OpenAI gym doesn't specify anything about discount factors.
