### ISSUE TITLE
Render windows not closing in some environments with pygame

### ISSUE THREAD

**Issue by Maritimo** [openai/gym#2702]
## Bug description:
'toy_text/Blackjack-v1' and 'toy_text/FrozenLake' do not close the render window when calling env.close()

## Possible solution:
Add a `close(self)` method to the environments:
```
def close(self):
     if self.screen is not None:`
         pygame.display.quit()
         pygame.quit()
```

**Comment by pseudo-rnd-thoughts** [comment]
I wasn't able to replicate this issue with the following code
```
import gym

env = gym.make('Blackjack-v1')
env.reset()
env.render()
env.step(0)
env.render()

env = gym.make('FrozenLake-v1')
env.reset()
env.render()
env.step(0)
env.render()
```

For me, the windows close fine even without .close()
I know, the solution you are talking about is implemented by box2d/car_racing.py so we could replicate that for these two environments 

Could you provide some code that causes an issue on your system? I might be OS dependant, Im on ubuntu

**Comment by Maritimo** [comment]
**Thanks for your quick response.**

This is my code:
```
import gym
env = gym.make('Blackjack-v1')
state=env.reset()
for _ in range(20):
    env.render()
    next_state, reward, done, info = env.step(env.action_space.sample())
    if done: env.reset()
env.close()
```
uname -a
> Linux mgq 5.4.0-104-generic #118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 20.04.4 LTS
> Release:	20.04
> Codename:	focal

python --version
> Python 3.8.10

pip show gym
> Name: gym
> Version: 0.23.1
> Summary: Gym: A universal API for reinforcement learning environments
> Home-page: https://www.gymlibrary.ml/
> Author: Gym Community
> Author-email: jkterry@umd.edu
> License: MIT
> Location: /home/mario/.local/lib/python3.8/site-packages
> Requires: cloudpickle, gym-notices, importlib-metadata, numpy
> Required-by: gym-aima, gym-bandits, gym-jcr, gym-robotics, gym-walk, spinup

pip show pygame
> Name: pygame
> Version: 2.1.0
> Summary: Python Game Development
> Home-page: https://www.pygame.org
> Author: A community project.
> Author-email: pygame@pygame.org
> License: LGPL
> Location: /home/mario/.local/lib/python3.8/site-packages
> Requires: 
> Required-by:

**Comment by pseudo-rnd-thoughts** [comment]
Thanks, this seems like a juypter notebook only issue but I found that your fixed works
I will create a PR soon with it and look for anything environments where this is also an issue
