### ISSUE TITLE
Space box scope issues

### ISSUE THREAD

**Issue by zhengnx0906** [openai/gym#2715]
I set"self.action_space = spaces.Box(low=np.zeros(self.n_actions), high=np.array([0.01,0.01,0.01,0.001,0.001,0.001,0.001,0.001,0.001,0.0001,0.0001,0.0001,0.8,0.8,0.8,0.8,0.8,0.8]),shape=(self.n_actions, ),dtype='float64')"
Finally, I print(action).There is something wrong with it，as shown below.
'''
actions: [-0.00118571 -0.00160194  0.0019625   0.00791211  0.00863184 -0.00543408
 -0.0030086  -0.00890199 -0.00843143  0.00064863 -0.00920339  0.01
  0.00334563 -0.00949795  0.00387605  0.00723022  0.00999997 -0.01      ]
actions: [-0.00789045  0.00017375 -0.00691849 -0.00469118 -0.0020665   0.00065899
  0.00976756  0.0036408  -0.00295245  0.00015504  0.00942443 -0.00999937
  0.00582671 -0.00696542 -0.00987869 -0.00740871  0.00994805 -0.00313018]
actions: [ 0.00365427  0.00721091 -0.00934831 -0.0039444  -0.00475496  0.00262727
 -0.00848177  0.00989775  0.0041684  -0.00511937 -0.00713703 -0.00999997
 -0.00219222 -0.00620296 -0.00071861 -0.00436106 -0.01        0.00998589]
actions: [-0.00758547 -0.00905749  0.00876167  0.00734259  0.00264309 -0.00862467
  0.00022848 -0.00921106 -0.00361994 -0.00663873  0.00662107  0.00884177
 -0.00957858 -0.00650989  0.00006509 -0.00873047  0.01        0.00925519]
'''
I found that the value scope is right, but the symbol is wrong.

**Comment by jkterry1** [comment]
@pseudo-rnd-thoughts could you please take a look at this when you get a chance?

**Comment by RedTachyon** [comment]
I can't seem to replicate this using the last release or current `master`. Are you sure the error isn't in some other part of your code?

**Comment by zhengnx0906** [comment]
You are right,there is a problem in my code. I just use the "action_space.high" to set my action space.Thank you.

**Comment by pseudo-rnd-thoughts** [comment]
If this is solved, @zhengnx0906 could you close the issue, thanks
