### ISSUE TITLE
Code sample on docs homepage is buggy

### ISSUE THREAD

**Issue by cool-RR** [openai/gym#2716]
I'm using Gym for the first time. I tried to run the code sample on https://www.gymlibrary.ml/:

```
import gym
env = gym.make("LunarLander-v2")
observation, info = env.reset(seed=42, return_info=True)
for _ in range(1000):
    env.render()
    action = policy(observation)
    observation, reward, done, info = env.step(action)

    if done:
        observation, info = env.reset(return_info=True)
env.close()
```

It fails because `policy` isn't defined. This is embarrassing because it's the very first code sample that a new user would see.

Error message: `name 'policy' is not defined`

**Comment by jkterry1** [comment]
This the policy function is psuedo-code for the policy function you'd have in learning code, it's not something that's natively included in Gym. In not sure how we could make this more explicit?

**Comment by cool-RR** [comment]
You could make it explicit by including a line saying "this is pseudo-code that doesn't really run". But it's silly. It's especially silly that it has an `import` statement in it, which is really not something you see in pseudo-code.

The best thing would be to have a piece of code that actually runs. The policy doesn't have to actually do RL, it can choose an action in random. It doesn't have to be good, it just needs to be an "hello world".

**Comment by jkterry1** [comment]
I mean it's all real code except the policy, which at least to me seems to clearly be referencing user provided code...? Adding extra logic to randomly sample actions in a basic API demostration doesn't seem like the best idea either

**Comment by jkterry1** [comment]
@RedTachyon do you have any opinions on this?

**Comment by cool-RR** [comment]
The question is how newbie-friendly you want to be. I like to err on the side of newbie-friendliness, but your interests may be different. If you do want to newbie-friendly, you should consider that the person reading your documentation doesn't know nearly as much as you do. You've seen this loop a million times. They may be seeing it for the first time. 

If you're looking for ways to make it explicit that this code doesn't run, you could maybe add something like this at the top:

```
def policy(observation):
    # Your RL algorithm goes here.
```

Then it's clearer what's going on, and also the code won't compile which would send stronger signals that it's pseudo-code. Also you could drop the `import`.

**Comment by RedTachyon** [comment]
I'm mostly indifferent to this tbh, but it's good to keep it newbie-friendly, since we can assume that more advanced users will understand it either way. 

How about adding this?
```python
import numpy

def policy(obs):
    # Your RL algorithm goes here
    # The default code choosees a random action
    return np.random.default_rng().integers(4)
```

There's a commentary "hey, put your stuff here", and also the code would actually run.


A fancier option would be hard-coding a policy that actually does something nice. It might be tricky for LunarLander, but I'm pretty sure there are good linear policies for CartPole
