### ISSUE TITLE
[Question] OSError: [WinError 127], after 'import gym'

### ISSUE THREAD

**Issue by whliu90** [openai/gym#2720]
### Question

About my installation:
`>> git clone https://github.com/openai/gym.git`
then changed my directory and installed gym:
`>> pip install -e .[all]`
It seems everything was OK.

However, it gives me WinError 127, when trying to import gym.
`>>> import gym`

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\users\whliu\desktop\gym\gym\__init__.py", line 12, in <module>
    from gym.envs import make, spec, register
  File "c:\users\whliu\desktop\gym\gym\envs\__init__.py", line 10, in <module>
    _load_env_plugins()
  File "c:\users\whliu\desktop\gym\gym\envs\registration.py", line 725, in load_
env_plugins
    fn = plugin.load()
  File "C:\Users\whliu\.conda\envs\rl\lib\site-packages\importlib_metadata\__ini
t__.py", line 203, in load
    module = import_module(match.group('module'))
  File "C:\Users\whliu\.conda\envs\rl\lib\importlib\__init__.py", line 127, in i
mport_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Users\whliu\.conda\envs\rl\lib\site-packages\ale_py\__init__.py", lin
e 26, in <module>
    os.add_dll_directory(packagedir)
  File "C:\Users\whliu\.conda\envs\rl\lib\os.py", line 1109, in add_dll_director
y
    cookie = nt._add_dll_directory(path)
OSError: [WinError 127] 找不到指定的程序。: 'C:\\Users\\whliu\\.conda\\envs\\rl\
\lib\\site-packages\\ale_py'

- python 3.8.8
- mujoco 1.50.1
- win 10

**Comment by jkterry1** [comment]
@pseudo-rnd-thoughts would you mind taking a quick look at this?

**Comment by pseudo-rnd-thoughts** [comment]
Im not able to replicate your issue as mujoco is deprecated on windows for the latest branch
However, looking at the error then it appears to be ale-py

But I think that the issue if with using editable in installing it
https://github.com/openai/gym/issues/2648#issuecomment-1054962800
See this issue that explains the problem with editable for ale-py

Does `pip install gym[atari]` fix it?

**Comment by whliu90** [comment]
> Im not able to replicate your issue as mujoco is deprecated on windows for the latest branch However, looking at the error then it appears to be ale-py
> 
> But I think that the issue if with using editable in installing it [#2648 (comment)](https://github.com/openai/gym/issues/2648#issuecomment-1054962800) See this issue that explains the problem with editable for ale-py
> 
> Does `pip install gym[atari]` fix it?

Thanks for your advice. I just fix it by running `pip uninstall ale-py`, then everything is OK right now. I'm not sure if this would brings any bad influcence.

**Comment by pseudo-rnd-thoughts** [comment]
No worries, is this fixed? If so, could you close it

**Comment by whliu90** [comment]
> 
Yes, it is fixed. Thanks again for your help.
