### ISSUE TITLE
[Proposal] gym.utils.play has no tests 

### ISSUE THREAD

**Issue by pseudo-rnd-thoughts** [openai/gym#2729]
I ran coverage over our pytest to see what percentage of the code base is currently being tested
It seems that gym.utils.play is not being tested at all currently (every other files is from my check)
Is it possible to run tests on this as the tests are normally headless I thought?

**Comment by balisujohn** [comment]
Just a small thought is that even for headless systems you can create dummy x servers(assuming correct permissions) to serve as a sink for graphical output so it might still be possible to test headless.

**Comment by gianlucadecola** [comment]
I'm currently working on that :)
