### ISSUE TITLE
How to combine Panda3D and Openai Gym？

### ISSUE THREAD

**Issue by dooliu** [openai/gym#2730]
I want to develop a 3D environment based on gym. Panda3D is great for developing 3D games.
After a few days of study, I developed a small game. However, I tried to combine with Gym but failed.
Panda3d rendering graphics need call the function app.run(), but after that, the game's control handle is not available. I can't execue other code after call run().
Anyone konw how to do?

**Comment by younik** [comment]
Hello @dooliu, 
Can you maybe share an example code?
I am not familiar with Panda3D; the engine is in charge of the interaction with the user, isn't it? 
How do you plan to have a software agent interacting with it?

**Comment by dooliu** [comment]
Thanks，panda3D is a development kit for developing 3D environments.
I've found a way to combine panda3D and Gym。
If you interest with it,you can look this page:
https://docs.panda3d.org/1.10/python/introduction/index

panda3D is a good package for develop 3D envirment.
