### ISSUE TITLE
[Proposal] Simplify `gym.make` implementation

### ISSUE THREAD

**Issue by RedTachyon** [openai/gym#2738]
### Proposal 

Rewrite the entire `registration.py` file so that the top-level `make` function actually does its thing, instead of calling `EnvRegistry` which calls `EnvSpec` through an `EnvSpecTree`

### Motivation

`gym.make` is crucial to the practical use of Gym, but its implementation is pretty chaotic and overcomplicated, which makes any modifications difficult, and bugs hard to spot. When you call it, it instantly just calls `registry.make` on a global object, which does some of the logic, and then `spec.make` which has the rest of the logic. It feels object-oriented to a fault.

### Implementation details

1. The top-level function `make` should perform most/all of the environment creation logic, with parts delegated to separate functions
2. `EnvSpec` becomes **just** a dataclass, without extra logic
3. I don't think `EnvSpecTree` is actually necessary, since we're not really working with multi-layer trees here. Imo a dictionary is sufficient to represent all envs, and the extra layers can just be flattened - and that's perfectly fine. I don't see any actual use cases for the nested structure other than maybe asymptotically slightly faster lookups of *incorrect* env names
4. `EnvRegistry` gets turned into a dictionary (the same one as mentioned above), with no logic of its own
5. `register` gets changed similarly to `make`, and it essentially just adds an entry to the global registry (dict)

Pinging in particular @JesseFarebro since you added EnvSpecTree in #2481 and the whole plugin system.

### Rough edges

The plugin system is a total undocumented mystery to me. I have no idea if it will work if I just copy-paste it. 

Also, I think backwards-compatibility of the undocumented low-level implementation details shouldn't be a priority. This reminds me why I'm not a fan of python and always exporting everything, but I *hope* nobody's accessing the `registry` directly, for example. It might be best to keep this for 1.0 release, not sure though.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by JesseFarebro** [comment]
This is long overdue. At the time of #2481 I didn't know how much of an appetite there was for breaking changes as there's quite a bit of code that uses the environment registry object. If you have any questions about how the entry-point plugin system works just let me know.
