### ISSUE TITLE
[Question] Changing mujoco xml path dynamically

### ISSUE THREAD

**Issue by wj210** [openai/gym#2741]
Is there any way i can dynamically change the mujoco model i would like to load? Example if i were to make 5 different xml files, could i somehow use the make function to load different xml files without having to register 5 different classses?

**Comment by pseudo-rnd-thoughts** [comment]
To create an environment, you don't need to use `gym.make`, this is more a shortcut for wrappers and everything else. You can if you want just initialise the environment passing a file path to mujoco. Personally, I don't have an experience with doing that, but I don't know a reason why you can't do that. You will have to recreate the environment each time for each file path but it could be a shortcut
