### ISSUE TITLE
How do I solve this 'FrozenLakeEnv' object has no attribute 'lastaction'

### ISSUE THREAD

**Issue by Anna4142** [openai/gym#2751]
### Question

If you're a beginner and have basic questions, please ask on [r/reinforcementlearning](https://www.reddit.com/r/reinforcementlearning/) or in the [RL Discord](https://discord.com/invite/xhfNqQv) (if you're new please use the beginners channel). Basic questions that are not bugs or feature requests will be closed without reply, because GitHub issues are not an appropriate venue for these.

Advanced/nontrivial questions, especially in areas where documentation is lacking, are very much welcome.

**Comment by pseudo-rnd-thoughts** [comment]
Could you provide some example code? 
Are you sure that you have reset the environment?

Looking at the code, I'm guessing that you have tried rendering without resetting

**Comment by jkterry1** [comment]
@younik if this is a reproducible bug, you're the one who's been working with this code

**Comment by pseudo-rnd-thoughts** [comment]
Im fairly sure their code is 
```
import gym

env = gym.make('FrozenLake-v1')
env.render()

> AttributeError: 'FrozenLakeEnv' object has no attribute 'lastaction'
```
We can add PR to add a check for render that reset has been called before render or move the variables into the constructor

**Comment by younik** [comment]
> @younik if this is a reproducible bug, you're the one who's been working with this code

Yes, it is reproducible as @pseudo-rnd-thoughts showed. This is a problem in all environments: if you don't call `reset()` before `render()`, you will get a non-explanatory error.

@jkterry1 should be possible to drop the constraint of calling reset after the creation? It is common to all environments, so it could be done internally, isn't it?

**Comment by jkterry1** [comment]
I spoke to younik about this on a call, we have to have reset first
