### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by haoshuiwuxiang** [openai/gym#2753]
### Question
![image](https://user-images.githubusercontent.com/40374436/163542329-bb655598-ee82-44c4-b852-f8f0e69a9b50.png)
when i run :env = gym.make("CartPole-v1")
report error: Segmentation fault (core dumped)
environment: 
ubuntu16.04
python3.8

**Comment by pseudo-rnd-thoughts** [comment]
Have you downloaded the master and `pip install .`? Or have you just downloaded `pip install gym`? 
There is a known issue in the CI currently where gym is seg faulting but that seems to be different from what is happening here

Are you able to do anything else with gym?
It would be great is you could locate what is causing the issue, i.e. pygame, cartpole,

**Comment by haoshuiwuxiang** [comment]
Thanks for your reply. I used PIP install gym to install gym
I used anaconda. I tried again and still reported an error:


从 Windows 版邮件发送

发件人: Mark Towers
发送时间: 2022年4月15日 18:22
收件人: openai/gym
抄送: haoshuiwuxiang; Author
主题: Re: [openai/gym] Segmentation fault (core dumped) (Issue #2753)

Have you downloaded the master and pip install .? Or have you just downloaded pip install gym?
There is a known issue in the CI currently where gym is seg faulting but that seems to be different from what is happening here
Are you able to do anything else with gym?
It would be great is you could locate what is causing the issue, i.e. pygame, cartpole,

**Comment by pseudo-rnd-thoughts** [comment]
Could you run 
```
from gym.envs.classic_control import CartPoleEnv

env = CartPoleEnv()
```

If this passes, could you try to make other environments, i.e. lunar lander, bipedal walker

**Comment by haoshuiwuxiang** [comment]
> Could you run
> 
> ```
> from gym.envs.classic_control import CartPoleEnv
> 
> env = CartPoleEnv()
> ```
> 
> If this passes, could you try to make other environments, i.e. lunar lander, bipedal walker

![image](https://user-images.githubusercontent.com/40374436/163587118-cb5b42d0-0d93-45ff-a009-5eb20a542ce2.png)
it report error

**Comment by RedTachyon** [comment]
@haoshuiwuxiang Do you have `pygame` installed and functional? Can you do `import pygame` and `from pygame import gfxdraw`? I suspect one of this lines might be causing the crash.

**Comment by haoshuiwuxiang** [comment]
Thank you very much for your reply. Is it possible that the incompatibility is caused by the installation of ROS? I just changed a computer without ROS to run gym normally.

从 Windows 版邮件发送

发件人: Ariel Kwiatkowski
发送时间: 2022年4月16日 0:42
收件人: openai/gym
抄送: haoshuiwuxiang; Mention
主题: Re: [openai/gym] Segmentation fault (core dumped) (Issue #2753)

@haoshuiwuxiang Do you have pygame installed and functional? Can you do import pygame and from pygame import gfxdraw? I suspect one of this lines might be causing the crash.

**Comment by pseudo-rnd-thoughts** [comment]
ROS shouldn't affect gym at all to my knowledge. 
Did you try what @RedTachyon suggested above to trying to `import pygame` and see if that crashes your system?
You said that you are using ubuntu 16.04, I dont this should be an issue but we are starting to look for weird answers as there doesn't seem to be an obvious reason why this is happening

**Comment by jkterry1** [comment]
This should be fixed in master now, if it's not please let us know
