### ISSUE TITLE
[Bug] turn indicators on car racing not rendering

### ISSUE THREAD

**Issue by jjshoots** [openai/gym#2758]
**Describe the bug**
I have no idea why, but after #2749, the turn indicators in CarRacing no longer render and are only black now.

Edit: Figured it out.

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

![image](https://user-images.githubusercontent.com/38184875/163634485-ac7cdb46-a3f8-4164-bc99-ebc077d1472d.png)

**Comment by pseudo-rnd-thoughts** [comment]
@jjshoots Could you update the title just for the future
