### ISSUE TITLE
[Proposal] Tests for all envs

### ISSUE THREAD

**Issue by jjshoots** [openai/gym#2767]
### Proposal 

There should be more comprehensive tests for all envs. Probably the easiest test would be similar to that in PettingZoo where every state of a rollout is asserted to be contained in the observation space.

There should also be tests that assert the behaviour of environments where this can be tested. One example is the heuristic landing for Lunar Lander (which currently only works for the non-winded case).

**Comment by pseudo-rnd-thoughts** [comment]
## Proposed changes 
* Update the`spec_list` to remove atari and provide a full spec list and a no-mujoco spec list
* Remove all atari tests - Currently atari is not being installed so there is no point in the tests being there. https://github.com/openai/gym/issues/2734#issuecomment-1109729283
* Upgrade the action dim test - Check that environments do not allow out of bounds actions, i.e. extra dims, outside observation space
* Upgrade the environment determinism - Improve the number of time steps that we environment step equivalence. This will also test the environments can step / rollout
* Simplify the observation shape check - This could be part of the determinism check to help improve performance and reduce test time
* Test render - Current that all of the render modes for environments return the expected output
* Test kwargs for classic control, box2d, and toy text, some of these environments have kwargs, hardcore, randomize, etc. Currently there are no tests that the kwargs effect the environments "correctly" however this is difficult to test. There is a frozenlake DFS map generation test already for this
*  Mujoco - There is a mujoco v2 to v3 tests however it is unclear if this is unneeded anymore with v4 coming out. Possibly add new v4 tests
* Registration - These tests are actually in a good condition, I believe so these will be kept
