### ISSUE TITLE
[Bug Report] Import error when making cliff-v0 environment 

### ISSUE THREAD

**Issue by SamVanhoutte** [openai/gym#2779]
**Describe the bug**
I am (for an excercise in my course), trying to create (`make`) an environment for RL.  However, when executing the lines of code (see below in the Code example), I am getting an import error: 
```
ImportError: cannot import name 'rendering' from 'gym.envs.classic_control' (/opt/homebrew/Caskroom/miniforge/base/lib/python3.9/site-packages/gym/envs/classic_control/__init__.py)
```

**Code example**
This is the code I am using
```python
import gymgrid #pip install gymgrid
import numpy as np
import gym
env = gym.make('cliff-v0')
```

**System Info**
Describe the characteristic of your environment:
 * Gym was installed, using pip: `pip3 install gym`
 * What OS/version of Linux you're using: macOS 11.6 - Apple M1 Chipset
 * Python version: 3.9.7

**Additional context**
Other environment has worked (CartPole-v1, for example)
### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by younik** [comment]
This should be a problem of gymgrid, there is an open PR: https://github.com/wsgdrfz/gymgrid/pull/1
If you want to use the last version of gym, you can try using the branch of that PR (https://github.com/CedricHermansBIT/gymgrid2); you can install it with `pip install gymgrid2`

**Comment by ankshith** [comment]
> It seems to work, when downgrading the `gym` package to an older version, such as 0.21.0, by performing the following command: `pip install gym==0.21.0`

**Comment by ankshith** [comment]
Yes, it works when you downgrade the version.

**Comment by billtubbs** [comment]
I also get this error when building my [custom gym environment](https://github.com/billtubbs/gym-CartPole-bt-v0). It is avoidable by downgrading to version 0.21.0 as described above (I also had to downgrade piglet to `pyglet==1.5.27`). However, it's a little annoying for users.

Will there be an upgrade that fixes this, or is there anything I can do to my code to avoid it?
thanks

**Comment by billtubbs** [comment]
Okay sure. Thanks. But why? Are these old classic control environments not supported anymore?

**Comment by billtubbs** [comment]
I see. Do you know what specifically has been deprecated that is causing the problem here?  Is it Pyglet as a whole or just some method that these old environments use?

Basically, I'm trying to answer the question: should I
1. make some minor update to my environment to use the latest versions, or
2. a major upgrade to some new framework or something
3. or "freeze it in time" at these versions?

You seem to be suggesting (3) but just want to check.
thanks.

**Comment by pseudo-rnd-thoughts** [comment]
The easiest solution is freeze it in time as you have already written the code but I would recommend 2 as training libraries etc will start updating to the latest version
