### ISSUE TITLE
env.make() and env.render() not working properly

### ISSUE THREAD

**Issue by HasanBurney** [openai/gym#2780]
While running the env.render(), its giving me the deprecated error, and asking me to add render_mode to env.make(), while i already have done so. Reinstalled all the dependencies, including the gym to its latest build, still getting the same error
![image](https://user-images.githubusercontent.com/48687738/165476743-a92eb472-2749-4998-a28d-b6a252db4869.png)
![image](https://user-images.githubusercontent.com/48687738/165476888-2977faa0-99f8-4999-910b-2e923c37fdc0.png)
![image](https://user-images.githubusercontent.com/48687738/165476987-ca1be24a-a19b-422c-bf00-09e7d20fff69.png)

**Comment by arjun-kg** [comment]
I believe ale-py (atari envs) removed support for `env.render()` at every step. You only need to specify render argument in make, and can remove `env.render()` line. This will soon be default in native gym environments too.

**Comment by HasanBurney** [comment]
I made it work using render(mode='rgb_array') for the time being, but thank you for this!

**Comment by EiriniKot** [comment]
TypeError: AtariEnv.render() got an unexpected keyword argument 'mode'

**Comment by pseudo-rnd-thoughts** [comment]
If you are using the most up-to-date then `AtariEnv.render()` doesn't have any arguments so you will get an error.
Run `gym.make("Pong-v5", render_mode="human")` with `env.render()` and this will work like before

**Comment by Tiansuy** [comment]
> If you are using the most up-to-date then `AtariEnv.render()` doesn't have any arguments so you will get an error. Run `gym.make("Pong-v5", render_mode="human")` with `env.render()` and this will work like before

it worked for me

**Comment by MilesQLi** [comment]
> If you are using the most up-to-date then `AtariEnv.render()` doesn't have any arguments so you will get an error. Run `gym.make("Pong-v5", render_mode="human")` with `env.render()` and this will work like before

But what if I want to watch the reply and also want to get the frame in case I want to save to disk?
