### ISSUE TITLE
Maze environments

### ISSUE THREAD

**Issue by danijar** [openai/gym#279]
It would be cool to have grid world environments as common in RL literature. Is that something you are thinking about?

**Comment by ppwwyyxx** [comment]
I did have some maze wad files, as well as code to randomly produce them. They look like this:
![maze](https://cloud.githubusercontent.com/assets/1381301/17505981/ee2b36c4-5db9-11e6-8e97-67d783704bc6.png)

**Comment by danijar** [comment]
Is this for Doom? That's very interesting but for testing and comparing new algorithms, it would be nice to test them on fully-observed 2D grid world tasks, where the four actions move the current position to the four adjacent cells, respectively.

**Comment by ppwwyyxx** [comment]
Oh I forgot to mention it is for doom. Yes having a 2D fully-observed maze would be nice. This is a partially-observed 3D one and it would be much more challenging.

**Comment by sanjinzhi** [comment]
Is there 3D grid environment for gym?

**Comment by mryellow** [comment]
It's not fully polished and a little complex agents to solve, but generates mazes for episodes and wraps them in Gym.

https://github.com/mryellow/gym-mazeexplorer  
https://github.com/mryellow/maze_explorer

**Comment by jkterry1** [comment]
I'm not open to accepting new environments in Gym at this time. However, @mryellow and others, I welcome PRs to add more environments to the third part environments list.
