### ISSUE TITLE
OpenAI Email

### ISSUE THREAD

**Issue by shivencar** [openai/gym#2794]
Hello, 

I know this is not regarding the code point of things, but I was just wondering if there is an email I could use to contact OpenAI about a great project idea. 

Thanks!!!

**Comment by pseudo-rnd-thoughts** [comment]
All of the current maintainers are not openai employees or have any contact with openai most of the time
So sadly we can't help you at all

I recommend looking for an email address on their website but before doing that I recommend trying to check if anyone has done the work already

**Comment by shivencar** [comment]
I tried looking on the website and searching it up, but I couldn't find an email address or phone number. Also, I have looked on their website to see if somebody has done that project, but no one has done it. 


Cheers!!!
