### ISSUE TITLE
[Bug Report] Misleading type hint for `MultiDiscrete`

### ISSUE THREAD

**Issue by Markus28** [openai/gym#2797]
Type hints suggest that `MultiDiscrete` spaces must be flat: https://github.com/openai/gym/blob/b4f40f5ab621cafa778af393f540e51588fe2b8d/gym/spaces/multi_discrete.py#L33

That's actually not true, something like

```
MultiDiscrete([[1,2], [3, 4]])
```

is allowed. Whether it is a good idea is another question entirely.

**Comment by Markus28** [comment]
Also, why do we need a dtype?

**Comment by pseudo-rnd-thoughts** [comment]
One of the aims in the future is to have the whole project type checked, at least the critical parts like space. 

From memory, nvec that is passed to a numpy array so you are right, the type is greater than what the docstring actually says.

**Comment by Markus28** [comment]
I will change the type to `Union[np.ndarray, list[int]]`. 

I feel like it is reasonable to require a numpy array if someone wants multiple axes. I have no idea how to encode an arbitrarily nested list as a type hint. Even if it was possible, it wouldn't guarantee flawless conversion to a numpy array.

But I'm still puzzled by the argument `dtype`. Why would we want to allow someone to pass `float` to a `MultiDiscrete` space? (That is actually possible and results in really dumb behavior)

**Comment by pseudo-rnd-thoughts** [comment]
To make an arbitrarily nested list, I suspected we would have to construct a recursive type hint but that doesn't seem good.
For now, I think it is fine
Passing a numpy array is probably the way to get people to use arbitrarily sized arrays so I dont think we should worry about it with the new typing.

For the dtype, I agree, this doesn't seem to make much sense but someone may care about using `uint8`, `int16`, `int32` or `int64` plus for backward compatibility then I think we have to keep the parameter
But we could add a check that the dtype passed supports ints and raise an error or warning if not??
