### ISSUE TITLE
[Proposal] Add turbulance disturbance to LunarLander

### ISSUE THREAD

**Issue by jjshoots** [openai/gym#2799]
### Proposal 

As it stands, LunarLander currently has an option to add wind. But this wind only applies a linear impulse to the craft.
It would be good if wind also applies rotational impulses to the craft, to pseudo-simulate the effect of turbulance.

The most obvious way to do this would be to modify the first part of `step()` to also include a `self.lander.ApplyTorque(...)` line under the wind code.

What's unclear is what magnitudes of wind are suitable, as well as what function should the torque follow (currently wind follows a pseudo-perlin noise function).

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by virgilt** [comment]
@jjshoots, I am looking into this issue. @pseudo-rnd-thoughts asked me take a stab at it.
