### ISSUE TITLE
[Bug Report] env checker does not restart done environments.

### ISSUE THREAD

**Issue by vadim0x60** [openai/gym#2803]
**Describe the bug**
When `CartPole` is `done`, but you keep calling `env.step()` on it, it logs a warning that any steps after the environment is done are undefined behavior. However, the env checker (see, for example, `gym.utils.env_checker._check_nan()`) does not respect this rule and makes step after step without checking for `done`. For some environments this can lead to an error, so those environments do not pass the env check, even though this kind of errors are expected.

**Code example**

```
import sys
import gym
from gym.utils.env_checker import check_env

class OneStepEnv(gym.Env):
    done = True
    observation_space = gym.spaces.Discrete(2)
    action_space = gym.spaces.Discrete(2)

    def reset(self):
        self.done = False
        obs = self.observation_space.sample()
        return obs

    def step(self, action):
        assert not self.done, 'Cannot call env.step() before calling reset()'
        self.done = True
        obs = self.observation_space.sample()
        r = 0
        return obs, r, self.done, {}

check_env(OneStepEnv())
```

```
Traceback (most recent call last):
  File "/home/320012346/imaging-gym/check.py", line 22, in <module>
    check_env(OneStepEnv())
  File "/home/320012346/.pyenv/versions/3.9.12/lib/python3.9/site-packages/gym/utils/env_checker.py", line 338, in check_env
    _check_nan(env)
  File "/home/320012346/.pyenv/versions/3.9.12/lib/python3.9/site-packages/gym/utils/env_checker.py", line 55, in _check_nan
    observation, reward, _, _ = env.step(action)
  File "/home/320012346/imaging-gym/check.py", line 16, in step
    assert not self.done, 'Cannot call env.step() before calling reset()'
AssertionError: Cannot call env.step() before calling reset()
```

**System Info**

Python 3.9.12, gym 0.21.0 installed with pip on Ubuntu 18.04.6 LTS, 4.15.0-176-generic

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for the comment, this will be fixed in the next release
