### ISSUE TITLE
[Bug Report] ActionWrapper NotImplementedError 

### ISSUE THREAD

**Issue by minoshiro1** [openai/gym#2811]
Hello, i have some problem during my test on Reinforcement learning implementation. Then I try a easy one also come out the same error. It happens every time env.step(action) and the action is normalized through the ActionWrapper.
My codes are as follows

import torch
import gym
class NormalizedActions(gym.ActionWrapper):
def _action(self, action):
        low  = self.action_space.low
        high = self.action_space.high

        action = low + (action + 1.0) * 0.5 * (high - low)
        action = np.clip(action, low, high)

        return action

    def _reverse_action(self, action):
        low  = self.action_space.low
        high = self.action_space.high

        action = 2 * (action - low) / (high - low) - 1
        action = np.clip(action, low, high)

        return action
env = NormalizedActions(gym.make("Pendulum-v0"))
env.reset()
action = env.action_space.sample()
o,r,done,info = env.step(action)
env.render()

And the error come out this
C:\Users\COLLAB\Anaconda3\envs\gym\python.exe C:/Users/COLLAB/Desktop/SAC/SAC_model/1.py
Traceback (most recent call last):
  File "C:/Users/COLLAB/Desktop/SAC/SAC_model/1.py", line 24, in <module>
    o,r,done,info = env.step(action)
  File "C:\Users\COLLAB\Anaconda3\envs\gym\lib\site-packages\gym\core.py", line 308, in step
    return self.env.step(self.action(action))
  File "C:\Users\COLLAB\Anaconda3\envs\gym\lib\site-packages\gym\core.py", line 312, in action
    raise NotImplementedError
NotImplementedError

Process finished with exit code 1

If anyone got the same question like me and anyone know how to fix it , please also put your comment or how to solve it. 
Thank you very much.

**Comment by RedTachyon** [comment]
You seem to have implemented the wrapper incorrectly, check out its actual signature: https://github.com/openai/gym/blob/master/gym/core.py#L349

Notably, you should remove the underscore in `def _action` and `def _reverse_action` and it should maybe work

**Comment by minoshiro1** [comment]
> You seem to have implemented the wrapper incorrectly, check out its actual signature: https://github.com/openai/gym/blob/master/gym/core.py#L349
> 
> Notably, you should remove the underscore in `def _action` and `def _reverse_action` and it should maybe work
