### ISSUE TITLE
[Bug Report] NotImplementedError

### ISSUE THREAD

**Issue by harshshah1801** [openai/gym#2820]
I am trying to run a basic program but it is showing NotImplementedError which I am unable to fix
code-
import gym
env = gym.make('CartPole-v0')
env.reset()
for _ in range(1000):
    env.render()
    env.step(env.action_space.sample()) 
env.close()
error-
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-4-7b96e94983d7> in <module>()
      3 env.reset()
      4 for _ in range(1000):
----> 5     env.render()
      6     env.step(env.action_space.sample())
      7 env.close()

~/anaconda3/lib/python3.6/site-packages/gym/core.py in render(self, mode, **kwargs)
    293 
    294     def render(self, mode="human", **kwargs):
--> 295         return self.env.render(mode, **kwargs)
    296 
    297     def close(self):

~/anaconda3/lib/python3.6/site-packages/gym/envs/classic_control/cartpole.py in render(self, mode)
    179             from gym.envs.classic_control import rendering
    180 
--> 181             self.viewer = rendering.Viewer(screen_width, screen_height)
    182             l, r, t, b = -cartwidth / 2, cartwidth / 2, cartheight / 2, -cartheight / 2
    183             axleoffset = cartheight / 4.0

~/anaconda3/lib/python3.6/site-packages/gym/envs/classic_control/rendering.py in __init__(self, width, height, display)
     86         self.width = width
     87         self.height = height
---> 88         self.window = get_window(width=width, height=height, display=display)
     89         self.window.on_close = self.window_closed_by_user
     90         self.isopen = True

~/anaconda3/lib/python3.6/site-packages/gym/envs/classic_control/rendering.py in get_window(width, height, display, **kwargs)
     66     Will create a pyglet window from the display specification provided.
     67     """
---> 68     screen = display.get_screens()  # available screens
     69     config = screen[0].get_best_config()  # selecting the first screen
     70     context = config.create_context(None)  # create GL context

~/anaconda3/lib/python3.6/site-packages/pyglet/canvas/base.py in get_screens(self)
     96     Use :func:`~Display.get_screens` or :func:`~Display.get_default_screen`
     97     to obtain an instance of this class.
---> 98 
     99     :guide:`screens`
    100     '''

NotImplementedError: abstract

I have installed gym using pip and am using Ubuntu 18.04.6 and Python 3.6.3 :: Anaconda, Inc.

There was a similar problem in this repo but it got solved by downgrading pyglet to pyglet 1.2.4 but it did not work for me. I am a beginner so forgive me if i have made any silly mistake and any help would be appreciated.

**Comment by pseudo-rnd-thoughts** [comment]
So we do not support python 3.6 anymore (as python itself are not supporting it anymore with no more updates)
This means that I believe you have downloaded an old version of the project and therefore it is probably causing issues with pyglet that we no longer use.

Could you upgrade python version and install a more recent version of gym, (`pip install gym[classic_control]`)

**Comment by jkterry1** [comment]
Hey, I'm going to close this, please let us know if you need any more help
