### ISSUE TITLE
[Proposal] Invalid action masking

### ISSUE THREAD

**Issue by vwxyzjn** [openai/gym#2823]
### Motivation

It's common for games to have invalid _discrete_ actions (e.g. walking into a wall). The status quo is to create a `gym.spaces.Discrete` action space that contains both valid actions and invalid actions, and if an invalid action is executed, the gym environment/game engine ignores the invalid actions. 

This is less ideal for RL libraries because using action masks (i.e., only sampling valid actions) could significantly speed up training. See [A Closer Look at Invalid Action Masking in Policy Gradient Algorithms](https://arxiv.org/abs/2006.14171).

### Proposal

Let's add a standard API for invalid action masking. This issue kick starts the discussion. The simplest API I can think of is just adding

```python
class Discrete(Space[int]):
    r"""A space consisting of finitely many elements.
    This class represents a finite subset of integers, more specifically a set of the form :math:`\{ a, a+1, \dots, a+n-1 \}`.
    Example::
        >>> Discrete(2)            # {0, 1}
        >>> Discrete(3, start=-1)  # {-1, 0, 1}
    """

    def __init__(
        self,
        n: int,
        seed: Optional[int | seeding.RandomNumberGenerator] = None,
        start: int = 0,
    ):
        # ...

    def action_mask(self) -> Sequence[int]:
        pass
```

### Additional context

* SB3 has implemented invalid action masking via a wrapper (i.e., `env = ActionMasker(env, mask_fn)`). See https://github.com/Stable-Baselines-Team/stable-baselines3-contrib/pull/25 and [docs](https://sb3-contrib.readthedocs.io/en/master/modules/ppo_mask.html#example)
* Griddly does this via a wrapper ([docs](https://griddly.readthedocs.io/en/latest/getting-started/action%20spaces/index.html#sampling-valid-actions))
* Gym-microrts implemented it with a class method (see [code](https://github.com/vwxyzjn/gym-microrts/blob/bfa6e8d922c27d7f9e90f4ff94821c9cbe8c14f8/gym_microrts/envs/vec_env.py#L247))

### Alternative design

We could also make the observations a dicttionary obs space and include a key called action_mask, which is inlined with practice done here https://www.pettingzoo.ml/classic/go. This approach requires no change to the main API but only a recommendation from gym's website.

### Example

`Taxi-v2` (https://www.gymlibrary.ml/environments/toy_text/taxi/) could be a straightforward example. Its action space has 6 discrete actions:

0: move south
1: move north
2: move east
3: move west
4: pickup passenger
5: drop off passenger

Consider the following screenshot example, the `env.action_space.action_mask()` should look like

```[1, 0, 1, 0, 0, 0]```

![image](https://user-images.githubusercontent.com/5555347/171018184-f852a640-7725-4200-801a-4f9d76e74f22.png)

### Additional notes:

This action mask feature should work with `MultiDiscrete` action space and the vectorized environments natively.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by DarkLord0206** [comment]
Created PR #2859 for this.

**Comment by heng2j** [comment]
Hi @pseudo-rnd-thoughts,  we are working on a path planning problem on 2D maps where our agent samples cartesian coordinates from the continuous action space. Each 2D map clearly defines feasible and infeasible regions for the agent to navigate. (Imagine the game map of StarCraft). We are looking for ways to mask the continuous action space where our agent can only sample cartesian coordinates from the feasible region of the map. Do you recommend adding an image masking-like technique to mask action for the Box space to solve planning problems similar to ours? 


<img width="1127" alt="Screen Shot 2022-07-22 at 8 59 35 AM" src="https://user-images.githubusercontent.com/6942234/180444295-45b3d113-917d-4b75-b429-f4e17558e477.png">
I am using this notional image that I found from [Aparajita Ojha's Lecture on Path Planning and Robot Navigation](https://www.youtube.com/channel/UC-ssnV9DeWFKzyu-uHhXjrw) on Youtube as reference

**Comment by pseudo-rnd-thoughts** [comment]
HI @heng2j, thanks for the comment. The problem is that is difficult to know how to specify the sample area for a Box environment in a clear way that will be generic enough. In addition, for RL algorithms, it is not possible to apply a mask to the output. These are the main reasons, we have not implemented the sample for Box
I would be possible for you to implement this with a MultiDiscrete action space but if you really want a continuous action space then I recommend you implement your own sample function. 
Is you arrive at an efficient solution, we would be interested in you submitting a PR with your suggestion for us to consider.

**Comment by Leong1230** [comment]
Hi, does anyone ever try implmenting the action masking technique for a Box environment or for different algorithms (DQN, TD3,..., etc.) ? Still confused in how to use it with sb3 algorithm and gym. Can you provide some advices/examples on doning this?

**Comment by pseudo-rnd-thoughts** [comment]
Currently, Gym doesn't provide a way of masking Box spaces and for SB3, I would ask on SB3's repo
