### ISSUE TITLE
[Proposal] Standard error handling for out of bound actions

### ISSUE THREAD

**Issue by gianlucadecola** [openai/gym#2828]
### Proposal

Currently, for discrete action spaces, there isn't a standardized way of handling out-of-bound actions.
Some have this kind of check:
https://github.com/openai/gym/blob/745e7059e7754e26cfcaa82d0d9a0defec3a08c4/gym/envs/box2d/lunar_lander.py#L425-L427
Others let the step fail with different errors.

i.e. IndexError for acrobot (AVAIL_TORQUE is a `list`):
https://github.com/openai/gym/blob/745e7059e7754e26cfcaa82d0d9a0defec3a08c4/gym/envs/classic_control/acrobot.py#L190

KeyError here since `P[self.s]` is a `dict`:
https://github.com/openai/gym/blob/745e7059e7754e26cfcaa82d0d9a0defec3a08c4/gym/envs/toy_text/taxi.py#L210-L211
I think it is reasonable to add more consistency across error handling and raise for example this exception:

https://github.com/openai/gym/blob/e2266025e6c77641629f1ce8b12b4f73bca91352/gym/error.py#L64-L65

Continuous action space performs clipping for out-of-bounds action so I think it is ok to leave them as they are.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by pseudo-rnd-thoughts** [comment]
I'm not sure, how I feel about this idea. Having looked through a couple of the environments, they seem like a spaghetti mess of code with features and rewrites slowly added over the last 5 years. For reference, this is a rewritten version of [mountain_car](https://github.com/google/deluca/blob/main/deluca/envs/classic/_mountain_car.py) 

Personally, I think having a specification for dealing with out-of-bounds actions for both discrete and continuous action spaces is needed however this would be easier to add uniformly in the new/upgraded versions of these environments. 
Given how long these environments have been around, and that I haven't seen any issues on the topic then I'm unsure if we need this.

**Comment by jkterry1** [comment]
I really don't think that enforcing a standard is a good idea. Different environments and learning code have different needs for a variety of good reasons here. Illegal actions are a bit different than just outside the bounds of observation spaces. Also an alarmingly large number of environments have ill defined bounds.

@RedTachyon

**Comment by gianlucadecola** [comment]
Got it; the idea come to my mind while writing tests and seeing that discrete envs raises different kinds of exceptions when dealing with out-of-action-space actions (however they all raise _an_ exception). 
For continuous action-spaces this problem is not present since they perform clipping inside _step_.

**Comment by RedTachyon** [comment]
It kinda feels like the discussion is about a few different proposals to me, or I'm misreading the original post.

FWIW I think the proposal is fine in the scope that it describes - that is, introduce a specific type of an exception, and use it for environments where we're already doing out-of-bounds checking. All it really does is that it makes the error messages a bit clearer. It doesn't have to be enforced in external envs in any way
