### ISSUE TITLE
Allow to add custom Doom levels 

### ISSUE THREAD

**Issue by danijar** [openai/gym#283]
As @ppwwyyxx suggested, it would be nice to use the Gym interface for custom Doom levels. I think this could actually be a rather easy change. Currently, the tasks pass their level number to the `DoomEnv` class that selects the config, WAD file, and some other parameters based on the level number.

Instead, the `DoomEnv` class could take those parameters as constructor arguments. The classes for the specific tasks would then pass their parameters to the the base class constructor. That way, one could easily add custom Doom tasks by subclassing `DoomEnv` and registering this subclass to the Gym registry.

**Comment by ppaquette** [comment]
@ppwwyyxx 
I converted doom to a custom env.

1) you need to install ``gym_pull`` with ``pip install gym_pull``
2) you need to pull the custom env with:

```
import gym
import gym_pull
gym.pull('ppaquette/gym-envs/DoomBasic')   # You can use gym.pull('ppaquette/gym-envs/*') to download all my custom envs, but there are 75+
env = gym.make('ppaquette/DoomBasic-v0')
```

If you go the my [gym-envs](https://github.com/ppaquette/gym-envs) repo, you can manually download wrappers to modify the env (including loading a custom map).

If you want more customization, you can just fork the repo, modify a couple of lines directly, adjust the '.openai.yml' in the root folder, and then download the env with gym.pull('your username/your repo/env name'). The openai.yml documentation is [here](https://github.com/ppaquette/gym_pull)

**Comment by christopherhesse** [comment]
Thanks for answering this @ppaquette, we don't have the doom envs in gym anymore, so something like that seems ideal.
