### ISSUE TITLE
[Bug Report] CarRacing environment - Change of SCALE (car_racing.py) results to shifted initial position 

### ISSUE THREAD

**Issue by SteliosNtua** [openai/gym#2830]
release 0.23.1

**Describe the bug**
Trying to run the car_racing.py with different values on track scale parameter SCALE leads to shifted starting position of the car.
While the camera starts at the expected starting position on the track, the car initial position is shifted.
 
The only parameters modified is ZOOM, reduced to 0.2 in order to make the bug visible, and SCALE in order to achieve larger tracks.

default value of SCALE: 6.0
example value of SCALE: 10.0

Below there are two examples that show the car position for 
default value of SCALE 

![281891809_420748906224647_7156620405392163796_n](https://user-images.githubusercontent.com/37153597/169799908-19bfc106-5dbe-495c-8a09-53acef7f658f.png)

and example value of SCALE.
![281920040_717363976074899_6156146512703631858_n](https://user-images.githubusercontent.com/37153597/169800078-a80babed-ef7a-40af-ba91-ff95d7152e61.png)

The initial angle position of the car is specified here:
`self.car = Car(self.world, *self.track[0][1:4])`

and it is related to first tile of the track that is generated but the visual result is different.

**System Info**
 * Anaconda environment
 * MacOS Monterey 12.3
 * Python 3.9.12

**Desired solution**
The desired behaviour would be that regardless the SCALE, the initial position of the car should match the first track tile.

I think in the previous version of CarRacing env, with pyglet, this was not an issue.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for your PR, we will investigate and try to solve the issue. 
Do you have any ideas about what is going wrong in the code?

**Comment by andrewtanJS** [comment]
The issue was that there are in fact 2 different `SCALE` variables in `car_racing` and `car_dynamics` . #2831 fixes the issue.

**Comment by SteliosNtua** [comment]
Hey @andrewtanJS great work! Thank you for your prompt reply and contribution!
