### ISSUE TITLE
Adding Different Reward Functions for Environments (MuJoCo+)

### ISSUE THREAD

**Issue by jhollowayj** [openai/gym#284]
For part of my research, I'm planning on implementing target speed in the MuJoCo models that could  involve speed (Ant, Half Cheetah, Hopper, Humanoid, Walker 2D, maybe Swimmer). Has there been any discussion or thought into adding different reward functions into the MuJoCo models or any other environment?  I know it could potentially add a large number of environments (6+ environments*x number of target speeds) listed in the [Algorithms](https://gym.openai.com/algorithms) page, but I'm planning on doing that for some of my research anyway and wondered if that would be beneficial to the gym community.  It seems that it would force algorithms to be stronger.

If there is interest, I'd be happy to share and also get feed back how to best implement it to be straight forward and streamlined for future users in the pull request.

**Comment by JKCooper2** [comment]
The [gym_pull](https://github.com/ppaquette/gym_pull) package could be a good way to store alternate versions of envs in your local github repo but have them easily accessible from the gym.

**Comment by tbreloff** [comment]
I'll register my interest in this as well.  Particularly, I'm interested in dynamically changing reward functions during training: for example lowering a "movement penalty" during initial exploration and then increasing it during efficiency tuning.  As everything is currently hardcoded, this sort of thing is too difficult.  It would be great to maybe access the reward multipliers from a dictionary that can be updated dynamically by users.

**Comment by shelhamer** [comment]
@jhollowayj Another approach I've taken is to define env wrappers, such as [RewardWrapper](https://github.com/openai/gym/blob/master/gym/core.py#L389-L398), for composing with the default gym environment. I've only done it for simple reward manipulations, but perhaps this could work for you.

(I don't have concrete examples online yet, but I'll push to my fork when I have the chance.)

**Comment by jhollowayj** [comment]
I'll close this for now, but if I ever do come back around to doing this, I'll look into the RewardWrapper, suggested by shelhamer
