### ISSUE TITLE
[Question] How to suppress  Custom namespace `ALE` is being overridden by namespace `ALE` warning?

### ISSUE THREAD

**Issue by araffin** [openai/gym#2849]
### Question

Installing gym and then ale-py (easiest is to do that in a colab), `import gym` throws a warning:

```
 Custom namespace `ALE` is being overridden by namespace `ALE`
```
how to get rid of it?

(does not seem normal that basic install of gym throws a warning)
gym 0.24
ale-py 0.7.5

**Comment by RedTachyon** [comment]
That's an error of the recent registration revamp, my bad.

I fixed the problem in #2850, hopefully we'll put it in like a 0.24.1 release. 

There's also the underlying reason why the gym import is affected just by having ale-py installed. A few releases ago, we added a plugin system that simplifies some use-cases when using/developing external libraries that are meant to interface with gym. While I'm not a huge fan of it, it is what it is. It basically detects that ALE is installed, and then automatically imports it when you import gym, registering all contained environments. Effectively, this saves you from having to write `import ale_py` in your code.
