### ISSUE TITLE
[Bug Report] Environment Step Check doesn't allow NumPy integer rewards.

### ISSUE THREAD

**Issue by ttran2** [openai/gym#2878]
**Describe the bug**
Some environments return the rewards in the form of a _NumPy integer_ (ex. `np.int32`).  However, the _passive environment step check_ doesn't allow NumPy integer rewards, as it allows only Python built-in `float` & `int` datatypes and `np.float32`.

**Reproducing Bug**
To reproduce the issue, create an environment where the `step()` would return `rewards` in NumPy integer datatype (ex. `np.int32`).

**System Info**
 * OS: `Windows 10`
 * Python: `3.7.9`
 * Gym: `0.24.1`

**Additional context**
_none_

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for the PR, yes, you are right that `np.integers` should be allowed

**Comment by pseudo-rnd-thoughts** [comment]
@ttran2 During testing, I realised that your PR didn't actually fix the issue. Could you test my PR here, it fixes some additional stuff and I just want to check it hasn't caused more https://github.com/openai/gym/pull/2873
