### ISSUE TITLE
[Question] Custom environment where states are fed in from database?

### ISSUE THREAD

**Issue by IanQS** [openai/gym#2895]
### Question

I currently have a custom environment that loosely obeys the gym API. I have an environment wherein the state at any given time is data that was collected e.g price of electricity, supply, etc. All of this would be polled in from the database via a connection. The logic of my custom env looks a little like this:

```
class CustomEnv:
    def __init__(self, my_arg1, my_arg2, ....):
        self.db_connection = initialize_db_conn(**db_params)
        self.db_cursor = self.db_connection.generate_cursor()  
        ....

    def step(self, action: Action) -> State:
        raw_next_state = self.db_cursor.next()
        # take action and modify some internal tracker
        processed_next_state, reward, done = self.some_internal_applier(raw_next_state, action)
        return processed_next_state, reward, done, {}
        ...
```

How would I best accomplish integrating in the database? Is it as "simple" as merely adding in the connection on the init? I'm reading through the [environment creation docs](https://www.gymlibrary.ml/content/environment_creation/) and that's the impression I'm getting but I'd like to be sure before moving things over

**Comment by pseudo-rnd-thoughts** [comment]
Hi, interesting question, yes this looks like the correct way of doing, however, your dataset will most likely need to contain all of the possible states that the agent could encounter

**Comment by RedTachyon** [comment]
Opening the DB connection in `__init__` and then using it in `reset` and/or `step` should work exactly how you want. Just make sure you have logic to close the connection on `env.close()`, and other than that you just need to follow the general gym API and there shouldn't be any problems
