### ISSUE TITLE
[Question] Assertion error, cant use cnn policy with atari breaout open gym ai

### ISSUE THREAD

**Issue by Shivam310** [openai/gym#2914]
### Question

Hi,

I was making my atari breakout model when I was trying to use the cnn policy but I get this:

```
AssertionError Traceback (most recent call last) Input In [16], in <cell line: 2>() 1 log_path = os.path.join('Training', 'Logs') ----> 2 model = A2C('CnnPolicy', environment_name, verbose=1, tensorboard_log=log_path)

(you are probably using \
CnnPolicy\ instead of `MlpPolicy` or `MultiInputPolicy`) If you are using a custom environment, please check it using our env checker``
```

Here is my code:

```
environment_name = gym.make("Breakout-v0")

environment_name = gym.wrappers.FrameStack(environment_name, 4)

log_path = os.path.join('Training', 'Logs')

model = A2C('CnnPolicy', environment_name, verbose=1, tensorboard_log=log_path)
```

**Comment by RedTachyon** [comment]
That's not a gym issue, you should check the documentation/usage guide. Also, it's likely that you're using an outdated version of gym and atari, since current atari envs (which are also not a part of this repository, but instead https://github.com/mgbellemare/Arcade-Learning-Environment) are `v4`

I'd also suggest trying to do what the error message is telling you to do.

**Comment by Shivam310** [comment]
> That's not a gym issue, you should check the [SB3 documentation/usage guide](https://stable-baselines3.readthedocs.io/en/master/). Also, it's likely that you're using an outdated version of gym and atari, since current atari envs (which are also not a part of this repository, but instead https://github.com/mgbellemare/Arcade-Learning-Environment) are `v4`
> 
> I'd also suggest trying to do what the error message is telling you to do.

Hi, firstly thx for the response and I am sorry for my late reply but I tried what u said but I still get the same error. I also tried using mlp policy to make the model but when I test it the platform that moves just goes to right and stops and nothing happens then. Please help, thx

**Comment by pseudo-rnd-thoughts** [comment]
This issue appears to be due to SB3 not Gym, would you be able to report this issue with him. Im unsure what we can do to help

**Comment by Shivam310** [comment]
> This issue appears to be due to SB3 not Gym, would you be able to report this issue with him. Im unsure what we can do to help

Hi,
Thanks for the response, I have dropped the question on the sb3 github issues page.
Thanks for the suggestion!
