### ISSUE TITLE
Passive env checker reads shape wrongly

### ISSUE THREAD

**Issue by BlueskyFR** [openai/gym#2917]
Hi! Thanks for reading ;)

The documentation shows many examples of **Box** being used with `shape=()`, e.g. `spaces.Box(-1, 1, shape=(), dtype=np.float32)`.

## Problem

- `len(spaces.Box(-1, 1, shape=(), dtype=np.float32).shape)` returns 0
- `len(spaces.Box(-1, 1, shape=(1,), dtype=np.float32).shape)` returns 1

The passive env checker shows an error if shape length is zero : https://github.com/openai/gym/blob/4d57b864f866b5f38ce8a05024184d675c897727/gym/utils/passive_env_checker.py#L30-L35

Since I can think of a lot of cases where a **Dict** is needed to display values nicely instead of a big 1D vector without property namings, I think this is not a wanted behavior.

What do you think?

**Comment by RedTachyon** [comment]
The env checker doesn't raise an error, it raises a warning. Basically saying "Hey, you're doing something non-standard, just make sure you know what you're doing and move along". A zero-dimensional array is technically possible in the `Box` space, but definitely qualifies as something "weird" and you probably don't want to use it unless you know what you're doing.

And I don't see how `Dict` spaces are relevant here, since this is a check for `Box` spaces?

**Comment by pseudo-rnd-thoughts** [comment]
@RedTachyon I think the reason for the `Dict` comment is that the `observation_space` check is done recursively for `Tuple` and `Dict` spaces.
@BlueskyFR The reason for 1d vectors is that if you are using an environment with a neural network, they normally expect 1d vectors for dense layers or 3d tensors for convolutional layers. While 0d vectors are nicer to look at and sometimes work with, we don't recommend it. What were the cases that you were thinking about?

**Comment by BlueskyFR** [comment]
I mean that I want to use a Dict to make it easier to read properties by hand.
I would of course convert the Dict to a 1D array but just before fedding the NN with it.
The idea as that the 1D array doesn't HAVE to be created in Gym as this is pretty hard to read by a human

**Comment by pseudo-rnd-thoughts** [comment]
This is a warning so you can just ignore it but personally, I think that is a really weak reason for worse performance (having to expand dims before passing to NN)

**Comment by BlueskyFR** [comment]
okay, thanks for the informations!
So may I ask what the typical use case for the Dict is?

**Comment by pseudo-rnd-thoughts** [comment]
Personally, I haven't use them in research but they are functionally the same as `Tuple` for lot of problem. So if you have multiple action spaces. For example, we you have a robot, where you have a "left arm" you may have that as a subspace in a `Dict`

**Comment by RedTachyon** [comment]
> will using a dict instead of a 1D vector throw a warning?
No, that test is only for box spaces.

I think this issue can be closed, there's no problem to fix

**Comment by BlueskyFR** [comment]
@pseudo-rnd-thoughts completing my last comment above, the recommended usage of a 1D vector does not mix well with the fact that observations can be converted to flat arrays using a wrapper.
On top of that, for example I am currently representing wind data as a `(182, 360)` shape, which throws a warning.

I am just suggesting that maybe too much assumptions are made in this passive env checker about the shape? Maybe it is better to let people use the shapes they want a bit more since there is no way to disable that warning specifically AFAIK

**Comment by pseudo-rnd-thoughts** [comment]
Agreed but this is primarily a warning not an error so you can ignore it. This is a recommendation due to the architecture of neural networks, without pre-processing you would not be able to pass your observation straight to the NN.
