### ISSUE TITLE
[Bug Report] Pygame opening windows with render_mode=rgb_array in Lunar Lander environment

### ISSUE THREAD

**Issue by CooKySch** [openai/gym#2924]
If you are submitting a bug report, please fill in the following details and use the tag [bug].

**Describe the bug**
I'm using the environment LunarLander-v2, continuous. I want to save the images made by env.render(), but not necessarily check them, so I used rgb-array as rendering option. Yet, pygame windows keep popping up when I use this. 

**Code example**
            if render:
                frames.append(env.render(mode="rgb_array"))

**System Info**
Describe the characteristic of your environment:
Gym was installed with pip using a given requirements.txt. I'm using 0.22.0
 Pop-OS 22.04
 3.10

**Additional context**

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for the bug report, I can confirm that on 0.24.0 that this is an issue with
```python
import time

import gym

env = gym.make("LunarLander-v2")
env.reset()
env.render(mode="rgb_array")
time.sleep(2)
env.step(env.action_space.sample())
env.render(mode="rgb_array")
time.sleep(2)
env.close()
```
However, https://github.com/openai/gym/pull/2671 has seemed to have fixed this bug which will be released in v0.25

**Comment by jkterry1** [comment]
Hey, I'm closing this issue as it's fixed on master

**Comment by eabase** [comment]
@pseudo-rnd-thoughts 
How do you set the window size to something larger? 

The lander is always starting outside the view port. 
I think it's set to 600*800 or something, and I want it much larger.
