### ISSUE TITLE
[Question] Inconsistent descriptions in `half_cheetah_v4.py`

### ISSUE THREAD

**Issue by yawen-d** [openai/gym#2932]
### Question

It seems to me that the description for the **first** two dimensions of HalfCheetah's observation space aren't clear.

Specifically, in the first table in its observation space, it's said that observation[1] represents "y-coordinate of the center of mass", but in the second table, it's said that that same dimension represents "y-coordinate of the front tip".

- First table:
https://github.com/openai/gym/blob/66c431d4b3072a1db44d564dab812b9d23c06e14/gym/envs/mujoco/half_cheetah_v4.py#L50 

- Second table:
https://github.com/openai/gym/blob/66c431d4b3072a1db44d564dab812b9d23c06e14/gym/envs/mujoco/half_cheetah_v4.py#L78

I think it might just be a typo. They should mean the coordinates of the front tip. But it seems unclear to me what the front tip is. Could you please give a more detailed explanation? Thank you.

**Comment by jkterry1** [comment]
Hey, I'm closing this as the fix is in master
