### ISSUE TITLE
[Bug Report] Render window hangs

### ISSUE THREAD

**Issue by Balssh** [openai/gym#2934]
If you are submitting a bug report, please fill in the following details and use the tag [bug].

**Describe the bug**
On WSL using Ubuntu 20.04, VSCode with JupyterNotebooks, the render windows hangs and I can't close it unless I use xkill. The minimize/maximize buttons on the window works, the close button doesn't.

**Code example**
import os
import gym
from stable_baselines3 import A2C
from stable_baselines3.common.vec_env import VecFrameStack
from stable_baselines3.common.evaluation import evaluate_policy
from stable_baselines3.common.env_util import make_atari_env

environment_name = "Breakout-v0"
env = gym.make(environment_name, render_mode='human')

episodes = 5

for episode in range(episodes):
    obv = env.reset()
    done = False
    score = 0
    while not done:
        action = env.action_space.sample()
        n_state, reward, done, info = env.step(action)
        score += reward
    print("Episode:{} SCORE:{}".format(episode, score))
env.close()

**System Info**
I use Python3.10.4, along with these packages (installed in a conda environment):
_libgcc_mutex 0.1
_openmp_mutex 4.5
absl-py 1.1.0
ale-py 0.7.5
alsa-lib 1.2.3.2
aom 3.3.0
asttokens 2.0.5
atari_py 0.2.9
attrs 21.4.0
autorom 0.4.2
autorom-accept-rom-license 0.4.2
backcall 0.2.0
beautifulsoup4 4.11.1
blas 1.0
bleach 5.0.0
brotli 1.0.9
brotli-bin 1.0.9
brotlipy 0.7.0
bzip2 1.0.8
ca-certificates 2022.6.15
cachetools 5.2.0
certifi 2022.6.15
cffi 1.15.0
charset-normalizer 2.0.4
click 8.1.3
cloudpickle 2.1.0
control 0.9.2
cryptography 37.0.1
cudatoolkit 11.3.1
cycler 0.11.0
cython 0.29.30
dbus 1.13.6
debugpy 1.5.1
decorator 5.1.1
defusedxml 0.7.1
entrypoints 0.4
executing 0.8.3
expat 2.4.8
ffmpeg 4.4.1
font-ttf-dejavu-sans-mono 2.37
font-ttf-inconsolata 3.000
font-ttf-source-code-pro 2.038
font-ttf-ubuntu 0.83
fontconfig 2.14.0
fonts-conda-ecosystem 1
fonts-conda-forge 1
fonttools 4.33.3
freetype 2.11.0
gettext 0.19.8.1
giflib 5.2.1
glfw 2.5.3
gmp 6.2.1
gnutls 3.6.15
google-auth 2.8.0
google-auth-oauthlib 0.4.6
grpcio 1.47.0
gst-plugins-base 1.20.2
gstreamer 1.20.2
gym 0.21.0
gym-notices 0.0.7
icu 69.1
idna 3.3
imageio 2.19.3
importlib-metadata 4.11.4
importlib_resources 5.7.1
intel-openmp 2021.4.0
ipykernel 6.9.1
ipython 8.3.0
jbig 2.1
jedi 0.18.1
jinja2 3.1.2
jpeg 9e
jsonschema 4.6.0
jupyter_client 7.2.2
jupyter_core 4.10.0
jupyterlab_pygments 0.2.2
keyutils 1.6.1
kiwisolver 1.4.2
krb5 1.19.3
lame 3.100
lcms2 2.12
ld_impl_linux-64 2.38
lerc 3.0
libblas 3.9.0
libbrotlicommon 1.0.9
libbrotlidec 1.0.9
libbrotlienc 1.0.9
libcblas 3.9.0
libclang 13.0.1
libdeflate 1.10
libdrm 2.4.109
libedit 3.1.20191231
libevent 2.1.10
libffi 3.4.2
libgcc-ng 12.1.0
libgfortran-ng 12.1.0
libgfortran5 12.1.0
libglib 2.70.2
libgomp 12.1.0
libiconv 1.16
libidn2 2.3.2
liblapack 3.9.0
libllvm13 13.0.1
libnsl 2.0.0
libogg 1.3.4
libopus 1.3.1
libpciaccess 0.16
libpng 1.6.37
libpq 14.3
libsodium 1.0.18
libstdcxx-ng 12.1.0
libtasn1 4.16.0
libtiff 4.3.0
libunistring 0.9.10
libuuid 2.32.1
libuv 1.40.0
libva 2.14.0
libvorbis 1.3.7
libvpx 1.11.0
libwebp 1.2.2
libwebp-base 1.2.2
libxcb 1.13
libxkbcommon 1.0.3
libxml2 2.9.12
libzlib 1.2.11
lockfile 0.12.2
lz4-c 1.9.3
markdown 3.3.7
markupsafe 2.1.1
matplotlib 3.5.2
matplotlib-base 3.5.2
matplotlib-inline 0.1.2
mistune 0.8.4
mkl 2021.4.0
mkl-service 2.4.0
mkl_fft 1.3.1
mkl_random 1.2.2
munkres 1.1.4
mysql-common 8.0.29
mysql-libs 8.0.29
nbclient 0.6.4
nbconvert 6.5.0
nbconvert-core 6.5.0
nbconvert-pandoc 6.5.0
nbformat 5.4.0
ncurses 6.3
nest-asyncio 1.5.5
nettle 3.7.3
nspr 4.32
nss 3.77
numpy 1.22.3
numpy-base 1.22.3
oauthlib 3.2.0
opencv-python 4.6.0.66
openh264 2.1.1
openssl 3.0.4
packaging 21.3
pandas 1.4.2
pandoc 2.18
pandocfilters 1.5.0
parso 0.8.3
pcre 8.45
pexpect 4.8.0
pickleshare 0.7.5
pillow 9.0.1
pip 21.2.4
prompt-toolkit 3.0.20
protobuf 3.19.4
psutil 5.9.1
pthread-stubs 0.4
ptyprocess 0.7.0
pure_eval 0.2.2
pyasn1 0.4.8
pyasn1-modules 0.2.8
pycparser 2.21
pyglet 1.5.26
pygments 2.11.2
pyopenssl 22.0.0
pyparsing 3.0.9
pyqt 5.12.3
pyqt-impl 5.12.3
pyqt5-sip 4.19.18
pyqtchart 5.12
pyqtwebengine 5.12.1
pyrsistent 0.18.1
pysocks 1.7.1
python 3.10.4
python-dateutil 2.8.2
python-fastjsonschema 2.15.3
python_abi 3.10
pytorch 1.11.0
pytorch-mutex 1.0
pytz 2022.1
pyzmq 22.3.0
qt 5.12.9
readline 8.1.2
requests 2.27.1
requests-oauthlib 1.3.1
rsa 4.8
scipy 1.8.1
setuptools 61.2.0
six 1.16.0
slycot 0.4.0.0
soupsieve 2.3.1
sqlite 3.38.5
stable-baselines3 1.5.0
stack_data 0.2.0
svt-av1 0.9.1
tensorboard 2.9.1
tensorboard-data-server 0.6.1
tensorboard-plugin-wit 1.8.1
tinycss2 1.1.1
tk 8.6.12
torchaudio 0.11.0
torchvision 0.12.0
tornado 6.1
tqdm 4.64.0
traitlets 5.1.1
typing_extensions 4.1.1
tzdata 2022a
unicodedata2 14.0.0
urllib3 1.26.9
wcwidth 0.2.5
webencodings 0.5.1
werkzeug 2.1.2
wheel 0.37.1
x264 1!161.3030
x265 3.5
xorg-fixesproto 5.0
xorg-kbproto 1.0.7
xorg-libx11 1.7.2
xorg-libxau 1.0.9
xorg-libxdmcp 1.1.3
xorg-libxext 1.3.4
xorg-libxfixes 5.0.3
xorg-xextproto 7.3.0
xorg-xproto 7.0.31
xz 5.2.5
zeromq 4.3.4
zipp 3.8.0
zlib 1.2.11
zstd 1.5.2

**Comment by RedTachyon** [comment]
Gym 0.21 is outdated, the current version is 0.24.1

**Comment by Balssh** [comment]
> Gym 0.21 is outdated, the current version is 0.24.1

Yeah I know, but stable-baselines3 doesn't work with 0.24.1, should I just find a replacement to it?

**Comment by jkterry1** [comment]
You can use the PR to SB3 that supports newer versions of Gym, or you can use a different learning library that supports newer versions of Gym (I like cleanrl)
