### ISSUE TITLE
I am having "reset() got an unexpected keyword argument 'seed'" Error

### ISSUE THREAD

**Issue by amissafari** [openai/gym#2935]
Hi everyone,
when I try to run simple example code:

import gym
env = gym.make("LunarLander-v2")
env.action_space.seed(42)

observation, info = env.reset(seed=42, return_info=True)

for _ in range(1000):
    observation, reward, done, info = env.step(env.action_space.sample())
    env.render()

    if done:
        observation, info = env.reset(return_info=True)

env.close()

I will receive the following error:

 ~\anaconda3\lib\site-packages\gym\wrappers\time_limit.py", line 27, in reset
    return self.env.reset(**kwargs)

TypeError: reset() got an unexpected keyword argument 'seed' 

Can anyone help me with this error?

**Comment by RedTachyon** [comment]
When you go to create a bug report as a github issue, there's a form that gets automatically created for you to fill. This form is not for decoration, please provide the information requested there, notably system information (installation method, platform,  python version, **gym version**)

**Comment by jkterry1** [comment]
Hey, I'm going to close this due to inactivity, please let us know if you have any additional issues

**Comment by AbhayGoyal** [comment]
Hi, how would it work if I have gymnasium and not gym?

**Comment by scottyueguan** [comment]
I got the same issue when I use the FlattenObservation Wrapper...
