### ISSUE TITLE
[Proposal] Integrate pyvirtualdisplay

### ISSUE THREAD

**Issue by vadim0x60** [openai/gym#2936]
### Proposal 

If a pygame-based openai gym environment is run on a server without a screen, it should automatically provision a virtual display with a library like `pyvirtualdisplay`.

### Motivation

Calling `env.render` on many environments (in particular, [pygame](pygame.org)-based environments) requires a screen, even if it is called with `mode='rgb_array'` parameter to save an image to disk or analyze it somehow. If a screen does not exist, the function raises `pygame.error`. 

### Pitch

An exception is never intended behavior when calling `render()` (or, indeed, any other function?). So I see no downsides to changing the behavior of this function on a headless system from exception to doing what it does on a computer with a screen.

### Alternatives

I run all of [my RL training scripts](https://github.com/vadim0x60/worstpractices/blob/master/worstpractices/rl/rainbow.py) wrapped in:

```
try:
    train()
except pygame.error:
    from pyvirtualdisplay import Display
    display = Display(visible=0, size=(1400, 900))
    display.start()
    train()
```

I noticed that I use this pattern in each of my interactions with OpenAI Gym, so I believe we could make some devs' lives easier by integrating this into gym itself.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by younik** [comment]
I did quick tests, and `SDL_VIDEODRIVER = dummy` seems to work properly. However, I would not add this to the gym since it is specific to PyGame. 

Your solutions overcome this issue, but it doesn't come for free: you need to install `xvfb` manually (and it doesn't work for Windows).


Both solutions seems fairly simple, but case-specific; thus I will let the user do that. What do you think @vadim0x60?

**Comment by Markus28** [comment]
Hey @vadim0x60, could you check whether the issue persists on the master branch? There was a bug where a window was opened during rgb_array rendering and this was fixed recently. It was my understanding that this bug caused problems on headless systems. rgb_array rendering works for me over ssh on the master branch (it doesn't work with the latest release though)

**Comment by vadim0x60** [comment]
Indeed, this looks fixed. The issue occurs in version 0.24.1, but goes away in aeda7eb3581985628963a184123a19487f38da5c
