### ISSUE TITLE
Action space with mixed action types

### ISSUE THREAD

**Issue by Odalric-Ambrym** [openai/gym#2940]
Hello,

I want to describe the following action space, with 4 actions: 1 continuous 1d, 1 continuous 2d, 1 discrete, 1 parametric.
action1: Box(0.,2.)
action2: Tuple(Box(-4.,3.),Box(0,.5.))
action3: Discrete(5)
action4: Dict({'p1': Dict(3), 'p2': Box(-1.,1.)})
What is the most appropriate way to build this as a gym space? 
What is the most appropriate way to build its powerset as a gym space? 

Simply using Tuple or Dict to glue them does not produce the desired result.

**Comment by pseudo-rnd-thoughts** [comment]
Could you explain how you cannot use `Dict` or `Tuple` spaces? 
These spaces would easily allow you to "glue them" together?

Could you provide an example of the expected output and the actual output with using `Dict` or `Tuple` or your example

**Comment by jkterry1** [comment]
Hey, I'm going to close this due to inactivity, please let me know if you need anything else
