### ISSUE TITLE
Is this normal?

### ISSUE THREAD

**Issue by rukiAtLife** [openai/gym#2950]
/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/gym/utils/passive_env_checker.py:97: UserWarning: WARN: We recommend you to use a symmetric and normalized Box action space (range=[-1, 1]) https://stable-baselines3.readthedocs.io/en/master/guide/rl_tips.html
  logger.warn(

**Comment by balisujohn** [comment]
Yeah, the env checker is telling you it's ideal for your environment to have an action space where actions are allowed in the range [-1,1]. Presumably, whatever environment you are using doesn't. You can check in the code wherever your environment is defined to see what the action space is. stable-baselines3 algorithms will still (sort of) work when the action space is non symmetric and normalized, though you will definitely end up wanting to use the vectornormalize feature of stable-baselines3 for any difficult rl environments.
