### ISSUE TITLE
[Proposal] Add __setattr__ to Wrapper baseclass

### ISSUE THREAD

**Issue by seawee1** [openai/gym#2952]
### Proposal 

Currently, I am working with Tianshou which offers an env.set_env_attr(name, value) function. However, when I don't disable all default gym wrappers (OrderEnforcing and PassivEnvChecker as of now), the setattr call issued by Tianshou onto the wrapped environment does not arrive at the actual environment object. Instead, the setattr is processed by the Wrapper object and, as a result, sets the attribute of the outermost wrapper. Do I overlook something?

### Motivation

I don't see any clear reason, why this is not implemented correctly.

### Pitch

See above.

### Alternatives

Leave it as it is, which will lead people to not use your provided environment wrappers.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by RedTachyon** [comment]
The canonical way of doing this is `env.unwrapped.(whatever)`, which will always bring you to the raw environment. What's the problem with using that?

Overriding `__setattr__` in a wrapper would make it impossible to, well, set attributes of the wrapper itself.

**Comment by seawee1** [comment]
Ah okay, that makes sense. Then this is probably something that might have to be adapted on Tianshou's side. Thanks!
