### ISSUE TITLE
[Question] Questions about "gym.make()"

### ISSUE THREAD

**Issue by miyukin73** [openai/gym#2961]
Hello,

I'd like to display my own xml file (attached "mug.xml" in "mug-xml_obj.zip") in MuJoCo using "gym.make".

However, I am not sure how to change it, so I asked this question.

I apologize if this is not the appropriate place to ask this question.

Thank you in advance.
[mug-xml_obj.zip](https://github.com/openai/gym/files/9095679/mug-xml_obj.zip)

**Comment by pseudo-rnd-thoughts** [comment]
While this is possible to do it is a sequence step process
1. You need to create an environment like the current mujoco environments, [example](https://github.com/openai/gym/blob/master/gym/envs/mujoco/ant_v4.py)
2. You need to register the environment, [example](https://github.com/openai/gym/blob/634afec9bc948cc9c2633827fe7af9e67497035e/gym/envs/__init__.py#L293)
3. Then you can call `gym.make` with the registered environment name, `gym.make("Ant-v4")`
