### ISSUE TITLE
[Bug Report] "from gym.utils.renderer import Renderer" gives module not found error

### ISSUE THREAD

**Issue by FinAminToastCrunch** [openai/gym#2969]
If you are submitting a bug report, please fill in the following details and use the tag [bug].

**Describe the bug**
"from gym.utils.renderer import Renderer" gives module not found error. 

This is code from https://www.gymlibrary.ml/content/environment_creation/

**Code example**
`ModuleNotFoundError                       Traceback (most recent call last)
Input In [119], in <cell line: 3>()
      1 import gym
      2 from gym import spaces
----> 3 from gym.utils.renderer import Renderer
      4 import pygame
      5 import numpy as np

ModuleNotFoundError: No module named 'gym.utils.renderer'`

**System Info**
I have tried on Python 3.9 with the latest version of Gym and gym version 0.21.0

### Checklist

- [ x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by pseudo-rnd-thoughts** [comment]
The documentation currently only supports the latest gym version which is v0.25.0
