### ISSUE TITLE
The healthy condition for Mujoco Ant environment

### ISSUE THREAD

**Issue by Bowen-He** [openai/gym#2970]
Hi,

In the function of is_healthy(self) in ant, there is this line of the code 
is_healthy = np.isfinite(state).all() and min_z <= state[2] <= max_z 
that I think is checking if the z-coordinate is in the range defined by self._healthy_z_range.
I noticed that you take the 2nd entry from the state vector and want to double-check if that's the correct thing to do. Since in the documentation it says that if we set exclude_current_positions_from_observation=False, then the 2nd entry will be actually the y-orientation of the torso.

**Comment by RedTachyon** [comment]
I might be missing something, but in Python, arrays are 0-indexed, which means that `state[2]` is actually the third entry in that array. So if the array is `[x, y, z]`, then `state[2] == z`. Does that answer the question?

Another option I see is that you might be conflating observations and the internal state, they are very much not the same.

**Comment by rodrigodelazcano** [comment]
Thank you for answering this @RedTachyon . I think this comment bellow might also help:

The state array of the `is_healthy` method is a full observation generated by the base method `state_vector` https://github.com/openai/gym/blob/98a929303f0596ea20c9568ebab81f703a08a41c/gym/envs/mujoco/mujoco_env.py#L215

This method is independent of `exclude_current_positions_from_observation` meaning that the third entry `state[2]` will always be the z-coordinate of the torso.

**Comment by Bowen-He** [comment]
Thanks! That really helps solve my question.
