### ISSUE TITLE
Creating a SE3 state space in open ai gym environment where x,y,z signify an image of size 256*256*256,and a1,a2,a3,a4 signify quaternions i.e a rotation matrix

### ISSUE THREAD

**Issue by muk465** [openai/gym#2982]
### Question
I want to create an environment which has a curvilinear motion specified by a model ,for that i need each state to have 7 values i.e x,y,z and 4 quaternions which signify rot matrix as the motion will be curvilinear which follows a model ,so my question is how can i define such an observation space in environment?

**Comment by pseudo-rnd-thoughts** [comment]
Interesting question, gym offers a range of spaces to use https://www.gymlibrary.ml/content/spaces/
I would recommending the `Box` space with a shape of `(19,)` or a `Tuple([Box(), Box(), Box(), Box()])` with the Box containing their respective limits and shapes for the `x, y, z` and quaternions.
One option you could have is create a new `Quaternion` shape that inherits from `Box` if there are certain complex functions you need to apply to the space but you probably don't need that.

**Comment by muk465** [comment]
@pseudo-rnd-thoughts Thank you for answering my question so i have 2 doubts instead of using a tuple can i use 
1)Box(low=np.array([0,0,0,-inf,-inf,-inf,-inf]), high=np.array([255,255,255,inf,inf,inf,inf]), dtype=np.float32) 
2)now as state is an observation from the environment to which we add actions to generate new state 
can i access these individual state parameters like for eg state[3:7] should give me all 4 quaternions?

**Comment by muk465** [comment]
Thanks @pseudo-rnd-thoughts  sir
