### ISSUE TITLE
[Bug Report] deepcopying an environment results in no randomness

### ISSUE THREAD

**Issue by nollied** [openai/gym#2994]
**Describe the bug**
my use case involves running multiple environments at the same time, and after every step some of them get copied/replaced between each other. i'm using deepcopy.

when i do this deepcopying, the random numbers that the environment generates become the same as all of the other environments, this is expected behavior. however, what's not expected is that, if all of the environments have been cloned to each other in one way or another, after a few more random steps in, all numbers that are generated by sampling randomly from the action space are always the same and never change.

the action space is a tuple of 2 discrete numbers on some interval, let's call it 0-10. you will begin seeing random numbers, and then as you progress, the numbers become something like (5, 5) or (9, 0) and then repeat forever. the number selected seems to be random depending on the initial seeds. 

i've already tried setting seeds randomly before each step for the environments in a few different ways. i tried using the `env.seed` method, setting `np.random.seed`, and also i tried using the `env.unwrapped.seed` and `env.np_random.seed` methods.

**Code example**
```python
# inside env:
self.action_space = gym.spaces.Tuple(
    (
        gym.spaces.Discrete(N),
        gym.spaces.Discrete(N),
    )
)
```

```python
envs = [...]  # fill a list with some environments that can be deepcopied

for _ in range(100):
    for env in envs:
        # NOTE: i already tried setting seed here...
        action = env.action_space.sample()
        env.step(action)
    
    # ... randomly deepcopy environments to each other ...
    envs[random_index] = deepcopy(envs[another_random_index])
```

**System Info**
ubuntu desktop 20.04
conda python version 3.8.12 and gym version 0.25.0 (pip installed)

**Comment by nollied** [comment]
also weirdly enough, if you initialize only 1 environment and then deepcopy it to create your initial envs list, the seeds **do** seem different when you reset the environment for the first time. it only happens gradually as the environments are copied amungst each other during steps.

maybe it has to do with the reset function?

**Comment by pseudo-rnd-thoughts** [comment]
Im not sure that I understand exactly what you are doing, a minimal testing script would be helpful.

In the meantime, I will briefly explain how randomness in gym is done.
For each environment (and wrapper), it contains a `np_random` variable which allows access to a numpy random number generator.
The seed for `np_random` is unknown until the first call, at which it is set.
This means that if you initialise 1 environment which you copy 10 times, this will have a different seed (and different randomness).
But if you initialise 1 environment, reset it then copy 10 times, they will look act the same (given the same actions)

The same randomness exists in the spaces (i.e the obs space and action space)

Without an example to run, Im not sure what else there is to explain that could be helpful currently

**Comment by nollied** [comment]
@pseudo-rnd-thoughts i just slapped together a testing script for you to reproduce:

```python



from copy import deepcopy
import gym
import numpy as np


class CustomEnv(gym.Env):

    def __init__(self):
        self.action_space = gym.spaces.Tuple(
            (
                gym.spaces.Discrete(5),
                gym.spaces.Discrete(5),
            )
        )

    def step(self, action):
        pass  # implementation doesn't matter


env = CustomEnv()

NEW_SEED_EVERY_STEP = True  
N = 10
STEPS = 200
envs = [deepcopy(env) for _ in range(N)] 

for _ in range(STEPS):
    all_actions = []

    for env in envs:
        if NEW_SEED_EVERY_STEP:
            # NOTE: none of these actually help.
            env.seed()
            # env.unwrapped.seed()
            # np.random.seed()
            # env.np_random.seed()

        action = env.action_space.sample()
        all_actions.append(action)

    unique_actions_taken = len(set(all_actions))
    
    # NOTE: if NEW_SEED_EVERY_STEP is false, you would expect this number to converge to 1 (over time environments tend to homogenenize the seeds)
    # however, if False, you would exapect this number to never converge to 1 because the seeds should be different before every step.
    print(unique_actions_taken)

    random_index = np.random.randint(0, N)
    another_random_index = np.random.randint(0, N)
    envs[random_index] = deepcopy(envs[another_random_index])
```

**Comment by pseudo-rnd-thoughts** [comment]
As the action spaces have their own unique source of randomness from the environment randomness you need to run
`env.action_space.seed()`

**Comment by nollied** [comment]
@pseudo-rnd-thoughts hah. nice, lol thanks that works.
