### ISSUE TITLE
[Proposal] please don't remove `env.seed`!

### ISSUE THREAD

**Issue by nollied** [openai/gym#2996]
### Proposal 

when calling `env.seed` in v0.25.0 i receive a deprecation notice: `DeprecationWarning: WARN: Function `env.seed(seed)` is marked as deprecated and will be removed in the future. Please use `env.reset(seed=seed)` instead.`

Please don't remove this function as it is important to be able to set seeds without resetting the environment for solutions that rely on distributed tree searching over a state space.

for example, a process may copy its state to another process if it found a promising state before the other process. if you have to reset the environment to choose a new seed, this means the processes will take the exact same path instead of divergent ones (or reset to the very beginning). hence, using `env.seed()`.

**Comment by balisujohn** [comment]
I'm personally fine with retaining env.seed, especially if there is explicit user demand for keeping it, but I'm curious to hear what others think, since it has long been set for deprecation. Interestingly, planned functional envs will solve this problem even without env.seed because functional step takes an prng state as a param, so you can mutate the same state into multiple next states by passing a different prng key. If env.seed does end up being removed, you can patch it into your own environments, I think just by copying the definition from the current version of core.py.

**Comment by pseudo-rnd-thoughts** [comment]
@nollied I understand what you mean but that seems like a very niche issue
Without `seed` you can change the seed through `env.np_random=rng` to a particular seed (in v24+) or `env.unwrapped.np_random=rng`

**Comment by nollied** [comment]
@pseudo-rnd-thoughts i wouldn't say it's niche, it's important for many variations of tree searching algorithms like MCTS at scale while remaining general. most planning algorithm implementations don't use openai gym, presumably because you need to build your own get_state and set_state methods for efficient state hopping (see [plangym](https://github.com/FragileTech/plangym))

**Comment by nollied** [comment]
@balisujohn interesting, i haven't heard of a functional envs. could you share resources so i can read up on this?

**Comment by balisujohn** [comment]
This PR might be of interest: https://github.com/openai/gym/pull/2958 This is not stable for the time being, so anything related to functional envs is subject to change.

**Comment by RedTachyon** [comment]
> most planning algorithm implementations don't use openai gym, presumably because you need to build your own get_state and set_state methods

That seems to be the crux of the matter for me - gym is already somewhat ill-suited for this purpose, so even if we bring back `env.seed` (which in turn causes problems for some other envs), it still won't be useful for planning algorithms. So I'd lean towards keeping the deprecation, since this way, the envs which already work well with gym, will work even better. And the envs which will get new problems this way, probably didn't use gym in the first place.

But yes, as John mentioned, you will probably get a better mileage from the functional API. It's currently in development, and at least for a few releases it will have an experimental status (i.e. breaking changes are likely to occur with no deprecation/transition period), but if there is demand, we can try to accelerate its stabilization. So take a look at #2958 and feel free to leave any comments on its structure

**Comment by nollied** [comment]
@RedTachyon what about `env.seed` breaks certain other environments? also wouldn't you expect the same opposite breakage to occur by removing the `env.seed` methods?

i write a lot of planning algorithms and personally i love using gym for them, it's such a nice interface and i hope that more emergent research on these topics will baseline/build environments in gym.

**Comment by RedTachyon** [comment]
> what about env.seed breaks certain other environments?

I believe the main issue was with Atari, where the RNG mechanism is sitting somewhere internally, and cannot just be modified in the middle of an episode. The only way to seed the env is right before/after resetting it. Essentially, if we say that environments should expose the `env.seed` method, then we know some of the popular envs won't be able to properly support it, and that's not good.

> is there a demand for checkpointing environments

I think it's possible to some extent (in general it is possible to pickle environments), but probably painfully slow. But I think that a functional style would pretty much make it trivial?

**Comment by balisujohn** [comment]
Why not have seed defined in core.py and throw a not-implemented error, unless implemented by the subclassing environment. Then atari envs and envs which similarly have unfriendly pseudorandom won't silently fail, but people can keep using env.seed if they want.

**Comment by RedTachyon** [comment]
That would defeat the point a little bit. The main feature of gym is the standard API, so in particular, I know that I can do
```python
env = gym.make("whatever-v0")
obs = env.reset(seed=0)
# alternatively, env.seed(0)
obs, reward, terminated, truncated, info = env.step(policy(obs))
```

and whatever the env is, this will work and be reproducible. The moment core features like this become optional, things start falling apart.

Also notice that in principle, people can use `env.seed` for their specific envs if they so choose - they just might need to implement it themselves, and it will likely not be supported by the popular open implementations (for which the standardization is extra important). But extending envs with custom features is always possible.

**Comment by nollied** [comment]
@RedTachyon there does seem to be a lot of interesting benefits from a functional environment style especially relevant to checkpointing and such. although, i can see environments being implemented in such a way where the benefits are nullified. namely, creating a stateful object that is passed around in the exact same way as OOP's `self` param as opposed to using a factorized "only pass what you need" type paradigm.

**Comment by nollied** [comment]
an alternative to keeping the `env.seed` function handy would be to add a couple methods to the interface which [plangym](https://github.com/FragileTech/plangym) exposes: `env.get_state` and `env.set_state`. but this suffers from the same issue you point out @RedTachyon regarding unimplemented methods causing downstream errors which disregard the principles of a unified API.

**Comment by RedTachyon** [comment]
@nollied to have a point of reference, if the functional API becomes stable/public (as an alternative to the main OOP API), would that work for your purposes with the planning algorithms? The state is passed around explicitly, so `get_state` and `set_state` are available for free.

**Comment by nollied** [comment]
@RedTachyon i don't see it really changing much for environments with internal RNG, even if all environments supported the functional API.

this issue probably isn't solve-able with any API mods, likely it has to be addressed on a case to case basis.

as an argument in principle, wouldn't you say it's inconsistent to deprecate env.seed in favor of env.reset(seed=...)? it would suffer the same problems you mentioned above about environments simply not using the seed parameter right?

there's no API level enforcement you can do that will stop people from leaving bits unimplemented. 

@balisujohn 's point about silent failing is spot on.
