### ISSUE TITLE
[Question] Clarification on Pendulum Coordinate System

### ISSUE THREAD

**Issue by shivaniraochepuri21** [openai/gym#2999]
### Question

The pendulum coordinate system is not clear, and the diagram mentioned in the comments of pendulum.py is not available in the master branch as far as I can see. Could you please clarify if theta is positive clockwise or anti-clockwise? When I test the Pendulum-v1 environment it seems to be positive anti-clockwise, but the image in assets is clockwise. Do correct me. Thanks.

**Comment by RedTachyon** [comment]
I beg you, use the "title" field the way it's intended, and put the content in the... content. Put at least a modicum of effort into asking the question if you want someone to answer it.

**Comment by pseudo-rnd-thoughts** [comment]
In the docstring for Pendulum it notes
```
    The diagram below specifies the coordinate system used for the implementation of the pendulum's
    dynamic equations.

    ![Pendulum Coordinate System](./diagrams/pendulum.png)

    -  `x-y`: cartesian coordinates of the pendulum's end in meters.
    - `theta` : angle in radians.
    - `tau`: torque in `N m`. Defined as positive _counter-clockwise_.
```

Therefore, Im assuming that `tau` will be influenced by `theta` and so it is "positive counter-clockwise" (ant-clockwise) so you are most likely correct

**Comment by vincentzhang** [comment]
`theta` is indeed positive counter-clockwise. It follows right-hand rule:
1. x axis points right and y axis points up, so the axis of rotation is z-axis and it points away from screen toward the viewer.
2. positive rotation is counter-clockwise around the axis of rotation.

See this for an illustration: https://www.evl.uic.edu/ralph/508S98/gif/rightx.gif

**Comment by shivaniraochepuri21** [comment]
Thank you @vincentzhang  and @pseudo-rnd-thoughts. Counterclockwise seems correct. Here, the upright position is considered as 0 degrees. Assuming no friction at the hinge, how to obtain/derive the dynamic equations considered in the pendulum.py environment? which are as follows:

state = [theta, theta_dot] 
d(theta) = theta_dot
d(theta_dot) = (3*g / 2*l) * sin(theta) + (3*u / m*l**2)

We may have to use lagrangian but I am not able to obtain the equation considered in the gym pendulum environment. Here is what I did to derive the equations. Please correct me anywhere.

let m be the mass, l be the length of the pendulum
let x,y be the coordinates of the free end of the pendulum, theta is the angle made by the free end in counter-clockwise direction about the fixed end. Let M be the moment of inertia about the fixed end of the pendulum which is (1/3)*m*l**2 
  
Then, x = l * sin(theta), y = l * cos(theta) 

Lagrangian L = 1/2 * m * v**2 + 1/2 * M * theta_dot **2 + PE

As the pendulum is going toward its equilibrium position (180 degrees) from the initial position (0 degrees), work done decreases as y decreases. So PE is Positive and is equal to m* g * l * cos(theta)

and v = (d/dt)(x)**2 + (d/dt)(y)**2

Using the euler-lagrangian equation: (do correct if anything is wrong)
d/dt [(d/d theta_dot) (L)] - (d/d theta) (L) = u ----- eq (1)
 
I obtained this: 
L = (2/3) * m * l**2 * theta_dot**2 + m*g*l*cos(theta)

from eq (1), we get theta_dot as:
theta_dot = 3u/(4ml**2) - 3g*sin(theta)/(4 * l)

Sorry about the possible inconsistency in notation. I am doubtful about the PE but either way I don't get the equation same as the one in gym. Please help me with this.
 
Thanks IA

**Comment by RedTachyon** [comment]
I went through the math in Pendulum like... a year ago? Anyways, it checked out, it's possible you'll find my derivation somewhere in old issues on this repo, though I'm not sure if I put it here in its entirety. I don't think I needed to use a Lagrangian, just regular solid body mechanics, but I don't have the capacity right now to go through your derivation. If you triple-check it and are confident that there's an issue with the implementation, please write it up with LaTeX syntax/rendering so that it's easier to parse, and I can go through it again.

One potential problem off the top of my head: L = T - V, but in your post, you add the potential energy. It might be a matter of the sign of the potential energy though.

**Comment by shivaniraochepuri21** [comment]
Thanks @RedTachyon I wasn't able to find relevant information in the old issues.
 
I added the potential energy in the lagrangian because, originally, L = KE - PE, here PE = m*g*l*cos(theta + 180) = - mlg cos(theta), therefore, finally you add the mlg*cos(theta) term in the lagrangian. Here, I am measuring the angle theta from the equilibrium postion. 

I am still not sure how to consider the potential energy and its reference (and if the equilibrium position has anything to do with it). Could you please provide an insight on this? Will update the equations in LaTex anyway soon, so u can go through them and correct me if I am wrong. 

Thanks IA

**Comment by shivaniraochepuri21** [comment]
> Thanks @RedTachyon I wasn't able to find relevant information in the old issues.
> 
> I added the potential energy in the lagrangian because, originally, L = KE - PE, here PE = m_g_l_cos(theta + 180) = - mlg cos(theta), therefore, finally you add the mlg_cos(theta) term in the lagrangian. Here, I am measuring the angle theta from the equilibrium postion.
> 
> I am still not sure how to consider the potential energy and its reference (and if the equilibrium position has anything to do with it). Could you please provide an insight on this? Will update the equations in LaTex anyway soon, so u can go through them and correct me if I am wrong.
> 
> Thanks IA

updated the derivation in previous comment. Please help me find the correct dynamics for this system. Thank you

**Comment by shivaniraochepuri21** [comment]
> > Thanks @RedTachyon I wasn't able to find relevant information in the old issues.
> > I added the potential energy in the lagrangian because, originally, L = KE - PE, here PE = m_g_l_cos(theta + 180) = - mlg cos(theta), therefore, finally you add the mlg_cos(theta) term in the lagrangian. Here, I am measuring the angle theta from the equilibrium postion.
> > I am still not sure how to consider the potential energy and its reference (and if the equilibrium position has anything to do with it). Could you please provide an insight on this? Will update the equations in LaTex anyway soon, so u can go through them and correct me if I am wrong.
> > Thanks IA
> 
> updated the derivation in previous comment. Please help me find the correct dynamics for this system. Thank you

I am implementing a model predictive controller with casadi for the pendulum system, and the evolution of state as the system tries to reach the target state is a decaying oscillation with the system I mentioned. I cannot see such a behavior with the dynamics equation implemented in gym (well, maybe that's not necessary, but it confirms the suggested dynamics are correct; how do I verify if the one provided in gym is correct? It would be great if someone can provide an old doc or method as to how we got the equation in gym). Keeping all the parameters, and changing just the equation, I can find the solution with the suggested dynamics but not with the one implemented in gym. I believe given how extensively useful gym is, the equation or some other settings/assumptions need to be looked at in Pendulum-v1 env, or please correct me if I am wrong. An RL agent may be trained for any non-linear equation of that form to do well in a test run, but MPC (and some optimal control methods, online methods) need the right model. Thanks IA

**Comment by RedTachyon** [comment]
![image](https://user-images.githubusercontent.com/19414946/187781712-c2879169-ce61-4d5e-9a69-8ca1ba5710a2.jpeg)

I did the math again, and it checks out again. Uploading the derivation in case of future questions. One thing I didn't properly check is how we actually represent the angle, but it's definitely something like theta, pi - theta, etc. But if this were wrong, the problem would be very apparent (the system have an equilibrium at the top or to either side)

@jkterry1 This can probably be closed, there might be a further discussion but I'm pretty sure there's no critical bugs here.

**Comment by ReHoss** [comment]
@RedTachyon 
Hi there, according to the literature (see H. K. Khalil - Nonlinear Systems (2001)), the motion is given by 

$\ddot{\theta} = - \frac{g}{l} \sin ( \theta )$

I don't get why there is no negative sign in the implementation of the acceleration $\ddot{\theta}$.
See this code snippet (generated by ChatGPT), adding the $-$ sign gives the right expected physical behaviour (infinite oscillation going back and forth from the starting point and passing by the origin $\theta = 0$ angle)...

![Image](https://github.com/user-attachments/assets/2b8f30c6-cbbc-4a01-a72e-44ee0ea22a94)

```python
import numpy as np
import matplotlib.pyplot as plt
from scipy.integrate import solve_ivp

# Define constants
g = 9.81  # Gravitational acceleration (m/s^2)
l = 1.0   # Length of pendulum (m)
m = 1.0   # Mass of pendulum (kg)
dt = 0.01  # Time step (s)

# External torque (constant for both systems)
def external_torque(t):
    return 0.0

def gym_pendulum_dynamics(t, y):
    theta, omega = y
    # Gym-like dynamics
    u = external_torque(t)
    dtheta_dt = omega
    domega_dt = (g / l * np.sin(theta) + u / (m * l**2))
    return [dtheta_dt, domega_dt]

def classical_pendulum_dynamics(t, y):
    theta, omega = y
    # Classical dynamics
    u = external_torque(t)
    dtheta_dt = omega
    domega_dt = (-g / l * np.sin(theta) + u / (m * l**2))
    return [dtheta_dt, domega_dt]

# Simulation parameters
time_span = (0, 10)  # Simulate for 10 seconds
t_eval = np.arange(0, 10, dt)  # Evaluation time points

# Initial conditions
initial_conditions = [1.6, 0.0] 

# Solve the Gym dynamics
sol_gym = solve_ivp(gym_pendulum_dynamics, time_span, initial_conditions, t_eval=t_eval)

# Solve the classical dynamics
sol_classical = solve_ivp(classical_pendulum_dynamics, time_span, initial_conditions, t_eval=t_eval)

# Extract results
t = sol_gym.t
theta_gym = sol_gym.y[0]
theta_classical = sol_classical.y[0]

# Plot the results
plt.figure(figsize=(10, 6))
plt.plot(t, theta_gym, label='Gym Formulation', linestyle='--')
plt.plot(t, theta_classical, label='Classical Formulation', linestyle='-')
plt.title('Comparison of Pendulum Dynamics: Gym vs Classical')
plt.xlabel('Time (s)')
plt.ylabel('Angle (rad)')
plt.legend()
plt.grid()
plt.show()


```

**Comment by vincentzhang** [comment]
"infinite oscillation going back and forth from the starting point and passing by the origin θ=0 angle", this description seems to assume that the lowest point corresponds to θ=0. However, in the Gym coordinate system, the lowest point is at θ=pi. So it seems to me that both curves on your plot check out in terms of the central point of oscillation. Mathematically, from the acceleration equation provided, sin(θ) = sin(θ'-pi) = -sin(θ') where θ' is the angle in gym coordinate system. The negative sign cancels out.

**Comment by ReHoss** [comment]
> "infinite oscillation going back and forth from the starting point and passing by the origin θ=0 angle", this description seems to assume that the lowest point corresponds to θ=0. However, in the Gym coordinate system, the lowest point is at θ=pi. So it seems to me that both curves on your plot check out in terms of the central point of oscillation. Mathematically, from the acceleration equation provided, sin(θ) = sin(θ'-pi) = -sin(θ') where θ' is the angle in gym coordinate system. The negative sign cancels out.

Exactly, I forgot that point.
