### ISSUE TITLE
OpenGL or GLFW render error

### ISSUE THREAD

**Issue by Xinyu-Wu-0000** [openai/gym#3003]
**Describe the bug**
I can not render a mujoco environment InvertedDoublePendulum-v4.

**Code example**
```python
import gym
IDP = gym.make('InvertedDoublePendulum-v4',new_step_api=True, render_mode="human")
IDP.reset()
IDP.step(IDP.action_space.sample())
IDP.render()
```

**System Info**
Describe the characteristic of your environment:
ubuntu 22.04 lts
gym installed via pip
python version 3.10.4

Package     Version
absl-py     1.2.0
autopep8    1.6.0
certifi     2022.6.15
cloudpickle 2.1.0
glfw        2.5.4
gym         0.25.1
gym-notices 0.0.7
imageio     2.20.0
install     1.3.5
mujoco      2.2.0
numpy       1.23.1
Pillow      9.2.0
pip         22.1.2
pycodestyle 2.8.0
PyOpenGL    3.1.6
setuptools  61.2.0
toml        0.10.2
wheel       0.37.1

**Additional context**

warning and error :
```
WARNING: OpenGL error 0x502 in or before mjr_makeContext
home/xinyu/spinning_up/Inverted_Double_Pendulum/envs/lib/python3.10/site-packages/glfw/__init__.py:906: GLFWError: (65537) b'The GLFW library is not initialized'
```

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for the issue, but I have tested on my mac and can't replicate the issue. 
I will try on ubuntu tomorrow

**Comment by Xinyu-Wu-0000** [comment]
I changed to x11 then it works. Looks like it won't work on wayland.
