### ISSUE TITLE
Acrobot-v0 not found (CartPole-v0 is OK)

### ISSUE THREAD

**Issue by yongduek** [openai/gym#301]
The env CartPole-v0 runs OK, however, Acrobot-v0 produces error. 
The error message suggested Acrobot-v1, and it worked well.

When I tried to upload the result with Acrobot-v1, an error was reported:

*This version of the environment is not registered on the server, but other versions exist. You may need to upgrade your version of gym. Env Acrobot-v1 not found (valid versions include ['Acrobot-v0'])*

**Comment by gdb** [comment]
This is expected — we've retired Acrobot-v0 and upgraded to Acrobot-v1!
