### ISSUE TITLE
[Bug Report] Action space seeding hangs due to memory constraints

### ISSUE THREAD

**Issue by olipinski** [openai/gym#3010]
**Describe the bug**
When seeding Dict action spaces, gym hangs.

**Code example**
```
from gym.spaces import Dict, Discrete, MultiDiscrete

space = Dict(a=Discrete(4), b=MultiDiscrete([6, 6, 6, 6, 6, 6]))

space.seed(1626)
```

**System Info**
Describe the characteristic of your environment:
 * Gym=0.21 (pip)
 * Windows 10 Enterprise H202
 * Python 3.9

**Additional context**
![image](https://user-images.githubusercontent.com/5785856/182115904-d6ef4fc5-709d-4c78-969a-f781cf505b60.png)

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by pseudo-rnd-thoughts** [comment]
The same memory issues can occur on mac, so this is not just a windows issues. 

As `np_random.choice()` will generate in memory `np.arange(2147483647)` this could be a speed issue as well.
In addition, in testing, as we use `np.iinfo(int).max` and the size of `int` can vary on different systems, @olipinski has `int32` and my mac has `int64`, any solution should use a standardised `np.intXX` value.
