### ISSUE TITLE
AttributeError: module 'numpy.random' has no attribute 'Generator'

### ISSUE THREAD

**Issue by bengadisoufiane** [openai/gym#3012]
get this bug when trying to use the gym model. AttributeError: module 'numpy.random' has no attribute 'Generator'

**Comment by balisujohn** [comment]
What's your gym version, and what operating system are you on?

**Comment by pseudo-rnd-thoughts** [comment]
Also what is your numpy version? The random generator API is relatively new I believe
Try running `pip install --upgrade numpy`
