### ISSUE TITLE
[Proposal] Update Table of Environments in wiki page

### ISSUE THREAD

**Issue by shivaniraochepuri21** [openai/gym#3030]
### Proposal 

The table of environments on the wiki page shows the last update in 2019 [Table of Environments](https://github.com/openai/gym/wiki/Table-of-environments)

### Motivation

Recently, Pendulum-v0 was deprecated and later made unavailable in the current stable gym version. It is still in the table of environments which might be misleading. Pendulum-v0 is updated to Pendulum-v1 which comes with changes (eg. seed function usage, updated dynamics equation, etc). For quick reference, the environment list page can be updated likewise.

### Pitch

Remove the environments that don't exist in the current stable version, and add the new environments

### Additional context

The closed [issue 106](https://github.com/openai/gym/issues/106) is relevant to this.

**Comment by pseudo-rnd-thoughts** [comment]
You can find up-to-date documentation at the website https://www.gymlibrary.ml/

**Comment by jkterry1** [comment]
The wikipage is no longer maintained and hasn't been for many years.

Also the documentation was recently moved to gymlibrary.dev
