### ISSUE TITLE
[Bug Report] Mujoco envs offscreen rendering error for width > 640 or height > 480

### ISSUE THREAD

**Issue by YouJiacheng** [openai/gym#3043]
Separately track issue "the size >500 making the environment crash" from https://github.com/openai/gym/issues/2989#issuecomment-1202214444 here, and describe it more precisely.

The cause is:
https://github.com/openai/gym/blob/6e2e921b5faaa9c356f589e4e938e718824c7d4a/gym/envs/mujoco/mujoco_rendering.py#L77-L78
https://github.com/openai/gym/blob/6e2e921b5faaa9c356f589e4e938e718824c7d4a/gym/envs/mujoco/mujoco_rendering.py#L63-L67
Precisely, `self.con.free()` will reset the struct(strangely, it will save and restore some fields) thus `con->offFBO` will be `0`, then
https://github.com/deepmind/mujoco/blob/090fe2db3f23ad608f833e3e8e9cb049e4daaa87/src/render/render_gl2.c#L37-L46
will set window buffer instead of offscreen buffer.
In principle, "[call ctx.free(), after which point it is the user’s responsibility to ensure that no further rendering calls are made on the context.](https://mujoco.readthedocs.io/en/latest/python.html#rendering)", we should create a new context after `free`.
## Fix
```python
  def update_offscreen_size(self, width, height):
      if width != self.con.offWidth or height != self.con.offHeight:
          self.model.vis.global_.offwidth = width
          self.model.vis.global_.offheight = height
          self.con.free()
          self.con = mujoco.MjrContext(self.model, mujoco.mjtFontScale.mjFONTSCALE_150)
          self._set_mujoco_buffers()
```
This snippet can fix this issue on `glfw`, but I wonder why `GLContext` with wrong `max_width` and `max_height`(since correct width and height is not passed to `_get_viewer`) doesn't cause any problem. (`egl` doesn't need it, but `glfw` need it)
@pseudo-rnd-thoughts

**Comment by pseudo-rnd-thoughts** [comment]
@rodrigodelazcano Do you understand this? 
@YouJiacheng Can you fix it?

**Comment by YouJiacheng** [comment]
I post the patch that can fix it. (without take care of viewer's width and height).
But I don't know why `GLContext` with wrong width and height doesn't cause any problem.

**Comment by YouJiacheng** [comment]
It is possible to initialize the width and height of the context and keep it constant. We only need to tweak the implementation, and it will also help avoid "`GLContext` with wrong width and height" problem.

By "`GLContext` with wrong width and height", see https://github.com/openai/gym/issues/2989#issuecomment-1225354628
i.e., `GLContext` is not initialize with correct width and height set by user, since width and height is not passed to `_get_viewer` creating the `GLContext`.

**Comment by rodrigodelazcano** [comment]
Got it, I see what you mean. I can't understand why it doesn't cause any problem but it looks like an issue on the Mujoco side. 

Since we don't require to change the width and height during runtime it would be great if you could make a PR that initializes the size of the offscreen renderer at initialization only.

**Comment by YouJiacheng** [comment]
Okay, let's just do semantically right things: Create `GLContext` with correct size at initialization, set `model.vis.global_.offwidth` and `offheight` at initialization, remove `width` and `height` parameter from `RenderContextOffscreen.render`. I will make a PR for it.
