### ISSUE TITLE
[Question] What is the best equivalent to the old Monitor object class?

### ISSUE THREAD

**Issue by DarthMalloc** [openai/gym#3045]
### Question

Given that the Monitor object class has been retired since 0.23, which object class is the ideal choice to replace it? The Monitor class does not seem to be mentioned anywhere in the docs.

**Comment by vwxyzjn** [comment]
`gym.wrappers.RecordVideo` and `gym.wrappers.RecordEpisodeStatistics`. See https://www.gymlibrary.dev/content/wrappers/ and an example usage [here at CleanRL](https://github.com/vwxyzjn/cleanrl/blob/e466f6efb251462de2b80f064133f32cb5d83e22/cleanrl/ppo.py#L85-L88)
