### ISSUE TITLE
[Question] RecordVideo funtion not saving any videos 

### ISSUE THREAD

**Issue by eak0mo** [openai/gym#3049]
### Question
when using the following syntax `test_env=record_video.RecordVideo(gym.make("BipedalWalker-v3",render_mode="rgb_array"),video_folder="",name_prefix="")`

for the RecordVideo function, there is a video file created that is immediately deleted and produces these warnings.
![image](https://user-images.githubusercontent.com/34249609/187370631-c5ca68a6-8db5-43a3-8c59-ab324ac64fdb.png)

**Comment by younik** [comment]
Regarding the first warning, you should specify a non-existing folder to get rid of it

The second one is tricky; Mujoco environments are rendering with different shapes after https://github.com/openai/gym/pull/2671
This is obviously a bug, I am investigating the cause; thanks for spotting this

**Comment by pseudo-rnd-thoughts** [comment]
@younik I don't seem to be able to replicate the issue

```python
env = gym.make("BipedalWalker-v3",render_mode="rgb_array")
for _ in range(10):
    env.reset()

    for _ in range(20):
        render = env.render()
        assert render.shape == (400, 600, 3), render.shape
        env.step(env.action_space.sample())

env.close()
```
Weirdly I found that the render image was (400, 600, 3) not (400, 620, 3)

I couldn't find the warning raised by any other env
```
for spec in gym.envs.registry.values():
    env = spec.make(render_mode="rgb_array")
    env = gym.wrappers.RecordVideo(env, video_folder="video", name_prefix=spec.id)

    env.reset()
    env.step(env.action_space.sample())
    env.close()
```
