### ISSUE TITLE
reward_range useless in core.py documentation

### ISSUE THREAD

**Issue by osigaud** [openai/gym#305]
A minor issue:

In the comments of gym/gym/envs/core.py, it is said:

 " And set the following attributes:

        action_space: The Space object corresponding to valid actions
        observation_space: The Space object corresponding to valid observations
        reward_range: A tuple corresponding to the min and max possible rewards"

but the last one is not present in the classic_control environments I watched

Shouldn't this be removed from the comments? Is it useful for some reward normalization mechanism in some agents?

**Comment by tlbtlbtlb** [comment]
It is there, defaulting to `[-inf, +inf]` in all released environments:
```
>>> import gym
>>> e=gym.make('CartPole-v0')
[2016-08-22 10:17:55,102] Making new env: CartPole-v0
>>> e.reward_range
(-inf, inf)
```
but some new environments do define a narrower range.

**Comment by osigaud** [comment]
Thanks. To me, this information should be added to the comment.
I believe this closes the issue.

**Comment by gdb** [comment]
Feel free to add that to the comment! Thanks!
