### ISSUE TITLE
Where can I find the fetch env python code?

### ISSUE THREAD

**Issue by TheDech** [openai/gym#3067]
Hi,

I am trying to locate the fetch python code and I am receiving a 404 error page.
Is there a way to retrieve a version of it?

Thank you

**Comment by balisujohn** [comment]
It seems like there's a fetch environment in gym-robotics https://github.com/Farama-Foundation/Gym-Robotics/tree/main/gym_robotics/envs

**Comment by TheDech** [comment]
@balisujohn Thank you!
