### ISSUE TITLE
[Question] Question about state setting

### ISSUE THREAD

**Issue by isluoshuang** [openai/gym#3069]
### Question

Can the state of environment be reset to a specified one?
Can we sample state-action pair which can reach a specified state?

**Comment by pseudo-rnd-thoughts** [comment]
Yes and no, `reset(seed=seed)` will let you reset your environment to a particular seed (or in older environments `env.seed(seed)`. 
However, if you want to reset to a particular state that you specify then this is not possible currently. You would have to investigate the environment's implementation. 

For the second question, yes if you set the seed then take a sequence of actions, for most environments, this will always result in the same action
