### ISSUE TITLE
Eval ennvironment is not working on my custom environment!!

### ISSUE THREAD

**Issue by muk465** [openai/gym#3074]
`import math
inf=math.inf
pi=math.pi

class NeuroRL4(gym.Env):
  metadata={ 'render.modes':['human','rgb_array'], 'video.frames_per_second':50 }
  def __init__(self,label_name):
    self.img_folder="/content/drive/MyDrive/final_label_image"
    self.img_path=os.path.join(self.img_folder,label_name)
    self.img_arr=nib.load(self.img_path).get_fdata()
    #self.img_arr=img.copy()
    #self.batches=batches
    
    #self.gravity=9.8
    
    self.min_action=-1
    self.max_action=1
    self.reward=0
    
    
    self.action_space=spaces.Box(low=self.min_action,high=self.max_action,shape=(1,))
    self.observation_space=spaces.Box(low=np.array([0,0,0,-inf,-inf,-inf,-inf]), high=np.array([255,255,255,inf,inf,inf,inf]), dtype=np.float32)
    
    self.rad_curvature=0.01
    self.insertion_depth=5
    self.action_model=bicycle_function(self.rad_curvature,self.insertion_depth)
    
    #self.initial=start_point
    self.reset_count=0
    self.max_insertion=150
    self.num_steps=0
    self.steps_to_reset=(self.max_insertion)//(self.insertion_depth)
    
    self.seed()
    self.viewer=None
    self.episodes_done_count=0
    
    self.start_point=start_point_generator(fs_file_name,fs_path,conform_T1_file_name,T1_path,visualise=False)
    self.goal_point= goal_point_generator(label_name)
  
  def seed(self,seed=None):
    self.np_random,seed=seeding.np_random(seed)
    return [seed]

  def reset(self):
    if self.episodes_done_count!=0 and self.episodes_done_count%10==0:
      self.start_point=start_point_generator(fs_file_name,fs_path,conform_T1_file_name,T1_path,visualise=False)

    if self.reset_count==0:
      x=self.start_point[0]
      y=self.start_point[1]
      z=self.start_point[2]
    
    else:
      x=self.start_point[0] +np.random.randint(-3,3)
      y=self.start_point[1] +np.random.randint(-3,3)
      z=self.start_point[2] +np.random.randint(-3,3)
    
    a2=np.array([0.,0.,0.,1.])
    a1=np.array([x,y,z],dtype=np.float32)
    
    s=np.append(a1,a2)
    s=np.array(s,dtype=np.float32)    
    self.state=s.copy()
    return self.state
    #self.reward=0

  def step(self,action):
    self.state_temp=self.state.copy()

    print(action)
    
    print("state",self.state)

    k=self.rad_curvature
    u1=self.insertion_depth
    
    #un normalise the action
    u2=math.pi*(action[0]+1)
    
    xi=self.state[0]
    
    yi=self.state[1]
    zi=self.state[2]
    
    qi1=self.state[3]
    qi2=self.state[4]
    qi3=self.state[5]
    qi4=self.state[6]
    
    

    curr_needle_mtx=self.action_model.homogenous_matrix(xi,yi,zi,qi1,qi2,qi3,qi4)
    next_needle_mtx=self.action_model.NeedleModelBicycle(curr_needle_mtx,k,u2,u1)
        
    xnew=next_needle_mtx[0,3]
    ynew=next_needle_mtx[1,3]
    znew=next_needle_mtx[2,3]
    
    rot_mtx=next_needle_mtx[0:3,0:3]
    ar=R.from_matrix(rot_mtx)
    Q=ar.as_quat()

    self.state_temp[0]=xnew 
    self.state_temp[1]=ynew
    self.state_temp[2]=znew
    
    self.state_temp[3]=Q[0]
    self.state_temp[4]= Q[1]
    self.state_temp[5]= Q[2]
    self.state_temp[6]= Q[3]
  
     
    print("tempstate: ",self.state_temp)

    self.new_state=self.state_temp.copy()
    
    done=False 
    self.num_steps+=1

    self.reward,done,res=state_reward_validator(self.img_arr,curr_state=self.state_temp,prev_state=self.state,reward=self.reward,num_steps=self.num_steps,steps_to_reset=self.steps_to_reset,done=done,goal_point=self.goal_point)
    
    
    if res == True:
      temp_state = self.reset()
      self.new_state= temp_state.copy()
      self.reset_count+=1
      self.num_steps=0
    self.state=self.new_state.copy()

    if self.reset_count==100:
      done=True
    #print("new",self.new_state)
    print("no of reset",self.reset_count)
    print("no of steps",self.num_steps)
    info={}
    if done==True:
      self.episodes_done_count+=1
      self.reset_count=0
    
    return self.state,self.reward,done,info

  def render(self):
    pass
  
  def close(self):
    pass
`    `

I am recieving this  error
![error_env](https://user-images.githubusercontent.com/69351880/188889669-4005ebb2-bdad-41e8-934d-04f5d680bf49.png)

**Comment by pseudo-rnd-thoughts** [comment]
It is difficult to tell what the issue or replicate your issue due to the code formatting. 
Could you edit the original post such that all of the code is readable and can reproduce the issue.
Secondly, as you can see from the error, this is an error originating from stable-baselines 3

**Comment by muk465** [comment]
Yea so I added 2 methods close and render to my environment so the error has changed to 
**he observation returned by the `reset()` method does not match the given observation space**
  
I changed this in  reset dtype to np.float32 as used i box.spaces
    a2=np.array([0.,0.,0.,1.])
    a1=np.array([x,y,z],dtype=np.float32)
    
    self.state=np.append(a1,a2)
    return self.state

why am i getting this error ,is this due to math.inf in  the box space?

**Comment by pseudo-rnd-thoughts** [comment]
`self.observation_space=spaces.Box(low=np.array([0,0,0,-inf,-inf,-inf,-inf]), high=np.array([255,255,255,inf,inf,inf,inf]), dtype=np.float32)`
Your state has 7 values while your obs space has 6

**Comment by muk465** [comment]
@pseudo-rnd-thoughts thanks i solved it by changing it to np.float32 but now a wierd error is popping 
![error_env](https://user-images.githubusercontent.com/69351880/188897227-0faf9cc6-891b-4906-b7b2-afb1a771f70d.png)

**Comment by muk465** [comment]
so is it issue of gym version? i am just importing gym in colab

**Comment by pseudo-rnd-thoughts** [comment]
You need to install a particular version of gym for stable baselines 3. Gym 25 has its own version of the `check_env` function

**Comment by muk465** [comment]
ok thanks ,I will try and see

**Comment by muk465** [comment]
Thanks it worked
