### ISSUE TITLE
How to convert timestep based learning to episodic learning

### ISSUE THREAD

**Issue by muk465** [openai/gym#3084]
### Question
I am using a custom environment to to path planning using ddpg algorithm , (i am using stable baslines3)

`model = DDPG("MlpPolicy", env, action_noise=action_noise, verbose=1)
model.learn(total_timesteps=10000, log_interval=1)
model.save("sb3_ddpg_model")`

here model.learn is used for timestep based learning but i want to convert it to certain like 3000 steps per episode and have multiple episodes,how can i achieve that?

**Comment by muk465** [comment]
@pseudo-rnd-thoughts any advice?

**Comment by pseudo-rnd-thoughts** [comment]
I'm not sure I understand what you are trying to achieve.
How do you believe the system currently works? 
This seems like a stable baselines issue rather than gym

**Comment by muk465** [comment]
yea thanks ,it was going for multiple episodes ,i was wrong
