### ISSUE TITLE
[Question] Baseline scores

### ISSUE THREAD

**Issue by ikamensh** [openai/gym#3087]
### Question

I need to quickly get an approx idea how good certain score in a given environment is.
What is a useful baseline for the score in an environment? I have an algorithm that achieves score of -900 +-200 in Pendulum-v1, and I wonder just how good is that. 

Do you think including a uniformly random agent score in environment documentation, plus maybe maximum and minimum score theoretically possible would be something useful? would be a nice addition to gymlibrary.dev documentation.

I know its asymmetric for different environments, but some baseline is needed. Next level would be some agreed basic RL algorithm benchmarked on all environments.

#### Maintaining it

There comes a question how this data would evolve over time. There could be a script to update these scores in a text file (.md file as a table?), such that it's directly searchable as represented by a web browser.

Or it can be just a reference file, and a test could check via regex that these are the same scores as given in all environment docs.

**Comment by araffin** [comment]
Hello,
what you are probably looking for is done in the RL Zoo : https://github.com/DLR-RM/rl-baselines3-zoo/blob/master/benchmark.md

Pretrained models and scores are also available on hf hub: https://huggingface.co/sb3/trpo-Pendulum-v1

**Comment by ikamensh** [comment]
Thanks for the link. This solves my problem.
