### ISSUE TITLE
[Bug Report] no attribute 'hash_seed' when using "ALE/Pong-v5"

### ISSUE THREAD

**Issue by gmarceaucaron** [openai/gym#3091]
**Describe the bug**
module 'gym.utils.seeding' has no attribute 'hash_seed' when using "ALE/Pong-v5"

**Code example**
```
import gym
env = gym.make("ALE/Pong-v5", render_mode="human")
env.close()
```

**System Info**

- pip install -U gym==0.26.0
- Ubuntu 22.04.1 LTS
- Python 3.9.12

**Additional context**
There was a warning in gym 0.25.2 saying:
`lib/python3.9/site-packages/gym/utils/seeding.py:159: DeprecationWarning: WARN: Function hash_seed(seed, max_bytes) is marked as deprecated and will be removed in the future.` The code calling this function seems to be inside the Pong environment.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by pseudo-rnd-thoughts** [comment]
Have you updated your ALE-py version? It should be 0.0.8, `pip install --upgrade ale-py`

**Comment by gmarceaucaron** [comment]
No, upgrading solved the problem. Thank you!
