### ISSUE TITLE
[Bug report] AtariPreprocessing pickle error.

### ISSUE THREAD

**Issue by vermouth1992** [openai/gym#3095]
**Describe the bug**
The AtariPreprocessing throws TypeError: cannot pickle 'ale_py._ale_py.ALEInterface' object when it trys to pickle the env instance.

**Code example**
```python
import gym
env = gym.make('ALE/Seaquest-v5')
env = gym.wrappers.AtariPreprocessing(env)
import pickle
pickle.dumps(env)
```

This is problematic if we try to serialize the environment. The problem is that the wrapper holds an ale instance. The fix is quite easy, just move
```python
self.ale = env.unwrapped.ale 
``` 
to a class property
```python
@property
def ale(self):
    return self.env.unwrapped.ale
``` 

I can submit a pull request if it helps.

**Comment by pseudo-rnd-thoughts** [comment]
Hi, thanks for the PR. Yes, could you make a PR that changes this

**Comment by vermouth1992** [comment]
I have submitted a PR [here](https://github.com/openai/gym/pull/3105)
