### ISSUE TITLE
[Bug Report] Taxi env no default render mode

### ISSUE THREAD

**Issue by guyazran** [openai/gym#3096]
**Describe the bug**
Taxi-v3 does fails if no render mode is provided and fails with uninformative error message. This is a severe breach in backward compatibility.

**Code example**
```python
import gym
env = gym.make('Taxi-v3')
env.reset()
env.render()

>>  AssertionError: Something went wrong with pygame. This should never happen.
```

** Suggested Solution **
set a default render mode then add a deprecation warning

**Comment by pseudo-rnd-thoughts** [comment]
What gym version are you using? 
If you are using v26 then you need to set the render mode
`gym.make("Taxi-v3", render_mode="human")`

We will look to adding a more helpful error message

**Comment by guyazran** [comment]
> What gym version are you using? If you are using v26 then you need to set the render mode `gym.make("Taxi-v3", render_mode="human")`

I am also using v26 and did exactly as you suggested, except I printed the ansi renderings (as before). 

> We will look to adding a more helpful error message

This would be of great help. I suggest setting some default render mode, preferably one that does not require a screen.
