### ISSUE TITLE
[Bug Report] Env_Specs attribute not found 

### ISSUE THREAD

**Issue by oofmeister27** [openai/gym#3097]
**Describe the bug**
I am playing around with this [repository](https://github.com/MishaLaskin/rad) and I keep getting this error when I run the training: 

 ```
File "train.py", line 318, in <module>
    main()
  File "train.py", line 200, in main
    frame_skip=args.action_repeat
  File "/home/anavani/anaconda3/envs/rad/lib/python3.7/site-packages/dmc2gym/__init__.py", line 28, in make
    if not env_id in gym.envs.registry.env_specs:
AttributeError: 'dict' object has no attribute 'env_specs'
```

**Code example**
The error seems to be coming from this line in __init__.py of dmc2gym: ```    if not env_id in gym.envs.registry.env_specs:```

**System Info**
- Dmc2Gym was installed with conda
- I am using Ubuntu 22.04
- Python version 3.7

**Comment by Chengyui** [comment]
I solved this error throught degrading the version of Gym from 0.26.0 to 0.19.0

**Comment by rickstaa** [comment]
For future reference, this change was implemented in https://github.com/openai/gym/pull/2748 and released under https://github.com/openai/gym/releases/tag/0.24.0.
