### ISSUE TITLE
What all changes should one do to convert a custom environment as a vectorised environment

### ISSUE THREAD

**Issue by muk465** [openai/gym#3099]
I have created a custom environment,below is small snippet of step function of my environment
 `def step(self,action):
    self.state_temp=self.state.copy()

    
    
    print("state",self.state)

    k=self.rad_curvature
    u1=self.insertion_depth
    
    #un normalise the action
    u2=math.pi*(action[0]+1)
    print("action",u2)
    xi=self.state[0]
    
    yi=self.state[1]
    zi=self.state[2]
    
    qi1=self.state[3]
    qi2=self.state[4]
    qi3=self.state[5]
    qi4=self.state[6]
    
    

    curr_needle_mtx=self.action_model.homogenous_matrix(xi,yi,zi,qi1,qi2,qi3,qi4)
    next_needle_mtx=self.action_model.NeedleModelBicycle(curr_needle_mtx,k,u2,u1)

    xnew=next_needle_mtx[0,3]
    ynew=next_needle_mtx[1,3]
    znew=next_needle_mtx[2,3]
    
    rot_mtx=next_needle_mtx[0:3,0:3]
    ar=R.from_matrix(rot_mtx)
    Q=ar.as_quat()

    self.state_temp[0]=xnew 
    self.state_temp[1]=ynew
    self.state_temp[2]=znew
    
    self.state_temp[3]=Q[0]
    self.state_temp[4]= Q[1]
    self.state_temp[5]= Q[2]
    self.state_temp[6]= Q[3]
  
     
    print("tempstate: ",self.state_temp)

    self.new_state=self.state_temp.copy()
    
    done=False 
    self.num_steps+=1
    
    self.reward,done,res,self.num_times_tum_reached=state_reward_validator(self.img_arr,curr_state=self.state_temp,prev_state=self.state,reward=self.reward,num_steps=self.num_steps,steps_to_reset=self.steps_to_reset,done=done,goal_point=self.goal_point,num_times_tum_reached=self.num_times_tum_reached)
    `
1)What i want to know is I am using stable baslines 3 and after reading vectorised env doc [https://stable-baselines3.readthedocs.io/en/master/guide/vec_envs.html](url)

2)Do i mak changes in the actions and rewards like put them in a loop for each env?

3)Or do i let my env be as it is in and use a wrapper?

**Comment by muk465** [comment]
`
# list of envs 
num_envs = 3
envs = [lambda: NeuroRL4(label_name) for i in range(num_envs)]

# Vec Env 
envs = DummyVecEnv(envs)

model = DDPG("MlpPolicy", envs, action_noise=action_noise, verbose=1)
model.learn(total_timesteps=1, log_interval=1)
model.save("sb3_envs_ddpg_model")
#env = model.get_env()`
I tried doing this and error says **you must use only one env when doing episodic training.**

**Comment by pseudo-rnd-thoughts** [comment]
For the Gym API, you should not need to modify your environment to vectorise it but for Stable Baselines 3 I have no idea. I would make an issue on their repo
