### ISSUE TITLE
The Mujoco package seems to be something wrong in the environment "xxx-v4"

### ISSUE THREAD

**Issue by Chris-Chow** [openai/gym#3103]
When I run gym.make("Humanoid-v4") or gym.make("Ant-v4"), there is a common bug:
AttributeError: module 'mujoco' has no attribute 'MjModel'
The version of gym I use is 0.26.2. Does anyone know how to fix it? QwQ
BTW, it's OK to make the "v2" version of mujoco environment.

**Comment by pseudo-rnd-thoughts** [comment]
What is your `mujoco` version? If you try uninstalling then reinstalling mujoco does that fix it?
