### ISSUE TITLE
ctrlrange [-.4, .4] to [-1, 1] ?

### ISSUE THREAD

**Issue by cachett-ML** [openai/gym#3104]
Hi,

Using RL algorithms it is common practice to output actions normalized in [-1, 1]. So why do we set ctrlrange to [-.4, .4] in the XML file as below?

https://github.com/openai/gym/blob/e055ee7b8e7a95d5cb41c2cb5bfd3603c67b516c/gym/envs/mujoco/assets/humanoid.xml#L6

Best,
Théo

**Comment by RedTachyon** [comment]
FWIW I don't think there's anyone here who can give you a satisfying answer to this beyond an educated guess, the current team didn't design the mujoco envs, and since it's fundamentally a ~meaningless design choice, reverse engineering this decision is unlikely
