### ISSUE TITLE
[Bug Report] importlib-metadata version 5 removed entrypoints

### ISSUE THREAD

**Issue by rusu24edward** [openai/gym#3110]
If you are submitting a bug report, please fill in the following details and use the tag [bug].

**Describe the bug**
importlib-metadata version 5 removed entrypoints, which causes gym registration to fail. Either update the registration code or adjust the requirement.

**Code example**
```
  File "/lib/python3.7/site-packages/gym/envs/registration.py", line 250, in load_env_plugins
    for plugin in metadata.entry_points().get(entry_point, []):
AttributeError: 'EntryPoints' object has no attribute 'get'
```

**System Info**
Describe the characteristic of your environment:
 * Describe how Gym was installed (pip, docker, source, ...): pip install gym==0.21.1
 * What OS/version of Linux you're using. Note that while we will accept PRs to improve Window's support, we do not officially support it: mac os 10.15.17
 * Python version: 3.7.9

**Additional context**

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by pseudo-rnd-thoughts** [comment]
If you using an old version of gym then you will need to downgrade the importlib metadata project to <5
I don't have an issue with importlib metadata 5 with gym v26.1
