### ISSUE TITLE
[Question] How do we make an environment use a config file to change the parameters

### ISSUE THREAD

**Issue by sushant1212** [openai/gym#3117]
### Question

Hi,
I have an environment and it has a config file for controlling various parameters of the environment. I was using gym version `0.21.0` and it was working fine, but recently I upgraded it to the latest version, and it threw errors. The error that was thrown was that `observation_space` was not found, even though I specify the observation_space in a variable. On further inspection, I found out that during `gym.make()` it actually calls `hasattr(env, "observation_space")` in `PassiveEnvChecker` class, and since the observation_space variable uses some class variables that are initialised as None, `hasattr` returns False. The variables that are initialised as None would be replaced with the values from the config file. 

So as of now this is the order that I am using:
```python
env = gym.make("EnvName-v0")
# calling a defined method called configure that would initialise the class parameters
env.configure("path to config file")
obs = env.reset()
```

So since the configure method is called after the `gym.make` the variables are still None when the `PassiveEnvChecker` calls `hasattr`. My question is that is there any other format in which it is expected to pass the config file? As much as I understand, the `gym.make` method does not take in any arguments (correct me if I am wrong here).

I would really appreciate your help here. Thank you!

**Comment by pseudo-rnd-thoughts** [comment]
Interesting question. You have two options
1. Specify the configurations within `make`, for example, you can run `gym.make("EnvName-v0", config_file="filename")` where the config_file will be passed to the environment. I would recommend this as the solution if the configuration doesn't change during the runtime of the environment
2. Disable the environment checker, passing `disable_env_checker=True` within `make` (`gym.make("EnvName-v0", disable_env_checker=True)`) should disable the environment checker and if this is a permanent thing, the same parameter exists within `gym.register` that should be used by default in `gym.make` unless `disable_env_checker=False` is specified

**Comment by sushant1212** [comment]
Thanks for the quick response. I'll try to work with one of the solutions.
