### ISSUE TITLE
[Bug Report] importlib-metadata v5.0 breaks registration.py

### ISSUE THREAD

**Issue by sidney-tio** [openai/gym#3119]
If you are submitting a bug report, please fill in the following details and use the tag [bug].

**Describe the bug**
After `importlib_metadata` update on 2nd Oct, `metadata.entry_points().get()` is deprecated and breaks registration.py.

**Code example**
With the latest installation, `import gym` already produces the error:

![image](https://user-images.githubusercontent.com/35787241/194386564-a7cf7ceb-94cb-4ec5-8554-42f1d4942b35.png)

**System Info**
Describe the characteristic of your environment:
 I installed a fresh version of stable_baselines3 which uses gym 0.21. Currently tried running on colab, with python version 3.7.14 

**Additional Info**
The importlib_metadata devs are already discussing the issue here at https://github.com/python/importlib_metadata/issues/409

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by sidney-tio** [comment]
suggestion to either

1) update setup.py to use `importlib-metadata < 5.0` 
or 
2) update registration.py to use `metadata.entry_points(group = entry_point)`

**Comment by francescomaldonato** [comment]
Follow up. Please try to solve this quickly.
I am developing a thesis on RL with OpenAI gym and this kinda blocks me :(
Contact me for any help or suggestion.

**Comment by sidney-tio** [comment]
@francescomaldonato as a temp solution, you can downgrade importlib-metadata via  `pip install importlib-metadata==4.11.3`

**Comment by francescomaldonato** [comment]
Thank you for the quick answer @sidney-tio, I also used as a workaround solution the previous version of gym==0.20.0.

**Comment by pseudo-rnd-thoughts** [comment]
Gym v0.21 is over a year old which is why you are getting this issue. 
We are hoping that SB3 updates to the latest gym version soon to solve this issue

**Comment by sidney-tio** [comment]
Thanks! I think the SB3 team is aware of it already.
