### ISSUE TITLE
AttributeError: 'EntryPoints' object has no attribute 'get'

### ISSUE THREAD

**Issue by Daiiszuki** [openai/gym#3122]
`import gym` returns A`ttributeError: 'EntryPoints' object has no attribute 'get'`

**Code example**
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-2-c727ea424a25>](https://localhost:8080/#) in <module>
----> 1 import gym

2 frames
[/usr/local/lib/python3.7/dist-packages/gym/__init__.py](https://localhost:8080/#) in <module>
     11 )
     12 from gym.spaces import Space
---> 13 from gym.envs import make, spec, register
     14 from gym import logger
     15 from gym import vector

[/usr/local/lib/python3.7/dist-packages/gym/envs/__init__.py](https://localhost:8080/#) in <module>
      8 
      9 # Hook to load plugins from entry points
---> 10 _load_env_plugins()
     11 
     12 

[/usr/local/lib/python3.7/dist-packages/gym/envs/registration.py](https://localhost:8080/#) in load_env_plugins(entry_point)
    248 def load_env_plugins(entry_point="gym.envs"):
    249     # Load third-party environments
--> 250     for plugin in metadata.entry_points().get(entry_point, []):
    251         # Python 3.8 doesn't support plugin.module, plugin.attr
    252         # So we'll have to try and parse this ourselves

AttributeError: 'EntryPoints' object has no attribute 'get'
**System Info**
Describe the characteristic of your environment:
 * Describe how Gym was installed (pip, docker, source, ...)
 * What OS/version of Linux you're using. Note that while we will accept PRs to improve Window's support, we do not officially support it.
 * Python version

**Additional context**
Restarting the runtime gets the issue sorted, but after reinstalling 
`Requirement already satisfied: gym>=0.17 in /usr/local/lib/python3.7/dist-packages (from finrl==0.3.5) (0.21.0)`

the error reappears. What are some possible reasons/solutions/.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by pseudo-rnd-thoughts** [comment]
You need to downgrade entry_points, entry_points >= 5 causes the issue
`pip install --upgrade entry_points<5`

**Comment by Daiiszuki** [comment]
Solved. thank you @pseudo-rnd-thoughts

**Comment by ashok-arora** [comment]
@pseudo-rnd-thoughts I am facing the same error but entry_points package is not available:
```
(base) ashok@mini gym-gridverse % pip install --upgrade 'entry_points<5'
ERROR: Could not find a version that satisfies the requirement entry_points<5 (from versions: none)
ERROR: No matching distribution found for entry_points<5
```

**Comment by FedeCuci** [comment]
I'm having the same error as @ashok-arora

**Comment by gsavarela** [comment]
@ashok-arora @FedeCuci I was having the same issue. Following the [bread crumbs](https://packaging.python.org/en/latest/specifications/entry-points/) in the internet the problem is actually on the `importlib-metadata` package. The fix that worked for me was downgrading to version 4.13.0:

```
 pip install importlib-metadata==4.13.0
```
