### ISSUE TITLE
sim2real using OpenAI gym

### ISSUE THREAD

**Issue by ddharshan** [openai/gym#3123]
Hi
I have created a customized Gym environment and trained the agent. However, i am just wondering how to transfer the trained model from simulation to real world. Is there any successful research available for sim2real using OpenAI gym?

**Comment by ddharshan** [comment]
> Hi I have created a customized Gym environment and trained the agent. However, i am just wondering how to transfer the trained model from simulation to real world. Is there any successful research available for sim2real in OpenAI gym?

**Comment by pseudo-rnd-thoughts** [comment]
Hey, we just launched [gymnasium](https://github.com/Farama-Foundation/Gymnasium), a fork of Gym by the maintainers of Gym for the past 18 months where all maintenance and improvements will happen moving forward. Could you please move this over to the new repo?

If you'd like to read more about the story behind the backstory behind this and our plans going forward, click [here](https://farama.org/Announcing-The-Farama-Foundation).
