### ISSUE TITLE
[action_space]How to change the action_space.low or action_space.high of my own model?

### ISSUE THREAD

**Issue by Woodeeer** [openai/gym#3124]
When I use the model "Humanoid-v3", I can use
print(env.action_space)
and get the result:
Box(-0.4, 0.4, (17,), float32).

But when I change the model to my own, the result:
Box(0.0, 0.0, (8,), float32), and the result stop my simulate.

So, I want to know how to change the action_space.low or action_space.high of my own model?

**Comment by pseudo-rnd-thoughts** [comment]
Could you provide some basic code for your environment? 
It looks like the `action_space` of all mujoco environment is determined by the `BaseMujocoEnv._set_action_space`, I would look here first

**Comment by Woodeeer** [comment]
> Could you provide some basic code for your environment? It looks like the `action_space` of all mujoco environment is determined by the `BaseMujocoEnv._set_action_space`, I would look here first

Sorry but where can I find the BaseMujocoEnv._set_action_space code?

**Comment by pseudo-rnd-thoughts** [comment]
In Gym v26.2, in mujoco_env.py contains `BaseMujocoEnv` with a function `_set_action_space` that all of the environments call in their `__init__`

**Comment by Woodeeer** [comment]
Ok, I have solved the problem by modifying the xml documentation
