### ISSUE TITLE
AsyncVectorEnv is slow

### ISSUE THREAD

**Issue by linshuxi** [openai/gym#3125]
### Question

Hello, thanks for the great work!
I found that AsyncVectorEnv is much slower with respect to normal one.

The following code give some confusing results,

```
if __name__ == "__main__":
    res = gym.vector.AsyncVectorEnv([lambda :gym.make("CartPole-v1")] * 5)
    res.reset()

    s = time.time()
    res.step(np.array([0,0,0,0,0]))
    e = time.time()

    print('time',e - s)

    res2 = [gym.make("CartPole-v1") for _ in range(5)]
    for item in res2:
        item.reset()

    s = time.time()
    for item in res2:
        item.step(0)
    e = time.time()
    print('time2',e - s)
```

The results:
time 0.0024688243865966797
time2 0.00013899803161621094

It seems that AsyncVectorEnv is ten times slower than the normal one, which makes me confused.

**Comment by pseudo-rnd-thoughts** [comment]
You are possibly correct but you would need compute the difference over a large number of samples.

Vector environments is helpful for neural network which are more efficient when computing a batch of observation allowing for more actions per seconds. 

We are aware that the Gym vector implement is not that efficient, we recommend you using EnvPool if you need max speed

**Comment by linshuxi** [comment]
> You are possibly correct but you would need compute the difference over a large number of samples.
> 
> Vector environments is helpful for neural network which are more efficient when computing a batch of observation allowing for more actions per seconds.
> 
> We are aware that the Gym vector implement is not that efficient, we recommend you using EnvPool if you need max speed

many thanks!
