### ISSUE TITLE
[Question] Can we redefine the reward space?

### ISSUE THREAD

**Issue by Mouse-Diplodicus** [openai/gym#3129]
### Question

Hi, I'm currently working on a custom environment for gym and I was wondering if we are limited to keeping the reward as a float or if we could use an array of floats instead for example. Also, I see the base env class has a 'reward_range' variable, would this need to be modified in this case?

Thanks for the responses

**Comment by balisujohn** [comment]
The impression I get is that reward_range is basically for telling other libraries that use gym what range to expect rewards in for a particular environment. I don't think changing the return type of reward in a custom env will break any gym internal logic, though wrappers and RL libraries that use gym probably expect reward as a single float. You could consider using a Reward Wrapper if you need to convert your non-float reward into a float to make your custom env compatible with standard RL libraries, but still want a custom env that has a non-float reward return type.

**Comment by pseudo-rnd-thoughts** [comment]
@Mouse-Diplodicus Gym assumes that the reward return type will be an integer or a float. 

I would keep this as the total reward returned by a step then include in the `info` parameter your array of floats. 
This will allow you to use both the internal gym `check_env` to use if your environment is correct and other gym wrappers. 
Though you could add a wrapper to change the reward to be the info data.

**Comment by Mouse-Diplodicus** [comment]
> @Mouse-Diplodicus Gym assumes that the reward return type will be an integer or a float.
> 
> I would keep this as the total reward returned by a step then include in the `info` parameter your array of floats. This will allow you to use both the internal gym `check_env` to use if your environment is correct and other gym wrappers. Though you could add a wrapper to change the reward to be the info data.

That makes sense, Thanks!
