### ISSUE TITLE
[Bug Report] passive_env_step_check() cant handle observation_space being a dict

### ISSUE THREAD

**Issue by Wajktor** [openai/gym#3130]
**Describe the bug**
If a custom environment has an observation_space being a dict, the passive_env_step_check(env, action) attempts `if np.any(np.isnan(obs)):`, however this is invalid and throws an error.

**Code example**
```
        self.observation_space = spaces.Dict(
            {
                "Observation": spaces.Box(low = -np.inf, high = np.inf, shape=(10,), dtype=np.float32),
            }
        )
```

**System Info**
OS: Ubuntu 20.02
Python version: 3.8.10
Gym version: 0.26.2

Gym installed via pip

**Comment by pseudo-rnd-thoughts** [comment]
I know that there was an issue with the line presented however this was in v24 I believe but you claim to use v26

```python
class TestEnv(gym.Env):

    def __init__(self):
        self.observation_space = spaces.Dict(
            {
                "Observation": spaces.Box(low=-np.inf, high=np.inf, shape=(10,), dtype=np.float32),
            }
        )
        self.action_space = spaces.Discrete(5)

    def reset(self, *, seed: Optional[int] = None, options: Optional[dict] = None) -> Tuple[ObsType, dict]:
        super().reset(seed=seed, options=options)
        return self.observation_space.sample(), {}

    def step(self, action: ActType) -> Tuple[ObsType, float, bool, bool, dict]:
        return self.observation_space.sample(), 0, False, False, {}


env = TestEnv()
env = PassiveEnvChecker(env)
env.reset()
env.step(env.action_space.sample())
```
I can run this code using v26.2 and not get an issue. 
Does this example work for you?

**Comment by Wajktor** [comment]
The code snippet is missing all proper import statements, could you include them as well?

**Comment by Wajktor** [comment]
Sorry, this was indeed an issue with gym version 24.x, there was a version mismatch in my project.
Works with version 26!
