### ISSUE TITLE
Environment Pong doesn't exist. 

### ISSUE THREAD

**Issue by IshitaB28** [openai/gym#3131]
I have been trying to make the Pong environment. Neither Pong nor PongNoFrameskip works. I also could not find any Pong environment on the github repo.

**Comment by pseudo-rnd-thoughts** [comment]
Have you installed atari? `pip install "gym[atari, accept-rom-license]"`. Atari is part of a separate repo

**Comment by IshitaB28** [comment]
I had installed gym[atari]. That did not work! Could you share the repo link please!

**Comment by pseudo-rnd-thoughts** [comment]
You also need to run gym[accept-rom-license] as the atari install does not automatically install the roms 
https://github.com/mgbellemare/Arcade-Learning-Environment

**Comment by IshitaB28** [comment]
Hi, thanks a lot! This worked!

**Comment by ParisaO** [comment]
> You also need to run gym[accept-rom-license] as the atari install does not automatically install the roms https://github.com/mgbellemare/Arcade-Learning-Environment

Hi,
I am trying to run a code and I am getting this error:
```
File "/usr/local/lib/python3.10/dist-packages/gymnasium/envs/registration.py", line 380, in _check_name_exists
    raise error.NameNotFound(
gymnasium.error.NameNotFound: Environment `PongNoFrameskip` doesn't exist.
```
So I guess that I need to install the ROM file for the pong game, but I can't find the steps. I am confused how to install it. Could you help me?

edit: Solved by this command
`!pip install "gymnasium[atari, accept-rom-license]"`

**Comment by deep1305** [comment]
> > You also need to run gym[accept-rom-license] as the atari install does not automatically install the roms https://github.com/mgbellemare/Arcade-Learning-Environment
> 
> Hi, I am trying to run a code and I am getting this error:
> 
> ```
> File "/usr/local/lib/python3.10/dist-packages/gymnasium/envs/registration.py", line 380, in _check_name_exists
>     raise error.NameNotFound(
> gymnasium.error.NameNotFound: Environment `PongNoFrameskip` doesn't exist.
> ```
> 
> So I guess that I need to install the ROM file for the pong game, but I can't find the steps. I am confused how to install it. Could you help me?
> 
> edit: Solved by this command `!pip install "gymnasium[atari, accept-rom-license]"`

Thanks a lot.

**Comment by Emanuel-de-Jong** [comment]
Now that gymnasium 1.0 is out and a lot of rl frameworks don't support it, you might need to specify the version:
`
pip install "gymnasium[atari,accept-rom-license]==0.29.1"
`
Due to a dependency this only works on python 3.11 and lower!
