### ISSUE TITLE
[Bug Report] Enviornment Not Closing macOS Monterey 

### ISSUE THREAD

**Issue by Mukilan-Krishnakumar** [openai/gym#3132]
This is in reference to a previous issue #2160, @jkterry1 seemed to have closed the issue, but I ran into the same problem. 

I am encountering the same error as #2160 whenever I close an environment on gym 0.21.0 and macOS Monterey 12.6, the render window doesn't close, even after using `env.close()`. I am running this from a Jupyter Notebook and every time I Force Quit the render window, my kernel dies. 

I am working on a simple CartPole experiment. 

Here is the code: 
```python
environment_name = 'CartPole-v0'
env = gym.make(environment_name)
episodes = 5
for episode in range(1, episodes+1):
state = env.reset()
done = False
score = 0
while not done:
env.render()
action = env.action_space.sample()
n_state, reward, done, info = env.step(action)
score += reward
print(f'Episode : {episode} Score : {score}')

env.close()
```

Here is a picture of my render window, frozen and unresponsive. 
<img width="813" alt="image" src="https://user-images.githubusercontent.com/71809485/197134312-202a54d2-de53-4be6-bd8a-222af75fb007.png">

**Comment by Mukilan-Krishnakumar** [comment]
Upgrading to the latest versions doesn't seem to resolve the error. 
I upgraded to Gym=0.26.2, then ran the same code with some minor changes (added `render_mode`)

```python
environment_name = 'CartPole-v1'
env = gym.make(environment_name,render_mode = 'human')

episodes = 5
for episode in range(1, episodes+1):
    state = env.reset()
    done = False
    score = 0
    while not done:
        env.render()
        action = env.action_space.sample()
        n_state, reward, done, trunc, info = env.step(action)
        score += reward
    print(f'Episode : {episode} Score : {score}')
env.close()
```

The environment does seemingly close, but when I rerun the cell for a new demonstration, the following error is thrown. 
```
File ~/.pyenv/versions/zenml/lib/python3.8/site-packages/gym/envs/classic_control/cartpole.py:295, in CartPoleEnv.render(self)
    292 gfxdraw.hline(self.surf, 0, self.screen_width, carty, (0, 0, 0))
    294 self.surf = pygame.transform.flip(self.surf, False, True)
--> 295 self.screen.blit(self.surf, (0, 0))
    296 if self.render_mode == "human":
    297     pygame.event.pump()

error: display Surface quit
```
Does it have something to do with the fact that I am running this with Rosetta from an M1 Mac? Should I just Force Quit the application?  

Using the latest version of Gym also introduces dependency issues with Stable Diffusion :(

**Comment by Mukilan-Krishnakumar** [comment]
Update: I ran the whole code natively (on M1 ARM). I am able to replicate the same error, even with the latest version of Gym. 

It displays the same error: `error: display Surface quit`

**Comment by andrewtanJS** [comment]
Did you rerun the entire cell including the `gym.make()`? If you call `env.close()`, you'll need to reinitialise the environment by using `env = gym.make(environment_name, render_mode = 'human')` again.

For me, running your code above in one cell works on M2 ARM and Jupyter Notebook.

**Comment by Mukilan-Krishnakumar** [comment]
Oh Yes!! I ran `gym.make` and `env.close` in different blocks. It does work when they are both in the same code block. 
Thanks @andrewtanJS, Appreciate your help!! 

To folks who are directed here in the future, Stable Baselines3 hasn't caught up with the latest gym versions. To work with Stable_Baselines3, we need to downgrade gym to 0.21.0 (As of October 2022). You can read the changelogs [here](https://stable-baselines3.readthedocs.io/en/master/misc/changelog.html). Hopefully, they will upgrade gym version soon!!

**Comment by yigtkaya** [comment]
I run into the same problem env.close doesn't work
