### ISSUE TITLE
gym.wrappers.RecordVideo not recording any videos anymore in 0.26.x

### ISSUE THREAD

**Issue by SebastianHurubaru** [openai/gym#3140]
Hello,

since the change in 0.26.0 of the render_mode flag, the gym.wrappers.RecordVideo does not work anymore. 

When recording the video we are getting the following log message: 

`.../lib/python3.8/site-packages/gym/wrappers/monitoring/video_recorder.py:59: UserWarning: WARN: Disabling video recorder because environment <OrderEnforcing<PassiveEnvChecker<AtariEnv<ALE/Pong-v5>>>> was not initialized with any compatible video mode between `rgb_array` and `rgb_array_list``

We are setting the render_mode when creating the environment, as showed in the [blog](https://younis.dev/blog/render-api/) for the 0.26.0 release, but the render_mode flag no longer gets set, leading to the warning and videos not being recorded.

Here is a code sample that can help with the issue replication:

`
import gym

env = gym.make("ALE/Pong-v5", render_mode="rgb_array")

env = gym.wrappers.RecordVideo(
    env,
    video_folder='video',
    step_trigger=lambda x: x % 100 == 0
)

env.reset()
for t in range(100):
    action = env.action_space.sample()
    observation, reward, terminated, truncated, info = env.step(action)

env.close()

`

Currently on Gym 0.26.2 and Python 3.8.10.

Please let me know in case you need additional info.

**Comment by pseudo-rnd-thoughts** [comment]
Hey, we just launched [gymnasium](https://github.com/Farama-Foundation/Gymnasium), a fork of Gym by the maintainers of Gym for the past 18 months where all maintenance and improvements will happen moving forward. Could you please move this over to the new repo?

If you'd like to read more about the story behind the backstory behind this and our plans going forward, click [here](https://farama.org/Announcing-The-Farama-Foundation).
