### ISSUE TITLE
[Bug Report] Unexpected time between environment step function calls

### ISSUE THREAD

**Issue by jameszampa** [openai/gym#3141]
### Bug description
I have a custom gym environment for fighting the Tree Sentinel from Elden Ring and I will sometimes get upwards of 20+ seconds between step function calls.

### Time between step calls
![image](https://user-images.githubusercontent.com/36577736/199007321-00c8cd85-5694-4a2c-8856-bc1445bcc4c8.png)

### Step time
![image](https://user-images.githubusercontent.com/36577736/199007896-8e1aec79-2b19-40bf-9f15-c6818a7c6e55.png)

### Code
https://github.com/jameszampa/EldenRingAI

EldenEnv.py is where the custom environment code is
EldenReward.py is where I compute all of my rewards
play_elden_ring.py is a Flask server where elden ring is actually played and keys are pressed

### System Info for Running Gym Environment
 * Conda environment, gym version 0.21.0
 * Ubuntu 20.04
 * Python3.9

### Additional context
I can't seem to identify reasons behind why the time between steps is occasionally very high. To me it seems random.
Also please let me know if this is an issue with stable_baselines3 and not gym
[Clip of bug happening](https://www.twitch.tv/eldenringai/clip/ExpensiveLightAlligatorSmoocherZ-ljP052lKHkF4xGm9)

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by jameszampa** [comment]
https://github.com/DLR-RM/stable-baselines3/issues/1147

**Comment by pseudo-rnd-thoughts** [comment]
I would be fairly confident that gym itself is not causing this as we run performance runs and I haven't noticed this before. I would suspect that this is more an issue with the flask server or sb3

**Comment by jameszampa** [comment]
Yeah I kinda thought the same thing, thanks for the reply tho
