### ISSUE TITLE
[Question] Some question about the attr {._max_episode_steps}

### ISSUE THREAD

**Issue by Aidilele** [openai/gym#3142]
I can get the attr `._max_episode_steps` when I use the version `gym==0.18.0` in `PongNoFrameskip-v4`,but in `gym version 0.26.0`,this attr has gone.I want to know how can I get this attr when I use `gym version == 0.26.0`

 
<img width="320" alt="p1" src="https://user-images.githubusercontent.com/115619013/199386731-cb9d75c3-e694-48ae-a47c-2fa1fb7cb62a.png">
<img width="884" alt="p2" src="https://user-images.githubusercontent.com/115619013/199387042-b8b7e5ae-0858-4b1d-904d-3ea2cacde54f.png">

**Comment by pseudo-rnd-thoughts** [comment]
`env.spec.max_episode_steps` will be the easier way

**Comment by Aidilele** [comment]
> `env.spec.max_episode_steps` will be the easier way

Thanks！
