### ISSUE TITLE
[Question] New API seed.

### ISSUE THREAD

**Issue by spyroot** [openai/gym#3146]
Hi Folks,

Q1) I'm porting some of the env to the new API.
Do I understand correctly? With new API 
env = gym.make(gym_id)

Is it sufficient to call a reset(seed=some_seed), which should set a seed?

```
  env.reset(seed=seed)
  #env.seed(seed)
  #env.action_space.seed(seed)
  #env.observation_space.seed(seed)
```

Q2) I was trying to find an exact semantic behind a truncate. Could you please share?
(I believe other folks will find it helpful as well) :) ty

**Comment by pseudo-rnd-thoughts** [comment]
1. `env.reset(seed=seed)` should run behind the scenes the same code as `env.seed(seed)`
2. To seed your action space (there shouldn't be any point to seeding the observation space) you will need to call `env.action_space.seed(seed)`
3. We are planning on writing this up into a full blog post but here a draft of the reasoning https://github.com/pseudo-rnd-thoughts/gym/issues/1

**Comment by spyroot** [comment]
Thank you very much.    But I guess what is not very clear.

```
If during construction caller provide Iterator[Callable[[], Env]]

gym.vector.SyncVectorEnv(env_creator) 

Where env_creator already yields some env with seed.
envs = gym.vector.SyncVectorEnv(env_creator)

Down the line 
caller call 
next_obs, infos = self.envs.reset()
```

My understanding is that during the creation of batch_xxx copy seed i.e deepcopy
So if the caller call reset without any arg. (SyncVectorEnv.reset() that will be some seed since you can't pass during env. create.

```

def make_env(gym_id: Union[str, EnvSpec], seed, idx: int, capture_video: bool, run_name: str):
    def foo():
        env = gym.make(gym_id, action_space=None)
        env = gym.wrappers.RecordEpisodeStatistics(env)
        # env.seed = seed
        # env.action_space.seed(seed) 
        # I assume it should do that only reset can reset seed.
       AttributeError: 'CartPoleEnv' object has no attribute 'seed'
        return env

    return foo

def create_env(gym_id: Union[str, EnvSpec], seed, num_envs: int,
               capture_video: Optional[bool] = False,
               run_name: Optional[str] = "test") -> Iterator[Callable[[], Env]]:
    for i in range(0, num_envs):
        yield make_env(gym_id, seed + 1, 1) # initialize each env with seed.
```
Some trainer.
```
        self.envs = gym.vector.SyncVectorEnv(env_creator)

        def bar(self):
          # what caller should do here ?
          next_observation, infos = self.envs.reset()
```

**Comment by pseudo-rnd-thoughts** [comment]
I don't understand your question or problem

**Comment by spyroot** [comment]
Sorry.   In this example, env_creator yield iterator and each element Callable,  as per signature Iterator[Callable[[], Env]]
sync_envs = gym.vector.SyncVectorEnv(env_creator)

In this case,  

sync_envs.reset(x) should re-initialize each env with the correct seed, no? 
It is unclear whether Callable sets the seed or SyncVectorEnv will do that upon reset(seed) call.

**Comment by pseudo-rnd-thoughts** [comment]
The gym vector environments allow a both `int` and `list[int]`, for `int` then the sub-environments are reset with `seed + i` where `i` in the sub-environment index.
For `list[int]`, for each of the sub-seed are used for seeding the sub-environment

**Comment by spyroot** [comment]
I'm closing.  I think other folks will find it useful to understand.  Once again, thank you very much for taking the time and answering.
