### ISSUE TITLE
Split doom into a separate gym-doom package

### ISSUE THREAD

**Issue by gdb** [openai/gym#315]
Now that we have a convention for packages outside of gym-core, I'd like to split gym-doom back into its own package. (vizdoom is pretty slow to compile, which means slowing down `pip install gym[all]`.)

@catherio mind taking?

cc @ppaquette

**Comment by JKCooper2** [comment]
Are there instructions available for adding an env in the new style (that would overwrite what's currently  [here](https://github.com/openai/gym/tree/master/gym/envs) and [here](https://github.com/openai/gym/wiki/Environments)). Also could a template env be added that people can base new envs on to simplify the process?

**Comment by gdb** [comment]
Nope, but we should add those!

**Comment by gdb** [comment]
(Closed by #319.)
