### ISSUE TITLE
[Question] Inference of spaces.Dict observation space. 

### ISSUE THREAD

**Issue by yeonsann** [openai/gym#3153]
Hi, 

I just trained a model that uses a `spaces.Dict` as observation space. Now I can't seem to use the `model.predict(obs)` method (with obs being a python dict). 

In my training environment it is defined as follows:
```
        self.observation_space = spaces.Dict({
			'has_collided': spaces.MultiBinary(1),
			'previous_output': spaces.Box(),
			'orientation': spaces.Box(),
			'position': spaces.Box(),
			'target': spaces.Box(l),
		})  
```

And I get the following error:
```
ValueError: Error: Unexpected observation shape () for MultiBinary environment, please use (1,) or (n_env, 1) for the observation shape.
```

The documentation mentions FlattenObservation, but that only seems useful during training. 

What am I doing wrong?

**Comment by pseudo-rnd-thoughts** [comment]
What training library is this with as I don't recognise the error source
I would post the error on the training library if Gym is not the source.

**Comment by yeonsann** [comment]
@pseudo-rnd-thoughts I am using stable baselines 3, I'll ask the question there. Thanks :)
