### ISSUE TITLE
[Question] Misleading `MultiDiscrete` doc?

### ISSUE THREAD

**Issue by eliegoudout** [openai/gym#3157]
In the doc of `gym.spaces.MultiDiscrete`, on can read:
```
This represents the cartesian product of arbitrary [Discrete](https://www.gymlibrary.dev/api/spaces/#gym.spaces.Discrete) spaces.
It is useful to represent game controllers or keyboards where each key can be represented as a discrete action space.

e.g. Nintendo Game Controller - Can be conceptualized as 3 discrete action spaces:
- Arrow Keys: Discrete 5 - NOOP[0], UP[1], RIGHT[2], DOWN[3], LEFT[4] - params: min: 0, max: 4
- Button A: Discrete 2 - NOOP[0], Pressed[1] - params: min: 0, max: 1
- Button B: Discrete 2 - NOOP[0], Pressed[1] - params: min: 0, max: 1
```
#### From this example, should we understand that every discrete interval will be one-hot encoded?
I ask because in my mind, it makes no sense to spatially relate `NOOP`, `UP`, `RIGHT`, `DOWN` and `LEFT`. Instead, for the arrow keys, I would probably choose to use 4 input neurons with 1 or 0 depending whether or not button is pressed, just like for `Button A` and `Button B`.
Thus, I think this doc example is misleading. Users (myself included, being new to `gym`) might ask "should I one-hot encode my features or just let `MultiDiscrete` do it for me?

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for the question, sorry for taking so long to respond.

For discrete-based action spaces (`Discrete`, `MultiDiscrete` and `MultiBinary`) then yes, each action can be thought of as a one-hot encoding (or multiple one-hot encoding in the case of `MultiDiscrete` or `MultiBinary`) 

Im quite confused by this questions, so I will answer where I think you are mistaken

> Instead, for the arrow keys, I would probably choose to use 4 input neurons with 1 or 0 depending whether or not button is pressed, just like for Button A and Button B.

You can only take one of the arrow keys, therefore, while there is four values, there is only a single input value. If you implement the space, and sample from it, you can see examples of this

```python
space = MultiDiscrete((4, 2, 2))
space.sample()
```

**Comment by eliegoudout** [comment]
Thank you for your answer. My confusion comes from the fact that despite arrow keys being pressed only one by one, when we encode which arrow is pressed with an integer between 0 and 4 (including `noop`), we imply a forme of mathematical relationship between arrows, which is totally arbitrary (for example, 1 is further away from 3 than 4, but it makes no sense to say "up is further away from left then down" for example.

Usually, in machine learning, people one-hot encode data which have no obvious relationships, to avoid any unwanted correlation that the NN will have to decorrelate on its own later.
I don't know if I make more sense know?

**Comment by pseudo-rnd-thoughts** [comment]
Ok, I understand better now. 
As these are discrete actions, you are right that the value has no relationship to the "distance" between them. Therefore in reinforcement learning, actions are implement as one hot as you discuss however in the literature we do not discussion them like this, in contrast to classification-based problems in supervised learning. 

If you look at the DQN algorithm, then the neural network would have 5 output neurons for an action space of `Discrete(5)`
Likewise, for the Nintendo game controller, then you would expect the neural network to at least 8 outputs, more likely 16 (4 x 2 x 2)

**Comment by eliegoudout** [comment]
> If you look at the DQN algorithm, then the neural network would have 5 output neurons for an action space of Discrete(5)
Likewise, for the Nintendo game controller, then you would expect the neural network to at least 8 outputs, more likely 16 (4 x 2 x 2)

I am not entirely sure what you meant, but if you're saying that it seems silly to have 5 output neurons for only 5 possible state, I do agree, indeed.

Do you have any idea if someone tried to monitor the impact of the "forced" relationship between arrows? For example, by comparing encodings `{0:left, 1: noop, 2:up, 3:down, 4:right}` (which is completly random) with `{0:down, 1: left, 2:noop, 3:right, 4:up}` (which seems a bit more "logical" with noop centered, and symmetry between directions)?

Finally, maybe an "in-between" encoding with two 3-state-neurons `{0:left, 1:noleftorright, 2:right}` and `{0:down, 1:nodownorup, 2:up}` is something to consider?

**Comment by pseudo-rnd-thoughts** [comment]
> I am not entirely sure what you meant, but if you're saying that it seems silly to have 5 output neurons for only 5 possible state, I do agree, indeed.

There is an important difference between states, actions and observation, they are all different so this statement is not correct. 

Importantly, the documentation is not specifying the neural network for multi-discrete action spaces and can be done in a large variety of ways. 

As discussed earlier, the outputs are really one-hot encoding for discrete actions, then there is no relationship between arrows so your question doesn't make sense to me. There might be research that investigates this possible relationship however, I am not aware of it in the common literature.

**Comment by eliegoudout** [comment]
Okay, thank you for your answer.

Since it is basically one-hot encoding, I have 2 questions:

- Is `Discrete(2)` equivalent to only one neuron with 0/1 encoding? While `Discrete(3)` is translated to 3 neurons?
- Are `Discrete(n)` and `MultiDiscrete([2, ..., 2])` equivalent (the second one corresponding to user one-hot encoding before-hand)?

Thanks!

**Comment by pseudo-rnd-thoughts** [comment]
1. Yes it would be possible to do that my certain learning methods, DQN, for `Discrete(2)` would still require 2 neurons. Yes for `Discrete(3)`
2. No, try sampling from the spaces for examples of this

**Comment by eliegoudout** [comment]
I'm sorry if I'm not understanding but I am confused. Maybe I should have precised in the last question "...under the assumption that input vector will always have exactly 1 one and n-1 zeros".

If `Discrete(n)` one-hot encodes as I think you confirmed, then it transforms an input in [0, n-1] to a vector (0, ..., 0, 1, 0, ...), am I correct? Thus in the end, the network will have `n` neurons representing this integer, right? Is it the same as one-hot encoding prior to giving the input to the environment?

**Comment by eliegoudout** [comment]
Thank you for the time you're taking to answer <3 I'm sorry that I'm not making myself understood. My question might be better formulated this way:
Imagine I use `Discrete(4)`. Then, I can have samples 0, 1, 2 or 3, this is clear. But my question is: **how is this value _concretely_ input in the neural network?**
If the answer is "in a single neuron, with value 0, 1, 2 or 3", then no one-hot encoreding is happening and the relashionship between 0, 1, 2 and 3 is kept. If the answer is "in 4 neurons, with value either `1 0 0 0`, `0 1 0 0`, `0 0 1 0` or `0 0 0 1`, then this is one-hot encoding, and indeed the relationship between 0, 1, 2 and 3 is broken.

Since you're telling me it is "essentially one-hot encoding", then I think it is the second answer. If this is that, then, I don't think there's any obvious difference between using `Discrete(n)` and one-hot encode before passing `(0, ..., 0, 1, 0, ...)` to `MultiDiscrete([2, ..., 2])`.

Once again, thank you very much for you patience <3

**Comment by pseudo-rnd-thoughts** [comment]
Thanks for clarifying the question. 
As the original question was about the Nintendo game controller, this is the action space (output of the neural network), I think I was misunderstanding your question. 
For discrete **observation** spaces which are inputs to neural networks, this is not very common and I would agree that the value now has a distance relationship between values so I would one-hot is you want to avoid the relationship problem.

For your proposal of using the `MultiDiscrete` space as one-hot, I would recommend using the `MultiBinary` space as this is already limited to 0-1 values. However, be aware sampling from `MultiBinary` and `MultiDiscrete` will not ensure valid one-hot values

**Comment by eliegoudout** [comment]
Thank you for clarifying 🙏
