### ISSUE TITLE
[Question] custom environment in trouble

### ISSUE THREAD

**Issue by npdrbong** [openai/gym#3159]
Hello, I am very nub in this area...

I proposed a Balloon analogue risk task, which is very simplified discrete task for my research.

I referenced the document but My environment seems to have some trouble

'''
import gym
from gym import spaces
import pygame
import numpy as np
import os

def burst(max_pump, npumps):
    if np.random.rand(1)[0] < 1/(max_pump - npumps + 1):
        return True
    else:
        return False

class Bart(gym.Env):
    metadata = {"render_modes": ["human", "rgb_array"], "render_fps": 4}

    def __init__(self, max_pump = 30):
        self.observation_space = spaces.Dict({"kth pump": spaces.Discrete(max_pump+1), "balloon": spaces.Discrete(2)})
        self.action_space = spaces.Discrete(2)
        self.action_to_pump = {"pump": 1, "stop" : 0}
        self.max_pump = max_pump

    def step(self, action):
        assert self.action_space.contains(action)
        if action: # pump a balloon or stop ( 1 / 0 )
            self.npumps += 1
            if burst(self.max_pump, self.npumps):
                self.balloon=1
                terminated = True
                reward = 0
            else:
                terminated = False
                reward += 1
        else: # stop to pump balloon and withdraw rewards
            terminated = True
        
        if self.render_mode == "human":
            self.render()
        
        return self._get_obs(), reward, terminated, False, {}

    def _get_obs(self):
        return ({"kth pump": self.npumps, "balloon": self.balloon})

    def reset(self, seed=None, options=None):
        super().reset(seed=seed)
        self.npumps = 0
        self.balloon = 0 # pop = 1, else = 0
        return self._get_obs(), {}

    def render(self):
        if self.render_mode is None:
            gym.logger.warn(
                "you didn't specifying any render mode."
            )
            return
        
        npumps, balloon = self._get_obs()
        screen_width, screen_height = 1000, 800
        img_height = 437
        img_width = 612
        spacing = screen_height // 20

        bg_color = (200, 200, 200)
        white = (255, 255, 255)
        
        pygame.display.init()
        self.screen = pygame.display.set_mode((screen_width, screen_height))
        self.screen.fill(bg_color)
        self.clock = pygame.time.Clock()

        def get_image(path):
            cwd = os.path.dirname(__file__)
            image = pygame.image.load(os.path.join(cwd, path))
            return image

        def get_font(path, size):
          cwd = os.path.dirname(__file__)
          font = pygame.font.Font(os.path.join(cwd, path), size)
          return font
    
        small_font = get_font(
            os.path.join("font", "Minecraft.ttf"), screen_height // 15
        )

        def scaled_img(img):
            return pygame.transform.scale(img, (img_width, img_height))
        if balloon == 0:
            balloon_image = scaled_img(
                get_image(
                    os.path.join(
                    "img",
                    "balloon.jpg"
                    )
                )  
            )

            balloon_image_rect = self.screen.blit(
                balloon_image,
                ( screen_width // 2 - img_width - spacing // 2)
            )
        else:
            balloon_image = scaled_img(
                get_image(
                    os.path.join(
                    "img",
                    "pop.jpg"
                    )
                )  
            )

            balloon_image_rect = self.screen.blit(
                balloon_image,
                ( screen_width // 2 - img_width - spacing // 2)
            )

            
        cash_text = small_font.render("pumps", True, white)
        cash_text_rect = self.screen.blit(cash_text, (spacing, balloon_image_rect.bottom + 1.5 * spacing))

        large_font = get_font(
            os.path.join("font", "Minecraft.ttf"), screen_height // 6
        )

        reward_text = large_font.render(str(npumps), True, white)
        reward_text_rect = self.screen.blit(reward_text, (screen_width // 2 - reward_text.get_width() // 2, reward_text_rect.bottom + spacing,),
        )

        if self.render_mode=="human":
            pygame.event.pump()
            pygame.display.update()
            self.clock.tick(self.metadata["render_fps"])
        else:
            return np.transpose(np.array(pygame.surfarray.pixels3d(self.screen)), axes = (1, 0 ,2))

    def close(self):
        if self.window is not None:
            pygame.display.quit()
            pygame.quit()
'''

this is my whole module, and it make some trouble when I use it.

'''
done = False
obs = env.reset()
while not done:
    action = env.action_space.sample()
    obs, reward, done, _, info = env.step(action)
    env.render()
env.close()
'''
'''
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
Cell In[15], line 5
      3 while not done:
      4     action = env.action_space.sample()
----> 5     obs, reward, done, _, info = env.step(action)
      6     env.render()
      7 env.close()

File c:\bce772\gym-examples\.env\lib\site-packages\gym\wrappers\time_limit.py:50, in TimeLimit.step(self, action)
     39 def step(self, action):
     40     """Steps through the environment and if the number of steps elapsed exceeds ``max_episode_steps`` then truncate.
     41 
     42     Args:
   (...)
     48 
     49     """
---> 50     observation, reward, terminated, truncated, info = self.env.step(action)
     51     self._elapsed_steps += 1
     53     if self._elapsed_steps >= self._max_episode_steps:

File c:\bce772\gym-examples\.env\lib\site-packages\gym\wrappers\order_enforcing.py:37, in OrderEnforcing.step(self, action)
     35 if not self._has_reset:
     36     raise ResetNeeded("Cannot call env.step() before calling env.reset()")
---> 37 return self.env.step(action)
...
     36 if self.render_mode == "human":
     37     self.render()
---> 39 return self._get_obs(), reward, terminated, False, {}

UnboundLocalError: local variable 'reward' referenced before assignment

'''

I don't know why this happens... can you help me to fix this?

**Comment by pseudo-rnd-thoughts** [comment]
In your step function, the reward is reference on the `return` but you never define the value of reward is `action == 0` 
```python
def step(self, action):
    assert self.action_space.contains(action)
    if action: # pump a balloon or stop ( 1 / 0 )
        self.npumps += 1
        if burst(self.max_pump, self.npumps):
            self.balloon=1
            terminated = True
            reward = 0
        else:
            terminated = False
            reward += 1
    else: # stop to pump balloon and withdraw rewards
        terminated = True
    
    if self.render_mode == "human":
        self.render()
    
    return self._get_obs(), reward, terminated, False, {}
```
