### ISSUE TITLE
Uploading Acrobot-v1 and CartPole-v1 fails as env not register on the server

### ISSUE THREAD

**Issue by JKCooper2** [openai/gym#316]
When uploading for Acrobot-v1 or CartPole-v1 the following error occurs: `gym.error.InvalidRequestError: Request req_4Y4xDfEyQvSfs9u4C4EHxQ: This version of the environment is not registered on the server, but other versions exist. You may need to upgrade your version of gym. Env Acrobot-v1 not found (valid versions include ['Acrobot-v0'])`

Pages don't currently exist for those envs either: https://gym.openai.com/envs/Acrobot-v1

**Comment by gdb** [comment]
Deployed, thanks!
