### ISSUE TITLE
[Question] How to make open AI gym.env.spaces.dict into tensor of pytorch?

### ISSUE THREAD

**Issue by npdrbong** [openai/gym#3160]
Hello, everyone.

I have trouble with make my observation space into tensor to use as deep RL's input.

    import gym
    from gym import spaces
    import pygame
    import numpy as np
    import os
    from typing import Optional

    def burst(max_pump, npumps):
        if np.random.rand(1)[0] < 1/(max_pump - npumps + 1):
            return True
        else:
            return False

    class Bart(gym.Env):
        metadata = {"render_modes": ["human", "rgb_array"], "render_fps": 4}

        def __init__(self, render_mode: Optional[str] = None, max_pump = 30):
            self.observation_space = spaces.Dict({"kth pump": spaces.Discrete(max_pump+1), "balloon": spaces.Discrete(2)})
            self.action_space = spaces.Discrete(2)
            self.action_to_pump = {"pump": 1, "stop" : 0}
            self.max_pump = max_pump
            self.render_mode = render_mode

        def step(self, action):
            assert self.action_space.contains(action)
            reward = self.reward
            if action: # pump a balloon or stop ( 1 / 0 )
                self.npumps += 1
                if burst(self.max_pump, self.npumps):
                    self.balloon=1
                    terminated = True
                    reward = 0
                else:
                    terminated = False
                    reward =self.npumps
            else: # stop to pump balloon and withdraw rewards
                terminated = True
                reward =self.npumps
        
            if self.render_mode == "human":
                self.render()
        
            return self._get_obs(), reward, terminated, False, {}

        def _get_obs(self):
            return ({"kth pump": self.npumps, "balloon": self.balloon})

        def reset(self, seed=None, options=None):
            super().reset(seed=seed)
            self.npumps = 0
            self.balloon = 0 # pop = 1, else = 0
            self.reward = 0
            return self._get_obs(), {}

        def render(self):
            if self.render_mode is None:
                gym.logger.warn(
                    "you didn't specifying any render mode."
                )
                return
        
            npumps, balloon = self._get_obs()
            screen_width, screen_height = 1000, 800
            img_height = 437
            img_width = 612
            spacing = screen_height // 20

            bg_color = (200, 200, 200)
            white = (255, 255, 255)
        
            pygame.display.init()
            self.screen = pygame.display.set_mode((screen_width, screen_height))
            self.screen.fill(bg_color)
            self.clock = pygame.time.Clock()

        
    def close(self):
        pygame.display.quit()
        pygame.quit()

below is my model using for train and evaluate

    class BaseAgent:
    
    def __init__(self, config):
        self.config = config
        self.env = gym.make(config['env_id'])
        self.model = Model(2, self.env.action_space.n)
        self.gamma = config['gamma']
        self.optimizer = torch.optim.Adam(self.model.net.parameters(), lr=config['learning_rate'])
        
    
    def _make_returns(self, rewards):
        """Returns the cumulative discounted rewards at each time step

        Parameters
        ----------
        rewards : array
            The array of rewards of one episode

        Returns
        -------
        array
            The cumulative discounted rewards at each time step
            
        Example
        -------
        for rewards=[1, 2, 3] this method outputs [1 + 2 * gamma + 3 * gamma**2, 2 + 3 * gamma, 3] 
        """
        
        returns = np.zeros_like(rewards)
        returns[-1] = rewards[-1]
        for t in reversed(range(len(rewards) - 1)):
            returns[t] = rewards[t] + self.gamma * returns[t + 1]
        return returns
    
    # Method to implement
    def optimize_model(self, n_trajectories):
        """Perform a gradient update using n_trajectories

        Parameters
        ----------
        n_trajectories : int
            The number of trajectories used to approximate the expectation card(D) in the formula above
        
        Returns
        -------
        array
            The cumulative discounted rewards of each trajectory
        """
        
        raise NotImplementedError
    
    def train(self, n_trajectories, n_update):
        """Training method

        Parameters
        ----------
        n_trajectories : int
            The number of trajectories used to approximate the expectation card(D) in the formula above
        n_update : int
            The number of gradient updates
            
        """
        
        rewards = []
        for episode in range(n_update):
            rewards.append(self.optimize_model(n_trajectories))
            print(f'Episode {episode + 1}/{n_update}: rewards {round(rewards[-1].mean(), 2)} +/- {round(rewards[-1].std(), 2)}')
        
        # Plotting
        r = pd.DataFrame((itertools.chain(*(itertools.product([i], rewards[i]) for i in range(len(rewards))))), columns=['Epoch', 'Reward'])
        sns.lineplot(x="Epoch", y="Reward", data=r, ci='sd');
        
    def evaluate(self):
        """Evaluate the agent on a single trajectory            
        """
        observation = self.env.reset()
        observation = torch.tensor(observation, dtype=torch.float)
        reward_episode = 0
        done = False
            
        while not done:
            action = self.model.select_action(observation)
            observation, reward, done, info = self.monitor_env.step(int(action))
            observation = torch.tensor(observation.values(), dtype=torch.float)
            reward_episode += reward
        
        #self.monitor_env.close()
        show_video("./gym-results")
        print(f'Reward: {reward_episode}')
        

    class SimpleAgent(BaseAgent):
    
    def optimize_model(self, n_trajectories):
        weighted_logproba = torch.zeros(n_trajectories)
        reward_trajectories = np.zeros(n_trajectories)

        for i in range(n_trajectories):
            # New episode
            observation = self.env.reset()
            rewards_episode = []
            logproba_episode = []
            discount_factor = 1
            observation = torch.tensor(observation.values(), dtype=torch.float)
            done = False
            
            while not done:
                action = self.model.select_action(observation)
                logproba_episode.append(torch.log(self.model.forward(observation))[action])
                # Interaction with the environment
                observation, reward, done, info = self.env.step(int(action))
                observation = torch.tensor(observation.values(), dtype=torch.float)
                rewards_episode.append(discount_factor * reward)
                discount_factor *= self.gamma
            
            cum_rewards_episode = np.sum(rewards_episode)
            weighted_logproba[i]= cum_rewards_episode * torch.cat(logproba_episode).sum()
            reward_trajectories[i] = cum_rewards_episode
            
        loss = - weighted_logproba.mean()
        
        self.optimizer.zero_grad()
        # Compute the gradient 
        loss.backward()
        # Do the gradient descent step
        self.optimizer.step()
        return reward_trajectories

This code make some trouble like this

    agent = SimpleAgent(config)
    agent.train(n_trajectories=50, n_update=50)

    ---------------------------------------------------------------------------
    TypeError                                 Traceback (most recent call last)
    Cell In[21], line 2
          1 agent = SimpleAgent(config)
    ----> 2 agent.train(n_trajectories=50, n_update=50)

    Cell In[12], line 67, in BaseAgent.train(self, n_trajectories, n_update)
         65 rewards = []
         66 for episode in range(n_update):
    ---> 67     rewards.append(self.optimize_model(n_trajectories))
         68     print(f'Episode {episode + 1}/{n_update}: rewards {round(rewards[-1].mean(), 2)} +/- {round(rewards[-1].std(), 2)}')
         70 # Plotting

    Cell In[19], line 13, in SimpleAgent.optimize_model(self, n_trajectories)
         11 logproba_episode = []
         12 discount_factor = 1
    ---> 13 observation = torch.tensor(observation, dtype=torch.float)
         14 done = False
         16 while not done:

    TypeError: must be real number, not dict

I think this occurs because my observation_space is space.dict but torch.tensor can't make this into tensor.

So I tried to change it as observation.values() but it answers like::
AttributeError: 'tuple' object has no attribute 'values'

so I am confused to how to make this work?

Thank you for your advice!

have a good day!

**Comment by pseudo-rnd-thoughts** [comment]
As your data is a dictionary, `{"kth pump": 1, "balloon": 0}` then torch doesn't understand how to convert this to be a pytorch tensor. You need to convert each value to be a tensor, i.e., `obs = {"kth pump": torch.tensor(obs["kth pump"]), "balloon": torch.tensor(obs["balloon"]}` or flatten the space https://gymnasium.farama.org/api/spaces/utils/#gymnasium.spaces.utils.flatten_space

**Comment by ManojGadam** [comment]
Hi npdrbong did you resolve the problem? If yes how so?
