### ISSUE TITLE
[Bug Report] ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by oofmeister27** [openai/gym#3165]
I am working with this [repo](https://github.com/RajGhugare19/dreamerv2) and I am facing an issue when I start the traing that seems to be coming from core.py: 

```
Traceback (most recent call last):
  File "/home/anavani/dreamerv2/test/pomdp.py", line 138, in <module>
    main(args)
  File "/home/anavani/dreamerv2/test/pomdp.py", line 67, in main
    trainer.collect_seed_episodes(env)
  File "/home/anavani/dreamerv2/dreamerv2/training/trainer.py", line 41, in collect_seed_episodes
    s, done  = env.reset(), False
  File "/home/anavani/anaconda3/lib/python3.9/site-packages/gym/core.py", line 379, in reset
    obs, info = self.env.reset(**kwargs)
ValueError: too many values to unpack (expected 2)
```
Clone [this](https://github.com/RajGhugare19/dreamerv2) repo and in the tests folder run ```python pomdp.py --env breakout --device cuda``` to reproduce this error. 

**System Info**
 * Gym was installed through pip
 * Ubuntu 22.04
 * Python 3.9
 
Any help would be appreciated.

**Comment by pseudo-rnd-thoughts** [comment]
What gym version are you using? ``import gym`` ``gym.__version__``
The repo requires 0.18 https://github.com/RajGhugare19/dreamerv2/blob/0c12a20c5608fdadc5aeb0cd335d6db3ba0cad0c/requirements.txt#L31

**Comment by oofmeister27** [comment]
@pseudo-rnd-thoughts That fixed it. Thanks for your help.
