### ISSUE TITLE
[Question] Gym space issue "Values of the dict should be instances of gym.Space"

### ISSUE THREAD

**Issue by jerrydzh410** [openai/gym#3169]
### Question
HI,
I would like to know why this issue happens. I define my observation space in my customized environment like this. But when I try to run my environment the below error occurs. Could you inspire me on how to fix such issue? 
Thanks!
![image](https://user-images.githubusercontent.com/121841553/210390773-68ee91d3-dce0-4e65-8ef3-365420837a1c.png)

![image](https://user-images.githubusercontent.com/121841553/210390635-73734458-849c-4ea9-87d8-17a7f4a155da.png)

**Comment by jerrydzh410** [comment]
> Hi, thanks for the help! I think I do import the gym space.

![image](https://user-images.githubusercontent.com/121841553/210393755-16cc8bcf-6f70-4c8f-9d18-8422f2f1c908.png)

**Comment by pseudo-rnd-thoughts** [comment]
Change to `self.state = {"PipeL": [0, 0, 0, 0], "Score": [results_test["nrmse"]]}`

**Comment by jerrydzh410** [comment]
> self.state = {"PipeL": [0, 0, 0, 0], "Score": [results_test["nrmse"]]}

I see thank! So I can only define my observation space as gym.sapce, but I should define my state with python Dict.

**Comment by pseudo-rnd-thoughts** [comment]
Yes, you can see the example instance of the space with `space.sample()`, i.e., `self.observation_space.sample()`
