### ISSUE TITLE
[Bug Report] AssertionError: The algorithm (PPO) only supports Discrete as action spaces but Box was provided [bug]

### ISSUE THREAD

**Issue by Kristin-Schwarzmuller** [openai/gym#3171]
**Describe the bug**
I trained a PPO model in an environment with a Discrete action space. Now after expanding the functionalities, I want to use a Box. But I am getting:
` AssertionError: The algorithm only supports (<class 'gym.spaces.discrete.Discrete'>,) as action spaces but Box(-1, 32, (12,), int32) was provided`

In the [Docu](https://stable-baselines3.readthedocs.io/en/master/modules/ppo.html), it's written, that Boxes should be supported as action spaces. 

I updated my gym and stable baseline3 version to the [Bleeding-edge version](https://stable-baselines3.readthedocs.io/en/master/guide/install.html#bleeding-edge-version) without success. 

I tried other algorithms like A2C, TD3, SAC but got the same error.

What am I doing wrong? What can I check? 

**Code example**
I am defining my action space using: 
`self.action_space = Box(low=-1, high=32, shape=(12,), dtype=np.int32)`

**System Info**
* OS:  Linux Ubuntu 20.04.4 LTS (Focal Fossa)
 * gym: installed using pip. At first, I had version 0.21 but I just updated it to 0.24 (without improvements) 
 * stable baseline3: 2.0.0a0 (tried it before with 1.6.2 but with the same error) 
 * Python: 3.10.5

### Checklist

- [ x] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by pseudo-rnd-thoughts** [comment]
This is a stable-baselines-3 issue not a gym issue, could you post the issue on that github please
https://github.com/DLR-RM/stable-baselines3/

**Comment by Kristin-Schwarzmuller** [comment]
I am so sorry, this is actually what I intendet. A too long working day and too many taps.

**Comment by Krishnendu1984** [comment]
The algorithm only supports <class 'gym.spaces.box.Box'> as action spaces but Box(-0.5, 0.5, (6,), float32) was provided
 I am also getting same issue while training.Kindly help

**Comment by pseudo-rnd-thoughts** [comment]
What is the type of your box action space? I suspect you are using a Gymnasium space rather than a gym space
