### ISSUE TITLE
[Question] LunarLanderV2 not enforcing env.spec.max_episode_steps?  Gym 0.26.1

### ISSUE THREAD

**Issue by ncotie** [openai/gym#3173]
Hello,
I have been using LunarLanderV2 for RL testing, on Gym 0.26.1, on python 3.9.

From what I've seen, the Env has env.spec.max_episode_steps set to 1000, however the model/agent I'm using is often seeing episodes going past 1000 steps, even to 20k in one case, without the Env returning 'done'.  After adding a bit of code in the Agent to set an episode to done after hitting 1000 steps, I continue to see a lot of episodes hitting the Agent-enforced limit, including during runs where the agent solves the environment (> 200 score for 100 games).

I am assuming this should not be happening, that all Env's should enforce the env.spec.max_episode_steps?
Is this assumption correct, or do various games behave differently with respect to the env.spec.max_episode_steps?
I can provide code if needed, but it seemed to need a sanity check first.

Thanks,
Neil

**Comment by pseudo-rnd-thoughts** [comment]
Could you provide example code to show this? 

The `env.spec.max_episode_steps` is implemented through the `TimeLimit` wrapper such that if you run `gym.make("LunarLander-v2")` this is equal to `TimeLimit(LunarLanderEnv())`, the base lunar lander environment doesn't implement the time limit code.

In v0.26, the `step` function was modified to `tuple[obs, reward, terminated, truncated, info]` such that `done = terminated or truncated`. Could this be the cause of your issue?

**Comment by ncotie** [comment]
Hello,
Indeed, I had seen that the step return was extended by one field in 0.26, however I did not realize that the step limit would be signalled through the new field.  That must be why I'm seeing this.
Thanks very much for the reply, apologies for the time spent.
Regards,
Neil
