### ISSUE TITLE
[Question] Isn't auto-reset of vector-env problematic?

### ISSUE THREAD

**Issue by bkkgbkjb** [openai/gym#3177]
### Question or Potential Bug

During my use of  `gym.vector.AsyncVectorEnv`, I find it seems problematic for `vectorEnv` to automaticall reset  element env when its episode ends. (as stated in [docs](https://www.gymlibrary.dev/content/vectorising/#working-with-vectorized-environments): *The environment copies inside a vectorized environment automatically call gym.Env.reset at the end of an episode*)

Specifically, imagine a reward-delayed env that only returns reward when episode ends.
Doing auto-reset would make us lose track of `next_state` and only has a partial tuple of `(last_state, last_act, done, delayed_reward, *missing*)` instead of a normal `(s, a, r, d, s')`

Workarounds or solutions I could think of are:
1. discard last tuple, but this certainly wouldn't work in reward-delayed env
2. use reset-ed `init_state` as `terminal_state`, but I guess this would confuse `value_function` or other parts in `RL` algo.
3. use `None` for `terminal_state`, but this seems un-compatible for some `RL` algos.

What's your idea on this?
any solution/workarounds that I could take to avoid above issue?

Thanks a lot in advance

**Comment by jkterry1** [comment]
Hey, Gym is no longer being actively developed, all work has been shifted to Gymnasium, like the readme here and the splash screen on the documentation page when you go to it for the first time say. You can read a bit more about the transition here if you're unfamiliar: https://farama.org/Announcing-The-Farama-Foundation

Could you please file this issue over there instead?

**Comment by bkkgbkjb** [comment]
finds that `terminal_state` would be returns in `info` of that `env.step()`
question resolved

thanks for your great work

**Comment by zzhixin** [comment]
I don't think mainstream RL algo need the terminal state. You might think q learning does. But actually one can just set the Q(s',a')[ or V(s')] as zero if it' is terminal state.
