### ISSUE TITLE
Individual Env Pages for PyGame envs don't load correctly

### ISSUE THREAD

**Issue by JKCooper2** [openai/gym#318]
Clicking on an env in https://gym.openai.com/envs#pygame load a blank page

**Comment by gdb** [comment]
@catherio Ah I'd forgotten that we load the environment spec in scoreboard. We need it in order to know the scoring parameters for the environment.

I've added a hackfix for now (manually importing the relevant registrations). We can do something more sophisticated later.

**Comment by gdb** [comment]
Done
