### ISSUE TITLE
no working

### ISSUE THREAD

**Issue by testtest954** [openai/gym#3188]
(english broken or not understanding maybe?)
this is my first time i typed the code
`import gym
env = gym.make("CartPole-v1")
observation, info = env.reset(seed=42)

for _ in range(1000):
    action = env.action_space.sample()
    observation, reward, terminated, truncated, info = env.step(action)

    if terminated or truncated:
        observation, info = env.reset()
env.close()`
then add
`env.render()
true`
it appears this
`D:\gympy\venv\lib\site-packages\gym\envs\classic_control\cartpole.py:212: UserWarning: WARN: You are calling render method without specifying any render mode. You can specify the render_mode at initialization, e.g. gym("CartPole-v1", render_mode="rgb_array")
  "You are calling render method without specifying any render mode. "`
what is this?
and how do i do it?
can somebody know to fix it?

**Comment by pseudo-rnd-thoughts** [comment]
You need to do `env = gym.make("CartPole-v1", render_mode="human")` or `render_mode="rgb_array"`
