### ISSUE TITLE
:display(warning): FrameBufferProperties available less than requested.

### ISSUE THREAD

**Issue by GeYuhong** [openai/gym#3195]
After upgrading the system from 16.04 to 20.04, the rendered image is very sluggish and completely unusable. When running the program, the following prompt appears:
:display(warning): FrameBufferProperties available less than requested.
  requested: depth_bits=1 color_bits=3 red_bits=1 green_bits=1 blue_bits=1 alpha_bits=1 multisamples=8 back_buffers=1 force_hardware 
  got: depth_bits=32 color_bits=24 red_bits=8 green_bits=8 blue_bits=8 alpha_bits=8 multisamples=4 back_buffers=1 force_hardware force_software

How can I solve this problem, thx

**Comment by pseudo-rnd-thoughts** [comment]
What code were you running to produce this? 
I suspect that the issue is with pygame rather than Gym

**Comment by GeYuhong** [comment]
> 

Hi,

You are right. The problem is caused by the defect of my computer itself and i have solved it.
Thank you!

**Comment by lunalulu** [comment]
@GeYuhong  May I know how you solved it? thanks

**Comment by GeYuhong** [comment]
> @GeYuhong May I know how you solved it? thanks

@lunalulu Sorry for not replying in time. There was a problem with my driver that caused the computer to have to render animations on the cpu. After I reinstalled the driver 510.108.03, the problem was solved.
