### ISSUE TITLE
[Proposal] gym.box.sample() (and maybe others gym.spaces) may sample batch

### ISSUE THREAD

**Issue by hbonnavaud** [openai/gym#3197]
### Proposal 

gym.spaces.box.sample() return a numpy array unifomly sampled in the given box.

For example, gym.spaces.Box(0, 1, (2,)).sample() may returns np.array([0.4, 0.6]).

It can be interesting to give a batch shape to sample() so the returned numpy array is a batch of sampled arrays.
```
def sample(self, ..., batch_shape=(1,)):
    ...
```

In the case above, the shape of the returned array will be (*batch_shape, *self.shape).

For example, gym.spaces.Box(0, 1, (2,)).sample(batch_shape=(5,)) may returns :
```
np.array([
    [0.1, 0.5],
    [0.8, 0.6],  
    [0.7, 0.3],  
    [0.9, 0.8],  
    [0.32, 0.5],  
])
```

### Motivation

In reinforcement learning, we work so many times with batches.
More, sample many data uniformly in a space is really usefull in so many cases.
I guess that include this feature inside spaces.Box.sample() can leads to way more optimized solutions than

```
for _ in range(batch_size):
    box.sample()
```
   
or more clean than 

```
b = Box(low=np.array([-10, -5]), high=np.array([10, 5]))
b_prime = Box(np.repeat(b.low, batch_size).reshape(*b.shape, batch_size).T, np.repeat(b.high, batch_size).reshape(*b.shape, batch_size).T)
b_prime.sample()
```

### Pitch

... I guess it's detailed enough above ...

### Alternatives

_Repeat from above .... _

I guess that include this feature inside spaces.Box.sample() can leads to way more optimized solutions than

```
for _ in range(batch_size):
    box.sample()
```
   
or more clean than 

```
b = Box(low=np.array([-10, -5]), high=np.array([10, 5]))
b_prime = Box(np.repeat(b.low, batch_size).reshape(*b.shape, batch_size).T, np.repeat(b.high, batch_size).reshape(*b.shape, batch_size).T)
b_prime.sample()
```

### Checklist

Searched for similar issues, found None, guess it's enough.

**Comment by pseudo-rnd-thoughts** [comment]
There exists a `batch_space(space: Space, n: int) -> Space` that will return a new space with the updated batch size
https://gymnasium.farama.org/api/spaces/vector_utils/#spaces-vector-utils

Then you can call sample on that space for a sample of that particular batch size

**Comment by hbonnavaud** [comment]
I didn't knew that it definitely solve it. Thx.
