### ISSUE TITLE
Issue with resuming Super Mario Bros game training from interrupted state in Google Colab

### ISSUE THREAD

**Issue by wulukewu** [openai/gym#3204]
I'm having some issues with training a Super Mario Bros game on Google Colab. I modified some code so that I could resume training from where it left off after an interruption, but I found that the new training did not pick up where the previous one left off. 

```python
# Import os for file path management
import os
# Import PPO for algos
from stable_baselines3 import PPO
# Import Base Callback for saving models
from stable_baselines3.common.callbacks import BaseCallback

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

if not os.path.exists(f'{folder_path_temp}/{model_number}'):
    os.makedirs(f'{folder_path_temp}/{model_number}')

# Get the current training times
train_folder_path = f'{folder_path_temp}/{model_number}/train'
if os.path.exists(train_folder_path):
    train_files = os.listdir(train_folder_path)
    train_file_dict = {}
    for file in train_files:
        file_path = os.path.join(train_folder_path, file)
        if os.path.isfile(file_path):
            train_num = int(file.split('_')[-1].split('.')[0])
            train_file_dict[file] = train_num
    current_train_num = train_file_dict[max(train_file_dict, key=train_file_dict.get)]

class TrainAndLoggingCallback(BaseCallback):

    def __init__(self, check_freq, save_path, verbose=1):
        super(TrainAndLoggingCallback, self).__init__(verbose)
        self.check_freq = check_freq
        self.save_path = save_path
        self.model_counter = current_train_num + check_freq  # Set the model counter to the current number of training times

    def _init_callback(self):
        if self.save_path is not None:
            os.makedirs(self.save_path, exist_ok=True)

    def _on_step(self):
        if self.n_calls % self.check_freq == 0:
            model_path = os.path.join(self.save_path, 'best_model_{}.zip'.format(self.model_counter))
            self.model.save(model_path)
            self.model_counter += check_freq  # Increase the model counter by check_freq after each save
    
        return True

# Setup model saving callback
callback = TrainAndLoggingCallback(check_freq=check_freq, save_path=CHECKPOINT_DIR)

# This is the AI model started
model = PPO('CnnPolicy', env, verbose=1, tensorboard_log=LOG_DIR, learning_rate=learning_rate, n_steps=n_steps)


if os.path.exists(train_folder_path):

    # Get the most training times model
    max_train_num_file = max(train_file_dict, key=train_file_dict.get)

    # Build the path of the most training times model
    max_train_num_file_path = os.path.join(train_folder_path, max_train_num_file)

    # Load the most training times model before model.learn
    if os.path.exists(max_train_num_file_path):
        model.load(max_train_num_file_path)
        print(f'Loaded model from {max_train_num_file_path}')

# Set the total timesteps as the sum of last training numbers and total timesteps
total_timesteps += current_train_num
print(f'total_timesteps: {total_timesteps}\ncurrent_train_num: {current_train_num}')

# Train the AI model, this is where the AI model starts to learn
model.learn(total_timesteps=total_timesteps, callback=callback, reset_num_timesteps=False, tb_log_name='PPO')
``` 

In my code, I have a variable called train_folder_path, which points to a directory containing two subdirectories: logs and train. Each time I run the code, the logs directory will have new subdirectories with names like PPO_1 and PPO_2, and each of these subdirectories will contain a log file with a name like events.out.tfevents.1680514391.100228883bb9.309.0. Meanwhile, the train directory will contain saved model files with names like best_model_100000.zip and best_model_200000.zip, depending on the value of check_freq. 

I would greatly appreciate any help with this issue, as I am hoping to successfully resume training from where it left off after an interruption. Thank you in advance for any assistance you can provide.

**Comment by StarKnightt** [comment]
Your code suggests that you are successfully saving the model and loading the most recent model before starting the training process again. It is probable that the `total_timesteps` argument supplied to the `model.learn()` method causes the problem, though.

In order to resume training, you must add the` total_timesteps` value to the number of timesteps from the previous training runs and then send this value to the `model.learn()` method. However, the `model.learn()` method determines the total number of timesteps to train the model rather than the number of timesteps to train in the current run using the `total_timesteps` parameter.

To ensure that the model continues training from where it left off, you should pass the remaining number of timesteps to train to the `model.learn()` method. You can calculate this by subtracting the number of timesteps already trained (i.e., current_train_num) from the total number of timesteps you want to train (i.e., total_timesteps). Here's an example:


`#Calculate the remaining number of timesteps to train
remaining_timesteps = total_timesteps - current_train_num

#Train the AI model, starting from the current number of timesteps
model.learn(total_timesteps=remaining_timesteps, callback=callback, reset_num_timesteps=False, tb_log_name='PPO')
`
By doing this, the model will continue training from where it left off in the previous run, rather than starting from scratch.

**Comment by wulukewu** [comment]
Hi StarKnightt,

I've modified the code according to your suggestions, but I'm still having trouble with the model not continuing training from where it left off. Could it be because I also need to load the log directory files?

Here's my current modified code:
```python
# Import os for file path management
import os
# Import PPO for algos
from stable_baselines3 import PPO
# Import Base Callback for saving models
from stable_baselines3.common.callbacks import BaseCallback

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

if not os.path.exists(f'{folder_path_temp}/{model_number}'):
    os.makedirs(f'{folder_path_temp}/{model_number}')

# Get the current training times
train_folder_path = f'{folder_path_temp}/{model_number}/train'
if os.path.exists(train_folder_path):
    train_files = os.listdir(train_folder_path)
    train_file_dict = {}
    for file in train_files:
        file_path = os.path.join(train_folder_path, file)
        if os.path.isfile(file_path):
            train_num = int(file.split('_')[-1].split('.')[0])
            train_file_dict[file] = train_num
    current_train_num = train_file_dict[max(train_file_dict, key=train_file_dict.get)]

class TrainAndLoggingCallback(BaseCallback):

    def __init__(self, check_freq, save_path, verbose=1):
        super(TrainAndLoggingCallback, self).__init__(verbose)
        self.check_freq = check_freq
        self.save_path = save_path
        self.model_counter = current_train_num + check_freq  # Set the model counter to the current number of training times

    def _init_callback(self):
        if self.save_path is not None:
            os.makedirs(self.save_path, exist_ok=True)

    def _on_step(self):
        if self.n_calls % self.check_freq == 0:
            model_path = os.path.join(self.save_path, 'best_model_{}.zip'.format(self.model_counter))
            self.model.save(model_path)
            self.model_counter += check_freq  # Increase the model counter by check_freq after each save
    
        return True

# Setup model saving callback
callback = TrainAndLoggingCallback(check_freq=check_freq, save_path=CHECKPOINT_DIR)

# This is the AI model started
model = PPO('CnnPolicy', env, verbose=1, tensorboard_log=LOG_DIR, learning_rate=learning_rate, n_steps=n_steps)


if os.path.exists(train_folder_path):

    # Get the most training times model
    max_train_num_file = max(train_file_dict, key=train_file_dict.get)

    # Build the path of the most training times model
    max_train_num_file_path = os.path.join(train_folder_path, max_train_num_file)

    # Load the most training times model before model.learn
    if os.path.exists(max_train_num_file_path):
        model.load(max_train_num_file_path)
        print(f'Loaded model from {max_train_num_file_path}')

# Set the total timesteps as the sum of last training numbers and total timesteps
remaining_timesteps = total_timesteps - current_train_num
print(remaining_timesteps)

# Train the AI model, this is where the AI model starts to learn
model.learn(total_timesteps=remaining_timesteps, callback=callback, reset_num_timesteps=False, tb_log_name='PPO')
```

Thank you so much for your help with this issue. I'm grateful for your assistance in understanding the issue and for suggesting solutions to resolve it. Thank you again for all of your help!

**Comment by StarKnightt** [comment]
The log directory may also need to have the files loaded. The tensorboard logs that document your model's development throughout training are stored in the log directory files. The model might not be able to pick up where it left off with its training if you do not load them.
To load the log directory files, you can pass the path to the log directory to the `tensorboard_log` argument when you create the `PPO` object. In your code, you're already doing this, so you should be good to go.
However, be sure to use the same log directory that was utilized for the earlier training sessions. The model might not be able to continue training from where it left off if the log directory changes between training sessions.
Hopefully, it will help you.

**Comment by wulukewu** [comment]
Hi, thank you for your response. When running the program using the code above, I did print the message "Loaded model from /content/drive/Shareddrives/MarioRL/train/best_model_1000000.zip," and there are log files in the PPO_0 folder within the log directory. However, it seems that the final output model still starts training from scratch. Regarding your example, it does appear to have loaded the step 1000000 checkpoint. I'm currently wondering if, since the previous training batch had 512 steps, I should actually load the step 1000448 checkpoint instead. Or would this not have any effect?

**Comment by StarKnightt** [comment]
It's possible that the model is still starting from scratch due to the way you are setting the total timesteps. If you set reset_num_timesteps=False, the model will continue training from where it left off. However, in your code, you are setting remaining_timesteps to total_timesteps - current_train_num, which could be resetting the timesteps to zero.

You mentioned that the previous training batch had 512 steps, but it's not clear how you arrived at the number 1000448. If the model had already been trained for 1000000 steps and you want to continue training from that point, you should load the model checkpoint that was saved at 1000000 steps.

You can check the number of timesteps trained by inspecting the num_timesteps attribute of the model object. You can also check the name of the latest saved model checkpoint by looking at the files in the checkpoint directory.

I took help from ChatGPT, because I had no idea this time.

**Comment by wulukewu** [comment]
Hi! Thank you for patiently answering my questions. After consulting with ChatGPT, I modified the "learn" section of the code to the following: 
```python
import tensorflow as tf
from stable_baselines3 import PPO

ppo_model = PPO("MlpPolicy", "CartPole-v1", verbose=1)

class PPOTrackable(tf.train.Checkpoint):
    def __init__(self, ppo_model):
        super().__init__()
        self.ppo_model = ppo_model

trackable_ppo = PPOTrackable(ppo_model)
checkpoint = tf.train.Checkpoint(model=trackable_ppo)

# Save model
checkpoint.save('my_model')

# Load model
checkpoint.restore(tf.train.latest_checkpoint('./'))

# Continue training
# model.learn(total_timesteps=remaining_timesteps, callback=callback, reset_num_timesteps=False, tb_log_name='PPO')
model.learn(total_timesteps=total_timesteps, callback=callback, reset_num_timesteps=False, tb_log_name='PPO')
``` 
In this modified code, when "model.learn()" is called, it successfully loads the logs and continues the previous training process. The "training_steps" that are printed out also continue to increment from the previous value, rather than starting from 0.

I believe that I have successfully solved the issue and there are no major problems. Thank you again for your help, I have learned a lot as a beginner. 🙏
