### ISSUE TITLE
[Bug Report] `AssertionError: nvec (counts) have to be positive` for MultiDiscrete Action Space?

### ISSUE THREAD

**Issue by windowshopr** [openai/gym#3205]
[bug]

**Describe the bug**
Getting the error `AssertionError: nvec (counts) have to be positive` when using the MultiDiscrete action space with 0's in the space.

**Code example**
To reproduce, create a new Colab notebook and run the following code:

```
!apt-get install ffmpeg freeglut3-dev xvfb  # For visualization
try:
    import stable_baselines3
except:
    import sys
    !pip3 install pyglet==1.4
    !pip3 install git+https://github.com/JY251/stable-baselines3.git
    import stable_baselines3
import gym

self.action_space = gym.spaces.MultiDiscrete([
            [x for x in range(50)],
])
```

Changing the above to:

```
self.action_space = gym.spaces.MultiDiscrete([
            [x for x in range(1, 50+1)],
])
```

...works. The error is a tad misleading, 0 isn't a negative number (although granted it's not a positive either), and I swear it worked with 0's before, but maybe time's they are a changin'.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by windowshopr** [comment]
Not even sure this is really a bug, so I will close it, just didn't find an issue like it yet, so figured I'd post it here.

**Comment by pseudo-rnd-thoughts** [comment]
As `nvec` represents the number of discrete valid actions that a user can take in each dimension then this is correct as you can't / shouldn't have zero actions to take. This is also as `MultiDiscrete` is exclusive not inclusive when sampling
