### ISSUE TITLE
Link to default wiki page for each environment

### ISSUE THREAD

**Issue by osigaud** [openai/gym#321]
Hi,

I had my continuous mountain car environment accepted, it is now on the repository and it has its own page, that people from openAI made by themselves. 

I like it. But before this page existed, I was already wondering how to connect useful information about this environment (parameters, explaining the reward function, papers published on this benchmark...) into a web page (my forked version of gym should disappear, shouldn't it?). 

On the wiki, I saw a page about one environment (cartpole-V0, I guess).

I believe this is a good solution, but a link to that wiki page should appear when you visit the environment page. So, to generalize, each time an environment is added to the repo, it would be nice to generate a link to a wiki page, that the author of the environment (or other people, this is a wiki!) could fill.

Don't you like the idea? Isn't this easy to implement?

Best regards,

Olivier

**Comment by gdb** [comment]
Right now we're still experimenting with different models for documenting environments. Please feel free to manually add that documentation. If it turns out to be very successful and something we decide to scale, then we'll consider automating down the road!

**Comment by osigaud** [comment]
Thanks.
I have just created a page on MountainCarContinuous-v0 on the wiki, it would be nice to refer to it in the environment page.
BTW, this environment page requires a small edit, see the text there is some ugly message in it.


Best regards,

Olivier

**Comment by gdb** [comment]
Thanks — yep, we'll be fixing this soon.

**Comment by PeterMitrano** [comment]
I like the wiki idea. It's easy enough for a small community to maintain for now. I added one for pendulum-v0. I intend to make a new one for each new environment I work on.
