### ISSUE TITLE
error?

### ISSUE THREAD

**Issue by SadlekAski** [openai/gym#3217]
![image](https://github.com/openai/gym/assets/129619951/dc1615fa-bba8-42d8-91b6-2555d0e423b8)

**Comment by pseudo-rnd-thoughts** [comment]
There are several issue already about this
https://github.com/openai/gym/issues/3211
https://github.com/openai/gym/issues/3208
https://github.com/openai/gym/issues/3202
https://github.com/openai/gym/issues/3200

Please see if one of these solves your issue

**Comment by SadlekAski** [comment]
nothing worked of this but I lazy to fix it so uh I close this
