### ISSUE TITLE
Local evaluations?

### ISSUE THREAD

**Issue by osigaud** [openai/gym#322]
Is it possible to evaluate one's agent on one environment and benefit from the evaluation information without uploading on gym? I believe this would help testing and debugging before (proudly) uploading the final working agent on the website...

**Comment by gdb** [comment]
Yes, there's code here to show your score! https://github.com/openai/gym/blob/master/gym/scoreboard/scoring.py

**Comment by anjishnu** [comment]
What happened to all this evaluation code?
