### ISSUE TITLE
[Question] Querying xpos (and other fields) from env after initialization produces all zeros?

### ISSUE THREAD

**Issue by vymao** [openai/gym#3228]
### Question

I wanted to use `xpos` from my environment that I created. I noticed that doing something like this: 

```
p = gym.make('Humanoid-v4')
    print(p.data.xpos)
```
produces a Numpy array of all zeros. I would have expected the body positions to be filled in after initialization, but this doesn't seem to be the case. I just wanted to confirm: 
1) Is this intended?
2) Is there another easy way of querying body position data after initialization?

**Comment by pseudo-rnd-thoughts** [comment]
The models data will be initialised during `reset`

**Comment by vymao** [comment]
Got it, thanks!
