### ISSUE TITLE
Is there a leader board for external envs?

### ISSUE THREAD

**Issue by danijar** [openai/gym#323]
The Doom tasks were recently moved into its own package (https://github.com/openai/gym/issues/315), and they disappeared from the web service. I worked on the Doom gym envs for the last two month and finally got reasonable results. Can I upload those results?

**Comment by gdb** [comment]
Cool. We're going to whitelist external envs for now. I'll bring back Doom this weekend.

**Comment by gdb** [comment]
(I'll note that long-term we haven't sorted out exactly what we'll host on the leaderboards ourselves, but worst case we'll provide an open-source version of the scoreboard which people could add their own environments to.)

**Comment by gdb** [comment]
(Back on the main site for now: https://gym.openai.com/envs#doom.)

**Comment by danijar** [comment]
Thanks!

**Comment by andreas-eberle** [comment]
@gdb: Is there a reason why doom is not on the site anymore?
