### ISSUE TITLE
[Bug Report] SyncVectorEnv has an unremoved but deprecated method seed()

### ISSUE THREAD

**Issue by zhengzl18** [openai/gym#3234]
The `SyncVectorEnv` has a method `seed()`, in which `super().seed(seed=seed)` is called. However, the method `seed()` has already been deprecated in `Env`.

**Code example**
```
import gymnasium as gym

sync_env = SyncVectorEnv([lambda: gym.make("CartPole-v1") for _ in range(3)])
sync_env.seed(0)
```

This yields:
> AttributeError: 'super' object has no attribute 'seed'

**Comment by zhengzl18** [comment]
I mistakenly report a bug of gymnasium in this repo, so I closed this issue.

**Comment by zzr2311559** [comment]
I have also encountered `AttributeError: 'super' object has no attribute 'seed'`. Did you find anything that could lead to this error? Thank you!

**Comment by pseudo-rnd-thoughts** [comment]
`seed` has been moved to `reset(seed=seed)`
