### ISSUE TITLE
multi-armed bandit as an environment

### ISSUE THREAD

**Issue by AshishBora** [openai/gym#324]
multi-armed bandit is one of the simplest stateless reinforcement learning problems. [This](https://www.dropbox.com/s/b3psxv2r0ccmf80/book2015oct.pdf?dl=0) introductory book uses them to explain simple RL algorithms.

It would be useful to have it (if its not present already) as an environment for simple experimentation for beginners.

As a concrete instance, we can implement one 10-armed bandit from the testbed defined in second paragraph on Page 30 of the same book.

**Comment by JKCooper2** [comment]
I've created a suite of bandit envs you can easily add [here](https://github.com/JKCooper2/gym-bandits) including a few 10 armed bandits with probabilities and rewards based on distributions. If you have any particular distribution types you'd like to see (particularly those from books/papers) let me know and I'll add them in

**Comment by korymath** [comment]
Very nice!

**Comment by tycho01** [comment]
another implementation from Microsoft's edx course [DAT257x](https://github.com/MicrosoftLearning/Reinforcement-Learning-Explained/):
- [env](https://github.com/MicrosoftLearning/Reinforcement-Learning-Explained/blob/master/lib/envs/bandit.py#L24)
- [render](https://github.com/stan4git/DAT257x_Reinforcement_Learning/blob/master/lib/plotting.py#L145)
- [demo](https://github.com/MicrosoftLearning/Reinforcement-Learning-Explained/blob/master/Module%202/Ex2.1A%20Greedy.ipynb)

**Comment by christopherhesse** [comment]
Thanks for making those @JKCooper2!  It would be nice to have the environments linked on this page: https://github.com/openai/gym/blob/master/docs/environments.md#third-party-environments Please submit a PR if you would like them there.
