### ISSUE TITLE
Segmentation Fault while trying to run Rviz in a wsl enviorment using VcXsrv 

### ISSUE THREAD

**Issue by MateusAlo** [openai/gym#3255]
I am trying to run rviz in an enviorment in a windows 11 computer using Ubuntu 18.04, a common issue with openGl is sited at the source that i was following (https://jackkawell.wordpress.com/2020/06/12/ros-wsl2/) i tryed adding "export LIBGL_ALWAYS_INDIRECT=0" at my bashrc file but it didnt work.
I also checked to see if some other opengl aplication ran and found that glxgears works withou errors
This is the error when i try to run "roscore & rosrun rviz rviz" at the last step of the tutorial:

QXcbConnection: XCB error: 147 (Unknown), sequence: 171, resource id: 0, major code: 141 (Unknown), minor code: 20
started roslaunch server http://Mateus-Note:36313/
ros_comm version 1.14.13

SUMMARY
========

PARAMETERS
 * /rosdistro: melodic
 * /rosversion: 1.14.13

NODES

auto-starting new master
process[master]: started with pid [3348]
ROS_MASTER_URI=http://Mateus-Note:11311/

setting /run_id to db01b4d4-c525-11ee-bf81-00155daee43e
process[rosout-1]: started with pid [3359]
started core service [/rosout]
[ INFO] [1707247688.483309600]: Forcing OpenGl version 0.
Segmentation fault

i have also tryed to change the configurations of VcXsrv to -nowgl but it seems to not change anything
Is there any obvious answer or problem that i am not seeing?

**Comment by pseudo-rnd-thoughts** [comment]
How is this an issue with Gym?
