### ISSUE TITLE
[Bug Report] Humanoidv4 doesnt include contact_cost in code, but still present in documentation

### ISSUE THREAD

**Issue by OliEfr** [openai/gym#3268]
In the [documentation for Humanoidv4](https://www.gymlibrary.dev/environments/mujoco/humanoid/) it mentions costs in the reward for the contact forces. They are, however, not present [in the code](https://github.com/openai/gym/blob/master/gym/envs/mujoco/humanoid_v4.py).

For Humanoidv3 I still find the contact forces [in the code](https://github.com/openai/gym/blob/dcd185843a62953e27c2d54dc8c2d647d604b635/gym/envs/mujoco/humanoid_v3.py#L36)

Is the documentation wrong, or am I missing something in the code?

**Comment by Kallinteris-Andreas** [comment]
This bug has been fixed in humanoid version 5 in gymnasium

**Comment by OliEfr** [comment]
> This bug has been fixed in humanoid version 5 in gymnasium

Could you show me where I find the source code for humanoid v5? I don't find it in main branch.

**Comment by Kallinteris-Andreas** [comment]
Please read the read me of this repository.

**Comment by pseudo-rnd-thoughts** [comment]
The code is in 'gymnasium/envs/mujoco/humanoid_v5.py'
