### ISSUE TITLE
ModuleNotFoundError: No module named 'gym.envs.atari'

### ISSUE THREAD

**Issue by eadadi** [openai/gym#3277]
Hey, I know this issue has been asked before, but I haven't been able to solve it using the solution I have seen.

Basically, even on clean environment if I do:
```
pip install gym[atari]
```
Then, doing `import gym.envs.atari` results with
ModuleNotFoundError: No module named 'gym.envs.atari'

Does anyone have an idea?

**Comment by pseudo-rnd-thoughts** [comment]
What version of Atari are you using? It needs to be `ale_py < 0.9`

**Comment by eadadi** [comment]
Hey man, and thanks.
Using (on clean environment):
pip install gym[atari]==0.26.0

leads to having:
pip list | grep ale
<<< ale-py    0.8.1

But the same error stil happens

**Comment by pseudo-rnd-thoughts** [comment]
Ohh, sorry, yeah that was removed in v0.21 I believe. You can find the atari code in `ale_py`

**Comment by eadadi** [comment]
Got you, what was working for me was to manually download and install 0.19 (for some reason doing it via pip was failed), and import ROMS manually

thanks man
