### ISSUE TITLE
Env should provide reward range

### ISSUE THREAD

**Issue by rafaelcp** [openai/gym#33]
In some algorithms like [R-Max](http://jmlr.csail.mit.edu/papers/volume3/brafman02a/brafman02a.pdf) it is necessary to know the maximum reward given at any _single step_ by the environment. Just like continuous state environments provide ranges for each dimension, I suggest that they should provide reward ranges too. Note that it is not the _accumulated reward_ range, but _single step_ reward range.

**Comment by joschu** [comment]
Not a bad idea.

**Comment by danlangford** [comment]
would it make sense for that to be exposed as `env.reward_space` ? to follow suit with `env.action_space` and `env.observation_space` which give shape and bound data around actions and observations

**Comment by gdb** [comment]
Yep, that sounds right to me.

John, what do you think of doing a 1-D box which we extend to also allow \inf and -\inf as bounds?

**Comment by joschu** [comment]
I'm more in favor of calling it reward_range, which defaults to (-np.inf, np.inf)

**Comment by gdb** [comment]
Ok yeah, that sounds better. Don't think we want to imply that it can be more than a scalar.

**Comment by joschu** [comment]
I can't think of any reason why one would care that it's a discrete set.

**Comment by shelhamer** [comment]
Note the Atari environments (and perhaps others) are still at the default (-inf, inf) range.
