### ISSUE TITLE
[Bug Report] Bug title

### ISSUE THREAD

**Issue by ChengYoghurt** [openai/gym#3304]
**Describe the bug**
I used the "CarRacing-v3" environment and set the "continuous=False", and created a stable baseline3 DQR agent to train on it, I got error message like this:
<img width="895" alt="image" src="https://github.com/user-attachments/assets/6e5a04ae-af2a-49b9-b870-50d227351008">

According to the error message, I checked the source code of "class CarRacing", and noticed that:
<img width="684" alt="image (1)" src="https://github.com/user-attachments/assets/fefac6ab-583b-4354-912b-615736d09879">

`action = action.astype(np.float64)`
will be executed even when action is sampled from Discrete Action Space, i.e. when action is an Integer.

**Code example**
`import gymnasium as gym
from gymnasium.spaces import Tuple, Discrete, Box
from stable_baselines3 import PPO, DQN
from stable_baselines3.common.monitor import Monitor
from stable_baselines3.common.vec_env import DummyVecEnv, VecVideoRecorder
import numpy as np

config = {
    "policy_type": "MlpPolicy",
    "total_timesteps": 25000,
    "learning_rate": 0.01,
    "gamma": 0.95, 
    "env_name": "CarRacing-v3",
}

env = gym.make(config["env_name"], render_mode="rgb_array", continuous=False,)
env = Monitor(env)  # record stats such as returns
env = DummyVecEnv([make_env])

# Initialize PPO model
model = DQN(
    "MlpPolicy",  # Use a multi-layer perceptron policy
    env,
    verbose=1,
    learning_rate=config["learning_rate"],
    # n_steps=512,  # Number of steps to run for each environment per update
    gamma=config["gamma"],   # Discount factor
)

# Train DQN
model.learn(total_timesteps=config["total_timesteps"], ),

`

**System Info**
Describe the characteristic of your environment:
 *  my Gym was installed via pip
 * 
 * I ran into this problem on a linux machine
 * Python version=3.12

### Checklist

- [yes] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by pseudo-rnd-thoughts** [comment]
Thank for raising this, it was fixed in https://github.com/Farama-Foundation/Gymnasium/pull/1253 and will be part of Gymnasium v1.1

**Comment by ChengYoghurt** [comment]
I see. Thanks for your prompt help!
