### ISSUE TITLE
[Bug Report] cv2.error: OpenCV(4.9.0) :-1: error: (-5:Bad argument) in function 'cvtColor'

### ISSUE THREAD

**Issue by ZhuShaoQiang** [openai/gym#3305]
**Describe the bug**
BUG detail:
```text
lib/python3.9/site-packages/gym/wrappers/gray_scale_observation.py", line 61, in observation
    observation = cv2.cvtColor(observation, cv2.COLOR_RGB2GRAY)
cv2.error: OpenCV(4.9.0) :-1: error: (-5:Bad argument) in function 'cvtColor'
> Overload resolution failed:
>  - src is not a numerical tuple
>  - Expected Ptr<cv::UMat> for argument 'src'
```
In StackOverflow, some guys said this is a problem about opencv, I changed many version, but it didn't help. And this is more like a random problem, Because I ran this code successfully in the morning, and now it cannot work.

**Code example**
```python
def main():
    world = 1
    stage = 1
    human = False
    env = gym_super_mario_bros.make(f"SuperMarioBros-{world}-{stage}-v0")
    # 设定灰度
    env = GrayScaleObservation(env=env, keep_dim=True)
    # 设定模拟摇杆
    env = JoypadSpace(env, COMPLEX_MOVEMENT)
    # 包裹进一个sb3的env包
    env = DummyVecEnv([lambda: env])

    done = True
    episode = 0
    total_reward = 0
    for step in range(100000):
        if done:
            print(f"第{episode}个episode得了{total_reward}分数.")
            episode += 1
            total_reward = 0
            env.reset()
        state, reward, done, info = env.step(env.action_space.sample())
        total_reward += reward
        if human:
            env.render()
    env.close()
if __name__ == "__main__":
    main()
```

**System Info**
Gym == 0.25.2  (pip install gym==0.25.2)

Linux/Debian

Python version==3.9.20

### Checklist

- [yes] I have checked that there is no similar [issue](https://github.com/openai/gym/issues) in the repo (**required**)

**Comment by pseudo-rnd-thoughts** [comment]
What version of NumPy are you using? I would guess that NumPy 2.0 is incompatible with OpenCV

**Comment by MarcMrw** [comment]
I do have the same problem, and numpy version is <2

**Comment by ZhuShaoQiang** [comment]
> What version of NumPy are you using? I would guess that NumPy 2.0 is incompatible with OpenCV

I tried many versions of numpy. And I finally recreate this environment and it works. I don't know why.
