### ISSUE TITLE
Machine learning to build/simulate environments

### ISSUE THREAD

**Issue by asmith26** [openai/gym#34]
Firstly, I like to thank everyone involved with this project - I believe this has potential to really speed up machine/reinforcement learning progress.

As far as I can tell, this project focuses predominately on experimenting with RL algorithms for achieving a goal in an explicitly defined environment (e.g. the Cartpole environment is hand-written based on physics). I was wondering if there are plans to investigate machine learning algorithms that learn how to best model an environment and agent behaviour within it? I haven't found of such methods being implemented previously, however I feel it is just as an important aspect for progressing machine learning/robots in real world (physical) applications. For example, biology is extremely complicated and I imagine we don't have a good set of equations describing how cancer grows; thus we can't learn how to beat it if we can't model it in the first place.

I hope I'm making sense, and any information of this topic would be greatly appreciated. Not sure if a GitHub issue is the best place to raise this question, but hopefully it can encourage discussion between as wide an audience as possible.

(On a related note, are their any plans to implement more "worthwhile" environments? I agree with the need for generality regarding any designed algorithms, and using simpler environments as a testing platform is useful for quick experimentation, however would it be worthwhile to e.g. implement the equations of nuclear fusion (if this hasn't already been done within another simulation platform) to experiment how to make it more stable? Thanks again for any help in advance!)

**Comment by tlbtlbtlb** [comment]
Model-based RL is a big topic. People have strong preferences between model-free (like Q learning) and model-based approaches. [[arXiv:1509.06824]](http://arxiv.org/abs/1509.06824) has a good example of a model-based approach

It'd be great for domain experts to implement realistic environments.
