### ISSUE TITLE
How to speed up the execution of games to speed up testing?

### ISSUE THREAD

**Issue by james007tia** [openai/gym#342]
How to speed up the execution of games to speed up testing?

**Comment by tlbtlbtlb** [comment]
Are there particular games you think are performing slower than they could?

State-of-the-art game learning often involves tens of machines running for several days.  http://arxiv.org/pdf/1507.04296.pdf describes a parallel implementation that gives human-level performance on Atari games after running on 100 machines for 2-6 days. There's no algorithm known that'll learn games in an hour on a laptop, though any progress towards that goal would be great.

**Comment by ai-tor** [comment]
Well, there are probably better approaches, like A3C, which only requires one CPU with multiple cores: https://arxiv.org/pdf/1602.01783.pdf

**Comment by tlbtlbtlb** [comment]
Since this is more of a research question, I'd suggest joining the debate at https://gitter.im/openai/research, or https://www.reddit.com/r/machinelearning. Reopen if you think there are particular games in Gym with much worse performance than they should have.
