### ISSUE TITLE
Operations & Logistics Problems

### ISSUE THREAD

**Issue by jkarnows** [openai/gym#344]
A few of us would like to contribute to the gym by adding a category for operations and logistics problems. The first problem we have could fit into the 'Toy Text' problems category given that it can be rendered that way and it is similar in nature to the taxi problem, but it could be good to move it later to a new category of similar problems. Any recommendations for us?

**Comment by jkarnows** [comment]
Looks like you can just do a pull request with a new collection present.

**Comment by tlbtlbtlb** [comment]
It's better to make a new repo, following the instructions here: https://github.com/openai/gym/blob/master/gym/envs/README.md.
