### ISSUE TITLE
Run Atari tests on Windows CI

### ISSUE THREAD

**Issue by crizCraig** [openai/gym#360]
Installing Arcade Learning Environment on Windows seems to have somewhat spotty support, but it looks like [this ](https://medium.com/@AtariAnn/running-a-l-e-arcade-learning-environment-0-4-4-on-windows-49f2494b5344#.j21pqbtvd) could work [last updated 2014] and should be tried.
Also see #99

**Comment by christopherhesse** [comment]
Closing in favor of https://github.com/openai/atari-py/pull/50
