### ISSUE TITLE
Facebook MazeBase environments

### ISSUE THREAD

**Issue by anandtrex** [openai/gym#361]
It would be cool to have the Facebook's MazeBase environments included in OpenAI Gym.
Facebook have an [existing implementation](https://github.com/facebook/MazeBase) in lua. Related publication available on [arXiv](http://arxiv.org/abs/1511.07401) and was used to test algorithms like [End-to-end memory networks](http://arxiv.org/abs/1503.08895)

**Comment by christopherhesse** [comment]
We aren't planning on adding more environments to gym, but if there is a gym interface for MazeBase, it would be nice to have a link here: https://github.com/openai/gym/blob/master/docs/environments.md
