### ISSUE TITLE
Object Construction

### ISSUE THREAD

**Issue by Durhamite** [openai/gym#365]
I'm looking mainly at the doom environment but I believe this is an issue for a lot of the environments.  My issues stems mainly from not being able to identify an object.  Lets say, in the doom environment, you walk up to and touch a wall, you currently can't know that as anything...  Or if you get a reward for walking through a door, how would you know that that object is a door if that same reward equates to, say, picking up a health pack.  The same way a human equates the word door to the object door, or a video game large health pack to a medium or small health pack, the AI would also need to be able to do that in some way.  

So my issue/suggestion would be, along with the reward, to add an object number to all interactive objects.  So like touching a wall giving an output of 01, health 02, door 03, enemy 04, projectile 05, weapon 06, etc.  The reward could still be the same but in this way, the AI should be able to interpolate new objects it comes across and guess what type of object it is leading to faster learning and better understanding of new levels/areas,

I think object recognition is crucial to machine learning but without anything relating similar objects, there's no way that the AI can properly and efficiently learn.  Humans have language to relate objects, animals have reward/punishments to relate objects.  But these current environments have nothing, even similar rewards do not relate to similar objects.

Is there a way this could be added to the environments?  I'm a decent programmer with a few other languages but I'm still learning syntax for Python so if someone else could do this it would be greatly appreciated, but if this is something I could do I'd be happy if someone could just point me in the direction on how to start with adding this and I can take it from there.

I appreciate any feedback.

**Comment by christopherhesse** [comment]
I think you could perceive game state instead of pixels, the way the mujoco tasks do.  I don't think we're planning on adding this to existing pixel based gym environments though.
