### ISSUE TITLE
change the control of pong

### ISSUE THREAD

**Issue by wwxFromTju** [openai/gym#370]
hi, all:
I want to change the control of pong to one player to two player. How i can make is idea? I read the site-package, the file is bin.so i hope can find the way to change it.
because i am china student, so my english is poor.

**Comment by hs105** [comment]
your english is not bad at all!

looks it's not supported now. Multi-agent is openai's future directions in their white paper. Can someone reply this? I am interested to know too.

**Comment by tobegit3hub** [comment]
Multi-agent is also mentioned in OpenAI universe as well.

Really looking forward to this feature 😃
