### ISSUE TITLE
Support for continuous control environments based on FREE 3D physics simulator rather than MuJoCo

### ISSUE THREAD

**Issue by peterzcc** [openai/gym#373]
Hi there,

I'm doing research in reinforcement learning in continuous control. I found that all the continuous control tasks needs support from the MuJoCo engine, whose license is extremely expensive.

May I ask if anyone has implemented the tasks like 'Ant' based on other engines like ODE or Bullet? I think it would be beneficial to get rid of the exclusive requirement on physics engine, and I will start working on it if others haven't done it yet.

Best,
Peter

**Comment by olegklimov** [comment]
There is a work going on, exactly on that. For now, please use `LunarLander`, `BipedalWalker`, `BipedalWalkerHardcore`, `CarRacing`, those all are continuous control environments, without dependencies on proprietary physics engines.

**Comment by peterzcc** [comment]
Hi @olegklimov ,

Thanks a lot for your reply! Do you know whose is working on that? I'm quite willing to help on the project since my research focuses on hierarchical reinforcement learning tasks which are not present now, like the  'Ant-Gather' and 'Ant-Maze' environment proposed by rllab.

Peter

**Comment by olegklimov** [comment]
Hello @peterzcc do you volunteer to help with beta testing? :)  I'll have you in mind. Please post some of your results here https://gym.openai.com/algorithms

**Comment by peterzcc** [comment]
@olegklimov sure. I'm just planning to upload some data to the leaderboard after I have some results.

**Comment by tbreloff** [comment]
I have similar interest in this.  I was thinking about extending BipedalWalker with feet to start.  I'm just curious whether you're interested in any particular extensions and if you have anything in-progress that I should know about.  Thanks.

**Comment by olegklimov** [comment]
Simulator based on Bullet coming out very soon. Probably will ask for beta-testing. Please post link to any of your RL video if you want beta test version.

**Comment by peterzcc** [comment]
@tbreloff I have tried to develop upon  [PGE](https://github.com/222464/PGE) but didn't successfully install it while its developers have suspended the updates.

**Comment by zuoxingdong** [comment]
@olegklimov  Would the new simulator based on Bullet contains tasks like Humanoid and Reacher in Mujoco ?

**Comment by Phylliade** [comment]
+1 !

**Comment by olegklimov** [comment]
We're releasing soon.

**Comment by benelot** [comment]
@tbreloff: If you can provide a mujoco file for your Bipedal Walker and some of your ideas of what reward signals you would want to have for learning, then we can easily include your work. If you already have a complete mujoco implementation, then just provide that, we can port it.

@zuoxingdong Yes, it will simply include all currently available mujoco environments, just without using mujoco as the physics engine.

**Comment by olegklimov** [comment]
https://github.com/openai/roboschool

Hope you like it.
