### ISSUE TITLE
Minimal example for learning from pixels

### ISSUE THREAD

**Issue by Tomakko** [openai/gym#374]
Hi everyone,

am I missing it somewhere or it is nowhere mentioned how to actually get the raw, greyscale/rgb pixel data from the environments?

Am I suppose to call `render` with `mode=rgb_array` and used the returned value?

Cheers,
Martin

**Comment by tlbtlbtlb** [comment]
The atari and doom environments give pixels in their observations (ie, the return value from `step`). I don't think any other ones do.

`render` produces different results on different OSes, so they're not part of any official environment for benchmarking purposes. But if you want to create a new environment where the observation is in pixels, you could implement it by wrapping an existing environment and calling `render`.

**Comment by Tomakko** [comment]
Thank you for your response.

In the Paper
 https://arxiv.org/abs/1509.02971
they compared performance after learning from low-level features and from pixels using the mujoco environments. 

Is there a way to extract pixel info from those environments, too?

**Comment by tlbtlbtlb** [comment]
The code that Lillicrap et al. used in that paper hasn't been released, and Gym doesn't have an implementation of pixels-as-observation for Mujoco environments. If you'd like to work on adding it, I'm sure a lot of people would find it useful. Especially if you could make the observation as similar as possible to the Lillicrap work, by taking 3 consecutive images and downsampling to 64x64, etc.

The file [gym/envs/README.md](https://github.com/openai/gym/blob/master/gym/envs/README.md) has guidance on how to create new environments.

**Comment by sumethy** [comment]
@Tomakko I made a crude version of this, please see the gym repo I forked at sumethy/gym
the readme is in /gym/envs/GET_PIXELS_AS_OBSERVATION_MUJOCO.md

**Comment by christopherhesse** [comment]
Closing in favor of https://github.com/openai/gym/pull/1499
