### ISSUE TITLE
gym.spaces is not imported until gym.make(...) is called

### ISSUE THREAD

**Issue by admcrae** [openai/gym#376]
Attempting to access the `gym.spaces` package before ever calling `gym.make()` gives `AttributeError: module 'gym' has no attribute 'spaces'`. Calling `dir(gym)` immediately after importing gives
```
['ActionWrapper', 'Env', 'ObservationWrapper', 'RewardWrapper', 'Space', 'Wrapper', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'benchmark_spec', 'benchmarks', 'configuration', 'core', 'distutils', 'envs', 'error', 'logger', 'logging', 'make', 'monitoring', 'reraise', 'sanity_check_dependencies', 'scoreboard', 'spec', 'sys', 'undo_logger_setup', 'upload', 'utils', 'version']
```
while calling it after `gym.make("Pendulum-v0")` gives
```
['ActionWrapper', 'Env', 'ObservationWrapper', 'RewardWrapper', 'Space', 'Wrapper', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', 'benchmark_spec', 'benchmarks', 'configuration', 'core', 'distutils', 'envs', 'error', 'logger', 'logging', 'make', 'monitoring', 'reraise', 'sanity_check_dependencies', 'scoreboard', 'spaces', 'spec', 'sys', 'undo_logger_setup', 'upload', 'utils', 'version']
```
I have tested with the latest master in python 3 (I got the same error in python 2 with an older version).

This is a problem when running unit tests on code that needs to interact with gym spaces (e.g. code that checks whether an object is a certain subclass of `gym.Space`).

**Comment by tlbtlbtlb** [comment]
If your code references `gym.spaces`, you should import it directly with `import gym.spaces`.
