### ISSUE TITLE
Docs refer to deprecated 'writeup' upload parameter

### ISSUE THREAD

**Issue by colinmorris** [openai/gym#381]
Attempting to call upload with `writeup` set fails, complaining that `writeup` is deprecated in favour of `algorithm_id`. [The docs](https://gym.openai.com/docs#evaluations) still refer to it though.

Also, I don't understand _why_ the writeup parameters is rejected. The web UI still allows you to attach a writeup (even if you have a linked algorithm).

**Comment by christopherhesse** [comment]
The web UI doesn't exist anymore, closing this issue.
