### ISSUE TITLE
Environment behaviour should be consistent across python versions - use one rollout file for py2 and py3

### ISSUE THREAD

**Issue by colinmorris** [openai/gym#387]
Having separate files gives an opportunity for some [bugs](https://github.com/openai/gym/pull/383#issuecomment-255482977) to creep in. 

Currently the only two envs that have different hashes between py2 and py3 are `OneRoundNondeterministicReward-v0` and `TwoRoundNondeterministicReward-v0` (and they differ only in rewards).

**Comment by tlbtlbtlb** [comment]
Indeed, having just one file would be wonderful. Beware the details. In particular, the hashes are of things like `str(observations)`, and for numpy arrays this includes newlines and indenting. I think the original reason for the py2/py3 split had to do with the `u'xxx'` format for unicode strings, but that seems to be fixed now. So a big thumbs up on fixing this.

**Comment by colinmorris** [comment]
Fixed in #386
