### ISSUE TITLE
mujoco environments errors

### ISSUE THREAD

**Issue by shaneshixiang** [openai/gym#388]
Ant-v1  ValueError: b'torso' is not in list
Reacher-v1 ValueError: b'fingertip' is not in list

Other domains work. Thanks!

**Comment by tlbtlbtlb** [comment]
This doesn't happen in our tests. Could you provide more details: version of Python, version of Gym, complete stack trace, etc.

**Comment by shaneshixiang** [comment]
Python version: Python 3.5.2 |Anaconda 4.2.0 (x86_64)
Gym version: gym 0.4.0

Essentially, line below in get_body_com, mujoco_env.py fails. Called from ant.py and reacher.py.
 idx = self.model.body_names.index(six.b(body_name))

Thanks!

**Comment by tlbtlbtlb** [comment]
I can't reproduce this, either with gym-0.4.0 or gym-0.4.9 (latest). Perhaps you have an old version of Mujoco or mujoco_py?

Could you report the result of this script:
```
import gym
import mujoco_py
print(mujoco_py.config.mjpro_path)
e=gym.make('Ant-v1')
print(e.model.body_names)
print(e.reset())
print(e.step(e.action_space.sample()))
```

**Comment by shaneshixiang** [comment]
Thanks! Problem was with mujoco_py. rllab had local mujoco_py and it was using that instead.
