### ISSUE TITLE
new environment file structure

### ISSUE THREAD

**Issue by gpldecha** [openai/gym#390]
Would it make sense to add  a test folder to the proposed structure of  a new environment: [How to create new environments for Gym](https://github.com/openai/gym/tree/master/gym/envs) ?
Proposition:

``` sh
  gym-foo/
    README.md
    setup.py
    gym_foo/
      __init__.py
      envs/
        __init__.py
        foo_env.py
        foo_extrahard_env.py
      test/
          foo_test.py
```

**Comment by tlbtlbtlb** [comment]
Yes. (To fit our nose2 convention, the file ought to be `test_foo.py`.)

Additionally, I'd propose enhancing `gym/gym/envs/tests/test_envs_semantics.py` to operate as a module accepting another `rollout.json` file from an add-on package. So other gym add-on packages can add similar tests. And documentation for `gym/scripts/generate_json.py` for how to set it all up.

**Comment by gpldecha** [comment]
Thanks for the reply, I am currently writing an environment: [gym-leftright](https://github.com/gpldecha/gym-leftright).

Would it make sense to have a standalone repo with an environment skeleton with all documentation regarding testing, deployment and how to make it an add-on package ?

**Comment by gpldecha** [comment]
?

**Comment by tlbtlbtlb** [comment]
On the standalone template repo: maybe, but not high priority right now. We're working on a more extensible framework for new environments which will simplify the process.

Does gym-leftright work? Do you have agents that solve it? If you have a baseline solution we can consider adding it to the public scoreboard.

**Comment by gpldecha** [comment]
Ok regarding priority

[gym-leftright](https://github.com/gpldecha/gym-leftright) works, it is a simple environment used in a few papers for presenting concepts. Discrete state Q-learning can solve it as the state space is small.

**Comment by christopherhesse** [comment]
I've moved the creating environments page to https://github.com/openai/gym/blob/master/docs/creating-environments.md

It might be worth replacing the link to `gym-soccer` with `gym-leftright` if it's a more clear starting point.
