### ISSUE TITLE
blackjack environment (and others?) use numpy types which are not JSON serializable

### ISSUE THREAD

**Issue by currymj** [openai/gym#400]
I ran into this problem because I was trying to use the REST server with the Blackjack-v0 environment. It isn't possible to json serialize its outputs which are often numpy.int64 rather than python int. This can result in some pretty confusing error messages.

 I have some local fixes to make things work for me, but what is the correct approach here?

1. Environments can use whatever numpy types they want, it's up to the client to handle them. If this is the case then there will need to be some changes to the `to_jsonable` and `from_jsonable` methods in some of the classes descending from `Space`. Other changes would also be required in `gym-http-api` to handle the weird cases. Is there anything else that would need to be done in the main `gym` repo?
2. Environments must output types that can be serialized to JSON. This would require wrapping up lots of return values in the environments with simple conversion functions like `.item()` or `int()`.

Whichever approach is better, it should be a pretty simple fix and I can open a PR.

**Comment by tlbtlbtlb** [comment]
I think the right approach is adding a `to_jsonable` and `from_jsonable` to `gym.space.Discrete`. They should convert numpy int arrays to lists of regular python ints.

**Comment by tlbtlbtlb** [comment]
Fixed in b5108b384ed1e29f3d241d654666b8e347f0f7b9
