### ISSUE TITLE
Ball does not appear without FIRE action in Atari Breakout environment 

### ISSUE THREAD

**Issue by NachoKim** [openai/gym#401]
Breakout have following action space
['NOOP', 'FIRE', 'RIGHT', 'LEFT', 'RIGHTFIRE', 'LEFTFIRE']

The ball in the Breakout atari game does not appear until one of ['FIRE', 'RIGHTFIRE', 'LEFTFIRE'] actions is executed.
I understand this FIRE action make the game start for human player, but this is unnecessary in learning procedure.

**Comment by tlbtlbtlb** [comment]
It may be unnecessary, but a reasonable learning algorithm shouldn't have much trouble learning it. Changing the semantics of an environment makes new researcher's results not comparable to old results, so we avoid changing them unless there's a compelling reason.

**Comment by koulanurag** [comment]
May I know the right place to look for description of each action in a specific environment?

Thanks for any reference

**Comment by tlbtlbtlb** [comment]
The games themselves aren't documented anywhere. You can play them using the the emulator Stella to understand what the controls do.
