### ISSUE TITLE
BlackJack environment

### ISSUE THREAD

**Issue by peroyose** [openai/gym#405]
There is a bug in the BlackJack environment "https://github.com/openai/gym/blob/master/gym/envs/toy_text/blackjack.py". I always win  if I stay (action=0).

After changing the cmp function in the file it works. New cmp-function:

    def cmp(a, b):
        return float(a > b) - float(a < b)

**Comment by tlbtlbtlb** [comment]
This was probably caused when we switched to the numpy RNG. It returns `np.int64` instead of int, and when you compare them you get an `np.bool`, which doesn't convert to int when you subtract the same way Python's bool does.

Thanks @peroyose, fixed in b5108b384ed1e29f3d241d654666b8e347f0f7b9.
