### ISSUE TITLE
More discreet environments (Box2D)

### ISSUE THREAD

**Issue by olegklimov** [openai/gym#41]
Hello,

I've found very few discreet environments to play with. It's MountainCar and CartPole, that's all, if you don't count Atari. All MuJoCo games have continuous actions.

I happen to have a few Box2D reinforcement learning environments, that I want to port. I think it's a good idea because Box2D is open-source, easy to install (pip install box2d) like the rest of gym. Should be a good start for new people.

1) CartPole swing up, physics, friction, more reward if kept in center (3 actions).

2) MoonLander (6-wide state, 4 actions).

3) PipedalWalker (16-wide state, 4 actuated joints, 3*3*3*3=81 actions).

Greg, John please tell me if you don't need it and not going to merge it, I'll stop.

**Comment by rickhenderson** [comment]
Have you posted code for your environments? Maybe if people saw them and tried them out then more people would request they get added. I'm new here so just throwing out suggestions.

**Comment by joschu** [comment]
+1: a good first step would be to post the code somewhere, e.g., in it's own github repo.
I'd recommend creating the envs with continuous action spaces. If people need discrete actions, they can discretize themselves.

**Comment by olegklimov** [comment]
Please someone test if it works for you.

https://github.com/olegklimov/gym/commits/box2d

I'll make one or two more environments and publish a PR.

**Comment by olegklimov** [comment]
To test, run one of these:

```bash
python examples/agents/keyboard.py LunarLander-v0
python examples/agents/keyboard.py CartPoleSwingUp-v0
```

You should get be able to play from keyboard like this:

https://youtu.be/ZTlpZSN5gdA

I don't have a working learning agent at hand, cannot test reward and states of this two environments. If you have, please give it a try.

**Comment by joschu** [comment]
These are nice! I'm running learning algorithms on them now.

**Comment by jonasschneider** [comment]
These are really cool. Can you open a PR so we can start discussing the code? (In particular, I'm wondering if we can make Box2D installation any easier.)

**Comment by joschu** [comment]
What's the reward function for lunar lander? I'm getting the following behavior, is it optimal?
[openaigym.video.0.24.video035000.mp4.zip](https://github.com/openai/gym/files/247258/openaigym.video.0.24.video035000.mp4.zip)
My algorithm didn't solve cart-pole swing-up, but maybe that's just because it's not exploring well enough. Have you verified that it's possible to solve with keyboard control in the allotted timesteps?

**Comment by jonasschneider** [comment]
I think the reward function might be missing a component that forces you to land eventually, e.g. a "running out of fuel", or maybe the alive penalty just has to be higher.

Could also imagine penalizing high accelerations, high distances from the helipad, and/or forceful/non-upright ground impact.

**Comment by olegklimov** [comment]
> Could also imagine penalizing high accelerations, high distances from the helipad, and/or forceful/non-upright ground impact.

`shaping = - abs(state[0]) - abs(state[1]) - abs(state[2]) - abs(state[3]) - abs(state[4])`

It is distance from helipad (`state[0]` and `state[1]`), high speed (`state[2]` and `state[3]`) and high angular velocity (`state[4]`).

Total potential change from top of the screen to target is about 1.4, i.e. to get to helipad and have zero speed is about 1.4 total reward. On landing (body not awake) it receives additional +1. On crash, -1.

I'm not saying it has no bugs, sure there's something. 

> I'm getting the following behavior, is it optimal

Optimal is to come down and get zero speed (+1.4) and land (another +1). Solved is more than 2.0. Hopefully.

**Comment by olegklimov** [comment]
> Can you open a PR

I'm working on third environment (with normal and hardcore version), then I'll make another branch (I noticed botched merge on current branch) and PR.

**Comment by olegklimov** [comment]
https://github.com/openai/gym/pull/54

**Comment by gdb** [comment]
(#54 is merged; closing issue.)

**Comment by Rokas98765** [comment]
Is there any chance anyone would know why I'm getting this error? 'pip install gym' worked but it only installed 3 environments, when I try to install 'pip install box2d' this error comes up:

![image](https://user-images.githubusercontent.com/33398705/32417098-eb8b6cac-c24b-11e7-939b-85e1063ffb8d.png)
