### ISSUE TITLE
Issue with different results with/without Monitor

### ISSUE THREAD

**Issue by geffy** [openai/gym#410]
Hi! 
I faced a problem: results from running with and without monitor are different.
I found this under FrozenLake8x8, but believe that the same issue may occur under other (stochastic) env.

There is a reproducing script: https://gist.github.com/geffy/a999ae87bd0f2835c6dd981f66b49606

After some investigation I found that the problem in the constant `timestep_limit`.
It's checked only in the Monitor, but, in my opinion,  it should be checked in an instance of Env.

Workaround for this problem is just use `max_steps = env.spec.timestep_limit`

**Comment by DollarAkshay** [comment]
I agree with this. The `timestep_limit` should be checked even when the monitor isnt running

**Comment by quazar42** [comment]
I'm facing the same issue in the CartPole-v0, seems like the maximum episode length is being capped at the record frequency.

**Comment by nottombrown** [comment]
Good timing. We've just started working on a fix for this. We need a maximum episode length when running with the monitor in order to get scores correctly.

The current plan is to add a new `TimeLimit` Wrapper that enforces a maximum length, and can be used independently of the monitor. This will allow us to have identical runs whether or not the monitor is running.

**Comment by quazar42** [comment]
I just tried the new wrapper but I'm facing the same issue, the maximum episode length seems to be capped at 200 frames.

**Comment by nottombrown** [comment]
Ah yes, the new wrapper doesn't yet fix this issue. 

I have a PR that I'm working on that will extract the TimeLimit logic from the monitor, so that we can choose whether or not to add the limit independently of the monitor: https://github.com/openai/universe/pull/82

**Comment by quazar42** [comment]
Aah ok, thank you! =D

**Comment by tlbtlbtlb** [comment]
This should be fixed by the TimeLimit wrapper, which is in gym 0.8.0.
