### ISSUE TITLE
0 and N/A Scores in Leaderboards

### ISSUE THREAD

**Issue by ryanpeach** [openai/gym#412]
It seems that leaderboards are prioritizing new algorithms, and non ML algorithms (such as simple control algorithms). It has a lot of repeat posts, and a lot of N/A posts. I have a few suggestions:

1. Review's should be turned into a kind of voting system, or stars, for quick read throughs of the writeup.
2. Each user should only have one unreviewed post to each leaderboard. New posts by a user should discard old posts.
3. Each leaderboard should have tagging, creating "categories" of algorithms, such as control, ML, etc. This allows Q learners to be capable of being compared either to "All ML Algorithms" or "Other Q Learners."

**Comment by christopherhesse** [comment]
Thanks for the feedback but the scoreboard isn't active anymore, so I am closing this issue.
