### ISSUE TITLE
The "down" action (action ID 5) in Asteroids-v0 and v3 makes your ship vanish / jump randomly around the screen 

### ISSUE THREAD

**Issue by mpgussert** [openai/gym#421]
Greetings all!

My exploration of the asteroids environment is unending.  See title.  I have discovered a bug in this environment which makes the down action exhibit unexpected behavior.  below is a minimum working example
```
  import gym
   
  env = gym.make("Asteroids-v3")
  env.reset()
  for i in range(10000):
     env.render()
     env.step(5)
```

this makes the ship either vanish or jump sporadically around the screen.  What is up with that yo?!  I haven't looked into a solution yet.  My AIs just learn to never press that button lol

**Comment by tlbtlbtlb** [comment]
I believe that's the hyperspace button. https://en.wikipedia.org/wiki/Asteroids_%28video_game%29. Human players learn to only press it in an emergency, since it might put you in a worse situation.

**Comment by mpgussert** [comment]
http://s2.quickmeme.com/img/8e/8e0813df4bec36536b438ee50ddf38ff0ef237f6dc7a55ef47ae60d5f81ee51f.jpg
