### ISSUE TITLE
Scoreboard Mechanics

### ISSUE THREAD

**Issue by DavidSanwald** [openai/gym#426]
For me the scoreboards are a nice place to look for something, to learn from or get inspired. Especially the entries with shared code are helpful. 
Right now the boards have only one page (or am I overlooking something?) and if there are many evaluations, sometimes 90% of the board consists of 0 point evaluations with no shared code or writeup.

I don't care for the boards in terms of ranking or competition but I think maybe there could be a better way to make it easier to find working code or code with interesting shared implementations.

**Comment by DanielTakeshi** [comment]
I think the problem with this is that anyone can upload their results from any trial, and then those results get put on the pages even if that trial was a simple 2-episode toy case not intended for serious experimentation.

**Comment by christopherhesse** [comment]
The scoreboard isn't active anymore, closing this issue.
