### ISSUE TITLE
[Ubuntu, Atari] Error while downloading atari

### ISSUE THREAD

**Issue by SeungyounShin** [openai/gym#431]
I use Ubuntu and I just typed 
"sudo pip install -e .[atari]"
However, I got .... and below is the part of error log
`Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-fqagdxow/atari-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-se3htidd-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-fqagdxow/atari-py/
`
p.s
cmake version 3.5.1
numpy version 1.11.2
pip version 9.0.1

**Comment by tlbtlbtlb** [comment]
The file it mentions, `/tmp/pip-se3htidd-record/install-record.txt`, will have more clues.

**Comment by SeungyounShin** [comment]
@tlbtlbtlb  I can't open  /tmp/pip-se3htidd-record/install-record.txt ... 
I tried with the other command " sudo pip install gym[all]" of course I got error 
below is what I got
`Requirement already satisfied: gym[all] in /usr/local/lib/python2.7/dist-packages
Requirement already satisfied: numpy>=1.10.4 in /usr/local/lib/python2.7/dist-packages (from gym[all])
Requirement already satisfied: requests>=2.0 in /usr/local/lib/python2.7/dist-packages (from gym[all])
Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (from gym[all])
Requirement already satisfied: pyglet>=1.2.0 in /usr/local/lib/python2.7/dist-packages (from gym[all])
Collecting PyOpenGL (from gym[all])
Collecting box2d-py (from gym[all])
  Downloading box2d-py-2.3.1.tar.gz (425kB)
    100% |████████████████████████████████| 430kB 1.5MB/s 
Collecting keras (from gym[all])
  Downloading Keras-1.2.0.tar.gz (167kB)
    100% |████████████████████████████████| 174kB 2.1MB/s 
Collecting theano (from gym[all])
  Downloading Theano-0.8.2.tar.gz (2.9MB)
    100% |████████████████████████████████| 2.9MB 393kB/s 
Collecting atari_py>=0.0.17 (from gym[all])
  Downloading atari-py-0.0.18.tar.gz (750kB)
    100% |████████████████████████████████| 757kB 1.1MB/s 
Collecting Pillow (from gym[all])
  Downloading Pillow-3.4.2-cp27-cp27mu-manylinux1_x86_64.whl (5.6MB)
    100% |████████████████████████████████| 5.6MB 239kB/s 
Collecting pachi-py>=0.0.19 (from gym[all])
  Downloading pachi-py-0.0.21.tar.gz (1.1MB)
    100% |████████████████████████████████| 1.1MB 938kB/s 
Collecting mujoco_py>=0.4.3 (from gym[all])
  Downloading mujoco-py-0.5.7.tar.gz
Collecting imageio (from gym[all])
  Downloading imageio-2.1.0.zip (3.3MB)
    100% |████████████████████████████████| 3.3MB 342kB/s 
Collecting pyyaml (from keras->gym[all])
  Downloading PyYAML-3.12.tar.gz (253kB)
    100% |████████████████████████████████| 256kB 1.4MB/s 
Collecting scipy>=0.11 (from theano->gym[all])
  Downloading scipy-0.18.1-cp27-cp27mu-manylinux1_x86_64.whl (40.3MB)
    100% |████████████████████████████████| 40.3MB 37kB/s 
Installing collected packages: PyOpenGL, box2d-py, scipy, theano, pyyaml, keras, atari-py, Pillow, pachi-py, mujoco-py, imageio
  Running setup.py install for box2d-py ... error
    Complete output from command /usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4GRnuY/box2d-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-H0hQUN-record/install-record.txt --single-version-externally-managed --compile:
    Using setuptools (version 32.1.2).
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-2.7
    creating build/lib.linux-x86_64-2.7/Box2D
    copying library/Box2D/__init__.py -> build/lib.linux-x86_64-2.7/Box2D
    copying library/Box2D/Box2D.py -> build/lib.linux-x86_64-2.7/Box2D
    creating build/lib.linux-x86_64-2.7/Box2D/b2
    copying library/Box2D/b2/__init__.py -> build/lib.linux-x86_64-2.7/Box2D/b2
    running build_ext
    building 'Box2D._Box2D' extension
    swigging Box2D/Box2D.i to Box2D/Box2D_wrap.cpp
    swig -python -c++ -IBox2D -small -O -includeall -ignoremissing -w201 -globals b2Globals -outdir library/Box2D -keyword -w511 -D_SWIG_KWARGS -o Box2D/Box2D_wrap.cpp Box2D/Box2D.i
    unable to execute 'swig': No such file or directory
    error: command 'swig' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-4GRnuY/box2d-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-H0hQUN-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-4GRnuY/box2d-py/
`

**Comment by tlbtlbtlb** [comment]
You need swig. Run `brew install swig`. 

If that doesn't entirely fix it, run
```
sudo pip install -v --no-clean gym[all]
```
and it won't erase the error log files in /tmp

**Comment by SeungyounShin** [comment]
I installed swig and run 'sudo pip install -v --no-clean gym[all]' 
but I couldn't still run openai... 
when I typed "sudo pip install -e .[atari]' or several other command I always got same errors

**Comment by tlbtlbtlb** [comment]
I'm confused. Can you cut and paste an exact transcript of what you did and what error message you got?

**Comment by iamsarthakk** [comment]
I am facing similar problem. I think there is a syntax error in tmp/pip-build-QEnfZM/mujoco-py/setup.py not sure though.
