### ISSUE TITLE
Building gym in virtualenv failure at pachi_py

### ISSUE THREAD

**Issue by sarodz** [openai/gym#437]
I have cloned pachi_py and tried to run `python setup.py install` however I got the following error:
"Could not build pachi-py: Command 'cd pachi_py; mkdir -p build && cd build && cmake ../pachi && make -j4' returned non-zero exit status 1"

I am using Mingw32 and I tried the script setup is using directly in the folder. 
So `cd pachi_py; mkdir -p build && cd build && cmake ../pachi` part works without any issue but when I try to do make -j4 I get the following messages:

[after I cloned the pachi_py files, I have put them in a temp file in a different location]

mkdir -p build && cd build && cmake ../pachi && make -j4
-- Configuring done
-- Generating done
-- Build files have been written to: C:/PlayZone/AIGym/temp/pachi_py/build
make[1]: Entering directory `/c/PlayZone/AIGym/temp/pachi_py/build'
make[1]: warning: -jN forced in submake: disabling jobserver mode.
make[1]: *** No targets specified and no makefile found.  Stop.
make[1]: Leaving directory `/c/PlayZone/AIGym/temp/pachi_py/build'
make: *** [build] Error 2

So looking into this error I found that this is caused by a missing Makefile. And when I check /c/PlayZone/AIGym/temp/pachi_py/build I infact do not see one. What would be the appropriate Makefile? [ I am working in Windows10]

**Comment by tlbtlbtlb** [comment]
The Makefile should be created by cmake. It doesn't look like your cmake is doing anything. Here's what happens on my system (OSX):

```
zagreb pachi_py$ pwd
/Users/tlb/openai/pachi-py/pachi_py
zagreb pachi_py$ ls
Makefile		cypachi.h		exceptions.hpp		goutil.cpp		pachi
__init__.py		cypachi.cpp		cypachi.pyx		extra_unused.pyx	goutil.hpp		ptr.hpp
zagreb pachi_py$ mkdir -p build && cd build && cmake ../pachi
-- The C compiler identification is AppleClang 8.0.0.8000042
-- The CXX compiler identification is AppleClang 8.0.0.8000042
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'Release' as none was specified.
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/tlb/openai/pachi-py/pachi_py/build
zagreb build$ ls
CMakeCache.txt		CMakeFiles		Makefile		cmake_install.cmake	lib
zagreb build$ make
Scanning dependencies of target pachi
[  2%] Building C object CMakeFiles/pachi.dir/board.c.o
/Users/tlb/openai/pachi-py/pachi_py/pachi/board.c:392:1: warning: control may reach end of non-void function [-Wreturn-type]
}
^
1 warning generated.
[  4%] Building C object CMakeFiles/pachi.dir/chat.c.o
[  6%] Building C object CMakeFiles/pachi.dir/distributed/distributed.c.o
[  8%] Building C object CMakeFiles/pachi.dir/distributed/merge.c.o
[ 10%] Building C object CMakeFiles/pachi.dir/distributed/protocol.c.o
[ 12%] Building C object CMakeFiles/pachi.dir/fbook.c.o
[ 14%] Building C object CMakeFiles/pachi.dir/gtp.c.o
...
```

Some things to try:

   If your cmake version (`cmake --version`) is older than 3.7.1, upgrade it.

   Make sure to start with an empty build directory each time you try building.

   Does cmake create any files in that build directory?

   Cmake should look at ../pachi/CMakeLists.txt to do its job. Does that file exit?

   Try more debugging output. `cmake --trace ../pachi`

**Comment by tlbtlbtlb** [comment]
Assuming fixed.

**Comment by KthProg** [comment]
I'm having this issue as well
