### ISSUE TITLE
about gym installation

### ISSUE THREAD

**Issue by encore2020** [openai/gym#438]
Hi, I have reinstalled operation software of Ubuntu 16.

After doing all download, I found that there is no gym folder in the desk.
When I use import gym , the error of no gym will appear.

How is gym folder downloaded?  How can I solve the problem?

**Comment by DollarAkshay** [comment]
You seem to be really new to Ubuntu. Its operating system not operation software.

If you download something via pip it dosent install everything on the Desktop. Please try installing everything again by reading the Documentation carefully.

Here is the link : https://gym.openai.com/docs
