### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'None'

### ISSUE THREAD

**Issue by wjb123** [openai/gym#439]
When I install some dependencies for gym, I test my installation. The test code always report the bug "ValueError: invalid literal for int() with base 10: 'None' ", I know it is caused by pyglet, and When I uninstall nvidia-*, there is no bug. And I run  glxinfo | grep 'version' as https://github.com/openai/gym/issues/403, there has the bug "Error: couldn't find RGB GLX visual or fbconfig, Error: couldn't find RGB GLX visual or fbconfig", how can I get rid of it ?

**Comment by tlbtlbtlb** [comment]
Gym needs GLX (OpenGL for X windows) to display renderings. It's pre-installed on OSX and most Linux desktop systems. You didn't say what OS you have, but if you google for installing GLX on it there should be answers.

**Comment by wjb123** [comment]
I am using the ubuntu14.04, i install the GLX, but has the same error.

**Comment by tlbtlbtlb** [comment]
If GLX is correctly installed, running `glxinfo` will show something like
```
name of display: /private/tmp/com.apple.launchd.ts0KGCZLW8/org.macosforge.xquartz:0
display: /private/tmp/com.apple.launchd.ts0KGCZLW8/org.macosforge.xquartz:0  screen: 0
direct rendering: Yes
server glx vendor string: SGI
server glx version string: 1.4
server glx extensions:
    GLX_ARB_multisample, GLX_EXT_import_context, GLX_EXT_visual_info,
    GLX_EXT_visual_rating, GLX_OML_swap_method, GLX_SGIS_multisample,
    GLX_SGIX_fbconfig
client glx vendor string: Mesa Project and SGI
client glx version string: 1.4
```

After installing GLX you have to restart your X11 server (log out and log back in) to make it work.

**Comment by wjb123** [comment]
Thank  you，I finally solve it as you say.

**Comment by Maoquan232** [comment]
I have a Ubuntu server which is connected to my local computer( Windows 7 ) by the software MobaXterm.  I have the same issue when I am running following code：
### 
    import gym
    env=gym.make('CartPole-v0')
    env.reset()
    env.render() 

The interesting things is my friend can run it correctly in his computer and we both visit the Ubuntu serve by MobaXterm with the same software settings.

I guess it is because something lack in my Windows(Perhaps OpenGL problem or something else？) Can you give some advice to help fixing it?

**Comment by WangXin93** [comment]
> I have a Ubuntu server which is connected to my local computer( Windows 7 ) by the software MobaXterm. I have the same issue when I am running following code：
> 
> ```
> import gym
> env=gym.make('CartPole-v0')
> env.reset()
> env.render() 
> ```
> The interesting things is my friend can run it correctly in his computer and we both visit the Ubuntu serve by MobaXterm with the same software settings.
> 
> I guess it is because something lack in my Windows(Perhaps OpenGL problem or something else？) Can you give some advice to help fixing it?

I fix it on mac by **+extension GLX**, follow this link <https://unix.stackexchange.com/questions/429760/opengl-rendering-with-x11-forwarding>, maybe the problem is on the windows machine.
