### ISSUE TITLE
Documentation for monitoring is out-of-date

### ISSUE THREAD

**Issue by yonilx** [openai/gym#444]
The [documentation](https://gym.openai.com/) for using the monitor feature still states the old monitoring feature and not the new wrapper. I've found the correct way to use the monitoring only [here](https://github.com/openai/gym/blob/master/examples/agents/cem.py).
This can easily confuse newcomers and should be updated when possible.

**Comment by nottombrown** [comment]
Good eye, thanks! Updated docs are up now: https://gym.openai.com/docs

**Comment by nottombrown** [comment]
Ah I see there's another location. Fixing now

**Comment by nottombrown** [comment]
Updated https://gym.openai.com/
