### ISSUE TITLE
Is it possible to save video files and results without rendering during training?

### ISSUE THREAD

**Issue by hipoglucido** [openai/gym#454]
Hello, I am trying to save the video files and results (so I can upload them afterwards) without rendering during training, because I am using a server and I cannot install xvfb). Weird thing is that it only saves de video files it I set `video_callable=False` in the call `wrappers.Monitor()` (while testing on my laptop). Otherwise it doesn't rise up any error, but it doesn't write the video files nor the result files, so I can't upload them.

How can get the video and result files without rendering during training?

Thanks

**Comment by tlbtlbtlb** [comment]
You need xvfb in order to generate movies. The movies are made by rendering each frame (using OpenGL or X11 drawing commands, depending on the enviroment), then capturing the frame buffer and piping it to ffmpeg.

Does `apt-get install xvfb` not work? What OS are you on?

**Comment by olegklimov** [comment]
In fact, it's entirely up to environment to process `render('rgb_array')`. You can create your own environment that renders into numpy array without X. But most of the existing environments require X or OpenGL. So it's not a bug or limitation in gym, it's just a easiest way to implement environments.

**Comment by hipoglucido** [comment]
Thanks, it was just that I was using a Debian remote server wherein I had no super user acces, but I asked the admin and he installed xvfb for me :)

**Comment by JihaoLee** [comment]
@hipoglucido May you tell me how to write prgrams to save video of gym? Thank you~
