### ISSUE TITLE
Atari rendering, zoom, statistics, etc.

### ISSUE THREAD

**Issue by Hvass-Labs** [openai/gym#461]
Hello Everyone,

I'm trying out the Atari games Space Invaders and Breakout from OpenAI Gym. But the window with the rendered output is tiny because of the low resolution of the game-images. Is there a built-in method for rendering a zoomed image instead? I can't seem to find it.

I would also like to show some more statistics in a plot / chart next to the game-images. Is there a built-in method for doing this?

If I have to program this myself, which easy-to-use Python package / library would you suggest using?

Thanks.

**Comment by tlbtlbtlb** [comment]
Neither is built-in.

Atari rendering uses pyglet. You could write a new version of `SimpleImageViewer` (in `gym/gym/envs/classic_control/rendering.py` that also draws charts, and install that in `env.viewer` before the first call to `env.render()`.
