### ISSUE TITLE
Version number.

### ISSUE THREAD

**Issue by Hvass-Labs** [openai/gym#476]
In order to print the version number of Gym, I currently have to do:

    from gym.version import VERSION
    print(VERSION)

But in Python it is more customary to do the following (https://www.python.org/dev/peps/pep-0396/):

    import gym
    print(gym.__version__)

Would it be possible for you to change this?

Thanks.

**Comment by hholst80** [comment]
Make a PR for it and have it merged. :-)

**Comment by nottombrown** [comment]
Agreed. If you make a PR for this, we'll be happy to merge it iN :)

**Comment by Hvass-Labs** [comment]
I'm sorry but I'm not going to spend a few hours on setting up my Gym installation for making pull-requests, when you can make the change yourself in a few minutes. It would also take you longer to review a PR.

It really is up to you if you want to be in compliance with Python PEP standards.

**Comment by hholst80** [comment]
@Hvass-Labs If that takes you a few hours I assume you never actually tried it yourself. Unfortunately I already did this one, but I would recommend that you try and do it yourself next time and you will see that it does not take a few hours once you know the process.

**Comment by nottombrown** [comment]
Fixed by https://github.com/openai/gym/pull/490

Thanks all!
