### ISSUE TITLE
examples/agents/keyboard_agent.py  fails with "AttributeError: 'TimeLimit' object has no attribute 'viewer'"

### ISSUE THREAD

**Issue by cirosantilli** [openai/gym#483]
```
[2017-02-01 21:58:16,739] Making new env: LunarLander-v2
Traceback (most recent call last):
  File "examples/agents/keyboard_agent.py", line 37, in <module>
    env.viewer.window.on_key_press = key_press
AttributeError: 'TimeLimit' object has no attribute 'viewer'
```

Ubuntu 16.10.

Maybe also make `tabular_q_agent.py` runnable, currently just class def.

d337f4e5719bb8b49f2f9fba1501fe7749fa4d5c

**Comment by olegklimov** [comment]
To fix this, `keyboard_agent.py` needs an option to create environments without any wrappers.

Another option would be to kill `keyboard_agent.py`. Is it useful or not?

Pro:
- Helpful for people to be less afraid of `viewer`, understand it's just a pyglet window. 
- Helpful to have control over execution of the program. I never use manual control, but pause, manual restart, visualization options.

Cons:
- Manual control really works only for Lander.
- It is a hack.

**Comment by nottombrown** [comment]
Fixed in 2d41d69

**Comment by cirosantilli** [comment]
Thanks for the fix, but it is impossible to control without frame limiting :-)

I wish there was a generalized script to use any (discrete action) agent with the keyboard :-)

**Comment by olegklimov** [comment]
@cirosantilli `render('human')` many times.

**Comment by cirosantilli** [comment]
@olegklimov ah it's fine, I don't need to hand control it *that* badly :smile: 

If you ever decide to seriously implement some rate limiting, consider this for inspiration: https://github.com/cirosantilli/general-game-ai/blob/310136f0c1a2108e75f21c51fdf6de8190ff4a1a/main.cpp#L245
