### ISSUE TITLE
Why does my python keep crashing when running experiments on acrobot-v1?

### ISSUE THREAD

**Issue by yxchng** [openai/gym#487]
Why does my python keep crashing when running experiments on acrobot-v1?

I am trying to upload an experiment using wrappers monitor. How does this actually work? what does monitor keeps track of? Is there a limit on how big of a file it can record? Suspecting that this might cause my python to crash.

**Comment by tlbtlbtlb** [comment]
The monitor writes to a file as it goes, so there should be no practical limit on length.

Can you upload a stack trace of the crash?
