### ISSUE TITLE
Lacking changelog entry for TimeLimit wrapper

### ISSUE THREAD

**Issue by rmoehn** [openai/gym#496]
If I see it correctly, many environments are now wrapped in a `TimeLimit` by default. Would you not consider this a breaking change? Shouldn't it be noted in the changelog?

**Comment by tlbtlbtlb** [comment]
It shouldn't break things that follow the API. What is breaking for you?

**Comment by rmoehn** [comment]
Adapting the example from the docs, I used to train my agents like this:

```Python
import gym
env = gym.make('CartPole-v0')
for i_episode in range(20):
    observation = env.reset()
    reward      = 0
    for t in range(max_steps):
        action = agent.step(observation, reward)
        observation, reward, done, info = env.step(action)
        if done:
            agent.done(observation, reward)
            break

        agent.conclude()
```

Nothing was said about `max_steps` (in the example from the docs it's 100), so I usually set it around 400 in order to be able to observe more. My agents would only be `.done()` when they let the pole fall. When they managed to balance it for `max_steps`, `.done()` wouldn't be called, only `.conclude()`.

Now with the `TimitLimit` Wrapper, the agents receive `.done()` after `max_episode_steps` (from `gym.envs.__init__`), which throws off their learning, because the think they did something wrong so that the pole dropped.

You might consider training beyond `max_episode_steps` as not following the API. I consider turning a traditionally non-episodic task like the cart-pole into an episodic task (by signalling a terminal state with `done==True`) as confusing. It has cost me several hours of debugging and some time ago there were people on the chat, too, who were surprised that turning on the monitor messed up the training. This just as a side note.

The `TimeLimit` wrapper breaks things that are natural to do and not discouraged in the docs.

**Comment by joschu** [comment]
Sorry for the confusion it caused. You can just get rid of the wrapper by writing env.env or env.unwrapped to get the underlying (unwrapped) env.

**Comment by joschu** [comment]
You're right that this was a breaking change and should've been in the changelog.

I think the current solution, with TimeLimit being applied by `make`, is better than the previous situation we had, where the environment would behave differently when you monitored it.

**Comment by rmoehn** [comment]
Yeah, making the behaviour consistent is certainly better.

It would be good to do something about the `done==True` on continuing environments, too, though. Cart-pole is *the* beginner environment and it's very easy to train vanilla Sarsa(λ) with Fourier basis linear function approximation on it, for example. If this kind of setup receives `done==True`, because `max_episode_steps` is reached, it won't perform well, which is bound to discourage beginners.

So you could at least put in the docs somewhere that people need to distinguish between episode end because of fallen pole, and episode end because of `max_episode_steps` reached. I'm not expressing myself too clearly, but I hope you understand what I mean.

Oh, and please add the breaking change to the changelog…

**Comment by tlbtlbtlb** [comment]
See FAQ about why changing environment parameters to make environments easier isn't exposed as an official API: https://github.com/openai/gym/wiki/FAQ

**Comment by rmoehn** [comment]
This is not really about changing environment parameters. It's about the timestep limit suddenly being enforced where it wasn't before. Why do you not want to put an entry in the changelog?

**Comment by Hvass-Labs** [comment]
I agree with @rmoehn that this kind of change should be in the changelog. I just upgraded Gym and got a strange error about `TimeLimit` because I was calling `env.ale.lives()` in my code, as instructed by @tlbtlbtlb some time ago. I had to google the error to find out why I got this error about `TimeLimit`. I couldn't really find any docs about it, only a few threads on Github. So I had to debug the code to find out it was a wrapper-object and I just had to access `env` inside it. Now I have to instantiate my env with the following: `env = gym.make("Breakout-v0").env` in case somebody has the same error.

It can be a bit frustrating using Gym because it seems to be in an alpha-stage with constant changes and key features that aren't documented very well / at all / or incorrectly. Some more polishing of the API and docs before releasing it would be very helpful to the community.

**Comment by tlbtlbtlb** [comment]
Using `env.env` unwraps 1 level, which only works with 1 wrapper. If you have a monitor, there'll be 2 wrappers. The right way to peek inside the ALE is with `env.unwrapped.ale.lives()`.

**Comment by Hvass-Labs** [comment]
Thanks for the tip. I'm not aware how all those wrappers work and what they do. I'm not sure they were in the docs when I started using Gym some months ago and I don't seem to need them.

Now I do the following in case it may help others:

    env_name = "Breakout-v0"
    env = gym.make(env_name)

    def get_lives(env):
        return env.unwrapped.ale.lives()
