### ISSUE TITLE
changing timestep limit

### ISSUE THREAD

**Issue by amolchanov86** [openai/gym#499]
To my best knowledge, the only way to limit number of timesteps during an experiment is to change spec of the env which, as I understand, can only be changed during registration of the env. But what if I am creating my own env and I need to change timestep limit (or just need to run existing envs with different limits). If the monitor is not running I guess you can just reset the env whenever you want, but if monitor is running it forbids doing so.

Hence  a couple of questions:
- is there a way of changing timestep limit without registering another env for that (I don't think it is the best solution - to register tons of envs when you want to run the same env with different timestep limits)?
- if not, is introducing my env specific variable (such as my own timestep limit) in order to generate 'done' to prevent Monitor from crashing is the best way to go ? But it looks like a hack to me, rather than a good solution, thus, maybe it would make sense to make timestep limit changeable when needed (could be seen as a feature request :) )? 

Thank you in advance

**Comment by nottombrown** [comment]
Hey @amolchanov86. Changing the `max_episode_steps` of an environment is indeed creating a different environment, that can no longer be compared to the original environment, so registering a new environment would seem like a reasonable way to do this.

If you'd like to change the `max_episode_steps` on an env directly, you can also hack the private variable of the `TimeLimit` wrapped env like so:
```
>>> env = gym.make('Pong-v0')
[2017-02-22 17:14:36,689] Making new env: Pong-v0
>>> env._max_episode_steps = 50
```

**Comment by mkhansen-intel** [comment]
@nottombrown - will this make it return 'done' as True after it has hit the max_episode_steps value (50 in this example)?
