### ISSUE TITLE
wrappers: inherit non standard functionality

### ISSUE THREAD

**Issue by amolchanov86** [openai/gym#500]
Right now, wrappers don't seem to be able to inherit non standard functions, i.e. if I write my own env where I add functions beyond basic set and I would like to wrap it then the only way I can access new functions is by using 'unwrapped' variable. It is ok if you operate inside the wrapper,  but in case I want to access these new functions externally I have to know if I wrapped my env or not, because the way I would call them changes. 
Thus, I am curious if there are plans to make wrappers inherit all functionality of the root environment.

**Comment by tlbtlbtlb** [comment]
In either case you can access the raw env with `env.unwrapped` (which will return `self` if it's not wrapped. So use eg `env.unwrapped.foo()` for any non-standard functions.

**Comment by amolchanov86** [comment]
Oh, really sorry, didn't know that. I just assumed that it was wrappers feature. Thanks a lot !
