### ISSUE TITLE
'TimeLimit' object has no attribute 'ale' Error

### ISSUE THREAD

**Issue by NoobFang** [openai/gym#504]
I have cloned the latest gym and install it by " pip install -e '.[all]' ", and I can make an environment, say 'Breakout-v0'. 

But when I try to get the lives in the environment, say "env.ale.lives()", the error occurs.

Please tell me how to solve this problem, thank you!

**Comment by tlbtlbtlb** [comment]
Most environments are now wrapped in a TimeLimit wrapper. Use `env.unwrapped.ale.lives()`. (This works with all environments, wrapped or not).

**Comment by NoobFang** [comment]
That seems work for me.

Thank you for timely reply!

**Comment by inksci** [comment]
it works:
env.unwrapped.ale.lives()
