### ISSUE TITLE
Repeated actions in Atari envs

### ISSUE THREAD

**Issue by Hvass-Labs** [openai/gym#508]
There is a problem with the documentation for the Atari environments concerning repeated actions.

I noticed by coincidence from the following webpage that Gym's Atari environment randomly repeats an action 2-4 times:

https://gym.openai.com/envs/Breakout-v0

But this is not mentioned in the docs:

https://gym.openai.com/docs

I call the `step()` function implemented in `core.py` whose doc-string says (emphasis added by me):

    Run **one timestep** of the environment's dynamics. When end of
    episode is reached, you are responsible for calling `reset()`
    to reset this environment's state.

So according to the API docs it only performs a single (!) timestep of the environment.

But the `step()` function merely wraps the `_step()` function in `atari_env.py` which is not documented at all. But I can now see from the code that it either repeats an action a fixed number of times, or it selects a random number of repeats between 2-4 times.

I assumed the doc for `step()` was correct and I have therefore manually repeated the actions in my code, so they were actually repeated twice as many times as intended. This has probably wasted several weeks of my research time.

Please ensure that the docs are correct and complete, if you intend for others to rely on your work.

Furthermore, you note that `reset()` must be called after end of episode (aka. game over) because the result is undefined otherwise. But inside `_step()` you don't do this. You need to have something like `if self.ale.game_over(): break` inside the for-loop in `_step()`.

**Comment by tlbtlbtlb** [comment]
We should clarify the docs. When it says "step performs one timestep of the environment", that's a statement about the external API. For physics environments, it can correspond to tens of steps of the physics simulator, and for Atari, it's an an attempt to match previously published research like https://arxiv.org/pdf/1312.5602.pdf.

You can get Atari environments with 1/60 second steps with `BreakoutNoFrameskip-v0` if you prefer those.

> Furthermore, you note that reset() must be called after end of episode (aka. game over) because the result is undefined otherwise. But inside _step() you don't do this. You need to have something like if self.ale.game_over(): break inside the for-loop in _step().

Your agent should call `env.reset()` after it gets `done=True` in the return from `env.step()`
