### ISSUE TITLE
Uploaded gym episodes do not appear in user history

### ISSUE THREAD

**Issue by ghost** [openai/gym#511]
Uploads consisting of less than 100 episodes do not show up in the _selected evaluations_ of the user page. This is very confusing due to the [upload example only training for 20 episodes](https://gym.openai.com/docs). For uploads consisting of fewer than 100 episodes the observation page is created correctly but adds a message: "Only completed 20 episodes, but at least 100 are needed to compute a score."

To resolve this, I would suggest either changing the documentation code to train for 100 or more on CartPole, or allowing for uploads consisting of fewer than 100 training episodes to show up in user page.

**Comment by christopherhesse** [comment]
Thanks for the bug report, but we don't run the scoreboard anymore, so I'm going to close this issue.
