### ISSUE TITLE
observation_space for hybrid observations

### ISSUE THREAD

**Issue by pengsun** [openai/gym#513]
Hi,

When writing my own gym-compatible env, how to specify the observiation_space for hybrid observations? For instance, the observation includes a matrix and a vector. In this case, should it be
```Python
observation_space = [Box(shape=(mat_width, mat_height)), Box(shape=(vec_length,))]
```
or it be wrapped by some `gym.Wrapper`? What's your recommended way?

This issue can be related:
https://github.com/openai/universe/issues/60

**Comment by olegklimov** [comment]
Hello, what you need is Tuple space. Please open this issue again if that is not what you mean.

https://github.com/openai/gym/blob/master/gym/spaces/tuple_space.py

**Comment by pengsun** [comment]
Ah, it is what I mean, thanks for the (really) quick response :)

**Comment by amolchanov86** [comment]
I think it would be quite convenient to make Tuple space iterable and indexable with []. Otherwise one has to actually access .spaces variable instead. Thanks.
