### ISSUE TITLE
keyboard_agent needs a reset of the env

### ISSUE THREAD

**Issue by sabbasizadeh** [openai/gym#515]
It seems that the keyboard_agent in the examples of the agents (/gym/examples/agents/keyboard_agent.py) needs to reset the environment after its making:

```
env = gym.make('LunarLander-v2' if len(sys.argv)<2 else sys.argv[1])
env.reset()
```

**Comment by tlbtlbtlb** [comment]
It is reset right here: https://github.com/openai/gym/blob/master/examples/agents/keyboard_agent.py#L43

Is there some environment on which it fails?

**Comment by olegklimov** [comment]
`reset` is definitely there.

**Comment by sabbasizadeh** [comment]
Yes there is, but for some of the environments such as `cartpole` which need an initial configuration, this `reset` does not work.

**Comment by tlbtlbtlb** [comment]
Fixed (environments should crash when render is called before reset) in https://github.com/openai/gym/commit/874b6fe2afe5b241c18a973979e4094948116db1
