### ISSUE TITLE
How to capture the image of the demo window?

### ISSUE THREAD

**Issue by Ja1r0** [openai/gym#516]
I would like to know if there is a function in gym that can
capture the image of the demo window?Or what should I do.
I want to use the image of every moment to be the input of DNN.

**Comment by olegklimov** [comment]
Hello, this is not a bug, and there is nothing to fix. You're asking for advice.

Many environments support `render("rgb_array")`, it will return you an image. This images are normally used for demo video.

For DNN input, observations normally are used. Please see tutorial https://gym.openai.com/docs for overview what observations you can encounter.
