### ISSUE TITLE
Mujoco Opengl rendering issue on the remote machine

### ISSUE THREAD

**Issue by yjy765** [openai/gym#517]
Hello I have an issue on Mujoco rendering.

I use the remote server machine(ubuntu 14.04) by connecting through VNC viewer.

Therefore, I use VirtualGL to address the problem that VNC viewer only supports the low version of OpenGL.

By this method, I have no problem to run gym application like atari games or cartpole etc.

However, when I run Mujoco binding application like 'InvertedPendumlum-v1', then I get following error.

    vglrun python    
    >>import gym
    >>env = gym.make('InvertedPendulum-v1')
    >>env.reset()

By far, it is ok. But,

    >>env.render()

gives

    X Error or failed request: BadBatch (invalid parameter attributes)
       Major opcode of failed requests: 72 (X_PutImage)
       Serial number of failed request:    43
       Current serial number in output stream:  48

In my opinion, it is due to the fact that Mujoco has its own OpenGL rendering but I don't know how to address this problem.

**Comment by tlbtlbtlb** [comment]
I recommend Xdummy instead of vgl. See gym/bin/docker_entrypoint for an example of how to set up Xdummy.

**Comment by christopherhesse** [comment]
This should be solved by using `Xvfb` as now mentioned in the README: https://github.com/openai/gym#rendering-on-a-server
