### ISSUE TITLE
import error when making box2d environments

### ISSUE THREAD

**Issue by falcondai** [openai/gym#518]
the `gym.envs.classic_control.rendering` import in `car_racing.py` is preventing other box2d environments to run on a headless machine. I believe this can be fixed by simply moving the import call into the `render` function (just like in other environments). I shall submit a PR.

> [2017-02-27 16:37:17,408] Making new env: LunarLanderContinuous-v2
> Traceback (most recent call last):
>   File "async_node.py", line 100, in <module>
>     env = get_env(args.env_id)
>   File "/home/dai/dev/policy-gradient/envs/registry.py", line 19, in get_env
>     return GymEnv(parts[1])
>   File "/home/dai/dev/policy-gradient/envs/core.py", line 30, in __init__
>     self.gym_env = gym.make(env_id)
>   File "/usr/local/lib/python2.7/dist-packages/gym/envs/registration.py", line 130, in make
>     return registry.make(id)
>   File "/usr/local/lib/python2.7/dist-packages/gym/envs/registration.py", line 95, in make
>     return spec.make()
>   File "/usr/local/lib/python2.7/dist-packages/gym/envs/registration.py", line 70, in make
>     cls = load(self._entry_point)
>   File "/usr/local/lib/python2.7/dist-packages/gym/envs/registration.py", line 18, in load
>     result = entry_point.load(False)
>   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2268, in load
>     return self.resolve()
>   File "/usr/local/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2274, in resolve
>     module = __import__(self.module_name, fromlist=['__name__'], level=0)
>   File "/usr/local/lib/python2.7/dist-packages/gym/envs/box2d/__init__.py", line 4, in <module>
>     from gym.envs.box2d.car_racing import CarRacing
>   File "/usr/local/lib/python2.7/dist-packages/gym/envs/box2d/car_racing.py", line 10, in <module>
>     from gym.envs.classic_control import rendering
>   File "/usr/local/lib/python2.7/dist-packages/gym/envs/classic_control/rendering.py", line 23, in <module>
>     from pyglet.gl import *
>   File "/usr/local/lib/python2.7/dist-packages/pyglet/gl/__init__.py", line 236, in <module>
>     import pyglet.window
>   File "/usr/local/lib/python2.7/dist-packages/pyglet/window/__init__.py", line 1817, in <module>
>     gl._create_shadow_window()
>   File "/usr/local/lib/python2.7/dist-packages/pyglet/gl/__init__.py", line 205, in _create_shadow_window
>     _shadow_window = Window(width=1, height=1, visible=False)
>   File "/usr/local/lib/python2.7/dist-packages/pyglet/window/xlib/__init__.py", line 163, in __init__
>     super(XlibWindow, self).__init__(*args, **kwargs)
>   File "/usr/local/lib/python2.7/dist-packages/pyglet/window/__init__.py", line 494, in __init__
>     display = get_platform().get_default_display()
>   File "/usr/local/lib/python2.7/dist-packages/pyglet/window/__init__.py", line 1766, in get_default_display
>     return pyglet.canvas.get_display()
>   File "/usr/local/lib/python2.7/dist-packages/pyglet/canvas/__init__.py", line 82, in get_display
>     return Display()
>   File "/usr/local/lib/python2.7/dist-packages/pyglet/canvas/xlib.py", line 83, in __init__
>     raise NoSuchDisplayException('Cannot connect to "%s"' % name)
> pyglet.canvas.xlib.NoSuchDisplayException: Cannot connect to "None"

**Comment by tlbtlbtlb** [comment]
That could be the right approach. An alternative is to wrap the `from pyglet.gl import *` in `gym/envs/classic_control/rendering.py` inside a `try: except:` that sets a `rendering_unavailable` flag. Up to you.

**Comment by falcondai** [comment]
i just realized the other cause of the issue (as you alluded to). the reason `from pyglet.gl import *` is called outside of `_render` is that the car_racing environment relies on GL to provide rendered pixel states.
