### ISSUE TITLE
LunarLander-v2 observation_space.sample mtrand error

### ISSUE THREAD

**Issue by Scitator** [openai/gym#520]
Code:
```
env = gym.make("LunarLanderContinuous-v2")
sample_obs = env.observation_space.sample()
```

Traceback:
```
...
File ".../git/gym/gym/spaces/box.py", line 29, in sample
    return prng.np_random.uniform(low=self.low, high=self.high, size=self.low.shape)
File "mtrand.pyx", line 1300, in mtrand.RandomState.uniform (numpy/random/mtrand/mtrand.c:19526)
    OverflowError: Range exceeds valid bounds
```

**Gym version: 0.7.4-dev**
Box2D version (cause I change upgrade it): 2.3.1

Error in:
https://github.com/openai/gym/blob/master/gym/spaces/box.py

Addiition:

For LunarLanderContinuous-v2:
```
env.observation_space
    Box(8,)
env.observation_space.low
     array([-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf])
env.observation_space.high
    array([-inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf])
```

Same code for MountainCarContinuous-v0:
```
env.observation_space
    Box(2,)
env.observation_space.low
    array([-1.2 , -0.07])
env.observation_space.high
    array([ 0.6 ,  0.07])
```

**Comment by Scitator** [comment]
By the src code of LunarLander, it looks like "normal" behavior:
https://github.com/openai/gym/blob/master/gym/envs/box2d/lunar_lander.py

So typical LunarLander-v2 gives the same error. Why so?

**Comment by olegklimov** [comment]
Hello, so are you surprised that random(-inf, +inf) gives you an error?

It is true that observation you can get is unlimited. It is generally scaled to be in -1 to +1 range, but physics simulator can give spikes and you cannot say beforehand what is the limit.

And did you confuse it with `env.action_space.sample()`? Do you really need to sample from observation space?

**Comment by Scitator** [comment]
I am surprised that function does not works properly (gym gives same API for bunch of environments and it confusing when something goes wrong in one of them). There is no assert or exception with description why it is not allowed in this environment. If you add something like this, it would be much simpler to understand.

And for some reason it is needed for sklearn.MLPRegressor initialization (awkward implementation, really). But yeah, it can be done just with shapes.

**Comment by olegklimov** [comment]
Let's close this. There is no obvious reason to sample from observation space. It is usually high-dimensional (think RGB image), you need generative model to get reasonable random samples. Nothing we can fix here without overreaching.

**Comment by Scitator** [comment]
I don't think this is solution... but nevertheless it is your code.

**Comment by wil3** [comment]
I'm also running into situations where this is confusing. Using PPO from OpenAI baselines, the action space is sampled, https://github.com/openai/baselines/blob/master/baselines/ppo1/pposgd_simple.py#L13 If you have an environment in which the action space is inf ```OverflowError: Range exceeds valid bounds``` is thrown. If there's no reason to sample from observation or action space then this is a bug in PPO baselines and there should be a better way to get the data type. If infs are not in a space then an exception or assert should be made in the constructor.

**Comment by olegklimov** [comment]
Yes, it's a bit ugly... @pzhokhov maybe we can sample from -Inf .. +Inf with gaussian distribution?

**Comment by pzhokhov** [comment]
yes, we can do that. @wil3 As for usage in the ppo1 - I'll look into removing sampling from observation space, please keep in mind that we are gradually stopping support of ppo1 in favor or ppo2; so I won't spend too much time on it if it becomes too involved.
