### ISSUE TITLE
CarRacing environment states break if I the monitor isn't started

### ISSUE THREAD

**Issue by Instassa** [openai/gym#521]
I am trying to run learning without displaying the environment (in a hope this speeds up the code), so I've not enabled the monitor: `env.monitor.start('results/carrace-newQ-4')`
But now the states are displayed like that for me:
<img width="274" alt="screen shot 2017-03-02 at 14 25 23" src="https://cloud.githubusercontent.com/assets/12833628/23511176/34858e3a-ff54-11e6-9718-2c1949911a01.png">

Is there a way of running without displaying the environment and keeping states normal?

Code to reach this issue: 
`env = gym.make('CarRacing-v0');
env.render();`
`state = env.reset();`
`plt.figure();
plt.imshow(np.flipud(state), cmap='Greys');
plt.show()`

**Comment by tlbtlbtlb** [comment]
Can you try with version 93d554bdbb4b2d29ff1a685158dbde93b36e3801 and see if that fixes it?

**Comment by Instassa** [comment]
I tried, now it looks like this: 
<img width="248" alt="screen shot 2017-03-07 at 14 47 47" src="https://cloud.githubusercontent.com/assets/12833628/23661582/24fc85d2-0345-11e7-8ec1-0312558f894b.png">

**Comment by tlbtlbtlb** [comment]
@olegklimov Can you look at this? I see the same as above (on my Mac with Anaconda 3.5), unless something (like the monitor) also calls `env.render(mode='rgb_pixels')`.

**Comment by alexandervandekleut** [comment]
I am also getting this problem

**Comment by Qinusty** [comment]
This is fixed as of https://github.com/openai/gym/pull/1343
