### ISSUE TITLE
Getting perfect score in Car-Racing env, likely a bug

### ISSUE THREAD

**Issue by rahulsengupta** [openai/gym#522]
I used Keras-RL DDPG agent and trained it overnight.
At the start, with randomly un-initialized weights, I can see screen and the car, barely move as it is expected. Then I trained it overnight. 
But then with the saved weights, the episodes get done almost instantly and I get a near-perfect score. I'm not sure what's going on. How can saved keras model weights affect Gym?

https://gym.openai.com/evaluations/eval_55ksvxr8RXmS2rMlNah8Q

@olegklimov

**Comment by rahulsengupta** [comment]
I restarted my PC. When I start my code WITHOUT the saved overnight weights, the car and the env work as expected. I can see the car being rendered and moving around randomly.
However when I re-run the exact same code with the saved weights loaded into the model, the agent is able to finish the episode almost instantly with 999 score.
I've repeated this several times and this behaviour is seen consistently.

What logs/info would you like me to send?
Thanks

**Comment by olegklimov** [comment]
Nice! Your agent seems to be pretty smart! I think it finishes in one frame, please post here action it takes in that first frame. (maybe two frames)

(no, I have now idea how the car can visit all track tiles in one frame, maybe NaN again?)

**Comment by rahulsengupta** [comment]
Yep I checked , as suspected it was NaN indeed! Interesting how it managed to figure that out. I'm using np.random_normal to sample, so really no idea how it managed arrive at NaN
[ nan  nan  nan] is the action input

**Comment by rahulsengupta** [comment]
I guess I should remove my entry from the leaderboard. How do I delete my entry? Or will the admins do that? Thanks
