### ISSUE TITLE
running toy text example - frozenlake

### ISSUE THREAD

**Issue by BLCKPSTV** [openai/gym#523]
I get following error after installing via clone (minimal).

env.render()

SFFF
FHFH
FFFH
HFFG
<open file '<stdout>', mode 'w' at 0x105dc6150>

**Comment by tlbtlbtlb** [comment]
I don't understand what you did to get that. Can you post a complete transcript from the terminal?

**Comment by tlbtlbtlb** [comment]
There's no error there, but it is surprising that render returns the file it wrote to (stdout). I changed it to not do that.
