### ISSUE TITLE
Box Environment with Non-Box Parameters

### ISSUE THREAD

**Issue by dqii** [openai/gym#524]
I want to train an rllab algorithm for CarRacing-v0 with non-box parameters, specifically, velocity, angle, and distance from center. I already have these parameters, but I am having trouble setting the observation space, since it is no longer a Box space. Do you have any suggestions? Thanks!

**Comment by tlbtlbtlb** [comment]
Observation spaces don't have to be a tight box around the parameters values. In fact, most physics-based environments use [-Inf, +Inf] as the range.

**Comment by olegklimov** [comment]
I'm not sure I understand what you're saying. What is non-box parameters? Distance from center is hard to obtain, it's unconstrained 2d world, you can drive on grass and have several distances to different roads to choose from.

**Comment by olegklimov** [comment]
And if it is no longer Box space, you may need Tuple space. Again I'm not sure I understand.

**Comment by dqii** [comment]
For the CarRacing environment, I have obtained velocity, angle from the road, and distance from the center of the road. I can see how the latter two might not be completely accurate now, as the car could serve and go onto another road, if that's what you mean. 

Regardless, my question is what should I change the observation space to in this case? 

This is the observation space for car racing. It is STATE_H by STATE_W pixels of different colors as I understand. I thought these were discrete values.
self.observation_space = spaces.Box(low=0, high=255, shape=(STATE_H, STATE_W, 3))

If I wanted instead 3 variables, each with a different range, I was not sure what the corresponding observation space ought to be. Suppose my variables were continuous and ranged from [-Inf, +Inf], [-Pi, Pi], and [-Inf, +Inf] respectively. Would it be something like

self.observation = [np.array(-Inf, -Pi, -Inf), np.array(Inf, Pi, Inf)]

Thanks for responding!

**Comment by olegklimov** [comment]
OK, you want to modify CarRacing to include high-level parameters, and keep RGB. You need Tuple space, see:

https://github.com/openai/gym/blob/master/gym/spaces/tuple_space.py

**Comment by dqii** [comment]
Ah, and with 1d boxes inside the tuple! Thanks!
