### ISSUE TITLE
New toy text environment: Kelly Coinflip Game

### ISSUE THREAD

**Issue by gwern** [openai/gym#528]
I'd like to add a new environment to the Gym toy text section: it is a simple gambling MDP which can be solved by backwards induction on decision trees to find the optimal policy, as well as simple heuristics like the Kelly criterion.

[0001-toy-text-game-The-Kelly-Coinflip-Game-https-www.gwer.patch.txt](https://github.com/openai/gym/files/836101/0001-toy-text-game-The-Kelly-Coinflip-Game-https-www.gwer.patch.txt)

For more detailed analysis, see my writeup: https://www.gwern.net/Coin-flip

If this environment is acceptable, I'd like to extend the environment to the harder Bayesian POMDP versions where the coin flip percentage, maximum wealth, and number of rounds, are random variables, for which I do not yet have efficiently computable policies but which a deep RL agent could probably solve easily. (I am hoping someone with an A3C implementation or something will come along and prove my intuition right: that the Bayesian version achieves performance close to the fully-observed version and that the VoI is low.)

**Comment by tlbtlbtlb** [comment]
Hi Gwern! (HN mod/fan tlb here). That looks good! Would you like to do a pull request so you'll be properly credited?

I'd propose one change: for deep RL with neural networks, it works better when the scale of the action and observation space within an order of magnitude of 1. For this, I'd suggest using log(amount in dollars) as the action & observation. Then well-known algorithms should work without requiring any feature engineering.

**Comment by gwern** [comment]
Hm. Log scaling might help deep RL algorithms (although I would hope that the SOTA could cope better with reward scaling these days and not require reward shaping), but it does change the problem substantially. Maximizing log wealth is not the same as maximizing wealth, is it? For example, winning \$125 is 50% as good as winning the cap of \$250, but winning log(125) is 87% as good as winning log(250). This would, at the least, screw up any decision tree approach and make them systematically conservative, I think. (Log-scaling the actions/bet amounts wouldn't matter since they're discretized anyway, with no sub-penny bets.)

I suppose there could be an initialization option for whether to log-scale the rewards. Then the default 'register' one could be log-scaled (if we want to assume people will mostly be trying deep RL algorithms on it) or two versions could be provided in `envs/__init__.py`, one log-scaled and one not. (I assume that the `kwargs` argument is for passing arguments to the `__init__`?)

**Comment by tlbtlbtlb** [comment]
Fair enough, let's leave it without log-scaling. It makes a good test for numerical robustness.

**Comment by gwern** [comment]
Cool. I have opened a pull request: #532
