### ISSUE TITLE
How to move an agent in desired directions 

### ISSUE THREAD

**Issue by josephchow1991** [openai/gym#530]
Take MsPacman-v0 for example. I know we can use env.action_space.sample() to move agent in random direction. But is there a way that I can move the agent in the directions as I desired?

**Comment by olegklimov** [comment]
Use `keyboard_agent.py`, move everywhere you want.

**Comment by nczempin** [comment]
action_space tells you what actions are available; you can pick any one of them. So if the environment offers you an action "move_right" and you want to move right, you find that action in that list and pass it to env.act(a) (with a being the chosen action here)

**Comment by olegklimov** [comment]
Let's close this!
