### ISSUE TITLE
Attribute Error: module 'gym' has no attribute 'make'

### ISSUE THREAD

**Issue by Brehski** [openai/gym#535]
`import gym
import universe # register the universe environments

env = gym.make('flashgames.DuskDrive-v0')

env.configure(remotes=1) # automatically creates a local docker container

observation_n = env.reset()

while True:
	action_n = [[('KeyEvent', 'ArrowUp', True)] for ob in observation_n] # your agent here
	observation_n, reward_n, done_n, info = env.step(action_n)
	env.render()`
My current directory consists of a demo.py file readme, cloned gym, and cloned universe. I am just trying to run the sample code but I am getting this error.

  File "demo.py", line 3, in <module>
    env = gym.make('flashgames.DuskDrive-v0')
AttributeError: module 'gym' has no attribute 'make'

Not sure what to do to fix this. I was just trying to verify that I set up the dependencies correctly.

**Comment by Brehski** [comment]
I used sudo pip install -e .

**Comment by tlbtlbtlb** [comment]
You must have another file called `gym.py` or directory called `gym` which Python is finding instead of the installed gym. You can find out what Python is loading with
```
$ python
>>> import gym
>>> gym.__file__
```

**Comment by Brehski** [comment]
Right now, I'm trying to just get universe to work. But when importing universe, I get this error.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/brehski/Downloads/universe/universe/__init__.py", line 22, in <module>
    from universe import error, envs
  File "/Users/brehski/Downloads/universe/universe/envs/__init__.py", line 1, in <module>
    import universe.envs.vnc_env
  File "/Users/brehski/Downloads/universe/universe/envs/vnc_env.py", line 11, in <module>
    from universe.envs import diagnostics
  File "/Users/brehski/Downloads/universe/universe/envs/diagnostics.py", line 2, in <module>
    import fastzbarlight
  File "/Users/brehski/anaconda3/lib/python3.6/site-packages/fastzbarlight/__init__.py", line 7, in <module>
    from ._zbarlight import zbar_code_scanner
ImportError: dlopen(/Users/brehski/anaconda3/lib/python3.6/site-packages/fastzbarlight/_zbarlight.cpython-36m-darwin.so, 2): Symbol not found: _iconv
  Referenced from: /Users/brehski/anaconda3/lib/python3.6/site-packages/fastzbarlight/_zbarlight.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/brehski/anaconda3/lib/python3.6/site-packages/fastzbarlight/_zbarlight.cpython-36m-darwin.so

**Comment by Brehski** [comment]
I was able to get gym to import correctly now though.

**Comment by hholst80** [comment]
I think the problem was that you used sudo install -e
You should not use sudo with install -e

**Comment by zhaolongkzz** [comment]
I think that a py file named gym.py may be created in your workspace, this will conflict with gym package.

**Comment by muzilify** [comment]
I meet the same problem,can you tell me how do you solve this problem?
