### ISSUE TITLE
How to save atari screen images? 

### ISSUE THREAD

**Issue by jackielxu** [openai/gym#541]
I am trying to save the atari screen images by doing
```
import gym
env = gym.make('Breakout-v0')
env.reset()
env.env.ale.saveScreenPNG('test_image.png')
```
I also tried changing the last line to
`env.env.ale.saveScreenPNG('test_image')`

but the function doesn't seem to take a string input. The input for the function says it should be a filename, which I would have expected should be a string, but it seems that I'm mistaken. How can I save image data from atari game screens with gym?

Thank you for the help!

**Comment by tarvos21** [comment]
Hi, @jackielxu, I have tried to save an image by the code you provided here, exactly the same(using  `'test_image.png'`), I have got a `test_image.png` file in the woking directory like this:

![test_image](https://cloud.githubusercontent.com/assets/18745870/24319218/6ceceaa8-1150-11e7-91ec-933c6a106624.png)

It works as expected, I use python 2.7.

**Comment by tlbtlbtlb** [comment]
If you're using python3, it needs to be a `bytes` rather than a `str`. So use:
```
env.env.ale.saveScreenPNG(b'test_image.png')
```

If you want it to be portable, 
```
import six
...
env.env.ale.saveScreenPNG(six.b('test_image.png'))
```

**Comment by jackielxu** [comment]
Indeed I was using python 3, and needed the input to be a `bytes` rather than a `str`. 

Thank you so much!

**Comment by tshr729** [comment]
`env.env.ale.saveScreenPNG(b'test_image.png')`

Images saved using this have are having width= 320 px and height =250 px which is not same as the game is displayed over console. The game screen is having width < height. Why is so? Is there a work around?

**Comment by tlbtlbtlb** [comment]
Internal screen images are 160x210, the SaveScreenPNG function (part of the Stella dependency, not Gym) doubles the width to save it as 320x210. I believe this is closer to the way it looked on the original hardware. If you want 160x210, you can resize it using any image editing tool.
