### ISSUE TITLE
getScreenRGB returns blank screen?

### ISSUE THREAD

**Issue by jackielxu** [openai/gym#542]
I'm trying to obtain the atari screen image as an RBG numpy array, which I believe `getScreenRGB` is supposed to do. 

At the moment, after I initiate a game environment, I try to run: 
```
env.reset()
x = env.env.ale.getScreenRGB()  # a (210, 160, 4) matrix
```
But `x` renders into a blank white screen when I try plotting `x` with `matplotlib`.  

Even initializing `screen_data`(following the  [documentation](https://github.com/openai/atari-py/blob/master/atari_py/ale_python_interface.py)) and trying
```
screen_data = np.zeros((210, 160, 4))  # screen dims are (210, 160, 4)
env.reset()
x = env.env.ale.getScreenRGB(screen_data=screen_data)
```
doesn't seem to do the trick. 

I would like `x` to contain the RGB values of the screen. What is the correct way to do so? I'm using python 3 -- if that is important. 

Thank you for any help!

**Comment by eddiepierce** [comment]
try using the first 3 dimensions x[:, :, :3]

**Comment by jackielxu** [comment]
Awesome - the images are showing up. The only strange thing is that the colors seem to not be like the original atari games? Not sure if others are experiencing the same issue, but the image dimensions and objects are perfect..

**Comment by eddiepierce** [comment]
Even though it says RGB in getScreenRGB(), I'm pretty sure it's BGR. Try transposing the image like
 x = x[:, :, [2, 1, 0]]

**Comment by jackielxu** [comment]
Hm, I'm still getting a weird coloring scheme that doesn't match the original. I tried a few other possible rearrangements of the RGB values...no luck yet.
