### ISSUE TITLE
module 'gym' has no attribute 'make'

### ISSUE THREAD

**Issue by mahavir1196** [openai/gym#544]
Traceback (most recent call last):
  File "./test.py", line 249, in <module>
    env = gym.make('BipedalWalkerHardcore-v2')
AttributeError: module 'gym' has no attribute 'make'
How should I solve this error?

**Comment by tlbtlbtlb** [comment]
You probably have a file in your local directory called 'gym.py', which conflicts with the installed gym. In Python, avoid naming files with names that might conflict with packages.
