### ISSUE TITLE
use gym tags

### ISSUE THREAD

**Issue by weiliu620** [openai/gym#545]
This is a rather vague question. I didn't find document about using tags. I created a new env, similar to the classic_control/cartpole. But when run it together with rllab, I got error and found the `max_path_lengh` is not set for this env. And that seem related to a tag `'wrapper_config.TimeLimit.max_episode_steps'`

I found this code in gym: 
```
# BACKWARDS COMPAT 2017/1/18
        if tags.get('wrapper_config.TimeLimit.max_episode_steps'):
            max_episode_steps = tags.get('wrapper_config.TimeLimit.max_episode_steps')
```
and wonder if they are related. So my question is: how to use the tags to add this `max_path_lengh`. I'm confused that my env is very similar to the original one, but why this field is missing...

**Comment by tlbtlbtlb** [comment]
There was never a tag `max_path_length` in gym. That attribute is used in rllab, but as a property of a training algorithm like TRPO, not an environment. If that doesn't help, ask in the rllab repo.
