### ISSUE TITLE
Restore env and state after pickling?

### ISSUE THREAD

**Issue by jackielxu** [openai/gym#546]
I'm trying to pickle states from a game env in one file and try to unpickle and restore the states in a new file.  It seems that you need the original env that produced those states to restore the states. 

When I try to restore the game states, I get: 
`ValueError: Can only restore state on the ale instance it yielded from`

I've tried to:

- pickle the env (of type `gym.wrappers.time_limit.TimeLimit`), and then restore the state by running `env.env.ale.restoreState(state)` --> this leads to the same ValueError
- pickle the env (of type `gym.envs.atari.atari_env.AtariEnv`), and restore the state by `env.ale.restoreState(state)` --> this leads to the same ValueError
- pickle the ale (of type `atari_py.ale_python_interface.ALEInterface`), and then restore the state by `ale.restoreState(state)` --> this leads to a `Segmentation fault` 

Is there a proper way to restore game states that are saved in a different file? 

Update: I've also tried to pickle on deepcopies of the envs and ale, but get the same errors.

**Comment by tlbtlbtlb** [comment]
I'm afraid it would take some hacking on Atari-py. ALE defines an `ALEState` type which has a binary representation of internal states. Inside it keeps a pointer to a memory buffer -- pickling the `ALEState` just saves the pointer which is useless in any other process.

**Comment by samiede** [comment]
Hey, I'm trying to do the same thing, have you found a solution?
