### ISSUE TITLE
unexpected result while pickling atari env

### ISSUE THREAD

**Issue by hholst80** [openai/gym#548]
The pickling of atari does not restore overridden constructor properties.

```
import pickle
import gym
env = gym.make('Pong-v0')
env.frameskip # default frameskip is (2, 5)
env.frameskip = 4
env.frameskip # frameskip is now 4
b = pickle.dumps(env)
env2 = pickle.loads(b)
assert env2.frameskip == 4, "frameskip not restored properly"
```

The assert should not trigger on the last line.

**Comment by tlbtlbtlb** [comment]
Atari envs aren't pickleable at all, because they are mainly a reference to a big data structure defined in C. At best, it'll pickle a pointer to memory which would just segfault in another process.
