### ISSUE TITLE
Do we have dictionary spaces?

### ISSUE THREAD

**Issue by botonchou** [openai/gym#555]
Hi all,

I know we have `tuple_space.py`, but I'm wondering whether we have something like `dict_space.py`.

> observation (object): an environment-specific object representing your observation of the environment. For example, pixel data from a camera, joint angles and joint velocities of a robot, or the board state in a board game.

From the [documentation](https://gym.openai.com/docs), I know if I call `env.step`, the `observation` returned is a Python object. This means if I want to create an environment (like MuJoCo) that returns both the robot states (ex: joint velocity) and pixel in RGB array, I can just return the `observation` in a Python dict.

But for the `observation_space`, I can only use `class Tuple`.

I think it'd be great if we have dictionary spaces so that the user can associate the `observation` with `observation_space` using the keys.

**Comment by longjie** [comment]
Hi, I'm new to gym, and considering to write handy bridge code between gym and ROS.
I just think same way as you, and I've created a PR for Dict space feature in #563 .
Please review if you please.

**Comment by tlbtlbtlb** [comment]
@longjie Consider borrowing ideas from https://github.com/openai/rosbridge

**Comment by tlbtlbtlb** [comment]
@botonchou Just use a Tuple space. You can name the fields by defining constants in the class, and access them like:
```
  obs[MyEnv.KNEE_ANGLE]
```
