### ISSUE TITLE
'ALEInterface' object has no attribute 'getScreenRGB2'

### ISSUE THREAD

**Issue by mathDR** [openai/gym#556]
Hello, just installed gym with atari support and ran the most basic example I could think of:
```python
import gym
env = gym.make("Pong-v0")
observation = env.reset()
for _ in range(1000):
  env.render()
  action = env.action_space.sample() # your agent here (this takes random actions)
  observation, reward, done, info = env.step(action)
```
and this threw the Error:
```python
AttributeError: 'ALEInterface' object has no attribute 'getScreenRGB2'
```

I physically changed line 86 in gym/gym/envs/atari/atari_env.py from
```python
return self.ale.getScreenRGB2()
```
to 
```python 
return self.ale.getScreenRGB()
```
but that throws a segmentation fault.

I am running osx 10.11.6 

Any ideas?

**Comment by tlbtlbtlb** [comment]
You have an older version of atari-py. `pip install --upgrade atari-py`.

**Comment by mathDR** [comment]
Updated atari-py-0.0.18 to atari-py-0.0.21 and the issue is resolved.  I wonder why the setup.py didn't flag the mismatch?

**Comment by mathDR** [comment]
Just to be complete:  I git cloned the repo and used 
```python
pip install -e .
```
to install.

**Comment by tlbtlbtlb** [comment]
Atari is an optional dependency of gym -- it's only installed with `pip install -e .[atari]`.

**Comment by cws7777** [comment]
How about on windows 10? I'm using Windows 10 with anaconda. I tried most of things to upgrade atari-py but didn't work. any suggestions?

**Comment by tlbtlbtlb** [comment]
@cws777 You have an obsolete version of atari-py. 
```
$ pip install --upgrade atari-py.
```
to fix.
