### ISSUE TITLE
inline support for ipython notebooks

### ISSUE THREAD

**Issue by ryantuck** [openai/gym#56]
it would be awesome to see `inline` support for ipython notebooks, similar to how `%matplotlib inline` prevents the secondary python application windows from opening. it seems like an ideal use case for quickly iterating and sharing `openai` environments (although it is very easy to set up). 

i've been unable to find any demos online of people using `%pyglet inline`, which is discouraging. would this need to be built out at the `pyglet` level?

**Comment by jonasschneider** [comment]
That sounds very exciting. I don't think we necessarily need pyglet support; the `rgb_array` rendering mode might be interesting here -- it just returns the raw image, which we usually use for video encoding. As a first idea, you might want to try using `env.render(mode='rgb_array')`, and then render the resulting `np.ndarray` using e.g. matplotlib inside of IPython.

We're definitely open to merging something that makes this even easier, though!

**Comment by joschu** [comment]
Should work to do plt.imshow(env.render(mode='rgb_array')) inside of your notebook cell

**Comment by gdb** [comment]
(Going to close for now; let us know if we can help with anything!)

**Comment by patrickmineault** [comment]
Here's one approach:

http://nbviewer.jupyter.org/github/patrickmineault/xcorr-notebooks/blob/master/Render%20OpenAI%20gym%20as%20GIF.ipynb

**Comment by mpacer** [comment]
Note `import matplotlib.pyplot plt.imshow(env.render(mode='rgb_array'))` does not work in either notebook 5.0.0 or 5.1.0.  I honestly don't think it would have worked in earlier editions, but some stuff with mimetypes have changed so I don't know if that's affecting it.

But should this have ever worked?: 

 ```python
from matplotlib import pyplot as plt
# plt.ion()
%matplotlib inline
import gym
env = gym.make('CartPole-v0')
env.reset()
for _ in range(1000):
    plt.imshow(env.render(mode='rgb_array'))    
    env.step(env.action_space.sample()) # take a random action
```

**Comment by mpacer** [comment]
I can vouch for the solution by @patrickmineault as working, but I'm thinking this should be possible by using the IPython display mech for handling general mimetypes so long as the right spot can be hooked into directly.

**Comment by andrewschreiber** [comment]
Created a Gist based on tweaking some of the above responses:
https://gist.github.com/andrewschreiber/e9a21bba9c604a790e605fbacd3f4109

#### Open jupyter with
    $ xvfb-run -s "-screen 0 1400x900x24" jupyter notebook

#### In Jupyter
    import matplotlib.pyplot as plt
    %matplotlib inline

#### After each step
```python2
def show_state(env, step=0):
    plt.figure(3)
    plt.clf()
    plt.imshow(env.render(mode='rgb_array'))
    plt.title("%s. Step: %d" % (env._spec.id,step))
    
    plt.pause(0.001)  # pause for plots to update

    if is_ipython:
        display.clear_output(wait=True)
        display.display(plt.gcf())
```

**Comment by dsblank** [comment]
I avoided the matplotlib issues by simply doing:

```python
import PIL
PIL.Image.fromarray(env.render(mode='rgb_array')).resize((320, 420))
```
There may still be an issue on servers without DISPLAYS, but that seems like a separate issue.
