### ISSUE TITLE
Can we set the quality of the videos recorded by the monitor wrapper ?

### ISSUE THREAD

**Issue by joemathai** [openai/gym#564]
hi,
Is there a way to improve the quality of the video created by the monitor wrapper ?

**Comment by tlbtlbtlb** [comment]
Do you want to make them bigger, or reduce noise?

Either way, you can modify the arguments to the video compressor (avconv) in gym/gym/monitoring/video_wrapper.py around line 222. There are arguments (see `man avconv`) to scale it up or compress at higher bit rates.

**Comment by joemathai** [comment]
Thanks.
