### ISSUE TITLE
Setting is_slippery=False in FrozenLake-v0

### ISSUE THREAD

**Issue by pdoongarwal** [openai/gym#565]
I want to make FrozenLake-v0 work as deterministic problem, so want to set variable is_slippery=False.
How can I set it to False while initialing the environment?
[Reference to code](https://github.com/openai/gym/blob/master/gym/envs/toy_text/frozen_lake.py#L60)

**Comment by tlbtlbtlb** [comment]
You should register an environment with a different name and the kwargs you want, something like:

```python
from gym.envs.registration import register
register(
    id='FrozenLakeNotSlippery-v0',
    entry_point='gym.envs.toy_text:FrozenLakeEnv',
    kwargs={'map_name' : '4x4', 'is_slippery': False},
    max_episode_steps=100,
    reward_threshold=0.78, # optimum = .8196
)
```

**Comment by pdoongarwal** [comment]
Thanks, that works!

**Comment by Daksh** [comment]
You can simply do,
`env = gym.make('FrozenLake-v0', is_slippery=False)`

[Source](https://stackoverflow.com/a/56546717/2806163)

**Comment by svdeepak99** [comment]
> You can simply do,
> `env = gym.make('FrozenLake-v0', is_slippery=False)`
> 
> [Source](https://stackoverflow.com/a/56546717/2806163)

Thank you
