### ISSUE TITLE
gym.error.InvalidRequestError: Request req_uw01jvGbSTSTQWqCezMgCw: Unknown environment 'GazeboCircuitTurtlebotLidar-v0'. No  registered env with id: GazeboCircuitTurtlebotLidar-v0

### ISSUE THREAD

**Issue by RDaneelOlivav** [openai/gym#571]
Hi , 
I'm trying to upload this environment data put for some reason, is tells me that its unknown?
#!/usr/bin/env python
import gym
import gym_gazebo
import universe
gym.upload('/tmp/gazebo_gym_experiments', api_key='MY_API_KEY')
Any ideas why?
Is there any extra procedure that I'm not aware of?

**Comment by tlbtlbtlb** [comment]
The scoreboard only knows about environments defined in the gym repo. Add-on repos like gym_gazebo aren't currently uploadable. We're working on a new scoreboard/benchmark system that will handle this.

**Comment by frankier** [comment]
Shouldn't it be possible to run your own instance of the scoreboard server for testing anyway?

**Comment by christopherhesse** [comment]
Thanks for the feedback but the scoreboard isn't active anymore, so I am closing this issue.
