### ISSUE TITLE
Env.configure has been removed in gym v0.8.0, released on 2017/03/05.

### ISSUE THREAD

**Issue by skur42** [openai/gym#572]

**Comment by tlbtlbtlb** [comment]
What is the issue you're having?

**Comment by skur42** [comment]
I tried to use env.configure command and an error occured saying env.configure has been removed in gym v0.8.0 so you need to use and old version

**Comment by tlbtlbtlb** [comment]
`env.configure` is not needed in gym any more. Just remove your call to it.
