### ISSUE TITLE
Bad rendering in FronzenLake

### ISSUE THREAD

**Issue by pablocastilla** [openai/gym#573]
Hi!

If I just move in frozen lake to the right twice I don't see the red square in that position.

Quite strange:

Code:
import gym
import tensorflow as tf
import numpy as np

env = gym.make('FrozenLake-v0')

env.reset()
rewards = []
for _ in range(2):    
    state, reward, done, info = env.step(2) 
    env.render()   
    rewards.append(reward)
    if done:        
        env.reset()

Result:

![capture](https://cloud.githubusercontent.com/assets/8155105/25624827/ed7aeff8-2f5a-11e7-97a8-e7bd8eb326bc.PNG)

Thanks

**Comment by tlbtlbtlb** [comment]
From https://gym.openai.com/envs/FrozenLake-v0:

  "However, the ice is slippery, so you won't always move in the direction you intend."

Specifically, it has a 1/3 chance of moving in the direction given and 1/3 each to the orthogonal directions. It never moves in the opposite direction. A tabular Q learning agent should have no problem figuring this out.

**Comment by pablocastilla** [comment]
Ouch! Sorry! 

I will try to program better than I read :)
