### ISSUE TITLE
Missing previous environment on the website

### ISSUE THREAD

**Issue by danijar** [openai/gym#574]
Several environments on gym.openai.com/envs have no previews. For example, half of the [classic control environments](https://gym.openai.com/envs#classic_control) and all of the [Minecraft environments](https://gym.openai.com/envs#minecraft). I believe adding previews would make the tasks more accessible. How do the previews get generated?

**Comment by danijar** [comment]
@gdb?

**Comment by christopherhesse** [comment]
Looks like classic control envs have videos now and minecraft envs don't exist anymore.  Thanks for the feedback!
