### ISSUE TITLE
Ubuntu on Windows running openAI gym, env.render() give out nothing

### ISSUE THREAD

**Issue by RuihongQiu** [openai/gym#576]
[http://stackoverflow.com/questions/43716468/ubuntu-on-windows-running-openai-gym-env-render-give-out-nothing](url)

Today I met with another question. I use

`env = gym.wrappers.Monitor(env, 'gym_results/CartPole-v0-experiment-1')`

At last, I wanted to upload and the Gym gave me an error

`raise error.Error('[{}] No such video file {}. (HINT: Your video recorder may have broken midway through the run. You can check this with `video_recorder.functional`.)'.format(env_id, video_path))
gym.error.Error: [CartPole-v0] No such video file /mnt/d/RL/gym_results/CartPole-v0-experiment-1/openaigym.video.0.1606.video000000.mp4. (HINT: Your video recorder may have broken midway through the run. You can check this with `video_recorder.functional`.)`

**Comment by tlbtlbtlb** [comment]
In order for video recording to work, it needs a working X11 server. See http://xpra.org/trac/wiki/Xdummy for one that works inside a Linux container.
