### ISSUE TITLE
CartPole-v0 flash 

### ISSUE THREAD

**Issue by pickittwice** [openai/gym#579]
I'm new to openai gym and when i ran the example CartPole-v0 on the site, the simulator flashed (ran very fast). I try to set env.mode='human' but it makes no difference. Is there anyone who has come across the same issue? thx

**Comment by tlbtlbtlb** [comment]
CartPole indeed runs very fast. This is mostly a feature, since it takes thousands of episodes to train an agent. If you want to slow it down, add a `time.sleep(0.1)` after the call to `env.render()`.

**Comment by pickittwice** [comment]
Thanks.  :)

**Comment by nyck33** [comment]
Is this the correct placement of `time.sleep(0.1)` below?
```
import gym
env = gym.make('CartPole-v0')
env.reset()
for _ in range(1000):
    env.render()
    time.sleep(0.1)
    env.step(env.action_space.sample()) # take a random action
```

**Comment by thedictionary** [comment]
that code isnt working for me. I use jupyter and have imported all the files (tf, numpy, gym etc.) yet when i run every cell together it just opens a freeze frame of the game. anyone know why this is?
