### ISSUE TITLE
changing action and observation space size

### ISSUE THREAD

**Issue by mohakbhardwaj** [openai/gym#580]
I am trying to make an environment for graph search and need to be able to change the environment and observation space size as more nodes get added to the frontier. Is it possible using the current gym spaces? and is there any tutorial on how to implement your own spaces

**Comment by stevenschmatz** [comment]
Which action/observation space objects are you using?

* One option would be to directly set properties of the `gym.Space` subclass you're using. For example, if you're using a `Box` for your observation space, you could directly manipulate the space size by setting `env.observation_space.low` and `env.observation_space.high` values. Check out the [source code](https://github.com/openai/gym/blob/master/gym/spaces/box.py) for more details.
* Alternatively, you could directly create a new `Space` object and set it to be your observation space: `env.observation_space = Box(low, high, shape)`. Doing this rapidly would probably be more costly than the other method.

Not sure what the other options are here, but would love to hear a second opinion. As for a tutorial, I couldn't find one, but you could take a look at the [code for some built-in envs](https://github.com/openai/gym/tree/master/gym/envs) to get started!

**Comment by mohakbhardwaj** [comment]
I am using Box for the observation space and Discrete for my action space and both keep on changing as the size of my search frontier increases, so the second option might not be very feasible for me. I will try the first one and see the results. For Discrete space, would changing the `env.action_space.n` property be sufficient?

**Comment by stevenschmatz** [comment]
Yes, I think changing the `env.action_space.n` should be sufficient.

**Comment by theonlyjohnny** [comment]
Any note on whether or not this worked for you @mohakbhardwaj ?

**Comment by mohakbhardwaj** [comment]
@theonlyjohnny  I was able to get this working using the advice from @stevenschmatz

**Comment by nnmsIsaac** [comment]
Close this issue, maybe?

**Comment by shuruiz** [comment]
You can define you space like this:

`from gym import spaces
space = spaces.Discrete(8) # Set with 8 elements {0, 1, 2, ..., 7}
x = space.sample()
assert space.contains(x)
assert space.n == 8`

The space library enables your to define your own action/state space. 

source: [https://gym.openai.com/docs/](doc)

**Comment by Eriz11** [comment]
@mohakbhardwaj I'm developing an environment that has a changing action space, as your case. The implementation seems reasonable. However, I have doubts on how to then integrate it within the agents. 

¿Could you please elaborate a bit more on how did you handle this within the agents? I mean, the last layer of a DQN model for example would need to change its outputs constantly. ¿Did you implement the agent yourself or did you use some library + wrapper?

Many thanks in advance,

**Comment by ppanteliadis** [comment]
Would it be possible then to have an observation space of varying y dimensions? 
for example

After first iteration:
```
array([[0.],
           [0.],
           [0.]])
```

After second iteration:
```
array([[0., 0.],
           [0., 0.98],
           [0., 0.]])
```

And at the third:
```
array([[0., 0., 0],
           [0., 0.98],
           [0., 0.]])
```

In this example, in the second iteration the dimensions of the obs space changed from (3,1) to (3,2) and at the 3rd iteration they changed to (3,3) on the first row and remained (3,2) on the rest. Is this possible?

**Comment by hojoung97** [comment]
> Would it be possible then to have an observation space of varying y dimensions?
> for example
> 
> After first iteration:
> 
> ```
> array([[0.],
>            [0.],
>            [0.]])
> ```
> 
> After second iteration:
> 
> ```
> array([[0., 0.],
>            [0., 0.98],
>            [0., 0.]])
> ```
> 
> And at the third:
> 
> ```
> array([[0., 0., 0],
>            [0., 0.98],
>            [0., 0.]])
> ```
> 
> In this example, in the second iteration the dimensions of the obs space changed from (3,1) to (3,2) and at the 3rd iteration they changed to (3,3) on the first row and remained (3,2) on the rest. Is this possible?

Does anybody know if this is possible?

**Comment by shuruiz** [comment]
> > Would it be possible then to have an observation space of varying y dimensions?
> > for example
> > After first iteration:
> > ```
> > array([[0.],
> >            [0.],
> >            [0.]])
> > ```
> > 
> > 
> > After second iteration:
> > ```
> > array([[0., 0.],
> >            [0., 0.98],
> >            [0., 0.]])
> > ```
> > 
> > 
> > And at the third:
> > ```
> > array([[0., 0., 0],
> >            [0., 0.98],
> >            [0., 0.]])
> > ```
> > 
> > 
> > In this example, in the second iteration the dimensions of the obs space changed from (3,1) to (3,2) and at the 3rd iteration they changed to (3,3) on the first row and remained (3,2) on the rest. Is this possible?
> 
> Does anybody know if this is possible?

I don't think so. It's like you want to handle some time-related behavior. I think this formation might produce issues in your algo. If you accumulating your observation, your observation space size can go to infinity. I personally suggest you change your observation space formation.

**Comment by GaetanLepage** [comment]
I have a similar problem: my observations are numpy arrays of different length.
I have found this which might help: https://github.com/szemenyeim/DynEnv#the-observation-space
