### ISSUE TITLE
Tuple from_jsonable bug

### ISSUE THREAD

**Issue by unixpickle** [openai/gym#582]
The `Space.from_jsonable` method is supposed to take a batch of samples and convert each one from JSON to a space value. That's not what the [Tuple.from_jsonable](https://github.com/openai/gym/blob/314a20047ed9224437941e13b262d1276531eedf/gym/spaces/tuple_space.py#L31) method currently does. Rather, the current implementation treats sample_n as a tuple of batches, rather than as a batch of tuples.

This can result in an exception which looks something like this:

```
Traceback (most recent call last):
  File "/path/code/code/file.py", line 1337, in some_method
    return env.action_space.from_jsonable([obj])[0]
  File "/usr/local/lib/python3.6/site-packages/gym/spaces/tuple_space.py", line 31, in from_jsonable
    return zip(*[space.from_jsonable(sample_n[i]) for i, space in enumerate(self.spaces)])
  File "/usr/local/lib/python3.6/site-packages/gym/spaces/tuple_space.py", line 31, in <listcomp>
    return zip(*[space.from_jsonable(sample_n[i]) for i, space in enumerate(self.spaces)])
IndexError: list index out of range
```

**Comment by tlbtlbtlb** [comment]
> The `Space.from_jsonable` method is supposed to take a batch of samples and convert each one from JSON to a space value

I don't know where anyone committed to that semantics. The important requirement is that `s.from_jsonable(json.loads(json.dumps(s.to_jsonable([x1, x2, ...])))` is an identity. Which as far as I can tell it is:
```
>>> s = Tuple([gym.spaces.Discrete(3), gym.spaces.Discrete(5)])
>>> list(s.from_jsonable(json.loads(json.dumps(s.to_jsonable([(1,1),(2,4),(0,4)])))))
[(1, 1), (2, 4), (0, 4)]
```

The list-of-batches representation lets us use the from_jsonable/to_jsonable methods from the component spaces.

**Comment by unixpickle** [comment]
Ah, I see what you mean. I just assumed that "batch of x" meant that it was a "list of x", but that is an invalid assumption. Thanks.
