### ISSUE TITLE
Env.isTerminal(observation)

### ISSUE THREAD

**Issue by rafaelcp** [openai/gym#59]
I'm working with model-based RL and it is necessary to know if some observation is terminal **without** experiencing it. But this information is buried into the environment's step function when assigning a value to "done". Then, for instance, I have to hardcode the condition for each environment in my algorithm (like "if observation[0] >= 0.5" in Mountain Car). If there was a "**isTerminal(observation)**" method in Env, hardcoding wouldn't be necessary.
I don't know if it is ok according to the Gym philosophy or if you think it is too much work for too little, so I'll leave it here for discussion.

Edit: according to the project's coding style, I think the method's name would be **is_terminal** instead.

**Comment by gdb** [comment]
Yes, that strikes me as a very good idea. I'd probably call it `is_done` or `observation_done`. @joschu do you see any issues with it?

**Comment by rafaelcp** [comment]
Once we reach a consensus, I can make a PR with refactored code for the few environments I currently have access to (classic and text I think). But how would it be done in the main Env class? A default method that always return false?

**Comment by joschu** [comment]
I don't think we should add it -- this function is not available in general POMDPs

**Comment by rafaelcp** [comment]
John Schulman @joschu 15:41
@rafaelcp I'm not in favor of adding this function, because the episode termination is not necessarily a function of the observation
also, one should never need to use the observation from a terminal state, the last observation you receive in an episode is from the last non-terminal state
or more precisely, from the transition from a nonterminal to terminal state

rafaelcp @rafaelcp 15:43
@joschu that's exactly the doubt I had when asking for discussion  Then, do you think there is some way around it for my case? I can always learn the terminal condition too.

John Schulman @joschu 15:44
yeah, the model-based algorithm should probably learn it

rafaelcp @rafaelcp 15:44
yes, but we update the previous state based on the terminal one reward, and should know that there is no "maxQ" to compute there in this case

John Schulman @joschu 15:46
i don't understand exactly what your setup is, is this a DYNA type algorithm?

rafaelcp @rafaelcp 15:46
precisely
with function approximation
so I can't just put 0 on terminal states' Q values

John Schulman @joschu 15:47
Could you just learn a function that tells you if you're in a terminal state
and use that as part of your Q-value backup?

rafaelcp @rafaelcp 15:50
Yes, that was the first thing I did, but since terminal states are relatively rare, it's somewhat hard to learn. Then I thought having it in the environment wouldn't be "cheating", but you have a point on the POMDP formal definition.
