### ISSUE TITLE
Grumpy - automatic porting of python code to golang for learning on the job.

### ISSUE THREAD

**Issue by joeblew99** [openai/gym#591]
Is there anyone interested in a golang port using codegen to golang ?

https://github.com/google/grumpy

I know this is contentious and I am not wishing to raise the language wars debate.
Python and golang are both great.

However the usecases I am thinking about are IOT, mobiles and unikernels environments where using python is an issue. Also the whole point as you have seen in Tesla cars is that you need your machine learning to also run out in the field and then compress and send some aggregates back to your data center. Been there done that :)

The grumpy code generator is not perfect but getting pretty good. It's being done by the YouTube team because they want to port their python code to golang.  They want to help other code bases also move across.

**Comment by christopherhesse** [comment]
It looks like grumpy is not being maintained.  Swift has some interop that looks like it might do something like this: https://github.com/tensorflow/swift/blob/master/docs/PythonInteroperability.md
