### ISSUE TITLE
the less frequently I want to make videos the longer it takes to record them

### ISSUE THREAD

**Issue by gasiort** [openai/gym#592]
Hi, I am experiencing strange behaviour when setting video_schedule parameter in GymEnv. 
```python
step = 20000
video_schedule = lambda episode_id: episode_id % step == 0
env = normalize(GymEnv(args.env, log_dir='/tmp/videos/trpo_rllab', video_schedule=video_schedule))
```
the bigger the step is the longer it takes to record video. 

It's custom, mujoco based, environment. Recording time is proportional to the `step` value. For instance, with `step=20000` it takes 45 minutes to record. 

Anyone had the same bug?

**Comment by tlbtlbtlb** [comment]
It takes a long time because it has to run through 19999 episodes without making a video before making the first one. (Under normal use, the first episode_id will be 1). You might change to 
```
video_schedule = lambda episode_id: episode_id % step == 1
```
if you want a video of the first episode.

**Comment by gasiort** [comment]
I mean the process of creating video takes too much time. For instance 1 iteration with 500 episodes takes about 1 minute. Then after 40 iterations program freezes for 30mins to produce video. I should be more clear about this.

I just wanted to reduce training time by producing fewer videos but it actually feels like whatever `step` I set I always end up with same training time (fewer videos but more time spent to produce each).

**Comment by gasiort** [comment]
It halts after computing first frame
