### ISSUE TITLE
rendering breaks after installing universe

### ISSUE THREAD

**Issue by nolsigan** [openai/gym#596]
Hi,

I was working with Breakout-v0 alright until yesterday, but screen rendering became weird after installing openai/universe.
<img width="159" alt="screenshot" src="https://cloud.githubusercontent.com/assets/8858376/26297610/8b4b2dc0-3f0e-11e7-9c6d-7cb2a1b16378.png">

I tried checking out to previous commits where universe is not used and also tried removing packages that I installed for universe

`pip uninstall universe`
`brew uninstall libjpeg-turbo`
`brew uninstall golang`

It still doesn't solve the issue.

Did anyone experience similar issue before?

edit) I tried making new virtual python environment and it works fine

It seems like dependent package for universe is causing the break

**Comment by stefanutti** [comment]
@nolsigan 

What do you mean exactly with:
"edit) I tried making new virtual python environment and it works fine"

**Comment by nolsigan** [comment]
@stefanutti 

I use virtualenv and uninstalling universe from current env didn't solve the problem. So I deactivated current env, created new one, and installed packages except universe.

Then gym started to display correctly. So my guess was 'pip uninstall universe' doesn't erase all dependent packages that 'pip install universe' installed, and one of those unerased packages causes the display to break.

**Comment by stefanutti** [comment]
This downgrade worked also for me:
- pip install atari-py==0.0.21

**Comment by hikirkendall** [comment]
It is the version problem of gym.
By using pip install gym==0.10(my case) and modify environment.py :
modify: self.env = gym.make(config.env_name)
to: self.env = gym.make(config.env_name).unwrapped
It is for all games in gym

**Comment by christopherhesse** [comment]
Thanks for answering this @hikirkendall, please file a new issue against `atari_py` if this is still happening
