### ISSUE TITLE
CarRacing-v0 always terminating after 1000 frames

### ISSUE THREAD

**Issue by sjang92** [openai/gym#597]
Hi, 

I am training my agent to play the CarRacing-v0 environment.
I notices that the terminal flag (returned by s, r, terminal, info = env.step(a)) always becomes True after 1000 frames during training. When I play the environment myself, it doesn't happen. Has anyone seen this problem before?
![screen shot 2017-05-21 at 10 46 51 pm](https://cloud.githubusercontent.com/assets/3598201/26327574/cf103c72-3ef4-11e7-8487-d96f918d42c0.png)

**Comment by hholst80** [comment]
The `CarRacing-v0` environment has a step limit of 1000. If you want you can create your own environment that does not have a limit, or has a higher limit.

```
In [2]: env = gym.make('CarRacing-v0')
[2017-06-23 13:39:33,745] Making new env: CarRacing-v0

In [3]: env.spec.max_episode_steps
Out[3]: 1000
```

To create your own environment without a limit you can run the following code:

```
register(
    id='CarRacing-v1', # CHANGED
    entry_point='gym.envs.box2d:CarRacing',
    # max_episode_steps=1000, # CHANGED
    reward_threshold=900,
)
```

Based on https://github.com/openai/gym/blob/5cb12296274020db9bb6378ce54276b31e7002da/gym/envs/__init__.py

**Comment by christopherhesse** [comment]
Thanks for answering this @hholst80!

**Comment by smmuzza** [comment]
thanks for this, it was confusing me a lot

does the leaderboard also have this limit?
https://github.com/openai/gym/wiki/Leaderboard
