### ISSUE TITLE
Taxi-v0 isn't returning the right reward for dropoff

### ISSUE THREAD

**Issue by chrisranderson** [openai/gym#6]
It returns -1 reward for a successful dropoff. The paper (https://www.jair.org/media/639/live-639-1834-jair.pdf) uses +20.

**Comment by joschu** [comment]
Thanks for pointing that out. It shouldn't affect the problem much because it'll just shift the optimal return by a constant, but we might as well adhere to Dietterich's specification.

**Comment by joschu** [comment]
Closing now, if we upgrade to Taxi-v1, we'll change it.
