### ISSUE TITLE
Would be nice to have easily viewable API docs as part of the documentation

### ISSUE THREAD

**Issue by mpacer** [openai/gym#616]
I realise these docs are mostly for users, but it'd be useful to surface API docs as well, especially for anyone who wanted to extend the behaviour of some of the classes (e.g., the `render()` function should work better in a jupyter notebook, see https://github.com/openai/gym/issues/56). I work on Jupyter & IPython's display mechanism. I want to work on solving this, but it's much harder to do that when there's no narrative docs explaining the design behind the current `render` API. I imagine this goes for other aspects of the API as well.

**Comment by gdb** [comment]
Thanks for the feedback. Any specific questions that I can answer? The implementations and semantics of these methods vary widely, since environments are so diverse, so there's not much more to be said than the docstring here: https://github.com/openai/gym/blob/master/gym/core.py#L109-L146.

**Comment by mpacer** [comment]
Yes I spent all weekend looking into the different envs and their approaches to rendering. I think what would have been useful was more than just a docstring describing the approach behind the core supported envs. For example this would lay out (narratively) what their requirements would be for supporting their outputs from a front-end perspective. 

Here are the kinds of things I learned from my exploration

Overall, I think the classic_control's pyglet window is going to be pretty hard to deal with directly. @carreau suggested trying to draw to a canvas optionally would allow us to create an html mimetype. My having looked at the way the pyglet rendering classes are made suggests that there might be a way to hijack the processing before creating the window while using the same underlying structures to write to a HTML5 canvas instead. That might be the easiest solution for that case.  
The key that would have been great to know from narrative docs was that there is no way to render any image without relying on the pyglet rendering context. 

For the Atari games it would be straightforward to just wrap something in the back end to capture the sequence of images and transform them either to a gif or a video, without needing a rendering window (since they wouldn't need to trigger `gym.classic_control.rendering.SimpleImageViewer` when you use the `rgb_array` output method.  The key that would have been great to know from narrative docs is that the Atari method does not require a pyglet window to get the image output.

I haven't figured out as much about the `ansi` approach because I imagine that the trick there is going to be figuring out how to do an inplace overwrite of the content (ala a video but for terminal output). I think that's been solved on our side but I forget where or how.  
I don't know if there is anything that narrative docs would have helped with.

Does this clarify the lines along which I'm thinking?

**Comment by gdb** [comment]
Got it, sounds like a productive weekend :). I would be very happy to merge a PR adding these findings to the docs section of the repo: https://github.com/openai/gym/tree/master/docs, but it's unfortunately not something we're going to get to in the short term ourselves.
