### ISSUE TITLE
Wrappers for AtariEnv used in baselines

### ISSUE THREAD

**Issue by muupan** [openai/gym#617]
https://github.com/openai/baselines has a set of wrappers for AtariEnv to mimic the configuration used in DeepMind papers:

https://github.com/openai/baselines/blob/master/baselines/common/atari_wrappers_deprecated.py

I think these wrappers are very useful and should be merged into gym.

**Comment by muupan** [comment]
I can send a PR for it, but I'm not sure I'm a right person to do it because I'm not the author of baselines.

**Comment by hholst80** [comment]
Sounds like an excellent idea!

**Comment by christopherhesse** [comment]
I think this is being addressed in @zuoxingdong's PRs: https://github.com/openai/gym/pull/1488

**Comment by christopherhesse** [comment]
Going to close this because of @zuoxingdong's PRs, if there's a missing one, file a new issue please.
