### ISSUE TITLE
New environment class

### ISSUE THREAD

**Issue by sven1977** [openai/gym#618]
Hi openAI team,
talking to Rocky Duan over at the rllab repo about my pygame based 2D game engine where one can create any level via a simple tmx file, he told me to make this available as an Env in the gym.

I'm almost done creating a sample level for "The Lost Vikings" game from the 90s, a platformer with 3 agents, between which one can switch at any time:
![the lost vikings screenshot](http://en.ducandu.com/lostvikings/lostvik_sample2.png)

My question is now, should I do this as an external package (that you would just link to from your [website](https://gym.openai.com/envs)), or as an integral part of your gym repo?

Regards,
Sven

**Comment by christopherhesse** [comment]
We have a guide for how to create a gym environment as a python package here: https://github.com/openai/gym/blob/master/docs/creating-environments.md

As well as a list of environments here: https://github.com/openai/gym/blob/master/docs/environments.md

The env looks pretty nice from the screenshot!  Please submit a PR to add a link to your environment to the list.
