### ISSUE TITLE
MultiDiscrete iterates twice over input

### ISSUE THREAD

**Issue by ngc92** [openai/gym#622]
The current implementation of `spaces.MultiDiscrete` iterates the `array_of_param_array` twice.
This fails in python 3 if an input iterator is provided, like the result of a zip operation.
More importantly, this fails without any warnings or errors, but assigns an empty list to the `high` member variable.

Either MultiDiscrete should support input iterators, or it should at least check that 
`low.shape == high.shape` and raise an error otherwise.

**Comment by christopherhesse** [comment]
Thanks for the bug report, are you interested in creating a PR for this?

**Comment by ngc92** [comment]
The problem as described above does not exist anymore. In 4c460ba6c8959dd8e0a03b13a1ca817da6d4074f the explicit iteration was removed. 

In the current version, `__init__` does not accept generator objects, but requires something that is at least a sequence, so the double iteration does not cause a silent failure anymore. I could make a PR that also allows general iterables to be passed to `__init__.

On another note, there is currently a comment claiming
```
# if nvec is uint32 and space dtype is uint32, then 0 <= x < self.nvec guarantees that x
# is within correct bounds for space dtype (even though x does not have to be unsigned)
```
but `__init__` sets `nvec` to be of type `int64`.

**Comment by christopherhesse** [comment]
Okay, well I guess it's at least not an issue anymore.  Please file a PR to update the comment if you are interested in that.
