### ISSUE TITLE
tic tac toe environment

### ISSUE THREAD

**Issue by Kallin** [openai/gym#625]
I am considering adding a tic-tac-toe environment in order to have a simpler env that can be 'solved' quite easily'.

If I were to open a PR for this env would it be accepted?

**Comment by hholst80** [comment]
I think we have a good supply of "toy environments". If you would make something more intermediate like https://en.wikipedia.org/wiki/Renju I think it could be interesting?

**Comment by Kallin** [comment]
Thanks @hholst80 ,

I have another issue opened to discuss a framework for describing arbitrary games. Renju would be a perfect candidate for such a system I believe. My suggestion for 'tic-tac-toe' was in response to seeing the included 'board game' examples in the project: "GO" and "Hex", both fairly complicated. Perhaps you're right that the existing 'toy' examples such as 'guessing game' provide enough simple examples. However, I think there is something unique about the multi-player board-games due to them requiring 'adversary policies', which I don't see in the toys.

**Comment by pavelsavara** [comment]
Somebody already did that
https://github.com/nczempin/gym-tic-tac-toe

**Comment by christopherhesse** [comment]
We're not currently accepting new environment PRs, but you can definitely make your own environment as a separate python package, as described here: https://github.com/openai/gym/blob/master/docs/creating-environments.md
