### ISSUE TITLE
How to make environment

### ISSUE THREAD

**Issue by lilyxoxo** [openai/gym#626]
Hello, I am a beginner of open ai gym.
 I want to add my environment, but I cannot do well.
Could someone tell me how to make new environment?
https://github.com/openai/gym/wiki/Environments
I did it along this wiki, and I run random_agent.py(replace CartPole-v0 to MyEnv-v0)

(ml_env_2)S-no-MacBook-Air-2:agents $ python random_agent.py
[2017-06-18 17:27:44,978] Making new env: MyEnv-v0
Traceback (most recent call last):
  File "random_agent.py", line 36, in <module>
    env = gym.make(args.env_id)
  File "/Users/S/.pyenv/versions/miniconda3-latest/envs/ml_env_2/lib/python2.7/site-packages/gym/envs/registration.py", line 161, in make
    return registry.make(id)
  File "/Users/S/.pyenv/versions/miniconda3-latest/envs/ml_env_2/lib/python2.7/site-packages/gym/envs/registration.py", line 118, in make
    spec = self.spec(id)
  File "/Users/S/.pyenv/versions/miniconda3-latest/envs/ml_env_2/lib/python2.7/site-packages/gym/envs/registration.py", line 147, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: MyEnv-v0

**Comment by Jackiexiao** [comment]
same problem

**Comment by hholst80** [comment]
The question is how to register your own environment in the registry?

Lets say you have your own environment defined in the following structure:

```
myenv/
    __init__.py
    myenv.py
```

`myenv.py` contains the class for your environment. In `__init__.py` you put the following code:

```
from gym.envs.registration import register

register(
    id='MyEnv-v0',
    entry_point='myenv.myenv:MyEnv',
)
```

To use your own environment

```
import gym
import myenv
env = gym.make('MyEnv-v0')
```

More detailed example on how to register your own environments have a look here: https://github.com/openai/gym/blob/522c2c532293399920743265d9bc761ed18eadb3/gym/envs/__init__.py

NOTE: You have to have `myenv` directory in your PYTHONPATH or start python from the parent directory.

**Comment by MartinThoma** [comment]
See also on StackOverflow: [Is it possible to create a new gym environment in OpenAI?](https://stackoverflow.com/q/45068568/562769)

**Comment by Sohojoe** [comment]
@lilyxoxo - did this solve it for you? I create my own enviroments and could knock up a sample git repro if you are still stuck

**Comment by fhoelzl** [comment]
@Sohojoe That would be great. Even though the question is asked quite poorly there are probably a few others looking for something like to help them make their own environment.

**Comment by lily-xoxo-30** [comment]
@Sohojoe  I apologize for this late reply.
I have already solved this problem.
Thank you.

**Comment by lily-xoxo-30** [comment]
close

**Comment by lily-xoxo-30** [comment]
**close**

**Comment by peterlabuschagne** [comment]
@lily-xoxo-30 could you maybe share your solution or give a quick how to? I’m also struggling with this problem now for a while already.

**Comment by MartinThoma** [comment]
@peterlabuschagne Did you have a look at https://stackoverflow.com/a/47132897/562769 ?  What else do you need?

**Comment by cristyandavid1** [comment]
I’m trying to build my self a A.i so I’m sure my is going right and on time

**Comment by peterlabuschagne** [comment]
@MartinThoma no I hadn't yet seen that, but that really answers the questions I've had up until now. Hopefully the rest is smooth sailing. Thanks a lot!

**Comment by cyrilzakka** [comment]
I've followed all the steps outlined above but I get the following error when importing the gym: 
ModuleNotFoundError: No module named 'gym_foo'

**Comment by christopherhesse** [comment]
Thanks for answering this @hholst80!  Please see the documentation here: https://github.com/openai/gym/blob/master/docs/creating-environments.md

**Comment by mullachv** [comment]
What fixed this for me was prefixing ```foo-v0``` in the following line:
```
gym.make('gym_foo:foo-v0')
```
