### ISSUE TITLE
Taxi environment unusable

### ISSUE THREAD

**Issue by jenleong** [openai/gym#629]
# Problem
Taxi is broken right now. Taxi-v1 is deprecated, but uploading Taxi-v2 is not supported on the server.

# Steps to reproduce
 
`gym.make("Taxi-v1")`
results in an error:

> DeprecatedEnv: Env Taxi-v1 not found (valid versions include ['Taxi-v2'])

So, we use Taxi-v2.

```
env = gym.make('Taxi-v2')
env = wrappers.Monitor(env, 'taxidir', force=True)
state = env.reset()
for _ in range(10000):
    state, reward, done, info = env.step(env.action_space.sample())
    if done: 
        break 
env.close()
gym.upload('taxidir', api_key=TOKEN)
```

However, now we get this error:

> InvalidRequestError: Request req_7FQsZgRSTq63SQwcLlTbmQ: This version of the environment is not registered on the server, but other versions exist. You may need to upgrade your version of gym. Env Taxi-v2 not found (valid versions include ['Taxi-v1'])

But Taxi-v1 is deprecated, which means it is not valid. No version of Taxi works, therefore Taxi is broken!

More details in #507.

**Comment by christopherhesse** [comment]
The website no longer exists, closing this issue.
