### ISSUE TITLE
Feature req: Set environment spec

### ISSUE THREAD

**Issue by hholst80** [openai/gym#632]
In this commit https://github.com/openai/gym/commit/2b30434d14a5bd27087ae672264a9f8beb90947e env.spec was remade into a property. 

We would like have a setter for this property because of the use case where we have our own make function where we can override some options for the environment:

```
def make(id, **kwargs):
    spec = gym.spec(id)
    cls = gym.envs.registration.load(spec._entry_point)
    args = spec._kwargs.copy()
    args.update(kwargs)
    env = cls(**args)
    spec._kwargs = args
    env.spec = spec
    if (env.spec.timestep_limit is not None) and not spec.tags.get('vnc'):
        from gym.wrappers.time_limit import TimeLimit
        env = TimeLimit(
            env,
            max_episode_steps=episode_steps=env.spec.max_episode_steps,
            max_episode_seconds=episode_steps=env.spec.max_episode_seconds
        )
    return env
```

If this sounds reasonable, to have a setter for env.spec, I can submit a PR. If there is a better workaround for our use case I'd like to hear about it.

**Comment by hholst80** [comment]
We are applying a workaround for now where we use `env._spec = spec`.

**Comment by christopherhesse** [comment]
Hmm, why can't you set the spec property directly?

**Comment by hholst80** [comment]
You cannot set the underlying variables without a "setter". 

https://www.python-course.eu/python3_properties.php

**Comment by blueyanggg** [comment]
I am using gym version 0.14.0.  I solved this problem by using **env.spec.max_episode_steps** instead of **env.spec.timestep_limit**
