### ISSUE TITLE
Is there a contribution guideline?

### ISSUE THREAD

**Issue by FirefoxMetzger** [openai/gym#635]
I haven't found anything when searching for it.
As of yet, is there any guideline to how a contribution should be structured or what constraints have to be accounted for?
Will there be one in the future or are we simply allowed to submit anything (within reason) as a PR?

**Comment by olegklimov** [comment]
Policy is: improve this project within its scope, post PRs. In "improve" it is implied that less code is better.  New environments should be in separate repositories as there are too many of them to all be there.

**Comment by christopherhesse** [comment]
I think @olegklimov answered this already, but PRs that fix bugs in gym are welcome, new environments are not being added to this repo, but they can be added to this document: https://github.com/openai/gym/blob/master/docs/environments.md
