### ISSUE TITLE
Breakout-v0 "pauses"

### ISSUE THREAD

**Issue by rmeertens** [openai/gym#639]
Hey everyone, 

I am facing a strange bug/feature in the Breakout-v0 environment: sometimes it takes a long time before the ball starts dropping again. You can see it clearly in this .gif I made: https://imgur.com/a/kgwf6
For a pretty long time nothing is happening in the game, the bot just moving around a bit, till the ball comes back into play. 

Is this an error in the gym environment? Is this something that is part of the game Breakout-v0?

I also posted this questions on stackoverflow, but unfortunately it received no attention: https://stackoverflow.com/questions/44777068/openai-gyms-breakout-v0-pauses

**Comment by wagonhelm** [comment]
The ball will not drop unless the fire button is pressed, possibly your agent is just not pressing fire?

You can always try playing a environment yourself for insights using [play.py](https://github.com/openai/gym/blob/master/gym/utils/play.py#L185)

**Comment by christopherhesse** [comment]
Thanks for answering this @wagonhelm!
