### ISSUE TITLE
c/c++ interface in future?

### ISSUE THREAD

**Issue by hjchen2** [openai/gym#640]
Is it possible to provide an c/c++ interface in the future?

**Comment by olegklimov** [comment]
Just use HTTP binding.

**Comment by hjchen2** [comment]
@olegklimov  Thank you for your reply. There is something wrong with c++ binding, so I plan using python c api .

**Comment by masotrix** [comment]
I prefer this (faster than http binding and c++ working): https://github.com/integeruser/gym-uds-api
This could be needed to install it: https://askubuntu.com/questions/1072683/how-can-i-install-protoc-on-ubuntu-16-04
