### ISSUE TITLE
Agent registration and adding some common Agents such as DQN, DDQN, DDPG etc.

### ISSUE THREAD

**Issue by benelot** [openai/gym#648]
Hello everyone!

I recently built an Agent registration system based on the Environment registration system of OpenAI. I am mainly using this to make my common Agents (implemented via KerasRL) quickly available to myself in code. I just thought that this could also be handy to others which maybe would like to be able to load some common Agents when doing research or others that might want to register their own package of baseline agents they usually do experiments with. 

An important discussion would definitely be the interface which is implemented by the registered agents. Do not work, it is a light interface, still providing all the freedom you might wish for (basically, there is already a vague interface on how to interact with an environment, so there are some guidelines on how to create an interface for the agent.)

Below is the Template I am currently using when coding a new Agent, but this can be changed of course:

	#!/usr/bin/env python

	def add_opts(parser):
		pass

	class TemplateAgent(object):
		'''
		classdocs
		'''

		def __init__(self, opts):
			self.metadata = {
				'discrete_actions' : True,
			}
			
			self.opts = opts
			
			
		def configure(self, observation_space_shape, nb_actions):
			pass
			
		def train(self, env, nb_steps, visualize, verbosity):
			pass
		
		def test(self, env, nb_episodes, visualize):
			pass
		
		def load_weights(self, load_file):
			pass
		
		def save_weights(self, save_file, overwrite):
			pass

Just give me a comment if this sounds interesting to be added to OpenAI gym!

**Comment by christopherhesse** [comment]
It does sound cool (having a standard agent interface could make a lot of stuff easier), but is definitely out of the scope of gym.   Feel free to have your own repo with this interface in it though.

**Comment by benelot** [comment]
I already do to be honest 😉Thx!
