### ISSUE TITLE
Openai sample always samples same actions in a program run.

### ISSUE THREAD

**Issue by abhigenie92** [openai/gym#649]
I created a new environment and then sampled from it.
The agent always samples the same action.
I am unsure why.
I mean the actions sampled in sequence are always the same.
on each program run.
Even changing seed doesn't do anything.

My enviroment is similar to this https://github.com/gpldecha/gym-leftright/blob/master/gym_leftright/envs/leftright_env.py

**Comment by FirefoxMetzger** [comment]
If you are talking about any "spaces.sample()" as per https://github.com/openai/gym/tree/master/gym/spaces
Then that makes perfect sense.

Spaces are seeded separately from environments, [here](https://github.com/openai/gym/blob/master/gym/spaces/prng.py). As the seed is set to 0 (hardcoded) it will indeed be the same every time you start python.

If you want different behavior, you can seed it manually:

    from gym.spaces import prng
    prng.seed(1337)

or initialise using real randomness (and non-reproducabile agents ;-) ) on a linux machine

    from gym.spaces import prng
    import hashlib
    
    with open("/dev/random", "rb") as file:
        rnd_str = file.read(20)
        seed = int(hashlib.md5(rnd_str).hexdigest(), 16)
        prng.seed(seed)

However, I agree that this could be documented a bit better ...

**Comment by christopherhesse** [comment]
Thanks for answering this @FirefoxMetzger!  I think each space now has it's own random number generator so you may have to seed them individually.
