### ISSUE TITLE
gym upgrade uninstalls numpy

### ISSUE THREAD

**Issue by ghost** [openai/gym#661]
Today I tried to upgrade OpenAI gym and for some strange reason, the procedure included trying to uninstall numpy:

```
Installing collected packages: numpy, atari-py, Pillow, gym
 Found existing installation: numpy 1.13.0
   Uninstalling numpy-1.13.0:
```

Why is this happening?

**Note:** I'm using the Anaconda distribution of scientific python tools on a MacOS Sierra.

**Comment by cshr25** [comment]
hum, I installed the package using pip and it can not find numpy...

**Comment by christopherhesse** [comment]
It looks more like it is installing a different version of numpy, are you installing with `--upgrade`?  Does this still occur with the newest gym?

**Comment by jkterry1** [comment]
This should no number be an issue, but please let me know if it is
