### ISSUE TITLE
Running a custom mujoco env on a remote server 

### ISSUE THREAD

**Issue by amyzhang** [openai/gym#663]
I am trying to run my custom mujoco env on a remote server and getting an error: GLFW error: 65542, desc: GLX: GLX extension not found

Tried it with vncserver and xvfb with no luck.

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
