### ISSUE TITLE
Making Atari environment fails with OSError

### ISSUE THREAD

**Issue by cshenton** [openai/gym#664]
Platform: MacOS Sierra 10.12.3
Language: Python 3.6.1

I followed the instructions to install all environments in the README.

When I try do, for example, `gym.make('SpaceInvaders-v0')` I get the following error:
```
OSError: dlopen(/my/path/to/venv/lib/python3.6/site-packages/atari_py-0.1.1-py3.6.egg/atari_py/ale_interface/build/libale_c.so, 6): image not found
```

**Comment by tonychan818** [comment]
same here

**Comment by cristyandavid1** [comment]
I know how to go to other universes

**Comment by cristyandavid1** [comment]
This is epic

**Comment by cristyandavid1** [comment]
Time travel wow

**Comment by christopherhesse** [comment]
Please try the new atari_py binary wheels and file a new issue if this is still happening.
