### ISSUE TITLE
Mujoco 

### ISSUE THREAD

**Issue by gautam1858** [openai/gym#665]
Hi, Can we get support for Mujoco 1.5 version because the new MacBook doesn't support 1.3 version ?

**Comment by ViktorM** [comment]
The same request. I'm working with Mujoco 1.5 on Windows and can't downgrade it to 1.3 to use it with gym.

**Comment by Carmezim** [comment]
Duplicate of #638

**Comment by christopherhesse** [comment]
Closed as a duplicate.
