### ISSUE TITLE
Overall Software Architecture

### ISSUE THREAD

**Issue by td2014** [openai/gym#666]
Hi.  I'm working to get an overall picture of how your components fit together from an architectural standpoint.  I was thinking that having an "architecture" diagram would be helpful to new folks as well as help guide design decisions.  Is the following the right way to think about your stack?  Thanks.

\--------------------------------------------
User Application:  Agents w/RL algorithms 
\--------------------------------------------
                 gym package API
\--------------------------------------------
gym environments | universe environments ---->(Interface w/docker containers)
\--------------------------------------------
           tensorflow, numpy, etc.
\--------------------------------------------
             python kernel
\--------------------------------------------

**Comment by olegklimov** [comment]
Well this is not a bug in this project, the lack of diagrams. Diagrams can be useful for novices, I think they should appear in RL educational courses.

**Comment by td2014** [comment]
@olegklimov .  Thanks for your comment.  I was asking more from the perspective of your specific (OpenAI's) architecture, not general RL.  I believe that diagrams that explain your architecture(s) would be helpful since as I review your great software offerings, I'm not quite sure how they all relate if I wanted to build out a platform to experiment with your (and other research teams) frameworks.  In any case, I would like to suggest this as a possible addition to OpenAI documentation to make it more intuitive, but this is only a request of course.  Thanks again for your time.
