### ISSUE TITLE
seeding spaces

### ISSUE THREAD

**Issue by FirefoxMetzger** [openai/gym#667]
Spaces are seeded separately from environments. That's good and reasonable, IF you happen to know that it is that way. I for one thought that I can control the seed of the space by calling `env.seed()` for the longest time, because there is nothing suggesting otherwise.

To raise awareness of this I would love to see below two lines added to one of the example agents. Tabular q-learning seems perfect, since it uses epsilon-greedy with `.sample()`.

    from gym.spaces import prng
    prng.seed(0) #optional: manually seed the gym.spaces pRNG

I am happy to provide a PR if someone is willing to review it =)

**Comment by christopherhesse** [comment]
I would review this PR if there is still interest in this.  It might be good to document this in the spaces somewhere as well if this is not mentioned.
