### ISSUE TITLE
Mujoco 1.50 support

### ISSUE THREAD

**Issue by ViktorM** [openai/gym#668]
Hi,

Can you provide some estimates when support of Mujoco 1.50 will be added to the Gym? This version was released quit long ago - in April.

**Comment by gautam1858** [comment]
+1

**Comment by koulanurag** [comment]
+1

**Comment by Carmezim** [comment]
Duplicate of #638

**Comment by wenyeming333** [comment]
+1

**Comment by tartavull** [comment]
+1

**Comment by christopherhesse** [comment]
Closing in favor of https://github.com/openai/gym/issues/638
