### ISSUE TITLE
Beginner/intermediate multi-agent grid games in ToyText

### ISSUE THREAD

**Issue by allanbreyes** [openai/gym#674]
Hi! Would you be interesting in us submitting a few multi-agent Markov games from literature? The motivation would be for providing more approachable alternatives to multi-agent RL other than those in the [Board Games](https://gym.openai.com/envs#board_game). We think that this would be a good "bridge" to go from single-agent to multi-agent RL.

Specifically, I'm proposing the grid games posed in:
- [Littman 1994](https://www.cs.rutgers.edu/~mlittman/papers/ml94-final.pdf)
- [Greenwald 2003](https://pdfs.semanticscholar.org/7480/4472b338283a5b92659db76b55f9eaef8b74.pdf)

As an aside, there doesn't seem to be any general-sum environments where multiple agents are controlled to achieve correlated equilibria. Would there be any interest in implementing some of these where the researcher can control multiple agents (vs. playing against a "good" adversarial agent)?

Thanks!

**Comment by andertavares** [comment]
Hi, I was interested in this issue, specially on Littman's soccer. 

You have closed it because you have added those Markov games?

Thanks
