### ISSUE TITLE
How do I give human inputs to the environment?

### ISSUE THREAD

**Issue by DakshMiglani** [openai/gym#675]
Hey,

I was trying to build the MountainCar-v0 Env but while training I noticed the random steps taken which was in my input data were not efficient and didn't work well, So I decided to give it input on my own but the way to do it is no where to be found?  is there any way to give the env inputs from human?

Best.
Daksh

**Comment by olegklimov** [comment]
Please see keyboard_agent.py

**Comment by eabase** [comment]
@olegklimov 
Where did this go?

**Comment by pseudo-rnd-thoughts** [comment]
See utils.play

**Comment by eabase** [comment]
@pseudo-rnd-thoughts 
Hi Mark, 
TY, but that doesn't seem to work. 
I mean, it runs but nothing at all happens. 

I tried:
```powershell
C:\venvs\lunar\Lib\site-packages\gymnasium\utils
python.exe .\play.py LunarLander-v2
```

In the old version you could do this:
* https://github.com/Farama-Foundation/Gymnasium/issues/1067
