### ISSUE TITLE
How do I find Possible moves in an env?

### ISSUE THREAD

**Issue by DakshMiglani** [openai/gym#676]
I've been searching for possible moves in the Box2D CarRacing-V0 but I'm not able to find it?

**Comment by koulanurag** [comment]
CarRacing-v0 has continuous action space.
```
>>> import gym
>>> env = gym.make('CarRacing-v0')
[2017-08-03 07:17:46,503] Making new env: CarRacing-v0
>>> env.action_space
Box(3,)
>>> env.action_space.sample()
array([ 0.09762701,  0.71518937,  0.60276338])

```
Also, For Discrete Action-Space Env: 

```
>>> import gym
>>> env= gym.make('Pong-v0')
[2017-08-03 07:22:32,390] Making new env: Pong-v0
>>> env.action_space
Discrete(6)
>>> env.unwrapped.get_action_meanings()
['NOOP', 'FIRE', 'RIGHT', 'LEFT', 'RIGHTFIRE', 'LEFTFIRE']
```

**Comment by DakshMiglani** [comment]
Actually I tried to do the same, but That output "Box(3,)" confused me.

**Comment by JarLowrey** [comment]
How do you get the size of a discrete object? Like `env.action_space + 1` would print 7

**Comment by JarLowrey** [comment]
Ah. [Here](https://github.com/openai/gym/blob/master/gym/spaces/discrete.py) is the source, you use `env.action_space.n`, and it prints returns `6`

**Comment by LucasColas** [comment]
Yes `env.action_space.n is pretty` good.

**Comment by typedecker** [comment]
> Pong-v0

Does the env.unwrapped.get_action_meanings() work for the cart pole environment?
