### ISSUE TITLE
use “unwrapped” causes cannot record the video

### ISSUE THREAD

**Issue by Baichenjia** [openai/gym#677]
if I use "unwarpped" function to definite my own reward, then the "Monitor" **cannot** record the video(Except for the beginning). like this:
```
env = wrappers.Monitor(env, "CartPole-experiment", force=True, video_callable=lambda x:True)
env = env.unwrapped
```
And if I call “env.unwrapped”  first, like this,
```
env = env.unwrapped
env = wrappers.Monitor(env, "CartPole-experiment", force=True, video_callable=lambda x:True)
```
then there will be an error:
**'Monitor' object has no attribute 'x_threshold'**

This is because I use these code below:
```
x, x_dot, theta, theta_dot = observation_
r1 = (env.x_threshold - abs(x))/env.x_threshold - 0.8
r2 = (env.theta_threshold_radians - abs(theta))/env.theta_threshold_radians - 0.5
reward = r1 + r2
```

How can I use "env.x_threshold" and **record** the video at the same time

**Comment by RukawaKaede** [comment]
Hi, can you tell me how to solve it finally? :-)

**Comment by iindovina** [comment]
Hi, I was running into the same issue recently. If it was closed because considered "solved" could we know the solution?
