### ISSUE TITLE
installing gym doom fail

### ISSUE THREAD

**Issue by darkstone520** [openai/gym#678]
I'm poor at trouble shooting. 
please help me here. T_T
I already installed all of cmake boost boost-python sdl2 wget. 

kkc:doom-py kyungchankim$ python setup.py build
running build
-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   filesystem
--   thread
--   system
--   date_time
--   chrono
--   regex
--   iostreams
--   atomic
CMake Deprecation Warning at cmake_modules/CreateLaunchers.cmake:48 (cmake_policy):
  The OLD behavior for policy CMP0026 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.
Call Stack (most recent call first):
  src/vizdoom/CMakeLists.txt:13 (include)

-- Could NOT find GME (missing: GME_LIBRARIES GME_INCLUDE_DIR) 
-- Using system zlib
-- Using system jpeg library
-- Using system bzip2 library
-- Using internal gme library
-- /usr/include
-- /usr/include
-- /Users/kyungchankim/doom-py/doom_py/src/vizdoom/lzma/C
-- Could NOT find PkgConfig (missing: PKG_CONFIG_EXECUTABLE) 
-- Could not find FMOD include files
-- Could NOT find MPG123 (missing: MPG123_LIBRARIES MPG123_INCLUDE_DIR) 
-- Could NOT find FluidSynth (missing: FLUIDSYNTH_LIBRARIES FLUIDSYNTH_INCLUDE_DIR) 
-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   thread
--   system
--   date_time
--   chrono
--   atomic
-- Fluid synth libs: FLUIDSYNTH_LIBRARIES-NOTFOUND
-- Using python library: /anaconda/lib/libpython3.5m.dylib
-- Using python include: /anaconda/include/python3.5m
CMake Warning at /usr/local/Cellar/cmake/3.9.0/share/cmake/Modules/FindBoost.cmake:1564 (message):
  No header defined for python-py353; skipping header check
Call Stack (most recent call first):
  CMakeLists.txt:124 (find_package)

-- Could NOT find Boost
CMake Warning at /usr/local/Cellar/cmake/3.9.0/share/cmake/Modules/FindBoost.cmake:1564 (message):
  No header defined for python-py35; skipping header check
Call Stack (most recent call first):
  CMakeLists.txt:133 (find_package)

-- Could NOT find Boost
-- Boost library python-py35: 
CMake Warning at /usr/local/Cellar/cmake/3.9.0/share/cmake/Modules/FindBoost.cmake:1564 (message):
  No header defined for python35; skipping header check
Call Stack (most recent call first):
  CMakeLists.txt:140 (find_package)

-- Could NOT find Boost
-- Boost library python35: 
CMake Warning at /usr/local/Cellar/cmake/3.9.0/share/cmake/Modules/FindBoost.cmake:1564 (message):
  No header defined for python-py3; skipping header check
Call Stack (most recent call first):
  CMakeLists.txt:133 (find_package)

-- Could NOT find Boost
-- Boost library python-py3: 
CMake Warning at /usr/local/Cellar/cmake/3.9.0/share/cmake/Modules/FindBoost.cmake:1564 (message):
  No header defined for python3; skipping header check
Call Stack (most recent call first):
  CMakeLists.txt:140 (find_package)

-- Could NOT find Boost
-- Boost library python3: 
-- Boost version: 1.64.0
-- Found the following Boost libraries:
--   python
-- Found components for NumPy
-- NUMPY_ROOT_DIR    = /usr/local
-- NUMPY_INCLUDES    = /anaconda/lib/python3.5/site-packages/numpy/core/include
-- NUMPY_LIBRARIES   = /anaconda/lib/python3.5/site-packages/numpy/core/lib/libnpymath.a
-- NUMPY_API_VERSION = 1.12.1
-- Configuring done
CMake Warning (dev):
  Policy CMP0042 is not set: MACOSX_RPATH is enabled by default.  Run "cmake
  --help-policy CMP0042" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  MACOSX_RPATH is not specified for the following targets:

   libvizdoom_shared

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Generating done
-- Build files have been written to: /Users/kyungchankim/doom-py/doom_py
[  0%] Built target freedoom2
[  9%] Built target gme
[ 13%] Built target lzma
[ 14%] Built target lemon
[ 16%] Built target re2c
[ 16%] Built target updaterevision
[ 17%] Built target libvizdoom_static
[ 17%] Linking CXX shared library bin/libvizdoom.dylib
[ 18%] Built target zipdir
[ 18%] Built target gdtoa
[ 34%] Built target dumb
[ 35%] Built target libvizdoom_shared
[ 35%] Linking CXX shared module bin/python/vizdoom.so
Undefined symbols for architecture x86_64:
  "boost::python::detail::init_module(PyModuleDef&, void (*)())", referenced from:
      _PyInit_vizdoom in ViZDoomPythonModule.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [bin/python/vizdoom.so] Error 1
make[1]: *** [CMakeFiles/libvizdoom_python.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 35%] Linking CXX executable ../../../bin/vizdoom.app/Contents/MacOS/vizdoom
[100%] Built target vizdoom
make: *** [all] Error 2

Could not build doom-py: Command '['make', '-j', '3']' returned non-zero exit status 2. (HINT: are you sure cmake is installed? You might also be missing a library. doom_py requires boost, boost-python, sdl2 on OSX (installable via 'brew install boost boost-python sdl2')

Traceback (most recent call last):
  File "setup.py", line 88, in <module>
    include_package_data=True,
  File "/anaconda/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/anaconda/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/anaconda/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 63, in run
    build_func()
  File "setup.py", line 34, in build_osx
    build_common('dylib', cmake_arg_list=['-DOSX_COCOA_BACKEND=OFF'])
  File "setup.py", line 29, in build_common
    subprocess.check_call(['make', '-j', str(cores_to_use)], cwd='doom_py')
  File "/anaconda/lib/python3.5/subprocess.py", line 271, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['make', '-j', '3']' returned non-zero exit status 2

**Comment by christopherhesse** [comment]
We don't have the doom environments anymore, so closing this issue.
