### ISSUE TITLE
Rendering issue in xfce using Ubuntu on Azure with remote desktop

### ISSUE THREAD

**Issue by fuzzballb** [openai/gym#682]
I am trying to run the Atari simulator on an Ubuntu cloud instance using xfce (https://xfce.org) and remote desktop. The instances do start, but the game windows remain black. 

I am using this repo, which runs fine on my Macbook 
https://github.com/tflearn/tflearn/blob/master/examples/reinforcement_learning/atari_1step_qlearning.py

The warning in the screenshot is also shown in OSx and does not cause this issue. 

![screen shot 2017-08-10 at 11 22 32](https://user-images.githubusercontent.com/3391337/29165235-60737cd6-7dc2-11e7-9826-9d45b74118bc.png)

> ^CTraceback (most recent call last):
>   File "qlearning.py", line 465, in <module>
>     tf.app.run()
>   File "/home/abloemenkamp/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
>     _sys.exit(main(_sys.argv[:1] + flags_passthrough))
>   File "qlearning.py", line 462, in main
>     train(session, graph_ops, num_actions, saver)
>   File "qlearning.py", line 411, in train
>     env.render()
>   File "/home/abloemenkamp/anaconda3/lib/python3.6/site-packages/gym/core.py", line 150, in render
>     return self._render(mode=mode, close=close)
>   File "/home/abloemenkamp/anaconda3/lib/python3.6/site-packages/gym/core.py", line 286, in _render
>     return self.env.render(mode, close)
>   File "/home/abloemenkamp/anaconda3/lib/python3.6/site-packages/gym/core.py", line 150, in render
>     return self._render(mode=mode, close=close)
>   File "/home/abloemenkamp/anaconda3/lib/python3.6/site-packages/gym/envs/atari/atari_env.py", line 120, in _render
>     self.viewer.imshow(img)
>   File "/home/abloemenkamp/anaconda3/lib/python3.6/site-packages/gym/envs/classic_control/rendering.py", line 325, in imshow
>     image.blit(0,0)
>   File "/home/abloemenkamp/anaconda3/lib/python3.6/site-packages/pyglet/image/__init__.py", line 892, in blit
>     self.get_texture().blit(x, y, z, width, height)
>   File "/home/abloemenkamp/anaconda3/lib/python3.6/site-packages/pyglet/image/__init__.py", line 818, in get_texture
>     force_rectangle)
>   File "/home/abloemenkamp/anaconda3/lib/python3.6/site-packages/pyglet/image/__init__.py", line 809, in create_texture
>     self.anchor_x, self.anchor_y, 0, None)
>   File "/home/abloemenkamp/anaconda3/lib/python3.6/site-packages/pyglet/image/__init__.py", line 953, in blit_to_texture
>     data = self._convert(data_format, data_pitch)
>   File "/home/abloemenkamp/anaconda3/lib/python3.6/site-packages/pyglet/image/__init__.py", line 1066, in _convert
>     rows = re.findall(asbytes('.') * abs(pitch), data, re.DOTALL)
>   File "/home/abloemenkamp/anaconda3/lib/python3.6/re.py", line 222, in findall
> Exception in thread Thread-7:
> Traceback (most recent call last):
>   File "/home/abloemenkamp/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1139, in _do_call
>     return fn(*args)
>   File "/home/abloemenkamp/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1121, in _run_fn
>     status, run_metadata)
>   File "/home/abloemenkamp/anaconda3/lib/python3.6/contextlib.py", line 89, in __exit__
>     next(self.gen)
>   File "/home/abloemenkamp/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
>     pywrap_tensorflow.TF_GetCode(status))
> tensorflow.python.framework.errors_impl.CancelledError: Run call was cancelled

**Comment by tktkm** [comment]
me too...

**Comment by christopherhesse** [comment]
The atari envs do not care about the windowing system, but using the preview window requires that the windowing system work correctly.  In your case, it's likely that your remote desktop does not support OpenGL.  You could verify this by running `glxgears` and if you can see the gears, then OpenGL support is working.

Assuming that it is not working, you would need to setup VirtualGL or something similar: https://wiki.archlinux.org/index.php/VirtualGL.

Another option is to write the output from `.render('rgb_array')` into a movie and then view that movie locally rather than using remote desktop.

Supporting linux remote desktop config is outside of the scope of gym though, so I will close this issue.
