### ISSUE TITLE
env.render() crashes python

### ISSUE THREAD

**Issue by act65** [openai/gym#69]
Hey,

I am just trying out the most basic tutorial, cart-pole-v0. When I render the video it plays and then crashes afterward (every time). Everything else seems to work fine, ie without rendering.  Dont know if this is a problem on my end or not, I am using anaconda with python 3.5.

**Comment by gdb** [comment]
Uh oh! Do you have an error message you can paste?

**Comment by act65** [comment]
Nah, it doesnt give any errors. Just crashes. 2 secs let me do some more tests

**Comment by act65** [comment]
Oh, the problem is pyglet. It crashes for just some simple examples. 

E.g. this crashes
```python
 import pyglet

window = pyglet.window.Window()
image = pyglet.resource.image('./test.png')

@window.event
def on_draw():
    window.clear()
    image.blit(0, 0)

pyglet.app.run()
```
Dont know what I have done wrong, but doesnt seems to be an issue with gym itself?

**Comment by jonasschneider** [comment]
I've also seen these silent crashes before, I think. Seems like an
OpenGL bindings issue that only appears on Python 3 (started to appear
while I was doing the upgrade). It does feel like this is something we
should care about. Are you running OS X? Does your example crash every
time on your machine?

- Jonas

**Comment by act65** [comment]
Yea, OSX. Yep, everytime.
