### ISSUE TITLE
'bipedalwalker' environments references & benchmarks

### ISSUE THREAD

**Issue by 4d55397500** [openai/gym#691]
Hi,
 I've been looking over the bipedal walker environments, especially 'BipedalWalkerHardcore-v2', and they are fascinating.  I'm not up to date with benchmarks in the reinforcement learning community, but are the bipedal walker environments here in OpenAI in fact the standard such benchmarks, if any exist, or do none exist?

I ask because the parameter space for specifying these environments is enormous, compared to the elementary cartpole environment, and hence what justifies  'BipedalWalkerHardcore-v2' as being the benchmark for a class of learning tasks? What are the properties of the set of environments `{env_i}` such that having solved them represents a definite general advance in learning?

To make an analogy, the space of possible Lagrangians is also infinite, and rather than solve any one in isolation general methods are devised: symmetry groups, feynman diagrams, symplectic structure, hence the Lagrangians can be classified and compared.

It would be nice to have something similar for the environments here on OpenAI; at least in the documentation a verbal description of the class of task addressed so there is explicit consensus as to what more general problem is being solved.

Apologies in advance if this is better not filed as an issue-
Thanks

**Comment by olegklimov** [comment]
...er so what do you want then? A lot of text, can you repeat what you want to be fixed?

**Comment by 4d55397500** [comment]
How about a 1 sentence summary stating why the environment is 'official' or
at least important? For the cartpole I can read papers and books; others
less likely. Example-Does solving mountain car in 2d with a cosine function
hill generalize to a class of hills in 3d?
For bipedal hardcover Walker v2 i wouldn't know where to start other than
it looks hard and there are papers about the bipedal walker.
I'd be happy to help:)

**Comment by olegklimov** [comment]
BipedalWalker is not important, it's fun.

So that's a philosophical question. You have your own way. If you find some of this work useful, that's great.

All there is to it.
