### ISSUE TITLE
0 episode rewards and sorting

### ISSUE THREAD

**Issue by 4d55397500** [openai/gym#693]
Many environments have solutions that meet the reward criterion with 0 episodes passed. Are these legitimate? 

Additionally, is it possible to sort the solutions listed for a given environment by average reward? I can't tell what the current solution ordering is.

**Comment by olegklimov** [comment]
We do you see a list of solutions? On https://gym.openai.com/ ? That is just a site that you can upload results to.

No serious team is uploading their results there, AFAIK. Including us, because we learning unreleased environments and other things.

**Comment by olegklimov** [comment]
Ah, that's just means "not solved"
