### ISSUE TITLE
env.step - Montezuma's revenge

### ISSUE THREAD

**Issue by richielo** [openai/gym#694]
Hi,

I apologize in advance if this is a stupid action. But I can't seem to find a solid answer about this. When will done be true in this environment? When the agent lost all lives or when he dies? It seems that it's the former case from my testing.
I want to see if it's possible to configure it to the latter case which done is true whenever the agent dies.

Thanks a lot for your help!

**Comment by olegklimov** [comment]
Hi. You need to write a wrapper for this. Ask for ale->lives(). If that's lower, send yourself a done.
