### ISSUE TITLE
Montezuma's revenge - suggestion on increasing speed

### ISSUE THREAD

**Issue by richielo** [openai/gym#699]
Hi All,

Not sure if this is the right place to ask such question. I am trying to train an agent to play Montezuma's revenge making use of hierarchical reinforcement learning. However, the process is extremely slow, even for one episode, as I am only running it on a built-in gpu of my laptop. Any general suggestions on speeding things up so I can see the results quicker? Like any cloud platform that would be compatible with work like this? I am really new to the area so I am not familiar with the common practices. 

Thanks a lot in advance!

**Comment by babak-badnava** [comment]
Hi,
I think you could use amazon aws. amazon have made some of their platforms free for students.
https://aws.amazon.com/education/awseducate/

**Comment by christopherhesse** [comment]
AWS, GCP, and Azure are popular places to rent GPUs from.
