### ISSUE TITLE
Legal action set

### ISSUE THREAD

**Issue by babak-badnava** [openai/gym#700]
Hi all,
I suggest that you add something that user can choices between legal action set or minimal action set in atary games.
sometimes ago I need something like this but couldn't find such functionality so I did explore the code and changed atary_env.py file to use legal action set instead of minimal action set.

I though this will be useful if gym has this functionality by default.

thanks in advance

**Comment by christopherhesse** [comment]
You can do this by setting `full_action_space=True` when using `AtariEnv`: https://github.com/openai/gym/blob/master/gym/envs/atari/atari_env.py#L32
