### ISSUE TITLE
Benchmarking env for model for multiple games

### ISSUE THREAD

**Issue by dgriff777** [openai/gym#701]
Do you have environments for or plans to benchmarking models that are trained to play multiple games at same time?

For example I have trained models that can play 3-4 Atari games at super human level and don't need to be retrained to play another game and/or don't require loading a different trained model when switching to evaluating different games. One loaded model plays all 4 games

**Comment by christopherhesse** [comment]
Joint training on atari games is interesting, but I don't think this is within the current scope of gym.   Thanks for the feedback though!
