### ISSUE TITLE
CartPole-V0 Done Angle Doc vs. Code

### ISSUE THREAD

**Issue by benbotto** [openai/gym#702]
I'm just getting started with Gym, and something I found a discrepancy between the documentation and code that tripped me up a bit.

- In the documentation for CartPole-V0 (https://gym.openai.com/envs/CartPole-v0) it says that the episode ends when the pole is more than 15 degrees from vertical.
- In the code the angle is actually 12 degrees (https://github.com/openai/gym/blob/master/gym/envs/classic_control/cartpole.py#L33).

Maybe the documentation can be changed to 12 degrees?

**Comment by thedch** [comment]
Just ran into this myself — the [wiki](https://github.com/openai/gym/wiki/CartPole-v0) states Episode Termination at +/- 20.9 degrees, which seems to be inaccurate.

**Comment by FirefoxMetzger** [comment]
The website is no longer supported and is only a static export. I don't think it will be fixed there.

The wiki is the goto reference and @thedch has already fixed it there =).
