### ISSUE TITLE
CartPole reward function inconsistent with Barto et al.

### ISSUE THREAD

**Issue by moshelooks** [openai/gym#704]
In both the [paper](http://incompleteideas.net/sutton/papers/barto-sutton-anderson-83.pdf.gz) and [original source code ](http://incompleteideas.net/sutton/book/code/pole.c) the reward function for CartPole is `r = -1` when the pole falls over and `r = 0` otherwise. In the gym implementation the reward is the same (`r = 1`), whether the pole [falls over](https://github.com/openai/gym/blob/master/gym/envs/classic_control/cartpole.py#L82) or [not](https://github.com/openai/gym/blob/master/gym/envs/classic_control/cartpole.py#L78).

**Comment by olegklimov** [comment]
I think it's not even worth version change. Task is so, so easy. Everything works, any reward works.
