### ISSUE TITLE
Env.step() with no action

### ISSUE THREAD

**Issue by keleftheriou** [openai/gym#71]
Intuitively, an algorithm should at any point also have the choice of *not* acting at all.

At least in the example of control/physics environments, being able to not act might sometimes be the "best" choice. Defining "best" here can be a long discussion, but as an example an algorithm might be optimizing for *efficiency* (reward/effort), rather than absolute reward.

**Comment by jonasschneider** [comment]
This seems like it's mostly a semantic issue with env action spaces. In some envs, "not acting" is meaningless -- take board games like Chess or Go (the latter we have as an env already) for example: if it's your turn, you can't meaningfully choose to "not act".

Also, _efficiency/effort_ are ill-defined concepts whose semantics depend on the env. In fact, what you propose is already implemented in some envs. For example, the mujoco envs penalize you (i.e. reduce reward) based on the joint torques that you specify, i.e. what could intuitively be described as the "effort".

So it seems like this is a per-env semantic issue. We're happy about proposals for definitions of efficiency for specific envs, though!

**Comment by tlbtlbtlb** [comment]
In (I think) all the physics environments the actions are converted to torques, so a vector of 0s is a reasonable least-effort action. That might not be obvious from the `action_space`, which usually is a `Box` with `low=[-1, ...]` and `high=[+1, ...]`.

**Comment by keleftheriou** [comment]
I've only been playing with the 'CartPole-v0' environment so far, and that has an `action_space` of `spaces.Discrete(2)` which led me to my comment.

I wonder if making `Env.step()` have `action=None` as a default could work, letting the environment  complain if it can't accept it. The API would be more general this way, and the potential for API misuse by either environment users or environment authors seems low.

 Alternatively, 'CartPole-v0' could just be changed to take a `Box` `action_space` instead of a `Discrete` one, although it feels like this particular environment might have been purposefully made to not take variable force values.

Good to know about the mujoco environments utilizing a notion of "effort" through the `reward` returned, thanks.

**Comment by gdb** [comment]
The feedback makes sense; thanks for the input!

This isn't part of the standard formulation of RL, so I think for now we shouldn't add it (and I'm not sure if it'd make sense for every env). I'm going to close for now, but if we see more demand for something like this, we'll revisit!

**Comment by ivanvoid** [comment]
So you wanna say this issue was never resolved? 
Yea 4 years later, please add option to stay still in 'CartPole-v1', 
or just help to figure out how to make it possible, this also will be really appreciated.

**Comment by soroush-bn** [comment]
@gdb I came across the same problem when I want to add additional actions for "Taxi" environment, I want to add diagonal movements to the grid world, however, it is not possible to perform such action when agent is on the edge of the grid, thus, whether I need to create my custom env or use a "NOOP" action and pass it to env.step() function to see the observation and etc.

**Comment by meghbhalerao** [comment]
https://github.com/openai/gym/issues/71#issuecomment-217780087 - why would this not be a part of the standard formualation of RL?
We can have an MDP with an action = None, which would essentially have the following transition probablity distribution - 
T(s'|s,a = None) = 1 if s'= s, else = 0.
I think it would be useful to have this, say, if one simply wants to get the current env state. Or am I missing something here?

**Comment by leafstar** [comment]
> [#71 (comment)](https://github.com/openai/gym/issues/71#issuecomment-217780087) - why would this not be a part of the standard formualation of RL? We can have an MDP with an action = None, which would essentially have the following transition probablity distribution - T(s'|s,a = None) = 1 if s'= s, else = 0. I think it would be useful to have this, say, if one simply wants to get the current env state. Or am I missing something here?

I don't think so. In cartpole environment, intuitively, if you do nothing when the pole is not vertical to the cart, finally it will fall. Therefore the state will also be changed even if you do nothing.
