### ISSUE TITLE
How to get an observation upon restore?

### ISSUE THREAD

**Issue by evanthebouncy** [openai/gym#715]
I can clone a state in the atari environment with:

    state = env.clone_full_state()

Later on I can restore it with

    env.restore_full_state(state)

However how do I get an observation of the environment now? The only way to produce an observation is through env.reset() which would erase the current restored state, or by env.step(..) which would give an observation of the next state after an action is already performed.

Am I missing something obvious?

**Comment by dqii** [comment]
Were you able to figure this out?

**Comment by SuhitK** [comment]
`state = env.env.state`
should do the trick. The thing is when we create env using `gym.make(environment-name)`, env is actually a wrapper around the actual environment which is an attribute called env in this wrapper.

**Comment by christopherhesse** [comment]
If @SuhitK's solution does not work you should be able to create a wrapper with a method `get_state()` that returns `(last_obs, state)` and `set_state()` that takes that tuple, then access `last_obs` when you want.

**Comment by daidew** [comment]
As of 2020: for Atari environments, you need to use env.env.ale.getScreenRGB() instead to access the state.
