### ISSUE TITLE
Gym Docs Page Is Down

### ISSUE THREAD

**Issue by donamin** [openai/gym#718]
Hi
https://gym.openai.com/docs
This address is not working.

**Comment by TheShoutingParrot** [comment]
Me too. I just get redirected me he3e

**Comment by Dudder** [comment]
Same here.

**Comment by israelzuniga** [comment]
Both leaderboard and docs sites are down. Seems that now as OpenAI is fully focusing on the library:

[https://twitter.com/gdb/with_replies](https://twitter.com/gdb/with_replies)

**Comment by gdb** [comment]
Yep, that's accurate — we'll do a static export of the site soon, but we really haven't maintained it at all, and the library is the focus of the project!

**Comment by patrafter1999** [comment]
gym/universe is a truly great framework to experiment RL. Since the doc site is gone now, there is no way to read through all source codes when you try to find out about an environment such as available actions, game descriptions, etc. Although the site may not be perfect, it will be greatly appreciated if you can get the site back up as soon as possible. Great work!!

**Comment by korroktheslavemaster** [comment]
https://scoreboard-site-1764008611.us-west-2.elb.amazonaws.com/
They just changed dns [https://twitter.com/gdb/status/908101501058400256](url)

**Comment by superxingzheng** [comment]
The site is helpful when people want to look for best implementations or algorithms.

**Comment by icoxfog417** [comment]
The leaderboard site is not only useful to share the training result, but also a good first challenge for the beginners to tackle with reinforcement learning.

I held the hands-on event for novices and its goal is to upload the agent to OpenAI Gym site. Many participants had a fun to do it. I understand it is not the main work of OpenAI, but it was so great feature. So I hope it'll keep on somewhere.

![image](https://user-images.githubusercontent.com/544269/30461580-5f01b9cc-99fa-11e7-9b5b-bc445b5054a1.png)

(Sorry for only Japanese)
https://github.com/icoxfog417/techcircle_openai_handson

**Comment by gdb** [comment]
I have an update!

- Read-only export of the old site here: https://gym.openai.com/read-only.html. All the old links should work, and https://gym.openai.com will redirect to the Github repo. (Might still be some caching weirdness for the next hour or so.)
- @hardmaru is going try out setting up the wiki to allow people to submit scores (https://twitter.com/hardmaru/status/908121667854942209). This will be a community-maintained way of submitting scores, and hopefully will be better curated than the Gym site was!

I'm super appreciative that this thread exists — honestly we weren't sure whether there was enough demand to even make the read-only export worthwhile. Thanks everyone, and look forward to seeing how @hardmaru's setup works!

**Comment by patrafter1999** [comment]
Thanks a million, gdb!!!!!!!!!!

**Comment by patrafter1999** [comment]
The main links in https://gym.openai.com/read-only.html still lead us to
github site. However, https://scoreboard-site-1764008611.us-west-2.elb.
amazonaws.com/ works. I'm just happy with it.

**Comment by benelot** [comment]
@hardmaru: If you need any help, just call me in!

**Comment by ceobillionaire** [comment]
The Static export ( https://gym.openai.com/read-only.html  ) doesn't displays the env. videos and the learning performance curves are missing.

**Comment by gdb** [comment]
I've checked internally. Sadly, there was a miscommunication about what was included in the static export during the shutdown of the old Gym infra. The production S3 bucket containing the videos and learning curves was deleted. This means that we no longer have copies of the videos and learning curves. Sorry for this — was definitely not our intention. On the plus side, all of that data was uploaded directly from clients, so people still may have the primary copy of what was lost.

The rest of the export is intact and isn't going anywhere.

**Comment by jner14** [comment]
@gdb If it were me I would just take down the site completely.  As it is now it just reflects poorly on the OpenAI project which I'm personally a fan of.  It's very frustrating to not be able to access the site in its entirety.

**Comment by benelot** [comment]
It is common practice for migration to put up a site in read-only mode. It
is not meant to be used any further except for taking the information and
reusing it somewhere else. I think a more community driven approach could
bebetter anyway.

**Comment by dyelax** [comment]
Super disappointed about this. The ability to easily compare RL results on standardized environments was OpenAI's biggest contribution to the AI community IMO. Sad to see we are regressing in terms of transparency

**Comment by jner14** [comment]
@dyelax , I agree.  It feels like they just used the community to get a jump start by taking the best algorithms or finding the best talent and now they don't need the rest of us anymore.

**Comment by gdb** [comment]
As I said above, the Gym website never had a big impact, and so we never maintained it. The Gym library, on the other hand, has been very successful. As this thread is no longer about technical reports, I'm going to close it. Feel free to shoot me an email (gdb@openai.com) if you'd like to discuss anything directly.
