### ISSUE TITLE
Bugs in Taxi-v1 environment

### ISSUE THREAD

**Issue by arboo** [openai/gym#72]
I think the strings for the last action of _North_ and _South_ are switched. Also sometimes there seems to be a passenger to pick up, but no destination.

Are there any plans to extend the environment in a probabilistic manner? Like in the original paper when choosing an action there is a 20 % chance to end up somewhere else.

**Comment by joschu** [comment]
Thanks, should be fixed now. The problem was that sometimes the start location was the same as the destination.
I didn't notice in the paper that the transitions were random, but that's good to know.
