### ISSUE TITLE
how to get a API KEY now?

### ISSUE THREAD

**Issue by zhan0903** [openai/gym#720]
It seems I can not apply an API key for uploading now.

**Comment by gdb** [comment]
See https://github.com/openai/gym/issues/718#issuecomment-329661594!

**Comment by MartinThoma** [comment]
I can't find the information about the API key. Could you paste the relevant part here?

**Comment by jcq15** [comment]
I can't find the information about the API key, either. Could you please paste them here? Thanks!

**Comment by icoxfog417** [comment]
The upload feature of OpenAI Gym is finished. So you can't get API key anymore and you can't upload your experiment even if you have the key.
