### ISSUE TITLE
AttributeError: module 'gym' has no attribute 'make'

### ISSUE THREAD

**Issue by lucky-geqian** [openai/gym#723]
First of all,i have installed gym[atari] during windows and i got this:
(tensorflow) C:\ProgramData\Anaconda3\envs\tensorflow>pip install gym[atari]
Requirement already satisfied: gym[atari] in c:\programdata\anaconda3\envs\tensorflow\lib\site-packages
Requirement already satisfied: requests>=2.0 in c:\programdata\anaconda3\envs\tensorflow\lib\site-packages (from gym[atari])
Requirement already satisfied: six in c:\programdata\anaconda3\envs\tensorflow\lib\site-packages (from gym[atari])
Requirement already satisfied: pyglet>=1.2.0 in c:\programdata\anaconda3\envs\tensorflow\lib\site-packages (from gym[atari])
Requirement already satisfied: numpy>=1.10.4 in c:\programdata\anaconda3\envs\tensorflow\lib\site-packages (from gym[atari])
Requirement already satisfied: atari-py>=0.1.1; extra == "atari" in c:\programdata\anaconda3\envs\tensorflow\lib\site-packages\atari_py-0.1.1-py3.5.egg (from gym[atari])
Requirement already satisfied: Pillow; extra == "atari" in c:\programdata\anaconda3\envs\tensorflow\lib\site-packages (from gym[atari])
Requirement already satisfied: PyOpenGL; extra == "atari" in c:\programdata\anaconda3\envs\tensorflow\lib\site-packages (from gym[atari])
Requirement already satisfied: idna<2.7,>=2.5 in c:\programdata\anaconda3\envs\tensorflow\lib\site-packages (from requests>=2.0->gym[atari])
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\envs\tensorflow\lib\site-packages (from requests>=2.0->gym[atari])
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\programdata\anaconda3\envs\tensorflow\lib\site-packages (from requests>=2.0->gym[atari])
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\programdata\anaconda3\envs\tensorflow\lib\site-packages (from requests>=2.0->gym[atari])
Requirement already satisfied: olefile in c:\programdata\anaconda3\envs\tensorflow\lib\site-packages (from Pillow; extra == "atari"->gym[atari])
Is that meaning i install the gym[atari] successfully?
So i test it in anacoda and i got this:
>>> import gym
>>> env = gym.make('SpaceInvaders-v0')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'gym' has no attribute 'make'
How can i solve this problem? Thanks a lot.

**Comment by FirefoxMetzger** [comment]
You install gym into the virtual environment called tensorflow in your first line. If I read that correct for python3 / anaconda3.

I can't tell how you are running the script, but did you double check that you are using the same virtual environment as well as the same python version?
To me it sounds like one of these is off, but I can't be certain with the information given.

**Comment by lucky-geqian** [comment]
The main point is that when I install gym[atari] in my virtual environment ,there is not report error.
So I think I have installed it successfully  . And I test it ,but it comes the error like this "AttributeError: module 'gym' has no attribute 'make' ".
I don't know what to do next?

**Comment by christopherhesse** [comment]
You are likely installing gym with a different python, please make sure the pip you used to install corresponds to the python executable you are using to run your code.  I think you can also use `python -m pip` instead of `pip` to be more certain.

**Comment by BlkPingu** [comment]
### In:

`pip3 install gym-retro`

```python
#retro.py

import retro
env = retro.make(game='Airstriker-Genesis')
```


### Out

> ▶ python3 retro.py
Traceback (most recent call last):
  File "retro.py", line 1, in <module>
    import retro
  File "/Users/Tobias/Desktop/NN/retro.py", line 2, in <module>
    env = retro.make(game='Airstriker-Genesis')
AttributeError: module 'retro' has no attribute 'make'
