### ISSUE TITLE
Unable to upload evaluation onto gym

### ISSUE THREAD

**Issue by chewterence** [openai/gym#724]
Hi guys i am unable to upload my evaluation onto the gym.
i am also unable to login on the gym website with my github account.
is anyone experiencing the same error??

404 Not Found
    Code: NoSuchKey
    Message: The specified key does not exist.
    Key: evaluations/eval_oR6WM07gRJqc7YSmqoLrow
    RequestId: 66BD4ACD64B68FB2
    HostId: WCZhHVRWWW0KSPQCl/9nYMY2Z1zopd4PelFWHelFSmXbX2fsJuqy6SgbBzoGBB9Mu96mcFJ9er4=
An Error Occurred While Attempting to Retrieve a Custom Error Document
    Code: NoSuchKey
    Message: The specified key does not exist.
    Key: fake.html

**Comment by christopherhesse** [comment]
Thanks for the feedback but the scoreboard isn't active anymore, so I am closing this issue.
