### ISSUE TITLE
Instructions on developping new game environment

### ISSUE THREAD

**Issue by zhoubinxyz** [openai/gym#73]
May I ask if you can provide a general instructions on developing new game environment?

I want to train an agent for a racing game, but the games provided by default does not contain the game I want. Therefore I am considering to develop a new game environment for it. A general instructions from you on this will help a lot for me.

Best,
Bin

**Comment by JKCooper2** [comment]
It's probably easiest looking at other people's new environment submissions, e.g: https://github.com/openai/gym/pull/61/files
There's comments inside the core.py file that can also help know what you need to implement: https://github.com/openai/gym/blob/master/gym/core.py

**Comment by gdb** [comment]
Closing for now, but please jump into chat (https://gitter.im/openai/gym) if you need help with anything!
