### ISSUE TITLE
import gym does not work on Jupyter notebook

### ISSUE THREAD

**Issue by soma11soma11** [openai/gym#731]
I installed gym on my Python3 following the instruction.
It works with Python3, but it is not working on Jupyter notebook with Python3.

**Comment by soma11soma11** [comment]
It worked after I deleted and installed them again!

**Comment by ZhengPeng7** [comment]
Maybe it's caused by that the default kernel of jupyter-notebook wasn't the right one.

You can use these two lines of codes to set the python of kernel:

```shell
/home/a/.virtualenvs/tf_env/bin/python -m pip install ipykernel 

/home/a/.virtualenvs/tf_env/bin/python -m ipykernel install --user
```
Hope this can help you.

**Comment by plopd** [comment]
```
source activate <myenv>
conda install pip
pip install gym
conda install ipykernel
python -m ipykernel install --user --name <myenv> --display-name "Python <myenv>"
```
Restart jupyter notebook `jupyter-notebook`

Change kernel to `Python <myenv>` by selecting it from the tab `Kernels`.
Resources: https://ipython.readthedocs.io/en/latest/install/kernel_install.html

**Comment by christopherhesse** [comment]
Sounds like the original poster got this to work.

**Comment by Hosseinghr** [comment]
> Maybe it's caused by that the default kernel of jupyter-notebook wasn't the right one.
> 
> You can use these two lines of codes to set the python of kernel:
> 
> ```shell
> /home/a/.virtualenvs/tf_env/bin/python -m pip install ipykernel 
> 
> /home/a/.virtualenvs/tf_env/bin/python -m ipykernel install --user
> ```
> 
> Hope this can help you.
this works. thanks a lot

**Comment by sssrnty** [comment]
> ```
> source activate <myenv>
> conda install pip
> pip install gym
> conda install ipykernel
> python -m ipykernel install --user --name <myenv> --display-name "Python <myenv>"
> ```
> 
> Restart jupyter notebook `jupyter-notebook`
> 
> Change kernel to `Python <myenv>` by selecting it from the tab `Kernels`.
> Resources: https://ipython.readthedocs.io/en/latest/install/kernel_install.html

this worked for me thanks!

**Comment by NumeloUno** [comment]
Install jupyter in the environment gym is installed
