### ISSUE TITLE
Add tile coding algorithms from Sutton

### ISSUE THREAD

**Issue by hughchristensen** [openai/gym#732]
@joschu @gdb On page 204+ (chapter 8) of Sutton (Reinforcement Learning, 2nd edition) Sutton presents tile coding.@ I do not believe these tile algorithms are already included in this repo and I think the library would benefit from them. 

Sutton makes code for this available (in Python 3.x, as well as Python 2.x) here: 

* https://webdocs.cs.ualberta.ca/~sutton/tiles/tiles3.html 
* http://incompleteideas.net/rlai.cs.ualberta.ca/RLAI/RLtoolkit/tilecoding.html 

Alternatively the RLToolkit Version 1.0: (which is Python 2.x) is available here, which includes tiles as well as a additional algorithms 

* http://incompleteideas.net/rlai.cs.ualberta.ca/RLAI/RLtoolkit/RLtoolkit1.0.html#downloads

**Comment by christopherhesse** [comment]
The gym library doesn't really handle specific algorithms.  This would be more appropriate in a separate library I think.  Thanks for the suggestion!
