### ISSUE TITLE
Error with openAI session page

### ISSUE THREAD

**Issue by soma11soma11** [openai/gym#734]
I cannot login to https://gym.openai.com/session.

It says
`This distribution is not configured to allow the HTTP request method that was used for this request. The distribution supports only cachable requests. `

I thought it was a temporal issue but it seems like it has been 2 days. Any idea?

**Comment by agakshat** [comment]
+1 same issue

**Comment by apoorvkul** [comment]
I am also facing same issue

**Comment by agakshat** [comment]
Just FYI, OpenAI has stopped maintaining the scoreboard on its own website, and the Github repo is now the primary location for Gym.

**Comment by christopherhesse** [comment]
Thanks for answering this @agakshat!
