### ISSUE TITLE
Training time of openai gym is too long, what is the good way to accelerate it?

### ISSUE THREAD

**Issue by jinpengchina** [openai/gym#736]
I did some gym training what need a long time for training.

my notebook is a new macbook 12,

Such as training mario game,

what is your hardware , and how long?

what is the good way to accelerate it?

**Comment by olegklimov** [comment]
Mario is on the order 100M frames to train. You need bigger machine you can buy or find in a cloud.

**Comment by jinpengchina** [comment]
what is your hardware , and how long?

**Comment by olegklimov** [comment]
Hardware is standard everywhere, more or less... You should be asking what is my software, that's what makes a difference. Currently unreleased software, pretty good one. Typical game requires one GPU, 10 hours, 100M frames.

**Comment by jinpengchina** [comment]
olegklimov-------thanks

**Comment by jinpengchina** [comment]
olegklimov----------- how to run openai gym on cloud for train ?

run openai gym on  linux desktop environment  ?
