### ISSUE TITLE
Cannot sign in with GitHub on the website

### ISSUE THREAD

**Issue by wendingp** [openai/gym#738]
I have signed in the GitHub on my browser (tried both Chrome and Safari on mac). But when I "sign in with GitHub" on the [gym website](https://gym.openai.com/envs/), I need to "sign in to GitHub to continue to OpenAI Gym". Alright then I tried signing in but I got 
"Error, The request could not be satisfied.

This distribution is not configured to allow the HTTP request method that was used for this request. The distribution supports only cachable requests. "

![image](https://user-images.githubusercontent.com/17057603/31072334-0de5fa72-a72d-11e7-8e2a-fc71d7074975.png)

Why?

**Comment by benelot** [comment]
The openai gym website is only available in a read only mode for
transition. It is not meant to be used anymore due to high maintenance
costs. It is meant to be replaced by the wiki on the github repository.

**Comment by wendingp** [comment]
Oh, then can we still download/upload algorithms?

**Comment by benelot** [comment]
I do not think so, but I do not know a lot about the gym website, I just
read that the other info a lot on the issues here.

**Comment by wendingp** [comment]
OK, thx.

**Comment by BIGBALLON** [comment]
I have the same issue too.
I can't sign in with GitHub.

**Comment by cyborgnoah** [comment]
Will the website be available to upload our developed algorithms in near future.

**Comment by discordianfish** [comment]
Oh.. are there alternatives? Maybe even a bit further gamified? :)

**Comment by JackieTseng** [comment]
I also noticed the broken image problem and couldn't login using Github.

**Comment by christopherhesse** [comment]
We've replaced the site with a static site.  For those looking for more RL competitions, there are occasional things such as the Obstacle Tower Challenge, https://create.unity3d.com/obstacletower which offer a leaderboard.  As for a long-term community leaderboard for different benchmarks I haven't seen anything yet but let me know if anyone knows of something (or add it to the wiki)
