### ISSUE TITLE
RepeatCopy description does not fit task

### ISSUE THREAD

**Issue by dommueller** [openai/gym#74]
The description of [RepeatCopy](https://gym.openai.com/envs/RepeatCopy-v0) and the task don't match.
> A generic input is [mx<sub>1</sub>x<sub>2</sub>...x<sub>k</sub>] and the desired output is [x<sub>1</sub>x<sub>2</sub> ...x<sub>k</sub>x<sub>1</sub>x<sub>2</sub>...x<sub>k</sub>x<sub>1</sub>x<sub>2</sub>...x<sub>k</sub>], where the number of copies is given by m. Thus the goal is to copy the input m times, where m can be only 2 or 3.

However, m is always 3 and it is never displayed as an observation. Furthermore, the expected output is not just a copy, but the the second copy is reversed, as in [x<sub>1</sub>x<sub>2</sub>...x<sub>k</sub><b>x<sub>k</sub>...x<sub>2</sub>x<sub>1</sub></b>x<sub>1</sub>x<sub>2</sub>...x<sub>k</sub>].

**Comment by gdb** [comment]
@wojzaremba mind taking a look?

**Comment by wojzaremba** [comment]
Fixed.
