### ISSUE TITLE
gym.space space dimensionality description

### ISSUE THREAD

**Issue by manuel-delverme** [openai/gym#742]
as of now we need to follow different procedures to understand environments space dimensionality
e.g.:
`
DQNAgent(env.observation_space.shape[0],  env.action_space.shape)
`

in the above example action_space is a gym.space.MultiDiscrete type, while observation_space is of type gym.space.Box .
would it be desiderable to have a common procedure for all the space classes?
(i.e. turn MultiDiscrete.shape from an int to a list or np.array)

**Comment by FirefoxMetzger** [comment]
I generally agree, as this is bugging me, too. However, I am not sure how one would unify across all spaces that gym offers. You only have partial common ground on some spaces, e.g. all discrete spaces are homeomorphic. 

On the other hand, I usually end up writing a single agent script against one environment. Moving to another environment usually means changing more than just a few lines to account for different spaces. So in the bigger picture I don't know if it's an optimization that pays off relative to the maturity of the library.
