### ISSUE TITLE
[Question] Typo error in gym/core.py?

### ISSUE THREAD

**Issue by roya0045** [openai/gym#744]
Greetings,

I'm trying to set up an environment from scratch and I noticed a potential error in the docstring of the step method of Env. Shouldn't the action argument come from the agent and not the environment( as stated in the docstring)? Or maybe I just understood something wrong.

Cheers

**Comment by FirefoxMetzger** [comment]
A bit of both. You are right in that the argument comes from the agent. However, it has to be an element of  within the action space (which is an instance of a gym/spaces class). The space itself is owned by the environment. As I understand it, this is what the docstring refers to.

So in short, yes the action is chosen by the agent, no the comment is correct. Though I do see where the confusion is coming from and it should probably be adjusted.

**Comment by roya0045** [comment]
Yes the possibility space is within the Environment but it's not the environment itself picking which precise action to do. 

In that sense something along the lines of : 
" Action provided by the agent ( within the defined action_space)" 

Or something similar would be more helpful than insinuating that it is the environment itself that is choosing which action to perform.
