### ISSUE TITLE
Page link missing in Wiki

### ISSUE THREAD

**Issue by JIElite** [openai/gym#747]
In the [MountainCar-v0](https://github.com/openai/gym/wiki/MountainCar-v0) section of 
Wiki, Algorithms Page is missing.

<img width="492" alt="2017-10-13 18 45 46" src="https://user-images.githubusercontent.com/6872274/31543001-e273c8f0-afd9-11e7-8705-a1427bfc163c.png">

**Comment by christopherhesse** [comment]
I removed the link, thanks!
