### ISSUE TITLE
Pass arguments to Environments upon init

### ISSUE THREAD

**Issue by DavidS3141** [openai/gym#748]
If I understand correctly the code for the board_game Hex it should be possible to pass an opponent player policy via the __init__ function. However using the gym environment interface there is no way to actually pass this argument to the Hex engine and the argument gets read from the register() entry in gym/envs/__init__.py.

Am I missing something here? Is there a neat way to pass arguments to the engines in general?

**Comment by w121211** [comment]
Met the same problem and here is what I've found: [gym wiki](https://github.com/openai/gym/wiki/FAQ)
```
gym.envs.register(
    id='MountainCarMyEasyVersion-v0',
    entry_point='gym.envs.classic_control:MountainCarEnv',
    max_episode_steps=250,      # MountainCar-v0 uses 200
    reward_threshold=-110.0,
)
env = gym.make('MountainCarMyEasyVersion-v0')
```

**Comment by SomeDudeCalledMo** [comment]
If anybody is searching for this, here's how I did it:

I'll take 'Blackjack-v0' as an example, it has 1 argument 'natural' which defaults to False.
You can pass the argument(s) with the register functions kwargs argument, so you need to reregister the environment with a new name. I'll use 'Blackjack-natural-v0' (has to end with -v[number]).

First you need to import the register function:
`from gym.envs.registration import register`
Then you use the register function like this:
`register(
    id='Blackjack-natural-v0',
    entry_point='gym.envs.toy_text:BlackjackEnv',
    kwargs={'natural': True}
)`
Take a look at gym/envs/__init__.py if you want to copy an environment to make sure you copy all other arguments the same way.

Hope this helps anyone maybe, I'm pretty new to python myself so I had to search for it a bit myself

**Comment by benelot** [comment]
If you can live with an extra method call, you can easily create a method in your own env and then call it as:
your_env = gym.make("YourEnv")
your_env.env.your_init(your_vars)

you can also do self.your_var = None in init()
and then call:
your_env.env.your_var = some_var

upon calling reset or step,the variable can easily be used. I neede this at some point, maybe somebody else needs this too.

**Comment by icoxfog417** [comment]
I think `gym,make` have to support keyword arguments (now we have to make all environments by initial setting). I'm waiting for #644 merged!

**Comment by crobarcro** [comment]
I also wish this were possible, any chance that #644 will be merged soon?

**Comment by christopherhesse** [comment]
kwargs for gym.make were added since this was filed, please give that a try and open a new issue if it doesn't work correctly.

**Comment by sytelus** [comment]
Example:

```
env = gym.envs.make("podworld-v0", max_steps=10000, seed=None)
```
