### ISSUE TITLE
Dynamic action space

### ISSUE THREAD

**Issue by sebastianmarkow** [openai/gym#751]
How would someone implement a dynamic action space?

Since my environment has 16 actions with 25 subactions and at times only a few of them are legal. 
I went through the go and hex envs, which just raise or forfeit the session. But since my legal action pool is much smaller than the pool of illegal actions, I assume this is rather inefficient.

Any hints on how to mitigate this?

**Comment by mumas** [comment]
I would also expect Environment to provide legal action space given the state.

**Comment by Pozas91** [comment]
I think that in order to do this in a simple and standard way, the magic method __iter__ could be provided to the states, in this way the agents could perform operations such as:

```python
# Agent
for action in self.environment.action_space:
    print(action)
```

And environments that have the need to use dynamic action spaces could use the python properties to return the available states, such as:

```python
# Environment
@property
    def action_space(self):

        # Get current state
        state = self.current_state

        # Get all actions available
        keys = self.transactions.get(state, {}).keys()

        # Return complete valid_actions
        valid_actions = [value for value in self.action_space if value in keys]

        # Return and list of iterable valid actions
        return valid_actions
```

**Comment by avani17101** [comment]
> I think that in order to do this in a simple and standard way, the magic method `__iter__` could be provided to the states, in this way the agents could perform operations such as:
> 
> ```python
> # IterableDiscrete
> 
> from gym.spaces import Discrete
> 
> 
> class IterableDiscrete(Discrete):
> 
>         def __init__(self, n):
>         super().__init__(n)
>         self.index = 0
> 
>     def __iter__(self):
>         self.index = 0
>         return self
> 
>     def __next__(self):
>         if self.index < self.n:
>             x = self.index
>             self.index += 1
>             return x
>         else:
>             raise StopIteration
> 
>     def __repr__(self):
>         return "IterableDiscrete(%d)" % self.n
> 
>     def __eq__(self, other):
>         return isinstance(other, IterableDiscrete) and self.n == other.n
> ```
> 
> ```python
> # Agent
> for action in self.environment.action_space:
>     print(action)
> ```
> 
> And environments that have the need to use dynamic action spaces could use the python properties to return the available states, such as:
> 
> ```python
> # Environment
> @property
>     def action_space(self):
> 
>         # Get current state
>         state = self.current_state
> 
>         # Get all actions available
>         keys = self.transitions.get(state, {}).keys()
> 
>         # Return complete valid_actions
>         valid_actions = [value for value in self._action_space if value in keys]
> 
>         # Return and list of iterable valid actions
>         return valid_actions
> ```
My action space is {0,1,2... 9} integer vals, 
I followed the above mentioned solution, and did the following

``` 
self._action_space = IterableDiscrete(self.max_activities)
```
and this,
```
    @property
    def action_space(self):
        # Do some code here to calculate the available actions
        valid_actions = [value for value in self._action_space if value in self.possible_actions]

        # Return and list of iterable valid actions
        return valid_actions
```
am getting this error
```
AssertionError: The algorithm only supports (<class 'gym.spaces.box.Box'>, <class 'gym.spaces.discrete.Discrete'>, <class 'gym.spaces.multi_discrete.MultiDiscrete'>, <class 'gym.spaces.multi_binary.MultiBinary'>) as action spaces but [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] was provided
```

Please guide me further @Pozas91, anyone?
