### ISSUE TITLE
how could we change the code for individual environment so that we can change the dynamics and reward design?

### ISSUE THREAD

**Issue by xinleipan** [openai/gym#752]
I want to change some environments to count the number of times the agent dies or fails. However, for example in Freeway-v0, it is hard to infer whether the agent falls back to the start point or not.

**Comment by christopherhesse** [comment]
I think ALE exposes if you died in the info dictionary: `{'ale.lives': 5}`, though I don't see that for `Freeway-v0`.  For other games you should be able to create a wrapper that uses that information however you want.
