### ISSUE TITLE
Migrating gym leaderboards to wiki

### ISSUE THREAD

**Issue by ImpulseAdventure** [openai/gym#753]
Prompted by the change in the OpenAI gym's leaderboard status to read-only, the discussion in #718 led to @hardmaru's suggestion of creating a wiki to maintain the scores. A proper database would be ideal, but this might suffice for now. Following hardmaru's lead, I have started migrating a number of the descriptions and evaluations from the [read-only site](https://gym.openai.com/read-only.html).

Reference: [Gym leaderboard page](https://github.com/openai/gym/wiki/Leaderboard)

Assuming this is a useful endeavor, a couple questions come to mind:
- **Writeups**: Should one start with a focus on migrating evals that were accompanied by writeups? Some of the environments have a very large number of submissions, so this may be one way to keep the wiki manageable and highlight these entries.
- **Screenshots**: Presumably the inline screenshots are useful?
- **Page partitioning**: Assuming there is interest in copying the majority of the envs into the wiki, would it make sense to split each environment category (Classic Control, Algorithmic, Box2D, etc.) into their own page?
- **Validation**: Was there any desire for validation of future eval submissions? If so, how would that be done?
- **Filtering**: Would it make sense to only report the top score from each submitter (ie. fewest number of episodes to solve or highest performance)? Are the entries marked as "0 episodes to solve" valid?

Suggestions?

**Comment by hardmaru** [comment]
Thanks for helping with the migration. I think migrating the scores with write-ups only, at the beginning makes the most sense. The screenshots would be really helpful too (is there an easy way to do it in the wiki)?

Please feel free to take ownership of this and do what you think makes the most sense.

**Comment by ImpulseAdventure** [comment]
Thanks hardmaru. I think I've found a way to integrate screenshots into the wiki without having to store them externally or within the repo -- seems to be working so far.

@gdb -- in #718 you had asked if there were any broken links in the read-only site. If someone has an opportunity to see if the following might be recoverable, that would be great.

**Broken links**:

*Classic Control*
- https://gym.openai.com/envs/Acrobot-v1

*Minecraft*
- https://gym.openai.com/envs/TrickyArena1-v0
- https://gym.openai.com/envs/Eating1-v0
- https://gym.openai.com/envs/CliffWalking1-v0
- https://gym.openai.com/envs/Maze1-v0
- https://gym.openai.com/envs/Maze2-v0
