### ISSUE TITLE
What's the meaning of "observation_space"? How to deal with cases that state is out of "observation_space"?

### ISSUE THREAD

**Issue by PengZhenghao** [openai/gym#755]
I have written my own environment and set a observation_space.
However, ones my agent is out of that space, the program seem to continue until meet Max_Steps, and all the data (states, actions) are turn to "NaN".
More worse, after reset the environment, all data(states, actions) are still to be "NaN", seems "reset" didn't work.
What's the meaning of "observation_space"? How to deal with cases that state is out of "observation_space"?

**Comment by JoyChopra1298** [comment]
If you write code to your own environment you need to make sure that the observations you feed to the agent that belong to the observation space. The observation space can be any of the Space object which specifies the set of values that an observation for the environment can take.

For example suppose you define an environment's observation_space as `self.observation_space = spaces.MultiBinary(5)`. Then the observation space is set of all length 5 binary strings. And a observation is any one such string like 10010. If you use an observation 1001 then that will be invalid.

Note: spaces.MultiBinary doesn't actually store as python strings.

**Comment by tekinvahid** [comment]
You can have look at code for one agent like "mountain_car.py" [https://github.com/openai/gym/blob/master/gym/envs/classic_control/mountain_car.py](url). 
You can find the meaning of observation list's elements in this environment that is [position, velocity] for this particular environment. And code clips "state" on the cases that it is out of "observation_space":
```
velocity = np.clip(velocity, -self.max_speed, self.max_speed)
position += velocity
position = np.clip(position, self.min_position, self.max_position)
```
