### ISSUE TITLE
Is feature space in mujoco environments relative or absolute?

### ISSUE THREAD

**Issue by donamin** [openai/gym#759]
Hi
I've been looking at implementations of mujoco environments (Humanoid in this case), and it seems that the feature space is not constructed relatively. However I'm not sure about that and maybe I'm wrong.
So how can I make sure about relativeness of the feature vector? That's very crucial in learning at physical environments.

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
