### ISSUE TITLE
Images are not showing on gym.openai.com

### ISSUE THREAD

**Issue by gabrielcc2** [openai/gym#776]
Hiya,

Just pointing out a super simple issue: Images are not being shown in https://gym.openai.com/envs/.

Cheers,

Gabriel

**Comment by FirefoxMetzger** [comment]
Well the website is no longer maintained and merely a static export. 
See #718 for details.

**Comment by gabrielcc2** [comment]
Oh, Ok. Thanks for the pointer. Then I guess this issue is a non-issue ;)

I'll close it.
