### ISSUE TITLE
Issues installing openAI GYM over Mac

### ISSUE THREAD

**Issue by SalamElBsat** [openai/gym#782]
I am newbie to terminal (command line) in mac. I am trying to install openAI Gym, and I got the following, I tried search here and installing different dependencies, yet I am still stuck with this.
 
This is my log:

Obtaining file:///Users/SEBMachine/Documents/GitHub/gym
Requirement already satisfied: numpy>=1.10.4 in /Users/SEBMachine/miniconda3/lib/python3.6/site-packages (from gym==0.9.3)
Requirement already satisfied: requests>=2.0 in /Users/SEBMachine/miniconda3/lib/python3.6/site-packages (from gym==0.9.3)
Requirement already satisfied: six in /Users/SEBMachine/miniconda3/lib/python3.6/site-packages (from gym==0.9.3)
Requirement already satisfied: pyglet>=1.2.0 in /Users/SEBMachine/miniconda3/lib/python3.6/site-packages (from gym==0.9.3)
Requirement already satisfied: atari_py>=0.1.1 in /Users/SEBMachine/miniconda3/lib/python3.6/site-packages (from gym==0.9.3)
Requirement already satisfied: Pillow in /Users/SEBMachine/miniconda3/lib/python3.6/site-packages (from gym==0.9.3)
Requirement already satisfied: PyOpenGL in /Users/SEBMachine/miniconda3/lib/python3.6/site-packages (from gym==0.9.3)
Requirement already satisfied: pachi-py>=0.0.19 in /Users/SEBMachine/miniconda3/lib/python3.6/site-packages (from gym==0.9.3)
Collecting Box2D-kengz (from gym==0.9.3)
  Downloading Box2D-kengz-2.3.3.tar.gz (425kB)
    100% |████████████████████████████████| 430kB 989kB/s 
Collecting mujoco_py<1.0.0,>=0.4.3 (from gym==0.9.3)
Collecting imageio (from gym==0.9.3)
Collecting keras (from gym==0.9.3)
  Downloading Keras-2.1.1-py2.py3-none-any.whl (302kB)
    100% |████████████████████████████████| 307kB 1.0MB/s 
Collecting theano (from gym==0.9.3)
Requirement already satisfied: future in /Users/SEBMachine/miniconda3/lib/python3.6/site-packages (from pyglet>=1.2.0->gym==0.9.3)
Requirement already satisfied: olefile in /Users/SEBMachine/miniconda3/lib/python3.6/site-packages (from Pillow->gym==0.9.3)
Collecting pyyaml (from keras->gym==0.9.3)
Collecting scipy>=0.14 (from keras->gym==0.9.3)
  Downloading scipy-1.0.0-cp36-cp36m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl (16.7MB)
    100% |████████████████████████████████| 16.7MB 36kB/s 
Installing collected packages: Box2D-kengz, mujoco-py, imageio, pyyaml, scipy, keras, theano, gym
  Running setup.py install for Box2D-kengz ... error
    Complete output from command /Users/SEBMachine/miniconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-n4k_r08h/Box2D-kengz/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-am32i8h6-record/install-record.txt --single-version-externally-managed --compile:
    Using setuptools (version 27.2.0).
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.6
    creating build/lib.macosx-10.7-x86_64-3.6/Box2D
    copying library/Box2D/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/Box2D
    copying library/Box2D/Box2D.py -> build/lib.macosx-10.7-x86_64-3.6/Box2D
    creating build/lib.macosx-10.7-x86_64-3.6/Box2D/b2
    copying library/Box2D/b2/__init__.py -> build/lib.macosx-10.7-x86_64-3.6/Box2D/b2
    running build_ext
    building 'Box2D._Box2D' extension
    swigging Box2D/Box2D.i to Box2D/Box2D_wrap.cpp
    swig -python -c++ -IBox2D -small -O -includeall -ignoremissing -w201 -globals b2Globals -outdir library/Box2D -keyword -w511 -D_SWIG_KWARGS -o Box2D/Box2D_wrap.cpp Box2D/Box2D.i
    unable to execute 'swig': No such file or directory
    error: command 'swig' failed with exit status 1
    
    ----------------------------------------
Command "/Users/SEBMachine/miniconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-n4k_r08h/Box2D-kengz/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-am32i8h6-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-n4k_r08h/Box2D-kengz/

**Comment by Deniall** [comment]
Is swig set in your PATH correctly?

**Comment by StudentESE** [comment]
+1

**Comment by 13301132691** [comment]
+1

**Comment by Animuslupus** [comment]
+1

**Comment by christopherhesse** [comment]
This should be fixed on master, please file a new bug if not.
