### ISSUE TITLE
Broken images at https://gym.openai.com/envs/

### ISSUE THREAD

**Issue by howl-anderson** [openai/gym#789]
Many image links are broken at https://gym.openai.com/envs/

**Comment by FirefoxMetzger** [comment]
That's because the website has been depricated. See #718 for further details

**Comment by howl-anderson** [comment]
I already known that https://gym.openai.com/docs has been deprecated. Now I think that whole https://gym.openai.com/ is no longer maintained. If official developers don't have enough HR/time to manage this website, I think the community would be happy to contribute.

**Comment by FirefoxMetzger** [comment]
I think the topic is talking about the entire website, see https://github.com/openai/gym/issues/718#issuecomment-329661594

**Comment by christopherhesse** [comment]
The new static website seems to be working, please file a new issue if it is not.
