### ISSUE TITLE
"Making new env: ..." is annoying

### ISSUE THREAD

**Issue by ErazorBlade** [openai/gym#790]
Whenever I create a new environment, it prints "Making new env: BipedalWalker-v2". Is there a way to turn this of?

**Comment by aishik-pyne** [comment]
I guess they have added a log info whenever you make an environment in the file:
gym/gym/envs/registration.py Line 120
```python 
logger.info('Making new env: %s', id)
```

You can send them a pull request adding a log_verbose option and set it to false to prevent it from logging the name of the env into it.

Hope that helps

**Comment by FirefoxMetzger** [comment]
Or you can set the logging level to warning or higher or redirect sys.stdout while making the environment to prevent it from printing to the buffer you are interested in.

**Comment by christopherhesse** [comment]
Thanks for answering this @FirefoxMetzger, it looks like we use a custom logger, so you can use `gym.logger.set_level()`.  By default it shouldn't print the making lines, so make sure you're not setting the level somewhere and please file a PR if it's not working correctly.
