### ISSUE TITLE
Restricting action space for openai gym atari

### ISSUE THREAD

**Issue by lucasramos9** [openai/gym#793]
Hi All,

I'm working on a project and our aim is to make a game playing agent for the Atari game Tennis. However, one part of the game is that it needs to press fire to begin a rally, so we were thinking of circumventing this requirement by reducing the action space so that it is just the fire + movement. However, we have been unsuccessful in reducing the action space. Does anyone have any suggestions?

Thanks

**Comment by koulanurag** [comment]
I had a similar scenario sometime back and I did following: 

```
>>> import gym
>>> env= gym.make('Tennis-v0')
>>> env.unwrapped.get_action_meanings()
['NOOP', 'FIRE', 'UP', 'RIGHT', 'LEFT', 'DOWN', 'UPRIGHT', 'UPLEFT', 'DOWNRIGHT', 'DOWNLEFT', 'UPFIRE', 'RIGHTFIRE', 'LEFTFIRE', 'DOWNFIRE', 'UPRIGHTFIRE', 'UPLEFTFIRE', 'DOWNRIGHTFIRE', 'DOWNLEFTFIRE']
```

So, Let's say the new action space that you may like to have is : 

> ['NOOP', 'UPFIRE', 'RIGHTFIRE', 'LEFTFIRE', 'DOWNFIRE', 'UPRIGHTFIRE', 'UPLEFTFIRE', 'DOWNRIGHTFIRE', 'DOWNLEFTFIRE']

Now, You can simply train your network on this "action space". So, When your network predicts the action "1" i.e. "UPFIRE". Then; step "10" in the environment.Similarly, You can simply do mapping for others.

**Comment by christopherhesse** [comment]
You can create a wrapper to reduce the action space. There's an example in retro here: https://github.com/openai/retro/blob/master/retro/examples/discretizer.py#L9
