### ISSUE TITLE
hang when installing pachi-py 

### ISSUE THREAD

**Issue by fancyerii** [openai/gym#795]
I use pip install -e .[all] to install gym
my environment is Ubuntu 14.04 python 3.5 in virtualenv.
After the terminal outputing "Collecting pachi-py>=0.0.19 (from gym==0.9.3)
  Using cached pachi-py-0.0.21.tar.gz“
It hangs. I use ps to find pip process and it use no cpu.

ps aux|grep pip
mc        3757  1.4  0.7 122884 62544 pts/0    S+   00:25   0:03 /home/mc/env-py3.5/bin/python3.5 /home/mc/env-py3.5/bin/pip install -e .[all]
mc        3767  0.4  0.3  79876 25656 pts/0    S+   00:25   0:01 /home/mc/env-py3.5/bin/python3.5 -c import setuptools, tokenize;__file__='/tmp/pip-build-5xb2pwhq/pachi-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec')) egg_info --egg-base pip-egg-info

**Comment by jafetmorales** [comment]
How long did you wait? I waited between 5 and 10 minutes and it did eventually continue. Looks like it's compiling something.

**Comment by fancyerii** [comment]
the problem is I have not installed python3.5-dev. After I installed it, it's fine. But it should not hang
