### ISSUE TITLE
gym's version.py is at v0.9.3 but pypa has v0.9.4

### ISSUE THREAD

**Issue by FirefoxMetzger** [openai/gym#796]
If I `pip search gym` on my Win10 I find OpenAI `gym (0.9.4)`.
However, this repo's [version.py](https://github.com/openai/gym/blob/master/gym/version.py#L1) is on `0.9.3`.

I am curious what this version mismatch is about. Does the version in this repo have a different versioning than the pypa?

**Comment by cristyandavid1** [comment]
Bitcoins
