### ISSUE TITLE
pyglet.gl.lib.GLException: b'invalid enumerant'

### ISSUE THREAD

**Issue by lzx8608** [openai/gym#798]
**When doing the example: python3 examples/agents/random_agent.py** 
receive error:
[2017-12-11 21:07:20,217] Making new env: CartPole-v0
[2017-12-11 21:07:20,223] Clearing 3 monitor files from previous run (because force=True was provided)
[2017-12-11 21:07:20,225] Starting new video recorder writing to /tmp/random-agent-results/openaigym.video.0.47371.video000000.mp4
Traceback (most recent call last):
File "/home/lzx/gym/examples/agents/random_agent.py", line 52, in <module>
ob = env.reset()
File "/home/lzx/gym/gym/core.py", line 104, in reset
return self._reset()
File "/home/lzx/gym/gym/wrappers/monitoring.py", line 40, in _reset
self._after_reset(observation)
File "/home/lzx/gym/gym/wrappers/monitoring.py", line 197, in _after_reset
self._reset_video_recorder()
File "/home/lzx/gym/gym/wrappers/monitoring.py", line 218, in _reset_video_recorder
self.video_recorder.capture_frame()
File "/home/lzx/gym/gym/monitoring/video_recorder.py", line 106, in capture_frame
frame = self.env.render(mode=render_mode)
File "/home/lzx/gym/gym/core.py", line 150, in render
return self._render(mode=mode, close=close)
File "/home/lzx/gym/gym/core.py", line 286, in _render
return self.env.render(mode, close)
File "/home/lzx/gym/gym/core.py", line 150, in render
return self._render(mode=mode, close=close)
File "/home/lzx/gym/gym/envs/classic_control/cartpole.py", line 146, in _render
return self.viewer.render(return_rgb_array = mode=='rgb_array')
File "/home/lzx/gym/gym/envs/classic_control/rendering.py", line 94, in render
image_data = buffer.get_image_data()
File "/usr/local/lib/python3.5/dist-packages/pyglet/image/__init__.py", line 2155, in get_image_data
self.gl_format, GL_UNSIGNED_BYTE, buffer)
File "/usr/local/lib/python3.5/dist-packages/pyglet/gl/lib.py", line 105, in errcheck
raise GLException(msg)
pyglet.gl.lib.GLException: b'invalid enumerant'

And I try the method proposed in https://github.com/openai/gym/issues/115, but it  doesn't work for me.

**this is my python3 -m pyglet.info**

Python
------------------------------------------------------------------------------
sys.version: 3.5.2 |Anaconda 4.2.0 (64-bit)| (default, Jul  2 2016, 17:53:06) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
sys.platform: linux
sys.maxint: 9223372036854775807
os.getcwd(): /home/lzx

pyglet
------------------------------------------------------------------------------
pyglet.version: 1.3.0
pyglet.compat_platform: linux
pyglet.__file__: /usr/local/lib/python3.5/dist-packages/pyglet/__init__.py
pyglet.options['xsync'] = True
pyglet.options['debug_gl_trace_args'] = False
pyglet.options['audio'] = ('directsound', 'pulse', 'openal', 'silent')
pyglet.options['debug_graphics_batch'] = False
pyglet.options['shadow_window'] = True
pyglet.options['debug_trace'] = False
pyglet.options['debug_win32'] = False
pyglet.options['vsync'] = None
pyglet.options['graphics_vbo'] = True
pyglet.options['debug_x11'] = False
pyglet.options['xlib_fullscreen_override_redirect'] = False
pyglet.options['debug_font'] = False
pyglet.options['debug_trace_flush'] = True
pyglet.options['debug_texture'] = False
pyglet.options['debug_media'] = False
pyglet.options['debug_trace_args'] = False
pyglet.options['debug_gl_trace'] = False
pyglet.options['search_local_libs'] = True
pyglet.options['font'] = ('gdiplus', 'win32')
pyglet.options['debug_trace_depth'] = 1
pyglet.options['darwin_cocoa'] = False
pyglet.options['debug_gl'] = True
pyglet.options['debug_lib'] = False`
pyglet.window

------------------------------------------------------------------------------

platform: <pyglet.window.Platform object at 0x7f8d40c6d5c0>
display: <pyglet.canvas.xlib.XlibDisplay object at 0x7f8d4045e940>
screens[0]: XlibScreen(display=<pyglet.canvas.xlib.XlibDisplay object at 0x7f8d4045e940>, x=0, y=0, width=1920, height=1080, xinerama=1)
screens[1]: XlibScreen(display=<pyglet.canvas.xlib.XlibDisplay object at 0x7f8d4045e940>, x=1920, y=0, width=1920, height=1080, xinerama=1)
config['double_buffer'] = 1
config['stereo'] = 0
config['buffer_size'] = 32
config['aux_buffers'] = 0
config['sample_buffers'] = 0
config['samples'] = 0
config['red_size'] = 8
config['green_size'] = 8
config['blue_size'] = 8
config['alpha_size'] = 8
config['depth_size'] = 24
config['stencil_size'] = 8
config['accum_red_size'] = 16
config['accum_green_size'] = 16
config['accum_blue_size'] = 16
config['accum_alpha_size'] = 16
config['major_version'] = None
config['minor_version'] = None
config['forward_compatible'] = None
config['debug'] = None
context: XlibContext13()

window.context._info
------------------------------------------------------------------------------
gl_info.get_version(): 1.4 (4.4.0 - Build 21.20.16.4574)
gl_info.get_vendor(): Intel
gl_info.get_renderer(): Intel(R) HD Graphics 530
gl_info.get_extensions():
   GL_ARB_depth_texture
   GL_ARB_draw_buffers
   GL_ARB_fragment_program
   GL_ARB_fragment_program_shadow
   GL_ARB_multisample
   GL_ARB_multitexture
   GL_ARB_occlusion_query
   GL_ARB_point_parameters
   GL_ARB_point_sprite
   GL_ARB_shadow
   GL_ARB_texture_border_clamp
   GL_ARB_texture_compression
   GL_ARB_texture_cube_map
   GL_ARB_texture_env_add
   GL_ARB_texture_env_combine
   GL_ARB_texture_env_crossbar
   GL_ARB_texture_env_dot3
   GL_ARB_texture_mirrored_repeat
   GL_ARB_texture_non_power_of_two
   GL_ARB_transpose_matrix
   GL_ARB_vertex_program
   GL_ARB_window_pos
   GL_EXT_abgr
   GL_EXT_bgra
   GL_EXT_blend_color
   GL_EXT_blend_equation_separate
   GL_EXT_blend_func_separate
   GL_EXT_blend_minmax
   GL_EXT_blend_subtract
   GL_EXT_draw_range_elements
   GL_EXT_fog_coord
   GL_EXT_framebuffer_object
   GL_EXT_multi_draw_arrays
   GL_EXT_packed_pixels
   GL_EXT_rescale_normal
   GL_EXT_secondary_color
   GL_EXT_separate_specular_color
   GL_EXT_shadow_funcs
   GL_EXT_stencil_two_side
   GL_EXT_stencil_wrap
   GL_EXT_texture3D
   GL_EXT_texture_compression_s3tc
   GL_EXT_texture_edge_clamp
   GL_EXT_texture_env_add
   GL_EXT_texture_env_combine
   GL_EXT_texture_filter_anisotropic
   GL_EXT_texture_lod_bias
   GL_IBM_texture_mirrored_repeat
   GL_NV_blend_square
   GL_NV_texgen_reflection
   GL_SGIS_generate_mipmap
   GL_SGIS_texture_lod

pyglet.gl.glu_info
------------------------------------------------------------------------------
glu_info.get_version(): 1.3
glu_info.get_extensions():
   GLU_EXT_nurbs_tessellator
   GLU_EXT_object_space_tess

pyglet.gl.glx_info
------------------------------------------------------------------------------
context.is_direct(): 0
glx_info.get_server_vendor(): SGI
glx_info.get_server_version(): 1.4
glx_info.get_server_extensions():
   GLX_ARB_multisample
   GLX_EXT_import_context
   GLX_EXT_visual_info
   GLX_EXT_visual_rating
   GLX_MESA_copy_sub_buffer
   GLX_OML_swap_method
   GLX_SGI_make_current_read
   GLX_SGI_swap_control
   GLX_SGIS_multisample
   GLX_SGIX_fbconfig
   GLX_SGIX_pbuffer
glx_info.get_client_vendor(): NVIDIA Corporation
glx_info.get_client_version(): 1.4
glx_info.get_client_extensions():
   GLX_ARB_get_proc_address
   GLX_ARB_multisample
   GLX_EXT_visual_info
   GLX_EXT_visual_rating
   GLX_EXT_import_context
   GLX_SGI_video_sync
   GLX_NV_swap_group
   GLX_NV_video_out
   GLX_SGIX_fbconfig
   GLX_SGIX_pbuffer
   GLX_SGI_swap_control
   GLX_EXT_swap_control
   GLX_EXT_swap_control_tear
   GLX_EXT_buffer_age
   GLX_ARB_create_context
   GLX_ARB_create_context_profile
   GLX_NV_float_buffer
   GLX_ARB_fbconfig_float
   GLX_EXT_fbconfig_packed_float
   GLX_EXT_texture_from_pixmap
   GLX_EXT_framebuffer_sRGB
   GLX_NV_present_video
   GLX_NV_copy_image
   GLX_NV_copy_buffer
   GLX_NV_multisample_coverage
   GLX_NV_video_capture
   GLX_EXT_create_context_es_profile
   GLX_EXT_create_context_es2_profile
   GLX_ARB_create_context_robustness
   GLX_NV_delay_before_swap
   GLX_EXT_stereo_tree
   GLX_ARB_context_flush_control
   GLX_NV_robustness_video_memory_purge
glx_info.get_extensions():
   GLX_ARB_multisample
   GLX_EXT_import_context
   GLX_EXT_visual_info
   GLX_EXT_visual_rating
   GLX_SGI_swap_control
   GLX_SGIX_fbconfig
   GLX_SGIX_pbuffer
   GLX_ARB_get_proc_address

pyglet.media
------------------------------------------------------------------------------
audio driver: <pyglet.media.drivers.silent.SilentAudioDriver object at 0x7f8d39470208>

pyglet.media.avbin
------------------------------------------------------------------------------
AVbin not available.

pyglet.media.drivers.openal
------------------------------------------------------------------------------
Library: <CDLL 'libopenal.so.1', handle 259b3d0 at 0x7f8d363cffd0>

pyglet.input.wintab
------------------------------------------------------------------------------
WinTab not available.

**so how can I fix this problem?**

**Comment by lzx8608** [comment]
Oh I fix it

**Comment by ashishm-io** [comment]
How did you fix this?

**Comment by lzx8608** [comment]
Sorry. I don't know how to comment to you. 
I uninstall my CUDA and NVIDIA driver.
reinstall it with no opengl lib option.
The install code is:
sudo "/home/lzx/NVIDIA-Linux-x86_64-375.82.run" --no-opengl-files
sudo "/home/lzx/cuda_8.0.61.2_linux.run" --no-opengl-libs
and then use other libGl as opengl lib:
sudo ln -s /usr/lib/x86_64-linux-gnu/mesa/libGL.so.1 /usr/lib/libGL.so.1

I found the solution in https://github.com/openai/gym/issues/366

**Comment by ychjiang** [comment]
i tryed  but still unrun. can any one have methods to solve it? can i guess because of my NVIDIA Tesla K20 computation card ?

**Comment by christopherhesse** [comment]
I believe https://github.com/openai/gym/issues/366 answers this question and it looks like this has been resolved.
