### ISSUE TITLE
OSError on atari environment

### ISSUE THREAD

**Issue by tonychan818** [openai/gym#800]
my OS is MacOS Sierra

when I run the these codes
```
import gym
env = gym.make('SpaceInvaders-v0')
env.reset()
env.render()
```

I got the following error

OSError: dlopen(/usr/local/lib/python2.7/site-packages/atari_py/ale_interface/build/libale_c.so, 6): no suitable image found.  Did find:
	/usr/local/lib/python2.7/site-packages/atari_py/ale_interface/build/libale_c.so: mach-o, but built for simulator (not macOS)
	/usr/local/lib/python2.7/site-packages/atari_py/ale_interface/build/libale_c.so: mach-o, but built for simulator (not macOS)

any idea?? It seems the atari_py not compile properly? it looks like my mac is not able to run the .so files

**Comment by christopherhesse** [comment]
Please try using the atari_py wheels (which require python 3.5 or newer) and file a new issue if you're still getting that error.
