### ISSUE TITLE
 env.monitor.start('Artificial Intelligence/'+GAME, force=True)

### ISSUE THREAD

**Issue by obidovtz** [openai/gym#801]
# when I run code, appears that error:

(py34) C:\Users\obidov.tz\gym>python "C:\Disk D\Artificial_Intelegence_article\OpenAI_BipedalWalker_v2.py"
[2017-12-12 16:32:40,820] Making new env: BipedalWalker-v2

Observation
--------------------------------
Shape : 24
 High : [ inf  inf  inf  inf  inf  inf  inf  inf  inf  inf  inf  inf  inf  inf  inf
  inf  inf  inf  inf  inf  inf  inf  inf  inf]
 Low : [-inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf -inf
 -inf -inf -inf -inf -inf -inf -inf -inf -inf]

Action
--------------------------------
Shape : 4  | High : [1 1 1 1]  | Low : [-1 -1 -1 -1]

Generation :   1  |  Min :  -200  |  Avg :  -116  |  Max :   -82
Generation :   2  |  Min :  -163  |  Avg :  -115  |  Max :   -87
Generation :   3  |  Min :  -167  |  Avg :  -111  |  Max :   -84
Generation :   4  |  Min :  -148  |  Avg :  -110  |  Max :   -84
Generation :   5  |  Min :  -173  |  Avg :  -110  |  Max :   -86
Generation :   6  |  Min :  -210  |  Avg :  -109  |  Max :   -71
Generation :   7  |  Min :  -184  |  Avg :  -108  |  Max :   -61
Generation :   8  |  Min :  -190  |  Avg :  -108  |  Max :   -47
Generation :   9  |  Min :  -232  |  Avg :  -107  |  Max :   -50
Generation :  10  |  Min :  -178  |  Avg :  -105  |  Max :   -43

 Recording Best Bots
---------------------
Traceback (most recent call last):
  File "C:\Disk D\Artificial_Intelegence_article\OpenAI_BipedalWalker_v2.py", line 240, in <module>
    recordBestBots(bestNeuralNets)
  File "C:\Disk D\Artificial_Intelegence_article\OpenAI_BipedalWalker_v2.py", line 144, in recordBestBots
    env.monitor.start('Artificial Intelligence/'+GAME, force=True)
AttributeError: 'TimeLimit' object has no attribute 'monitor'

**Comment by jalajthanaki** [comment]
I had same issue.
` Traceback (most recent call last):
  File "atari.py", line 74, in <module>
    env.gym.monitor.start(args.out, force=True)
AttributeError: 'TimeLimit' object has no attribute 'monitor'`

**Comment by QuantumTCode** [comment]
Same exact error.

**Comment by christopherhesse** [comment]
Do you have a script that produces this error?
