### ISSUE TITLE
Registration kwargs are only passed to string entry points

### ISSUE THREAD

**Issue by timmeinhardt** [openai/gym#802]
Is there a particular reason why the `kwargs` argument of an environment registration is only passed to entry points that are provided in from of a string?

https://github.com/openai/gym/blob/efeadfdd20992aeba69e038205af90d340c5f95b/gym/envs/registration.py#L86

**Comment by christopherhesse** [comment]
Seems like we could remove the support for callables to `gym.make()` since I can't think of any reason to use `gym.make()` if you can just call the thing directly.
