### ISSUE TITLE
[Discussion] Mujoco 1.5, 1.3, dependencies and docker

### ISSUE THREAD

**Issue by pascalwhoop** [openai/gym#805]
Hi. I wanted to start a discussion about my workings and see if, with some help, I can get them done and contribute them if it is so desired.

I combined the [tensorflow gpu docker](https://github.com/tensorflow/tensorflow/tree/master/tensorflow/tools/docker) image with the dependencies of gym and made a `Dockerfile` that adds on top of the previously mentioned the gym, mujoco and whatelse is required. 

What works:
- docker build: Builds the image
- VNC connection and seeing some of the examples

What doesn't work: Mujoco 1.3 or 1.5.
1.3 doesn't work because I got a license for 1.5 apparently. 1.5 works with the license but it crashes because I cannot install the dependencies with pip for python3, because the build for pachi-py fails. I believe it is related to [a previous issue](https://github.com/openai/gym/issues/255)

So first of all: Is there an interest by others to get this to work? The benefit is that we could work in Jupyter Notebooks and still get the rendering on a virtual display that is connectable with VNC. So a Docker container in the cloud with some beefy GPU underneath and still working in Jupyter, doesn't sound too bad. 

If so, I'd need some help on how to get either the pachi-py build working on python3 so we can upgrade to 1.50 with [this PR](https://github.com/openai/gym/pull/767) or someone would need to test if it really works with 1.3 as I can't get a license for the lower version for some reason.

**Comment by pascalwhoop** [comment]
I posted the Docker build [in a repo](https://github.com/pascalwhoop/tf_openailab_gpu_docker)

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
