### ISSUE TITLE
conda installation support

### ISSUE THREAD

**Issue by jimdowling** [openai/gym#809]
It would be great to have an anaconda package for installing gym in conda environments using conda (not pip).

Background: I'm running a large DL course with 150 students, and much of my time has gone on getting 'pip install gym[...]' to work for conda enviornments. There have been issues with gcc incompatability, the usual python 2.7/3.6 issues. I expect my situation is not unique.

**Comment by jimdowling** [comment]
They work on real big data (40+ TB datasets) - we use Hops Hadoop as a multi-tenant platform. It supports conda and runs Tensorflow/SparkML jobs on YARN. Docker isn't there yet with YARN. Afaik, we're the only distributed DL course where students work with massive datasets.

**Comment by FirefoxMetzger** [comment]
Hm, I suppose you already looked into `conda skeleton pypi gym` to try and generate the anaconda package from the available pypi one. Did that cause any problems?

**Comment by jimdowling** [comment]
We're limited in the conda channels we can use - 'default', 'conda-forge'. So, no didn't try it. I suppose i could try and get it in 'conda-forge'.

**Comment by andrewgough94** [comment]
Any update here ?

**Comment by kevindavenport** [comment]
Curious of the same

**Comment by netkachev** [comment]
+1, this feature would be nice to have

**Comment by redlum94** [comment]
I am pretty new to python including anaconda an pip. For me pip was installed in anaconda3 and i was able to successfully use `pip install gym` in the anaconda terminal. It installed successfully into my environment.

**Comment by Ketki-Savle** [comment]
Thank you. I tried conda install --upgrade gym and conda install gym and got an error. pip install gym went through quickly and could work on it easily.

**Comment by kota8** [comment]
`pip install gym` works good, but supporting `conda install gym` will be great.  An advantage is that it can resolve dependency with external software.  Such as `libgcc` #543 and `ffmpeg`. https://github.com/openai/gym/blob/5404b39d06f72012f562ec41f60734bd4b5ceb4b/gym/wrappers/monitoring/video_recorder.py#L249-L254  
Both could be resolved by conda packaging by linking to `conda install libgcc` and `conda install -c conda-forge ffmpeg`.

**Comment by christopherhesse** [comment]
Conda support would be great, but I think we can get a lot of the benefit by making the pip install more reliable for everyone.  I think `video_recorder.py` should probably use `imageio` which already has a package, `imageio-ffmpeg`, and then we don't need a `ffmpeg` dependency.   For `gcc`, I think it would be best if we have compiled wheels for gym dependencies.

What packages are people having the most trouble with?  From https://github.com/openai/gym/blob/master/setup.py#L9 it looks like `atari-py` and `box2d-py` are the most likely to fail (besides mujoco licensing issues, but we've recently released binary wheels for roboschool https://github.com/openai/roboschool).   Those dependencies now have binary wheels on mac and linux that should work for most people.

**Comment by josephcarmack** [comment]
I tried creating a conda package version of gym with `conda skeleton pypi gym` but could not get it to work. My failure is likely due to my lack of experience with this feature of conda so any help with getting a conda package version of gym would be much appreciated.

**Comment by AdamStelmaszczyk** [comment]
That would not work, because `gym` is not present in the default conda channel. Right now you can install it with `pip`.

I will probably look into creating conda package, it would be very handy.

**Comment by justinkterry** [comment]
@AdamStelmaszczyk Any movement here? If not I'd be interested in working on doing official support for it.

**Comment by AdamStelmaszczyk** [comment]
Hey @justinkterry, sorry I didn't have time. I remember I looked briefly into it and seemed doable, but quite a bit of work. Feel welcome to do it :)

**Comment by justinkterry** [comment]
So it's already on conda: https://anaconda.org/powerai/gym, so porting it isn't the issue. The main challenge is that we'd want the release to be official, and to happen when it's pushed to PyPI. That would require involvement on the part of Gym maintainers and is not something I could fix on my own. @ppzhokhov ?
