### ISSUE TITLE
env.observation_space returns different datatypes for different envs

### ISSUE THREAD

**Issue by ThorbenJensen** [openai/gym#810]
I ran into a compatibility issue when adapting the example `baselines.deepq.experiments.train_cartpole` from `gym.make("CartPole-v0")` to `gym.make("Blackjack-v0")`

After adaptation, the code looks like this:
```
import gym
from baselines import deepq

env = gym.make("Blackjack-v0")
model = deepq.models.mlp([64])
act = deepq.learn(
    env,
    q_func=model,
    lr=1e-2,
    max_timesteps=10000,
    buffer_size=50000,
    exploration_fraction=0.1,
    exploration_final_eps=0.02,
    print_freq=10
)
print("Saving model to blackjack.pkl")
act.save("blackjack_model.pkl")
```
Unfortunately, the following error is thrown: 
```
~/bin/miniconda3/lib/python3.6/site-packages/baselines/deepq/simple.py in make_obs_ph(name)
    168 
    169     def make_obs_ph(name):
--> 170         return U.BatchInput(env.observation_space.shape, name=name)
    171 
    172     act, train, update_target, debug = deepq.build_train(

AttributeError: 'Tuple' object has no attribute 'shape'
```
**Could this be because _env.observation_space_ returns a different data type for "CartPole-v0" and "Blackjack-v0"?** 
The first returns a Box type, for which `.shape` works, the latter returns a Tuple type, which does not.

**Suggestion: change the blackjack environment to also return a Box datatype.**
Any opinions?

**Comment by christopherhesse** [comment]
This seems to be a limitation of baselines, which often does not support dict spaces, much less tuple spaces.  I think this should be a baselines issue rather than a gym issue, because there should be environments where expressing the observation space as a dict space actually makes the most sense.
