### ISSUE TITLE
Ubuntu - failed building wheel for atari

### ISSUE THREAD

**Issue by intouch2553** [openai/gym#812]
error message be like this
![image](https://user-images.githubusercontent.com/34792759/34319886-8cfac5c6-e81f-11e7-82fc-ee14083b884b.png)
can you help me please?
i just installed ubuntu hours ago and i dont know what to do with it

edit: when i installed cmake the error changed into this
![image](https://user-images.githubusercontent.com/34792759/34320064-7423b842-e823-11e7-85eb-22a7747a79b9.png)

**Comment by christopherhesse** [comment]
Looks like you need to install cmake, https://github.com/openai/gym#installing-everything
