### ISSUE TITLE
Missing module gym.scoreboard.registration.py

### ISSUE THREAD

**Issue by ChiragAnilkumar** [openai/gym#815]
It seems module registration.py is missing. In repo ppaquette/gym-doom, gym-doom/ppaquette_gym_doom/__init__.py imports add_task and add_group from gym.scoreboard.registration.py. But such a file doesn't exist anymore. So please do add that

**Comment by FirefoxMetzger** [comment]
It got removed when the scoreboard website was deprecated, so there is no real point in re-adding it as the back-end has gone away.

Also please note that `ppaquette/gym-doom` is not this repository. You should create an issue over there and say that they should either use a previous version of `gym` or update their code to reflect this (not backwards-compatible) change.

**Comment by jamesrichter** [comment]
This is still in the docs for adding new environments:

4.   Add your environment to the scoreboard in /gym/scoreboard/__init__.py

But /gym/scoreboard/ doesn't exist, should this be changed too?

**Comment by christopherhesse** [comment]
Thanks for answering this @FirefoxMetzger!  I've made a PR to fix the docs here: https://github.com/openai/gym/pull/1458
