### ISSUE TITLE
Can PP1 solve the Humanoid-v1 problem?

### ISSUE THREAD

**Issue by NoListen** [openai/gym#816]
I stuck at scores around 900 but I expected to see a much higher score.
[Note: I tried changing the batch_size to 512 and timesteps_per_actorbatch to 4096.]

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
