### ISSUE TITLE
Reward Calculation for MuJoCo Environments

### ISSUE THREAD

**Issue by arjunneervannan** [openai/gym#817]
I am testing various reinforcement learning algorithms on the MuJoCo environments using Tensorforce, a reinforcement learning library built on Tensorflow. I did not find the reward calculations for these environments on the OpenAI website, and wanted to know if anyone had these calculations. I am using the HalfCheetah-v1 environment, the Walker2d-v1 environment, and the Ant-v1 environment.

**Comment by KaustabhGanguly** [comment]
Have you looked inside the source files ?

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
