### ISSUE TITLE
How to support Texas hold'em

### ISSUE THREAD

**Issue by SmartAI** [openai/gym#819]
I want to do some research in playing Texas hold'em, how can I use gym?

**Comment by wenkesj** [comment]
@SmartAI Create a game engine that emulates Texas Hold'em, extend the `gym.Env` class and maintain the standard gym environment API. It may sound simple at first but multi-agent environments are _non-trivial_ to implement and standardize. You may notice that there is a sparsity of such cases, but as a work around you can encode the multi- state- and action- space as `spaces.Tuple` of states/actions corresponding to players.

Good luck!

**Comment by wenkesj** [comment]
@SmartAI fyi I threw something together that demonstrates how [a Texas Hold'em gym environment](https://github.com/wenkesj/holdem) can be done, this is just one of many possibilities

**Comment by SmartAI** [comment]
@wenkesj  Thanks for your suggestion.

**Comment by christopherhesse** [comment]
Thanks for answering this @wenkesj!

**Comment by dickreuter** [comment]
Put an implementation together here:
https://github.com/dickreuter/neuron_poker

It also demonstrates some implementations with reinforcement learning.
