### ISSUE TITLE
Plans for updating to ALE 0.6?

### ISSUE THREAD

**Issue by floringogianu** [openai/gym#820]
The [update](https://github.com/mgbellemare/Arcade-Learning-Environment/releases/tag/v0.6.0) brings some new modes on some of the games aimed at continuous learning tasks and also allows for difficulty levels as described in 7.4.1 in _[Revisiting the Arcade...](https://arxiv.org/abs/1709.06009)_ It also brings support for some new games.

Was wondering if anyone working on this before I start poking around myself.

**Comment by christopherhesse** [comment]
Closing in favor of https://github.com/openai/atari-py/issues/23
