### ISSUE TITLE
Issues starting own environment

### ISSUE THREAD

**Issue by Zarnluz** [openai/gym#826]
Hello,

I wanted to create a new environment (MyEnv).
It is already registered and can be rendered without any problem.

What cought my eye is that every time I start the environment, it looks like this:

[2018-01-16 09:31:01,787] Making new env: MyEnv-v1
[2018-01-16 09:31:01,848] Making new env: CartPole-v0
[2018-01-16 09:31:01,848] Making new env: CartPole-v0
[2018-01-16 09:31:01,944] Making new env: CartPole-v0
[2018-01-16 09:31:01,945] Making new env: CartPole-v0

And after that my episodes start normally.
MyEnv started as a copy of CartPole but I changed everything. I have registered it separately, created a new environment repo and everything else is changed. What happens when I delete CartPole-v0 I get an error saying CartPole-v0 cannot be found.

Did I mess something up?
How can I fix this?

Thanks in advance.

**Comment by chairbender** [comment]
Delete the CartPole environment. Error should tell you which line is trying to load that environment. Remove that reference. Also, find all references in your code to CartPole-v0. Remove them.

**Comment by Zarnluz** [comment]
Had a self written test.py file which caused that error. No idea why it was called though. My main testing python program did not call upon the test.py program which is very strange.
Deleting everything helped though, thank you.
