### ISSUE TITLE
Help needed , to make environments for own games .

### ISSUE THREAD

**Issue by stabgan** [openai/gym#830]
Please a little help is appreciated .

**Comment by chairbender** [comment]
Look at the instructions here: https://github.com/openai/gym/tree/master/gym/envs

The soccer environment is a good example to follow.

**Comment by AlexandreOuellet** [comment]
I also have problems with it.  I've cloned the gym-soccer into a new repository, removed the dependency, and modified soccer_env.py to be exactly as the cartpole.py environment (except for the class name, which is still SoccerEnv).

I do a `pip install -e .` within the gym-soccer directory, and it installs properly.  When I tried to instantiate an environment with `env = gym.make('Soccer-v0')`, I get an error 👍 `gym.error.UnregisteredEnv: No registered env with id: Soccer-v0`

You can find the repository [here](https://github.com/AlexandreOuellet/gym-soccer)

**Comment by AlexandreOuellet** [comment]
There is something weird going on with gym-soccer, where I can't seem to run it properly, but following https://stackoverflow.com/questions/45068568/is-it-possible-to-create-a-new-gym-environment-in-openai/47132897#47132897, I managed to clone gym-maze, and make it work by adding `import gym_maze` (which was not working with gym_soccer).

It appears I can use this one as a template instead.

**Comment by christopherhesse** [comment]
Thanks for answering this @chairbender, it might be the case that the instructions at https://github.com/openai/gym/blob/master/docs/creating-environments.md should use `gym_maze` and an example instead of `gym_soccer`.  If this is the case, a PR for the docs would be cool to see.
