### ISSUE TITLE
Breakout freeze if the agent can survive for a long time

### ISSUE THREAD

**Issue by hengyuan-hu** [openai/gym#833]
In the Atari game environment, the environment will freeze if the agent can play the game for a very long time. The game is not ended since there are still several blocks left there. The agent cannot hit them while it can always catch the ball, making the game last for a very long time. Then the game will freeze.

The video is uploaded here:
https://drive.google.com/file/d/1iLcp5mwdAlkizy5LOJwVYveD5FiVkhXR/view?usp=sharing

The freezing problem occurs at around 36min 30s. This seems to be a problem of ALE instead of gym since I ran into a similar problem before when I use my own wrapper of ALE. I raise it here with the hope to receive more attention. Also, how can I record the video in faster motion?

**Comment by muupan** [comment]
I can replicate the same issue. When I `gym.make('BreakoutNoFrameskip-v4')` and send NOOPs only, the observations are as below.

Observation after 65535th noop:
![image](https://user-images.githubusercontent.com/815970/48312379-f16a7e00-e5f0-11e8-9dad-87a73a87b604.png)

Observation after 65536th noop:
![image](https://user-images.githubusercontent.com/815970/48312370-d39d1900-e5f0-11e8-9de7-6514e2b12008.png)

Observation after 65537th noop:
![image](https://user-images.githubusercontent.com/815970/48312389-fdeed680-e5f0-11e8-9659-c5edb9f51679.png)

After 65535th action, Breakout no longer accepts FIRE after 65535th action, making the game stuck, while you can still move the paddle.

**Comment by twibiral** [comment]
I have exactly the same problem. Did you find any solution?

**Comment by hengyuan-hu** [comment]
Set a maximum length for the episode.
