### ISSUE TITLE
cannot import name spaces

### ISSUE THREAD

**Issue by erastogi** [openai/gym#838]
Hi, I recently installed gym package and I get following error whenever I try to import gym :
![gy](https://user-images.githubusercontent.com/24869756/35456264-def4ae08-02a2-11e8-8b9a-832a796bf3d2.png)

**Comment by covarsha** [comment]
Do
>>pip uninstall gym
>>pip2 install gym
The error disappeared for me when I did that

**Comment by aseembits93** [comment]
Doesn't seem to work for me. i downgraded gym to 0.9.2 to make it work.

**Comment by Astronirav** [comment]
I got the same error when I tried to run one of their inbuilt examples /gym/examples/agents/random_agent.py  after installing it. 

`Traceback (most recent call last):`
`File "random_agent.py", line 4, in <module>`
`import gym`
`File "/home/astronirav/git/gym/gym/__init__.py", line 12, in <module>`
`from gym import wrappers, spaces, logger`
`File "/home/astronirav/git/gym/gym/spaces/__init__.py", line 1, in <module>`
`from gym.spaces.box import Box`
`File "/home/astronirav/git/gym/gym/spaces/box.py", line 2, in <module>`
`from gym import Space, spaces, logger`
`ImportError: cannot import name 'spaces'`

**Comment by vzhadeyev** [comment]
Got the same error, but reference to [https://github.com/tensorflow/tensor2tensor/pull/520](url) doesn't make any sense. 
`Traceback (most recent call last):
  File "/Users/slava/Documents/Dev/IntroML/Labs/Lab11/main.py", line 1, in <module>
    import gym
  File "/Users/slava/Documents/Dev/openai/gym/gym/__init__.py", line 12, in <module>
    from gym import wrappers, spaces, logger
  File "/Users/slava/Documents/Dev/openai/gym/gym/spaces/__init__.py", line 1, in <module>
    from gym.spaces.box import Box
  File "/Users/slava/Documents/Dev/openai/gym/gym/spaces/box.py", line 2, in <module>
    from gym import Space, spaces, logger
ImportError: cannot import name spaces`

**Comment by zach-nervana** [comment]
I am having the same problem. Downgrading to 0.9.5 fixes the problem for me

**Comment by simontudo** [comment]
This PR solved the issue for me: https://github.com/openai/gym/pull/851

**Comment by Yizhe1208** [comment]
degrade is a nice sultion

**Comment by aglavers** [comment]
Downgrade to 0.9.5 fixes for me as well.

**Comment by paul-cb** [comment]
I am getting this problem as well. I have gym 0.10.9 and want to downgrade this package. How do you downgrade to 0.9.5 or 0.9.2?

**Comment by RenzoM157** [comment]
After downgrading to 0.9.5 I get this message
 from ppaquette_gym_doom.wrappers.action_space import ToDiscrete
ModuleNotFoundError: No module named 'ppaquette_gym_doom'

Anyone have a solution to this error?
