### ISSUE TITLE
AttributeError: 'Box' object has no attribute 'n'

### ISSUE THREAD

**Issue by MyAusweis** [openai/gym#839]
Dear All, 

Why AttributeError: 'Box' object has no attribute 'n' shown after i run  
"   Q = np.zeros([env.observation_space.n, env.action_space.n])"

i use windows 8.1 64 bit, i also tried in linux, but the result is same. 

can anybody help me to solve this ?

Here the complete program

import gym
import numpy as np

env  = gym.make('CartPole-v1')

Q = np.zeros([env.observation_space.n, env.action_space.n])

hitungreward=0
alpha = 0.618

for _ in range(20):
    state = env.reset()
    for t in range(1000):
        env.render()
        print(state)
        action = env.action_space.sample()
        state, reward, done, info = env.step(action)
        Q[state,action] += alpha * (reward + np.max(Q[state]) - Q[state,action])
        hitungreward+=1
        if done:
            print("Episode finished after {} timesteps".format(t+1))
            break
        
print ("Hitungan : ",hitungreward)

**Comment by FirefoxMetzger** [comment]
It is not valid for a continous space of type `Box` to have a finite number of elements `n`, thus the property doesn't exist.

If you want discrete values for the observation space, you will have to implement a way to quantize the space into something discrete.

**Comment by houseofwealth** [comment]
to expand a bit on FirefoxMetzger's reply, you need to make sure your environment is of a discrete type and not a continuous one. The gym contains a probabalistic discrete environment called DiscreteEnv in gym/envs/toy_text/discrete.py which uses a Discrete space. For an example of its use look at Taxi in the same directory. That will set the observation_space's n value correctly. There is also a multi-dimensional discrete space in gym/spaces if your space is multi-dimensional. However that seems to be missing the statement where the state space size is saved away in "n" so you'll have to add that yourself in its constructor, something like  `self.n = np.prod(nvec+1)` ought to do it.

**Comment by christopherhesse** [comment]
Thanks for answering this @FirefoxMetzger and @houseofwealth !

**Comment by alperensayar** [comment]
u can use env.observation_space.shape[0]
