### ISSUE TITLE
ImportError when installing on Mac

### ISSUE THREAD

**Issue by HenryZhou7** [openai/gym#840]
I am trying to run the command `pip install gym[all]` to install the package.
But it seems to have import error.
```
Collecting mujoco-py>=1.50; extra == "all" (from gym[all])
  Using cached mujoco-py-1.50.1.34.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/wk/ppqw97nn4zv467mnrpgp_4f00000gn/T/pip-build-TllN6p/mujoco-py/setup.py", line 2, in <module>
        import importlib.util
    ImportError: No module named util
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/wk/ppqw97nn4zv467mnrpgp_4f00000gn/T/pip-build-TllN6p/mujoco-py/
```
I have a registed mujoco license and can successfully run './simulate' under `~/.mujoco/mjpro150/bin/`. This error keeps failing when I try to install openai gym and mujoco_py.

Thanks in advance!

**Comment by Yizhe1208** [comment]
have u solved the problem？ same problem as u

**Comment by HenryZhou7** [comment]
I set up a Python 3.6 environment and it is solved.

**Comment by Austinzhenghua** [comment]
I have the same problem with u, how did you do that?

**Comment by Austinzhenghua** [comment]
Using cached mujoco-py-1.50.1.34.tar.gz 
I stopped here

**Comment by abheek96** [comment]
It won't process further unless you have a Mujoco license which costs around 500$ after its 30-day trial period

**Comment by HenryZhou7** [comment]
@Austinzhenghua Set up another conda environment using Python 3. The importlib in Python 2 doesn't seem to be compatible with the package.

**Comment by christopherhesse** [comment]
It looks like the original poster solved their issue, if there are other issues installing mujoco-py, please file them on that repo: https://github.com/openai/mujoco-py/issues
