### ISSUE TITLE
import: unable to open image `gym': Is a directory @ error/blob.c/OpenBlob/2712.

### ISSUE THREAD

**Issue by Backslash777** [openai/gym#842]
Prior to writing this question i reinstalled gym and ubuntu several times and followed different guides as to how to set up but I always run into this brick wall! When I type "import gym" my cursor changes to a plus symbol and any interaction brings the message "import: unable to open image `gym': Is a directory @ error/blob.c/OpenBlob/2712."
If I leave the PC then nothing happens. Very grateful for any help I can get on this.

**Comment by YuYangguang** [comment]
I also met this issue. Could anyone help solve this problem?

**Comment by balisujohn** [comment]
I had this issue and managed to fix it by calling my program from the command line as:
`    python ./myprogram.py`
Instead of 
`./myprogramn.py`

Hope this helps.

**Comment by christopherhesse** [comment]
It sounds like you're running the `ImageMagick` tool `import` instead of running python on your script.  @balisujohn's answer is probably correct.
