### ISSUE TITLE
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

### ISSUE THREAD

**Issue by lin-limin** [openai/gym#848]
something wrong when I use the command "pip3 install 'gym[all]'".What Should I do?Thank you very much.
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-gd1trgd7/mujoco-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-9vrzer4o-record/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-build-gd1trgd7/mujoco-py/

**Comment by christopherhesse** [comment]
This looks like a issue with `mujoco-py`, please file the issue there: https://github.com/openai/mujoco-py/issues
