### ISSUE TITLE
Python 3.5 incompatibility: no attribute 'itervalues'

### ISSUE THREAD

**Issue by bartkamphorst** [openai/gym#85]
Hi there,

I was trying to run a code snippet [from the docs](https://gym.openai.com/docs) when I ran into what seems to be a compatibility issue. For completeness, here's the snippet:
```python
import gym
env = gym.make('CartPole-v0')
env.reset()
for _ in xrange(1000):
    env.render()
    env.step(env.action_space.sample()) # take a random action
```
And here's the error I'm getting.
```
$ /opt/local/bin/python3.5 demo.py 
Traceback (most recent call last):
  File "demo.py", line 1, in <module>
    import gym
  File "/Users/bart/Documents/Programming/Python/gym/gym/__init__.py", line 47, in <module>
    from gym.scoreboard.api import upload
  File "/Users/bart/Documents/Programming/Python/gym/gym/scoreboard/__init__.py", line 562, in <module>
    registry.finalize()
  File "/Users/bart/Documents/Programming/Python/gym/gym/scoreboard/registration.py", line 41, in finalize
    registered_ids = set(env_id for group in self.groups.itervalues() for env_id in group['envs'])
AttributeError: 'collections.OrderedDict' object has no attribute 'itervalues'
```
As Python 3 support is experimental and you requested bug reports, I thought I'd let you know about this one.

**Comment by adelq** [comment]
Fixed by 6bb2d56266ae6679c2fb2336b31769a4133400d7 and 94eb492b993a55e3027c99af928a42659e4466ff

**Comment by bartkamphorst** [comment]
@jonasschneider @adelq Thanks for working on this. The original issue is indeed resolved. With your changes I got the example working, but not before I encountered two more minor issues.
1. I needed to import xrange in my snippet (`from six.moves import xrange`).
2. I had to install `pyglet` through pip (even though I ran `pip install -e .` for the minimal install).
Both of these issues are not strictly connected to the bug report, but rather to getting up and running quickly by following the docs. Do you prefer that I open a new ticket for these issues?

**Comment by gdb** [comment]
1. I've changed our doc examples to be `range` rather than `xrange` on the site.
2. It's expected that you'll have to install `pyglet` on your own, if you just do the minimal install! (Minimal install truly is pretty minimal.)

**Comment by bartkamphorst** [comment]
Thanks @gdb .

> It's expected that you'll have to install pyglet on your own

I guess our expectations don't match here. For I would expect that doing a minimal install from the "Getting Started" section (`pip install -e .`) would allow me to run the "bare minimum example of getting something running" from the "Running an environment" section. I don't think it's very encouraging if running the very first example fails on a missing dependency. Of course the docs have a general note about missing dependencies a little further down, but generally I want my getting started guides to do a little more handholding for a smooth first experience.

In any case, thanks everyone for resolving this issue so quickly!

**Comment by gdb** [comment]
That's a compelling argument. There used to be much better reasons not to require the rendering dependencies, and I hadn't properly rechecked my assumptions. Added `pyglet` to the base dependencies!

**Comment by bartkamphorst** [comment]
👍 Thanks!
