### ISSUE TITLE
Unable to import gym on Python 2.7, ImportError: cannot import name spaces.

### ISSUE THREAD

**Issue by robertnishihara** [openai/gym#850]
```
> python --version
Python 2.7.13 :: Anaconda 4.3.1 (x86_64)
```

I did `pip install -U gym` to get `0.9.6`.

```python
>>> import gym
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rkn/anaconda2/lib/python2.7/site-packages/gym/__init__.py", line 12, in <module>
    from gym import wrappers, spaces, logger
  File "/Users/rkn/anaconda2/lib/python2.7/site-packages/gym/spaces/__init__.py", line 1, in <module>
    from gym.spaces.box import Box
  File "/Users/rkn/anaconda2/lib/python2.7/site-packages/gym/spaces/box.py", line 2, in <module>
    from gym import Space, spaces, logger
ImportError: cannot import name spaces
```

**Comment by robertnishihara** [comment]
Related to #838, but that issue pre-dates `0.9.6` so is likely a different problem.

**Comment by pcmoritz** [comment]
It seems to be a recursive import problem with Python 2. If I replace the __init__.py by the following, it seems to work for me:

```
import distutils.version
import os
import sys
import warnings

from gym.utils import reraise
from gym.version import VERSION as __version__

from gym.core import Env, Space, Wrapper, ObservationWrapper, ActionWrapper, RewardWrapper
from gym.envs import make, spec
from gym import wrappers, logger

spaces = None
import gym.spaces
from gym import spaces

def undo_logger_setup():
    warnings.warn("gym.undo_logger_setup is deprecated. gym no longer modifies the global logging configuration")

__all__ = ["Env", "Space", "Wrapper", "make", "spec", "wrappers"]
```

Note I removed the from gym import spaces from above and then first import gym.spaces with gym.spaces set to None and then set gym.spaces to the proper variable.

This might break other things tough, so not sure if it's the right fix.

**Comment by robertnishihara** [comment]
The problem I mentioned doesn't seem to be reproducible on @pcmoritz's laptop (he has a different problem), so there may be something strange about my setup.

**Comment by robertnishihara** [comment]
I was doing something wrong, updated the issue description to reflect that.

**Comment by pcmoritz** [comment]
here is the diff: https://github.com/openai/gym/pull/851

**Comment by frostburn** [comment]
Same problem here.

**Comment by joschu** [comment]
Fixed

**Comment by fi000** [comment]
I encountered the same problem in python 3.5.6 Would you please explain how you solved it?

**Comment by joschu** [comment]
@fi000 could you post your stack trace?

**Comment by fi000** [comment]
Dear John,

Would you please let me know how I ca post stack trace?

Best

**Comment by robertnishihara** [comment]
Please copy and paste the error message that you see when you do `import gym`.

**Comment by fi000** [comment]
Hi
I used it for this repository: https://github.com/xenu256/stock_market_reinforcement_learning

When I run, I encounter a problem in gym:
(I clone the latest version of gym but I did not apply the last comment of 2018-01-25) 

stock_market_reinforcement_learning-master>python dqn.py portfolio.csv model
Using TensorFlow backend.
[33mWARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.[0m
Traceback (most recent call last):
  File "dqn.py", line 88, in <module>
    sudden_death=-1.0)
  File "C:\Users\fi\Desktop\rl\code\3.6\stock_market_reinforcement_learning-master\environment.py", line 43, in __init__
    self.reset()
  File "C:\Users\fi\Anaconda30\envs\tensorflow\lib\site-packages\gym\core.py", line 70, in reset
    raise NotImplementedError
NotImplementedError

**Comment by XBITSwitzerland** [comment]
@fi000 

Hello I get the same error:

[33mWARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.

Did you fix it?
