### ISSUE TITLE
Box2d particles randomly changing direction

### ISSUE THREAD

**Issue by tensor8** [openai/gym#852]
I'm creating a new Box2d env, working off of the lunar lander environment. The problem I'm having is that dynamic bodies in free motion never move straight in space, but jump around as if being hit by invisible particles.

I'm rendering every object I create, so not sure what's going on.

@olegklimov is there some gotcha here that you've come across as well?

**Comment by olegklimov** [comment]
Er... I'm no specialist in Box2d. Check your numerical scale for instance, it depends a lot on scale of numbers.

**Comment by tensor8** [comment]
Fixed it: didn't solve problem at root, ended up reimplementing a new whitelisted collision detector which seems to work fine.
