### ISSUE TITLE
BrokenPipeError [Errno 32] Broken pipe----help help me

### ISSUE THREAD

**Issue by reaIws** [openai/gym#855]
anaconda:3.4.2
python:    3.5
OS: slse 12.3

this error from "gym/wrappers/monitoring/vider_recorder.py"
self.proc.stdin.write(frame.tobytes())

what can i do,thx

**Comment by hzyjerry** [comment]
I have the same problem.

**Comment by hzyjerry** [comment]
I found out the reason for my case: I used `get_image` implementation from #841, and `gl.glReadPixels` doesn't seem to like it when `width` or `height` argument is an odd number. So I manually added:
`width = 1024
height = 1024`
This solves my problem for now, unless I run into something else later.

**Comment by OlofHarrysson** [comment]
I fixed the problem by installing avconv/libav. I'm running OSX though and installed it with `brew install libav`

In the video recorder there is a section that says
```python
if distutils.spawn.find_executable('avconv') is not None:
    self.backend = 'avconv'
elif distutils.spawn.find_executable('ffmpeg') is not None:
    self.backend = 'ffmpeg'
```

**Comment by reaIws** [comment]
finally i use ubuntu
