### ISSUE TITLE
Could reraise logic be simplified with six.raise_from() or six.reraise()?

### ISSUE THREAD

**Issue by cclauss** [openai/gym#859]
Would it be possible to leverage [six.raise_from() or six.reraise()](https://pythonhosted.org/six/#six.raise_from) to simplify
* https://github.com/openai/gym/blob/master/gym/utils/reraise.py +
* https://github.com/openai/gym/blob/master/gym/utils/reraise_impl_py2.py +
* https://github.com/openai/gym/blob/master/gym/utils/reraise_impl_py3.py ?

**Comment by pzhokhov** [comment]
closing per discussion in https://github.com/openai/gym/pull/906
