### ISSUE TITLE
Migration to mujoco-py 1.50

### ISSUE THREAD

**Issue by HenryZhou7** [openai/gym#861]
I just updated mujoco-py version.

Before the `geom_size` attribute can be set through an assignment statement.

However, after the upgrade. 
```
(Pdb) self.model.geom_size = temp
*** AttributeError: attribute 'geom_size' of 'mujoco_py.cymj.PyMjModel' objects is not writable
(Pdb) self.model.__setattr__('geom_size', temp)
*** AttributeError: attribute 'geom_size' of 'mujoco_py.cymj.PyMjModel' objects is not writable
```

How should I solve this problem? Thanks in advance!

**Comment by jeasinema** [comment]
Encounter the same issue here. Wait for a solution.

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
