### ISSUE TITLE
Where's TabularQ agent?

### ISSUE THREAD

**Issue by houseofwealth** [openai/gym#865]
The md says "Agent implementing tabular Q-learning located in this repo at gym/examples/agents/tabular_q_agent.py" but I don't see it - I just did a clone of the repository (main branch) yesterday. I didn't do a full install because I'm not currently interested in all the other environments - is that what I need here?

**Comment by FirefoxMetzger** [comment]
The agent has been removed in #836 and the readme is outdated. The random agent is still there and might give you a place to start.

Anything particular about that environment that you need?

**Comment by houseofwealth** [comment]
Oh nothing specific, I can implement it myself but if it were already there that's one less piece of code i have to write and debug..
PS. I meant the agents.md in the docs folder still mentions tabular Q learning

**Comment by FirefoxMetzger** [comment]
Okay =) 
Just as a heads up: If you use a spaces `.sample()` method make sure to set the space's random seed. It's not attached to the environment and can cause funny, unexpected results (e.g. two consecutive runs with the same env.seed() will produce different results).
It's set [here](https://github.com/openai/gym/blob/3c8a68a0b4b291791b02544d6a1b54ab20bd0354/gym/spaces/prng.py#L20)
