### ISSUE TITLE
Is discrete.py broken?

### ISSUE THREAD

**Issue by watts4speed** [openai/gym#867]
Here's a fix that worked for me.  Please let me know if this is not the right way to fix it.

The context is I'm trying to get openai/multiagent-particle-envs working.  I'm am not certain the exact nature of the problem so caution should be taken by anyone looking at my gist.

https://gist.github.com/watts4speed/ae1727310c54b248e078c7ff8cd6614d

**Comment by watts4speed** [comment]
I got things working.  I'm going to submit a pr for openai/multiagent-particle-envs if I can find the time to check what I did closer to make sure it makes sense.  I had to back up to gym-v0.95 also.  The code for openai/multiagent-particle-envs is a bit behind now.  I can't check with the current HEAD until later and I don't want to confuse things there either.

**Comment by christopherhesse** [comment]
It's likely that repo requires a specific version of gym, please file the issue on that repo, thanks!
