### ISSUE TITLE
Inverted double pendulum state vector meaning?

### ISSUE THREAD

**Issue by juancamilog** [openai/gym#87]
What does each state dimension represent on the inverted double pendulum environment? I was expecting to get the cart position/velocity plus the angles/angular velocities of each joint. That would give 6 state variables, but the state vector returned by gym has 11 dimensions.

**Comment by tlbtlbtlb** [comment]
Ideally, you should develop agents that don't need to know what the observation represents. 

That said, the observation vector consists of, in order:
  - linear position
  - sin of 2 joint angles
  - cos of 2 joint angles
  - velocities of position + 2 joint angles (3 terms)
  - constraint forces on position + 2 joint angles (3 terms)

It's defined in _get_obs here: https://github.com/openai/gym/blob/master/gym/envs/mujoco/inverted_double_pendulum.py

**Comment by jonasschneider** [comment]
Closing this for now. We're happy to answer any further questions though! Asking in chat (https://gitter.im/openai/gym) might also give even faster answers :)

**Comment by zhuyuanyang** [comment]
What does each state dimension represent on the inverted  pendulum environment?
