### ISSUE TITLE
GLFW error in SSH server

### ISSUE THREAD

**Issue by AntonioSerrano** [openai/gym#879]
I am trying to run Open AI Gym with MuJoCo 1.31 in a server via **-X -Y ssh**. The machine has Ubuntu 16.04 and CUDA 8 installed and goes with a Nvidia Titan. However, I got the following error related to OpenGL/Mesa. In particular, with the GLFW library:

`GLFW error: 65537, desc: b'The GLFW library is not initialized'`

Any clue? Thx.

**Comment by amanjhunjhunwala** [comment]
+1 same problem

**Comment by nke001** [comment]
+1. Anyone solved this issue?

**Comment by christopherhesse** [comment]
This sounds similar to https://github.com/openai/gym/issues/366 does running an OpenGL accelerated X server fix the issue?

**Comment by AntonioSerrano** [comment]
Dear cute bot. Do not close it. It remains unsolved and someone could give us a useful answer. Thanks

**Comment by swagatk** [comment]
On the ssh client terminal use fake screen to remove the glfw error. 

`$ xvfb-run -a -s "-screen 0 1400x900x24" python dmc_test.py
`

`dmc_test.py` uses mujoco environment and hence throws up GLFW initialization error when accessed through SSH.  The above command solves this error.

if the package `xvfb` is not installed, use the following command to install: 
`sudo apt install xvfb`
