### ISSUE TITLE
Playing an arbitrary game (i.e. fortnite) without special interfaces

### ISSUE THREAD

**Issue by dlazares** [openai/gym#882]
I've been looking at the openai gym and universe docs quite a bit in order to build a RL-agent that can play the game Fortnite.

I took a look at other repos that play desktop games such as minecraft and noticed that all of them use specific interfaces for each game and I'm wondering why there is not a more general method to start any arbitrary game and make a RL agent that can play it. I thought that universe was created to solve this problem, but I could not find any docs that showed an easy way to accomplish the task of playing an arbitrary desktop game.

I understand that there are numerous complexities in startup procedures for each game i.e. logging in, starting the game, etc..., but I'm surprised at how complex this seems for each game and I'm wondering if anyone has found a way to simplify this workflow.

**Comment by W1-PopelierE** [comment]
want this too
