### ISSUE TITLE
Wrong get_keys_to_action for Atari games

### ISSUE THREAD

**Issue by rubenvereecken** [openai/gym#886]
I just came across `env.unwrapped.get_action_meanings` after finding out gym does not just support all ALE actions in any game. It goes hand in hand with `env.unwrapped.get_keys_to_action()` which maps keyboard key tuples to an action index. Except, the dictionary it returns is wrong.

Consider for Montezuma's Revenge for example:

```python
env = gym.envs.make('MontezumaRevenge-v4')
env.unwrapped.get_keys_to_action()

{(): 0,
 (32,): 1,
 (32, 97): 12,
 (32, 97, 115): 17,
 (32, 97, 119): 15,
 (32, 100): 11,
 (32, 100, 115): 16,
 (32, 100, 119): 14,
 (32, 115): 13,
 (32, 119): 10,
 (97,): 4,
 (97, 115): 9,
 (97, 119): 7,
 (100,): 3,
 (100, 115): 8,
 (100, 119): 6,
 (115,): 5,
 (119,): 2}
```

You can vaguely make out from this snippet that the keys `97`, `100`, `115`, and `119` together should make up the arrow keys, and `32` the space bar. It got the space bar right but the left, top, right and down arrow keys respectively, on my system, are 81, 82, 83, and 84, all offset by `0xff00` (so left is actually `0xff00 + 81`). This is tested with the default renderer and the `env.unwrapped.viewer.window.on_key_press` callback.
I can work around this but it seems a shame as this dictionary is exactly what I needed.

**Comment by EliasHasle** [comment]
Is it really supposed to return key codes for your computer's keyboard, not for some array based on an Atari interface?

**Comment by rubenvereecken** [comment]
You know, I haven't found a 'reference array' of sorts anywhere yet, but I no longer believe this is a very valid issue. I don't even remember where I got those key values from on my own system when I wrote that issue, teaches me right. Let's just put this to rest.

**Comment by Remosy** [comment]
I found a keyboard mapping: [ref](https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&cad=rja&uact=8&ved=2ahUKEwiQluOhy-XgAhUSA3IKHfMDCV0Qjhx6BAgBEAM&url=https%3A%2F%2Fstackoverflow.com%2Fquestions%2F43294629%2Fkey-42-usb-hid-codes&psig=AOvVaw2do-A3p4jcFF2p__QgQTaI&ust=1551689178231922)

**Comment by Remosy** [comment]
The numbers are ASCII codes in DEC format, not keyboard mapping coordinates.
[REF](https://www.google.com/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=2ahUKEwjovNPJxungAhXLSH0KHRO1AEkQjRx6BAgBEAU&url=https%3A%2F%2Ftheasciicode.com.ar%2F&psig=AOvVaw3HgpZ6PLaumaaGGQpF_YZE&ust=1551825475340698)
```
{(): 0, 
 (32,): 1, //ESC
 (32, 97): 12, //ESC, A
 (32, 97, 115): 17, //ESC, A, S
 (32, 97, 119): 15, //ESC, A, W
 (32, 100): 11, //ESC, D
 (32, 100, 115): 16, //ESC, D, S
 (32, 100, 119): 14, //ESC, D, W
 (32, 115): 13, //ESC, S
 (32, 119): 10, //ESC, W
 (97,): 4, //A
 (97, 115): 9, //A, S
 (97, 119): 7, //A, W
 (100,): 3, //D
 (100, 115): 8, //D, S
 (100, 119): 6, //D, W
 (115,): 5, //S
 (119,): 2 //W
}
```
