### ISSUE TITLE
NotImplementedError: abstract Running on a head-less server

### ISSUE THREAD

**Issue by jamsawamsa** [openai/gym#890]
Hi all,

I'm trying to run a simple gym example from https://gym.openai.com/docs/. I'm running it on the Google Compute Engine, with jupyter notebook. Code's here:
`import gym`
`env = gym.make('CartPole-v0')`
`env.reset()`
`for _ in range(1000):`
    `env.render()`
    `env.step(env.action_space.sample()) # take a random action`

This is the error message I got. I assume it's got something to do pyglet, and not having a screen. But I ran my jupyter notebook with the following command: 
`xvfb-run -s "-screen 0 1400x900x24" jupyter notebook`
which is supposed to enable running in a server environment.

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
-----------------------------------------------------------------------
NotImplementedError                   Traceback (most recent call last)
<ipython-input-3-c13d11cabe05> in <module>()
      3 env.reset()
      4 for _ in range(1000):
----> 5     env.render()
      6     env.step(env.action_space.sample()) # take a random action

~/pytorch/gym/gym/core.py in render(self, mode)
    241 
    242     def render(self, mode='human'):
--> 243         return self.env.render(mode)
    244 
    245     def close(self):

~/pytorch/gym/gym/envs/classic_control/cartpole.py in render(self, mode)
    105         if self.viewer is None:
    106             from gym.envs.classic_control import rendering
--> 107             self.viewer = rendering.Viewer(screen_width, screen_height)
    108             l,r,t,b = -cartwidth/2, cartwidth/2, cartheight/2, -cartheight/2
    109             axleoffset =cartheight/4.0

~/pytorch/gym/gym/envs/classic_control/rendering.py in __init__(self, width, height, display)
     49         self.width = width
     50         self.height = height
---> 51         self.window = pyglet.window.Window(width=width, height=height, display=display)
     52         self.window.on_close = self.window_closed_by_user
     53         self.isopen = True

~/anaconda3/envs/py35/lib/python3.5/site-packages/pyglet/window/__init__.py in __init__(self, width, height, caption, resizable, style, fullscreen, visible, vsync, display, screen, config, context, mode)
    502 
    503         if not screen:
--> 504             screen = display.get_default_screen()
    505 
    506         if not config:

~/anaconda3/envs/py35/lib/python3.5/site-packages/pyglet/canvas/base.py in get_default_screen(self)
     71         :rtype: :class:`Screen`
     72         '''
---> 73         return self.get_screens()[0]
     74 
     75     def get_windows(self):

~/anaconda3/envs/py35/lib/python3.5/site-packages/pyglet/canvas/base.py in get_screens(self)
     63         :rtype: list of :class:`Screen`
     64         '''
---> 65         raise NotImplementedError('abstract')
     66 
     67     def get_default_screen(self):

NotImplementedError: abstract

Any help's greatly appreciated

**Comment by techniquark** [comment]
Definitely an issue with running Gym on Jupyter Notebook. Tried it and got hit with the very same error. The code works fine though when I try running it as a separate Python script on a GUI-based system. The terminal shows a warning in yellow, but a window with the game opens up anyway.
![selection_019](https://user-images.githubusercontent.com/16492682/36635492-8f2f2a52-1994-11e8-80db-23d3ad007a35.png)
![selection_018](https://user-images.githubusercontent.com/16492682/36635494-93456f02-1994-11e8-8a70-b7d3f8ef6075.png)

**Comment by amartya-k** [comment]
Having the same issue.

**Comment by christopherhesse** [comment]
I just ran the provided example on a linux machine and it worked, so if there was some bug in jupyter notebook that caused that.  I'm using version `6.0.0`, please file a new issue if this is still a problem.
