### ISSUE TITLE
How to solve environment error in open-ai-gym?

### ISSUE THREAD

**Issue by avitheavi** [openai/gym#896]
I am using gym version - '0.9.7', and mujoco_py version 1.50.1.41, Python 3.6.1 |Anaconda 4.4.0, installed on a mac.

When trying:

    import gym
    env = gym.make('Humanoid-v1')

I am getting the following error:

    Traceback (most recent call last):
        File "/Users/usr/gym/gym/envs/registration.py", line 139, in spec
        return self.env_specs[id]
    KeyError: 'Humanoid-v1'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/Users/usr/gym/gym/envs/registration.py", line 163, in make
        return registry.make(id)
      File "/Users/usr/gym/gym/envs/registration.py", line 118, in make
        spec = self.spec(id)
      File "/Users/usr/gym/gym/envs/registration.py", line 147, in spec
        raise error.DeprecatedEnv('Env {} not found (valid versions include {})'.format(id, matching_envs))
    gym.error.DeprecatedEnv: Env Humanoid-v1 not found (valid versions include ['Humanoid-v2'])

I have tried looking for solutions online with no success.

**Comment by Sicelukwanda** [comment]
It says you should try:
```
import gym
env = gym.make('Humanoid-v2')
```

**Comment by christopherhesse** [comment]
Thanks for answering this @Sicelukwanda!

**Comment by sabiinsearch** [comment]
Thanks for the hint ... 
same problem using Taxi-v2...
but i tried and replaced with v3 and it compiled without errror

**Comment by Adeiltoo** [comment]
thank you so much (sabiinsearch) I got it! :from  Brasil

**Comment by dhruvpunetha** [comment]
> Thanks for the hint ...
> same problem using Taxi-v2...
> but i tried and replaced with v3 and it compiled without errror

thank you mate

**Comment by TamerZah** [comment]
Thanks it worked with me using v3
env = gym.make('Taxi-v3')
many thanks.
