### ISSUE TITLE
Tricky Observation Space

### ISSUE THREAD

**Issue by scottazord** [openai/gym#904]
Hey guys,

Does there exist a way to replicate the below observation space in the current gym spaces.

(2, [(2,3,4),(3,2,1),(3,1,3)]

So far i've got:

        self.observation_space = spaces.Tuple((spaces.Discrete(inf),
                                               spaces.Box(low=-1, high=inf, shape=game_dimensions)))

However i don't think i can use Box, as it doesn't support tuples as values.

What alternative could i use?

**Comment by christopherhesse** [comment]
I would just use a `Dict` space and name the keys whatever you want, e.g. `'0', '1.0.1` if you really want it to be close to your example.
