### ISSUE TITLE
CartPole equation error

### ISSUE THREAD

**Issue by jmcomby** [openai/gym#907]
If you apply no force to the cart, the current equation is not correct.
`import gym`
`import math`
`env = gym.make('CartPole-v0')`
`env.reset()`
`env.env.force_mag = 0 // Set force to 0`
`env.env.state[0] = 0`
`env.env.state[1] = 0`
`env.env.state[2] = math.pi/2`
`env.env.state[3] = 0`
`env.env.masscart = 100`
`env.env.total_mass = env.env.masscart+env.env.masspole`
`for _ in range(1000):`
`    env.render()`
`    env.step(0) # force = 0`
Look the result of this code on youtube:
[https://youtu.be/7WkgMbKUpsY](https://youtu.be/7WkgMbKUpsY)

Actually the correction is very easy. In cartpole.py (v.0.9.7), function step
`...`
`x  = x + self.tau * x_dot`
`x_dot = x_dot + self.tau * xacc`
`theta = theta + self.tau * theta_dot`
`theta_dot = theta_dot + self.tau * thetaacc`
`...`
The order is not correct. Reorder like this:
`x_dot = x_dot + self.tau * xacc`
`x  = x + self.tau * x_dot`
`theta_dot = theta_dot + self.tau * thetaacc`
`theta = theta + self.tau * theta_dot`
And now you get:
[https://youtu.be/x8ixYi78I_w](https://youtu.be/x8ixYi78I_w)

**Comment by sritee** [comment]
Looks like Rich Sutton's code has the x first then x_dot first as well. Are you sure this is a mistake, if so wonder why there hasn't been much response.

**Comment by skinnersBoxy** [comment]
The 'mistake' is present all the time, it's just only obvious in certain circumstances.

**Comment by christopherhesse** [comment]
This environment is meant to be the cartpole environment from G Barto, RS Sutton and CW Anderson, "Neuronlike Adaptive Elements That Can Solve Difficult Learning Control Problem", IEEE Transactions on Systems, Man, and Cybernetics, 1983.  Is this error present in the original environment?

**Comment by jmcomby** [comment]
[david78k](https://github.com/david78k/pendulum/blob/master/c/anderson/poledriver.c) translated parts from FORTRAN to C of the orginally code of Rich Sutton and Chuck Anderson. With only gravity, we have the same problem. I [convert C to python](https://github.com/jmcomby/cartpoleopenai/blob/master/CartPole.ipynb).
I'm not sure if this little change can have other impact with different initial variable or use case.
