### ISSUE TITLE
bitflip environment from HER paper

### ISSUE THREAD

**Issue by zach-nervana** [openai/gym#913]
I have the bitflip environment from the Hindsight Experience Replay paper implemented in its own repo at the moment.  Would a pull request which adds this environment to gym be merged?

https://github.com/NervanaSystems/gym-bit-flip

**Comment by zach-nervana** [comment]
Good point.  Mine currently provides `state` and `goal` in the observation space.  I could rename them to be `observation` and `desired_goal` and add in an `achieved_goal` as well if that would be helpful.

**Comment by christopherhesse** [comment]
We'd accept a PR to add it to the environments list here: https://github.com/openai/gym/blob/master/docs/environments.md

You can now use `gym.make` with external environments too, so it's easier to use through the normal gym API.

**Comment by christopherhesse** [comment]
Going to close this issue, but please make a PR to add it to the list if you are interested.
