### ISSUE TITLE
gym version 0.10.2 install from pypi is broken

### ISSUE THREAD

**Issue by zach-nervana** [openai/gym#914]
The error I get is: `error: can't copy 'gym/envs/robotics/assets/hand': doesn't exist or not a regular file`

**Comment by lshamis** [comment]
I'm getting the same issue from `pip install gym`.

Reproducible example:
`docker run --rm -it ubuntu:xenial /bin/bash -c 'apt update && apt install -y python-pip && pip install gym'`

**Comment by matthiasplappert** [comment]
Thanks for reporting this. The issue has been fixed (it was Linux-specific) and Gym `0.10.3` has been uploaded to PyPI.
