### ISSUE TITLE
Running setup.py install for mujoco-py ... error

### ISSUE THREAD

**Issue by sbyNiceBlowJob** [openai/gym#915]
Running setup.py install for mujoco-py ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-i9jpp4r9/mujoco-py/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-mg8m1689-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    Compiling /tmp/pip-build-i9jpp4r9/mujoco-py/mujoco_py/cymj.pyx because it changed.
    [1/1] Cythonizing /tmp/pip-build-i9jpp4r9/mujoco-py/mujoco_py/cymj.pyx
    running build_ext
    building 'mujoco_py.cymj' extension
    creating /tmp/pip-build-i9jpp4r9/mujoco-py/mujoco_py/generated/_pyxbld_LinuxExtensionBuilder
    creating /tmp/pip-build-i9jpp4r9/mujoco-py/mujoco_py/generated/_pyxbld_LinuxExtensionBuilder/temp.linux-x86_64-3.5
    creating /tmp/pip-build-i9jpp4r9/mujoco-py/mujoco_py/generated/_pyxbld_LinuxExtensionBuilder/temp.linux-x86_64-3.5/tmp
    creating /tmp/pip-build-i9jpp4r9/mujoco-py/mujoco_py/generated/_pyxbld_LinuxExtensionBuilder/temp.linux-x86_64-3.5/tmp/pip-build-i9jpp4r9
    creating /tmp/pip-build-i9jpp4r9/mujoco-py/mujoco_py/generated/_pyxbld_LinuxExtensionBuilder/temp.linux-x86_64-3.5/tmp/pip-build-i9jpp4r9/mujoco-py
    creating /tmp/pip-build-i9jpp4r9/mujoco-py/mujoco_py/generated/_pyxbld_LinuxExtensionBuilder/temp.linux-x86_64-3.5/tmp/pip-build-i9jpp4r9/mujoco-py/mujoco_py
    creating /tmp/pip-build-i9jpp4r9/mujoco-py/mujoco_py/generated/_pyxbld_LinuxExtensionBuilder/temp.linux-x86_64-3.5/tmp/pip-build-i9jpp4r9/mujoco-py/mujoco_py/gl
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Imujoco_py -I/tmp/pip-build-i9jpp4r9/mujoco-py/mujoco_py -I/home/user/.mujoco/mjpro150/include -I/home/user/.local/lib/python3.5/site-packages/numpy/core/include -I/tmp/pip-build-i9jpp4r9/mujoco-py/mujoco_py/vendor/egl -I/usr/include/python3.5m -c /tmp/pip-build-i9jpp4r9/mujoco-py/mujoco_py/cymj.c -o /tmp/pip-build-i9jpp4r9/mujoco-py/mujoco_py/generated/_pyxbld_LinuxExtensionBuilder/temp.linux-x86_64-3.5/tmp/pip-build-i9jpp4r9/mujoco-py/mujoco_py/cymj.o -fopenmp -w
    /tmp/pip-build-i9jpp4r9/mujoco-py/mujoco_py/cymj.c:568:21: fatal error: mjmodel.h: No such file or directory
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
  Rolling back uninstall of mujoco-py
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-i9jpp4r9/mujoco-py/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-mg8m1689-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-i9jpp4r9/mujoco-py/

Does anyone have any idea about this?

**Comment by matthiasplappert** [comment]
Did you follow the installation instructions for mujoco-py? https://github.com/openai/mujoco-py/blob/master/README.md

**Comment by sbyNiceBlowJob** [comment]
I used sudo, and it's okay now. Thanks a lot!

**Comment by Ja1r0** [comment]
But I still have the simillar error.Does anyone can help me?
The directory '/home/yang/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/yang/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting mujoco-py<1.50.2,>=1.50.1
  Downloading mujoco-py-1.50.1.41.tar.gz (115kB)
    100% |████████████████████████████████| 122kB 247kB/s 
Requirement already up-to-date: glfw>=1.4.0 in /home/yang/.local/lib/python3.6/site-packages (from mujoco-py<1.50.2,>=1.50.1)
Requirement already up-to-date: numpy>=1.11 in /home/yang/.local/lib/python3.6/site-packages (from mujoco-py<1.50.2,>=1.50.1)
Requirement already up-to-date: Cython>=0.27.2 in /home/yang/.local/lib/python3.6/site-packages (from mujoco-py<1.50.2,>=1.50.1)
Requirement already up-to-date: imageio>=2.1.2 in /home/yang/.local/lib/python3.6/site-packages (from mujoco-py<1.50.2,>=1.50.1)
Requirement already up-to-date: cffi>=1.10 in /home/yang/.local/lib/python3.6/site-packages (from mujoco-py<1.50.2,>=1.50.1)
Requirement already up-to-date: pillow in /home/yang/.local/lib/python3.6/site-packages (from imageio>=2.1.2->mujoco-py<1.50.2,>=1.50.1)
Requirement already up-to-date: pycparser in /home/yang/.local/lib/python3.6/site-packages (from cffi>=1.10->mujoco-py<1.50.2,>=1.50.1)
Installing collected packages: mujoco-py
  Running setup.py install for mujoco-py ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-38cw6bp7/mujoco-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-16hw79yh-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    Compiling /tmp/pip-build-38cw6bp7/mujoco-py/mujoco_py/cymj.pyx because it changed.
    [1/1] Cythonizing /tmp/pip-build-38cw6bp7/mujoco-py/mujoco_py/cymj.pyx
    running build_ext
    building 'mujoco_py.cymj' extension
    creating /tmp/pip-build-38cw6bp7/mujoco-py/mujoco_py/generated/_pyxbld_LinuxExtensionBuilder
    creating /tmp/pip-build-38cw6bp7/mujoco-py/mujoco_py/generated/_pyxbld_LinuxExtensionBuilder/temp.linux-x86_64-3.6
    creating /tmp/pip-build-38cw6bp7/mujoco-py/mujoco_py/generated/_pyxbld_LinuxExtensionBuilder/temp.linux-x86_64-3.6/tmp
    creating /tmp/pip-build-38cw6bp7/mujoco-py/mujoco_py/generated/_pyxbld_LinuxExtensionBuilder/temp.linux-x86_64-3.6/tmp/pip-build-38cw6bp7
    creating /tmp/pip-build-38cw6bp7/mujoco-py/mujoco_py/generated/_pyxbld_LinuxExtensionBuilder/temp.linux-x86_64-3.6/tmp/pip-build-38cw6bp7/mujoco-py
    creating /tmp/pip-build-38cw6bp7/mujoco-py/mujoco_py/generated/_pyxbld_LinuxExtensionBuilder/temp.linux-x86_64-3.6/tmp/pip-build-38cw6bp7/mujoco-py/mujoco_py
    creating /tmp/pip-build-38cw6bp7/mujoco-py/mujoco_py/generated/_pyxbld_LinuxExtensionBuilder/temp.linux-x86_64-3.6/tmp/pip-build-38cw6bp7/mujoco-py/mujoco_py/gl
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fdebug-prefix-map=/build/python3.6-sXpGnM/python3.6-3.6.3=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Imujoco_py -I/tmp/pip-build-38cw6bp7/mujoco-py/mujoco_py -I/home/yang/.mujoco/mjpro150/include -I/home/yang/.local/lib/python3.6/site-packages/numpy/core/include -I/tmp/pip-build-38cw6bp7/mujoco-py/mujoco_py/vendor/egl -I/usr/include/python3.6m -c /tmp/pip-build-38cw6bp7/mujoco-py/mujoco_py/cymj.c -o /tmp/pip-build-38cw6bp7/mujoco-py/mujoco_py/generated/_pyxbld_LinuxExtensionBuilder/temp.linux-x86_64-3.6/tmp/pip-build-38cw6bp7/mujoco-py/mujoco_py/cymj.o -fopenmp -w
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fdebug-prefix-map=/build/python3.6-sXpGnM/python3.6-3.6.3=. -specs=/usr/share/dpkg/no-pie-compile.specs -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Imujoco_py -I/tmp/pip-build-38cw6bp7/mujoco-py/mujoco_py -I/home/yang/.mujoco/mjpro150/include -I/home/yang/.local/lib/python3.6/site-packages/numpy/core/include -I/tmp/pip-build-38cw6bp7/mujoco-py/mujoco_py/vendor/egl -I/usr/include/python3.6m -c /tmp/pip-build-38cw6bp7/mujoco-py/mujoco_py/gl/eglshim.c -o /tmp/pip-build-38cw6bp7/mujoco-py/mujoco_py/generated/_pyxbld_LinuxExtensionBuilder/temp.linux-x86_64-3.6/tmp/pip-build-38cw6bp7/mujoco-py/mujoco_py/gl/eglshim.o -fopenmp -w
    /tmp/pip-build-38cw6bp7/mujoco-py/mujoco_py/gl/eglshim.c:4:10: fatal error: GL/glew.h: No such file or directory
     #include <GL/glew.h>
              ^~~~~~~~~~~
    compilation terminated.
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-38cw6bp7/mujoco-py/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-16hw79yh-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-38cw6bp7/mujoco-py/

**Comment by Hi-Ryan** [comment]
I still have the simillar error too.

**Comment by motiwari** [comment]
Seems like a problem due to upgrading to Mojave: https://github.com/openai/mujoco-py/issues/53 and https://stackoverflow.com/questions/52509602/cant-compile-c-program-on-a-mac-after-upgrade-to-mojave

**Comment by xiaotingbiggirl** [comment]
I create a virtual environment in anaconda3. when i install gym, it reminds me that i need to install mujoco. then i installed mujoco successful, and i can use command”./simulate ../model/humanoid.xml” to use mujoco.
But when i enter the virtual environment to install gym again, it shows:
![image](https://user-images.githubusercontent.com/37876929/94240782-5d84cf80-ff46-11ea-877c-0590c322f583.jpg)
![image](https://user-images.githubusercontent.com/37876929/94240922-8c9b4100-ff46-11ea-9402-80855c765dd6.jpg)


what should i do, i wanna cry.

**Comment by xiaotingbiggirl** [comment]
and i can use mojo o, but i haven’t installed mujoco-pay. because when i installed it, it appears the same error: you are appear to be missing Mujoco.
![image](https://user-images.githubusercontent.com/37876929/94241288-0d5a3d00-ff47-11ea-8a24-8804e43cabdf.jpg)
