### ISSUE TITLE
number of actions of gym.MultiDiscrete

### ISSUE THREAD

**Issue by Lcressot** [openai/gym#921]
Hi,
It would be good to be able to get the total number of actions that can be performed in a gym.MultiDiscrete space, and also a mapping between an action index (between 0 and num_actions) and the tuple version of this action in the MultiDiscrete space.
I needed that for my own environment, and I made it but the solution is not the nicest way to do it. The best way would be to update the gym.Space class with a property num_actions returning this number and also a property actions_mapping returning the mapping.

**Comment by AvisekNaug** [comment]
@matthiasplappert Is there any fix for this problem yet?

**Comment by nerzadler** [comment]
@AvisekNaug you can create your own environnment wrapper class that does the work

**Comment by AvisekNaug** [comment]
@nerzadler, in fact, I did the same after giving it some thought. Since my multi discrete action space only needed 0s and 1s, and I had an actions space spanning 4 dimensions, I created a space.Discrete(16) action space and the env.step  method in my environment had a wrapper mapping the discrete action from decimal to binary using some simple code

**Comment by AbdulAlkurdi** [comment]
I struggled with this for a while but then I figured out how to do this.
Let's say I have a environment with a discrete action space:
'env.action_space.n' returns 1 integer which is size of that discrete space.  
 
In case the action space used is Multidiscrete, use the following:
'env.action_space.nvec' which returns an array of size of each integer.

**Comment by christopherhesse** [comment]
Thanks for answering this @AbdulAlkurdi!

**Comment by BharatBaweja** [comment]
Getting error while implementing qlearning. Its always giving error while sending new state to qlearning formula. Already checked all the dimensions but still getting "index 252 is out of bounds for axis 0 with size 240"
