### ISSUE TITLE
Velocity/torque control for Fetch environment

### ISSUE THREAD

**Issue by xli4217** [openai/gym#925]
Hi, it looks like the current Fetch environments use end-effector position control. I was wondering if it's possible to modify it for joint velocity or torque control. If so where should I start. Thanks

**Comment by st99315** [comment]
I have the same question.

**Comment by WuXinyang2012** [comment]
same questions. Just want to know how to use the joint velocity/angles rather than directly the position of the gripper to control the robot.

**Comment by Alonso94** [comment]
Hi, I have faced the same problem;
For me, modifying the step function works fine:
`    def step(self, action):
        qpos = {
            'robot0:shoulder_pan_joint': action[0],
            'robot0:shoulder_lift_joint': action[1],
            'robot0:upperarm_roll_joint': action[2],
            'robot0:elbow_flex_joint': action[3]
        }
        for name, value in qpos.items():
            self.env.sim.data.set_joint_qpos(name, value)
        self.env.sim.forward()
        ob=self.env._get_obs()
        return ob['achieved_goal']`

**Comment by kosta-jo** [comment]
@wangcongrobot Can you add a more detailed guide in step by step manner?

**Comment by kosta-jo** [comment]
@xli4217 Have you find the solution? If yes, can you share it?

**Comment by jkterry1** [comment]
PR #2762 is about to be merged, introducing V4 MuJoCo environments using new bindings and a dramatically newer version of the engine. If this issue still persists with the V4 ones, please create a new issue for it.
