### ISSUE TITLE
Argument error in env.render()

### ISSUE THREAD

**Issue by chennakeshava1998** [openai/gym#928]
I was working through the gym tutorial https://gym.openai.com/docs/. But I ran into an error after executing env.render() function. This function executed once properly, but I am not able to execute once more. I understood that after done=True, we need to perform env.reset().  But I wanted to know if there are any other reasons because the error message specifically mentions 'Argument Error'. I ran this code in Jupyter Notebook
Here is the code: (I am not able to show the indentation with markdown, but my code is properly indented)

`import gym`
`env.reset()`
`for _ in range(1000):`
`    env.render()`
`    env.step(env.action_space.sample()) # taking a random action from the possible set of actions`

---------------------------------------------------------------------------
ArgumentError                             Traceback (most recent call last)
<ipython-input-5-24825dd27544> in <module>()
      1 for _ in range(1000):
----> 2     env.render()
      3     env.step(env.action_space.sample()) # taking a random action from the possible set of actions

/usr/local/lib/python3.5/dist-packages/gym/core.py in render(self, mode, close)
    148             elif mode not in modes:
    149                 raise error.UnsupportedMode('Unsupported rendering mode: {}. (Supported modes for {}: {})'.format(mode, self, modes))
--> 150         return self._render(mode=mode, close=close)
    151 
    152     def close(self):

/usr/local/lib/python3.5/dist-packages/gym/core.py in _render(self, mode, close)
    284 
    285     def _render(self, mode='human', close=False):
--> 286         return self.env.render(mode, close)
    287 
    288     def _close(self):

/usr/local/lib/python3.5/dist-packages/gym/core.py in render(self, mode, close)
    148             elif mode not in modes:
    149                 raise error.UnsupportedMode('Unsupported rendering mode: {}. (Supported modes for {}: {})'.format(mode, self, modes))
--> 150         return self._render(mode=mode, close=close)
    151 
    152     def close(self):

/usr/local/lib/python3.5/dist-packages/gym/envs/classic_control/cartpole.py in _render(self, mode, close)
    144         self.poletrans.set_rotation(-x[2])
    145 
--> 146         return self.viewer.render(return_rgb_array = mode=='rgb_array')

/usr/local/lib/python3.5/dist-packages/gym/envs/classic_control/rendering.py in render(self, return_rgb_array)
     82         self.window.clear()
     83         self.window.switch_to()
---> 84         self.window.dispatch_events()
     85         self.transform.enable()
     86         for geom in self.geoms:

/usr/local/lib/python3.5/dist-packages/pyglet/window/xlib/__init__.py in dispatch_events(self)
    873         # Check for the events specific to this window
    874         while xlib.XCheckWindowEvent(_x_display, _window,
--> 875                                      0x1ffffff, byref(e)):
    876             # Key events are filtered by the xlib window event
    877             # handler so they get a shot at the prefiltered event.

ArgumentError: argument 2: <class 'TypeError'>: wrong type

**Comment by jleni** [comment]
At least in my case, it was because the window was previously closed:

From pyglet docs (https://pyglet.readthedocs.io/en/pyglet-1.2-maintenance/api/pyglet/window/pyglet.window.Window.html#pyglet.window.Window.close)

> After closing the window, the GL context will be invalid. The window instance cannot be reused once closed (see also set_visible).

**Comment by christopherhesse** [comment]
Thanks for answering this @jleni!

**Comment by cduguet** [comment]
So the workaround would be to create a new env?

**Comment by ay1011** [comment]
# Create an environment again solves the problem for me
env = gym.make('MountainCar-v0')
