### ISSUE TITLE
NoSuchDisplayException: Cannot connect to "None"

### ISSUE THREAD

**Issue by Arkoprabho** [openai/gym#936]
Hi,
New to gym. I have a nvidia-docker container with cntk installed, and wish to use reinforcement learning algorithms on some gym environments.
I started up the container by following the instructions [here](https://blog.jessfraz.com/post/docker-containers-on-the-desktop/), installed `apt install python-opengl` and tried to render a simple simulation as follows
```
import gym
gym.make('Pong-v0').render()
```

On doing this i am greeted with the error message 

`NoSuchDisplayException: Cannot connect to "None"`

Can someone direct me in how to use nvidia docker containers to run gym environments.

**Comment by MuLx10** [comment]
try this [link](https://stackoverflow.com/questions/40195740/how-to-run-openai-gym-render-over-a-server)

**Comment by christopherhesse** [comment]
Thanks for answering this @MuLx10!  As the link describes you need to run an X11 server on linux in order to get rendering to work, at least until `pyglet` supports EGL rendering: https://bitbucket.org/pyglet/pyglet/issues/219/egl-support-headless-rendering

**Comment by soerendip** [comment]
I am running it in WSL on windows. Same error. I am running an X11 server. I think I need to set the display first.

**Comment by soerendip** [comment]
Yep, this did the trick:

    export DISPLAY=localhost:0.0

**Comment by kunalJa** [comment]
> 
> 
> Yep, this did the trick:
> 
> ```
> export DISPLAY=localhost:0.0 
> ```

I had to replace localhost with the actual private IP 192.168.1.111:0.0

**Comment by shifabanu** [comment]
I also faced the same issue. I was doing it on Colab and Jupyter Notebook. I got the same errors.

Then I tried to run it on PyCharm and it worked!

**Comment by burgauss** [comment]
I also starting with Gym and I just try this code in jupyter and it worked:
import matplotlib.pyplot as plt
%matplotlib inline
from IPython import display

import gym
env = gym.make('Mountincar-v0')
env.reset()
for _ in range(1000):
    env.render()
    env.step(env.action_space.sample()) # take a random action
env.close()

**Comment by matwilso** [comment]
This worked for me:
```
export DISPLAY=':1'
```

**Comment by kenblu24** [comment]
I experienced this error after switching from a WSL 1 Ubuntu install to WSL 2. I installed `apt install python-opengl` and re-installed XMing and chose the "No Access Control" option when using XLaunch. In particular, this answer helped me a lot:
https://stackoverflow.com/questions/61110603/how-to-set-up-working-x11-forwarding-on-wsl2

**Comment by arthur801031** [comment]
This worked for me:

```
export DISPLAY=:0.0
```
