### ISSUE TITLE
Card game for Gym : Reward Shaping

### ISSUE THREAD

**Issue by benelot** [openai/gym#937]
I am working on a card game for gym and currently I ask myself how to shape the reward function for it. One round of the game consists of each player picking a card from its hand, whereas not every card can be played depending on the card which has been played by one of the players before. For every set of played cards, there is a total order such that the player with the highest card wins the round.  
In the situation in which cards are rejected I want to give the agent some reward.

In case of an invalid card, it is hard to say if that card is any nearer to one of the valid cards than any other. Also the agent should learn that this card is not playable at this point. 

For completeness, the agent gets a discrete observation of everything it can remember of the game (its own cards, cards played in current round, cards played in past rounds, game mode (defines the total order of cards)). Then it should play a discrete action which either is a game mode in the beginning or a card during the round. Then it either gets a reward because its card got rejected or it gets a reward based on whether it wins the round or not. The game accounts a certain amount of points for a won round depending on the constellation of played cards in that round.

My question is how to shape the rewards for card rejection and for winning a round. Any ideas? Positive or negative?

In case any more details are required, just ask for them.

**Comment by mvrozanti** [comment]
@benelot any progress on this? I just made a gym environment for a regional card game (imperfect information) and I'm struggling to find the best algorithms for this kind of task.

**Comment by benelot** [comment]
Yes, I tried different variants of rewards and came to the following conclusions:
-Learning the rules of the game by punishing the agent for wrong cards: NOT a good idea, since it is probably not what you want it to learn (you want it to learn to play the game well). Implementing a sub-loop which checks if the card is valid and punish internally if not did not lead to good results.
-Positive reward for winning the games and rounds: This is great, since this is really what you want it to learn. That is even what Sutton and Barto mention in their book. Do not shape the reward too much, since you should not tell the agent how to win, but that winning is good.
-Dealing with card game rules like a filter for valid cards: This is what turned out to be the best option. Implement the agent to give you a discrete probability distribution over all possible cards. Then you implement a filter that drops all cards that are invalid in the situation at hand. The agent then only has to learn to maximize the probability to play the best valid card. It does not have to learn to suppress invalid cards. This is much easier to learn. You can imagine the valid cards filter like a second part of the neural network which suppresses invalid answers if you care about biological plausibility.

**Comment by mvrozanti** [comment]
@benelot thank you for your response. I was doing precisely the contrary, I was allowing for invalid actions and rewarding them negatively. Will definitely try to tweak it!

**Comment by benelot** [comment]
@mvrozanti That way it takes really a lot of time for the agent to learn the game's rules. In case you find another solution, I would be happy to hear about it :)
