### ISSUE TITLE
Possible ways to replicate a env.

### ISSUE THREAD

**Issue by YuhangSong** [openai/gym#939]
In my research, I need to replicate a env object at current step. And then run the copies of the env object separately.

I have tried ```copy.deepcopy()``` and ```pickle.dumps()```, but it does not seems to work as expected. I am wondering if above methods cannot really copy the env object, maybe something at the bottom level of the env object is not copied as expected?

Many thanks, the OpenAI gym is really pushing forward the exciting AI research.

**Comment by mpSchrader** [comment]
I don't know which environment you are using if it is an environment, which wraps C/C++ code, such as Atari. You might wanna have a look at [ezpickle](https://github.com/openai/gym/blob/master/gym/utils/ezpickle.py). With ezpickle you should be able to replicate the states of these environments.

**Comment by YuhangSong** [comment]
Thank you so much for the reply.

I am using Atari, which is created by, say ```gym.make('AssaulNoFrameskip-v4')```. Should I look into ezpickle?

Many thanks!

**Comment by mpSchrader** [comment]
Yes, I would recommend it.
________________________________

**Comment by YuhangSong** [comment]
Hi, can you be more specific on how should I do it? It seems that I should make my Atari environment inherit the ```ezpickle```, then apply ```pickle``` & ```unpickle``` to it? But how can I do it?

**Comment by mpSchrader** [comment]
Sorry for the misunderstanding. Atari already implements ezpickle. [Code](https://github.com/openai/gym/blob/master/gym/envs/atari/atari_env.py)

You should be able to clone the state by using the following methods: clone_state,
restore_state, clone_full_state, restore_full_state

I hope this helps.
________________________________

**Comment by YuhangSong** [comment]
Thanks a lot, that helps a lot. 

But another small question came up, I use a lot of ```Wrapper```, how can I call these methods after using a Wrapper like:
```
class NoopResetEnv(gym.Wrapper):
    def __init__(self, env, noop_max=30):
        """Sample initial states by taking random number of no-ops on reset.
        No-op is assumed to be action 0.
        """
        gym.Wrapper.__init__(self, env)
        self.noop_max = noop_max
        self.override_num_noops = None
        self.noop_action = 0
        assert env.unwrapped.get_action_meanings()[0] == 'NOOP'

    def _reset(self, **kwargs):
        """ Do no-op action for a number of steps in [1, noop_max]."""
        self.env.reset(**kwargs)
        if self.override_num_noops is not None:
            noops = self.override_num_noops
        else:
            noops = self.unwrapped.np_random.randint(1, self.noop_max + 1) #pylint: disable=E1101
        assert noops > 0
        obs = None
        for _ in range(noops):
            obs, _, done, _ = self.env.step(self.noop_action)
            if done:
                obs = self.env.reset(**kwargs)
        return obs
```
And I wrap my_env with:
```
env = NoopResetEnv(env, noop_max=30)
```

I tried
```
my_env.env.clone_state()
```
It shows:
```
AttributeError: 'TimeLimit' object has no attribute 'clone_state'
```

But if I remove ```env = NoopResetEnv(env, noop_max=30)```, ```my_env.env.clone_state()``` works.

**Comment by mpSchrader** [comment]
You might wanna have a look at `self.unwrapped` from the [wrappers](https://github.com/openai/gym/tree/master/gym/wrappers), this allows you to access the inner environment.

**Comment by fuxianh** [comment]
Hi, bro. Have you succeed in replicating an env object and then run the copies of the env object separately?
@YuhangSong

**Comment by christopherhesse** [comment]
Thanks for all the help @mpSchrader!  As has been pointed out, you can look at `env.unwrapped. clone_full_state()` and `env.unwrapped.restore_full_state()` to get/set state for ALE environments.

**Comment by QasimWani** [comment]
in case anyone needs any help, this worked for me:
```python
import deepcopy

copied_agent = deepcopy(env.unwrapped)
```
