### ISSUE TITLE
Bug in viewer_setup function. In humanoid training camera keeps going away every timestep.

### ISSUE THREAD

**Issue by JoyChopra1298** [openai/gym#940]
In humanoid training camera keeps going away every timestep? The cause of this is the line set self.viewer.cam.lookat[2] += .8 in viewer_setup() in mujoco environment humanoid. What is the reason to  to do this? I found that because of this the viewer keeps getting zoomed out in every iteration. Setting it to 0 solves this problem.

**Comment by silverjoda** [comment]
Same issue in Hopper and several other envs.

**Comment by JoyChopra1298** [comment]
@pzhokhov could you look into this? Like is there some reason for doing this or just a bug?

**Comment by pzhokhov** [comment]
so looks like the camera moves away not every timestep, but rather every env.reset(). 
here's a PR fixing it: https://github.com/openai/gym/pull/1174
