### ISSUE TITLE
occasional exception when resetting the environment

### ISSUE THREAD

**Issue by yakticus** [openai/gym#95]
Symptom is an exception while resetting the environment during monitoring:

```  
File "/Users/julie/github/gym/gym/core.py", line 102, in reset
    self.monitor._after_reset(observation)
  File "/Users/julie/github/gym/gym/monitoring/monitor.py", line 250, in _after_reset
    self.video_recorder.capture_frame()
  File "/Users/julie/github/gym/gym/monitoring/video_recorder.py", line 105, in capture_frame
    frame = self.env.render(mode=render_mode)
  File "/Users/julie/github/gym/gym/core.py", line 153, in render
    return self._render(mode=mode, close=close)
  File "/Users/julie/github/gym/gym/envs/classic_control/cartpole.py", line 132, in _render
    return self.viewer.get_array()
  File "/Users/julie/github/gym/gym/envs/classic_control/rendering.py", line 102, in get_array
    arr = arr.reshape(self.height, self.width, 4)
ValueError: total size of new array must be unchanged
```

Unfortunately I don't have exact steps to reproduce as it seems to happen sporadically when using the CartPole-V0 environment (I haven't tried others). Will give more details as they are uncovered.

If it helps, information about my python environment is attached. 

[pythonenv.txt](https://github.com/openai/gym/files/262094/pythonenv.txt)

**Comment by tlbtlbtlb** [comment]
Puzzling. Could you try replacing the arr.reshape with
```
    try:
        arr = arr.reshape(self.height, self.width, 4)
    except:
        print arr.shape, self.height, self.width
        raise
```
to see what shape it has?

Does your Mac have a Retina screen?

**Comment by yakticus** [comment]
This is what I get for `arr.shape, self.height, self.width`:

`(84,) 400 600`

**Comment by yakticus** [comment]
some additional context that's worth mentioning - I wrote a quick & dirty wrapper API for the gym so that I could use it from non-Python code. Could the error arise by having the `env` be a global thing that is re-used more than once?  

https://gist.github.com/yakticus/de3639c23675a4f6e05b54e5faef56d4

**Comment by yakticus** [comment]
> Does your Mac have a Retina screen?
yes

**Comment by JKCooper2** [comment]
When you say env is being reused in that do you mean that monitor is being started and closed multiple times? When an env in created a monitor is created along with it which is given a unique monitor id (which is selected using a global variable and a lock). When monitor.close is run it removes the monitor from the monitors dictionary which can cause issues when you try and restart it

Try adding `env = gym.make(envname)` just before line 20 of your wrapper so that each time you call monitor(state=on) the monitor it's doing it with a fresh environment (and a usable monitor)

**Comment by yakticus** [comment]
I wasn't aware of the coupling between environment and monitor. Creating a new environment for each monitor seems to have addressed the problem. On a related note, Is there already a place in the repo or website carved out to create more in-depth documentation about the APIs and architecture of the gym? If not, I could start something under docs/api.md so that others don't make the same mistake I did.

**Comment by JKCooper2** [comment]
Not currently, although it has been discussed as to how best to document the code so people are aware of what's going on. I think they want to remain very flexible with anything that's done while the beta is running and not make any decisions before they have enough information.Maybe bring this up in chat and seeing if they're happy with an api.md file as a starting point.

**Comment by gdb** [comment]
Very happy with an api.md file. And yes, not quite ready to double down on another documentation source yet, though I'm sure as we add more of these doc files we'll figure out what we need over time. Thanks!
