### ISSUE TITLE
How to add an Atari game?

### ISSUE THREAD

**Issue by ArjonaMedina** [openai/gym#954]
How can I add an additional atari game?

**Comment by unixpickle** [comment]
I'd recommend using our newer [retro](https://github.com/openai/retro) project for this. Retro has a special tool that makes it possible to integrate new games from various Retro gaming consoles (including Atari2600).

You might also want to look at [atari-py](https://github.com/openai/atari-py), which is where the Atari environments in gym come from. However, retro is definitely a better, more general solution.
