### ISSUE TITLE
add fedora install notes

### ISSUE THREAD

**Issue by mariusa** [openai/gym#956]
Please add these in README, took me a while to figure out:

```
# Fedora install, using bullet 
dnf install openmpi-devel python3-devel 
echo 'export PATH=$PATH:/usr/lib64/openmpi/bin/' >> /etc/profile
export PATH=$PATH:/usr/lib64/openmpi/bin/
which mpiexec

pip3 install mpi4py 

pip3 install pybullet tensorflow gym baselines

git clone https://github.com/bulletphysics/bullet3

cd bullet3/examples/pybullet/gym/pybullet_envs/examples/
python3 simpleHumanoidGymEnvTest.py
```

**Comment by christopherhesse** [comment]
Thanks for the suggestion, but I don't think gym requires any of these dependencies, this sounds like it should be in a separate guide for how to setup pybullet.  Does that sound reasonable?

**Comment by mariusa** [comment]
From user's point of view, I'd find these notes best in gym's README, in a section similar to Ubuntu. Not sure which exactly are strictly pybullet deps.
As you see, other 2 users found these useful. Your call.

**Comment by christopherhesse** [comment]
Since these don't seem to be gym-specific dependencies, I'd prefer these were in the documentation for the things that actually have those.  Thanks for the suggestion though!

**Comment by AshlyLobo** [comment]
I didn't test for other environments but Classic Controls worked with this install script,
`dnf -y install mesa-libGLU-devel mesa-libGL-devel mesa-libOSMesa-devel mesa-libGLw mesa-libGLw-devel zlib zlib-devel curl patchelf swig xorg-x11-server-Xvfb

dnf -y install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
dnf -y install ffmpeg

pip3 install gym`
![Uploading Screenshot from 2021-09-05 07-00-29.png…]()

Sorry for my messed up screenshot

**Comment by AshlyLobo** [comment]
I didn't test this for every environment but it worked for Classic Controls, it should theoretically work for other environments as well

```
dnf -y install mesa-libGLU-devel mesa-libGL-devel mesa-libOSMesa-devel mesa-libGLw mesa-libGLw-devel zlib zlib-devel curl patchelf swig xorg-x11-server-Xvfb

dnf -y install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm
dnf -y install ffmpeg

pip3 install gym
```

![Screenshot from 2021-09-05 07-00-29](https://user-images.githubusercontent.com/39672386/132112164-1d8c3f22-89e4-4219-8f0b-6b042e3567c8.png)

Sorry for my messed up screenshot

**Comment by AshlyLobo** [comment]
Note: The installation of environments should be done according to ["gym/docs/environments.md"](https://github.com/openai/gym/blob/master/docs/environments.md)
