### ISSUE TITLE
Build error by running "pip install -e .[all]"

### ISSUE THREAD

**Issue by lbbc1117** [openai/gym#96]
I got some error msg like:
`Failed building wheel for pachi-py`
and
`ld: targeted OS version does not support use of thread local variables in _fast_srandom for architecture x86_64
  clang: error: linker command failed with exit code 1 (use -v to see invocation)
  error: command 'g++' failed with exit status 1`

I do have cmake installed:
`cmake version 3.5.1`

pip version is 8.0.2

OS version is Mac OS X 10.9.5

**Comment by lbbc1117** [comment]
It turns out swig was missed.
After running `brew install swig`, every thing works.

**Comment by gdb** [comment]
Cool!

**Comment by yanilkr** [comment]
Same error. Ran brew install swig did not fix it.

cmake version 3.5.2

pip version 8.1.2

OS version Mac OSX 10.11.5

xcode command line tools is installed and upto date.
