### ISSUE TITLE
MultiDiscrete space bounds

### ISSUE THREAD

**Issue by bzier** [openai/gym#961]
There were significant changes in PR #836 to the MultiDiscrete space.

The initialization previously allowed for individual min/max ranges which were inclusive. Now the initialization takes in an exclusive upper bound and assumes a minimum of 0. Calls to `.sample()` will be within the range of `[0, n)` for each discrete value. I'm not sure whether the inclusive -> exclusive change was intentional or not. However, the change that was made in PR #923 does not maintain the same space as a result.

Also, despite the fact that the `.sample()` call provides a minimum of 0, there is actually no longer support for a lower bound for each discrete value. Calling `.contains()` now allows for negative values (which should not be valid). Depending on overflow of the specified `dtype`, this essentially means anywhere from `[-inf, n)` will report as belonging to the space via the `.contains()` method. This seems incorrect.

Please let me know if these are expected differences in the 'breaking changes' PR, or not... and/or if you need any additional info from me. Thanks.

#### Old behavior:
```python
# gym 0.7.4
from gym import spaces

md = spaces.MultiDiscrete([ [0,4], [0,1], [0,1] ])
for i in range(10):
  md.sample()

md.contains([4, 1, 1]) # True
md.contains([-1, 0, 0]) # False
```
#### New behavior:
```python
# gym 0.10.4
import numpy as np
from gym import spaces

md = spaces.MultiDiscrete([ 4, 1, 1 ])
for i in range(10):
  md.sample()

md.contains(np.array([4, 1, 1], dtype=np.int32)) # False
md.contains(np.array([-1, 0, 0], dtype=np.int32)) # True
```

**Comment by bzier** [comment]
With more recent changes (#1136), the `contains()` method is fixed to not allow for all negative values. However, there are several other issues. The data type of the space is hard-coded as `np.int8`, limiting the range of any given discrete value from -128 to 127. However, you are able to pass anything in as `nvec`, for example `[160, 160, 2, 2, 2]`. The `contains()` method will happily tell you that `[159, 0, 0, 0, 0]` is valid as it is checking for positive values less than `nvec`. But the `sample()` method randomly selects from `nvec` and casts as `self.dtype` resulting in overflow and wrapping to negative values (e.g. `[-97, 0, 0, 0, 0]`), which wouldn't be valid according to `contains()`. Presumably anything that is sampled from the space using `sample()` should be valid according to the same space's `contains()` method.

The change from inclusive to exclusive bounds (mentioned in my original issue) is still present as well. This may have been intentional.

I originally came across these breaking changes due to one of the users of my custom environment encountering the error 'nvec should be a 1d array (or list) of ints' when working with a newer version of gym than I had previously tested ([link](https://github.com/bzier/gym-mupen64plus/issues/40) to that issue). Now #1149 has removed that assertion, so the code now 'works' with the newer gym library. However, the behavior is significantly different and in no way comparable to what was there before. Instead of failing with the assertion error, things will proceed but the actions taken in the environment are not necessarily what they should be.

Prior to #836, there was a large comment with a description and some example usages, which was removed. Some of the other spaces include example usages as well. With the change in functionality and expected behavior, I think at least one example usage would be helpful.

@joschu @pzhokhov Can either of you provide some info here? Am I missing something obvious? I understand that this was intended to clean up things and that there were intentional breaking changes. However, I think some of my observations show that this broke more than just the interface (e.g. provide single exclusive upper bound instead of inclusive low/high). I think there are issues here that result in incorrect/inappropriate behavior inside the class (e.g. `sample()` and `contains()` disagree) and loss of previous functionality (e.g. hard-coded data type, no more negative values).

Let me know if I should provide some sample scripts to demonstrate these issues, or if there's anything else I can provide. Thanks.

**Comment by pzhokhov** [comment]
Hi @bzier ! 
Let me try to go through the points you raised one at a time :) 

1) inclusive vs exclusive bounds - I think the change is intentional. I understand that it is a breaking change, but the change from limits to number of states would have been breaking anyways; from point of view of logic number of states is a cleaner way - I suspect that's why the change has been made. 

2) bounds vs maximal allowed value for an int8 - very good point, this is something that needs to be fixed. I suspect a good solution is to replace int8 with uint32; and add an extra check into `contains()` method.

3) removed assertion `nvec should be a 1d array or list` - that is an intentional change to be able to have samples with more than one dimension... If points 1) and 2) were not an issue, 3) by itself should not break anything. 

4) examples of usage - I agree; thanks for pointing it out. We are generally trying to improve docs in the gym (slow but a steady effort); if you feel like adding those, a PR would be very welcome. 

Hope this helps, and will fix 2) shortly!

**Comment by christopherhesse** [comment]
Was this issue resolved?

**Comment by pzhokhov** [comment]
unless @bzier objects, I think we can mark this as closed. There are still not that many examples of usage (discussion bullet 4), there is only a docstring in gym/spaces/multidiscrete.py), but I think we need a separate issue for documentation / examples overhaul.

**Comment by bzier** [comment]
Yeah it's been a while since I have looked at this, or worked with this stuff, but I believe the problems were addressed. Obviously better documentation is always possible, but if the problems themselves were taken care of, I'm happy calling this closed.
