### ISSUE TITLE
Why the CartPole problem is considered solved at 195 instead of 200?

### ISSUE THREAD

**Issue by GitYiheng** [openai/gym#964]
Could anyone point me to the original paper?

**Comment by christopherhesse** [comment]
This is the original paper: https://ieeexplore.ieee.org/abstract/document/6313077

I believe that the 195 is arbitrary though, the max is 200 I think so if your mean performance was 199.999, it would not count as solved, you would have to get 100% of all episodes during the evaluation period (if you're using the training curve to evaluate then it might be hard to do that).
