### ISSUE TITLE
How to modify the game MsPacman-v0?

### ISSUE THREAD

**Issue by ling-pan** [openai/gym#970]
Hi,

I am working on the game MsPacman-v0.

I wonder where to find the source code for this game so I can modify the behavior.

It seems that the reward can be obtained only from the step function.

Is there a way to modify it?

Thanks.

**Comment by EugenHotaj** [comment]
IIUC Atari games use the [ALE](https://github.com/mgbellemare/Arcade-Learning-Environment), which is built on top of an Atari Emulator. The emulator runs actual Atari bytecode so you can't just find the "source" of MsPacman game.

I suppose you could create a "homebrew" version of MsPacman and get it to run on ALE but this will be a very tedious/long process.

**Comment by christopherhesse** [comment]
The source code is not available, so you'll need to implement a clone of the game as a custom environment to be able to modify it :/
