### ISSUE TITLE
In mujoco such as Hopper-v2 what are the actions and what are the observations

### ISSUE THREAD

**Issue by bzdlity** [openai/gym#971]
Can someone figure this out?
I'm not sure what 'qvel' means, thanks

**Comment by christopherhesse** [comment]
You can see the observations here: https://github.com/openai/gym/blob/master/gym/envs/mujoco/hopper.py#L25

The actions control these actuators here: https://github.com/openai/gym/blob/master/gym/envs/mujoco/assets/hopper.xml#L35

To match up bodies with parts of qpos/qvel from observations, you can use `env.unwrapped.sim.model.get_joint_qpos_addr('<body name>')`
