### ISSUE TITLE
Is it possible to make the humanoid swim?

### ISSUE THREAD

**Issue by lisayan** [openai/gym#973]
I've copied humanoid.xml and humanoid.py, but added a few changes:
density=5000
viscosity=0.1
gear=300 for all motors (increases moment, which results in more force?)
stiffness=300 for all joints (it adds more force?)
gravity=disable

I have also added a target, and changed the reward function to equal the negative distance from the target to center-of-mass.
It seems as if through 70,000 episodes, the humanoid cannot move closer to the target, which makes me suspect it may not be able to swim? However, the swimmer is also a skinny model and seems to be able to swim. 

Do you have any suggestions on how I could tweak my parameters, or explanation of the impact of changing parameters if I am wrong in using them?

**Comment by christopherhesse** [comment]
You'll want to check the mujoco docs for more information about how the physics engine works: http://www.mujoco.org/book/
