### ISSUE TITLE
Getting “No standard config is available” on google collaboratory

### ISSUE THREAD

**Issue by uhotspot4** [openai/gym#979]
Getting “No standard config is available” on google collaboratory when running gym retro.
I am using Xvbf as the server in the background.

.....
/usr/local/lib/python3.6/dist-packages/pyglet/window/xlib/__init__.py in __init__(self, *args, **kwargs)
    164                     self._event_handlers[message] = func
    165 
--> 166         super(XlibWindow, self).__init__(*args, **kwargs)
    167 
    168         global _can_detect_autorepeat

/usr/local/lib/python3.6/dist-packages/pyglet/window/__init__.py in __init__(self, width, height, caption, resizable, style, fullscreen, visible, vsync, display, screen, config, context, mode)
    515                     pass
    516             if not config:
--> 517                 raise NoSuchConfigException('No standard config is available.')
    518 
    519         if not config.is_complete():

NoSuchConfigException: No standard config is available.

**Comment by christopherhesse** [comment]
This sounds like a gym-retro bug, could you file it over there?  Gym-retro doesn't require xvfb though, so it's not clear to me why you are running it here.
