### ISSUE TITLE
can openai be installed on windows 10?

### ISSUE THREAD

**Issue by ciaptainmilkman** [openai/gym#982]
i can't seem to figure out how to install the openai library on windows 10 maybe it is impossible but i am going to ask in here anyway :D

**Comment by Den5** [comment]
@ciaptainmilkman I don't believe it is supported on Windows at all, without installing some kind of environment, VM.   Whats the protocol on Github, do we create and issue and hope somebody does the work to fix it?  Its beyond my skillset.  I am sure we are not the only windows users hoping for support.

**Comment by Den5** [comment]
one option:
https://medium.com/@8B_EC/how-to-setup-openai-universe-in-windows-using-docker-aa6409163848

**Comment by ciaptainmilkman** [comment]
thanks 👌

2018-04-08 16:48 GMT+02:00 Den15 <notifications@github.com>:

**Comment by stofte** [comment]
It's certainly possible both to get OpenAI running in both WSL and in regular Windows. For the latter, I strongly recommend Anaconda for obtaining platform specific binaries.

If you choose to "non-standard" (docker, wsl, etc) keep in mind that GPU access may be unavailable for that environment. You should consider this strongly as it's a significant feature.

**Comment by NaderNazemi** [comment]
can you show the step by step installation on windows 10 ?

**Comment by eliaperantoni** [comment]
A simple `pip install gym` seems to be working for me

**Comment by BirdeeChen** [comment]
> A simple `pip install gym` seems to be working for me

it's the minimal version of gym, not complete

**Comment by Migdalin** [comment]
Here are some instructions from another thread.  (https://github.com/openai/gym/issues/11)  Caveat:  I haven't tried these, as installing via pip has allowed me to run the tutorials I'm following, which makes me happy.  I got to say, though:  RL is hard enough to come up to speed on by itself.  Environments that don't support either Windows or Apple (and I've seen one that doesn't support Linux or Android either, only Ubuntu):  that's harsh.  One more, entirely unnecessary, hurdle to overcome.

> @MaxOSmith Thank you for nice tutorial to enable gym work on Windows! I succeeded to run gym on my Windows PC (bash on Windows/Python 3.5.2). `pip install` also works fine, below is my setup procedure.
> 
> * install [`vcXsrv`](https://sourceforge.net/projects/vcxsrv/) on Windows
> * run bash on Windows
> * install [all dependencies](https://github.com/openai/gym/#installing-everything)
> * `pip install gym`
> * `pip install 'gym[atari]'`
> * invoke `vcXsrv` Window (I recommend to reboot PC before it)
> * run `export DISPLAY=:0`
> * run below script, Invaders works fine.
> 
> ```python
> import gym
> 
> 
> if __name__ == "__main__":
>     env = gym.make("SpaceInvaders-v0")
>     env.reset()
>     for _ in range(1000):
>         env.render()
>         env.step(env.action_space.sample())
> ```
> 
> ![Invaders](https://camo.githubusercontent.com/b02c6352e3d903ad742c7c0950e37adf2424444b/68747470733a2f2f7062732e7477696d672e636f6d2f6d656469612f43734e6d6c5237554d41414b4b6f562e6a7067)

**Comment by christopherhesse** [comment]
To answer the original question, it looks like `pip install gym` works fine on Windows 10.  Some of the environments do not support windows 10 though, if anyone wants to open individual issues for those (on the repos for the packages that don't support windows 10, e.g. atari_py) that would be fine.
