### ISSUE TITLE
How to specify custom keys to action mapping

### ISSUE THREAD

**Issue by ignacioalvmar** [openai/gym#983]
This is not so much an issue as a lack of clarity.
I was trying to enable CarRacing-v0 to be played by user using custom keys I thought I could have this using utils.play like this:

```
import gym
from gym.utils.play import *

play(gym.make("CarRacing-v0"))
```
It works fine for the atari environments but in this case I got 
```
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
<ipython-input-3-080385c697d2> in <module>()
      8 # play.keys_to_action = KEYWORD_TO_KEY
      9 
---> 10 play(gym.make("CarRacing-v0"))
     11 
     12 # mapping of keys

~/Documents/openai/gym/gym/utils/play.py in play(env, transpose, fps, zoom, callback, keys_to_action)
     92         else:
     93             assert False, env.spec.id + " does not have explicit key to action mapping, " + \
---> 94                           "please specify one manually"
     95     relevant_keys = set(sum(map(list, keys_to_action.keys()),[]))
     96 

AssertionError: CarRacing-v0 does not have explicit key to action mapping, please specify one manually
```
So I was wondering how to do this custom action mapping?
The comment in the play code says it's a mapping keys_to_action: dict: tuple(int) -> int

The atari_env does it this way:
```
KEYWORD_TO_KEY = {
            'UP':      ord('w'),
            'DOWN':    ord('s'),
            'LEFT':    ord('a'),
            'RIGHT':   ord('d'),
            'FIRE':    ord(' '),
        }
```
I know the car_racing script does this by capturing the keys pressed into an 3 element array and passing that value to env.step. So I tried a similar way here:
```
KEYWORD_TO_KEY = {'STEER':ord('a'),'GAS':ord('w'),'BREAK':ord('s')}
play.keys_to_action = KEYWORD_TO_KEY
```
It didn't work. I know steer is wrong but I thought I'd get at least the vehicle turning one way. 
Then I checked remapping the keywords to a custom combination on one of the Atari games. 
The game worked but the key mapping was the original not my modification. 
 
Can you throw some more clarity to how to do this custom key mapping?

**Comment by jamiesalter** [comment]
I ran into the same thing, but found the answer in the comments of `car_racing.py`

To play the car racing game using your keyboard, you can run `python gym/envs/box2d/car_racing.py`

Alternatively, you can copy the code at the bottom of `car_racing.py` and run:
```
from gym.envs.box2d import car_racing
from pyglet.window import key

a = np.array([0.0, 0.0, 0.0])

def key_press(k, mod):
    global restart
    if k == 0xff0d: restart = True
    if k == key.LEFT:  a[0] = -1.0
    if k == key.RIGHT: a[0] = +1.0
    if k == key.UP:    a[1] = +1.0
    if k == key.DOWN:  a[2] = +0.8  # set 1.0 for wheels to block to zero rotation

def key_release(k, mod):
    if k == key.LEFT and a[0] == -1.0: a[0] = 0
    if k == key.RIGHT and a[0] == +1.0: a[0] = 0
    if k == key.UP:    a[1] = 0
    if k == key.DOWN:  a[2] = 0

env = car_racing.CarRacing()
env.render()
record_video = False
if record_video:
    env.monitor.start('/tmp/video-test', force=True)
env.viewer.window.on_key_press = key_press
env.viewer.window.on_key_release = key_release
while True:
    env.reset()
    total_reward = 0.0
    steps = 0
    restart = False
    while True:
        s, r, done, info = env.step(a)
        total_reward += r
        if steps % 200 == 0 or done:
            print("\naction " + str(["{:+0.2f}".format(x) for x in a]))
            print("step {} total_reward {:+0.2f}".format(steps, total_reward))
            # import matplotlib.pyplot as plt
            # plt.imshow(s)
            # plt.savefig("test.jpeg")
        steps += 1
        if not record_video:  # Faster, but you can as well call env.render() every time to play full window.
            env.render()
        if done or restart: break
env.close()
```

I couldn't get `play(gym.make("CarRacing-v0"), keys_to_action=KEYWORD_TO_KEY)` to work.

As for custom key mappings, you can see what key mappings are being used by default (for Pong for example) by running:
```
from gym.utils.play import *

env = gym.make("Pong-v0")
if hasattr(env, 'get_keys_to_action'):
    keys_to_action = env.get_keys_to_action()
elif hasattr(env.unwrapped, 'get_keys_to_action'):
    keys_to_action = env.unwrapped.get_keys_to_action()
print(keys_to_action)
```

The output is `{(32, 97): 5, (32,): 1, (97,): 3, (32, 100): 4, (): 0, (100,): 2}`
So I think the format of your `KEYWORD_TO_KEY` needs to be `dict: tuple(int) -> int `.  So something like:
```
{
    (ord('w'), ): 1,
    (ord('d'), ): 2,
    ...
}
```    
    
You can get a list of action meanings at the bottom of the `atari_env.py` module.

I'm absolutely new to this so apologies if some of this isn't correct!

**Comment by christopherhesse** [comment]
Thanks for answering this @jamiesalter!  It seems like the `play()` function needs some improvements.  There's an example interactive script in `retro` here: https://github.com/openai/retro/blob/master/retro/examples/interactive.py that might be useful to generalize for all gym environments that support `render='rgb_array'` although in this case it would produce two windows and they might not share OpenGL contexts correctly.

**Comment by winutta** [comment]
Try reordering the order of the keys and values in the dictionary to match the format in @jamiesalter 's answer. You can also alter the play function in the module to have a selected value for when no keys are pressed (it is set to 0 by default, and has to be an element of the action_space). 👍
