### ISSUE TITLE
spaces.Dict is being packed into arrays

### ISSUE THREAD

**Issue by bklebel** [openai/gym#984]
I am using a dict-space for my custom gym environment (see  https://gist.github.com/bklebel/913d8f155e6ed23f8a35fba989c70140). 
Currently this only works with keras with slight changes to keras, as somehow, during the process of gym-agent communication, gym packs the dict into some array, so keras can not reccognize it as dict, and throws an error, as my model expects a dict. 

I could not find the place where the observation is packed into an additional array, so I changed my keras code to unpack it manually, in case it encounters a dict in an array with one single object (see [https://github.com/keras-team/keras/pull/9886](url)). 
Would it be possible to hand the raw dict, without a sort of 'array-wrapper', to the respective agent? The change in keras just clutters the code, while the problem develops somewhere else...

**Comment by mitar** [comment]
I think that automatic packing into an array is a good thing, no?

**Comment by bklebel** [comment]
I am sorry I left this open, I found the "error" - I am using keras-rl, and have a Pull-request there to fix this, since my problem originated directly there: 
https://github.com/keras-rl/keras-rl/pull/195

There seems to be nothing wrong with gym on this part.
