### ISSUE TITLE
BreakoutDeterministic-v4 no 'game over' status

### ISSUE THREAD

**Issue by corner200** [openai/gym#985]
Hello,

if I run s, r, d_now, _ = env.step(a) and lose the game I receive never True for d.

Sincerely

**Comment by christopherhesse** [comment]
I could not reproduce this:

```
import gym

env = gym.make("BreakoutDeterministic-v4")

observation = env.reset()
while True:
    action = env.action_space.sample()
    observation, reward, done, info = env.step(action)
    if done:
        print('done')
        break
env.close()
```

```
python test.py  
done
```

**Comment by OrionChang** [comment]
> I could not reproduce this:
> 
> ```
> import gym
> 
> env = gym.make("BreakoutDeterministic-v4")
> 
> observation = env.reset()
> while True:
>     action = env.action_space.sample()
>     observation, reward, done, info = env.step(action)
>     if done:
>         print('done')
>         break
> env.close()
> ```
> 
> ```
> python test.py  
> done
> ```

I recently encountered the same problem and managed to reproduce it.

When the agent takes action 0, 2, 3 rather than 1, the game will not end properly and keep hanging there, even if the agent has lost.

Replacing the uniform action sampling with a given action, say 3, could reproduce the problem.

**Comment by fatcatZF** [comment]
> > I could not reproduce this:
> > ```
> > import gym
> > 
> > env = gym.make("BreakoutDeterministic-v4")
> > 
> > observation = env.reset()
> > while True:
> >     action = env.action_space.sample()
> >     observation, reward, done, info = env.step(action)
> >     if done:
> >         print('done')
> >         break
> > env.close()
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > python test.py  
> > done
> > ```
> 
> I recently encountered the same problem and managed to reproduce it.
> 
> When the agent takes action 0, 2, 3 rather than 1, the game will not end properly and keep hanging there, even if the agent has lost.
> 
> Replacing the uniform action sampling with a given action, say 3, could reproduce the problem.

Thanks for your explanation. Is there any way to avoid the "No Game Over" problem?

**Comment by fatcatZF** [comment]
I found that the reason is that the agent has five lives, which can be accessed by `next_frame, reward, is_done, info = env.step(action)`, `info["ale.lives"]`. The agent will lose one life at the end of each episode. Since the agent is still alive, the end of the episode does not mean the end of the game. You have to re-fire at the end of episode, i.e., `env.step(1)`.
